### ISSUE TITLE
Does UndoLogManager.undo exist bug?

### ISSUE THREAD

**Issue by zhenjing** [seata/seata#1001]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Version: 0.5.1

**Problem 1:**
line 200:

>             } catch (SQLIntegrityConstraintViolationException e) {
>                LOGGER.info("xid {} branch {}, undo_log inserted, retry rollback",
>                    xid, branchId);
>            }

If insertUndoLogWithGlobalFinished fail because of dup key,  should this place throw TransactionException(BranchRollbackFailed_Retriable)?

**Problem 2:**
line 204:
>  catch (Throwable e) {
                if (conn != null) {
                    try {
                        conn.rollback();
                    } catch (SQLException rollbackEx) {
                        LOGGER.warn("Failed to close JDBC resource while undo ... ", rollbackEx);
                    }
                }
                throw new TransactionException(BranchRollbackFailed_Retriable, String.format("%s/%s", branchId, xid),
                    e);

            }

If rollback undo log always fail, who is response of stoping to retry rollback ?

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zhenjing** [comment]
> Problem1：insert undolog to prevent local transactions from continuing
Maybe business thread insert undo log before undo thread.

> Problem2：always retry
I don't know if exec undo rollback will error, maybe limit the retry time will be better.

**Comment by zhenjing** [comment]
@slievrly
When undo flow insert a record to rollback transaction, and the key is dup(other thread insert the recored), a exception will be throw.  

This means normal undo flow and insertUndoLogWithGlobalFinished have the same Exception(SQLIntegrityConstraintViolationException). 

For Problem1: retry rollback should be ok.
For Problem2: retry rollback should be limit the retry time.

**Comment by CoffeeLatte007** [comment]
> @slievrly
> When undo flow insert a record to rollback transaction, and the key is dup(other thread insert the recored), a exception will be throw.
> 
> This means normal undo flow and insertUndoLogWithGlobalFinished have the same Exception(SQLIntegrityConstraintViolationException).
> 
> For Problem1: retry rollback should be ok.
> For Problem2: retry rollback should be limit the retry time.

limit the retry time there is no guarantee of eventual consistency ，in the future we will privode web console to manual stop

**Comment by zhenjing** [comment]
@CoffeeLatte007 
UndoLogManager line 200 should throw exception, so server will retry rollback.

`        } catch (SQLIntegrityConstraintViolationException e) {
           LOGGER.info("xid {} branch {}, undo_log inserted, retry rollback",
               xid, branchId);
       }`

**Comment by zhenjing** [comment]
[#861](https://github.com/seata/seata/issues/861) limit the retry times.

**Comment by CoffeeLatte007** [comment]
> @CoffeeLatte007
> UndoLogManager line 200 should throw exception, so server will retry rollback.
> 
> For Problem2, retry always is ok.
> Now the retryRollbacking.scheduleAtFixedRate is 5ms, the server retry too frequently.
> Maybe the retry internal should be exponential increase, such as 5ms - 10ms - 20ms ...

yes
