### ISSUE TITLE
It is recommended to overwrite the registry.conf file with the application.yml (or Apollo) configuration item.

### ISSUE THREAD

**Issue by heshengyahuai** [seata/seata#1005]
## Why you need it?

我们项目有用Apollo， 但发现seata的注册方式和eureka地址必需在 registry.conf 文件指定。

现在的配置方式很让人痛苦！

@lovepoem

**Comment by xingfudeshi** [comment]
@heshengyahuai Seata supports Apollo as the configuration center as well.

**Comment by slievrly** [comment]
`yml ` should be considered.

**Comment by heshengyahuai** [comment]
@xingfudeshi ， @slievrly  在registry.conf文件里，可以配置apollo代替file.conf， 但是registry.conf文件本身不能被yml或apollo代替。如下，eureka地址如果写在yml，是不能生效的：
`
registry {
  type = "eureka"
  eureka {
    serviceUrl = "http://39.98.170.203:2110/eureka"
    application = "default"
    weight = "1"
  }
}
`

**Comment by heshengyahuai** [comment]
@xingfudeshi ， @slievrly 在registry.conf文件里，可以配置apollo代替file.conf， 但是registry.conf文件本身不能被yml或apollo代替。如下，eureka地址如果写在yml，是不能生效的：

```
registry {
  type = "eureka"

  eureka {
    serviceUrl = "http://172.10.0.31:8761/eureka"
    application = "default"
    weight = "1"
  }
}
```

**Comment by xingfudeshi** [comment]
.properties file should also be.considered.

**Comment by heshengyahuai** [comment]
期待下一个版本见到

**Comment by xingfudeshi** [comment]
are you using spring-boot?

**Comment by heshengyahuai** [comment]
是的，用 spring-boot。

**Comment by pigxcloud** [comment]
@xingfudeshi   hi,Is there a plan to support?  If I use Spring Cloud Alibaba  ，Need to maintain two sets of configurations

**Comment by xingfudeshi** [comment]
@pigxcloud Hey,There is already a PR that adds configuration isolation feature.#1075

**Comment by xingfudeshi** [comment]
@pigcloud For configuration files that support the yaml and property formats, we'll provide a seata-spring-boot-starter to do that.

**Comment by pigxcloud** [comment]
@xingfudeshi   nice. **seata-spring-boot-starter**  is better than   configuration isolation feature #1075 ，
