### ISSUE TITLE
A way to config the  threadpool

### ISSUE THREAD

**Issue by nikyotensai** [seata/seata#1008]
## Why you need it?
When I try to translate Chinese into English,I found `FrameworkErrorCode.ThreadPoolFull`,its message is not perfectly right.The threadpool isn't belong to netty,and I cannot find a way  to config the threadpool unless you change the code.So I need a way to config it.

## How it could be?
I can change the  config of  threadpool.

**Comment by slievrly** [comment]
ThreadPoolFull： netty channelRead -->user threadpool

**Comment by Moriadry** [comment]
Have you consider using disruptor as one of the implement of threadpool?
