### ISSUE TITLE
UndoLogParser should use SPI 

### ISSUE THREAD

**Issue by CoffeeLatte007** [seata/seata#1010]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
we can provide more UndoLogParser not only json such as protobuf,kyro

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by xingfudeshi** [comment]
Are you gonna do this feature?

**Comment by CoffeeLatte007** [comment]
> Are you gonna do this feature?

ok, if you want to do it ,you can do this

**Comment by xingfudeshi** [comment]
> > Are you gonna do this feature?
> 
> ok, if you want to do it ,you can do this

i will do another feature.

**Comment by CoffeeLatte007** [comment]
ok  i can do it

**Comment by ujjboy** [comment]
@CoffeeLatte007 Do you start it?

I want to change the method definition  of `UndoLogParser` for better extensibility.

`String encode(BranchUndoLog branchUndoLog)` -> `byte[] encode(BranchUndoLog branchUndoLog)`
`BranchUndoLog decode(String data)` -> `BranchUndoLog decode(byte[] bytes)`

**Comment by CoffeeLatte007** [comment]
> @CoffeeLatte007 Do you start it?
> 
> I want to change the method definition of `UndoLogParser` for better extensibility.
> 
> `String encode(BranchUndoLog branchUndoLog)` -> `byte[] encode(BranchUndoLog branchUndoLog)`
> `BranchUndoLog decode(String data)` -> `BranchUndoLog decode(byte[] bytes)`

no , u can do it
