### ISSUE TITLE
How to install develop branch to local maven and update seata-samples seata jar version?

### ISSUE THREAD

**Issue by zhenjing** [seata/seata#1015]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1. git pull develop
2. make install
3. update seata-samples seata.version -> 0.6.0-SNAPSHOT

However, the seata-sample build fail, and found the jar pom.xml don't have right version.
How to build develop branch and update seata-samples jar version?

><parent>
    <groupId>io.seata</groupId>
    <artifactId>seata-parent</artifactId>
    <version>${revision}</version>
  </parent>

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zhenjing** [comment]
**./mvnw clean install -Dmaven.test.skip=true**

**Comment by xingfudeshi** [comment]
change the version in sample's pom.xml.
try the following script in the develop branch of Seata:
mvn clean install -DskipTests -U
