### ISSUE TITLE
How to release seata?

### ISSUE THREAD

**Issue by xuzhiyiYoh** [seata/seata#1020]
1. command line:`mvn clean install -Dmaven.test.skip=true`

profile: release-seata

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (make-assembly) on project seata-distribution: Failed to create assembly: Error adding file to archive: /Users/letian/IdeaProjects/seata/distribution/NOTICE-BIN -> [Help 1]
```

Seems like file **NOTICE-BIN absent.**

![image](https://user-images.githubusercontent.com/48389485/57584494-96b5ce80-750e-11e9-889f-5f2598b19119.png)

2. Remove NOTICE and run again, package success.

But jar files in the package seems wrong.

```
tree seata-server-0.6.0-SNAPSHOT 
.
└── seata
    ├── LICENSE
    ├── bin
    │   ├── seata-server.bat
    │   └── seata-server.sh
    ├── conf
    │   ├── file.conf
    │   ├── logback.xml
    │   ├── nacos-config.sh
    │   ├── nacos-config.txt
    │   └── registry.conf
    └── target
        └── seata-server-0.6.0-SNAPSHOT.jar

4 directories, 9 files
```

**Comment by slievrly** [comment]
@xuzhiyiYoh thank you for the problem you found, you can mention a pr to fix this problem.
