### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by wxbty** [seata/seata#103]
Why is there only a checkLock operation in SelectForUpdateExecutor, and other DMLs do not override the doExecute method, but do not have this operation in doExecute in the parent class?
// 为什么只有SelectForUpdateExecutor里有checkLock 操作，而其他DML没有覆盖doExecute方法，父类中的doExecute里却没有这个操作？

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by sharajava** [comment]
DML operations will try to acquire locks. The locking is made when local transaction is about to commit. So there is no locking when executing DML.

But for SELECT FOR UPDATE, the lock checking must be done when executing such SQL to make sure it will not read uncommitted datas.

**Comment by leizhiyuan** [comment]
because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
