### ISSUE TITLE
GlobalTransactionScanner.wrapIfNecessary triggers BeanInstantiationException when find target class of a bean that must be instantiated lazily

### ISSUE THREAD

**Issue by AndyLvVip** [seata/seata#1030]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration': 
Unsatisfied dependency expressed through field 'clientDetailsService'; 
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientDetailsService': 
Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: 
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'scopedTarget.clientDetailsService' defined in org.springframework.security.oauth2.config.annotation.configuration.ClientDetailsServiceConfiguration: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [org.springframework.security.oauth2.provider.ClientDetailsService]: 
Factory method 'clientDetailsService' threw exception; 
nested exception is java.lang.UnsupportedOperationException: Cannot build client services (maybe use inMemory() or jdbc()).

  If there is an exception, please attach the exception trace:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.clientDetailsService' defined in org.springframework.security.oauth2.config.annotation.configuration.ClientDetailsServiceConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.ClientDetailsService]: Factory method 'clientDetailsService' threw exception; nested exception is java.lang.UnsupportedOperationException: Cannot build client services (maybe use inMemory() or jdbc()).
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at io.seata.spring.util.SpringProxyUtils.findTargetClass(SpringProxyUtils.java:45)
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:212)
	... 59 common frames omitted
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. create a bean that mark by @Lazy annotation, throw a exception when instantiating it before lazy instantiation.
2. Trigger GlobalTransactionScanner
3. can not instantiate it.

### Ⅴ. Anything else we need to know?

BeanCreationException occurred in ClientDetailsServiceConfiguration.clientDetailsService Bean which is marked as a Lazy Bean

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows 10
- Others: spring-security-oauth2:2.3.4.RELEASE

**Comment by slievrly** [comment]
@AndyLvVip if I Configured  spring.xml  as `lazy="true" `, can reproduce it?

**Comment by AndyLvVip** [comment]
> 
> 
> @AndyLvVip if I Configured spring.xml as `lazy="true" `, can reproduce it?

@slievrly yes, you can. The key point is that the bean should be instantiated when the first time use it rather than scan it.

**Comment by AndyLvVip** [comment]
![image](https://user-images.githubusercontent.com/34873888/57767050-11fbc800-773b-11e9-8dcd-e81deeeb83ea.png)
e.g. This is a Oauth2 library bean configuration, ClientDetailsService is a bean only can be instantiated after do some configuration in ClientDetailsServiceConfigurer, so if you instantiate it immediately when scanning it, it will raise a exception.

**Comment by xuande** [comment]
I have the same problem. How to solve this problem

**Comment by AndyLvVip** [comment]
> 
> 
> I have the same problem. How to solve this problem

Hello,
The key point of the solution is that: creating the required  bean explicitly

**Comment by xuande** [comment]
> > I have the same problem. How to solve this problem
> 
> Hello,
> The key point of my workaround is as below:
> 
> 1. Create the required  bean explicitly
> 2. Override the default Spring Configuration to avoid creating the lazily instantiated bean.

Thank you for your reply. Remove `@Lazy` like this ?
```
package org.springframework.security.oauth2.config.annotation.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.security.oauth2.config.annotation.builders.ClientDetailsServiceBuilder;
import org.springframework.security.oauth2.config.annotation.configurers.ClientDetailsServiceConfigurer;
import org.springframework.security.oauth2.provider.ClientDetailsService;

/**
 * @author Rob Winch
 * 
 */
@Configuration
public class ClientDetailsServiceConfiguration {

	@SuppressWarnings("rawtypes")
	private ClientDetailsServiceConfigurer configurer = new ClientDetailsServiceConfigurer(
			new ClientDetailsServiceBuilder());

	@Bean
	public ClientDetailsServiceConfigurer clientDetailsServiceConfigurer() {
		return configurer;
	}

	@Bean
	// @Lazy
	@Scope(proxyMode = ScopedProxyMode.INTERFACES)
	public ClientDetailsService clientDetailsService() throws Exception {
		return configurer.and().build();
	}

}
```
After this modification, startup still reported an error. Can you show me your code.

**Comment by AndyLvVip** [comment]
1. Override the Spring Configuration in order to remove the default bean creation
```
package org.springframework.security.oauth2.config.annotation.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.security.oauth2.config.annotation.builders.ClientDetailsServiceBuilder;
import org.springframework.security.oauth2.config.annotation.configurers.ClientDetailsServiceConfigurer;
import org.springframework.security.oauth2.provider.ClientDetailsService;

/**
 * @author Rob Winch
 *
 */
@Configuration
public class ClientDetailsServiceConfiguration {

    @SuppressWarnings("rawtypes")
    private ClientDetailsServiceConfigurer configurer = new ClientDetailsServiceConfigurer(new ClientDetailsServiceBuilder());

    @Bean
    public ClientDetailsServiceConfigurer clientDetailsServiceConfigurer() {
        return configurer;
    }

//    @Bean //remove the bean
    @Lazy
    @Scope(proxyMode=ScopedProxyMode.INTERFACES)
    public ClientDetailsService clientDetailsService() throws Exception {
        return configurer.and().build();
    }

}

```

2. Create the bean explicitly as required:
```
    @Bean
    public ClientDetailsService clientDetailsService(Config config, PasswordEncoder passwordEncoder) {
        return clientId -> {
            BaseClientDetails clientDetails = new BaseClientDetails();
            clientDetails.setClientId(clientId);
            clientDetails.setClientSecret(passwordEncoder.encode(config.getClientSecret()));
            clientDetails.setAuthorizedGrantTypes(Arrays.asList(config.getGrantTypes()));
            clientDetails.setScope(Arrays.asList(config.getScopes()));
            return clientDetails;
        };
    }
```

**Comment by xuande** [comment]
@AndyLvVip Thanks, start success.
