### ISSUE TITLE
The error of all/pom.xml and bom/pom.xml

### ISSUE THREAD

**Issue by lovepoem** [seata/seata#1031]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1).  seata/bom.xml and  seata/all/pom.xml have repeated content 
2).  `<packaging>jar</packaging>` in seata/all/pom.xml is lost 
3)  deploy a snapshot version to verify the kinds of bineries: all in one, bom , common

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
deploy snapshot jar

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lovepoem** [comment]
https://github.com/seata/seata/pull/1023

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/57615837-42aef680-75af-11e9-90cc-9ac46b613243.png)
![image](https://user-images.githubusercontent.com/8758457/57615857-54909980-75af-11e9-8ec9-953054067a77.png)

**Comment by lovepoem** [comment]
close via https://github.com/seata/seata/pull/1032
