### ISSUE TITLE
Rollback Global Transacction not work 

### ISSUE THREAD

**Issue by Kchetin** [seata/seata#1038]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

I load local SpringClould-jpa-seata with a MySQL 8.0 and the commit work fine but the rollback to do the update the same way, i need to install another version of mySql or a need to configurate any properties? Seata work for Oracle ? wirh version?

Thanks a lot.
Regards,
Cristian from Chile

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@Kchetin Oracle is not currently supported, but will be supported soon. I will test about the sample.

**Comment by ygsama** [comment]
Hi, How long will the Fescar take to support Oracle ? 
This will affect our technology selection, such as change the framework or DB.

**Comment by zjinlei** [comment]
supported
