### ISSUE TITLE
Optimize the business logic of the undo method

### ISSUE THREAD

**Issue by ujjboy** [seata/seata#1049]
## How it could be?

When running `AbstractUndoExecutor#executeOn`, There are several optimization logic codes that can be added:

- [x] compare beforeImage and afterImage, If they are equal, then you don't need to execute undo
- [x] execute `dataValidation()`(PS: the method is empty now.), compare current data in the database with destination image, if they are not equal, it means have dirty data, will throw an exception
- [x] Compare current data in the database and the original image, if they are equal, also no need to execute undo
- [ ] Add a switch for this feature.

**Comment by leizhiyuan** [comment]
has this been finished?

**Comment by ujjboy** [comment]
No, last one pr is adding a switch for this feature.
