### ISSUE TITLE
create a new project with seata but rollback does't work

### ISSUE THREAD

**Issue by dawnChen666** [seata/seata#1054]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
i use seata-server(0.5.0) and consulted the seata-samples(springcloud-jpa-seata),i create three new projects（A，B，C） A as business，B,C as order and storage,  A use feignClient to call B，C，and C has a active exception, in theory it should rollback but it does't work, these projects is the same as springcloud-jpa-seata, i don't know why it does't work, please help me。they may have difference that i can't get xid or tx_xid, but i dont know why

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS :win10
- Others: mysql 5.7

**Comment by xingfudeshi** [comment]
can you provider sample which can reproduce this problem?

**Comment by xingfudeshi** [comment]
sample like a ZIP file or we can clone code from github.

**Comment by dawnChen666** [comment]
@xingfudeshi OK Email or other?

**Comment by leizhiyuan** [comment]
> @xingfudeshi I can't send it to your gmail , please give me the way

maybe you can push your code to your public repo？

**Comment by xingfudeshi** [comment]
> @xingfudeshi I can't send it to your gmail , please give me the way

please create a public Repo on github,it will be convenient for both of us.

**Comment by dawnChen666** [comment]
> > @xingfudeshi I can't send it to your gmail , please give me the way
> 
> please create a public Repo on github,it will be convenient for both of us.

this way https://github.com/dawnChen666/seata-demo
use /demo3/rollback to test
there is an active exception in demo2 project, but demo2 is rollbacked and demo1 isn't 
there are some message received in demo3
msg: Receive:MergeResultMessage globalStatus=Rollbacked,ResultCode=Success,Msg=null
please help me, thanks.

**Comment by xingfudeshi** [comment]
ok.i will check.

**Comment by xingfudeshi** [comment]
@dawnChen666 your example has been fixed,you can free to merge the PR.it will make your example work.

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!

**Comment by dawnChen666** [comment]
> I will close this issue,if you have further question about this issue,please comment here.thank you!

i saw that jpa replaces jdbc and druid replaces hikari，and i accept all differences without these two, i try again and it failed again, so this version of seata(0.5.1) does't support jdbcTemplate and hikariCP? or i make mistakes again?

**Comment by xingfudeshi** [comment]
> > I will close this issue,if you have further question about this issue,please comment here.thank you!
> 
> i saw that jpa replaces jdbc and druid replaces hikari，and i accept all differences without these two, i try again and it failed again, so this version of seata(0.5.1) does't support jdbcTemplate and hikariCP? or i make mistakes again?

jdbcTemplate and hikariCP should be supported ,but i don't test yet,you can merge  the PR,then try with them again.

**Comment by dawnChen666** [comment]
@xingfudeshi hey, i got your demo and test it. there are results
env: druid+jdbctemplate result: success
env: hikariCP+jdbcTemplate result: failure

so i think this version does't support hikariCP and there are two question here, first，will the production version support hikariCP，second, if i want use seata now,  the best way is to use druid?

**Comment by xingfudeshi** [comment]
1.hikariCP will be supported.
2.it's better to use druid for now.
