### ISSUE TITLE
Optimize check style

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1055]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Optimize check style

### Ⅱ. Describe what happened

 
![image](https://user-images.githubusercontent.com/8758457/57837408-55b30800-77f5-11e9-96a7-9a66a71e76b6.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lovepoem** [comment]
refer  https://github.com/seata/seata/issues/985
