### ISSUE TITLE
Is there a bug in the rollback of the Update type?

### ISSUE THREAD

**Issue by ynfeng** [seata/seata#1056]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
假设库存为100，A全局事务将库存-1为99,然后A事务记录了beforeImage库存量为100。
B全局事务将库存减为98.
这时A事务回滚，库存被回滚成100了？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by CoffeeLatte007** [comment]
no, because we have globalLock,the transaction b will be blocked

**Comment by leizhiyuan** [comment]
the smallest lock key is primaryKey of a table. so what you described will not happen, you can use some test case to test it.

**Comment by ynfeng** [comment]
@leizhiyuan @CoffeeLatte007 
Ok,thanks for reply.

**Comment by leizhiyuan** [comment]
If you have other questions, you can close this issue, thanks~
