### ISSUE TITLE
Is it easy to use seata with Akka? Thanks.

### ISSUE THREAD

**Issue by Kiddinglife** [seata/seata#1070]

**Comment by xingfudeshi** [comment]
I am not familiar with Akka, but integration of Seata requires the following conditions:
1. XID can be passed through the entire service invocation chain
2. Business-side applications need to add an undo_log table

**Comment by slievrly** [comment]
@Kiddinglife Currently requires the user to manually pass the transaction context

**Comment by xingfudeshi** [comment]
i will close this issue，if you have further question please post here.
