### ISSUE TITLE
Users can set transaction file's saving history time by themselft in the config file.

### ISSUE THREAD

**Issue by zongtanghu** [seata/seata#1073]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
I do some research into the FileTransactionStoreManager class of  seata-server project.In the writeSession method,I think we coud add a configuable variable and users can set transaction file's saving history time by themselft in the config file.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
I think we coud add a configuable variable and users can set transaction file's saving history time by themselft in the config file.So users can config the saving history time by their own business condition.

//-------------------------------------------------------------------------------------------------------
@Override
    public boolean writeSession(LogOperation logOperation, SessionStorable session) {
        writeSessionLock.lock();
        long curFileTrxNum;
        try {
            if (!writeDataFile(new TransactionWriteStore(session, logOperation).encode())) {
                return false;
            }
            lastModifiedTime = System.currentTimeMillis();
            curFileTrxNum = FILE_TRX_NUM.incrementAndGet();
            if (curFileTrxNum % PER_FILE_BLOCK_SIZE == 0 &&
                    (System.currentTimeMillis() - trxStartTimeMills) > MAX_TRX_TIMEOUT_MILLS) {
                return saveHistory();
            }
        } catch (Exception exx) {
            LOGGER.error("writeSession error," + exx.getMessage());
            return false;
        } finally {
            writeSessionLock.unlock();
        }
        flushDisk(curFileTrxNum, currFileChannel);
        return true;
    }
//-------------------------------------------------------------------------------------------------------

**Comment by slievrly** [comment]
@zongtanghu What do you mean by opening this configuration（MAX_TRX_TIMEOUT_MILLS） to the user?
