### ISSUE TITLE
Global transaction rollback failed

### ISSUE THREAD

**Issue by jwrwst** [seata/seata#1079]
调用系统自带的接口方法测试：http://127.0.0.1:8084/purchase/rollback
请求接口时候，调用到手动抛出异常后，可是并没有回滚，库存依旧是扣减了,如下图：

![image](https://user-images.githubusercontent.com/24490695/58068444-f291ee80-7bc3-11e9-8da1-429cdbc665c1.png)

**Comment by slievrly** [comment]
@jwrwst use SCA 0.9.1 version?

**Comment by jwrwst** [comment]
我用得就是github最新得demo源码测试得
地址：https://github.com/seata/seata-samples.git

**Comment by jwrwst** [comment]
<dependency>
    <groupId>io.seata</groupId>
    <artifactId>seata-spring</artifactId>
    <version>0.5.0</version>
</dependency>

**Comment by jwrwst** [comment]
> @jwrwst使用SCA 0.9.1版本？
SCA是什么？
我用得就是github最新得演示源码测试得
地址：https：//github.com/seata/seata-samples.git
seata-spring版本：

io.seata 
seata-spring 
0.5.0

**Comment by slievrly** [comment]
> > @jwrwst使用SCA 0.9.1版本？
> > SCA是什么？
> > 我用得就是github最新得演示源码测试得
> > 地址：https：//github.com/seata/seata-samples.git
> > seata-spring版本：
> 
> io.seata
> seata-spring
> 0.5.0

please use 0.5.2

**Comment by jwrwst** [comment]
有spring-cloud-starter-alibaba-seata 0.9.1.BUILD-SNAPSHOT 测试用例吗

**Comment by xingfudeshi** [comment]
try this:https://github.com/seata/seata-samples/tree/master/springcloud-jpa-seata

**Comment by jwrwst** [comment]
好的，我有空更新再试试，这个里面没有你说的那个包，我看seata更新为6.0了

**Comment by xx1595140265** [comment]
这个 0.9.1.BUILD-SNAPSHOT  版本的spring-cloud-alibaba-seata在哪里下载
