### ISSUE TITLE
springboot + openFeign prompted error when call microservice

### ISSUE THREAD

**Issue by hao373738397hao** [seata/seata#1081]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
springboot + openFeign call microservice Prompt error
## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
[11111.txt](https://github.com/seata/seata/files/3202179/11111.txt)

**Comment by leizhiyuan** [comment]
which seata version do you use？

**Comment by hao373738397hao** [comment]
<dependency>
			<groupId>com.alibaba.fescar</groupId>
			<artifactId>fescar-spring</artifactId>
			<version>0.4.2</version>
		</dependency>

server used develop

**Comment by xingfudeshi** [comment]
please use latest version for both sides.

**Comment by hao373738397hao** [comment]
thanks，demo run success

**Comment by leizhiyuan** [comment]
Ok, If you have no other questions, you can close this issue, thanks.
