### ISSUE TITLE
When Support motan rpc and postgresql database?

### ISSUE THREAD

**Issue by zhangxn8** [seata/seata#1091]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by xingfudeshi** [comment]
#1086

**Comment by xingfudeshi** [comment]
motan has been supported,you can try it now.welcome get feedback us.

**Comment by leizhiyuan** [comment]
see https://github.com/seata/seata/issues/1091
