### ISSUE TITLE
The seata-serve(0.5.2vsersion) service is always automatically down on the Linux server, the frequency of the down is very high.

### ISSUE THREAD

**Issue by sun6hua** [seata/seata#1110]
See seata-server log found: WARN Could not found property transport.shutdown.wait, try to use default value instead.
INFO destroyed rpcServer
INFO 172.31.176.24:46634 to server channel inactive.
INFO 172.31.176.24:48650 to server channel inactive.
INFO 172.31.176.24:46610 to server channel inactive.
INFO remove channel:[id: 0x523c5c2b, L:0.0.0.0/0.0.0.0:8091 ! R:/172.31.176.24:46634]context:RpcContext{applicationId='user', transactionServiceGroup='qp_tx_group', clientId='user :172.31.176.24:46634', channel=[id: 0x523c5c2b, L:0.0.0.0/0.0.0.0:8091 ! R:/172.31.176.24:46634], resourceSets=null}, then the service is down, this The problem is very anxious, eager to recover, thank you

**Comment by slievrly** [comment]
@sun6hua check memory usage.

**Comment by sun6hua** [comment]
It is indeed a memory problem that has now been resolved. Thank you @slievrly
