### ISSUE TITLE
mysql field type is datetime afterRecords not equals currentRecords

### ISSUE THREAD

**Issue by jsbxyyx** [seata/seata#1116]
![image](https://user-images.githubusercontent.com/26616196/58444903-cf6bbf80-812c-11e9-960b-11a2f4470af1.png)

![image](https://user-images.githubusercontent.com/26616196/58444909-d5fa3700-812c-11e9-8263-d79d99c722d3.png)

suggestion: 
You can convert the field value to the field type, then compare

- JDK version : 1.8
- OS : window 7
- Others: mysql5.7

**Comment by leizhiyuan** [comment]
Fix in https://github.com/seata/seata/pull/1090
