### ISSUE TITLE
There are too many identical SessionLifecycleListener`s in GlobalSession

### ISSUE THREAD

**Issue by CandleFlower** [seata/seata#1126]
在GlobalSession中的lifecycleListeners字段中有很多相同实例的监听器，导致每次更新或删除时都会操作很多遍，考虑是否可以用set代替list

**Comment by xingfudeshi** [comment]
Thanks.Could you submit a PR to improve this?

**Comment by kezhenxu94** [comment]
Hi @xingfudeshi , pull request has been sent to fix this issue, can you take a look when you've got some time, thanks :-)

**Comment by xingfudeshi** [comment]
Thanks.I will do that.
