### ISSUE TITLE
DataCompareUtils#isFieldEquals equals type

### ISSUE THREAD

**Issue by jsbxyyx** [seata/seata#1139]
the isFieldEquals method only compare object (the object must override equals and hashcode)

can compare type:
String, BigDecimal, boolean, byte, short, int, long, float, double, Date, Time, Timestamp, URL

for other type can close validation

JDBC Type | Java Type
-- | --
CHAR | String
VARCHAR | String
LONGVARCHAR | String
NUMERIC | java.math.BigDecimal
DECIMAL | java.math.BigDecimal
BIT | boolean
BOOLEAN | boolean
TINYINT | byte
SMALLINT | short
INTEGER | int
BIGINT | long
REAL | float
FLOAT | double
DOUBLE | double
BINARY | byte[]
VARBINARY | byte[]
LONGVARBINARY | byte[]
DATE | java.sql.Date
TIME | java.sql.Time
TIMESTAMP | java.sql.Timestamp
CLOB | Clob
BLOB | Blob
ARRAY | Array
DISTINCT | mapping of underlying type
STRUCT | Struct
REF | Ref
DATALINK | java.net.URL
JAVA_OBJECT | underlying Java class

**Comment by xingfudeshi** [comment]
Could you submit a PR to improve this?thanks.

**Comment by jsbxyyx** [comment]
other ways to achieve

**Comment by dk-lockdown** [comment]
> other ways to achieve

how this problem solved?i reviewed the code,find just BigDecimal processing has been done,orther types such as BigInteger are still causing bugs

**Comment by jsbxyyx** [comment]
@dk-lockdown you see lastest version
