### ISSUE TITLE
Can't rollback the sql which only update the primary key

### ISSUE THREAD

**Issue by whzprivate** [seata/seata#1143]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
eg: update table1 set id = '1' where id = '2' ;

branchStatus=PhaseTwo_RollbackFailed_Retryable

undoSQL:   UPDATE table1 SET  WHERE id = ?

io.seata.rm.datasource.sql.struct.Row.nonPrimaryKeys(),This method may need to be changed

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
Why do you want to update the primary key?

**Comment by whzprivate** [comment]
I just wrote a test like this

**Comment by xingfudeshi** [comment]
> I just wrote a test like this

Okay. But it's really a problem. Could you try to submit a PR to improve this?

**Comment by whzprivate** [comment]
> > I just wrote a test like this
> 
> Okay. But it's really a problem. Could you try to submit a PR to improve this?

I'll try it in free time
