### ISSUE TITLE
0.6.0: When lockKey longer then branch_table, global lock will not unlock

### ISSUE THREAD

**Issue by zhenjing** [seata/seata#1154]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

When addBranch fail, locker don't unlock normally.

DefaultCore line 76： 
         
>	 try {
>                globalSession.addBranch(branchSession);
>            } catch (RuntimeException ex) {
>                branchSession.unlock();
>                throw new TransactionException(FailedToAddBranch);
>            }

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by romeoblog** [comment]
Please attach the exception trace
