### ISSUE TITLE
init nacos config fail

### ISSUE THREAD

**Issue by YonSite** [seata/seata#1155]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/7650375/58849675-d8750780-86bd-11e9-9517-4c8906165176.png)
![image](https://user-images.githubusercontent.com/7650375/58849682-e32f9c80-86bd-11e9-9e0a-fc0a6508eadc.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
There are spaces in the parameters of the configuration file, just delete the spaces.

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
![image](https://user-images.githubusercontent.com/24457941/58851914-0f9be680-86c7-11e9-8a66-0a2854bcf44f.png)
I tried it just now. It can initialize Nacos normally.Could you please provide more details about this problem.By the way,have you tried the latest version?

**Comment by YonSite** [comment]
### 😆i'm sorry. 0.6.1 don't have this problem. i used 0.6.0.
