### ISSUE TITLE
GlobalTransactional rollbackFor will rollback on unset exception

### ISSUE THREAD

**Issue by zhenjing** [seata/seata#1156]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Set: rollbackFor = {RuntimeException.class}, if throw Exception then Transaction will be rollback. It's not same with spring transaction: only throw RuntimeException will rollback.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by github-ygy** [comment]
I deliberately designed this way，anything that can happen to third-party services we rely on
