### ISSUE TITLE
0.6.0 Error reporting null for transaction group name startup。

### ISSUE THREAD

**Issue by lynk-coder** [seata/seata#1157]
![80984A71-725E-46dc-8819-E6241F1C1579](https://user-images.githubusercontent.com/23651124/58855157-ecc2ff80-86d1-11e9-843a-54c33e315780.png)
When I switched the version to 0.6.0, I found that the transaction group name was null when it was initialized.However, after connecting to the Server, it returned to normal.

The main reason I found was that “DataSourceProxy ”initialized before “GlobalTransactionScanner”.

**Comment by misvcom** [comment]
GlobalTransactionScanner globalTransactionScanner = new GlobalTransactionScanner(applicationId, "【group name】");
file.conf file :  vgroup_mapping.【group name】
** this two group name must the same
