### ISSUE TITLE
global_table table has no record generation

### ISSUE THREAD

**Issue by misvcom** [seata/seata#1163]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Why after entering the  service which add GlobalTransactional  ,but the global_table table has no record generation.

**Comment by slievrly** [comment]
Do you use store.mode=db and lock.mode=db configuration?

**Comment by misvcom** [comment]
yes,store.mode and lock.mode is set to db in server file.conf,but  global_table table is still no record generation

**Comment by misvcom** [comment]
log:
[ DEBUG] [2019-06-05 11:35:59] org.springframework.jdbc.datasource.DataSourceTransactionManager [372]
                - Creating new transaction with name [cn.liheng.user.service.VipEnrollServiceImpl.findVipByCondition]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
[ DEBUG] [2019-06-05 11:35:59] org.springframework.jdbc.datasource.DataSourceTransactionManager [264]
                - Acquired Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@766a49e5] for JDBC transaction
[ DEBUG] [2019-06-05 11:35:59] org.springframework.jdbc.datasource.DataSourceTransactionManager [281]
                - Switching JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@766a49e5] to manual commit

**Comment by misvcom** [comment]
data layer use tk.mybatis

<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper</artifactId>
    <version>4.1.5</version>
</dependency>

**Comment by misvcom** [comment]
now global_table has record,but branch_table and undo_log  is still no record.

**Comment by romeoblog** [comment]
@misvcom After the transaction is completed, the database data is deleted. You can make a breakpoint during the transaction and look at the data in the database.

**Comment by misvcom** [comment]
I have already make breakpoint before sql start and after sql end（during the transaction）。it is just have the global_table record。
