### ISSUE TITLE
add the table sql of undo_log to code 

### ISSUE THREAD

**Issue by leizhiyuan** [seata/seata#1166]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

maybe we should add a undo_log SQL to code .so users can copy it 

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
@leizhiyuan What you mean is to automatically create an undolog table in the database.

**Comment by leizhiyuan** [comment]
provide a sql file to create the table, if it can be created automatically, will be more convenient

because I found there is no sample which shows how to create the table, users only study from the seata-examples. It is not in time sometimes. 

just like this, maybe we will add a column in next seata version  https://github.com/seata/seata-samples/pull/145

**Comment by romeoblog** [comment]
> provide a sql file to create the table, if it can be created automatically, will be more convenient
> 
> ![image](https://user-images.githubusercontent.com/2684384/58878186-3e38b200-8705-11e9-977e-350d6cb8745e.png)
> 
> because I found there is no sample which shows how to create the table, users only study from the seata-examples. It is not in time sometimes.
> 
> just like this, maybe we will add a column in next seata version [seata/seata-samples#145](https://github.com/seata/seata-samples/pull/145)

It is currently being iteratively developed, and you are interested in supplementing this type of document.

**Comment by slievrly** [comment]
In general, the production environment account does not have DDL permissions.We need a document about db cluster.
