### ISSUE TITLE
Transaction cannot be rollback

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1167]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

1.  table ：

CREATE TABLE `test_jackson` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `int_test` bigint(11) DEFAULT NULL,
  `date_test` date DEFAULT NULL,
  `time_test` time DEFAULT NULL,
  `timespan_test` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

2.  jdbcTemplate.update("insert into test_jackson(id,int_test,date_test,time_test,timespan_test) values(1,1234567890,'2019-06-04','12:00:00','2019-06-04 12:12:12')");   rollback ok.

   jdbcTemplate.update("insert into test_jackson values(1,1234567890,'2019-06-04','12:00:00','2019-06-04 12:12:12')") ;   rollback failed.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by dawnChen666** [comment]
this bug has been repaired now ?

**Comment by dawnChen666** [comment]
i use seata of 0.7.1, this bug still exist, is it being repaired now?
