### ISSUE TITLE
Error creating bean with name 'scopedTarget.accessTokenRequest'

### ISSUE THREAD

**Issue by cashZhang27** [seata/seata#1168]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When I use the following dependencies and @EnableOAuth2Client
```xml
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-oauth2</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security.oauth</groupId>
      <artifactId>spring-security-oauth2</artifactId>
      <version>2.3.3.RELEASE</version>
    </dependency>
```
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

![4270FAF3-BD4A-4fe0-BFF1-DE601103B52F](https://user-images.githubusercontent.com/30404342/58884488-1cdec280-8713-11e9-88ae-f1a9c01c355d.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS :
- Others: 
seata：0.6.1
spring-cloud-alibaba-seata：0.9.1.BUILD-SNAPSHOT

**Comment by leizhiyuan** [comment]
how to reproduce the issue？

**Comment by cashZhang27** [comment]
> how to reproduce the issue？

@leizhiyuan For example, Use the following dependencies and @EnableOAuth2Client to start an error in the [seata-samples](https://github.com/seata/seata-samples/tree/master/springcloud-jpa-seata) order application，The picture above the error log can be seen，Sorry, my English is very bad,,,

```xml
 <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-oauth2</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.security.oauth</groupId>
      <artifactId>spring-security-oauth2</artifactId>
      <version>2.3.3.RELEASE</version>
    </dependency>
```

**Comment by xingfudeshi** [comment]
> > how to reproduce the issue？
> 
> @leizhiyuan For example, Use the following dependencies and @EnableOAuth2Client to start an error in the [seata-samples](https://github.com/seata/seata-samples/tree/master/springcloud-jpa-seata) order application，The picture above the error log can be seen，Sorry, my English is very bad,,,
> 
> ```
>  <dependency>
>       <groupId>org.springframework.cloud</groupId>
>       <artifactId>spring-cloud-starter-oauth2</artifactId>
>     </dependency>
>     <dependency>
>       <groupId>org.springframework.security.oauth</groupId>
>       <artifactId>spring-security-oauth2</artifactId>
>       <version>2.3.3.RELEASE</version>
>     </dependency>
> ```

It seems it's not the problem of seata,but like dependency conflicts.

**Comment by xuande** [comment]
I have the same question. Did you solved?

**Comment by cashZhang27** [comment]
@xuande No, I have no idea at all... I am waiting for seata to solve

**Comment by xingfudeshi** [comment]
> @xuande No, I have no idea at all... I am waiting for seata to solve

`import io.seata.rm.datasource.DataSourceProxy;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.security.oauth2.config.annotation.web.configuration.OAuth2ClientConfiguration;



/**
 * @author xingfudeshi@gmail.com
 * @date 2019/06/28
 */
@Configuration
@ConditionalOnBean(DataSourceProxy.class)
@Import(OAuth2ClientConfiguration.class)
public class MyConfiguration {

}
`

**Comment by cashZhang27** [comment]
@xingfudeshi I tested it in a  [seata-samples](https://github.com/seata/seata-samples/tree/master/springcloud-jpa-seata) and it didn't seem to change...Was I misconfigured?
![微信截图_20190629202330](https://user-images.githubusercontent.com/30404342/60384051-eabf4700-9aab-11e9-81ce-292cc28dbd45.png)

**Comment by xingfudeshi** [comment]
Can you pull the latest code of seata,and install the 0.7.0-snapshot at local,then try it again?My testing was passed with it.

**Comment by zhuyoufeng** [comment]
SpringProxyUtils wants to get the Class of the proxy object, but if the scope of the class is web scope, spring cannot get the request, just call getTargetClass will be OK, hope it can help you.

modify the class io.seata.spring.util.SpringProxyUtils as following:
`    
public static Class<?> findTargetClass(Object proxy) throws Exception {
        if (AopUtils.isAopProxy(proxy)) {
            AdvisedSupport advised = getAdvisedSupport(proxy);
            if (AopUtils.isJdkDynamicProxy(proxy)) {
                TargetSource targetSource = advised.getTargetSource();
                // remove 
                // return targetSource instanceof EmptyTargetSource ? getFirstInterfaceByAdvised(advised)
                    : targetSource.getTarget().getClass();
               // add
                return targetSource instanceof EmptyTargetSource ? getFirstInterfaceByAdvised(advised)
                    : targetSource.getTargetClass();
            }
            Object target = advised.getTargetSource().getTarget();
            return findTargetClass(target);
        } else {
            return proxy == null ? null :proxy.getClass();
        }
  }
`
