### ISSUE TITLE
When will postgresql be supported?

### ISSUE THREAD

**Issue by IKangXu** [seata/seata#1170]
When will postgresql be supported?

**Comment by slievrly** [comment]
@kangxukangxu Will be released in version 0.8.

**Comment by SherrillJoyceGit** [comment]
When will the version 0.8 be released?

**Comment by IKangXu** [comment]
> @kangxukangxu Will be released in version 0.8.

Version 0.9 is out, but PostgreSQL is not supported.

When to support PostgreSQL?

**Comment by R-anybbo** [comment]
Will the 1.0 version support PostgreSQL ?

**Comment by IKangXu** [comment]
:tada::tada::tada:  Already supported in version V1.1.0
