### ISSUE TITLE
Global rollback fails when an exception is thrown manually

### ISSUE THREAD

**Issue by lw5946** [seata/seata#1171]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

I use the code in the seata-sample(springboot-dubbo-seata) example
```java
//打开注释测试事务发生异常后，全局回滚功能
if (true) {
    throw new RuntimeException("测试抛异常后，分布式事务回滚！");
}
```
However, no global rollback occurred.
And no other exceptions were thrown during operation.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows 10
- mysql-connector-java: 5.1.31
- org.apache.dubbo: 2.7.1

**Comment by romeoblog** [comment]
@lw5946 Your application may not be registered with the Seata DataSource Proxy. Check if the program has configured the following information:
```
@Primary
@Bean("dataSource")
public DataSourceProxy dataSource(DruidDataSource druidDataSource) {
     return new DataSourceProxy(druidDataSource);
}
```

**Comment by lw5946** [comment]
In the official springboot-dubbo-seata example, account, order and storage all have registered with the Seata Data Source Proxy. The access interface is the business module, which does not register with the Seata Data Source Proxy, but the module does not operate the database.

**Comment by lw5946** [comment]
This issue has been solved in the latest version, so close this issue
