### ISSUE TITLE
add nacos-config.py initialize the nacos configuration

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1172]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

add nacos-config.py initialize the nacos configuration

The function is consistent with nacos-config.sh

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by leizhiyuan** [comment]
in order to use in windows？

**Comment by slievrly** [comment]
Compatible windows is part of it. From the script level, I think it should be compatible with the main scripts of shell and python.
