### ISSUE TITLE
Field case problem in SQL statement

### ISSUE THREAD

**Issue by yangom** [seata/seata#1176]
数据库表不是自增主键，自己写的SQL,insert 语句里主键名称用了大写，在使用SEATA代理数据源的时候，他从数据库表取出的元信息里主键是小写，然后SEATA就判定这是个自增主键表，就会提示数据库需要自增字段

**Comment by xingfudeshi** [comment]
Could you provide more details?like exception traces or some code to reproduce this problem?Thanks.

**Comment by kezhenxu94** [comment]
@yangom I don't think this is a bug if you're using Windows (I'm not sure), in Mac OS (and possibly Linux), the column name is case insensitive, I've tested like this and it works well:

- based on the [seata-samples](http://github.com/seata/seata-samples), make the `storage_tbl` not to auto increment:

```sql
alter table storage_tbl modify column id int(11) not null;
```

- modify `io.seata.samples.dubbo.starter.DubboStorageServiceStarter` and start it:

```java
public class DubboStorageServiceStarter {
    /**
     * 1. Storage service is ready . A seller add 100 storage to a sku: C00321
     *
     * @param args the input arguments
     */
    public static void main(String[] args) {
        ClassPathXmlApplicationContext storageContext = new ClassPathXmlApplicationContext(
            new String[]{"spring/dubbo-storage-service.xml"});
        storageContext.getBean("service");
        JdbcTemplate storageJdbcTemplate = (JdbcTemplate) storageContext.getBean("jdbcTemplate");
        storageJdbcTemplate.update("delete from storage_tbl where commodity_code = 'C00321'");
        storageJdbcTemplate.update("insert into storage_tbl(ID, commODity_code, count) values (200, 'C00321', 100)");
        new ApplicationKeeper(storageContext).keep();
    }
}
```

pay special attention to line `storageJdbcTemplate.update("insert into storage_tbl(ID, commODity_code, count) values (200, 'C00321', 100)");`, it use `ID` instead of `id`, and the sql executes normally.

@yangom if you're not sure whether it's a bug of seata, try to replace the datasource with the original (that doesn't proxied by Seata), and see whether the problem exists or not.

cc @xingfudeshi

**Comment by xingfudeshi** [comment]
> @yangom I don't think this is a bug if you're using Windows (I'm not sure), in Mac OS (and possibly Linux), the column name is case insensitive, I've tested like this and it works well:
> 
> * based on the [seata-samples](https://github.com/seata/seata-samples), make the `storage_tbl` not to auto increment:
> 
> ```sql
> alter table storage_tbl modify column id int(11) not null;
> ```
> 
> * modify `io.seata.samples.dubbo.starter.DubboStorageServiceStarter` and start it:
> 
> ```java
> public class DubboStorageServiceStarter {
>     /**
>      * 1. Storage service is ready . A seller add 100 storage to a sku: C00321
>      *
>      * @param args the input arguments
>      */
>     public static void main(String[] args) {
>         ClassPathXmlApplicationContext storageContext = new ClassPathXmlApplicationContext(
>             new String[]{"spring/dubbo-storage-service.xml"});
>         storageContext.getBean("service");
>         JdbcTemplate storageJdbcTemplate = (JdbcTemplate) storageContext.getBean("jdbcTemplate");
>         storageJdbcTemplate.update("delete from storage_tbl where commodity_code = 'C00321'");
>         storageJdbcTemplate.update("insert into storage_tbl(ID, commODity_code, count) values (200, 'C00321', 100)");
>         new ApplicationKeeper(storageContext).keep();
>     }
> }
> ```
> 
> pay special attention to line `storageJdbcTemplate.update("insert into storage_tbl(ID, commODity_code, count) values (200, 'C00321', 100)");`, it use `ID` instead of `id`, and the sql executes normally.
> 
> @yangom if you're not sure whether it's a bug of seata, try to replace the datasource with the original (that doesn't proxied by Seata), and see whether the problem exists or not.
> 
> cc @xingfudeshi

Good!

**Comment by yangom** [comment]
> @yangom I don't think this is a bug if you're using Windows (I'm not sure), in Mac OS (and possibly Linux), the column name is case insensitive, I've tested like this and it works well:
> 
> * based on the [seata-samples](https://github.com/seata/seata-samples), make the `storage_tbl` not to auto increment:
> 
> ```sql
> alter table storage_tbl modify column id int(11) not null;
> ```
> 
> * modify `io.seata.samples.dubbo.starter.DubboStorageServiceStarter` and start it:
> 
> ```java
> public class DubboStorageServiceStarter {
>     /**
>      * 1. Storage service is ready . A seller add 100 storage to a sku: C00321
>      *
>      * @param args the input arguments
>      */
>     public static void main(String[] args) {
>         ClassPathXmlApplicationContext storageContext = new ClassPathXmlApplicationContext(
>             new String[]{"spring/dubbo-storage-service.xml"});
>         storageContext.getBean("service");
>         JdbcTemplate storageJdbcTemplate = (JdbcTemplate) storageContext.getBean("jdbcTemplate");
>         storageJdbcTemplate.update("delete from storage_tbl where commodity_code = 'C00321'");
>         storageJdbcTemplate.update("insert into storage_tbl(ID, commODity_code, count) values (200, 'C00321', 100)");
>         new ApplicationKeeper(storageContext).keep();
>     }
> }
> ```
> 
> pay special attention to line `storageJdbcTemplate.update("insert into storage_tbl(ID, commODity_code, count) values (200, 'C00321', 100)");`, it use `ID` instead of `id`, and the sql executes normally.
> 
> @yangom if you're not sure whether it's a bug of seata, try to replace the datasource with the original (that doesn't proxied by Seata), and see whether the problem exists or not.
> 
> cc @xingfudeshi

我查看过源码，问题出在TableMeta的containsPK，在这个方法里，直接用从数据库元素据里获得的主键信息和SQL里的字段进行了比对，没有忽略大小写。所以如果库表里是小写，而SQL语句里是大写的时候，就会判断错误，认为插入语句中没有主键字段的值

**Comment by xingfudeshi** [comment]
> containsPK

OK.i will check.

**Comment by xingfudeshi** [comment]
@yangom Hey,i just tested what you described before.but i don't see any problems.Can you provide a example code to reproduce this problem?like a zip file or github repo.

**Comment by xingfudeshi** [comment]
this bug does exist,will be fixed in next release.

**Comment by yangom** [comment]
谢谢，期待早日修复
