### ISSUE TITLE
A situtation will result xid not unbind and global transaction and  line lock leak

### ISSUE THREAD

**Issue by caimofei** [seata/seata#1180]
### Ⅰ. Issue Description
When a globalTransaction is rollbacking. At the time RM receive the rollbackRequest from TC, I shutdown the seate_server(TC). So the RM could roll back phase1 change and delete the undoLogs successfully.
At this time,The TM is still waiting for the reponse for the RollBackRequest to Seata_server,until time out.

### Ⅱ. Describe what happened
1. In this situation,the rollbacking of TM throw an exception,so the unbind method is not invoked,the xid is still in threadLocal. This thread will not  reused because it can not begin new transaction.

2.The globalTransaction died in rollbacking status, and the line lock will never removed even the seate_server is restarted.

### Ⅲ. Describe what you expected to happen
1. for question 1, should unbind the xid whatever the rollbacking request to TC is success.
2. for questtion 2,the schedular should load the rollbacking  as well as retryRollbacking status global transaction.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1.debug the seate_server and a RM service. and mark a breakpoint in AbstractRMHandler where RM service receive the rollbackRequest.Then shutdown the seate_server and resume the RM service.

**Comment by caimofei** [comment]
is there any answer?

**Comment by slievrly** [comment]
Thanks for your feedback. These questions have been solved in the latest version.
