### ISSUE TITLE
What does seata mean?

### ISSUE THREAD

**Issue by RunningSanil** [seata/seata#1183]
What does seata mean?
Why keep fescar logo in home page? 
https://seata.io/en-us/index.html
https://img.alicdn.com/tfs/TB1aiRVJxTpK1RjSZFKXXa2wXXa-246-64.png

**Comment by kezhenxu94** [comment]
@RunningSanil 
![image](https://user-images.githubusercontent.com/15965696/59174966-20949e00-8b86-11e9-9d88-cd08b182b594.png)

**Comment by romeoblog** [comment]
@RunningSanil 
1. Seata is an easy-to-use, high-performance, open source distributed transaction solution.
2. When a project is split into microservices and exist distributed transactions, you can consider using the Seata to solve distributed transaction problems.
