### ISSUE TITLE
sever start fail

### ISSUE THREAD

**Issue by ChinaGDMU** [seata/seata#1185]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
start server fail with message "command line too long ,and syntax is uncorrect"

### Ⅱ. Describe what happened

```
C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>seata-server.bat  -h localhost -p 8091 -m file
输入行太长。
命令语法不正确。
C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows 10
- Others:

**Comment by xingfudeshi** [comment]
This bug has been fixed.ref #1138

**Comment by xingfudeshi** [comment]
> * [ ]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> ### Ⅰ. Issue Description
> start server fail with message "command line too long ,and syntax is uncorrect"
> 
> ### Ⅱ. Describe what happened
> ```
> C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>seata-server.bat  -h localhost -p 8091 -m file
> 输入行太长。
> 命令语法不正确。
> C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>
> ```
> 
> ### Ⅲ. Describe what you expected to happen
> ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> 1. xxx
> 2. xxx
> 3. xxx
> 
> ### Ⅴ. Anything else we need to know?
> ### Ⅵ. Environment:
> * JDK version : 1.8
> * OS : windows 10
> * Others:

please use 0.6.1

**Comment by ChinaGDMU** [comment]
> > * [ ]   I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> > 
> > ### Ⅰ. Issue Description
> > start server fail with message "command line too long ,and syntax is uncorrect"
> > ### Ⅱ. Describe what happened
> > ```
> > C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>seata-server.bat  -h localhost -p 8091 -m file
> > 输入行太长。
> > 命令语法不正确。
> > C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>
> > ```
> > 
> > 
> > ### Ⅲ. Describe what you expected to happen
> > ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> > 
> > 1. xxx
> > 2. xxx
> > 3. xxx
> > 
> > ### Ⅴ. Anything else we need to know?
> > ### Ⅵ. Environment:
> > 
> > * JDK version : 1.8
> > * OS : windows 10
> > * Others:
> 
> please use 0.6.1

ok

**Comment by ChinaGDMU** [comment]
> > * [ ]   I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> > 
> > ### Ⅰ. Issue Description
> > start server fail with message "command line too long ,and syntax is uncorrect"
> > ### Ⅱ. Describe what happened
> > ```
> > C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>seata-server.bat  -h localhost -p 8091 -m file
> > 输入行太长。
> > 命令语法不正确。
> > C:\Users\Administrator\Desktop\seata-server-0.6.0\distribution\bin>
> > ```
> > 
> > 
> > ### Ⅲ. Describe what you expected to happen
> > ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> > 
> > 1. xxx
> > 2. xxx
> > 3. xxx
> > 
> > ### Ⅴ. Anything else we need to know?
> > ### Ⅵ. Environment:
> > 
> > * JDK version : 1.8
> > * OS : windows 10
> > * Others:
> 
> please use 0.6.1

thank you!
