### ISSUE TITLE
Encode error when rollback method throw an exception

### ISSUE THREAD

**Issue by maxiaoguang64** [seata/seata#1191]
![image](https://user-images.githubusercontent.com/6637227/59261499-25ce1780-8c70-11e9-86df-dc1ff6956b06.png)
![image](https://user-images.githubusercontent.com/6637227/59261554-45654000-8c70-11e9-893c-c481a6dc9293.png)
branchStatus is null

**Comment by slievrly** [comment]
@maxiaoguang64 Can you write about how to reproduce it?

**Comment by maxiaoguang64** [comment]
@slievrly  rollback method `throw new RuntimeException();`

**Comment by leizhiyuan** [comment]
which version do you use？
