### ISSUE TITLE
add support for SQL starting with hint

### ISSUE THREAD

**Issue by masterfengj** [seata/seata#120]
## 增加对以hint开始的SQL支持
目前rm-dataresource的实现, 不支持以hint开始的sql,主要涉及到连接代理和UndoLog的处理实现.
比如mycat中间件依赖于sql开头的hint做服务切换,DB路由等,如:
/*!mycat:schema=wz_buss_001*/ SELECT * FROM t_user_info WHERE id=?

**Comment by sharajava** [comment]
It'll be great if you can join us and share your solution on this enhancement.

**Comment by sharajava** [comment]
Your PR is merged into branch at_plugin. I just get your point on this. Can you leave give me an email? I would like to share some ideas on how to support MyCAT. Thanks 👍 

My email: haiqiang.shq@alibaba-inc.com
