### ISSUE TITLE
Insert operation data rollback failed

### ISSUE THREAD

**Issue by xionganyin** [seata/seata#1203]
### Ⅱ. Describe what happened
导致这个问题的原因是insert操作在生成undo_log数据时，beforeImage实际为TableRecords的子类EmptyRecords，该类对象在被序列化时会调用getTableMeta()函数。但是EmptyRecords类的getTableMeta()抛出了异常，导致序列化失败，最终undo_log无法写入。所以在分布式事务回滚时，无法获取到当前分支事务的undo_log，进而导致insert的数据回滚失败。

![E63264FF8B9D28B7BE35D12C0B697B72](https://user-images.githubusercontent.com/4514707/59487738-1c32f280-8eb0-11e9-98bd-b97e7c61c1aa.jpg)

**Comment by xingfudeshi** [comment]
Thanks for reporting.Could you submit a PR to improve this?

**Comment by xingfudeshi** [comment]
> ### Ⅰ. 在分布式事务中，分支事务Insert数据之后，父节点抛出异常导致全局事务回滚时，当前分支事务回滚成功，状态为PhaseTwo_Rollbacked，但是之前插入的数据并没有回滚成功。同时undo_log表中包含一条当前xid、branchid且state=1(GlobalFinished)的数据。
> ### Ⅱ. Describe what happened
> 导致这个问题的原因是insert操作在生成undo_log数据时，beforeImage实际为TableRecords的子类EmptyRecords，该类对象在被序列化时会调用getTableMeta()函数。但是EmptyRecords类的getTableMeta()抛出了异常，导致序列化失败，最终undo_log无法写入。所以在分布式事务回滚时，无法获取到当前分支事务的undo_log，进而导致insert的数据回滚失败。
> 
> ![E63264FF8B9D28B7BE35D12C0B697B72](https://user-images.githubusercontent.com/4514707/59487738-1c32f280-8eb0-11e9-98bd-b97e7c61c1aa.jpg)

Any idea to reproduce this problem?

**Comment by zjinlei** [comment]
Thank you very much
default use jackson
