### ISSUE TITLE
remove third-party GPL/LGPL license dependencies

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1208]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

remove third-party GPL/LGPL license dependencies

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by xingfudeshi** [comment]
Can we set those dependencies as "provided" scope?

**Comment by slievrly** [comment]
> Can we set those dependencies as "provided" scope?

In the case of ensuring that the program functions normally, priority is given to exclusion. After those are excluded, if the function is affected, we will sort it out and see how to solve it.

**Comment by slievrly** [comment]
Find unknown license
     (Unknown license) servlet-api (javax.servlet:servlet-api:2.5 - no url defined)
     (Unknown license) Antlr 3.4 Runtime (org.antlr:antlr-runtime:3.4 - http://www.antlr.org)
     (Unknown license) SLF4J LOG4J-12 Binding (org.slf4j:slf4j-log4j12:1.5.8 - http://www.slf4j.org)
     (Unknown license) servlet-api (javax.servlet:servlet-api:2.5 - no url defined)
     (Unknown license) Antlr 3.4 Runtime (org.antlr:antlr-runtime:3.4 - http://www.antlr.org)
     (Unknown license) servlet-api (javax.servlet:servlet-api:2.5 - no url defined)
     (Unknown license) Antlr 3.4 Runtime (org.antlr:antlr-runtime:3.4 - http://www.antlr.org)
     (Unknown license) servlet-api (javax.servlet:servlet-api:2.5 - no url defined)
     (Unknown license) Antlr 3.4 Runtime (org.antlr:antlr-runtime:3.4 - http://www.antlr.org)
