### ISSUE TITLE
 Property  "env" for registry.conf conflicted with Apollo property "env".

### ISSUE THREAD

**Issue by xianwei** [seata/seata#1209]
## Why you need it?
 Property  name "env" for registry.conf conflicted with Apollo bootsrap property name "env".

## How it could be?
Unique property name,like seata-env.

## Other related information
![image](https://user-images.githubusercontent.com/3487614/59554269-2bf72780-8fd3-11e9-9570-d0f4a540c8ba.png)

**Comment by xingfudeshi** [comment]
Thanks for reporting.i will check.

**Comment by xingfudeshi** [comment]
In fact, the parameters passed in through - D are only valid for the current virtual machine process.
Can you show the full commands?

**Comment by xianwei** [comment]
> In fact, the parameters passed in through - D are only valid for the current virtual machine process.
> Can you show the full commands?

C:\SOFT\Java64\jdk1.8.0_131\bin\java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:53988,suspend=y,server=n -Dmaven.multiModuleProjectDirectory=C:\WORKSPACE\eluyun-parent\eluyun-webserver -Dspring.profiles.active=redis-single -Denv=dev -Didc=profile-sxw -Dapollo.cacheDir=c:\opt\data\ -Dapollo.configService=http://127.0.0.1:8080 "-Dmaven.home=C:\SOFT\Jetbrains\IntelliJ IDEA 2017.1.5\plugins\maven\lib\maven3" -Didea.modules.paths.file=C:\SOFT\Jetbrains\.IntelliJIdea2017.1\system\Maven\idea-projects-state-f5ef8187.properties -Dclassworlds.conf=C:\Users\sxw\AppData\Local\Temp\idea-8701-mvn.conf -Dfile.encoding=UTF-8 -classpath "C:\SOFT\Jetbrains\IntelliJ IDEA 2017.1.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar;C:\SOFT\Jetbrains\IntelliJ IDEA 2017.1.5\lib\idea_rt.jar" org.codehaus.classworlds.Launcher -Didea.version=2017.1.5 -s C:\SOFT\apache-maven-3.3.3\conf\settings.xml clean tomcat7:run -P local

**Comment by xianwei** [comment]
I copied bootstrap cmd from console.

**Comment by xingfudeshi** [comment]
> I copied bootstrap cmd from console.

Please refer the wiki here [https://github.com/seata/seata/wiki/Multi-configuration-Isolation](url)
You can use the another way to configure the configuration environment.
- Use **SEATA_CONFIG_ENV** as the key of environment variable,and it's value will be the name of the environment.[**recommended**]
```shell

e.g.(Linux)

#vi /etc/profile 

export SEATA_CONFIG_ENV=test

:wq

#source /etc/profile
```

**Comment by xianwei** [comment]
> > I copied bootstrap cmd from console.
> 
> Please refer the wiki here [https://github.com/seata/seata/wiki/Multi-configuration-Isolation](url)
> You can use the another way to configure the configuration environment.
> 
> * Use **SEATA_CONFIG_ENV** as the key of environment variable,and it's value will be the name of the environment.[**recommended**]
> 
> ```shell
> e.g.(Linux)
> 
> #vi /etc/profile 
> 
> export SEATA_CONFIG_ENV=test
> 
> :wq
> 
> #source /etc/profile
> ```

Thanks. It's ok in the most situation although the different env in the only server maybe have the same problem. In fact ,we have two envs in the same server for now.Perhaps we should apply for another server : ) .

**Comment by xingfudeshi** [comment]
You can start the seata-server like this
sh seata-server.sh -Denv=test
You may need to specific different port for multiple instances.please see the help options.(seata-server --help)

**Comment by xianwei** [comment]
> You can start the seata-server like this
> sh seata-server.sh -Denv=test
> You may need to specific different port for multiple instances.please see the help options.(seata-server --help)

Sorry, I mean the application env,not seata server env.

**Comment by xingfudeshi** [comment]
> > You can start the seata-server like this
> > sh seata-server.sh -Denv=test
> > You may need to specific different port for multiple instances.please see the help options.(seata-server --help)
> 
> Sorry, I mean the application env,not seata server env.

OK.I got it.I will improve it.

**Comment by xingfudeshi** [comment]
> > You can start the seata-server like this
> > sh seata-server.sh -Denv=test
> > You may need to specific different port for multiple instances.please see the help options.(seata-server --help)
> 
> Sorry, I mean the application env,not seata server env.

I've made a PR to improve this problem.
