### ISSUE TITLE
Zookeeper often reports an error: Error handling event ZkEvent[New session event sent to io.seata.discovery.registry.zk.ZookeeperRegisterServiceImpl$1@3333463a]

### ISSUE THREAD

**Issue by 15168326318** [seata/seata#1234]
Error handling event ZkEvent[New session event sent to io.seata.discovery.registry.zk.ZookeeperRegisterServiceImpl$1@3333463a]
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at io.seata.discovery.registry.zk.ZookeeperRegisterServiceImpl.recover(ZookeeperRegisterServiceImpl.java:257)
	at io.seata.discovery.registry.zk.ZookeeperRegisterServiceImpl.access$000(ZookeeperRegisterServiceImpl.java:49)
	at io.seata.discovery.registry.zk.ZookeeperRegisterServiceImpl$1.handleNewSession(ZookeeperRegisterServiceImpl.java:233)
	at org.I0Itec.zkclient.ZkClient$4.run(ZkClient.java:472)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:71)

**Comment by xingfudeshi** [comment]
Please provide zk's version,seata's version and the procedure to reproduce this problem.

**Comment by 15168326318** [comment]
zk是3.4，seata是0.6.0，几乎每次调用都会报这个错，但事务是成功的。


------------------ 原始邮件 ------------------
发件人: "xingfudeshi"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 下午4:02
收件人: "seata/seata"<seata@noreply.github.com>;
抄送: "龙凤胎，女儿说的"<529315491@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [seata/seata] Zookeeper often reports an error: Error handlingevent ZkEvent[New session event sent toio.seata.discovery.registry.zk.ZookeeperRegisterServiceImpl$1@3333463a](#1234)




Please provide zk's version,seata's version and the procedure to reproduce this problem.

**Comment by xingfudeshi** [comment]
> zk是3.4，seata是0.6.0，几乎每次调用都会报这个错，但事务是成功的。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "xingfudeshi"<notifications@github.com>; 发送时间: 2019年6月25日(星期二) 下午4:02 收件人: "seata/seata"<seata@noreply.github.com>; 抄送: "龙凤胎，女儿说的"<529315491@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [seata/seata] Zookeeper often reports an error: Error handlingevent ZkEvent[New session event sent toio.seata.discovery.registry.zk.ZookeeperRegisterServiceImpl$1@3333463a](#1234) Please provide zk's version,seata's version and the procedure to reproduce this problem. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

OK.A PR has been made to fix this bug.

**Comment by slievrly** [comment]
@xingfudeshi good job.
