### ISSUE TITLE
Is:iss is is:open by the provided example, tested, very easy to use, can this version be applied to production?

### ISSUE THREAD

**Issue by zwmnhao1980** [seata/seata#1241]
is:issue is:open通过提供的example，测试了，非常好用，目前这个版本可以应用生产吗

**Comment by slievrly** [comment]
@zwmnhao1980 Thank you very much for your feedback. What version did you test?

**Comment by zwmnhao1980** [comment]
0.61

**Comment by zwmnhao1980** [comment]
@slievrly 0.6.1版本的

**Comment by xingfudeshi** [comment]
> 0.61

Yes, version 0.6.1 already has the ability for production, but there still are something we're working on it.So, I suggest you wait until after 0.7.0.
