### ISSUE TITLE
ProtostuffUndoLogParser getDefaultContent can not new byte[0]

### ISSUE THREAD

**Issue by jsbxyyx** [seata/seata#1244]
ProtostuffUndoLogParser getDefaultContent can not new byte[0]

call insertUndolog can throws SerialException

![image](https://user-images.githubusercontent.com/26616196/60151439-5769e580-980f-11e9-9d4c-78a5d3f80724.png)

![image](https://user-images.githubusercontent.com/26616196/60151486-82543980-980f-11e9-9df9-cf618e176807.png)

**Comment by ujjboy** [comment]
@jsbxyyx  Can you provide a scenario for the problem to reproduce?

Maybe we no need to insert undo log if the content is null.

**Comment by jsbxyyx** [comment]
![image](https://user-images.githubusercontent.com/26616196/60415705-77821600-9c0e-11e9-8765-01aec353ccd6.png)

when code variable `exists` is false, will insert default content to db

**Comment by jsbxyyx** [comment]
#1848
