### ISSUE TITLE
Looking forward to the new version of seata update(0.6.2)

### ISSUE THREAD

**Issue by sun6hua** [seata/seata#1254]
The seata version is not updated, and now many bugs need to be resolved. Now, using seata (0.6.1) transactions does not roll back, 0.6.0 can still be rolled back, the same code. Looking forward to the new version of seata update

**Comment by slievrly** [comment]
@sun6hua You can feedback how to reproduce this problem, and will release the 0.7.0 version soon.

**Comment by sun6hua** [comment]
OK, thank you
