### ISSUE TITLE
seata集成mybatis或者tkmybatis问题本地事物和全局事务冲突

### ISSUE THREAD

**Issue by Empty66** [seata/seata#1257]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
springboot 2.0
mybatis 3.4.4
seata 0.6.1
1、本地@Transactional事务开启
      mapper.insertSelective(Oblect)可以从Oblect.getId()获取自增id
       单独加上全局事务@GlobalTransactiona从Oblect.getId()获取的却是undo_log的自增id

2、factoryBean.setTransactionFactory(new JdbcTransactionFactory());  这样配置的话，本地事务@Transactional无法回滚，必须配置DataSourceTransactionManager 配置seata的数据源代理才行

### Ⅱ. Describe what happened
@Bean
    public SqlSessionFactory sqlSessionFactory(DataSourceProxy dataSourceProxy) throws Exception {
        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(dataSourceProxy);
        factoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath*:/mapper/*.xml"));
//        factoryBean.setTransactionFactory(new JdbcTransactionFactory());
        factoryBean.setTransactionFactory(new SpringManagedTransactionFactory());
        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.setMapUnderscoreToCamelCase(true);
        factoryBean.setConfiguration(configuration);
        return factoryBean.getObject();
    }

@Bean
    @Primary
    public DataSourceTransactionManager dataSourceTransactionManager(DataSourceProxy dataSourceProxy){
        DataSourceTransactionManager transactionManager = new DataSourceTransactionManager();
        transactionManager.setDataSource(dataSourceProxy);
        return transactionManager;
    }

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅴ. Anything else we need to know?
本地事物和全局事务兼容，seata和mybatis示例

### Ⅵ. Environment:

- JDK version : 1.8
- OS :
- Others:

**Comment by slievrly** [comment]
@Empty66 Can you give me a link to the code, let me check it out?

**Comment by Empty66** [comment]
上面问题都已解决，wiki上面建议提供接入mybatis+sptingboot:
1、对于本地事物@transactional和全局事务冲突问题：
  配置calss类需要加上以下配置：配置事务管理器数据源为seata数据代理
/**
     * spring事务配置数据源代理
     * @param dataSourceProxy
     * @return
     */
    @Bean
    @Primary
    public DataSourceTransactionManager dataSourceTransactionManager(DataSourceProxy dataSourceProxy){
        DataSourceTransactionManager transactionManager = new DataSourceTransactionManager();
        transactionManager.setDataSource(dataSourceProxy);
        return transactionManager;
    }

并且 factoryBean.setTransactionFactory(new SpringManagedTransactionFactory()); 
必须配置成 SpringManagedTransactionFactory，因为mybatis默认用SpringManagedTransactionFactory
/**
     * 替换 mybatis 的sqlSessionFactory，用数据源代理替换自动装配的数据源
     * @Param: dataSourceProxy  fescar数据源代理
     * @Return: SqlSessionFactory  mybatic使用的数据源
     */
    @Bean
    public SqlSessionFactory sqlSessionFactory(DataSourceProxy dataSourceProxy) throws Exception {
        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(dataSourceProxy);
        factoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath*:/mapper/*.xml"));
//        factoryBean.setTransactionFactory(new JdbcTransactionFactory());  //这个不可用
        factoryBean.setTransactionFactory(new SpringManagedTransactionFactory());
        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.setMapUnderscoreToCamelCase(true);
        factoryBean.setConfiguration(configuration);
        return factoryBean.getObject();
    }
2、对于返回自增id是undo_log的自增id，解决方案如下：
       可以在生成的xml文件的insert加上：
            useGeneratedKeys="true" keyProperty="id"

       tkmybatis的话需要在生成的映射对象类的id上配置generator = "JDBC"如下：
        @Table(name = "xxx_credit_apply")
        @Setter
        @Getter
         public class XxxCreditApplyPo {
             @Id
             @GeneratedValue(generator = "JDBC")
              private Long id;
