### ISSUE TITLE
insert rows return -1 when success

### ISSUE THREAD

**Issue by weijj** [seata/seata#1259]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在使用mybatis+seata+druid提交全局事务插入数据时，遇到插入成功，但是返回的结果行数为-1的情况。

### Ⅱ. Describe what happened

下面是我的示例代码, 入代码注释，插入成功，但是结果返回了-1，更多代码详情见[这里](https://github.com/weijj/seata-samples.git)。

```
    @GlobalTransactional(timeoutMills = 3000000, name = "htw-bhScm-bindLock-gtx")
    public boolean addLockDtx(ScmDtxDO scmDtxDO) {
        try {
            int rows = scmDtxDao.add(scmDtxDO); // return -1, when insert successed
            boolean success = rows > 0;
            if (!success) {
                throw new RuntimeException("db failed");
            }
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
        return true;
    }
```

### Ⅲ. Describe what you expected to happen
插入成功，并且返回结果为1，即插入的行数

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

参考[这里](https://github.com/weijj/seata-samples.git)，代码入口为 ScmDtxRemoteService#main，注意需要修改 tc和jdbc配置。

### Ⅵ. Environment:

- JDK version : 1.8
- OS : macos
- Others: mybatis 3.2.2, durid: 1.1.12, seata 0.6.1

**Comment by slievrly** [comment]
mybatis mapper set `useGeneratedKeys="true" `

**Comment by vikenlove** [comment]
@weijj <generatedKey column="ID" sqlStatement="JDBC"  /> it will be return you slq PK values

**Comment by xingfudeshi** [comment]
> @weijj it will be return you slq PK values
The PK value will never be returned,It will be filled into the corresponding primary key fields in your entity class.
