### ISSUE TITLE
Is it supported to manually open and submit global transactions?

### ISSUE THREAD

**Issue by ghost0224** [seata/seata#1275]
最近有个需求根据一些条件判断是否需要开启全局事务，如果能手动控制开启和提交的话，那我们的控制流程会更加灵活，后续能否提供API接口？

**Comment by slievrly** [comment]
@ghost0224 Support for API, the use of spring annotations is also based on API.

**Comment by xingfudeshi** [comment]
> 最近有个需求根据一些条件判断是否需要开启全局事务，如果能手动控制开启和提交的话，那我们的控制流程会更加灵活，后续能否提供API接口？

please refer to here:http://seata.io/zh-cn/docs/quickstart/api.html
