### ISSUE TITLE
Can't resolve dependencies from version 0.7.0

### ISSUE THREAD

**Issue by siyu77** [seata/seata#1299]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
pom.xml
```
<dependency>
   <groupId>io.seata</groupId>
   <artifactId>seata-metrics-all</artifactId>
   <version>0.7.0</version>
</dependency>
```
shows error: "Failed to read artifact descriptor for io.seata:seata-metrics-all:jar:0.7.0"

### Ⅱ. Describe what happened
After comparing different versions of pom.xml, found that:

version 0.6.1 and before:
```
<parent>
  <groupId>io.seata</groupId>
  <artifactId>seata-parent</artifactId>
  <version>0.6.1</version>
</parent>
```
but version 0.7.0:
```
<parent>
  <groupId>io.seata</groupId>
  <artifactId>seata-metrics</artifactId>
  <version>${revision}</version>
</parent>
```

### Ⅲ. Describe what you expected to happen
"If you like to install or deploy artifacts by using the above setup you have to use the flatten-maven-plugin otherwise you will install/deploy artifacts in your repository which will not be consumable by Maven anymore."

see: https://maven.apache.org/maven-ci-friendly.html

### Ⅵ. Environment:
- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@siyu77 reslove later
