### ISSUE TITLE
Does seata now support HA-Cluster high availability?

### ISSUE THREAD

**Issue by lvchongyi** [seata/seata#1303]
请问下seata现在支持HA-Cluster高可用性吗?
哪个版本支持HA-Cluster?
HA-Cluster配置说明有吗？在哪里?

**Comment by slievrly** [comment]
@lvchongyi since 0.6.1+，ref https://github.com/seata/seata-samples/tree/master/ha

**Comment by jaychang9** [comment]
请问下seata现在支持HA-Cluster高可用性吗?
哪个版本支持HA-Cluster?
HA-Cluster配置说明有吗？在哪里?   同问
