### ISSUE TITLE
Netty memory leak

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1304]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/8758457/61200134-0a44a980-a713-11e9-9ca4-d3c84a30f9df.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by cmonkey** [comment]
PR 1333
