### ISSUE TITLE
Need properties file support

### ISSUE THREAD

**Issue by chenxi-null** [seata/seata#1311]
For now, Seata only support '*.conf' configuration file, but as java programer, most coder are more similar with properties file, in addition, some configuration center, like apollo, only support properties file.

**Comment by cmonkey** [comment]
这是否应该是关于是否支持apollo config server 的问题，如果是的话，那么此问题就属于config server 支持的问题，而不是基础配置问题

**Comment by jsbxyyx** [comment]
seata conf file implement by [lightbend/config](https://github.com/lightbend/config), the library support properties

**Comment by jsbxyyx** [comment]
supported.
