### ISSUE TITLE
zipkin SleuthHystrixConcurrencyStrategy  spring-cloud-alibaba-seata

### ISSUE THREAD

**Issue by luoc101** [seata/seata#1316]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
`org.springframework.cloud:spring-cloud-starter-zipkin:2.1.1.RELEASE` 中的  
`org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixConcurrencyStrategy` 和
org.springframework.cloud:spring-cloud-alibaba-seata:0.9.1.BUILD-SNAPSHOT的
`org.springframework.cloud.alibaba.seata.feign.hystrix.SeataHystrixConcurrencyStrategy`
冲突
### Ⅱ. Describe what happened
启动报错

```
Description:

Field existingConcurrencyStrategy in org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration required a single bean, but 2 were found:
	- seataHystrixConcurrencyStrategy: defined by method 'seataHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/alibaba/seata/feign/hystrix/SeataHystrixAutoConfiguration.class]
	- sleuthHystrixConcurrencyStrategy: defined by method 'sleuthHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.class]


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

### Ⅵ. Environment:
```
 <dependency>
           <groupId>org.springframework.cloud</groupId>
           <artifactId>spring-cloud-starter-zipkin</artifactId>
  </dependency>

        <dependency>#0.9.1.BUILD-SNAPSHOT
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <version>${alibaba-seata.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>${seata.version}</version>
        </dependency>#0.7.1
```
- JDK version : 1.8
- OS :
- Others:

**Comment by cmonkey** [comment]
这个问题应该去https://github.com/alibaba/spring-cloud-alibaba/issues 报告

**Comment by cwm3412638** [comment]
> * [x] 我已经搜索了这个存储库的[问题](https://github.com/seata/seata/issues)，并认为这不是重复的。
> 
> ### Ⅰ。问题说明
> `org.springframework.cloud:spring-cloud-starter-zipkin:2.1.1.RELEASE`的中
> `org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixConcurrencyStrategy`状语从句：
> org.springframework.cloud:spring-cloud-alibaba-seata:0.9.1.BUILD-SNAPSHOT的
> `org.springframework.cloud.alibaba.seata.feign.hystrix.SeataHystrixConcurrencyStrategy`
> 冲突
> 
> ### Ⅱ。描述发生的事情
> 启动报错
> 
> ```
> Description:
> 
> Field existingConcurrencyStrategy in org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration required a single bean, but 2 were found:
> 	- seataHystrixConcurrencyStrategy: defined by method 'seataHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/alibaba/seata/feign/hystrix/SeataHystrixAutoConfiguration.class]
> 	- sleuthHystrixConcurrencyStrategy: defined by method 'sleuthHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.class]
> 
> 
> Action:
> 
> Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
> ```
> 
> ### Ⅲ。描述您期望发生的事情
> ### Ⅳ。如何重现它（尽可能最小和精确）
> ### Ⅴ。还有什么我们需要知道的吗？
> ### Ⅵ。环境：
> ```
>  <dependency>
>            <groupId>org.springframework.cloud</groupId>
>            <artifactId>spring-cloud-starter-zipkin</artifactId>
>   </dependency>
> 
>         <dependency>#0.9.1.BUILD-SNAPSHOT
>             <groupId>org.springframework.cloud</groupId>
>             <artifactId>spring-cloud-alibaba-seata</artifactId>
>             <version>${alibaba-seata.version}</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>io.seata</groupId>
>                     <artifactId>seata-spring</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>io.seata</groupId>
>             <artifactId>seata-all</artifactId>
>             <version>${seata.version}</version>
>         </dependency>#0.7.1
> ```
> 
> * JDK版本：1.8
> * OS：
> * 其他：

请问下，我也同样遇到了这个问题，你是怎么解决的

**Comment by wangliang181230** [comment]
https://github.com/alibaba/spring-cloud-alibaba/pull/1946
已合并
