### ISSUE TITLE
MySql8.0 version service connection is abnormal

### ISSUE THREAD

**Issue by jiangbin31** [seata/seata#1320]
现象：
在使用mysql8.0版本数据库情况，数据库连接不上。
原因：
新版mysql8.0的jar包 和 驱动不对。
新版jar
    <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.12</version>
        </dependency>

驱动driverClassName：com.mysql.cj.jdbc.Driver

建议：
驱动可以在file.conf 进行配置

**Comment by jiangbin31** [comment]
配置
![image](https://user-images.githubusercontent.com/22318753/61352021-e0b88900-a89e-11e9-84f6-4e0b1566226f.png)

![image](https://user-images.githubusercontent.com/22318753/61352037-e9a95a80-a89e-11e9-970a-2f82306938d7.png)

![image](https://user-images.githubusercontent.com/22318753/61352066-fded5780-a89e-11e9-886a-0df3253ee268.png)


数据库连接异常

**Comment by vikenlove** [comment]
@jiangbin31  please tell me  which is version of mysql ?

**Comment by vikenlove** [comment]
@jiangbin31  i was commit a pr  about config to driverclassname

**Comment by jiangbin31** [comment]
mysql  version : 8.0
The new mysql jar package maven address is  【
    <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.12</version>
        </dependency>
】

Driverclassname  is  【com.mysql.cj.jdbc.Driver】。

**Comment by slievrly** [comment]
@vikenlove thank you.

**Comment by ChaunceyBee** [comment]
step 1.  Change the MySQL JAR file in the lib path to 8.0+
step 2.  Change the 

> > Hi @jiangbin31, we detect non-English characters in the issue. This comment is an auto translation from @fescar-robot to help other users to understand this issue.
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> # MySql8.0 version service connection is abnormal
> phenomenon:
> In the case of using the mysql8.0 version of the database, the database connection is not available.
> the reason:
> The new version of mysql8.0 jar package and driver is wrong.
> New jar
> 
> mysql
> mysql-connector-java
> 8.0.12
> Driver driverClassName: com.mysql.cj.jdbc.Driver
> 
> Suggest:
> The driver can be configured in file.conf

> Suggest :Add: `serverTimezone=GMT%2B8` to the URL
   for exanole:`url = "jdbc:mysql://127.0.0.1:3306/seata?serverTimezone=GMT%2B8"`

**Comment by ChaunceyBee** [comment]
> > Hi @jiangbin31, we detect non-English characters in the issue. This comment is an auto translation from @fescar-robot to help other users to understand this issue.
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> # MySql8.0 version service connection is abnormal
> phenomenon:
> In the case of using the mysql8.0 version of the database, the database connection is not available.
> the reason:
> The new version of mysql8.0 jar package and driver is wrong.
> New jar
> 
> mysql
> mysql-connector-java
> 8.0.12
> Driver driverClassName: com.mysql.cj.jdbc.Driver
> 
> Suggest:
> The driver can be configured in file.conf

> Suggest :Add: `serverTimezone=GMT%2B8` to the URL
   for exanole:`url = "jdbc:mysql://127.0.0.1:3306/seata?serverTimezone=GMT%2B8"`
