### ISSUE TITLE
Why is it null when I call RootContext.getXID() in @TwoPhaseBusinessAction?

### ISSUE THREAD

**Issue by quicksandznzn** [seata/seata#1327]
Why is it null when I call RootContext.getXID() in @TwoPhaseBusinessAction?

**Comment by quicksandznzn** [comment]
i use 0.7.1 version ,0.6.1 version is ok

**Comment by quicksandznzn** [comment]
![image](https://user-images.githubusercontent.com/23514918/61518045-4ccff400-aa3b-11e9-8c8b-c7e04063b4b7.png)

**Comment by quicksandznzn** [comment]
why unbind xid

**Comment by quicksandznzn** [comment]
![image](https://user-images.githubusercontent.com/23514918/61518287-bf40d400-aa3b-11e9-9016-9f857948398b.png)

**Comment by quicksandznzn** [comment]
@zhangthen

**Comment by zhangthen** [comment]
If the DataSource of AT is accessed in the preapre of TCC,   another branch transaction records will  create repeatedly.
