### ISSUE TITLE
[Discussion] How to avoid 'unknow column' Exception when table meta cache still available and real table meta has changed?

### ISSUE THREAD

**Issue by l81893521** [seata/seata#1350]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
some problem when execute delete operation have arised.

### Ⅱ. Describe what happened
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'sex' in 'field list'
```

### Ⅲ. Describe what you expected to happen
I think if druid doesn't throw the MySQLSyntaxErrorException that means sql is correct, we can catch the MySQLSyntaxErrorException in the DeleteExecutor, update the table meta cache, and try to execute the sql one more time.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.delete some data in seata_account_tbl(id,user_id,money,sex) normally
2.now, table meta have 4 column and set in the cache
3.delete successfully
4.remove 1 column in database(for example: delete sex column)
5.delete some data in seata_account_tbl again
6.try to find table meta in the cache(table meta in the cache have 4 column)
7.execute select id, user_id, money, sex from seata_account_tbl(actually, sex column have removed already)
8.'unknow column sex' Exception have arised.

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
In this case, we need to consider whether it is appropriate to change the table structure of the database when the business is not down and how to change the table structure without stopping the system to quickly invalidate the table cache.
