### ISSUE TITLE
Dirty reads occur in independent transactions during SEATA distributed transaction execution

### ISSUE THREAD

**Issue by chenjeff** [seata/seata#1354]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在seata分布式事务，A分支事务已执行完成，同时记录了undo-log；B分支事务正在执行...在B分支事务执行期间，存在一个非Seata的独立事务X，事务X读取了A分支已提交的数据(脏数据)，并使用脏数据执行了相应操作后；B分支事务执行失败，主事务驱动A分支事务回滚，A分支事务根据undo-log执行回滚后。即会丢失独立事务X提交的数据。

**Comment by xingfudeshi** [comment]
As you said, transaction X is not a branch transaction governed by seata, so it is correct that seata does not handle transaction X when it rolls back.

**Comment by xingfudeshi** [comment]
If the operation of transaction X might involve transaction B, why not treat transaction X as a branch transaction of seata?

**Comment by slievrly** [comment]
X should mark @GlobalLock or managed in seata.

**Comment by chenjeff** [comment]
确实可以通过@GlobalLock注解实现。谢谢
