### ISSUE TITLE
Does seata currently only support Mysql database? Different databases use different databases such as: mysql oracle, can you support it?

### ISSUE THREAD

**Issue by ltlwill** [seata/seata#1367]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
Seata will support these relational databases, Oracle is currently supported.

**Comment by vikenlove** [comment]
you can wait next version . and  next version support config jdbc driver version
