### ISSUE TITLE
Seata 0.7.1 always reports unknow dbtype:null when running in db mode

### ISSUE THREAD

**Issue by ltlwill** [seata/seata#1382]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by ltlwill** [comment]
windows7 系统seata 0.7.1 服务端 以 db 模式 启动错误日志：
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundExcepti
on: not found service provider for : io.seata.server.store.TransactionStoreManag
er caused by java.lang.IllegalArgumentException: unknown dbtype:null
        at io.seata.core.constants.DBType.valueof(DBType.java:90)
        at io.seata.core.store.db.AbstractDataSourceGenerator.getDBType(Abstract
DataSourceGenerator.java:44)
        at io.seata.server.store.db.DruidDataSourceGenerator.generateDataSource(
DruidDataSourceGenerator.java:36)
        at io.seata.server.store.db.DatabaseTransactionStoreManager.init(Databas
eTransactionStoreManager.java:98)
        at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedSer
viceLoader.java:361)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:235)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:194)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoad
er.java:89)
        at io.seata.server.session.db.DataBaseSessionManager.init(DataBaseSessio
nManager.java:81)
        at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedSer
viceLoader.java:361)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:235)
        at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedService
Loader.java:194)
        at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoad
er.java:89)
        at io.seata.server.session.SessionHolder.init(SessionHolder.java:91)
        at io.seata.server.Server.main(Server.java:68)

seata server 端配置：
file.conf 配置:
store {
  ## store mode: file、db
  mode = "file"

  ## file store
  file {
    dir = "sessionStore"

    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    max-branch-session-size = 16384
    # globe session size , if exceeded throws exceptions
    max-global-session-size = 512
    # file buffer size , if exceeded allocate new buffer
    file-write-buffer-cache-size = 16384
    # when recover batch read size
    session.reload.read_size = 100
    # async, sync
    flush-disk-mode = async
  }

  ## database store
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "dbcp"
    ## mysql/oracle/h2/oceanbase etc.
    db-type = "mysql"
    url = "jdbc:mysql://192.168.2.6:3306/seata?useUnicode=true"
    user = "db_ebay_dev"
    password = "db_ebay_devpwd"
    min-conn = 1
    max-conn = 3
    global.table = "global_table"
    branch.table = "branch_table"
    lock-table = "lock_table"
    query-limit = 100
  }
}

registry.conf 配置:
registry {
    type = "nacos"
   nacos {
      serverAddr = "localhost"
      namespace = "public"
      cluster = "default"
    }
}
config {
    type = "nacos"
    nacos {
      serverAddr = "localhost"
      namespace = "public"
      cluster = "default"
    }
}
如果将registry,conf中的 registry、config 的type = "file" 就能启动，换成 type = "nacos" 就报错dbtype: null的错误，nacos服务是已经启动了

**Comment by cmonkey** [comment]
我下午找个时间看一下

**Comment by cmonkey** [comment]
你下配置类似以下值
![image](https://user-images.githubusercontent.com/664050/62518820-f9dca600-b85c-11e9-8a76-fe7447af68ff.png)

**Comment by ltlwill** [comment]
这样配置确实不报 dbtype:null的错误，url、username、password等都可以这样配，但是无论怎么配置都会报：maxActive can't not set zero   我也是无语了！
我在nacos 中配置如下图
![B31D0C4C-3D13-4a75-9C64-AA01354571E3](https://user-images.githubusercontent.com/16695334/62528666-ca836480-b86f-11e9-90f9-9fa671117209.png)
：

**Comment by ltlwill** [comment]
这是控制台错误信息：
![Uploading {BC92F9B7-BF23-4C7F-8AB3-2F3046075DE6}_20190806173254.jpg…]()

**Comment by ltlwill** [comment]
这是控制的错误信息：
![{BC92F9B7-BF23-4C7F-8AB3-2F3046075DE6}_20190806173254](https://user-images.githubusercontent.com/16695334/62529024-690fc580-b870-11e9-81e6-240a57b5ecb7.jpg)

**Comment by ltlwill** [comment]
下图是控制台打印的错误信息：
![{BC92F9B7-BF23-4C7F-8AB3-2F3046075DE6}_20190806173254](https://user-images.githubusercontent.com/16695334/62529067-817fe000-b870-11e9-9cca-7f364157c5a9.jpg)

**Comment by cmonkey** [comment]
明天我测试一下

**Comment by cmonkey** [comment]
因为这个值读取的是store.db.max-conn

**Comment by ltlwill** [comment]
多谢大佬！但是又有个新问题，业务客户端在启动时总是报：Caused by: java.lang.NullPointerException: Name is null，如下图所示：
![{8887FF5E-84EB-46D6-9A17-8FC5FB015D4E}_20190807100045](https://user-images.githubusercontent.com/16695334/62588946-30b4c980-b8fa-11e9-8368-36bca4e9e566.jpg)
应该在nacos中怎么配置，我现在的在nacos中是这样配置的（spring.application.name=inventory-service），但是依然报这个错：
![{132F8D16-45C3-4CED-87D8-3D23A5CF6FC3}_20190807100316](https://user-images.githubusercontent.com/16695334/62589049-8d17e900-b8fa-11e9-90d0-de647ae48237.jpg)
![{FCEE65B9-6C2C-4698-BAE8-A61F43667323}_20190807100408](https://user-images.githubusercontent.com/16695334/62589074-a91b8a80-b8fa-11e9-9506-7ce594cf82ab.jpg)

**Comment by cmonkey** [comment]
SEATA_GROUP 这个group 对应的type是配置正确的吗？
