### ISSUE TITLE
2019-08-04 21:01:57.091 ERROR 12960 --- [           main] i.s.c.r.netty.AbstractRpcRemotingClient  : Failed to get available servers: {}null

### ISSUE THREAD

**Issue by FrankAblert** [seata/seata#1397]
2019-08-04 21:01:57.091 ERROR 12960 --- [           main] i.s.c.r.netty.AbstractRpcRemotingClient  : Failed to get available servers: {}null

#####  file.conf
transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #enable heartbeat
  heartbeat = true
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
}
service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"
  #only support single node
  default.grouplist = "127.0.0.1:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
  disableGlobalTransaction = false
}

client {
  async.commit.buffer.limit = 10000
  lock {
    retry.internal = 10
    retry.times = 30
  }
}

### registry.conf  file;
registry {
  # file 、nacos 、eureka、redis、zk
  type = "eureka"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://127.0.0.1:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6381"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  apollo {
    app.id = "fescar-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

always report the error...
request this  http://localhost:8084/purchase/commit  ,  response : No available service.  but eureka can see that's services.

**Comment by flightefore** [comment]
What is your client configuration?

**Comment by FrankAblert** [comment]
> What is your client configuration?

run the project that is url https://github.com/seata/seata-samples /springcloud-eureka-seata .

##Account Module Properties:

spring.application.name=account-service
server.port=8083
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/project_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
spring.datasource.username=project
spring.datasource.password=123456
logging.level.io.seata=debug
spring.cloud.alibaba.seata.tx-service-group=my_test_tx_group
eureka.instance.hostname=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka/



##Eureka Properties:

server.port=8761
eureka.instance.hostname=127.0.0.1
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false

**Comment by FrankAblert** [comment]
> What is your client configuration?

the question is reslove, update the seata-server to 7.1

**Comment by xingfudeshi** [comment]
Please try to use the latest version of seata.
