### ISSUE TITLE
branchRegister error，Data too long for column

### ISSUE THREAD

**Issue by dupengcheng** [seata/seata#1400]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

missing exception detail , no log ,no throw,

异常在这里被吞掉了，很不利于在线排错

![图片](https://user-images.githubusercontent.com/11847818/62437697-e22af200-b776-11e9-9e5a-fb165705aa90.png)

### Ⅱ. Describe what happened
"Data too long for column  " ，It's a simple question，but without any exception info online

![图片](https://user-images.githubusercontent.com/11847818/62438186-dccea700-b778-11e9-8372-f19d6d9a88a9.png)

好费劲的在测试环境开启remote  debug 才找到原因，希望能加一行日志

### Ⅲ. Describe what you expected to happen

add error log 

### Ⅵ. Environment:

- JDK version : 1.8
- OS :  linux  
- Others:  base image openjdk:8

**Comment by lightClouds917** [comment]
What size of the lockkeys ?

**Comment by dupengcheng** [comment]
varchar(500)

---
my team extend executeBatch  method，we set lock_key  longtext ，but to this issue just add log is fine.

这个问题，我认为加一行日志就好，方便问题定位，lock_key默认值一般就够了。因为我们扩展实现了executeBatch ，所以我们设置这个key为 longtext ，但我不建议其他人这么设置，数据库大字段操作不易优化。

**Comment by dupengcheng** [comment]
fine
@lightClouds917
optimize:add error log for addBranchSession for seata#1400
