### ISSUE TITLE
MySQLInsertRecognizer$1.printTableSourceExpr throws a ex:java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by radishT** [seata/seata#1405]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata+druild + mybatis
![image](https://user-images.githubusercontent.com/32050371/62508837-a6a62b80-b83b-11e9-8ade-fb6e7ad36b78.png)

I'm not sure it's a bug. But I need help!
![image](https://user-images.githubusercontent.com/32050371/62509380-87a89900-b83d-11e9-9763-c98667676a48.png)

- JDK version :1.8

**Comment by radishT** [comment]
When I regist  DruidDataSource  , it worked . But DataSourceProxy will throw this error.
mybatis sqlSessionFactoryBean was not supported?

**Comment by radishT** [comment]
![image](https://user-images.githubusercontent.com/32050371/62513805-d3643e00-b84f-11e9-930c-f8bceae4eb2f.png)
my datasource 

when I use 
![image](https://user-images.githubusercontent.com/32050371/62513850-f131a300-b84f-11e9-88b6-00ffa3d901f4.png)
it also unworked 
![image](https://user-images.githubusercontent.com/32050371/62513880-07d7fa00-b850-11e9-9239-5cc83f6330f2.png)

**Comment by slievrly** [comment]
@radishT druid version?

**Comment by radishT** [comment]
![image](https://user-images.githubusercontent.com/32050371/62514579-3525a780-b852-11e9-8121-c8d1ad9646f0.png)
@slievrly

**Comment by radishT** [comment]
@slievrly  oh  .
when I change the version of druid to seata-all , it worked.

**Comment by slievrly** [comment]
@radishT we used druid 1.1.12

**Comment by radishT** [comment]
@slievrly  ok thanks !
