### ISSUE TITLE
Seata Support jdk > 1.8

### ISSUE THREAD

**Issue by challange** [seata/seata#1410]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
在jdk >1.8 的版本下，seata无法正常运行

现象1:
使用jdk1.11编译seata-all,启动运行client抛出NoSuchMethodError异常
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
```
server端抛出OutOfMemoryError和TooLongFrameException异常
```
java.lang.OutOfMemoryError: Direct buffer memory
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 16777216 - discarded
```
现象2:
seata-server在jdk >1.8 的环境下启动记得也是报TooLongFrameException异常

### Environment:

- JDK version : > 1.8
- OS : Mac OX、Ubuntu
- Others:

**Comment by cmonkey** [comment]
需要更清晰的线索，比如具体的jdk version, seata version, 启动流程，配置的信息，错误的堆栈

**Comment by slievrly** [comment]
For the second question，whether the seata-all and seata-server versions are 0.7.1+？

**Comment by challange** [comment]
0.7.1 version
