### ISSUE TITLE
TableMetaCache getIndexInfo failed if the table name is {databasename.tablename}

### ISSUE THREAD

**Issue by maverickswin** [seata/seata#1421]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
If my table is LOOKUP.USER
in TableMetaCache.java resultSetMetaToSchema function
catalogName is "LOOKUP"
schemaName is ""
tableName is "LOOKUP.USER"

Then ResultSet rs2 = dbmd.getIndexInfo(catalogName, schemaName, tableName, false, true);
will get "illegal operation on empty result set"

Then index is null on
IndexMeta index = tm.getAllIndexes().get(indexName);
finally Null Pointer Exception is throwed.
index.getIndextype().value() != 0

### Ⅱ. Describe what happened

Then ResultSet rs2 = dbmd.getIndexInfo(catalogName, schemaName, tableName, false, true);
will get "illegal operation on empty result set"

Then index is null on
IndexMeta index = tm.getAllIndexes().get(indexName);
finally Null Pointer Exception is throwed.
index.getIndextype().value() != 0

### Ⅲ. Describe what you expected to happen
The weird thing is:
ResultSet rs1 = dbmd.getColumns(catalogName, schemaName, tableName, "%");
rs1 is correct.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
Shall we split the table name by "."?

### Ⅵ. Environment:

- JDK version : 1.8.0_131
- OS : centos7.3
- Others:

**Comment by l81893521** [comment]
I think the main problem is that the table without index cause the exception.

**Comment by maverickswin** [comment]
> I think the main problem is that the table without index cause the exception.

No, it is not.

I am using MySQL DB and the table has only one primary key.
Moreover, I've changed to use the actual table name, and I can get the correct index info.
