### ISSUE TITLE
Support CALL PROCEDURE

### ISSUE THREAD

**Issue by maverickswin** [seata/seata#1424]
**In a global transaction, I have to call procedure to create some ids.
But Seata throws ShouldNotHappenException.**

I am thinking of an alternative way:

_String unbindXid = RootContext.unbind();
CALL Procedure
RootContext.bind(unbindXid);_

To bypass my CALL prodcedure.

Do you have any suggestion?

**Comment by slievrly** [comment]
@maverickswin  procedures are not supported.
