### ISSUE TITLE
After starting a microservice, the console keeps reporting errors.

### ISSUE THREAD

**Issue by kaixinbaba** [seata/seata#1427]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
从github上down下来了seata-example， 由于公司用的是spring cloud eureka那一套，所以选择了这个module下开始运行，
本地通过sh seata-server.sh -p 8091 -h 127.0.0.1 -m db 启动server
![image](https://user-images.githubusercontent.com/22809336/62697105-8a0d1d80-ba0c-11e9-99e6-0b4021223541.png)
微服务同样先启动eureka，并无异常 访问8761 如下
![image](https://user-images.githubusercontent.com/22809336/62697251-e2441f80-ba0c-11e9-9b2d-e6f54232ea2d.png)
同样的配置启动account
![image](https://user-images.githubusercontent.com/22809336/62697324-069ffc00-ba0d-11e9-8ff9-8f27dc8bdac2.png)
贴一下account的配置
![image](https://user-images.githubusercontent.com/22809336/62697364-220b0700-ba0d-11e9-8c80-c6d016df8ef2.png)
![image](https://user-images.githubusercontent.com/22809336/62697390-2f27f600-ba0d-11e9-8b80-b1025f3c7e15.png)
但是控制台一直在报
![image](https://user-images.githubusercontent.com/22809336/62697447-48c93d80-ba0d-11e9-8b6b-21f977d42228.png)
全部微服务启动后如下：
![image](https://user-images.githubusercontent.com/22809336/62697908-63e87d00-ba0e-11e9-98c6-68a5efdc4df8.png)
访问如下：
![image](https://user-images.githubusercontent.com/22809336/62697948-7e225b00-ba0e-11e9-8b3d-b4979f757330.png)

### Ⅴ. Anything else we need to know?
是我用的姿势有问题吗？求助大佬

### Ⅵ. Environment:

- JDK version :1.8
- OS :MacOS 10.14.5 (18F132)
- Others:

**Comment by slievrly** [comment]
@kaixinbaba Paste application.properties

**Comment by kaixinbaba** [comment]
solved, the sh script must specify IP address, not 127.0.0.1,
eg: 
sh seata-server.sh -p 8091 -h 10.1.2.127 -m db
10.1.2.127 is example IP
