### ISSUE TITLE
In the examples, when configuring different databases, an error is reported.

### ISSUE THREAD

**Issue by dan334540507** [seata/seata#143]
订单、余额、库存 3个表都放同一个数据库中运行成功，但当我分库后，运行出错。求大神告知哪里配置错了还是目前fescar就不支持分库。

**Comment by liuqian6112** [comment]
Fescar is a support repository, you can paste your errors

**Comment by ad201717** [comment]
I found that when the three examples run at the same ip address, whole the three BranchCommitRequest/BranchRollbackRequest will be send to one rm role, then the error with undolog will occur!

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
