### ISSUE TITLE
Time type precision causes post mirroring and current mirroring to match mismatched transactions cannot be rolled back

### ISSUE THREAD

**Issue by lirengui** [seata/seata#1434]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
时间类型精度导致后置镜像和当前镜像比对不匹配事务无法回滚

### Ⅱ. Describe what happened
当业务表字段类为timestamp时
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
支持timestamp类型时间精度

![image](https://user-images.githubusercontent.com/26484302/62761019-0f014100-bab8-11e9-997d-1018e187abbc.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by l81893521** [comment]
i will fix this problem
