### ISSUE TITLE
How to configure multiple Eureka

### ISSUE THREAD

**Issue by liguanfeng** [seata/seata#1440]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

How to configure multiple Eureka ?
 eureka {
    serviceUrl = "http://localhost:8761/eureka,http://localhost:8762/eureka" 
    application = "default"
    weight = "1"
  }

**Comment by xingfudeshi** [comment]
Not support yet.
