### ISSUE TITLE
 How to set redis password?

### ISSUE THREAD

**Issue by liguanfeng** [seata/seata#1441]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

1.How to set redis password?
2.How to configure multiple redis clusters？
 redis {
    serverAddr = "localhost:6379"
    db = "0"
  }

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by l81893521** [comment]
just like this in registry.conf
```
redis {
    serverAddr = "127.0.0.1:6379"
    db = "0"
    password = "your password"
}
```

**Comment by liguanfeng** [comment]
哥们 redis集群是用逗号隔开吗？例如：
redis {
    serverAddr = "127.0.0.1:6379,127.0.0.1:6378"
    db = "0"
    password = "your password"
}

**Comment by l81893521** [comment]
Seata does not support setting redis cluster yet.
