### ISSUE TITLE
There is a problem with dataValidationAndGoOn

### ISSUE THREAD

**Issue by weibergit** [seata/seata#1461]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
包名:io.seata.rm.datasource.undo
类名：AbstractUndoExecutor
方法：dataValidationAndGoOn
这个方法有问题，这个方法的第二个if是这样写的
// Validate if data is dirty.
        TableRecords currentRecords = queryCurrentRecords(conn);
        // compare with current data and after image.
        if (!DataCompareUtils.isRecordsEquals(afterRecords, currentRecords))
逻辑是查出现在表的内容和修改后的(after image)进行比较，如果相同执行回滚，
可是这里永远不会相同，因为after镜像保存的是修改的列，而现在查出的(currentRecords)是全部的列，所以永远不会相同，所以就永远不会回滚了！

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
no
```
Just paste your stack trace here!
```
no

### Ⅲ. Describe what you expected to happen
修改一下代码呗

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?

no
### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows
- Others: no

**Comment by l81893521** [comment]
Sorry, I m not understand what s your mean clearly.
'''
if (!DataCompareUtils.isRecordsEquals(afterRecords, currentRecords))
'''
when after and current not equal, actually will cause the rollback because return true.

**Comment by zjinlei** [comment]
@weibergit please see isRecordsEquals --> compareRows,only check changed columns.

**Comment by slievrly** [comment]
@weibergit After image as the outer loop, then check the current data, I think there is no problem.

**Comment by weibergit** [comment]
> Sorry, I m not understand what s your mean clearly.
> 
> ```
> if (!DataCompareUtils.isRecordsEquals(afterRecords, currentRecords))
> ```
> 
> when after and current not equal, actually will cause the rollback because return true.

not return true, just throw new SQLException("Has dirty records when undo.");

 if (!DataCompareUtils.isRecordsEquals(afterRecords, currentRecords)) {
            
            // If current data is not equivalent to the after data, then compare the current data with the before 
            // data, too. No need continue to undo if current data is equivalent to the before data snapshot
            if (DataCompareUtils.isRecordsEquals(beforeRecords, currentRecords)) {
                if (LOGGER.isInfoEnabled()) {
                    LOGGER.info("Stop rollback because there is no data change " +
                            "between the before data snapshot and the current data snapshot.");
                }
                // no need continue undo.
                return false;
            } else {
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("check dirty datas failed, old and new data are not equal," +
                            "tableName:[" + sqlUndoLog.getTableName() + "]," +
                            "oldRows:[" + JSON.toJSONString(afterRecords.getRows()) + "]," +
                            "newRows:[" + JSON.toJSONString(currentRecords.getRows()) + "].");
                }
                throw new SQLException("Has dirty records when undo.");
            }
        }

**Comment by l81893521** [comment]
Maybe you can check here io.seata.rm.datasource.DataCompareUtils#compareRows
oldRowsMap as the outer loop, so the other column would not compare.
```
for (String rowKey : oldRowsMap.keySet()) {
            Map<String, Field> oldRow = oldRowsMap.get(rowKey);
            Map<String, Field> newRow = newRowsMap.get(rowKey);
```

**Comment by weibergit** [comment]
> @weibergit please see isRecordsEquals --> compareRows,only check changed columns.

comparRows,    **check all columns**

private static boolean compareRows(TableMeta tableMetaData, List<Row> oldRows, List<Row> newRows) {
        // old row to map
        Map<String, Map<String, Field>> oldRowsMap = rowListToMap(oldRows, tableMetaData.getPkName());
        // new row to map
        Map<String, Map<String, Field>> newRowsMap = rowListToMap(newRows, tableMetaData.getPkName());
        // compare data
        for (String rowKey : oldRowsMap.keySet()) {
            Map<String, Field> oldRow = oldRowsMap.get(rowKey);
            Map<String, Field> newRow = newRowsMap.get(rowKey);
            if (newRow == null) {
                return false;
            }
            for (String fieldName : oldRow.keySet()) {
                Field oldField = oldRow.get(fieldName);
                Field newField = newRow.get(fieldName);
                if (newField == null) {
                    return false;
                }
                if (!isFieldEquals(oldField, newField)) {
                    return false;
                }
            }
        }
        return true;
    }

see log :
io.seata.rm.datasource.undo.AbstractUndoExecutor.dataValidationAndGoOn(AbstractUndoExecutor.java:209) check dirty datas failed, old and new data are not equal,tableName:[stock],oldRows:[[{"fields":[{"keyType":"PrimaryKey","name":"id","type":-5,"value":1},{"keyType":"NULL","name":"total_stock","type":4,"value":74},{"keyType":"NULL","name":"lock_stock","type":4,"value":36}]}]],newRows:[[{"fields":[{"keyType":"PrimaryKey","name":"id","type":-5,"value":1},{"keyType":"NULL","name":"product_id","type":-5,"value":1},{"keyType":"NULL","name":"total_stock","type":4,"value":73},{"keyType":"NULL","name":"lock_stock","type":4,"value":37}]}]].

**check dirty datas failed, old and new data are not equal**

**Comment by weibergit** [comment]
> Maybe you can check here io.seata.rm.datasource.DataCompareUtils#compareRows
> oldRowsMap as the outer loop, so the other column would not compare.
> 
> ```
> for (String rowKey : oldRowsMap.keySet()) {
>             Map<String, Field> oldRow = oldRowsMap.get(rowKey);
>             Map<String, Field> newRow = newRowsMap.get(rowKey);
> ```

I know, but if I modify the source code myself, then only I can use it myself.

So I want the author to revise it.

**Thank you for answering my question.**

**Comment by l81893521** [comment]
I m wondering why you after image and current image would not equal, and cause the exception.

**Comment by weibergit** [comment]
Sorry，dataValidationAndGoOn is right.

**Comment by weibergit** [comment]
> I m wondering why you after image and current image would not equal, and cause the exception.

me too，I'm checking.

**Comment by weibergit** [comment]
> I m wondering why you after image and current image would not equal, and cause the exception.

Maybe it's because of threads，I'm checking.
**Thank you for answering my question.**

**Comment by l81893521** [comment]
Ok, if you find the error, contact us in any time. It's better if tell us how to reproduce it.

**Comment by weibergit** [comment]
I know the reason for this mistake.
Because I didn't open disableGlobalTransaction
This parameter default ： disableGlobalTransaction = false
change disableGlobalTransaction = true

**Comment by weibergit** [comment]
Last question，After service is deployed to docker ，unable to connect

**Comment by weibergit** [comment]
**my sqlUndoLogs for json :**
"sqlUndoLogs": ["java.util.ArrayList", [{
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "stock",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 889
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 111
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 888
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 112
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "stock",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 888
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 112
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 887
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 113
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "stock",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 887
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 113
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 886
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 114
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "stock",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 886
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 114
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "stock",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "total_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 885
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "lock_stock",
					"keyType": "NULL",
					"type": 4,
					"value": 115
				}]]
			}]]
		}
	}]]

---------------------------------------------------------------------------------------------------------

**this List size = 4**

class UndoLogManager
method :
public static void undo(DataSourceProxy dataSourceProxy, String xid, long branchId) throws TransactionException {
             ........;
   for(SQLUndoLog sqlUndoLog : sqlUndoLogList){  -- It should be recycled 4 times
        .......;
        AbstractUndoExecutor.executeOn();
    }
}

executeOn(){
    if (IS_UNDO_DATA_VALIDATION_ENABLE && !dataValidationAndGoOn(conn)) {
            return;
        }
}

dataValidationAndGoOn(){
    ....;
    if (!DataCompareUtils.isRecordsEquals(afterRecords, currentRecords)) {
    if (DataCompareUtils.isRecordsEquals(beforeRecords, currentRecords)) {
                if (LOGGER.isInfoEnabled()) {
                    LOGGER.info("Stop rollback because there is no data change " +
                            "between the before data snapshot and the current data snapshot.");
                }
                // no need continue undo.
                return false;
            } else {
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("check dirty datas failed, old and new data are not equal," +
                            "tableName:[" + sqlUndoLog.getTableName() + "]," +
                            "oldRows:[" + JSON.toJSONString(afterRecords.getRows()) + "]," +
                            "newRows:[" + JSON.toJSONString(currentRecords.getRows()) + "].");
                }
                throw new SQLException("Has dirty records when undo.");
    }
}

**throw new SQLException("Has dirty records when undo.");**  -- this line of code causes the program to stop！！！

**Comment by l81893521** [comment]
Can you tell me the way that can reproduce this error? Because this error only appear when after image and current image not equals.

**Comment by weibergit** [comment]
Using multithreaded access testing，

**Comment by warrior2005** [comment]
@weibergit Do you find the root cause of this problem? I meet this error too when use multithread test.

**Comment by warrior2005** [comment]
@weibergit Use select for update at the beginning of the Global Transaction.
See #1715
