### ISSUE TITLE
when branch rollbacking, the data image compare log confused

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1463]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When a branch transaction is rollbacking, the logs of the beforeImage and afterImage are confusing and need to be optimized.

![image](https://user-images.githubusercontent.com/8758457/63078734-1076b180-bf6f-11e9-873e-2500e2544dbf.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
I will fix this problem
