### ISSUE TITLE
When the seata-server starts, it should takes a delay to delete the expired undo log

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1464]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When the seata-server starts, it should takes a delay to delete the expired undo log. when the 
delete the expired undo log schedule run the first，rm channel was not registered.
![image](https://user-images.githubusercontent.com/8758457/63079612-6187a500-bf71-11e9-8aed-a03e798557f6.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by jsbxyyx** [comment]
can i fix it?
