### ISSUE TITLE
There is a plan to support multi type database connection pool ?

### ISSUE THREAD

**Issue by ykgarfield** [seata/seata#147]
## Why you need it?
Now, `rm-datasource` module is dependent on `druid`, not support others database connection pool.

## How it could be?
`rm-datasource` module is dependent on `druid`, `AbstractDataSourceProxy` is hardcode `DruidDataSource`, it means only can use `druid`.Threr is a plan to support multi type database connection pool ? eg. `hikariCP`、`cp30` ... etc.

## Other related information

**Comment by tswstarplanet** [comment]
I tried to do this, but I found fescar couples druid deeply.

**Comment by slievrly** [comment]
already support
