### ISSUE TITLE
build after-image sql Error

### ISSUE THREAD

**Issue by 9Cobra** [seata/seata#1470]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![95)@T 8~}9{6}_Y`EXKAO2](https://user-images.githubusercontent.com/16607042/63139532-2c329400-c011-11e9-8b83-d693b3a1f360.png)
![$Y76D V~$MOBWVA V2M7N0](https://user-images.githubusercontent.com/16607042/63139539-32287500-c011-11e9-9532-0f0696aa010f.png)

CREATE TABLE `test1`.`order_tbl`  (
  `order_id` int(11) NOT NULL AUTO_INCREMENT,
  `order_num` int(11) NOT NULL,
  `order_date` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

when i use sql 'insert into order_tbl(order_id,order_num,order_date) values (1, 100, ?) ',  it will throw an exception, then i check the exception and i find that if i have no value of primary key, building after-image sql will get an unnecessary 'where' and then throw exception

and what does cycleNums means?

update:
i see that i must use parameter list to build sql and seata use cycleNums to check the value of primary key

how can i just use sql without no parameters? like insert into order_tbl(order_id,order_num,order_date) values (1, 100, '2019-08-16') ?

seata version: 0.8.0-snapshot

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
thanks
I will fix this problem

**Comment by yqsas** [comment]
使用 0.8.0 遇到一样的问题，希望尽快修复。

定位：InsertExecutor
原因:  mapper 中 sql 语句部分字段使用了默认值，导致 preparedStatementProxy.getParameters() 获取的参数列表将小于字段列表，最终导致执行后续select 语句语法错误。

**Comment by jsbxyyx** [comment]
PR #1512
