### ISSUE TITLE
How to sync sessions between different TC servers ?

### ISSUE THREAD

**Issue by beston123** [seata/seata#1491]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I start two TC servers, 127.0.0.1:8091 and 127.0.0.1:8092 in 'file' store mode .
 1. The business service send a begin transcation request to 8091.
 2. The business logic throws a Exception,  then TM send a rollback request to 8092.
The TC server return rollback success, though it can not find the session and the transcation has not be rollbacked. 

### Ⅱ. Describe what happened
None

### Ⅲ. Describe what you expected to happen
The TC server return rollback success, and  the session is rollbacked. 
How to sync sessions between different TC servers in 'file' store mode?

**Comment by zjinlei** [comment]
tow TC is High Availability,please use db mode

**Comment by xingfudeshi** [comment]
The session is no need to synchronized between TCs，they should share data with database.
