### ISSUE TITLE
wiki problem,  can not open Overview refer at home page

### ISSUE THREAD

**Issue by Justice-love** [seata/seata#1494]
- [X] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
in english version,  can not open Overview at home page

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by Justice-love** [comment]
![图片](https://user-images.githubusercontent.com/3375778/63312088-e76d6c80-c332-11e9-9d3c-09263c17f138.png)

**Comment by slievrly** [comment]
It is recommended that documents be migrated to seata.io.

**Comment by Justice-love** [comment]
ok, got it, thx for reply
