### ISSUE TITLE
Using zookeeper registry transaction did not roll back

### ISSUE THREAD

**Issue by liuyi9608** [seata/seata#1498]
seata-server循环打印下面的日志
[RetryRollbacking_1]io.seata.server.coordinator.DefaultCore.doGlobalRollback:317 -Failed to rollback branch BR:2020015507/2020015504

**Comment by cmonkey** [comment]
有用例可以重现吗

**Comment by liuyi9608** [comment]
> 有用例可以重现吗

有的

**Comment by cmonkey** [comment]
链接，并需要知道seata 的版本

**Comment by liuyi9608** [comment]
> 链接，并需要知道seata 的版本

https://github.com/seata/seata-samples/tree/master/dubbo/src/main/java/io/seata/samples/dubbo/starter  使用的zookeeper注册中心 seata为0.8.0

**Comment by zjinlei** [comment]
May be the reason, please add jackson dependency

**Comment by cmonkey** [comment]
这应该不是一个问题，因为在BusinessServiceImpl.purchase 里面手动抛出了RuntimeException , 而在
DefaultCoordinator.handleRetryRollbacking中一直对其进行了重试，除非对配置service.max.rollback.retry.timeout 设置了值

**Comment by xingfudeshi** [comment]
Registry does not affect the rollback processing of transactions.

**Comment by liuyi9608** [comment]
> May be the reason, please add jackson dependency
> https://github.com/seata/seata-samples/pull/212/files

This method is used to solve the problem.Thank
