### ISSUE TITLE
when the application occurs  an exeption , the global transaction didn't rollback ..  

### ISSUE THREAD

**Issue by Zorance** [seata/seata#1503]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
程序发生异常时seata日志打印说是回滚成功  undo_log表没有数据记录   但是涉及到的微服务并没有回滚事务 

### Ⅱ. Describe what happened
用的seata版本: v0.8.0   代码在这里https://github.com/Zorance/seata-demo      account和user项目是两个为服务 里面的config配了数据源交给seata做代理   gateway项目是调用服务方 配置了GlobalTransactionScanner
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by gudepeng** [comment]
请问解决了吗？碰到同样的问题。使用版本0.9.0.1

**Comment by zjinlei** [comment]
please use 1.0.0
