### ISSUE TITLE
Whether the file.config in the demo supports the springboot configuration file form, such as in apollo or in application.properties

### ISSUE THREAD

**Issue by liuyi9608** [seata/seata#1509]

**Comment by slievrly** [comment]
@liuyi9608 Support for the configuration of file.conf to apollo, change the configuration config.type=apollo in registry.conf, but registry.conf is not allowed to put into apollo, it is metadata information.

**Comment by Garlichead** [comment]
so apollo configuration set up file.conf, How to set it.
