### ISSUE TITLE
timeout rollback may have a bug

### ISSUE THREAD

**Issue by xuyang0902** [seata/seata#152]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
flush undo_log pending before committing until the server notifies the branch to roll back when it finds that the global transaction has timed out.
finally undolog inserted and business sql executed。
it is wrong。

### Ⅱ. Describe what happened

rollback may make data dirty 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. debug point on
com.alibaba.fescar.rm.datasource.ConnectionProxy#
if (context.hasUndoLog())//line

2. until the server notifies the branch to roll back when it finds that the global transaction has timed out
3. branch rollback(has no undo_log)   return succ
4. finally release debug point 
### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by skyesx** [comment]
i think we should flush the logs first and then register later 
and when execute rollback we should use select for update to get the rollback info

**Comment by xuyang0902** [comment]
> i think we should flush the logs first and then register later
> and when execute rollback we should use select for update to get the rollback info

This is a solution. 
I think server should have a thread to clean up the invalid undolog.

**Comment by skyesx** [comment]
when not report, the instance may:
* dead, will not report any more
* stuck in transaction, will report later

TC can't know the status until communicate with the RM and it's database(Cause) .

In my naive opinion, there's no other solution...

**Comment by xuyang0902** [comment]
> Great found. TXC/GTS does have mechanism handling such case. We are trying to find a better solution.
> 
> Key of such case is: a branch was registered, but not reported to server. The how to treat such branch when rollback?

I think what Skyesx mentioned is really a solution to the problem.

We can think about whether there are other better solutions. After all, the resources of locks are more precious.

Think about it from a different angle. There are not many scenarios in which this happens.

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
