### ISSUE TITLE
Update rollback may lose intermediate state

### ISSUE THREAD

**Issue by cainiaoyuan** [seata/seata#1527]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
update rollback may lose intermediate state

### Ⅱ. Describe what happened

 when i run the example, i put a break point before the code throw new RunTimeException. now ,the value in the table storage_tbl is 98, then i change the value to 99 manually, then i cancel the break point, the code begin to execute rollback logic. finally, the value in the table storage_tbl rollback to 100.
![image](https://user-images.githubusercontent.com/25977343/63631434-2add1900-c65a-11e9-874a-fdeeec57321f.png)

just imagine, one thread just complete the phase one, the value in table storage_tbl get changed, then another thread increases the value, and then the first thread occurs exception and need to rollback. should the value increased by the second thread be overrided? below is the source code when bulid undoSql,just according to primary key:
![image](https://user-images.githubusercontent.com/25977343/63631596-b8216d00-c65c-11e9-97cf-48c727982dbc.png)

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by l81893521** [comment]
Normally, the second thread cannot changed value because the lock, until the first thread was finished.

**Comment by l81893521** [comment]
And the rollback value actually depends on the beforeImage.

**Comment by xingfudeshi** [comment]
If you manually change the value in the database, this will break normal global transaction processing, it should never happen.

**Comment by slievrly** [comment]
Pls confirm the configuration item `transaction.undo.data.validation = true`
