### ISSUE TITLE
store.db.driver-class-name is missing in nacos-config.txt  

### ISSUE THREAD

**Issue by jaychang9** [seata/seata#1531]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When I use apollo to config the seata-server. And I config the session store in db.
The error hint that store.db.driver-class-name must exists.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
Thank you for reporting this problem.
By the way,could you submit a PR to fix this problem?
