### ISSUE TITLE
AbstractSessionManager#updateBranchSessionStatus debug log is wrong

### ISSUE THREAD

**Issue by TinyZzh** [seata/seata#1538]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/5763397/63748354-ca5d0e80-c8db-11e9-9dc6-56e586ec4a23.png)

日志输出的内容是否应该分别修改为BRANCH_UPDATE和BRANCH_REMOVE？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
thanks
I will fix it
