### ISSUE TITLE
I want to use seata in production, please ask the transaction table undo_log, how can I configure the data source?

### ISSUE THREAD

**Issue by liuyi9608** [seata/seata#1540]
生产上想使用seata做分布式事务，想问一下demo中的undo_log这张表如何做单独的数据源的配置

**Comment by jsbxyyx** [comment]
I suggest you look at the principle of seata

**Comment by xingfudeshi** [comment]
The undo_log table must be in the same database as the business data table because the snapshot data is done in the same local transaction as the business data.

**Comment by liuyi9608** [comment]
> The undo_log table must be in the same database as the business data table because the snapshot data is done in the same local transaction as the business data.

What if two things operate under different instances?

**Comment by xingfudeshi** [comment]
> > The undo_log table must be in the same database as the business data table because the snapshot data is done in the same local transaction as the business data.
> 
> What if two things operate under different instances?

Do you mean the business is done with different DB instance?

**Comment by liuyi9608** [comment]
> > > The undo_log table must be in the same database as the business data table because the snapshot data is done in the same local transaction as the business data.
> > 
> > 
> > What if two things operate under different instances?
> 
> Do you mean the business is done with different DB instance?

yes ,Because every microservice has its own instance or a different library

**Comment by xingfudeshi** [comment]
> > > > The undo_log table must be in the same database as the business data table because the snapshot data is done in the same local transaction as the business data.
> > > 
> > > 
> > > What if two things operate under different instances?
> > 
> > 
> > Do you mean the business is done with different DB instance?
> 
> yes ,Because every microservice has its own instance or a different library

That's what Seata does,Seata treats it as a global transaction.
Please take a look at https://github.com/seata/seata/wiki/Quick-Start
