### ISSUE TITLE
Does it support multiple datasource for JPA

### ISSUE THREAD

**Issue by robinyeeh** [seata/seata#1546]
## Why you need it?
I would like to know if it supports multiple datasource transaction for JPA as we are using multiple datasources and we need to have transaction for multiple databases? Thanks a lot.

**Comment by xingfudeshi** [comment]
Yes.it supports multiple datasource.you need to create DataSourceProxy for each of datasource.

**Comment by robinyeeh** [comment]
@xingfudeshi , Thanks a lot for your prompt reply. I really appreciate it.

**Comment by xingfudeshi** [comment]
> @xingfudeshi , Thanks a lot for your prompt reply. I really appreciate it.

I'll close this issue,if you have further question,welcome reopen it.

**Comment by robinyeeh** [comment]
@xingfudeshi 
ok. Thanks .
