### ISSUE TITLE
seata config with apoll is not easy to uses enough, can you optimize it?

### ISSUE THREAD

**Issue by ldcsaa** [seata/seata#1555]
1. In actual usage scenarios, many (even that all) applications or serivice machines use the same apollo settings (apollo settings file: _/opt/settings/server.properties_), this settings file contains '_apollo.meta_' and '_env_' elements, can seata load this  settings file instead of config '_apollo.meta_' property in every application?
2. Likewise, in actual usage scenarios, many TM/RM applications use the same seata settings (such as _transport_, _service_, _client_ etc...), can seata support the **namespace** function of apollo ? If support, seata settings are configurated in a public namespace, many appilcations share these settings, instead of all applications duplicate them. In this case 'app.id' config item is optional.

**Comment by slievrly** [comment]
Will fix this problem soon
