### ISSUE TITLE
Does the seata proxy data source configuration support only configuring database instances, such as jdbc:mysql://127.0.0.1:3307/

### ISSUE THREAD

**Issue by liuyi9608** [seata/seata#1561]

**Comment by slievrly** [comment]
@liuyi9608 Did not understand your problem, datasourceProxy in addition to configuring the database instance can be configured other?

**Comment by liuyi9608** [comment]
> @liuyi9608 Did not understand your problem, datasourceProxy in addition to configuring the database instance can be configured other?

I mean the data source of the datasourceProxy configuration in the demo is: jdbc.order.url=jdbc:mysql://localhost:3306/fescar_demo, specifying the specific database: fescar_demo, but the mybatis we used during development, The data source does not specify a specific database, which is the database specified on the sql statement of mybatis. In this case, can the seata find the undo_log table to do the transaction rollback?

**Comment by xingfudeshi** [comment]
If your database name was specificed dynamically,please make sure the undo_log table exists the same database as the business table.

**Comment by liuyi9608** [comment]
> If your database name was specificed dynamically,please make sure the undo_log table exists the same database as the business table.

Dynamically specify database rollback when prompted to find no database specified
![Uploading image.png…]()

**Comment by liuyi9608** [comment]
> If your database name was specificed dynamically,please make sure the undo_log table exists the same database as the business table.

2019-09-04 09:58:19.807  INFO 33240 --- [atch_RMROLE_5_8] io.seata.rm.AbstractRMHandler            : Branch Rollbacking: 10.0.108.124:8091:2021289951 2021289952 jdbc:mysql://127.0.0.1:3307/
2019-09-04 09:58:19.811  INFO 33240 --- [atch_RMROLE_5_8] i.seata.rm.datasource.DataSourceManager  : branchRollback failed reason [2021289952/10.0.108.124:8091:2021289951 No database selected]
2019-09-04 09:58:19.811  INFO 33240 --- [atch_RMROLE_5_8] io.seata.rm.AbstractRMHandler            : Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable

**Comment by xingfudeshi** [comment]
In fact, how to choose data sources should not be done on seata's side, but at the business level.

**Comment by xingfudeshi** [comment]
To make global transactions available, seata must proxy your datasource. Make sure you are using seata's DataSourceProxy when working with the database.
