### ISSUE TITLE
What is the working mode of HA cluster, master-slave or others? How do multiple servers coordinate

### ISSUE THREAD

**Issue by shigenwang** [seata/seata#1562]
## Why you need it?
 I want to understand how HA works

**Comment by xingfudeshi** [comment]
Have you tried HA samples?

**Comment by xingfudeshi** [comment]
https://github.com/seata/seata-samples/tree/master/ha

**Comment by futuremen** [comment]
The seata-server server USES the database as the transaction log store, and users can deploy multiple seata-servers to provide clustered services to support high availability on the server side. That's the example. The other ones are like the eureka example, they don't say how to ensure high availability
