### ISSUE TITLE
Nacos registry loss something config in document

### ISSUE THREAD

**Issue by queal** [seata/seata#1563]
Nacos registry loss something config in document, please add that`

### Ⅰ. Issue Description
file.conf contains:
    service.default.grouplist
    db.driver-class-name

but nacos-config.txt has not this configs;

that i try to maunal edit the nacos-config.txt , sh nacos-config.sh ${nacos-addr}, that works,

please add that in document`

**Comment by xingfudeshi** [comment]
fixed #1537
