### ISSUE TITLE
Whether the configuration in the Seata client registry.conf file can be placed in the application.properties or configuration center.

### ISSUE THREAD

**Issue by pilihaotian** [seata/seata#1565]
## Why you need it?
 In order to reduce the client's configuration file, it is planned to integrate the configuration information in the registry.conf into the application.properties or configuration center.

## How it could be?
Excuse me, how to remove the client's registry.conf file, put the relevant configuration inside: 1, application.propertie 2, configuration center 3, the user can customize these configurations through code customization. In this case, the client relies on fewer files. I see the source code is read from the file registry.conf, there is no idea to adapt.

**Comment by zjinlei** [comment]
fixed in 1.0.0
