### ISSUE TITLE
Adjusted frame length exceeds 8388608: 2415944960 - discarded

### ISSUE THREAD

**Issue by MistraR** [seata/seata#1573]
**Adjusted frame length exceeds 8388608: 2415944960 - discarded**

Environment:

seata-server 0.8.0

**Comment by slievrly** [comment]
@MistraR Pls keep seata-all version 0.7.1+

**Comment by zhengjianfeng1103** [comment]
i have same problem

**Comment by slievrly** [comment]
@MistraR @zhengjianfeng1103 upgrade seata（seata-all、seata-server） version to 0.7.1 （recommend 0.8.0).

**Comment by MistraR** [comment]
> @MistraR @zhengjianfeng1103 upgrade seata（seata-all、seata-server） version to 0.7.1 （recommend 0.8.0).

Thank you
