### ISSUE TITLE
examples demo show sql

### ISSUE THREAD

**Issue by systp** [seata/seata#158]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
Not related to functionality, but it allows developers to better observe data changes 

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

Can the sample print the statement in the console before executing sql? I think that printing the sql in the console will better observe the data changes and operations.
ShowSql might be better when debugging to execute the demo to observe the data.

**Comment by leizhiyuan** [comment]
Thanks for your contribution.

I will close the issue, if you have other questions, please reopen it or create a new one
