### ISSUE TITLE
存储模型使用文件，服务器端分支事务会话为空 seata0.71 jdk1.8

### ISSUE THREAD

**Issue by mingyifei** [seata/seata#1586]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/38995810/64225081-728e5b00-cf0c-11e9-9830-65715f09dfcb.png)

![image](https://user-images.githubusercontent.com/38995810/64224624-d2840200-cf0a-11e9-87cd-092b7e99ef15.png)

采用读隔离，执行器使用的是selectForUpdateExcute，windows10环境
statementProxy.getConnectionProxy().checkLock(lockKeys);
seata服务端获取session会话为null  ；采用的session存储采用的file模式

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by jsbxyyx** [comment]
please tell your question. you question is rollback fail or something else???

**Comment by mingyifei** [comment]
> 请告诉你的问题。你的问题是回滚失败或其他什么???

首先store model是file模式，用了for update ，执行器selectForUpdateExcute，这一行statementProxy.getConnectionProxy（）CHECKLOCK（lockKeys）。请求seata服务端获取锁时，seata服务端的session会话为null，抛异常

**Comment by mingyifei** [comment]
> please tell your question. you question is rollback fail or something else???

你可以在线下复现一下该场景

**Comment by mingyifei** [comment]
> please tell your question. you question is rollback fail or something else???

我通过断点跟踪，发现Branch Session传的null，上面的截图所示

**Comment by jsbxyyx** [comment]
@mingyifei OK, I will reappear it and fix

**Comment by jsbxyyx** [comment]
#1647
