### ISSUE TITLE
HystrixSecurityAutoConfiguration needs to inject the bean at startup, but there are two beans with the same name, how to solve it

### ISSUE THREAD

**Issue by cwm3412638** [seata/seata#1587]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Field existingConcurrencyStrategy in org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration required a single bean, but 2 were found:
	- seataHystrixConcurrencyStrategy: defined by method 'seataHystrixConcurrencyStrategy' in class path resource [com/alibaba/cloud/seata/feign/hystrix/SeataHystrixAutoConfiguration.class]
	- sleuthHystrixConcurrencyStrategy: defined by method 'sleuthHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.class]

```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zaki12199** [comment]
I also encountered the same problem, how to solve

**Comment by zaki12199** [comment]
Just exclude conflicting files in the startup class。
@SpringBootApplication(scanBasePackages = "com.gcyl.pig.shop.*", exclude = {SleuthHystrixAutoConfiguration.class})
