### ISSUE TITLE
Invalid Nacos namespace registry.config?

### ISSUE THREAD

**Issue by yuandaijin** [seata/seata#1589]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
    registry. config setting namespace does not take effect?

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by jsbxyyx** [comment]
can you paste config info, seata version

**Comment by jsbxyyx** [comment]
you can use newest seata (develop branch)

**Comment by yuandaijin** [comment]
我运行的是seata-samples中的springcloud-nacos-seata.
seata版本是0.8

**Comment by yuandaijin** [comment]
I run spring cloud-nacos-seata in seata-samples.
Seata version is 0.8

**Comment by zjinlei** [comment]
https://github.com/seata/seata/pull/1539
Not yet released

**Comment by yuandaijin** [comment]
ok thanks

**Comment by xingfudeshi** [comment]
@yuandaijin This problem has been fixed,please try to build seata locally or wait for next release.
