### ISSUE TITLE
Consult the branch transaction before the global transaction GT1 is submitted, the other transaction is also submitted to the same data, then the global transaction GT1 initiates a rollback, how to roll back?

### ISSUE THREAD

**Issue by zimmem** [seata/seata#1591]
如帐户初始余额是 100 ；
发起全局事务 GT1 , 其中分支事务给余额加上50并提交， 但全局事务未提交；
发起全局事务 GT2 ， 其中分支事务给余额减去 130 并提交， 全局事务 GT2 提交成功；
全局事务 GT1  发起回滚， 这时是怎么回滚的？ 帐户减去 50 变 -30 ?

**Comment by zjinlei** [comment]
http://seata.io/zh-cn/docs/architecture/seata_at.html
