### ISSUE TITLE
Internal registration client ZkClient 0.11 version problem

### ISSUE THREAD

**Issue by zhongfuhua** [seata/seata#1595]
ZkClient 0.11版本不支持 zookeeper 3.4.13及以下版本的连接，会出现可以连接zookeeper但是无法返回响应导致超时。亲测0.10版本没问题
![微信图片_20190905093517](https://user-images.githubusercontent.com/13580963/64304989-7b406900-cfc0-11e9-98e8-2b01f6946680.png)

**Comment by lovepoem** [comment]
It is better to use the new version of jars ,  how about use newest version of zookeeper ?

**Comment by zhongfuhua** [comment]
> It is better to use the new version of jars , how about use newest version of zookeeper ?

The latest version of zookeeper is 3.4.14, but 3.4.13 is a smaller version, and many people don't necessarily use the latest version.

**Comment by cmonkey** [comment]
通过测试zookeeper (3.4.13 3.4.10) 无法重现此问题，请检查网路配置，是否在timout 的时间内不能获取到建立连接
