### ISSUE TITLE
store db模式被file覆盖

### ISSUE THREAD

**Issue by mingyifei** [seata/seata#1613]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata 0.71 jdk1.8 win10
根目录file.conf，model设置的为db，db连接也改了。并且初始化时Configuration中也是存在的。
在server的main方法里
init执行完是获取到了store model = db的
//initialize the metrics
 MetricsManager.get().init();
![image](https://user-images.githubusercontent.com/38995810/64444421-af25a680-d106-11e9-868e-ddcb1f7cd35c.png)

![image](https://user-images.githubusercontent.com/38995810/64444655-36731a00-d107-11e9-839c-a58d05725634.png)

本来是DB，这一步获取到的是file，你又把store model改成了file模式
导致全局session会话永远都是null 

所以我只能是下图
![image](https://user-images.githubusercontent.com/38995810/64444805-95d12a00-d107-11e9-8915-18c35dbf9fa9.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
080 fixed, priority startup parameters

**Comment by xingfudeshi** [comment]
This bug has been fixed since 0.8.0.
