### ISSUE TITLE
Method assertDbSupport in io.seata.rm.datasource.undo.UndoLogManager missed oracle dbType support

### ISSUE THREAD

**Issue by wangrui821** [seata/seata#1614]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Seata 0.8.0 has support Oracle database. But method assertDbSupport in io.seata.rm.datasource.undo.UndoLogManager missed oracle dbType support.
After I added the oracle dbType in this method, I execute the seata-sample project with Oracle database successfully.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
...
DbType[oracle] is not support yet!
...
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Execute the seata-sample project with Oracle database.

### Ⅵ. Environment:

- JDK version : 1.8
- OS : Windows 10

**Comment by ggndnn** [comment]
Same issue #1596 ?

**Comment by wangrui821** [comment]
@ggndnn Thanks for your reply. I'm sorry I didn't find the same issue before I add this one.
