### ISSUE TITLE
Could we upgrade the jdk version from 7 to 8?

### ISSUE THREAD

**Issue by tswstarplanet** [seata/seata#162]
Now jdk 8 is used widely used, and it has many advanced features than jdk 7. As a new open source project, I think we can use jdk 8 because we don’t have historical burden.

**Comment by systp** [comment]
I think it is JDK1.7. Although Java8 is widely used, some companies still use java7.

**Comment by tswstarplanet** [comment]
But upgrading to java 8 is the trend.

**Comment by xho22** [comment]
这是中间件，不是业务应用，用低版本是兼容更多的用户去使用

**Comment by tswstarplanet** [comment]
> 这是中间件，不是业务应用，用低版本是兼容更多的用户去使用

dubbo 2.7以后也只支持jdk8以上了

**Comment by leizhiyuan** [comment]
now it is  jdk 1.8,  I will close the issue, if you have other questions, please reopen it or create a new one
