### ISSUE TITLE
It  takes  too long that  server connect zk registry  

### ISSUE THREAD

**Issue by zmbaliqq** [seata/seata#1620]
![image](https://user-images.githubusercontent.com/17873871/64509621-af928d00-d312-11e9-9703-370e550c0de6.png)
if  I set the zk.connect.timeout=40000,it still  timeout
until  i set zk.connect.timeout=45000,it can normally connect 。

**Comment by cmonkey** [comment]
你需要查看一下服务到zk 服务的网络配置
