### ISSUE TITLE
Example of AT mode Two global transactions operate on a table and do not see the need for a global transaction.

### ISSUE THREAD

**Issue by kangkangshen** [seata/seata#1627]
这个例子貌似就是个sql连接修改同一张表的问题，底层数据库直接支持这种事务啊，没有看到使用全局事务的必要性，希望能给出切实的分布式事务的例子

**Comment by lightClouds917** [comment]
you can look this demo ,https://github.com/lightClouds917/seat

**Comment by lightClouds917** [comment]
demo分为四个项目，单独启动。

eureka:作为注册中心
order:订单服务，用户下单后，会创建一个订单添加在order数据库，同时会扣减库存storage，扣减账户account;
storage:库存服务，用户扣减库存；
account:账户服务，用于扣减账户余额；

**Comment by kangkangshen** [comment]
Yes,I had run it , thank you
