### ISSUE TITLE
Problems encountered when registering with Eureka

### ISSUE THREAD

**Issue by hengboy** [seata/seata#1634]
**Start the project and print on the console:**

2019-09-10 17:05:14.776 ERROR 7347 --- [imeoutChecker_1] i.s.c.r.netty.NettyClientChannelManager  : Failed to get available servers: null
2019-09-10 17:05:14.776 ERROR 7347 --- [imeoutChecker_1] i.s.c.r.netty.NettyClientChannelManager  : no available server to connect.

Below is my configuration information (basic auth exists in the Eureka link):
```
registry {
  # file、nacos、eureka、redis、zk、consul
  type = "eureka"

  file {
    name = "file.conf"
  }
  eureka {
    serviceUrl = "http://service:nodev2@10.180.98.216:10001/eureka"
    application = "default"
    wight = "1"
  }
}
```

**Comment by xingfudeshi** [comment]
`http://service:nodev2@10.180.98.216:10001/eureka` Is this your serviceUrl?Can you try http://10.180.98.216:10001/eureka?

**Comment by xingfudeshi** [comment]
It seems the Eureka client API does not support such type of urls.

**Comment by hengboy** [comment]
@xingfudeshi Sorry, the registration has been successful, but I have another question: Seata server configuration registered to Eureka and using DB mode, business services need to configure db-related information in file.conf? Or continue using file?

**Comment by xingfudeshi** [comment]
You need to configure db-related information in client-side as well.

**Comment by xingfudeshi** [comment]
And the store mode should be consistent.

**Comment by hengboy** [comment]
Do you want to configure the data source type of DB information in file. conf to be consistent with the project use?
For example: datasource = Druid
Project usage is: Hikari
