### ISSUE TITLE
Discovery seata server from register center(nacos, eureka, etc.)

### ISSUE THREAD

**Issue by tq02ksu** [seata/seata#1652]
## Why you need it?

First, every service will config the ip:port in file.conf. It is a little trublesome especially when system become to large. Furthermore, configured seata server maybe have single point problem when the server failed,  i can 't change the ip to restart the server.
Second, when the server highly loaded, i can't add some instances to server, and new instance will take some transactional schedule task to run(retryRollbacking, etc), But never reach the RM  node. 

## How it could be?

RM can discovery seata server from register center, and mantain server list continusly.
Seata server has mutual mechanism to avoid process scheduled task simultaneously.

## Other related information

Any body has better solution to resolve HA HP problem? thanks

**Comment by BeiKeJieDeLiuLangMao** [comment]
@tq02ksu 
Have you ever reviewed the code of [discovery model](https://github.com/seata/seata/tree/develop/discovery)? I think that's your talking about.

And TC Server will register itself at `io.seata.core.rpc.netty.AbstractRpcRemotingServer#start`

RM & TM client will find TC server list by `io.seata.discovery.registry.RegistryService#lookup`

Then  connect to one which selected by `io.seata.discovery.loadbalance.LoadBalance#select`

**Comment by BeiKeJieDeLiuLangMao** [comment]
@tq02ksu 
You could take a look this demo project [demo](https://github.com/lightClouds917/seat). It could show you how to config a registry center.

**Comment by tq02ksu** [comment]
@BeiKeJieDeLiuLangMao  thanks for you reply, i have mis guided by the comment in demo "#only support single node"
I check the discovery module, it is the solution. thank you!
