### ISSUE TITLE
Error in the mysql database primary key in the AT mode when using the Varchar type

### ISSUE THREAD

**Issue by lkxsoul** [seata/seata#1655]
0.8.0版本-0.8.1版本 mysql数据库主键当使用VARCHAR类型是，seata客户端报错，报错信息如下
![image](https://user-images.githubusercontent.com/54697419/64933193-68f2e480-d876-11e9-9949-82bfa1be2e67.png)

**Comment by jsbxyyx** [comment]
can you provide sql and parameter?

**Comment by lkxsoul** [comment]
Here is the information you need：

==>  Preparing: insert into seata_mq( `sid`,`param`,`createTime`) values (?,?,?) 
==> Parameters: 517619f8-865d-4e65-9acf-e9af0ce5a6ec(String), a(String), 2019-09-16 16:55:56.311(Timestamp)







At 2019-09-16 16:09:47, "jsbxyyx" <notifications@github.com> wrote:


can you provide sql and parameter?

**Comment by jsbxyyx** [comment]
OK, I will fix it

**Comment by jsbxyyx** [comment]
#1667
