### ISSUE TITLE
is support "A call B and C, call B by sync, but call C by async"

### ISSUE THREAD

**Issue by juaby** [seata/seata#166]
## Why you need it?
A call B and C, call B by sync, but call C by async

## How it could be?
Thread Context

**Comment by xuyang0902** [comment]
spring @Transactional also not suport asyn thread in a transaction

**Comment by sharajava** [comment]
Keep context in thread local is easiest way by the framework. I think you can give another implementation of com.alibaba.fescar.core.context.ContextCore to work with your async mechanism.

👍 It's great if you can share solutions for such cases.

**Comment by yuchonghua** [comment]
Very looking forward to the solution

**Comment by straybirdzls** [comment]
Very looking forward to the solution
