### ISSUE TITLE
What's the difference between Seata MT mode and TCC ?

### ISSUE THREAD

**Issue by andy-zhang-guohua** [seata/seata#1671]
## Why you need it?
In the Overview (Chinese version:https://github.com/seata/seata/wiki/%E6%A6%82%E8%A7%88) of Seata, it mentions two terms/concepts several times ： MT mode and TCC. They sound very similar . And can anyone from Seata team clarify the difference of them ? This information is very important for the user to better understand the features of Seata.

**Comment by slievrly** [comment]
there's no difference between MT and TCC.

**Comment by andy-zhang-guohua** [comment]
> there's no difference between MT and TCC.

Gotcha. 

But , TCC is well known by the public while Seata MT mode not. If they point to the samething, maybe the overview should give it a clearer clarification to avoid misleading .

**Comment by xingfudeshi** [comment]
> > there's no difference between MT and TCC.
> 
> Gotcha.
> 
> But , TCC is well known by the public while Seata MT mode not. If they point to the samething, maybe the overview should give it a clearer clarification to avoid misleading .

OK.Thank for your advice..

**Comment by xingfudeshi** [comment]
@andy-zhang-guohua Actually,the github wiki will be closed in the future,but you can still visit our website to know more about [Seata](http://seata.io).
