### ISSUE TITLE
@date is error javadoc  element

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1676]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/8758457/65146037-8a59f900-da4d-11e9-8f7d-892fec86fb34.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by jsbxyyx** [comment]
```
<plugin> 
  <groupId>org.apache.maven.plugins</groupId>  
  <artifactId>maven-javadoc-plugin</artifactId>  
  <version>2.10.4</version>  
  <executions> 
    <execution> 
      <id>attach-javadocs</id>  
      <goals> 
        <goal>jar</goal> 
      </goals> 
    </execution> 
  </executions>  
  <configuration> 
    <tags> 
      <tag> 
        <name>date</name> 
      </tag> 
    </tags> 
  </configuration> 
</plugin>
```

**Comment by slievrly** [comment]
@jsbxyyx I want  to remove all `date`, but will conflict with the existing pr.

**Comment by jsbxyyx** [comment]
@slievrly OK, I think wait for some pr to merged and then remove the date tag.

**Comment by jsbxyyx** [comment]
@slievrly 
![image](https://user-images.githubusercontent.com/26616196/65368985-63343f00-dc7a-11e9-8daa-264f519b6cd8.png)
