### ISSUE TITLE
exception for application_id too long

### ISSUE THREAD

**Issue by subo2010** [seata/seata#1680]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
application的名字过长seata_server会报错  seata v0.8.1
![image](https://user-images.githubusercontent.com/33054773/65294924-4f151280-db92-11e9-8f25-63dcf88576c2.png)

### Ⅱ. Describe what happened
springboot 项目application-name 命名过长会导致seata_server报错
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS :
- Others:

**Comment by xingfudeshi** [comment]
Please provide error details.

**Comment by cmonkey** [comment]
在对global_table表的application_id字段定义是varchar(32), 如果你的applicationId 长度超过32, 那么你可以尝试修改对application_id 的长度定义
