### ISSUE TITLE
cause "option error" when pass -D parameter to seata-server.sh

### ISSUE THREAD

**Issue by xingfudeshi** [seata/seata#1683]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When pass JVM parameter to seata-server.sh,will cause the follwoing error:
` Option error was passed main parameter '-DseataEnv=test' but no main parameter was defined in your arg class.`

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

seata-server.sh -p 8091 -m db -DseataEnv=test 

### Ⅴ. Anything else we need to know?
![image](https://user-images.githubusercontent.com/24457941/65308715-3c640300-dbbd-11e9-9125-015098358553.png)

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
export JVM_OPTS="-DseataEnv=test"

**Comment by xingfudeshi** [comment]
This problem only occurs on the server side.I'm gonna add a parameter option "-e" which will be used to set the name of environment.
