### ISSUE TITLE
Concurrency, when there are multiple branch transactions for the same global transaction: GlobalTransactionException: Could not found global transaction xid =

### ISSUE THREAD

**Issue by sseven** [seata/seata#1696]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

环境：SpringCloud、Openfeign、Nacos、Seata（model: DB）
基础服务：A、B （简单的保存对象）
组装服务：C  
C开启全局事务，C内部调用A、B两个服务；

![image](https://user-images.githubusercontent.com/17922001/65412604-260ab100-de22-11e9-9570-520face6a998.png)
![image](https://user-images.githubusercontent.com/17922001/65412666-4b97ba80-de22-11e9-8fd5-89841db40dd1.png)

### F5快频率刷新
![image](https://user-images.githubusercontent.com/17922001/65412698-5ce0c700-de22-11e9-979c-978ba746fbb0.png)

### 非常容易出现A/B两个服务新增的数据不一致，大部分的异常
io.seata.core.exception.GlobalTransactionException: Could not found global transaction xid = 192.168.2.12:8091:2022968728
	at io.seata.server.coordinator.DefaultCore.assertGlobalSessionNotNull(DefaultCore.java:99)

然后我提取了一些日志出来， 
两份日志都是在xid一致，存在多个不同branchId情况；
如下：
1、正常情况（XID=192.168.2.12:8091:2022968725）：
![image](https://user-images.githubusercontent.com/17922001/65413052-1dff4100-de23-11e9-80ba-4721d1842fe4.png)

2、失败情况（XID=192.168.2.12:8091:2022968728）

![image](https://user-images.githubusercontent.com/17922001/65413104-38d1b580-de23-11e9-9e67-4c1b5c3a69fc.png)

其中失败的服务日志

![image](https://user-images.githubusercontent.com/17922001/65413841-ec877500-de24-11e9-96e3-df83809f8423.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by sseven** [comment]
SpringCloud Feign与Dubbo两种方式，如果请求超时，事务好像不会受seata控制，不会回滚；

**Comment by VainEffort** [comment]
do you pass the XID?

**Comment by YangXueJun** [comment]
> SpringCloud Feign与Dubbo两种方式，如果请求超时，事务好像不会受seata控制，不会回滚；

I also find this problem.My seata version is 0.9.0.How to solve ,my god!

**Comment by slievrly** [comment]
@sseven @YangXueJun did you find that the data was inconsistent or  just throw an exception stack? This exception means that the transaction has ended and no longer exists.

**Comment by YangXueJun** [comment]
> @sseven @YangXueJun did you find that the data was inconsistent or just throw an exception stack? This exception means that the transaction has ended and no longer exists.

In fact ，  this exception  result from using db doc is rollbacking or in a transaction . so ,if you begin a transaction  to the same db doc ,it will  throw that exception .  But real problem is why the db doc is keeping rollbacking or why rollback failed。You can see my another  isssue  :https://github.com/seata/seata/issues/1965

  (实际上，这个异常是由于你正要加事务的记录正在回滚或者正在事务操作。因此，如果你针对同一条记录重新开启一个事务，这个时候程序会抛出该异常。但是真正的问题在于为什么这条数据库会一直处于回滚中或者为什么一直回滚失败,你可以看看我的另外一个issue：https://github.com/seata/seata/issues/1965)
