### ISSUE TITLE
Package package error

### ISSUE THREAD

**Issue by wangbeiyong** [seata/seata#1704]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

RROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project seata-common: Compila tion failure                                                                                                                                   [ERROR] /D:/seata/seata-0.8.1/seata-0.8.1/common/src/main/java/io/seata/common/util/ReflectionUtil.java:[188,41] ▒▒▒▒▒ݵ▒▒▒▒▒: java.util.Set va.lang.Class>▒޷▒ת▒▒Ϊjava.util.Set>
--

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS :windows
- Others:

**Comment by jsbxyyx** [comment]
may be you dependency download fail. we have CI build. [https://travis-ci.org/seata/seata/builds](https://travis-ci.org/seata/seata/builds)

**Comment by xingfudeshi** [comment]
Please ensure you've pulled the latest code of seata,then please run following commands to build.
```
mvn clean install -DskipTests=true -U
```
