### ISSUE TITLE
using @GlobalTransactional with @Transactional will cause global transaction timeout

### ISSUE THREAD

**Issue by 9Cobra** [seata/seata#1716]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
when i use the annotations of GlobalTransactional  and Transactional  on the same function, the local transaction will be blocked and then global transaction will be timeout

by the way, does seata support multiple datasource? just like use  postProcessBeanFactory to regist BeanDefinition and then use spring ioc to autowired, i try and it don't rollback. the scene like this: firstly i register ds1datasource, ds1jdbctemplate, ds1transactionmanager into ioc, ds2 is the same as ds1 and then i use autowired to inject but finally it fail to rollback 
some code like 
![image](https://user-images.githubusercontent.com/16607042/65737398-f8b74f00-e110-11e9-8b95-4dc76fe8987b.png)
updateuser rollback and updatestate by feignclient fails

i want help thanks

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by 9Cobra** [comment]
nobody come cross this issue?

**Comment by xingfudeshi** [comment]
seata supports multiple datasource,you need  to configure the DatasourceProxy for each of datasource.

**Comment by xingfudeshi** [comment]
Please remove @Transactional from the method which has annotated by @GlobalTransactional.

**Comment by 9Cobra** [comment]
i remember that seata support use @GlobalTransactional with @Transactional before, does it change? maybe i didn't notice that

**Comment by xingfudeshi** [comment]
I'm not sure.Please just try it.

**Comment by 9Cobra** [comment]
OK i'll try it again thanks~

**Comment by xingfudeshi** [comment]
try use @GlobalLock instead of @Transactional.

**Comment by 9Cobra** [comment]
i try it but it is still timeout,i dont know that is registing db dynamic  the cause of this issue ?

**Comment by xingfudeshi** [comment]
> i try it but it is still timeout,i dont know that is registing db dynamic the cause of this issue ? i use postProcessBeanFactory to regist bean
> 
> some logs:
> 2019-10-12 11:23:41.922 INFO [NettyServerNIOWorker_2_8]io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegTmMessage:131 -checkAuth for client:127.0.0.1:64877 vgroup:my_test_tx_group ok
> 2019-10-12 11:24:00.922 INFO [ServerHandlerThread_15_500]io.seata.server.coordinator.DefaultCore.begin:142 -Successfully begin global transaction xid = IP:8091:2024577115
> 2019-10-12 11:24:00.924 INFO [batchLoggerPrint_1]io.seata.core.rpc.DefaultServerMessageListenerImpl.run:199 -SeataMergeMessage timeout=60000,transactionName=insert()
> ,clientIp:127.0.0.1,vgroup:my_test_tx_group
> 
> 2019-10-12 11:25:01.652 INFO [TxTimeoutCheck_1]io.seata.server.coordinator.DefaultCoordinator.timeoutCheck:303 -Global transaction[IP:8091:2024577115] is timeout and will be rolled back.
> 2019-10-12 11:25:02.649 INFO [RetryRollbacking_1]io.seata.server.coordinator.DefaultCore.doGlobalRollback:346 -Successfully rollback global, xid = IP:8091:2024577115

Please increase the value of timeoutMills within @GlobalTransactional.

**Comment by 9Cobra** [comment]
> Please increase the value of timeoutMills within @GlobalTransactional.

it should be excuted successfully not timeout

**Comment by 9Cobra** [comment]
![image](https://user-images.githubusercontent.com/16607042/66695779-fbf93000-ecf7-11e9-8adf-8321260bdf7d.png)

when i do insert with local datasource, it can't get the db connection, and then timeout, i dont know why, can you help me ? thanks

**Comment by 9Cobra** [comment]
i know it, i set only one idle, seata will keep one connection and when other db exec request come in, it will be timeout. but why seata hold it all the time?

**Comment by xingfudeshi** [comment]
Seata will hold the connection before the branch transaction is complete.

**Comment by 9Cobra** [comment]
> Seata will hold the connection before the branch transaction is complete.

in fact, it makes other execs timeout. i dont know why maybe I don't understand the principle

**Comment by xingfudeshi** [comment]
Is that possible to provide a demo that can re-produce this problem?a zip or github repo.

**Comment by 9Cobra** [comment]
> Is that possible to provide a demo that can re-produce this problem?a zip or github repo.

it's easy, set the max idle of druid pool to 1. then other properties use default values

**Comment by xingfudeshi** [comment]
The pool size should not be set to 1.Because @GlobalTransactional and @Transactional are two different things.They'll need separately connection.

**Comment by 9Cobra** [comment]
got it thanks for your guidance
