### ISSUE TITLE
May I ask is there has any plan to support 'properties' style configuration? 

### ISSUE THREAD

**Issue by RootDriver** [seata/seata#1721]
## Why you need it?
Ⅰ.Application Using Seata
The config file named 'registry.conf', it's not bad. But I still hope it could be in 'properties', familiar to operate.

Ⅱ.Seata regist Nacos Discovery
When I use Nacos and Seata together, there were Dispersed configurations and takes pretty lines, because each configuration is a 'Data ID'. I sincerely hope those configurations could be centralized.

## How it could be?
When application use seata in 'properties' style, I could write all need configurations in a 'properties' file, like 'application.properties'; And I also could put those configurations into Nacos Configuration.

**Comment by jsbxyyx** [comment]
can you provide pr?

**Comment by xingfudeshi** [comment]
will support it in seata-spring-boot-starter which working in progress.
