### ISSUE TITLE
seata does not support mybatis batch update?

### ISSUE THREAD

**Issue by lolashe** [seata/seata#1733]
## Why you need it?
i need batch update for one db connection as follows
update user_account set remain_amount=0 where id=100;update user_account set remain_amount=100 where id=101;
when throw RuntimeException，rollback success！

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by zjinlei** [comment]
not yet supported.
We plan to support multiple sql with the same structure.

**Comment by lolashe** [comment]
> not yet supported.
> We plan to support multiple sql with the same structure.

Thank you. Are there any plans for which version to be implemented?

**Comment by zjinlei** [comment]
@lolashe Release GA version this month,this feature may be after GA.
