### ISSUE TITLE
insert sql can not getGeneratedKeys

### ISSUE THREAD

**Issue by jsbxyyx** [seata/seata#1736]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
insert sql can not rs.getGeneratedKeys()

because genKeys.getGeneratedKeys() operation in InsertExecutor, cause the rs cursor move to last.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by jKill** [comment]
Does this bug still exsit？

**Comment by jsbxyyx** [comment]
@jKill mysql not exists this bug, oracle exists.
