### ISSUE TITLE
Memory lock is not released

### ISSUE THREAD

**Issue by alichuanga** [seata/seata#1744]
The TM open transaction calls an RM, and the RM operates three table update operations. The data with the two table operations has the same primary key id. 
After the first request is successful, the second request will report a lock exception.

**Comment by zjinlei** [comment]
Confirmed.
Triggering conditions:
1.store.mode=file
2.Superimposed spring @Transaction
3.Different tables with the same pk

**Comment by zjinlei** [comment]
fixed.
release in 090
