### ISSUE TITLE
About a bug with nginx

### ISSUE THREAD

**Issue by shiyuecamus-ssy** [seata/seata#1748]
When your RPC calls URL as an nginx address, the default configuration of nginx automatically ignores the request header that it deems invalid. Then XID placed in the request header may be ignored at this time. This causes the global transaction to roll back without locating and taking effect. At present, my solution is to add HTTP in nginx.conf:

Underscores_in_headers on;

Ignore_invalid_headers off;

Two configurations. I hope you can put this problem in the document or readme to remind users who are using nginx!

**Comment by cmonkey** [comment]
发个PR哈

**Comment by xingfudeshi** [comment]
Thanks for your suggestion.
