### ISSUE TITLE
Whether to support manual trigger rollback

### ISSUE THREAD

**Issue by wander-soul** [seata/seata#1772]
因业务需求，需要根据情况作出手动触发回滚，通过GlobalTransactionContext.getCurrentOrCreate.rollback()并不能成功直接，spring 事务中有TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();可以实现手动回滚，seata有类型实现吗

**Comment by zjinlei** [comment]
GlobalTransactionRole needs to be the Launcher.

**Comment by wander-soul** [comment]
> GlobalTransactionRole needs to be the Launcher.

See the source, The GlobalTransactionRole must be Launcher, how to get GlobalTransaction status is Lacuncher?or there are other ways to control rollback in the second stage?
`    /**
     * Get GlobalTransaction instance bind on current thread.
     *
     * @return null if no transaction context there.
     */
    private static GlobalTransaction getCurrent() {
        String xid = RootContext.getXID();
        if (xid == null) {
            return null;
        }
        return new DefaultGlobalTransaction(xid, GlobalStatus.Begin, GlobalTransactionRole.Participant);
    }

    /**
     * Get GlobalTransaction instance bind on current thread. Create a new on if no existing there.
     *
     * @return new context if no existing there.
     */
    public static GlobalTransaction getCurrentOrCreate() {
        GlobalTransaction tx = getCurrent();
        if (tx == null) {
            return createNew();
        }
        return tx;
    }`

**Comment by zjinlei** [comment]
1.We discuss whether to expose GlobalTransactionRole
2.If you are using @GlobalTransactional, throw an exception to tm and roll back

**Comment by jKill** [comment]
According to your description, throw exceptions whenever you want to rollback in your transaction ,may meet your requirement

**Comment by slievrly** [comment]
@wander-soul TransactionManagerHolder.get().rollback(), setRollbackonly will support later.
