### ISSUE TITLE
rollbackFor does not work properly

### ISSUE THREAD

**Issue by 767248371** [seata/seata#1794]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
方法设置：    @GlobalTransactional(name = "fsp-create-order", rollbackFor = RuntimeException.class)

异常抛出：Exception

结果：应该不回滚，但是回滚了，我觉得rollbackOn方法有问题

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
public boolean rollbackOn(Throwable ex) {

        RollbackRule winner = null;
        int deepest = Integer.MAX_VALUE;

        if (this.rollbackRules != null) {
            for (RollbackRule rule : this.rollbackRules) {
                int depth = rule.getDepth(ex);
                if (depth >= 0 && depth < deepest) {
                    deepest = depth;
                    winner = rule;
                }
            }
        }

        return winner == null || !(winner instanceof NoRollbackRule);
    }

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
@767248371 Thansk for report.I'll fix it.

**Comment by xingfudeshi** [comment]
> * [ ]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> ### Ⅰ. Issue Description
> ### Ⅱ. Describe what happened
> If there is an exception, please attach the exception trace:
> 
> ```
> Just paste your stack trace here!
> ```
> 
> ### Ⅲ. Describe what you expected to happen
> 方法设置： @GlobalTransactional(name = "fsp-create-order", rollbackFor = RuntimeException.class)
> 
> 异常抛出：Exception
> 
> 结果：应该不回滚，但是回滚了，我觉得rollbackOn方法有问题
> 
> ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> 1. xxx
> 2. xxx
> 3. xxx
> 
> ### Ⅴ. Anything else we need to know?
> public boolean rollbackOn(Throwable ex) {
> 
> ```
>     RollbackRule winner = null;
>     int deepest = Integer.MAX_VALUE;
> 
>     if (this.rollbackRules != null) {
>         for (RollbackRule rule : this.rollbackRules) {
>             int depth = rule.getDepth(ex);
>             if (depth >= 0 && depth < deepest) {
>                 deepest = depth;
>                 winner = rule;
>             }
>         }
>     }
> 
>     return winner == null || !(winner instanceof NoRollbackRule);
> }
> ```
> 
> ### Ⅵ. Environment:
> * JDK version :
> * OS :
> * Others:

If the exception specified for rollbackFor is not found, other exceptions will be rolled back by default.
