### ISSUE TITLE
Why not upgrade spring 2 to spring 4 ?

### ISSUE THREAD

**Issue by tswstarplanet** [seata/seata#181]
I find that the spring fescar uses is 2.x version. It's really old. Why not upgrade to newer edition ?

**Comment by sharajava** [comment]
We do not depend on features of Spring on higher versions. So I think it is better to keep such dependency low. Anyway, it should NOT be a problem working with higher Spring in application projects. 

Thanks 👍

**Comment by Kiddinglife** [comment]
Hi @sharajava,
worthy of mentioning it in documentation.
Regards.

**Comment by leizhiyuan** [comment]
because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
