### ISSUE TITLE
v0.9.0 occur a bug 

### ISSUE THREAD

**Issue by suxinsen** [seata/seata#1814]
2019-10-24 16:03:57.872 ERROR io.netty.util.ResourceLeakDetector Line:317 - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:334)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)

**Comment by cmonkey** [comment]
需要更多的日志信息才能准确的知道是什么地方发生了忘记关闭bytebuff

**Comment by suxinsen** [comment]
问题目前没有再复现，从表现来看，mysql新增数据时，未使用主键自增策略导致异常信息的出现
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cmonkey"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月24日(星期四) 下午4:21
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"苏鑫森"<1324154699@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] v0.9.0 occur a bug  (#1814)




需要更多的日志信息才能准确的知道是什么地方发生了忘记关闭bytebuff

**Comment by xingfudeshi** [comment]
@suxinsen Thanks for report.Could you submit a PR to fix it?

**Comment by jKill** [comment]
麻烦贴下复现过程和环境
