### ISSUE TITLE
It is recommended to improve the performance of batch database operations

### ISSUE THREAD

**Issue by wilson2000x** [seata/seata#1818]
## Why you need it?
Business system development most likely involves simultaneous insert/update/delete to multiple records. However, currently seata inserts lock_key and rolls back bar by bar for multiple records.

## How it could be?
1)  improve the performance of batch insert lock_key into lock_table.
code at " core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java":
```java
 for (LockDO lockDO : unrepeatedLockDOs) {
                if (!doAcquireLock(conn, lockDO)) {
                    if (LOGGER.isInfoEnabled()) {
                        LOGGER.info("Global lock acquire failed, xid {} branchId {} pk {}", lockDO.getXid(),
                            lockDO.getBranchId(), lockDO.getPk());
                    }
                    conn.rollback();
                    return false;
                }
```
Optimization recommendations for Mysql:
It is suggested to replace " for( insert into table values() )"  with " insert into table(...) values(),(),()..." 

2)  improve the performance of batch undo .
code at " rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java"
```java
    /**
     * Execute on.
     * Execute on.updated by wilson@20191018
     *
     * @param conn the conn
     * @throws SQLException the sql exception
     */
    public void executeOn(Connection conn) throws SQLException {

}
```
Optimization recommendations for Mysql:
It is suggested to replace " for( insert into table values() )"  with " insert into table(...) values(),(),()..." ;
It is suggested to replace " for( update table set field1=value1 where pkid=id1 ...)"  with "
update table set 
  field1= case when pkid=id1 then field1=value1 
                       when pkid=id2 then field2=value2 end
where pkid in (id1,id2)
" ;
It is suggested to replace " for( delete from table where pkid=id1... )"  with " delete from table where pkid in (id1,id2,...)" ;

**Comment by zjinlei** [comment]
Thanks.
The single advantage is that the conflicting key can be clearly located, and the disadvantage is that the performance is too poor.
Could you submit a PR to improve it?
I recommend using jdbc batch,because we need to support various databases.

**Comment by wilson2000x** [comment]
sorry，I recently busy working. And I can only test it with the MYSQL. It would be better if you could improve the performance of it and to support various databases.  I can provide the source code that I have temporarily optimized for MYSQL.

**Comment by wilson2000x** [comment]
Thanks. On the second point, the rollback also needs to be changed to batch, otherwise the rollback will still have poor performance . code at " rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java"

**Comment by zjinlei** [comment]
Undo needs to check data one by one

**Comment by wilson2000x** [comment]
I know, but you just need to improve the last step "executeOn" at code  " rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java"
![image](https://user-images.githubusercontent.com/56192075/67635447-6d44ff80-f902-11e9-83b2-f98eb738f790.png)

you can change it like this :
`

    /**
     * Execute on.updated by wilson@20191018 only for MYSQL
     *
     * @param conn the conn
     * @throws SQLException the sql exception
     */
    public void executeOn(Connection conn) throws SQLException {
        if (!IS_UNDO_DATA_VALIDATION_ENABLE || this.dataValidationAndGoOn(conn)) {
            try {
                String undoSQL = this.buildUndoSQL();
                TableRecords undoRows = this.getUndoRows();

                if (undoSQL.toLowerCase().indexOf(CHECK_SQL_FOR_DELETE) == 0) {
                    executeOnForDelete(conn, undoRows, undoSQL);
                } else if (undoSQL.toLowerCase().indexOf(CHECK_SQL_FOR_INSERT) == 0) {
                    executeOnForInsert(conn, undoRows, undoSQL);
                } else if (undoSQL.toLowerCase().indexOf(CHECK_SQL_FOR_UPDATE) == 0) {
                    executeOnForUpdate(conn, undoRows, undoSQL);
                }
            } catch (Exception var11) {
                if (var11 instanceof SQLException) {
                    throw (SQLException) var11;
                } else {
                    throw new SQLException(var11);
                }
            }
        }
    }

    public void executeOnForDelete(Connection conn, TableRecords undoRows, String undoSQL) throws SQLException {
//                    DELETE FROM xalink_order WHERE id = ?
//                    DELETE FROM xalink_order WHERE id in (?,?,?)
        PreparedStatement undoPST = null;

        //1.prepare where
        boolean firstWhile = true;
        StringBuilder sbUndoSQL = new StringBuilder();
        sbUndoSQL.append(undoSQL.replaceAll("= ", " in ("));
        for (int i=0;i<undoRows.size();i++) {
            if (!firstWhile) {
                sbUndoSQL.append(",?");
            } else {
                firstWhile = false;
            }
        }
        sbUndoSQL.append(")");

        try {
            undoPST = conn.prepareStatement(sbUndoSQL.toString());

            //fill values
            Iterator rowIterator = undoRows.getRows().iterator();
            int i = 1;
            while (rowIterator.hasNext()) {
                Row undoRow = (Row) rowIterator.next();
                ArrayList<Field> undoValues = new ArrayList();
                Field pkValue = null;
                Iterator fieldIterator = undoRow.getFields().iterator();

                while (fieldIterator.hasNext()) {
                    Field field = (Field) fieldIterator.next();
                    if (field.getKeyType() == KeyType.PrimaryKey) {
                        pkValue = field;
                        break;
                    }
                }
                undoPST.setObject(i, pkValue.getValue(), pkValue.getType());
                i++;
            }

            undoPST.executeUpdate();
        }finally {
            if (undoPST != null) {
                try {
                    undoPST.close();
                } catch (SQLException e) {
                }
            }
        }

    }

    public void executeOnForInsert( Connection conn, TableRecords undoRows, String undoSQL) throws SQLException {
//                    INSERT INTO xalink_order (user_id, money, id) VALUES (?, ?, ?)
//                    INSERT INTO xalink_order (user_id, money, id) VALUES (?, ?, ?),(?, ?, ?),(?, ?, ?)

        PreparedStatement undoPST = null;

        //prepare values statement
        boolean firstWhile = true;
        String undoSQLTail = undoSQL.substring(undoSQL.indexOf("?") - 1);
        StringBuilder sbUndoSQL=new StringBuilder();
        sbUndoSQL.append(undoSQL);
        for (int i = 0; i < undoRows.size(); i++) {
            if (!firstWhile) {
                sbUndoSQL.append(",");
                sbUndoSQL.append(undoSQLTail);
            } else {
                firstWhile = false;
            }
        }

        try {
            undoPST = conn.prepareStatement(sbUndoSQL.toString());

            //fill values
            Iterator iteratorRows = undoRows.getRows().iterator();
            int rowsIndex = 0;
            while (iteratorRows.hasNext()) {
                Row undoRow = (Row) iteratorRows.next();
                ArrayList<Field> undoValues = new ArrayList();
                Field pkValue = null;
                Iterator iteratorFields = undoRow.getFields().iterator();

                while (iteratorFields.hasNext()) {
                    Field field = (Field) iteratorFields.next();
                    if (field.getKeyType() == KeyType.PrimaryKey) {
                        pkValue = field;
                    } else {
                        undoValues.add(field);
                    }
                }
                this.undoPrepareNewForInsert(rowsIndex, undoPST, undoValues, pkValue);
                rowsIndex++;
            }
            undoPST.executeUpdate();
        }finally {
            if (undoPST != null) {
                try {
                    undoPST.close();
                } catch (SQLException e) {
                }
            }
        }
    }

    public void executeOnForUpdate(Connection conn, TableRecords undoRows, String undoSQL) throws SQLException {
//      UPDATE xalink_order SET user_id = ?, money = ? WHERE id = ?
//        UPDATE xalink_order SET user_id = case
//                when id=? then ?
//                when id=? then ?
//                end
//                , money = case
//                when id=? then ?
//                when id=? then ?
//                end
//        WHERE id in (?,?)

        PreparedStatement undoPST = null;

        //0.get pkName
        String pkName = undoRows.getTableMeta().getPkName();
        //1.get case when and where
        boolean firstWhile = true;
        StringBuilder sbCaseWhen = new StringBuilder();
        StringBuilder sbWhere = new StringBuilder();
        for (int i = 0; i < undoRows.size(); i++) {
            if (!firstWhile) {
                sbWhere.append(",");
                sbWhere.append("?");
                sbCaseWhen.append(" when ");
                sbCaseWhen.append(pkName);
                sbCaseWhen.append(" =? then ? ");
            } else {
                sbWhere.append(" in (?");
                sbCaseWhen.append("case when ");
                sbCaseWhen.append(pkName);
                sbCaseWhen.append(" =? then ? ");

                firstWhile = false;
            }
        }
        sbWhere.append(")");
        sbCaseWhen.append(" end ");

        //2. get Last undoSql
        StringBuilder sbUndoSQL = new StringBuilder();
        String[] subUndoSQL = undoSQL.split("\\?");
        for (int i = 0; i < subUndoSQL.length; i++) {
            String str = subUndoSQL[i];
            if (i == subUndoSQL.length - 1) {
                str = str.replaceAll("=", "");
                sbUndoSQL.append(str);
                sbUndoSQL.append(sbWhere);
                break;
            } else {
                sbUndoSQL.append(str);
                sbUndoSQL.append(sbCaseWhen);
            }
        }

        //3. fill values
        try {
            undoPST = conn.prepareStatement(sbUndoSQL.toString());
            Iterator iteratorRows2 = undoRows.getRows().iterator();
            int rowsCount = undoRows.size();
            int rowsIndex = 0;
            while (iteratorRows2.hasNext()) {
                Row undoRow = (Row) iteratorRows2.next();
                ArrayList<Field> undoValues = new ArrayList();
                Field pkValue = null;

                Iterator iteratorFields = undoRow.getFields().iterator();
                while (iteratorFields.hasNext()) {
                    Field field = (Field) iteratorFields.next();
                    if (field.getKeyType() == KeyType.PrimaryKey) {
                        pkValue = field;
                    } else {
                        undoValues.add(field);
                    }
                }
                this.undoPrepareNewForUpdate(rowsIndex, rowsCount, undoPST, undoValues, pkValue);
                rowsIndex++;
            }

            //4. excute
            undoPST.executeUpdate();
        }finally {
            if (undoPST != null) {
                try {
                    undoPST.close();
                } catch (SQLException e) {
                }
            }
        }
    }

    /**
     * Undo prepare.New
     *
     * @param undoPST    the undo pst
     * @param undoValues the undo values
     * @param pkValue    the pk value
     * @throws SQLException the sql exception
     */
    protected void undoPrepareNewForInsert(int rowsIndex, PreparedStatement undoPST, ArrayList<Field> undoValues, Field pkValue)
            throws SQLException {
        int undoIndex = rowsIndex * (undoValues.size() + 1);
        for (Field undoValue : undoValues) {
            undoIndex++;
            if (undoValue.getType() == JDBCType.BLOB.getVendorTypeNumber()) {
                SerialBlob serialBlob = (SerialBlob) undoValue.getValue();
                if (serialBlob != null) {
                    undoPST.setBlob(undoIndex, serialBlob.getBinaryStream());
                } else {
                    undoPST.setObject(undoIndex, null);
                }
            } else if (undoValue.getType() == JDBCType.CLOB.getVendorTypeNumber()) {
                SerialClob serialClob = (SerialClob) undoValue.getValue();
                if (serialClob != null) {
                    undoPST.setClob(undoIndex, serialClob.getCharacterStream());
                } else {
                    undoPST.setObject(undoIndex, null);
                }
            } else {
                undoPST.setObject(undoIndex, undoValue.getValue(), undoValue.getType());
            }
        }
        // PK is at last one.
        // INSERT INTO a (x, y, z, pk) VALUES (?, ?, ?, ?)
        // UPDATE a SET x=?, y=?, z=? WHERE pk = ?
        // DELETE FROM a WHERE pk = ?
        undoIndex++;
        undoPST.setObject(undoIndex, pkValue.getValue(), pkValue.getType());
    }


    /**
     * Undo prepare.New for update
     *
     * @param undoPST    the undo pst
     * @param undoValues the undo values
     * @param pkValue    the pk value
     * @throws SQLException the sql exception
     */
    protected void undoPrepareNewForUpdate(int rowsIndex, int rowsCount, PreparedStatement undoPST, ArrayList<Field> undoValues, Field pkValue)
            throws SQLException {
//                UPDATE xalink_order SET user_id = case
//                when id=? then ?
//                when id=? then ?
//                end
//                , money = case
//                when id=? then ?
//                when id=? then ?
//                end
//        WHERE id in (?,?)
        int undoIndex = rowsIndex * 2 + 1;

        for (int i = 0; i < undoValues.size(); i++) {
            Field undoValue = undoValues.get(i);

            //1.set pk
            undoPST.setObject(undoIndex, pkValue.getValue(), pkValue.getType());

            //2.set unodValue
            if (undoValue.getType() == JDBCType.BLOB.getVendorTypeNumber()) {
                SerialBlob serialBlob = (SerialBlob) undoValue.getValue();
                if (serialBlob != null) {
                    undoPST.setBlob(undoIndex + 1, serialBlob.getBinaryStream());
                } else {
                    undoPST.setObject(undoIndex + 1, null);
                }
            } else if (undoValue.getType() == JDBCType.CLOB.getVendorTypeNumber()) {
                SerialClob serialClob = (SerialClob) undoValue.getValue();
                if (serialClob != null) {
                    undoPST.setClob(undoIndex + 1, serialClob.getCharacterStream());
                } else {
                    undoPST.setObject(undoIndex + 1, null);
                }
            } else {
                undoPST.setObject(undoIndex + 1, undoValue.getValue(), undoValue.getType());
            }

            //set where at lastField
            if (i == undoValues.size() - 1) {
                //get index of the pkKey
                undoIndex = undoIndex + (rowsCount - (rowsIndex + 1)) * 2 + 2 + rowsIndex;
                undoPST.setObject(undoIndex, pkValue.getValue(), pkValue.getType());
                break;
            }
            undoIndex = undoIndex + rowsCount*2;
        }
    }


`

**Comment by zjinlei** [comment]
not enough time
after 1.0

**Comment by wilson2000x** [comment]
I understand,looking forward to the 1.1 version.

**Comment by zjinlei** [comment]
Whether to support multiple modifications to a row of data?
eg. update A+1-->update A+2
Need to restore one by one to check when undo

**Comment by wilson2000x** [comment]
If your service  add the @Transcation, you can't Operate on the same record.  so you can  Remove the @Trancational for it;

**Comment by wilson2000x** [comment]
P.S. The lock key itself has been limited to one submission without duplicate keys.

**Comment by zjinlei** [comment]
The same global transaction lock can be reentered

**Comment by wilson2000x** [comment]
yes.  So as long as you don't operate on the same record in a local transaction, you will have more than one record  in the undo_log.   "io.seata.rm.datasource.undo.AbstractUndoExecutor#executeOn" is still base on the one record of the undo_log, and its order. Therefore, we just need to improve the "executeOn".
![image](https://user-images.githubusercontent.com/56192075/67674988-f28aeb80-f9b8-11e9-87f0-7f35f1dbacde.png)
