### ISSUE TITLE
seata server can't start in jdk10 win7 x64

### ISSUE THREAD

**Issue by wendal** [seata/seata#1819]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
download seata-server.zip from release, and unzip to `D:\`,  then run it.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
D:\seata>bin\seata-server.bat
Unrecognized VM option 'UseFastAccessorMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

D:\seata>java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

D:\seata>
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 10.0.2
- OS : Windows 7 x64
- Others:

**Comment by helloworlde** [comment]
Please switch to Java 8 and then server can start normally.
