### ISSUE TITLE
Seata0.9.0 Pause and recover of transaction does not work

### ISSUE THREAD

**Issue by lolashe** [seata/seata#1828]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

1、String unbindXid = RootContext.unbind();
2、my business code  batch operate db records（because seata not support batch update for mysql）
3、RootContext.bind(unbindXid);

### Ⅱ. Describe what happened
step 2 throw Exception，when i use version 0.8.0 step 2 will execute successful

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
step 2 execute success

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@lolashe throw exception on step 2?

**Comment by lolashe** [comment]
@slievrly yes，0.9.0 version will throw exception，but 0.8.0 will execute successfully，it seems that exclude from global transaction
