### ISSUE TITLE
There will be two identical EventListener add to EventDispatcher when using Nacos naming service.

### ISSUE THREAD

**Issue by zhangxb1987** [seata/seata#1830]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/24668174/67682240-db082e80-f9c9-11e9-911c-4ef018a54ea5.png)

These two init method invocations trigger RegistryService lookup in two separate threads:

![image](https://user-images.githubusercontent.com/24668174/67682484-700b2780-f9ca-11e9-8c65-cc8c95766cec.png)

I look into the Nacos implementation,which is :
![image](https://user-images.githubusercontent.com/24668174/67682663-d98b3600-f9ca-11e9-9171-be7fd2c3405f.png)

I think the highlighted code block shoud be synchronized，if not，the if block code will be executed twice,and there will be two identical EventListener add to EventDispatcher.

### Ⅱ. Describe what happened

  And because of the two event listeners, somtimes there will be ConcurrentModificationException thrown in EventDispatcher showed bellow. 
This is because the listeners may be modified when iterating:

![image](https://user-images.githubusercontent.com/24668174/67683680-c2e5de80-f9cc-11e9-802d-57027dbfb795.png)

```
[com.alibaba.nacos.naming.client.listener] ERROR com.alibaba.nacos.client.naming - [NA] notify error for service: DEFAULT_GROUP@@serverAddr, clusters: default
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.alibaba.nacos.client.naming.core.EventDispatcher$Notifier.run(EventDispatcher.java:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
Nice analysis.

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/67914394-f3936700-fbca-11e9-85f3-17ea1cc78bfd.png)
The latest nacos version has used CopyOnWriteArrayList to prevent concurrency issues

**Comment by zhangxb1987** [comment]
> The latest nacos version has used CopyOnWriteArrayList to prevent concurrency issues


![image](https://user-images.githubusercontent.com/24668174/67916074-8b934f80-fbcf-11e9-9cfd-859959931531.png)

**Comment by zhangxb1987** [comment]
> ![image](https://user-images.githubusercontent.com/8758457/67914394-f3936700-fbca-11e9-85f3-17ea1cc78bfd.png)
> The latest nacos version has used CopyOnWriteArrayList to prevent concurrency issues

I think the code you pasted is in the `com.alibaba.nacos.client.config.impl.EventDispatcher `,but actually the Nacos client contains two EventDispatcher as show bellow:

actually the `com.alibaba.nacos.client.naming.core.EventDispatcher ` is in use.

and also when i  looked into the latest version of nacos client,i found the code no difference.

![image](https://user-images.githubusercontent.com/24668174/67916167-ce552780-fbcf-11e9-84da-f6445f3ae71e.png)
