### ISSUE TITLE
Oracle 无效的列类型

### ISSUE THREAD

**Issue by fengjiangqwe** [seata/seata#1831]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1、Oracle的表字段类型是nvarchar2时回滚报无效的列类型，字段类型是varchar2就不会报这个错
2、操作Oracle同义词时，报Could not found any index in the table，dbmd操作中的Schema是小写的，请问是不是不支持同义词妮

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅵ. Environment:

- JDK version : JDK1.8
- OS :
- Others: springcloud-jpa-seata:0.8.1

**Comment by l81893521** [comment]
thanks for you report
