### ISSUE TITLE
[About commit]What branch should we choose ?

### ISSUE THREAD

**Issue by tswstarplanet** [seata/seata#185]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

What branch should be the base branch if we want to contribute the code. I set the master branch as the upstream and push commit. I find it have some problems. So should we set the develop branch as the upstream and fetch it ?

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@tswstarplanet yes，develop is the latest code branch and you should propose the branch of PR

**Comment by leizhiyuan** [comment]
It seems ok now.

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
