### ISSUE TITLE
获取 pk name容易出现 IndexOutOfBoundsException

### ISSUE THREAD

**Issue by zhaoyunxing92** [seata/seata#1854]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### 问题描述

数据库表如果没有设置主键的话根据代码,则容易出现数组越界

```java
io.seata.rm.datasource.sql.struct.TableMeta#getPkName
public String getPkName() {
        return getPrimaryKeyOnlyName().get(0);
    }
```
### 异常信息
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```
### 系统环境

- JDK version : 1.8
- OS : deepin
- Others: seata:0.7.1

**Comment by slievrly** [comment]
@zhaoyunxing92 must contain a single primary key.

**Comment by zhaoyunxing92** [comment]
> @zhaoyunxing92 must contain a single primary key.

我有uk键的没有pk键
![代码检查逻辑](https://user-images.githubusercontent.com/18088210/67923173-fe102980-fbe7-11e9-85d6-602fc439c09e.png)
