### ISSUE TITLE
非@GlobalTransactional事务，不应该有seata的限制，比如不支持联合主键，不支持批量sql语句

### ISSUE THREAD

**Issue by qinhua998** [seata/seata#1855]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
为了较少影响业务，seata的特殊规则应该只影响seata的事务业务，不应该去影响非seata事务的业务。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
非@GlobalTransactional事务，不应该有seata的限制，比如不支持联合主键，不支持批量sql语句。

**Comment by wendal** [comment]
refer: https://nutz.cn/yvr/t/pbr3s8lsvogafout1p9fm2njjo

quartz 没使用到seata的特性, 却导致系统无法启动

**Comment by jsbxyyx** [comment]
@qinhua998 not in global transaction, union primary key bug fix in latest develop branch.

**Comment by slievrly** [comment]
@qinhua998 let's discuss how the integration and cooperation between nutzboot and seata? what do you think?

**Comment by wendal** [comment]
> @qinhua998 not in global transaction, union primary key bug fix in latest develop branch.

then, quartz shall be fine.

 

> @qinhua998 let's discuss how the integration and cooperation between nutzboot and seata? what do you think?

it is done yet. refer: https://github.com/nutzam/nutzboot/tree/dev/nutzboot-starter/nutzboot-starter-seata

**Comment by zjinlei** [comment]
> refer: https://nutz.cn/yvr/t/pbr3s8lsvogafout1p9fm2njjo
> 
> quartz 没使用到seata的特性, 却导致系统无法启动

this is seata bug,already fixed, pending release.

**Comment by qinhua998** [comment]
@wendal ,thanks
but, when is the expected release time of the version supporting union primary key?
Also, will the problem of not supporting batch SQL be solved?

**Comment by slievrly** [comment]
@qinhua998 currently,support batch insert sql in GlobalTransactional

**Comment by zjinlei** [comment]
https://github.com/seata/seata/pull/1805
