### ISSUE TITLE
UpdateExecutor.afterimage 方法可去掉数据库查询

### ISSUE THREAD

**Issue by beston123** [seata/seata#1864]
## Why you need it?
UpdateExecutor.afterimage 没必要查询数据库，提升性能。

## How it could be?
在正常情况下，更新后的image可以通过updateSQL推理出来，而不用查一次数据库结果来组装image。如果有特殊情况，可以加个配置强制从数据库查询最新结果

**Comment by beston123** [comment]
InsertExecutor.afterimage也可以省去？

**Comment by jsbxyyx** [comment]
mysql update case:
1. update statement set column is function, can not get column value.
2. table column is timestamp type and like `logtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`

**Comment by jsbxyyx** [comment]
Can be partially optimized.
