### ISSUE TITLE
批量插入，批量更新方法不支持？

### ISSUE THREAD

**Issue by lfcx778899** [seata/seata#1868]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
数据库:MySQL 5.7 
Java :1.8
seata:0.9.0
Win10
### Ⅱ. Describe what happened
配置文件：
![image](https://user-images.githubusercontent.com/23076546/68065080-ef984e00-fd5e-11e9-865c-47585ff9f290.png)
mapper中新增内容
![image](https://user-images.githubusercontent.com/23076546/68065101-2706fa80-fd5f-11e9-8414-0d14ee52b76b.png)
但是在测试批量更新的时候，报错：
![image](https://user-images.githubusercontent.com/23076546/68065111-47cf5000-fd5f-11e9-92c7-1c7b6010d10b.png)

从控制台信息中看到
![image](https://user-images.githubusercontent.com/23076546/68065130-7c430c00-fd5f-11e9-990f-cd9d0844a759.png)
这里面的路径和配置文件中的内容不一致，“？”后面的内容不见了，不清楚是不是这里的问题。
我想知道，是现在还没支持批量插入/批量更新；还是我哪里设置有问题，谢谢！

**Comment by jsbxyyx** [comment]
Multiple statements separated by semicolons are not currently supported.

**Comment by lfcx778899** [comment]
以后会支持这种方法吗？
如果会，预计哪一个版本能支持？
是否更好的实现批量操作的方式？有没有例子可以借鉴一下
谢谢！

**Comment by eastbadman** [comment]
遇到了一样的问题     想知道什么时候会支持批量操作

**Comment by lfwer** [comment]
0.9.0.1版本已支持

**Comment by lfwer** [comment]
0.8.0也支持

**Comment by lfcx778899** [comment]
> 0.8.0也支持

这两个版本我刚刚试了一下，都不行；方不方便把你实现的过程发一下，看一下是哪里的问题

0.9.0.1的报错信息

![image](https://user-images.githubusercontent.com/23076546/69897893-efef2d80-138c-11ea-994e-f8212499e507.png)

0.8.0的报错信息

![image](https://user-images.githubusercontent.com/23076546/69897909-19a85480-138d-11ea-98c8-4aa35ef14af7.png)

**Comment by wangj3081** [comment]
我也遇到了一样的问题，用的是 1.0.0 的版本，依旧是不支持多个分号的更新操作

**Comment by FrancisQAQ** [comment]
项目用的io.seata:seata-all:1.1.0，也不支持批量更新语句

**Comment by jsbxyyx** [comment]
@wangj3081 @FrancisQAQ   use 1.2.0

**Comment by DaiZero** [comment]
@jsbxyyx  我们升级到了1.3.0，批量插入数据量过多的就会报错，请问你遇到过吗？

**Comment by yipanbo** [comment]
> [@jsbxyyx](https://github.com/jsbxyyx) 我们升级到了1.3.0，批量插入数据量过多的就会报错，请问你遇到过吗？

我们用的1.4.2的版本，批量插入数据多的话也是报错，不知道怎么搞
