### ISSUE TITLE
seata0.9.0 Fail to store global session FileTransactionStoreManager.saveHistory()方法后会出现这个异常

### ISSUE THREAD

**Issue by fx1061076658** [seata/seata#1875]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/5327286/68186900-35b01480-ffe0-11e9-8a59-323386e04c20.png)
![image](https://user-images.githubusercontent.com/5327286/68186917-43659a00-ffe0-11e9-9d17-7ac124ab0ded.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/68192952-22f00c80-ffed-11e9-8ccd-af5c38663446.png)
补图
