### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError:

### ISSUE THREAD

**Issue by wanming001** [seata/seata#1880]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
2019-11-08 11:55:28.395 ERROR[NettyServerNIOWorker_32_32]io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:424 -0318
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 134217728 byte(s) of direct memory (used: 1073741824, max: 1073741824)

### Ⅵ. Environment:

- JDK version : 1.8
- OS : linux
- Others:

**Comment by cmonkey** [comment]
简单的修改就是去启动脚本里面把-XX:MaxDirectMemorySize　的值改大看看

**Comment by wanming001** [comment]
建议设置多大这个值 @cmonkey

**Comment by cmonkey** [comment]
![image](https://user-images.githubusercontent.com/664050/68454600-1a3d4780-0234-11ea-92cf-eaf1ebf0ac01.png)
可以试着在启动脚本上加上图上的参数，MaxDirectMemorySize的值可以修改为heapSize  / 2

**Comment by wanming001** [comment]
Tanker you @cmonkey
