### ISSUE TITLE
RemotingParser load twice

### ISSUE THREAD

**Issue by charish00** [seata/seata#1901]
### Image
![image](https://user-images.githubusercontent.com/9687323/68840341-8371fe80-06fd-11ea-854f-c64bb305d928.png)

### Environment:

- JDK version : jdk12
- OS : windows
- Others:

**Comment by zjinlei** [comment]
Clean when packaged, otherwise it will be superimposed
mvn clean install
![image](https://user-images.githubusercontent.com/20024955/68841502-b1584280-06ff-11ea-93cf-e9e3b252ba97.png)

**Comment by charish00** [comment]
thx~
