### ISSUE TITLE
travis ci print too many error stack log

### ISSUE THREAD

**Issue by slievrly** [seata/seata#1915]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/8758457/69129600-ac253a00-0ae9-11ea-9d91-124076d86959.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by helloworlde** [comment]
Had fixed in #1885
