### ISSUE TITLE
不能 序列化 oracle.sql.TIMESTAMP

### ISSUE THREAD

**Issue by kejianchun** [seata/seata#1922]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["afterImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[14]->io.seata.rm.datasource.sql.struct.Field["value"]->oracle.sql.TIMESTAMP["stream"])

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 表字段类型（TIMESTAMP(6)）

### Ⅵ. Environment:

- JDK version : jdk1.8
- OS :window10
- Others: ojdbc6.11.2.0.3 + oracle11g +seata-all-0.9.0.1.jar

**Comment by zjinlei** [comment]
https://github.com/seata/seata/issues/2047
