### ISSUE TITLE
ORACLE 字段类型NVARCHAR2 ， branchRollback 

### ISSUE THREAD

**Issue by kejianchun** [seata/seata#1923]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

INFO  io.seata.rm.datasource.DataSourceManager - branchRollback failed reason [Branch session rollback failed and try again later xid = 10.169.2.189:8091:2028034600 branchId = 2028034601 无效的列类型]

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 数据库表的字段类型为 NVARCHAR2(64)

### Ⅵ. Environment:

- JDK version :jdk1.8
- OS :win10
- Others:ojdbc6 +oracle11g + seata-all-0.9.0.1

**Comment by zjinlei** [comment]
refer: https://github.com/seata/seata/pull/1863

**Comment by zjinlei** [comment]
Can use 1.0.0-SNAPSHOT, continuous release.
https://oss.sonatype.org/#nexus-search;gav~io.seata~seata-all~~~~kw,versionexpand
If successful, please close the issue.
