### ISSUE TITLE
批量更新的时候速度慢

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#1933]
### 前置条件以及情景

seata版本：0.9.0
MySQL版本：5.7
场景：批量更新2w条数据。
批量更新的时候查询比较慢，在不使用seata的时候用时800ms，加上seata之后的用时18s。

### 发生的原因

跟踪代码之后发现主要出现在以下两个地方。
1. 构建afterImage的时候使用id=1 or id=2 or id=3的形式查询，在性能上有问题。`BaseTransactionalExecutor.buildWhereConditionByPKs`
2. 构建lockKey的时候，在循环里面使用`TableRecords.pkRows()`获取pk的列表，然后再通过`List.size()`获取pk的长度，而`TableRecords.pkRows()`里面每次都会把所有的记录都遍历一次才能得出一个pk列表。建议修改为只在循环外获取一次pk列表。
原代码如下：
```java
// BaseTransactionalExecutor
protected String buildLockKey(TableRecords rowsIncludingPK) {
    if (rowsIncludingPK.size() == 0) {
        return null;
    }
    StringBuilder sb = new StringBuilder();
    sb.append(rowsIncludingPK.getTableMeta().getTableName());
    sb.append(":");
    int filedSequence = 0;
    for (Field field : rowsIncludingPK.pkRows()) {
        sb.append(field.getValue());
        filedSequence++;
        if (filedSequence < rowsIncludingPK.pkRows().size()) {
            sb.append(",");
        }
    }
    return sb.toString();
}
```
建议修改为：
```java
// BaseTransactionalExecutor
protected String buildLockKey(TableRecords rowsIncludingPK) {
    if (rowsIncludingPK.size() == 0) {
        return null;
    }
    StringBuilder sb = new StringBuilder();
    long start = System.currentTimeMillis();
    sb.append(rowsIncludingPK.getTableMeta().getTableName());
    sb.append(":");
    int filedSequence = 0;
    List<Field> pkRows = rowsIncludingPK.pkRows();
    for (Field field : pkRows) {
        sb.append(field.getValue());
        filedSequence++;
        if (filedSequence < pkRows.size()) {
            sb.append(",");
        }
    }
    return sb.toString();
}
```

**Comment by zjinlei** [comment]
Thanks.
I think you are suitable to submit this pr.

**Comment by zjinlei** [comment]
please optimize InsertExecutor.afterImage..buildTableRecords together

**Comment by xingfudeshi** [comment]
Welcome submit a PR to optimize it.

**Comment by caohdgege** [comment]
OK,I will deal with it soon.

**Comment by caohdgege** [comment]
i will just optimize UpdateExecutor.afterImage only. because i think it's not nessory to query database when insert. 
the only field can be use when rollback is the primary key and the primary key is known before query database.
see #1864

**Comment by zjinlei** [comment]
> i will also optimize UpdateExecutor.afterImage.
> but i think it's not nessory to query database when insert. the only field can be use when rollback is the primary key and the primary key is known before query database.
> see #1864
> @zjinlei

Insert.afterImage only optimize the first point you mentioned.
About 1864,  It is difficult to guarantee data correctness, such as parsing function parameters.
