### ISSUE TITLE
Seata0.9.0版本Server启动报错-mysql8.0.11

### ISSUE THREAD

**Issue by uzdz** [seata/seata#1934]
驱动Jar：mysql-connector-java-8.0.11.jar
Mysql数据库版本：8.0.17

file.conf参数配置如下（seata库已创建且导入了db_store.sql）：
![image](https://user-images.githubusercontent.com/28328355/69477278-34277e80-0e1f-11ea-8bcc-5b501476836a.png)

执行命令：sh seata-server.sh -m db

报错异常如下：
![image](https://user-images.githubusercontent.com/28328355/69477261-fcb8d200-0e1e-11ea-8cae-8f6d22d706c1.png)

![image](https://user-images.githubusercontent.com/28328355/69477291-6e911b80-0e1f-11ea-9251-d524f39a341e.png)

至此未修改另外其他配置，请问是什么原因呢，看报错是SQL语句查询问题？

**Comment by jsbxyyx** [comment]
@uzdz can you provider mysql driver version?
you mysql driver version is 8.0.11?

**Comment by jsbxyyx** [comment]
@uzdz you mysql driver version is 8.0.11, this is mysql bug. [DatabaseMetaDataUsingInfoSchema#getTables fails if method arguments are null](https://bugs.mysql.com/bug.php?id=90887).
Please try upgrading the mysql driver version.

**Comment by uzdz** [comment]
> @uzdz you mysql driver version is 8.0.11, this is mysql bug. [DatabaseMetaDataUsingInfoSchema#getTables fails if method arguments are null](https://bugs.mysql.com/bug.php?id=90887).
> Please try upgrading the mysql driver version.

No such bug after upgrading to mysql driver version 8.0.18, Thank.
