### ISSUE TITLE
FileTransactionStoreManager is never close so the seataFile could not be delete

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#1937]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

FileTransactionStoreManagerTest test failure, the reason is that `FileTransactionStoreManager.currRaf` is holding the file and the `currRaf` never close. so when call `seataFile.delete` will return a value `false`.

### Ⅲ. Describe what you expected to happen

FileTransactionStoreManager provider a method to close currRaf, so that the file can be delete success.

### Ⅵ. Environment:

- JDK version : oracle jdk8
- OS : windows 10
- seata: 1.0.0-SNAPSHOT

**Comment by slievrly** [comment]
check FileTransactionStoreManagerTest#testBigDataWrite() testFindTimeoutAndSave() is ok, can't reproduce.

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/69694320-481afb00-1113-11ea-8cf9-9d05eafd85eb.png)

**Comment by caohdgege** [comment]
I try to run `mvn package` in win10 and Ubuntu18.04lts, it can pass in ubuntu but failure in win10.

**Comment by caohdgege** [comment]
the error is:
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   FileTransactionStoreManagerTest.testBigDataWrite:68 expected: <true> but was: <false>
[ERROR]   FileTransactionStoreManagerTest.testFindTimeoutAndSave:114 expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 94, Failures: 2, Errors: 0, Skipped: 1

**Comment by slievrly** [comment]
@caohdgege so these error can reproduce on wins OS？I need to check with others.

**Comment by caohdgege** [comment]
yes, you can try it in  win10，java version oracle jdk8 and Apache Maven 3.6.3.
