### ISSUE TITLE
RM uses error jdbc url as resouceId to register to TC, when using mysql cluster and low version mysql connector java

### ISSUE THREAD

**Issue by VainEffort** [seata/seata#1941]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I'm using mysql cluster as my datesource, so I configure 
```
spring.datasource.url = jdbc:mysql://ip1:port1,ip2:port2/seata
```
when application starts, it registers RM to TC with resourceId:jdbc:mysql://ip1:port1,ip2:por2/
datebase is lost

when I configure:
```
spring.datasource.url = jdbc:mysql://ip1:port1/seata
```
the resourceId gets nomal to "jdbc:mysql://ip1:port1/seata"

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : JDK1.8
- OS : linux
- Others: seata 0.9.0,  mysql-connector-java 5.1.44

**Comment by zjinlei** [comment]
<img width="815" alt="7973F25F-7FF9-426C-B363-CC869F5BE8CF" src="https://user-images.githubusercontent.com/20024955/69592513-17629500-1031-11ea-923f-0979a0e77eda.png">

**Comment by zjinlei** [comment]
This cluster approach is not supported
