### ISSUE TITLE
Saga: Provide a visual graph designer for Seata Saga StateMachine

### ISSUE THREAD

**Issue by long187** [seata/seata#1959]
## Why you need it?
The Saga model uses a state machine to orchestrate business processes, and a graphical approach to design can get a better user experience.

## How it could be?
After using the designer to complete the design of the state machine, We can switch to the Json view, and save the Json to the project of our own application,  and the state machine can be directly loaded and run it.

**Comment by qiangbro** [comment]
Seata Saga StateMachine Designer 这个工具官方没有使用教程吗？很难入门啊

**Comment by DuLerWeil** [comment]
> Seata Saga StateMachine Designer 这个工具官方没有使用教程吗？很难入门啊

貌似生成的json还不太一样

**Comment by lovepoem** [comment]
**wiki:**                       https://seata.io/zh-cn/docs/user/saga.html
**designer online:**   http://seata.io/saga_designer/index.html
**video:**                     http://seata.io/saga_designer/vedio.html


closed via https://github.com/seata/seata/pull/1960
