### ISSUE TITLE
Maybe global transaction can not rolling back

### ISSUE THREAD

**Issue by zhangxu19830126** [seata/seata#196]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
In the class `TransactionalTemplate`,  in step 4,  we will sent `GlobalCommitRequest` to remote TC server. If application is crash before sent  the `GlobalCommitRequest`. This global transaction will timeout in the future.

### Ⅱ. Describe what happened
Who is responsible for rolling back the global transaction after timeout, how to roll back?

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zhangxu19830126** [comment]
The remote TC server holds a branch session map,  it will sent  rollback request to every branch node for clean up and rolling back. But if any of the branch nodes have a network failure and have not recovered for a long time，it will cause data inconsistency in the global transaction.

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
