### ISSUE TITLE
如何配置多个事务

### ISSUE THREAD

**Issue by haiziguo** [seata/seata#1963]
## Why you need it?
A事务需要a,b,c 服务协调；B事务需要e,f,g服务协调，如何配置同时支持连个事务？如何配置server的高可用性

**Comment by slievrly** [comment]
@haiziguo 
HA: https://github.com/seata/seata-samples/tree/master/ha
Multiple transactions are naturally supported. You can add the corresponding dependencies and configurations on the corresponding microservice nodes.

**Comment by haiziguo** [comment]
server的ha吗，用demo  
在server配置
service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"
  #only support single node
  default.grouplist = "127.0.0.1:8091;127.0.0.1:8092"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
  #unit ms,s,m,h,d represents milliseconds, seconds, minutes, hours, days, default permanent
  max.commit.retry.timeout = "-1"
  max.rollback.retry.timeout = "-1"
}
分别启动了 8091和8092 ，在调试服务时出现了
io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 127.0.0.1:8091:2028755630] ]
偶尔能成功一次。
有时出现
io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 127.0.0.1:8092:2028755630] ]

**Comment by slievrly** [comment]
@haiziguo Do you configure the storage mode as db on the tc-server side?

**Comment by haiziguo** [comment]
I conigured file mode on the server

**Comment by zjinlei** [comment]
refer: https://seata.io/zh-cn/docs/faq/faq.html
