### ISSUE TITLE
MySQL 5.7.22 表字段类型为 tinyint 长度为 1 时, undo_log 日志中只存储 true 和 false, 引起回滚异常

### ISSUE THREAD

**Issue by ymfs-wyh** [seata/seata#1964]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

MySQL 5.7.22 表字段类型为 tinyint 长度为 1 时, undo_log 日志中只存储 true 和 false, 引起回滚异常, 例如业务审核状态为 4, 回滚到 1, 结果 undo_log 中都是 true , 导致最终没有回滚.

### II. Environment:

- JDK version : 1.8
- OS : centos7.4
- Others: mysql 5.7.22

**Comment by ymfs-wyh** [comment]
seata version : 0.9.0

**Comment by ymfs-wyh** [comment]
undo_log 详情如下:

{
	"@class": "io.seata.rm.datasource.undo.BranchUndoLog",
	"xid": "10.10.0.251:8091:2026903810",
	"branchId": 2026903811,
	"sqlUndoLogs": ["java.util.ArrayList", [{
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "merchant_check_info",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant_check_info",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 15]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "service_fee_rate",
					"keyType": "NULL",
					"type": 3,
					"value": ["java.math.BigDecimal", 12.00]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_status",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant_check_info",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 15]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "service_fee_rate",
					"keyType": "NULL",
					"type": 3,
					"value": ["java.math.BigDecimal", 12.00]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_status",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "INSERT",
		"tableName": "merchant_check_log",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords",
			"tableName": "merchant_check_log",
			"rows": ["java.util.ArrayList", []]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant_check_log",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 31]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 15]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_code",
					"keyType": "NULL",
					"type": 12,
					"value": "20191129010001"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_status",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operator",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_org",
					"keyType": "NULL",
					"type": -5,
					"value": null
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_time",
					"keyType": "NULL",
					"type": 93,
					"value": ["java.sql.Timestamp", [1575019739000, 0]]
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "INSERT",
		"tableName": "`merchant_check_log_detail`",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords",
			"tableName": "`merchant_check_log_detail`",
			"rows": ["java.util.ArrayList", []]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "`merchant_check_log_detail`",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 460]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_log_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 31]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "field_name",
					"keyType": "NULL",
					"type": 12,
					"value": "checkStatus"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "original_val",
					"keyType": "NULL",
					"type": 12,
					"value": "1"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "current_val",
					"keyType": "NULL",
					"type": 12,
					"value": "4"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operator",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_org",
					"keyType": "NULL",
					"type": -5,
					"value": null
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_time",
					"keyType": "NULL",
					"type": 93,
					"value": ["java.sql.Timestamp", [1575019739000, 0]]
				}]]
			}, {
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 461]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "check_log_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 31]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "field_name",
					"keyType": "NULL",
					"type": 12,
					"value": "serviceFeeRate"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "original_val",
					"keyType": "NULL",
					"type": 12,
					"value": "12"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "current_val",
					"keyType": "NULL",
					"type": 12,
					"value": "12"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operator",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_org",
					"keyType": "NULL",
					"type": -5,
					"value": null
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "operate_time",
					"keyType": "NULL",
					"type": 93,
					"value": ["java.sql.Timestamp", [1575019739000, 0]]
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "merchant",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 9]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "user_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 20]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_code",
					"keyType": "NULL",
					"type": 12,
					"value": "20191129010001"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "channel_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试代理商2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "agent_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "parent_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 5]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_relation",
					"keyType": "NULL",
					"type": 12,
					"value": "20191114000004,20191114010001,20191129010001"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "service_fee_rate",
					"keyType": "NULL",
					"type": 3,
					"value": ["java.math.BigDecimal", 12.00]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "settle_cycle",
					"keyType": "NULL",
					"type": -6,
					"value": 18
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "admin_phone",
					"keyType": "NULL",
					"type": 12,
					"value": "13545677654"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "industry_type_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 367]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "contract_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 523]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "shop_addr_ext",
					"keyType": "NULL",
					"type": 12,
					"value": "天安门"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "disabled",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 9]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "user_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 20]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_code",
					"keyType": "NULL",
					"type": 12,
					"value": "20191129010001"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "channel_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试代理商2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "agent_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "parent_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 5]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "merchant_relation",
					"keyType": "NULL",
					"type": 12,
					"value": "20191114000004,20191114010001,20191129010001"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "service_fee_rate",
					"keyType": "NULL",
					"type": 3,
					"value": ["java.math.BigDecimal", 12.00]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "settle_cycle",
					"keyType": "NULL",
					"type": -6,
					"value": 18
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "admin_phone",
					"keyType": "NULL",
					"type": 12,
					"value": "13545677654"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "industry_type_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 367]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "contract_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 523]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "shop_addr_ext",
					"keyType": "NULL",
					"type": 12,
					"value": "天安门"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "disabled",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "merchant_subject_info",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant_subject_info",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 9]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "subject_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "subject_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试代理商2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_idcard_no",
					"keyType": "NULL",
					"type": 12,
					"value": "311789199810013576"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_sex",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_nationality",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_idcard_expire_date",
					"keyType": "NULL",
					"type": 12,
					"value": "2019-11-29"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_phone",
					"keyType": "NULL",
					"type": 12,
					"value": "13545677654"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_email",
					"keyType": "NULL",
					"type": 12,
					"value": "123@123.com"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_occupation",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "shop_addr_ext",
					"keyType": "NULL",
					"type": 12,
					"value": "天安门"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_no",
					"keyType": "NULL",
					"type": 12,
					"value": "20191129001001"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_time_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_time_begin",
					"keyType": "NULL",
					"type": 12,
					"value": "2019-11-01"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_time_end",
					"keyType": "NULL",
					"type": 12,
					"value": "2019-11-29"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "having_fixed_busi_addr",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_imgs",
					"keyType": "NULL",
					"type": 12,
					"value": "515"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "idcard_front_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 516]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "idcard_back_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 517]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "store_front_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 520]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "store_env_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 521]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "store_cash_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 519]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "other_imgs",
					"keyType": "NULL",
					"type": 12,
					"value": "518"
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant_subject_info",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 9]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "subject_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "subject_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试代理商2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_idcard_no",
					"keyType": "NULL",
					"type": 12,
					"value": "311789199810013576"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_sex",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_nationality",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_idcard_expire_date",
					"keyType": "NULL",
					"type": 12,
					"value": "2019-11-29"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_phone",
					"keyType": "NULL",
					"type": 12,
					"value": "13545677654"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_email",
					"keyType": "NULL",
					"type": 12,
					"value": "123@123.com"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "legal_occupation",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "shop_addr_ext",
					"keyType": "NULL",
					"type": 12,
					"value": "天安门"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_no",
					"keyType": "NULL",
					"type": 12,
					"value": "20191129001001"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_time_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_time_begin",
					"keyType": "NULL",
					"type": 12,
					"value": "2019-11-01"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_time_end",
					"keyType": "NULL",
					"type": 12,
					"value": "2019-11-29"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "having_fixed_busi_addr",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "license_imgs",
					"keyType": "NULL",
					"type": 12,
					"value": "515"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "idcard_front_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 516]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "idcard_back_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 517]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "store_front_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 520]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "store_env_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 521]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "store_cash_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 519]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "other_imgs",
					"keyType": "NULL",
					"type": 12,
					"value": "518"
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "merchant_channel_info",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant_channel_info",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 9]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "channel_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "province",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "city",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 2]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "district",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 3]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_acct_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_no",
					"keyType": "NULL",
					"type": 12,
					"value": "102100000021"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_branch_name",
					"keyType": "NULL",
					"type": 12,
					"value": "中国工商银行股份有限公司北京通州支行新华分理处"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_province",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_city",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 2]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_acct_no",
					"keyType": "NULL",
					"type": 12,
					"value": "6224561234567"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_acct_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_card_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 522]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_cell_phone",
					"keyType": "NULL",
					"type": 12,
					"value": "13456788765"
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "merchant_channel_info",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": -5,
					"value": ["java.lang.Long", 9]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "channel_type",
					"keyType": "NULL",
					"type": -7,
					"value": false
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "province",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "city",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 2]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "district",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 3]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_id",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_acct_type",
					"keyType": "NULL",
					"type": -7,
					"value": true
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_no",
					"keyType": "NULL",
					"type": 12,
					"value": "102100000021"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_branch_name",
					"keyType": "NULL",
					"type": 12,
					"value": "中国工商银行股份有限公司北京通州支行新华分理处"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_province",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 1]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_city",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 2]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_acct_no",
					"keyType": "NULL",
					"type": 12,
					"value": "6224561234567"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_acct_name",
					"keyType": "NULL",
					"type": 12,
					"value": "测试2"
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_card_img",
					"keyType": "NULL",
					"type": -5,
					"value": ["java.lang.Long", 522]
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "bank_cell_phone",
					"keyType": "NULL",
					"type": 12,
					"value": "13456788765"
				}]]
			}]]
		}
	}]]
}

**Comment by ymfs-wyh** [comment]
问题描述: 我数据库中这个字段是审核状态, 状态机流转过程中, 发现 seata 的 undo_log 这个状态的值在大于 0 时一直是 true, 导致 undo_log 记录时对象没有改变, 所以异常没有回滚
![image](https://user-images.githubusercontent.com/18379396/69860689-be655c00-12d1-11ea-83de-c425736525d5.png)
![image](https://user-images.githubusercontent.com/18379396/69860909-29af2e00-12d2-11ea-849c-ed6953a76738.png)
![image](https://user-images.githubusercontent.com/18379396/69860985-4b101a00-12d2-11ea-8382-39c2fe0abab0.png)

**Comment by jsbxyyx** [comment]
`tinyInt1isBit=false` add to jdbc url

**Comment by wangliang181230** [comment]
@ymfs-wyh @qin501 @jsbxyyx 现在已通过代码修复该BUG，PR：https://github.com/seata/seata/pull/6068

**Comment by wangliang181230** [comment]
@ymfs-wyh 使用 `mysql 5.x` 数据库的朋友，麻烦使用这个PR的代码再测一下吧。
我这边测过了 `mysql 8.x`，驱动包分别为5.x和8.x，都测试通过。
