### ISSUE TITLE
[Bug]Fix of duplicated RM init on demo was missed by MR

### ISSUE THREAD

**Issue by sharajava** [seata/seata#197]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Fix of duplicated RM init on demo was missed by MR

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by leizhiyuan** [comment]
does this issue has been fixed?
