### ISSUE TITLE
服务器安装了seata 0.8.0版本后再安装0.9.0版本，但是启不来

### ISSUE THREAD

**Issue by firehalt** [seata/seata#1981]
问题描述：同一台服务器之前安装的版本为0.8.0，现在安装0.9.0后启动不了
ps:同样的文件换成没有安装过seata的服务器是可以启动的
错误信息如下：
17:33:57,078 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5bcab519 - Roll-over at midnight.
17:33:57,080 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5bcab519 - Setting initial period to Tue Dec 03 17:33:57 CST 2019
17:33:57,082 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@117244645 - Cleaning on start up
17:33:57,082 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
17:33:57,082 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
17:33:57,082 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:33:57,084 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[seata-default] - Active log file name: /tmp/app/seata-server-master/logs//seata-server.log
17:33:57,084 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[seata-default] - File property is set to [/tmp/app/seata-server-master/logs//seata-server.log]
17:33:57,085 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [io.seata.server.store.file.FileTransactionStoreManager] to false
17:33:57,085 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - io.seata.server.store.file.FileTransactionStoreManager level set to INFO
17:33:57,085 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [seata-default] to Logger[io.seata.server.store.file.FileTransactionStoreManager]
17:33:57,085 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
17:33:57,085 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [seata-default] to Logger[ROOT]
17:33:57,085 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
17:33:57,085 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:33:57,086 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@e45f292 - Registering current configuration as safe fallback point

Exception in thread "main" io.seata.common.exception.NotSupportYetException: not support register type: null
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:87)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:71)
	at io.seata.server.ParameterParser.init(ParameterParser.java:74)
	at io.seata.server.ParameterParser.<init>(ParameterParser.java:58)
	at io.seata.server.Server.main(Server.java:59)
Caused by: java.lang.IllegalArgumentException: illegal type:null
	at io.seata.config.ConfigType.getType(ConfigType.java:70)
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:85)
	... 4 more
2019-12-03 17:33:57.114 WARN [configOperate_1_2]io.seata.config.FileConfiguration.run:214 -Could not found property config.type, try to use default value instead.

**Comment by zjinlei** [comment]
not support register type: null
I think it is because the environment variables have been set before.
refer: https://github.com/seata/seata/wiki/Multi-configuration-Isolation
