### ISSUE TITLE
表名用多个下划线分割,会出现get table meta error:Failed to fetch schema 

### ISSUE THREAD

**Issue by lolwsyzc** [seata/seata#1986]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
表名用多个下划线分割,会出现get table meta error:Failed to fetch schema ,2个及2个以上下划线分割的表名会出现这个问题

我使用的是从zk获取的数据源代理对象

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win10
- Others:

**Comment by l81893521** [comment]
Would you mind give some table name?

**Comment by lolwsyzc** [comment]
> 您介意提供一些表格名称吗？

不好意思,后续定位错误原因是表没有主键导致的, 不是因为下划线的问题. 
使用seata的对表进行操作时,主键必须要存在吗,否则无法获取表的元数据

**Comment by l81893521** [comment]
yes
