### ISSUE TITLE
undo_log.sql if the undo_log table not exists, execute occur error

### ISSUE THREAD

**Issue by jsbxyyx** [seata/seata#1988]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
undo_log.sql if the undo_log table not exists, execute occur error.

suggestion update to 
```
drop table if exists `undo_log`;
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by vikenlove** [comment]
the undo_log.sql file has "drop table `undo_log`;"

**Comment by helloworlde** [comment]
The script optimize is in progress.

**Comment by helloworlde** [comment]
The script optimize PR #2000 had been merged.
