### ISSUE TITLE
计划支持针对sqlserver数据库的事务回滚吗？

### ISSUE THREAD

**Issue by liuliu855** [seata/seata#1989]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
@liuliu855 No such plan at this time, waiting for further discussion in the community.

**Comment by mac8088** [comment]
@slievrly 
How are you, as we know, Seata AT mode supports MySQL, Oracle and PostgreSQL in current latest version: 1.3.
So far Seata don't support SQL Server,  but my company and our customers use MSSQL. 

So I wonder that the rough estimate (MD) of the Seata support with SQL Server by one well-skilled java engineer?
Is it technically feasible?

Of cause, if it is feasible and we did, we will contribute the efforts into community and make pull request to seata world .

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/3887
