### ISSUE TITLE
problem about auto proxying of datasource which has final modifier 

### ISSUE THREAD

**Issue by xingfudeshi** [seata/seata#1995]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When enable auto proxying of datasouce which has final modifier,it will cause a Exception means the class can't be proxied by using cglib.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
I will fix it.

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lizwmaster** [comment]
DataSource自动代理时，该DataSource已经被JavaMelody代理了，代理后的为net.bull.javamelody.JdbcWrapper，该类为final类型。<br>
错误堆栈如下：
![DINGTALK_IM_375567200](https://user-images.githubusercontent.com/18043228/70289411-a2047a80-180f-11ea-8b10-884aa97b3863.JPG)

**Comment by xingfudeshi** [comment]
OK.Thanks.

**Comment by xingfudeshi** [comment]
@lizwmaster problem fixed,pls check the PR.

**Comment by lizwmaster** [comment]
Has been verified, the issue has been resolved
