### ISSUE TITLE
I can't use it with JDK 11.0.5.

### ISSUE THREAD

**Issue by lzc555** [seata/seata#1999]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Java HotSpot(TM) 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Unrecognized VM option 'UseFastAccessorMethods'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Ⅱ. Describe what happened

When I use ./seata-server.sh , I can't start server.

JAVA_HOME=/opt/jdk-11.0.5
PATH=/opt/jdk-11.0.5/bin:$PATH
export JAVA_HOME PATH

### Ⅲ. Describe what you expected to happen

Solve it

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 11.0.5
- OS : centOS 7
- Others:

**Comment by lzc555** [comment]
JAVA_HOME=/opt/jdk-11.0.5
PATH=/opt/jdk-11.0.5/bin:$PATH
export JAVA_HOME PATH

**Comment by zjinlei** [comment]
We will adjust the jvm parameters to support jdk11, in version 1.0.
refer: https://github.com/seata/seata/pull/1824

**Comment by lzc555** [comment]
> We will adjust the jvm parameters to support jdk11, in version 1.0.
> refer: #1824

Thank you~

**Comment by lehug** [comment]
how to use? please give some examples
