### ISSUE TITLE
Why  `integration` sub module is not a direct maven sub module ?

### ISSUE THREAD

**Issue by lovepoem** [seata/seata#2003]
## Why you need it?
Why  `integration` sub module is not a direct maven sub module ?
It is a little strange 

![image](https://user-images.githubusercontent.com/827112/70383309-aca54800-19a6-11ea-96ba-7b1194387825.png)

## How it could be?
make it a  maven sub module

**Comment by ujjboy** [comment]
1. The directory structure is not necessarily related to the maven module.
2. `all/pom.xml` does not contain the `integration`
3. If there is a common part between submodules under `integration`, you can add `integration/pom.xml`

**Comment by lovepoem** [comment]
Get it
