### ISSUE TITLE
本地事务@transactional无法作回滚

### ISSUE THREAD

**Issue by qcmoke** [seata/seata#2005]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

@GlobalTransactional可以回滚，但是本地事务@transactional无法作回滚，如何让本地事务也能回滚？Config如下:

```
@Configuration
public class SeataConfiguration {

    @Autowired
    private DataSourceProperties dataSourceProperties;

    @Bean
    public GlobalTransactionScanner globalTransactionScanner() {
        return new GlobalTransactionScanner("springboot-order", "my_test_tx_group");
    }

    @Bean
    @Primary
    public DruidDataSource druidDataSource() {
        DruidDataSource druidDataSource = new DruidDataSource();
        druidDataSource.setUrl(dataSourceProperties.getUrl());
        druidDataSource.setUsername(dataSourceProperties.getUsername());
        druidDataSource.setPassword(dataSourceProperties.getPassword());
        druidDataSource.setDriverClassName(dataSourceProperties.getDriverClassName());
        druidDataSource.setInitialSize(0);
        druidDataSource.setMaxActive(180);
        druidDataSource.setMaxWait(60000);
        druidDataSource.setMinIdle(0);
        druidDataSource.setValidationQuery("Select 1 from DUAL");
        druidDataSource.setTestOnBorrow(false);
        druidDataSource.setTestOnReturn(false);
        druidDataSource.setTestWhileIdle(true);
        druidDataSource.setTimeBetweenEvictionRunsMillis(60000);
        druidDataSource.setMinEvictableIdleTimeMillis(25200000);
        druidDataSource.setRemoveAbandoned(true);
        druidDataSource.setRemoveAbandonedTimeout(1800);
        druidDataSource.setLogAbandoned(true);
        return druidDataSource;
    }

    @Bean
    @ConfigurationProperties(prefix = "spring.datasource")
    public DataSource dataSource() {
        return new DruidDataSource();
    }

    @Bean
    public DataSourceProxy dataSourceProxy(DataSource dataSource) {
        return new DataSourceProxy(dataSource);
    }

    @Value("${mybatis.mapper-locations}")
    private String mybatisMapperLocations;
    @Value("${mybatis.type-aliases-package}")
    private String typeAliasesPackage;

    @Bean
    public SqlSessionFactory sqlSessionFactoryBean(DataSourceProxy dataSourceProxy) throws Exception {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSourceProxy);
        sqlSessionFactoryBean.setTypeAliasesPackage(typeAliasesPackage);
        sqlSessionFactoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources(mybatisMapperLocations));
        sqlSessionFactoryBean.setTransactionFactory(new JdbcTransactionFactory());
        return sqlSessionFactoryBean.getObject();
    }
}

```

###Ⅲ. Environment:

- JDK version : 1.8
- OS : windows10
- Others:

**Comment by qcmoke** [comment]
后面根据网友改成如下配置可以提交本地事务了，但是mybatis的新增操作返回值变成了负数？请问怎么回事？
```java

@Slf4j
@Configuration
public class SeataConfiguration {

    @Autowired
    private DataSourceProperties dataSourceProperties;

    @Bean
    public GlobalTransactionScanner globalTransactionScanner() {
        return new GlobalTransactionScanner("springboot-order", "my_test_tx_group");
    }

    @Bean
    @Primary
    public DruidDataSource druidDataSource() {
        DruidDataSource druidDataSource = new DruidDataSource();
        druidDataSource.setUrl(dataSourceProperties.getUrl());
        druidDataSource.setUsername(dataSourceProperties.getUsername());
        druidDataSource.setPassword(dataSourceProperties.getPassword());
        druidDataSource.setDriverClassName(dataSourceProperties.getDriverClassName());
        druidDataSource.setInitialSize(0);
        druidDataSource.setMaxActive(180);
        druidDataSource.setMaxWait(60000);
        druidDataSource.setMinIdle(0);
        druidDataSource.setValidationQuery("Select 1 from DUAL");
        druidDataSource.setTestOnBorrow(false);
        druidDataSource.setTestOnReturn(false);
        druidDataSource.setTestWhileIdle(true);
        druidDataSource.setTimeBetweenEvictionRunsMillis(60000);
        druidDataSource.setMinEvictableIdleTimeMillis(25200000);
        druidDataSource.setRemoveAbandoned(true);
        druidDataSource.setRemoveAbandonedTimeout(1800);
        druidDataSource.setLogAbandoned(true);
        return druidDataSource;
    }

    @Bean
    public DataSourceProxy dataSourceProxy(DruidDataSource druidDataSource) {
        return new DataSourceProxy(druidDataSource);
    }

    @Value("${mybatis.mapper-locations}")
    private String mybatisMapperLocations;
    @Value("${mybatis.type-aliases-package}")
    private String typeAliasesPackage;

//    @Bean
//    public SqlSessionFactory sqlSessionFactoryBean(DataSourceProxy dataSourceProxy) throws Exception {
//        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
//        sqlSessionFactoryBean.setDataSource(dataSourceProxy);
//        sqlSessionFactoryBean.setTypeAliasesPackage(typeAliasesPackage);
//        sqlSessionFactoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
//                .getResources(mybatisMapperLocations));
////        sqlSessionFactoryBean.setTransactionFactory(new JdbcTransactionFactory());
//        sqlSessionFactoryBean.setTransactionFactory(new SpringManagedTransactionFactory());//支持本地事务管理
//        return sqlSessionFactoryBean.getObject();
//    }

    /**
     * 替换 mybatis 的sqlSessionFactory，用数据源代理替换自动装配的数据源
     * @Param: dataSourceProxy  fescar数据源代理
     * @Return: SqlSessionFactory  mybatic使用的数据源
     */
    @Bean
    public SqlSessionFactory sqlSessionFactory(DataSourceProxy dataSourceProxy) throws Exception {
        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(dataSourceProxy);
        factoryBean.setTypeAliasesPackage(typeAliasesPackage);
        factoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources(mybatisMapperLocations));
//        factoryBean.setTransactionFactory(new JdbcTransactionFactory());  //这个不可用
        factoryBean.setTransactionFactory(new SpringManagedTransactionFactory());
        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.setMapUnderscoreToCamelCase(true);
        factoryBean.setConfiguration(configuration);
        return factoryBean.getObject();
    }

    /**
     * 支持本地事务管理
     * spring事务配置数据源代理
     *
     * @param dataSourceProxy
     * @return
     */
    @Bean
    @Primary
    public DataSourceTransactionManager dataSourceTransactionManager(DataSourceProxy dataSourceProxy) {
        DataSourceTransactionManager transactionManager = new DataSourceTransactionManager();
        transactionManager.setDataSource(dataSourceProxy);
        return transactionManager;
    }
}

````

**Comment by slievrly** [comment]
@jsbxyyx

**Comment by qcmoke** [comment]
> @jsbxyyx

您能解决吗？

**Comment by jsbxyyx** [comment]
@qcmoke can you provide mybatis insert code? if use mysql, mybatis code like this.
```
@Options(useGeneratedKeys = true, keyProperty = "id")
```

**Comment by qcmoke** [comment]
> @qcmoke can you provide mybatis insert code? if use mysql, mybatis code like this.
> 
> ```
> @Options(useGeneratedKeys = true, keyProperty = "id")
> ```
> 
> or mybatis mapper xml specify useGeneratedKeys and keyProperty

··

**Comment by qcmoke** [comment]
> > @qcmoke can you provide mybatis insert code? if use mysql, mybatis code like this.
> > ```
> > @Options(useGeneratedKeys = true, keyProperty = "id")
> > ```
> > 
> > 
> > or mybatis mapper xml specify useGeneratedKeys and keyProperty
> 
> ··
Following is the mybatis insert code.

```xml
    <!--创建订单-->
    <insert id="createOrder" parameterType="Order">
      insert into t_order values(null,#{orderNo},#{userId},#{commodityCode},${count},${amount})
    </insert>
```
If you do not use DataSourceProxy to insert a successful return value, the default is the number of records changed, which is a positive number. But after using DataSourceProxy, the return value inserted successfully becomes negative.
如果不使用DataSourceProxy插入成功的返回值默认是改变的记录数，是一个正数。但是使用DataSourceProxy后插入成功的返回值变成了负数。

**Comment by qcmoke** [comment]
> > > @qcmoke can you provide mybatis insert code? if use mysql, mybatis code like this.
> > > ```
> > > @Options(useGeneratedKeys = true, keyProperty = "id")
> > > ```
> > > 
> > > 
> > > or mybatis mapper xml specify useGeneratedKeys and keyProperty
> > 
> > 
> > ··
> > Following is the mybatis insert code.
> 
> OrderMapper.xml
> 
> ```
>     
>     <insert id="createOrder" parameterType="Order">
>       insert into t_order values(null,#{orderNo},#{userId},#{commodityCode},${count},${amount})
>     </insert>
> ```
> 
> **order-server**
> OrderServiceImpl.java
> 
> ```java
> @Slf4j
> @Service
> public class OrderServiceImpl implements OrderService {
> 
>     @Autowired
>     private OrderMapper orderMapper;
> 
>     @Transactional
>     @Override
>     public boolean createOrder(OrderDTO orderDTO) {
>         log.info("开始扣创建订单。商品编号:{}", orderDTO.getCommodityCode());
>         Order order = new Order();
>         BeanUtils.copyProperties(orderDTO, order);
>         Integer status = orderMapper.createOrder(order);
>         return status > 0;
>     }
> }
> ```
> 
> **business-server**
> BusinessServiceImpl.java
> 
> ```java
> @Slf4j
> @Service
> public class BusinessServiceImpl implements BusinessService {
>     @Reference
>     private OrderDubboService orderDubboService;
>     @Reference
>     private StorageDubboService storageDubboService;
> 
>     @Override
>     @GlobalTransactional
>     public void handleBusiness(OrderDTO orderDTO) {
>         log.info("开始全局事务。XID:{}", RootContext.getXID());
>         StorageDTO storageDTO = new StorageDTO();
>         storageDTO.setCount(orderDTO.getCount());
>         storageDTO.setCommodityCode(orderDTO.getCommodityCode());
>         //1、扣减库存
>         boolean isDec = storageDubboService.decreaseStorage(storageDTO);
>         if (!isDec) {
>             throw new RuntimeException("扣减库存失败");
>         }
>         log.info("库存已扣减:{}", storageDTO);
> 
>         //2、创建订单
>         orderDTO.setOrderNo(UUID.randomUUID().toString());
>         boolean isOrder = orderDubboService.createOrder(orderDTO);
>         if (!isOrder) {
>             throw new RuntimeException("创建订单失败");
>         }
>         log.info("订单已创建：{}", orderDTO);
>     }
> }
> ```
> 
> ![Snipaste](https://camo.githubusercontent.com/ad1ba8fbd9980474a3ff8cf1f8d1148e435e900e/68747470733a2f2f73322e617831782e636f6d2f323031392f31322f31312f5172457754492e706e67)
> 
> 如果在business-server使用全局事务@GlobalTransactional，而在order-server使用本地事务@transactional，那么order-server对于“Integer status = orderMapper.createOrder(order)”，status变成了负数。难道seata不能同时支持全局事务和本地事务吗？
> 
> If you use the global transaction @GlobalTransactional on the business-server and the local transaction @transactional on the order-server, then the order-server status becomes negative for "Integer status = orderMapper.createOrder (order)". Can't seata support both global and local transactions?

**Comment by jsbxyyx** [comment]
provide you seata version or try use lastest release version.

**Comment by qcmoke** [comment]
> provide you seata version or try use lastest release version.

我之前使用的版本是0.6.1，现在改成最新版本问题已经被解决了。谢谢！
The version I used before was 0.6.1, and now the problem has been solved by changing to the latest version.Thank you！
