### ISSUE TITLE
saga与at事务无法使用同一数据源

### ISSUE THREAD

**Issue by chengyan0** [seata/seata#2009]
因at事务使用的数据源为DataSourceProxy代理过的，在saga使用此数据库时无法执行INSERT INTO seata_state_machine_inst (id, machine_id, tenant_id, parent_id, gmt_started
	, business_key, start_params, is_running, status, gmt_updated)
VALUES (?, ?, ?, ?, ?
	, ?, ?, ?, ?, current_timestamp)
原因是current_timestamp无法被解析。

**Comment by zjinlei** [comment]
refer: https://github.com/seata/seata/issues/1578

**Comment by chengyan0** [comment]
> 参考：[＃1578](https://github.com/seata/seata/issues/1578)

mysql 5.7版本，不使用代理的数据源可正常执行

**Comment by slievrly** [comment]
@chengyan0 AT mode cannot be used with Saga mode.

**Comment by chengyan0** [comment]
> @ chengyan0 AT模式不能与Saga模式一起使用。

没有同时使用at和saga事务，只是在同一个项目里都集成了at和saga无法使用同一数据源

**Comment by chengyan0** [comment]
> > @ chengyan0 AT模式不能与Saga模式一起使用。
> 
> 没有同时使用at和saga事务，只是在同一个项目里都集成了at和saga无法使用同一数据源

可能是DataSourceProxy代理后解析insert语句时有问题，都无法使用current_timestamp，
![image](https://user-images.githubusercontent.com/45382143/70700435-b364ef80-1d05-11ea-8937-9bda6bae941a.png)

**Comment by long187** [comment]
建议Saga不要使用AT代理的数据源，因为Saga的数据库操作也被生成undo log，没有必要的。

**Comment by wangliang181230** [comment]
#2551 ，几个月前提过PR，修复了此问题。目前还没合并。
