### ISSUE TITLE
使用Nacos配置管理，只能使用默认namespace？不支持其它namespace吗？dataID项能否用一个配置文件？不然dataId项太多了；

### ISSUE THREAD

**Issue by sseven** [seata/seata#2011]
### **使用Nacos配置管理，只能使用默认namespace？不支持其它namespace吗？dataID项能否用一个配置文件？不然dataId项太多了；**

修改seata-server/conf/nacos-config.sh文件
初始化Seata在Nacos中的配置项:
如下：正常显示，并且在namespace：67dfe694-7206-4426-be06-04ec873c5166
![image](https://user-images.githubusercontent.com/17922001/70596628-555edc00-1c21-11ea-9183-b21b6890be19.png)

![image](https://user-images.githubusercontent.com/17922001/70596590-424c0c00-1c21-11ea-9dd6-c8dd64dc2729.png)

![image](https://user-images.githubusercontent.com/17922001/70596691-76bfc800-1c21-11ea-8169-955914bfd43d.png)

properties对象固定只有serverAddr，namespace不会读取

![image](https://user-images.githubusercontent.com/17922001/70598007-ca7fe080-1c24-11ea-9749-5ee3be2bcc1a.png)

![image](https://user-images.githubusercontent.com/17922001/70597738-154d2880-1c24-11ea-8e02-78a2d1c584be.png)

**Comment by slievrly** [comment]
@sseven to resolve namespace problem need upgrade seata's version to 0.9.0.

**Comment by sseven** [comment]
@slievrly 
Thank you. I'll try

**Comment by sseven** [comment]
@slievrly 关于使用nacos配置管理的dataId项太多情况，可以用一个配置文件如seata.properties解决吗

**Comment by slievrly** [comment]
@sseven are you interested in contributing this feature? I hope you can contribute.

**Comment by zzzzzmh** [comment]
cluster 配置如何理解?

**Comment by 6westboy9** [comment]
这个问题有解决么？nacos-config.sh 依然不能指定命名空间么？

**Comment by zhaojiang1980** [comment]
执行脚本的时候加 -t 可以指定命名空间。但是DataId项太多这个有解决办法么？
