### ISSUE TITLE
Question for Help

### ISSUE THREAD

**Issue by dirkmurphy** [seata/seata#2015]
Hi team

I want ask a question, hope you can help me.

We are using spring cloud 2.x as microservice framework and seata as tx manager now.
There is a scene that in a http call chain, we have a micro service A insert a data into table A with transaction and this data ID is A001.And then service A call service B method, in this service B method, it call service A for query the data which ID is A001.

And I found service B can not get the data we just inserted A001.

I want to know how can service B get the data object from serviceA's query.Is it possible?

Thank you.

**Comment by slievrly** [comment]
@dirkmurphy I think you put @transactional on A's method，right？

**Comment by dirkmurphy** [comment]
@slievrly Thank you for kindly reply. 
Yes I put @Transactional on A's methods and B's methods and C's methods. Is there something wrong?

And Another question need to help that I run the demo project correctly. It work well and rollback well.
But when I run account-service, order-service, storage-service on the same one mysql database.
The tx can rollback but there are no data would be inserted into undo_log table.Is it works correct?

Thank you.

**Comment by dirkmurphy** [comment]
@slievrly Sorry please ignore my another question about undo_log. I found the auto_increament id is increased.

**Comment by slievrly** [comment]
@dirkmurphy This problem has nothing to do with distributed transactions. For example, you have a method A marked with a transactional annotation and calling B in it. B cannot read the value of A. This is because the isolation level of the database is at or above read commit.
