### ISSUE TITLE
请问怎么配置seata的AT模式的事务隔离级别为读已提交呢？

### ISSUE THREAD

**Issue by qcmoke** [seata/seata#2021]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
请问怎么配置seata的AT模式的事务隔离级别为读已提交呢？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
refer https://seata.io/zh-cn/docs/overview/faq.html#4
