### ISSUE TITLE
XA Support

### ISSUE THREAD

**Issue by sharajava** [seata/seata#2022]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

XA is a widely accepted protocol for distributed transaction. Most RDBMS supports XA. And there are also many other resources supports XA.

SEATA should have solution on managing all XA-support resources.

Distributed transaction based on XA can bring us:

- Non-invasive on business logic with strong consistency.
- Higher level of Isolation.
- More flexible ways to support multi-languages. 

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

![image](https://user-images.githubusercontent.com/4413362/70628723-a394cf00-1c63-11ea-881a-8b8fb15f0388.png)

According to SEATA defined distributed transaction framework, XA should be one of ways that RM managed branch transactions works.

As we can see that:

AT Mode works this way

![image](https://user-images.githubusercontent.com/4413362/70628984-29b11580-1c64-11ea-98de-9a027bbe53ad.png)

TCC Mode works this way

![image](https://user-images.githubusercontent.com/4413362/70629031-3e8da900-1c64-11ea-9863-b73cb10d95ff.png)

And XA Mode should be working this way in SEATA framework

![image](https://user-images.githubusercontent.com/4413362/70629098-5cf3a480-1c64-11ea-9b88-c103ffe951f4.png)

## Other related information

SEATA's  XA mode should be designed for cloud-native applications with micro-services.

**Comment by slievrly** [comment]
@sharajava it is a very kind feature. We look forward to your contribution in XA, this feature will be assigned to you.
