### ISSUE TITLE
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'  in Docker

### ISSUE THREAD

**Issue by sundong1982** [seata/seata#2024]
Reference http://seata.io/en-us/docs/ops/deploy-by-docker.html

Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

The PC has enough memory

**Comment by zjinlei** [comment]
refer https://github.com/seata/seata/pull/2001/files
Are you using the latest mirror?

**Comment by helloworlde** [comment]
execute `docker pull seataio/seata-server:latest` to pull the latest

**Comment by sundong1982** [comment]
My image:latest was pulled 12 / 06, now rmi and pull，it's ok. thx:)
