### ISSUE TITLE
implementation DatasourceProxy without AlibabaDruid

### ISSUE THREAD

**Issue by funcfoo** [seata/seata#2025]
## Why you need it?
DatasourceProxy design reason is adapt to more difference JDBC Datasource implementation(Hikaricp, c3p0...)

## How it could be?
io.seata.rm.datasource.sql.SQLVisitorFactory using AlibabaDruid SQLStatement, We can use JSqlParser or custom SqlUtils.

**Comment by zjinlei** [comment]
refer: https://github.com/seata/seata/pull/1703
after 1.0

**Comment by funcfoo** [comment]
Thanks!

**Comment by slievrly** [comment]
@funcfoo Seat just uses druid internally as sqlparser, and the database connection pool used by the business can be arbitrary.

**Comment by funcfoo** [comment]
Yes, I know that.

**Comment by funcfoo** [comment]
@slievrly Yes, I know that. but I can't agree with this design. We just use a little library, Why using a Heavyweight library.
