### ISSUE TITLE
Seata0.90版本，全局事务提交加锁问题以及关闭GloabSession防止分支事务提交

### ISSUE THREAD

**Issue by 850737895** [seata/seata#2026]
io.seata.server.coordinator.DefaultCore#commit的方法中，
![image](https://user-images.githubusercontent.com/24730577/70716263-f8e5e480-1d26-11ea-855e-aee6959f66bf.png)
然后执行lockAndExcute方法的时候，通过GlobalSession中的静态内部类中的Reentrantlock去加载，
那么我们每个线程的globalSession都不是一样的，这里锁不住。
    private static class GlobalSessionLock {

        private Lock globalSessionLock = new ReentrantLock();

        private static final int GLOBAL_SESSION_LOCK_TIME_OUT_MILLS = 2 * 1000;

        public void lock() throws TransactionException {
            try {
                if (globalSessionLock.tryLock(GLOBAL_SESSION_LOCK_TIME_OUT_MILLS, TimeUnit.MILLISECONDS)) {
                    return;
                }
            } catch (InterruptedException e) {
                LOGGER.error("Interrupted error", e);
            }
            throw new GlobalTransactionException(TransactionExceptionCode.FailedLockGlobalTranscation, "Lock global session failed");
        }

        public void unlock() {
            globalSessionLock.unlock();
        }

    }

2)
        boolean shouldCommit = globalSession.lockAndExcute(() -> {
            //the lock should release after branch commit
            globalSession.closeAndClean(); // Highlight: Firstly, close the session, then no more branch can be registered.
            if (globalSession.getStatus() == GlobalStatus.Begin) {
                globalSession.changeStatus(GlobalStatus.Committing);
                return true;
            }
            return false;
        });
  globalSession.closeAndClean();去设置他的active标识为fasle，那么分支事务就不能注册了，但是
我看代码中的分支注册逻辑，同样的globalSession也是从db中查询出来的。压根不是同一对象，无法控制GloabSession的状态改变.
![image](https://user-images.githubusercontent.com/24730577/70716656-b96bc800-1d27-11ea-9156-e9a90df25969.png)

**Comment by zjinlei** [comment]
The db mode implementation is based on the file mode.
Will continue to refactor.
