### ISSUE TITLE
在saga模式下，seata server是起什么作用？状态机配置和日志记录都在客户端，是否可以不需要seata server？

### ISSUE THREAD

**Issue by wuzuhong** [seata/seata#2039]
在saga模式下，seata server是起什么作用？状态机配置和日志记录都在客户端，是否可以不需要seata server？

**Comment by long187** [comment]
首先seata server会生成xid，branchId，然后是失败守护能力：当客户端Saga状态机宕机时，seata server会进行重试守护，触发应用的另一台实例恢复状态机的上下文并继续执行。

如果完全不使用seata server，xid和branchId会用uuid代替，或者你可以自己扩展一个`io.seata.saga.engine.sequence.SeqGenerator`，失败守护能力需要自己实现任务调度程序，且需要考虑高可以用及多实例争抢任务的问题。

**Comment by wuzuhong** [comment]
> 首先seata server会生成xid，branchId，然后是失败守护能力：当客户端Saga状态机宕机时，seata server会进行重试守护，触发应用的另一台实例恢复状态机的上下文并继续执行。
> 
> 如果完全不使用seata server，xid和branchId会用uuid代替，或者你可以自己扩展一个`io.seata.saga.engine.sequence.SeqGenerator`，失败守护能力需要自己实现任务调度程序，且需要考虑高可以用及多实例争抢任务的问题。

多谢
