### ISSUE TITLE
协调server 高可用如何做？

### ISSUE THREAD

**Issue by wuwenhui0917** [seata/seata#2041]
大致浏览了一下代码，有一个疑问：貌似协调器server只能是单点？后续是否会有高可用的方案？

**Comment by liubiao1** [comment]
高可用的未开源



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wuwenhui"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 下午3:34
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[seata/seata] 协调server 高可用如何做？ (#2041)




大致浏览了一下代码，有一个疑问：貌似协调器server只能是单点？后续是否会有高可用的方案？

**Comment by zjinlei** [comment]
refer: http://seata.io/zh-cn/docs/overview/faq.html#2
https://github.com/seata/seata-samples

**Comment by xingfudeshi** [comment]
See the HA samples.
