### ISSUE TITLE
oracle timestamp字段类型seata集成报错

### ISSUE THREAD

**Issue by gjzero123** [seata/seata#2047]
场景是这样的:

底层数据库是oracle，有个创建日期和修改日期 是 timestamp类型

在用seata集成的时候,报如下错误:

\r\n### Error updating database.  Cause: java.sql.SQLException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog[\"sqlUndoLogs\"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog[\"afterImage\"]->io.seata.rm.datasource.sql.struct.TableRecords[\"rows\"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row[\"fields\"]->java.util.ArrayList[5]->io.seata.rm.datasource.sql.struct.Field[\"value\"]->oracle.sql.TIMESTAMP[\"stream\"])

请问该如何解决呢

**Comment by zjinlei** [comment]
oracle.sql.TIMESTAMP requires oracle jar, this jar requires authorization, there is currently no good solution, you can add analysis in JacksonUndoLogParser.java.

/**
     * if necessary
     * extend {@link ArraySerializerBase}
     */
    private static class OracleTimestampSerializer extends JsonSerializer<oracle.sql.TIMESTAMP> {

        @Override
        public void serializeWithType(oracle.sql.TIMESTAMP timestamp, JsonGenerator gen, SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
            WritableTypeId typeId = typeSerializer.writeTypePrefix(gen, typeSerializer.typeId(timestamp, JsonToken.VALUE_EMBEDDED_OBJECT));
            serialize(timestamp, gen, serializers);
            gen.writeTypeSuffix(typeId);
        }

        @Override
        public void serialize(oracle.sql.TIMESTAMP timestamp, JsonGenerator gen, SerializerProvider serializers) {
            try {
                gen.writeBinary(timestamp.getBytes());
            } catch (IOException e) {
                LOGGER.error("serialize oralce.sql.Timestamp error : {}", e.getMessage(), e);
            }

        }
    }

    /**
     * if necessary
     * extend {@link JsonNodeDeserializer}
     */
    private static class OracleTimestampDeserializer extends JsonDeserializer<oracle.sql.TIMESTAMP> {

        @Override
        public oracle.sql.TIMESTAMP deserialize(JsonParser p, DeserializationContext ctxt) {
                try {
                    oracle.sql.TIMESTAMP timestamp = new oracle.sql.TIMESTAMP(p.getBinaryValue());
                    return timestamp;
                } catch (IOException e) {
                    LOGGER.error("deserialize oracle.sql.Timestamp error : {}", e.getMessage(), e);
                }
            return null;
        }
    }

**Comment by slievrly** [comment]
@zjinlei why not pull a request?

**Comment by VincentZhang666** [comment]
请问我需要怎么做呢，我修改之后发现还是不行呢，有具体的步骤吗

**Comment by VincentZhang666** [comment]
> 请问我需要怎么做呢，我修改之后发现还是不行呢，有具体的步骤吗

处理方式：在JacksonUndoLogParser.java增加上面两个Oracle的序列化和反序列化后，然后再定义：
private static final JsonSerializer ORACLETIMESTAMP_SERIALIZER = new OracleTimestampSerializer();
private static final JsonDeserializer ORACLETIMESTAMP_DESERIALIZER = new OracleTimestampDeserializer();
接着在静态块中增加：
MODULE.addSerializer(oracle.sql.TIMESTAMP.class, ORACLETIMESTAMP_SERIALIZER);
MODULE.addDeserializer(oracle.sql.TIMESTAMP.class, ORACLETIMESTAMP_DESERIALIZER);
最后重新打包，确保项目引用到的是修改后的类

**Comment by l81893521** [comment]
Could you paste your error trace here after your modification.

**Comment by jianweiGan** [comment]
替换成kryo

**Comment by stephenchow9527** [comment]
> @zjinlei why not pull a request?

请问现在这个问题解决了吗，我阅读了1.4的相关类好像并没有添加进去。
