### ISSUE TITLE
fescar concordance mybatis CRUD all  fairly

### ISSUE THREAD

**Issue by ak23173969** [seata/seata#205]
fescar --v0.1.1 
mybatis -3.4.6 
springboot  2.0
Datasource is proxy by Fescar 
CRUD all  fairly
bottom 
  org.apache.ibatis.executor.statement.RoutingStatementHandler
  myabtis ---com.alibaba.fescar.rm.datasource..PreparedStatementProxy----.=false
 springjdbc-->com.alibaba.fescar.rm.datasource..StatementProxy   --->true 

Is there no more mybatis inheritance ok at present? Or is there something wrong with my configuration

The relevant code
com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate

**Comment by slievrly** [comment]
any code?

**Comment by ak23173969** [comment]
> any code?
yes

**Comment by tswstarplanet** [comment]
Please provide a demo project and the stacktrace of exception.

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
