### ISSUE TITLE
rollback_info字段存储为空

### ISSUE THREAD

**Issue by Avengervick** [seata/seata#2051]
求助~~遇到一个比较奇怪的问题，seata服务端日志和客户端程序日志都显示回滚成功，但实际上数据并没有回滚，数据库里rollback_info字段存储为空，用的mybatisplus+feign+consul,
![}AUEIU_HQ{2Q`6KC$UIB%KH](https://user-images.githubusercontent.com/18612691/70992608-058e8200-2105-11ea-9d87-9a0d95b7f12a.png)
![9B1HV4`}QJYXI5G9G7 P@11](https://user-images.githubusercontent.com/18612691/70992611-07f0dc00-2105-11ea-8a15-2871dd52ecef.png)
![8)( PTMI9_KXM87~S3FS%CD](https://user-images.githubusercontent.com/18612691/70992616-09220900-2105-11ea-981c-7e3dac27728a.png)
![RWJ3`FEOZT2ZYX%AF%ZT538](https://user-images.githubusercontent.com/18612691/70992620-0aebcc80-2105-11ea-9b5f-734131e75664.png)
![% T690TL@F IITC3EXBVW4D](https://user-images.githubusercontent.com/18612691/70992624-0cb59000-2105-11ea-91bf-a24c9bef30eb.png)
![UTR5Y S_ULBQW@WIUO T24](https://user-images.githubusercontent.com/18612691/70992629-0e7f5380-2105-11ea-9345-99079edeee2a.png)

**Comment by slievrly** [comment]
@Avengervick This is defensive data, your data is consistent, ignore data with status = 1.

**Comment by lightClouds917** [comment]
http://seata.io/zh-cn/docs/overview/faq.html   ，look at the third ;
