### ISSUE TITLE
程序包io.seata.codec.protobuf.generated不存在，导致io.seata.server启动不了

### ISSUE THREAD

**Issue by lilin1996** [seata/seata#2061]
Error:(19, 41) java: 程序包io.seata.codec.protobuf.generated不存在，导致io.seata.server启动不了，这个少包是什么原因呀？谢谢^_^

**Comment by lightClouds917** [comment]
本地执行下mvn clean install -DskipTests=true

**Comment by lilin1996** [comment]
解决啦，谢谢\(^o^)/~

**Comment by chengxuyuan04** [comment]
本地执行下mvn clean install -DskipTests=true  这样idea打开也会显示没有错吗？

**Comment by Garlichead** [comment]
1.1.0执行无法解决
