### ISSUE TITLE
seat怎么解决redis和mongodb事务回滚问题

### ISSUE THREAD

**Issue by lixb3911** [seata/seata#2073]
业务数据出错我想解决redis和mogondb回滚问题怎么解决？

**Comment by slievrly** [comment]
@lixb3911 you can try to use TCC mode and write the reverse interface corresponding to the forward operation.

**Comment by lixb3911** [comment]
Does at mode provide exception rollback listening classes for developers?

**Comment by zjinlei** [comment]
@lixb3911 FailureHandler.java

**Comment by Garlichead** [comment]
i try mongodb.
