### ISSUE TITLE
请问能更新samples中得例子嘛？

### ISSUE THREAD

**Issue by 852675742** [seata/seata#2087]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

请问能更新samples中得例子嘛？不同的版本相差比较大，跑不通
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
done
