### ISSUE TITLE
feign在做降级处理的时候无法触发seata的事务的回滚

### ISSUE THREAD

**Issue by lazyboyl** [seata/seata#2088]
## Why you need it?
 在基于spring cloud开发的时候我们编写的feign的时候都会做降级处理，即在调用的时候出现异常，feign会自动触发我们的降级处理的方式，而这种方式导致无法触发seata的事务的回滚，因为异常给feign处理了。如果我们不做feign的降级处理，那么异常就会一直往上抛，一直抛到我们的页面，这种方式是我们不希望看到的。

## How it could be?
1、在application.yml中将feign.hystrix.enabled设置为true
2、编写相关feign的实现
3、在相关的feign的FeignClient注解中加上fallback=feign的实现的class

## Other related information
![image](https://user-images.githubusercontent.com/49420893/71430698-548d7600-2708-11ea-8174-e523072b38e1.png)

**Comment by wangwei-ying** [comment]
SCA-seata 是直接把fallback作为一个事务分支处理的. 可以在 fallback里触发回滚 
```java
     try {
            TransactionManagerHolder.get().rollback(RootContext.getXID());
        } catch (TransactionException e) {
            log.error(e.getMessage(),e);
        }
```
或者修改 `SeataHystrixConcurrencyStrategy.SeataContextCallable.call()`方法.
```java
public K call() throws Exception {
//增加配置项是否回滚全局事务
			try {
				RootContext.bind(xid);
				return actual.call();
			}
			finally {
				RootContext.unbind();
			}
		}
```

**Comment by lazyboyl** [comment]
已经使用以下的方式来实现feign降级的时候事务的回滚了：http://seata.io/zh-cn/blog/seata-spring-boot-aop-aspectj.html

**Comment by lazyboyl** [comment]
如果出现超时的时候，上面的这种方案还是不能实现事务的回滚，因此需要在服务降级的时候进行事务的回滚即在进行事务降级的时候添加以下的代码，或者使用aop来进行实现集成。
`f (!StringUtils.isBlank(RootContext.getXID()))
            GlobalTransactionContext.reload(RootContext.getXID()).rollback();`

**Comment by daledou** [comment]
```
服务降级或者aop集成下面代码都会提示：
Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.168:8091:2032611006]


if (!StringUtils.isBlank(RootContext.getXID())) GlobalTransactionContext.reload(RootContext.getXID()).rollback();


````


日志中发现在提交之前就执行了unbind

**Comment by 804434940** [comment]
> ```
> 服务降级或者aop集成下面代码都会提示：
> Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.168:8091:2032611006]
> 
> 
> if (!StringUtils.isBlank(RootContext.getXID())) GlobalTransactionContext.reload(RootContext.getXID()).rollback();
> ```
> 
> 日志中发现在提交之前就执行了unbind
您好 请问您这个问题解决了嘛 如何解决呢

**Comment by a364176773** [comment]
> ```
> 服务降级或者aop集成下面代码都会提示：
> Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.168:8091:2032611006]
> 
> 
> if (!StringUtils.isBlank(RootContext.getXID())) GlobalTransactionContext.reload(RootContext.getXID()).rollback();
> ```
> 
> 日志中发现在提交之前就执行了unbind

官网faq

**Comment by a364176773** [comment]
> ## Why you need it?
> 在基于spring cloud开发的时候我们编写的feign的时候都会做降级处理，即在调用的时候出现异常，feign会自动触发我们的降级处理的方式，而这种方式导致无法触发seata的事务的回滚，因为异常给feign处理了。如果我们不做feign的降级处理，那么异常就会一直往上抛，一直抛到我们的页面，这种方式是我们不希望看到的。
> 
> ## How it could be?
> 1、在application.yml中将feign.hystrix.enabled设置为true
> 2、编写相关feign的实现
> 3、在相关的feign的FeignClient注解中加上fallback=feign的实现的class
> 
> ## Other related information
> ![image](https://user-images.githubusercontent.com/49420893/71430698-548d7600-2708-11ea-8174-e523072b38e1.png)

https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo
看下下面的readme

**Comment by 804434940** [comment]
> > ## Why you need it?
> > 在基于spring cloud开发的时候我们编写的feign的时候都会做降级处理，即在调用的时候出现异常，feign会自动触发我们的降级处理的方式，而这种方式导致无法触发seata的事务的回滚，因为异常给feign处理了。如果我们不做feign的降级处理，那么异常就会一直往上抛，一直抛到我们的页面，这种方式是我们不希望看到的。
> > ## How it could be?
> > 1、在application.yml中将feign.hystrix.enabled设置为true
> > 2、编写相关feign的实现
> > 3、在相关的feign的FeignClient注解中加上fallback=feign的实现的class
> > ## Other related information
> > ![image](https://user-images.githubusercontent.com/49420893/71430698-548d7600-2708-11ea-8174-e523072b38e1.png)
> 
> https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo
> 看下下面的readme

谢谢 但是还是没看到如何处理io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.168:8091:2032611006]这个异常
