### ISSUE TITLE
seata集群事务提交或者回滚，server端 只有一个节点可以正常处理，其他节点都有异常

### ISSUE THREAD

**Issue by zhangchao778** [seata/seata#2089]
Ⅰ. Issue Description
seata集群事务提交或者回滚，server端 只有一个节点可以正常处理，其他节点都有异常
### Ⅱ. Describe what happened
server端集群部署，事务提交或者回滚会有服务端异常信息输出，
### Ⅲ. Describe what you expected to happen
解决这个异常信息吧，开始以为是服务端报错了
![3](https://user-images.githubusercontent.com/15061084/71435440-f5d5f580-2723-11ea-801e-d5625f0f945d.png)

**Comment by objcoding** [comment]
I will fix it

**Comment by zhangchao778** [comment]
> I will fix it

谢谢

**Comment by objcoding** [comment]
[bugfix: (issue#2089)when branchRollback failed, it will trigger retry of multi-tc. #2113](https://github.com/seata/seata/pull/2113)
