### ISSUE TITLE
hikari连接池，使用seata-spring-boot-starter1.0.0异常

### ISSUE THREAD

**Issue by liuyi9608** [seata/seata#2090]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
The bean 'dataSourceCCrecord' could not be injected as a 'com.zaxxer.hikari.HikariDataSource' because it is a JDK dynamic proxy that implements:
  javax.sql.DataSource
  java.io.Closeable

### Ⅱ. Describe what happened
hikari连接时，使用seata-spring-boot-starter异常
hikari使用方法如下
![QzpcVXNlcnNcbGl1eWltaW5nXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wzOTg0ODYwMzlfdjJcSW1hZ2VGaWxlc1wxNTc3MjY1NjQxMDk4X0VBMTg2QzdFLUFCODAtNDI4Zi05QzJCLTZBNEU4RTA4MTJDQi5wbmc=](https://user-images.githubusercontent.com/26061239/71442492-1eb8b380-2741-11ea-8b72-c63dabff7c96.png)
![QzpcVXNlcnNcbGl1eWltaW5nXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wzOTg0ODYwMzlfdjJcSW1hZ2VGaWxlc1wxNTc3MjY1NjQxMTAyXzk3NTdCOUI4LUFDNEUtNDI2ZC1BQTk0LTk4QzU1RkEyNUE3Ri5wbmc=](https://user-images.githubusercontent.com/26061239/71442499-237d6780-2741-11ea-94ca-5b653cd2bad8.png)

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lzf971107** [comment]
@liuyi9608 请添加 @EnableTransactionManagement(proxyTargetClass = true) 进行尝试

**Comment by liuyi9608** [comment]
> @liuyi9608 请添加 @EnableTransactionManagement(proxyTargetClass = true) 进行尝试

试过了 还是一样

**Comment by lzf971107** [comment]
@liuyi9608 你试过 spring.aop.proxy-target-class=true吗？或 @EnableAspectJAutoProxy(proxyTargetClass=true)

**Comment by liuyi9608** [comment]
> @liuyi9608 你试过 spring.aop.proxy-target-class=true吗？或 @EnableAspectJAutoProxy(proxyTargetClass=true)

试过了 还是一样的错误

**Comment by lzf971107** [comment]
@liuyi9608 您是否可以提供demo源码

**Comment by liuyi9608** [comment]
> @liuyi9608 您是否可以提供可运行的demo源码

可以 git@github.com:liuyi9608/seata-demo.git

**Comment by zjinlei** [comment]
HikariDataSource -->DataSource

**Comment by lzf971107** [comment]
@liuyi9608 上面的大佬 给了您答案，您可以重新进行测试

**Comment by liuyi9608** [comment]
> 重新

可以了 但是很奇怪 为什么不能直接用hikari

**Comment by lzf971107** [comment]
> > 重新
> 
> 可以了 但是很奇怪 为什么不能直接用hikari

@zhenjing 这位给出的解释为: 我们代理的是接口Datasource，生成的是Datasource的代理类，他要注入HikariDataSource的实现，必须是本身实例或者子类实例

**Comment by liuyi9608** [comment]
> > > 重新
> > 
> > 
> > 可以了 但是很奇怪 为什么不能直接用hikari
> 
> @zhenjing 这位给出的解释为: 我们代理的是接口Datasource，生成的是Datasource的代理类，他要注入HikariDataSource的实现，必须是本身实例或者子类实例

好的 懂了 谢谢大佬

**Comment by lzf971107** [comment]
@liuyi9608 哈哈 我也没帮您什么  刚才@错了 @zjinlei 是这位给您的解释
