### ISSUE TITLE
GlobalLock偶尔会报错

### ISSUE THREAD

**Issue by lxl53535** [seata/seata#2091]
在被@Transactional拦截的方法上,  同时用了@GlobalLock,   然后偶尔会报错
![image](https://user-images.githubusercontent.com/10113198/71442747-507e4a00-2742-11ea-958a-ea7511808c84.png)
![image](https://user-images.githubusercontent.com/10113198/71442768-5bd17580-2742-11ea-8af2-713233493178.png)

**Comment by zjinlei** [comment]
please use 1.0.0
