### ISSUE TITLE
配置中心使用SpringCloudConfig读取不到配置

### ISSUE THREAD

**Issue by lbysimun** [seata/seata#2104]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata1.0 使用springCloudConfig作为配置中心的时候，存在读取不到配置的情况（读不到就用了默认值）。 例如：

1. GlobalTransactionScanner去获取service.disableGlobalTransaction的配置的时候

2. GlobalTransactionScanner去获取datasource.autoproxy的配置的时候

经过调试发现，是在获取配置的时候，SpringContextProvider类还没有初始化好，其中的ApplicationContext和Environment为null。 

解决办法：
考虑让SpringContextProvider先初始化。之后自己打包了源码和修改，为SpringContextProvider实现了PriorityOrdered接口并实现getOrder方法返回highestorder。但是SpringContextProvide好像还是没有最先初始化，导致还是读取不到配置。

其他情况：
当SpringContextProvider类初始化后，就可以正常获取配置项，比如我的registry的配置（type:eureka... ）都是放在配置中心的，这些当程序跑到后面的时候又可以正常获取。估计就是SpringContextProvider初始化先后的问题？

**Comment by slievrly** [comment]
@lbysimun Is seata version 1.0? Spring cloud config in version 1.0 does not currently support dynamic configuration.

**Comment by lbysimun** [comment]
> @lbysimun Is seata version 1.0? Spring cloud config in version 1.0 does not currently support dynamic configuration.

是1.0版本的seata. 这个没有在运行运行过程中去动态获取或者动态改变配置。就是我程序启动的时候去拿一些基本配置(包括seata的必要配置).这个时候SpringContextProvider里面的ApplicationContext为null。导致拿到的配置都是默认值，不是我配置中心里配置的值。比如我上面说的GlobalTransactionScanner去拿那两个配置的时候

**Comment by slievrly** [comment]
@lbysimun GlobalTransactionScanner also implement Ordered interface，you can set a more lower priority.

**Comment by lbysimun** [comment]
> @lbysimun GlobalTransactionScanner also implement Ordered interface，you can set a more lower priority.

找到解决办法了，SeataAutoConfiguration类中，在GlobalTransactionScanner初始化之前，先把SpringContextProvider初始化好 。
```java
@Bean
@DependsOn({"springUtils", "springContextProvider"})  //这里依赖springContextProvider
@ConditionalOnMissingBean(GlobalTransactionScanner.class)
public GlobalTransactionScanner globalTransactionScanner() {
   if (LOGGER.isInfoEnabled()) {
     	LOGGER.info("Automatically configure Seata");
   }
   return new GlobalTransactionScanner(seataProperties.getApplicationId(),seataProperties.getTxServiceGroup());
}
```

**Comment by zjinlei** [comment]
@xingfudeshi Can SpringUtils and SpringContextProvider be merged?

**Comment by xingfudeshi** [comment]
> @xingfudeshi Can SpringUtils and SpringContextProvider be merged?

Check the PR.

**Comment by xingfudeshi** [comment]
> @xingfudeshi Can SpringUtils and SpringContextProvider be merged?

Check the PR.

**Comment by xingfudeshi** [comment]
@zjinlei Check the PR.
