### ISSUE TITLE
project.version和project.groupId问题

### ISSUE THREAD

**Issue by mintonzhang** [seata/seata#2110]
![image](https://user-images.githubusercontent.com/45935465/71571597-f6043580-2b15-11ea-9968-659d66556785.png)
![image](https://user-images.githubusercontent.com/45935465/71571614-0c11f600-2b16-11ea-891d-e718bc38ce58.png)
![image](https://user-images.githubusercontent.com/45935465/71571631-25b33d80-2b16-11ea-8c33-5109a7928c19.png)

你好，我下载了1.0.0版本的seata-spring-boot-starter 通过它无法下载最新版的seata-all.
我在依赖中看见了project.groupId和project.version两个变量。 但是我在parent中没有找到这个变量的定义。

**Comment by zjinlei** [comment]
refer: https://blog.csdn.net/chenchunlin526/article/details/85617213

**Comment by mintonzhang** [comment]
![image](https://user-images.githubusercontent.com/45935465/71572208-fd790e00-2b18-11ea-97d1-7bb37129485c.png)

**Comment by mintonzhang** [comment]
请看一下，maven自动下载0.9.0的seata-all

**Comment by mintonzhang** [comment]
在此之前，我连本地maven的seata都删除了

**Comment by helloworlde** [comment]
@mintonzhang 
I met this issue because I used `com.alibaba.cloud:spring-cloud-alibaba-dependencies` as `dependencyManagement` like:

```groovy
ext {
    springCloudAlibabaVersion = '2.1.0.RELEASE'
}

dependencyManagement {
    imports {
        mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:${springCloudAlibabaVersion}"
    }
}

dependencies {
    implementation('io.seata:seata-spring-boot-starter:1.0.0')
}
```

Pleasa have a try to remove SCA related dependence.

**Comment by mintonzhang** [comment]
@helloworlde  thanks
