### ISSUE TITLE
Seata does not support mysql 8.x ?

### ISSUE THREAD

**Issue by huguirong** [seata/seata#2116]
## 客户端报错如下：
```
io.seata.core.exception.TmTransactionException: TransactionException[begin global request failed. xid=null, msg=Could not retrieve transation read-only status server]
```

## 日志报错截图如下：
![63C8EF1A-1897-4342-89FF-644D693FF3BC.png](https://i.loli.net/2019/12/31/8sncJbwE6rCPIeL.png)

**Comment by slievrly** [comment]
@huguirong upgrade mysql-connector-java to 8.x.

**Comment by huguirong** [comment]
> @huguirong upgrade mysql-connector-java to 8.x.

这个错误是由seata-server端产生的，是因为配置了`store.db.db-type=mysql`
所以只能修改`seata/bom/pom.xml`中`<mysql.client.version>`标签里的版本号，然后自己构建seata-server了

**Comment by huguirong** [comment]
> @huguirong upgrade mysql-connector-java to 8.x.

@slievrly 这个错误是由seata-server端产生的，是因为配置了store.db.db-type=mysql
所以只能修改seata/bom/pom.xml中<mysql.client.version>标签里的版本号，然后自己构建seata-server了

**Comment by huguirong** [comment]
> @huguirong upgrade mysql-connector-java to 8.x.

@slievrly 这个错误是由seata-server端产生的，是因为配置了`store.db.db-type=mysql`
所以只能修改`seata/bom/pom.xml`中`<mysql.client.version>`标签里的版本号，然后自己构建seata-server了

**Comment by zjinlei** [comment]
http://seata.io/zh-cn/docs/overview/faq.html#12

**Comment by huguirong** [comment]
> http://seata.io/zh-cn/docs/overview/faq.html#12

**Thank you.**

**Comment by huguirong** [comment]
**seata server是用docker部署的，因此修改了下dockerfile。也在用mysql8.x的朋友可以参考：**
```
FROM seataio/seata-server:1.0.0

WORKDIR /$BASE_DIR

RUN set -x \
    && rm /seata-server/libs/mysql-connector-java-* \
    && wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.17/mysql-connector-java-8.0.17.jar -P /seata-server/libs
```
