### ISSUE TITLE
SEATA SERVER端集群配置

### ISSUE THREAD

**Issue by 852675742** [seata/seata#2121]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

请问下SEATA SERVER端集群怎么配置，防止单点故障
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zjinlei** [comment]
http://seata.io/zh-cn/docs/overview/faq.html#2
