### ISSUE TITLE
Question about tx-service-group【关于 tx-service-group参数的疑问】

### ISSUE THREAD

**Issue by 81519434** [seata/seata#2122]
**如何使用tx-service-group参数？**
假设我的事务分组1（tx-service-group）名称为 taobao。
seata-server集群在eureka的名称为 seata-server1。

假设我的事务分组1（tx-service-group）名称为 jd。
seata-server集群在eureka的名称为 seata-server2。

**那么我的架构应该怎么样才合适？**

seata-server1和seata-server2 可以同时属于一个tx-service-group吗？ 还是必须分开属于不同的tx-service-group。

文档中提到“事务分组”概念是为了发生故障时可以快速failover。
这种快速failover是大概是什么流程？以及什么情况下可以触发快速failover？

**Comment by slievrly** [comment]
@81519434 Seata-server1 and seata-server2 are two clusters, taobao and jd are two transaction groups that can be mapped to the same cluster, such as seata-server1. When a failure occurs, you need to change the cluster name of the transaction grouping map through the configuration center to complete a quick cluster switch.

**Comment by 81519434** [comment]
@slievrly 
Here is my point of view. Please let me know if I'm wrong.
First, My two big business Jd and taobao are using "seata-server1" as seata server which I deploy many copies of it.  And "seata-server2" is not used.
![image](https://user-images.githubusercontent.com/9690089/73829465-f17e1b80-483d-11ea-9129-08f804e7ad12.png)
Second, when seata-server1 clusters is down, I will change the cluster name of the transaction grouping map. That is say ,change all micro service to connect to seata-server2.
![image](https://user-images.githubusercontent.com/9690089/73830019-e37cca80-483e-11ea-9157-8a641fd13a21.png)
