### ISSUE TITLE
全局事务无法回滚

### ISSUE THREAD

**Issue by Exclusive-gfj** [seata/seata#2141]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
### Ⅱ. Describe what happened

  A服务调用B服务，A服务发生异常B服务的事务无法回滚。测试流程当B服务的接口走完后A服务抛出异常这个时候B服务的事务已经提交了。

```
Just paste your stack trace here!
```

**Comment by lightClouds917** [comment]
贴下堆栈。不然听起来像是全局事务未起效。

**Comment by lightClouds917** [comment]
可能是异常被拦截掉了。

**Comment by Exclusive-gfj** [comment]
> 可能是异常被拦截掉了。

异常是直接全部抛出到Controller中处理的。也没有定义全局异常

**Comment by lightClouds917** [comment]
B事务看起来没有纳入全局事务管理。你看看B服务的日志，是否有注册分支事务相关的日志。

**Comment by lightClouds917** [comment]
![image](https://user-images.githubusercontent.com/33415199/71958822-293c7800-322c-11ea-82b4-79c8ab3535c8.png)
或者监控下tc这边的日志，也能看到分支事务注册信息

**Comment by hankooxiaozei** [comment]
我也有一样的问题 是分支事务没有注册引起的 分支事务不注册应该如何排查

**Comment by EniJu** [comment]
> 我也有一样的问题 是分支事务没有注册引起的 分支事务不注册应该如何排查

检查XID 是否在服务之间进行传递了
