### ISSUE TITLE
注册中心使用consul, 客户端会拉取不健康的服务进行连接

### ISSUE THREAD

**Issue by 15058126273** [seata/seata#2147]
节点描述:
1. 一个consul注册中心
2. 一个seata-server, 注册模式为consul (版本 0.8.1)
3. 一个客户端服务, 服务发现为consul (版本 0.8.1)

过程:
1. 依次启动 consul / seata-server / client  (正常连接)
2. 关闭seata-server (此时consul中显示此节点服务为不健康, 但没有注销实例)
3. client与seata-server断开连接后, 每5秒进行一次服务拉取, **依然会拉取到不健康的seata-server, 并不断重连它, 直到 80秒后此seata-server从consul被注销**

导致的问题:
1. seata-server集群部署的情况下, 关闭/重启某一台seata-server服务, 客户端会有很长一段时间去重连这个不可用的服务, 严重影响业务服务

相关截图: 
1. 关闭seata-server后的consul显示
![image](https://user-images.githubusercontent.com/20962939/71866887-d6d35c80-3142-11ea-9dfd-dad9b6897792.png)

2. 关闭seata-server后, client重连日志
![image](https://user-images.githubusercontent.com/20962939/71866975-2c0f6e00-3143-11ea-861b-2e7a73d37303.png)

3. 一段时间后, client的重连日志
![image](https://user-images.githubusercontent.com/20962939/71867326-af7d8f00-3144-11ea-97ba-0160e102ceb8.png)

**Comment by 15058126273** [comment]
这个问题应该是由于配置没有正确导致的, 客户端的 service 节点需要改, 与 consul 的 cluster 对应 (默认是 "default")
![image](https://user-images.githubusercontent.com/20962939/71872975-e65da000-3158-11ea-8574-5443b8b6dcbc.png)

**Comment by xingfudeshi** [comment]
> 这个问题应该是由于配置没有正确导致的, 客户端的 service 节点需要改, 与 consul 的 cluster 对应 (默认是 "default")
> ![image](https://user-images.githubusercontent.com/20962939/71872975-e65da000-3158-11ea-8574-5443b8b6dcbc.png)

Has your problem been solved?

**Comment by 15058126273** [comment]
yes------------------ 原始邮件 ------------------
发件人: "xingfudeshi"<notifications@github.com>
发送时间: 2020年1月16日(星期四) 晚上9:48
收件人: "seata/seata"<seata@noreply.github.com>;
抄送: "yjy"<1335823608@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [seata/seata] 注册中心使用consul, 客户端会拉取不健康的服务进行连接 (#2147)


 
这个问题应该是由于配置没有正确导致的, 客户端的 service 节点需要改, 与 consul 的 cluster 对应 (默认是 "default")
 
  
Has your problem been solved?
 
&mdash;
