### ISSUE TITLE
使用    @GlobalLock+    @Transactional+for update会出现脏读现象，使用@GlobalTransactional不会

### ISSUE THREAD

**Issue by hardpbl** [seata/seata#2148]
在seata的事务执行过程中，其他方法能读到seata分支事务本地事务提交的数据，按照FAQ上面的介绍是有考虑脏读的情况的，
 /**
     * 查询当前库存信息
     * @return
     */
    @Scheduled(cron = "*/1 * * * * ?")
    @GlobalLock
    @Override
    @Transactional
    public void queryStorage() {
        //for update查询
        Storage storage = storageDao.queryForUpdate();
        System.out.println(storage.toString());
    }
上述代码会出现先输出storage.toString()的结果再抛出锁冲突的异常
使用@GlobalTransactional不会去打印结果，直接抛出全局锁等待超时，当然，这也是正确的情况

**Comment by zjinlei** [comment]
SelectForUpdateExecutor transformation point
1.if originalAutoCommit is true, use checkLock
2.if is false(such as add @Transactional), dirty reads still exist because the lock is not verified until commit
