### ISSUE TITLE
配置DataSourceProxy，通过connection的statement，statement.executeBatch()批量执行sql时报空指针

### ISSUE THREAD

**Issue by gongluzhen** [seata/seata#2154]
seata-all-1.0.0.jar
io.seata.rm.datasource.exec.ExecuteTemplate
line73 statementProxy.getTargetSQL()获取不到目标sql 会导致
com.alibaba.druid.sql.parser.Lexer
java.lang.NullPointerException: null
	at com.alibaba.druid.sql.parser.Lexer.charAt(Lexer.java:122)
![image](https://user-images.githubusercontent.com/42362486/71956188-76691b80-3225-11ea-8b40-fa8ae7d46246.png)

**Comment by javashop** [comment]
碰到同样的问题

**Comment by slievrly** [comment]
@gongluzhen can you paste batch sqls?

**Comment by javashop** [comment]
update es_goods set enable_quantity=1, quantity=1 where goods_id=1
update es_goods set enable_quantity=1, quantity=1 where goods_id=2
update es_goods set enable_quantity=1, quantity=1 where goods_id=3

**Comment by zjinlei** [comment]
https://github.com/seata/seata/pull/2575
released in 1.2.0
