### ISSUE TITLE
zk-config.sh 脚本报错

### ISSUE THREAD

**Issue by clfbai** [seata/seata#2155]
![image](https://user-images.githubusercontent.com/46588474/71956561-71f13280-3226-11ea-95d2-3cc0fd8afa67.png)
zk-config.sh 脚本 错误信息  运行环境 mac os X 10
/opt/seata/conf » sh zk-config.sh                                                                           
: command not found15:
: command not found16:
: command not found19:
: command not found20:
'k-config.sh: line 21: syntax error near unexpected token `do
'k-config.sh: line 21: `for line in $(cat zk-params.txt); do

**Comment by helloworlde** [comment]
The ZooKeeper script depend on ZooKeeper library, please make sure your `zk-params.txt` has right config with ZooKeeper

**Comment by objcoding** [comment]
这个错误是没有找到zk-params.txt这个文件，
seata 1.1.0之后版本将会用脚本参数化输入，详情请看：
https://github.com/seata/seata/pull/2171
