### ISSUE TITLE
分支事务是通过mybatis 调用 mysql的存储过程时会报异常

### ISSUE THREAD

**Issue by gongluzhen** [seata/seata#2157]
io.seata.common.exception.ShouldNeverHappenException: null
	at io.seata.core.context.RootContext.assertNotInGlobalTransaction(RootContext.java:185)
	at io.seata.rm.datasource.AbstractConnectionProxy.prepareCall(AbstractConnectionProxy.java:127)

**Comment by gongluzhen** [comment]
io.seata.rm.datasource.AbstractConnectionProxy line 126
public CallableStatement prepareCall(String sql) throws SQLException {
        RootContext.assertNotInGlobalTransaction();
        return targetConnection.prepareCall(sql);
    }
你们是不打算支持，存储过程了吗？

**Comment by cmonkey** [comment]
个人看法是在业务层上很难对存储过程逻辑产生的数据变更进行监控，undo 日志没法实现，那么事务比较也就无从谈起

**Comment by gongluzhen** [comment]
> 个人看法是在业务层上很难对存储过程逻辑产生的数据变更进行监控，undo 日志没法实现，那么事务比较也就无从谈起

懒汉思维

**Comment by cmonkey** [comment]
> > 个人看法是在业务层上很难对存储过程逻辑产生的数据变更进行监控，undo 日志没法实现，那么事务比较也就无从谈起
> 
> 懒汉思维

我想我已经强调了是个人看法，至于官方是如何考虑的，你可能需要问问他们

**Comment by wangwei-ying** [comment]
可以用tcc模式去做

**Comment by gongluzhen** [comment]
> 可以用tcc模式去做

3q
