### ISSUE TITLE
io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.config.ExtConfigurationProvider[null] and classloader : sun.misc.Launcher$AppClassLoader@73d16e93

### ISSUE THREAD

**Issue by gongluzhen** [seata/seata#2158]
增强服务是个what？

**Comment by gongluzhen** [comment]
/seata-all-1.0.0-sources.jar/META-INF/services 下也没有io.seata.config.ExtConfigurationProvider

**Comment by zjinlei** [comment]
seata-spring-boot-starter
http://seata.io/zh-cn/docs/ops/deploy-guide-beginner.html
