### ISSUE TITLE
seata-spring-boot-starter 注册时，选用redis注册报错

### ISSUE THREAD

**Issue by guojingyinan219** [seata/seata#2160]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

采用redis作为注册器的时候，redis.db 类型转换异常

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
redis 作为注册中心时发生的 
```
Just paste your stack trace here!
```
![image](https://user-images.githubusercontent.com/13974995/72043027-0cb34500-32eb-11ea-8b40-7a613bcc30ec.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
修改 RegistryRedisProperties 中 db 中类型

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win10
- Others:

**Comment by zjinlei** [comment]
db in RegistryRedisProperties is String
@xingfudeshi add miss param password
