### ISSUE TITLE
lock_table table_name varchar(32) 就这样任性的把表名长度设置成32了？去搞一搞mysql的表名长度限制好不好

### ISSUE THREAD

**Issue by gongluzhen** [seata/seata#2162]
CREATE TABLE `lock_table` (
  `row_key` varchar(128) NOT NULL,
  `xid` varchar(96) DEFAULT NULL,
  `transaction_id` bigint(20) DEFAULT NULL,
  `branch_id` bigint(20) NOT NULL,
  `resource_id` varchar(256) DEFAULT NULL,
  `table_name` varchar(64) DEFAULT '',
  `pk` varchar(36) DEFAULT NULL,
  `gmt_create` datetime DEFAULT NULL,
  `gmt_modified` datetime DEFAULT NULL,
  PRIMARY KEY (`row_key`),
  KEY `idx_branch_id` (`branch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by gongluzhen** [comment]
表名长度超过32，会报异常！

**Comment by gongluzhen** [comment]
用了两天发现了好几个问题，好感快变没了！：
1、不支持 connection的批量更新；
2、不支持存储过程；
3、字段长度问题

**Comment by zjinlei** [comment]
1. https://github.com/seata/seata/pull/2112 reviewing
3.please adjust the length according to your needs

**Comment by gongluzhen** [comment]
> 1. #2112 reviewing
>    3.please adjust the length according to your needs

3q
