### ISSUE TITLE
undo log 回滚失败，回滚数据为脏数据（Has dirty records when undo）

### ISSUE THREAD

**Issue by feijiing** [seata/seata#2186]
![图片](https://user-images.githubusercontent.com/3621758/72419933-bcd7f080-37b8-11ea-9fb5-d8230a4a6183.png)
如图所示，报异常之后，分支事物回滚，提示有脏数据：
 branchRollback failed reason [Branch session rollback failed and try again later xid = 192.168.80.79:18091:2031581034 branchId = 2031581658 Has dirty records when undo.]

并且通过测试发现不是100% 重现，有回滚成功的情况

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/72420462-bac26180-37b9-11ea-8260-32ff23119727.png)

**Comment by feijiing** [comment]
将seata server 版本升级至 1.1.0-SNAPSHOT版本，另外BRANCH_TABLE 表结构同步到最新表接口，可查看seata 源码中的sql脚本，经过测试验证能够回滚成功。
问题总结1： seata server 启动没有加 -n 参数，生产环境多机，多台TC必须加的，每台区分不同的node，用于生成不同范围的事务id，不然在开启全局事务时id会冲突报错
还有其他原因请作者补充 @slievrly @zjinlei

**Comment by GitHub-JXJ** [comment]
> 将seata server 版本升级至 1.1.0-SNAPSHOT版本，另外BRANCH_TABLE 表结构同步到最新表接口，可查看seata 源码中的sql脚本，经过测试验证能够回滚成功。 问题总结1： seata server 启动没有加 -n 参数，生产环境多机，多台TC必须加的，每台区分不同的node，用于生成不同范围的事务id，不然在开启全局事务时id会冲突报错 还有其他原因请作者补充 @slievrly @zjinlei

-n这个不指定的话应该会默认指定IP作为节点标识的吧？

**Comment by schild** [comment]
阿里出品，名不虚传
