### ISSUE TITLE
1.0版本缺少io.seata.codec.protobuf.generated包路径

### ISSUE THREAD

**Issue by mingyifei** [seata/seata#2199]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/38995810/72620660-b5f8db80-397a-11ea-856c-44b8320a03bb.png)
![image](https://user-images.githubusercontent.com/38995810/72620685-bf824380-397a-11ea-915b-0e23c0626261.png)

generated 包路径没找到呢、、、、、、

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@mingyifei http://seata.io/zh-cn/docs/overview/faq.html#11
