### ISSUE TITLE
BranchSession not release lock after GlobalSession is timeout

### ISSUE THREAD

**Issue by masterfengj** [seata/seata#220]
GlobalSession超时后(即isTimeout()=true)后, 没有对每个相关的BranchSession做unlock处理,对应客户端来说一个直观的现象就是,后续业务操作可能抛出LockConflictException, 类似于ISSUE #199 中提到的.
 
在GlobalSession超时后,没有发现有后续地方能执行执行BranchSession.unlock操作,看起来在DefaultCoordinator.timeoutCheck中,调用globalSession.close()不够, 应该调用globalSession.closeAndClean();

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
