### ISSUE TITLE
找不到可用的“默认”服务，请确保注册表配置正确

### ISSUE THREAD

**Issue by 623990721** [seata/seata#2205]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
项目正常启动，但是会时不时报error错误日志！

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
ERROR 19532 --- [imeoutChecker_2] i.s.c.r.netty.NettyClientChannelManager  :
no available service 'default' found, please make sure registry config correct
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. registry.conf 文件配置
registry {
  type = "eureka"
  eureka {
    serviceUrl = "http://10.7.142.41:8761/eureka,http://10.7.142.42:8761/eureka,http://10.7.142.45:8761/eureka"
    application = "default"
    weight = "1"
  }
2. file.conf 配置的是db模式。

**Comment by slievrly** [comment]
@623990721 you need to make sure that the server is registered with eureka first.
