### ISSUE TITLE
suport spring general configuration

### ISSUE THREAD

**Issue by sherlock-hao** [seata/seata#221]
I tried to intergrate fescar into a springboot project ,but could not find out how to configure fescar at general spring configuration like using application.properties or application.yml file .

So do you have any plan to suport it, I am currently using application.conf to configure fescar client ,but it's not convinient to swith to program environment.

**Comment by weics** [comment]
@sherlock-hao in the wiki show the plans what you needs https://github.com/alibaba/fescar/wiki/%E6%A6%82%E8%A7%88#v05x

**Comment by slievrly** [comment]
I will add some docs
