### ISSUE TITLE
多环境配置某个环境下seata服务开启过程中卡在log4j:WARN

### ISSUE THREAD

**Issue by BeanHhb** [seata/seata#2213]
多环境配置，分别使用了 -dev 和 -test

log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

注册到consul的，两种配置中consul和数据库 ip不同。
使用-dev的配置文件可以运行，而换成-test则运行到上面的WARN，后面就不再运行了。

**Comment by slievrly** [comment]
@BeanHhb It seems to be an environmental issue that should be examined for differences in the environment.
