### ISSUE TITLE
sharding-jdbc使用seata事务，分库操作广播表，发生异常时只有一个库的数据正常回滚

### ISSUE THREAD

**Issue by historicvally** [seata/seata#2218]
### Ⅰ. Issue Description

  这问题应该是seata这边的，还是sharding-transaction-base-seata-at那边的？

### Ⅱ. Describe what happened

 mysql分库，使用sharding-jdbc结合seata的at模式，操作广播表 A。
 进行连续的数据插入操作并主动抛出异常，使用@GlobalTransactional注解，永远只会有同一个库中的数据发生回滚操作，其它库中的数据均保持插入成功状态。
 当注解改成本地事务，即使用@Transactional注解，发现事务运行正常，所有数据库中A表数据正常回滚。
 
 使用版本
 seata-spring-boot-starter 1.0.0,
 sharding-transaction-base-seata-at 4.0.0-RC2,

### Ⅵ. Environment:

- JDK version : jdk1.8

**Comment by demoCow** [comment]
恩 我是分库分表出现这种情况 永远只有第一个库进行回滚.......DataSourceProxy是我手工注入到Mybatis 的SqlSessionFactory 有解决的办法么

**Comment by weilongshi** [comment]
同样问题，有解决方法吗

**Comment by 1992219hty** [comment]
问题解决了吗？
