### ISSUE TITLE
RM出现注册不上 超时情况

### ISSUE THREAD

**Issue by moshiqing** [seata/seata#2220]
io.seata.common.exception.FrameworkException: can not register RM,err:register error,role:RMROLE,err:cost 30001 ms

修改了启动bat
%JAVACMD% %JAVA_OPTS% -server -Xmx1024m -Xms1024m -Xmn1024m -Xss512k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="%BASEDIR%"/logs/java_heapdump.hprof -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -Xloggc:"%BASEDIR%"/logs/seata_gc.log -verbose:gc -Dio.netty.leakDetectionLevel=advanced -classpath %CLASSPATH% -Dapp.name="seata-server" -Dapp.repo="%REPO%" -Dapp.home="%BASEDIR%" -Dbasedir="%BASEDIR%" io.seata.server.Server %CMD_LINE_ARGS%
if %ERRORLEVEL% NEQ 0 goto error

导致出现问题
机器为8G内存，但是2048M启动不了 改小了内存 可以启动
之后启动服务 向TC进行注册，会出现
io.seata.common.exception.FrameworkException: can not register RM,err:register error,role:RMROLE,err:cost 30001 ms

由于身边没有机器想知道是不是内存太小的原因

**Comment by slievrly** [comment]
@moshiqing telnet ipAddress port
