### ISSUE TITLE
mybatis批量插入操作目前版本支持吗？

### ISSUE THREAD

**Issue by frakes-zou** [seata/seata#2221]
我的mapper中使用batch操作。
<foreach collection="list" item="cell" index="index" open="" close="" separator=";">
          update table...
          <set>
              <if test="cell.cellValue!=null">
                  cell_value = #{cell.cellValue},
              </if>
              ...
          </set>
          where id = #{cell.id}
      </foreach>
会报语法错误，之前使用过mycat。1.6版本被告知也不支持批处理操作；
请帮忙解答，谢谢~

**Comment by slievrly** [comment]
@laokime support batch-insert like this: insert into tb1(name1,name2) values("1","1") , ("2","2")

**Comment by laokime** [comment]
> @laokime support batch-insert like this: insert into tb1(name1,name2) values("1","1") , ("2","2")

Okay, man, I've tried this;
