### ISSUE TITLE
seata是否支持HSF微服务

### ISSUE THREAD

**Issue by anic** [seata/seata#2228]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

目前Seata 1.0.0支持dubbo和sofa协议，实现TCC分布式事务。项目组使用EDAS+HSF框架，希望使用Seata进行分布式事务。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

类似Dubbo，实现对HSF协议的支持

## Other related information

目前看到有DubboRemotingParser、LocalTCCRemotingParser和SofaRpcRemotingParser，但是没有HSF的parser，而看到io.seata.rm.tcc.remoting.Protocols预留了对HSF的常量，希望尽快进行支持。

**Comment by zhangthen** [comment]
HSF  没有开源，所以在开源版里面我们没有支持；
有需要的话，我们可以再细聊，你 钉钉号多少

**Comment by anic** [comment]
> HSF 没有开源，所以在开源版里面我们没有支持；
> 有需要的话，我们可以再细聊，你 钉钉号多少

钉钉号：k4g_fkgk7pdn2

**Comment by q294881866** [comment]
开发已排期
