### ISSUE TITLE
com.sun.proxy.$Proxy127 cannot be cast to com.zaxxer.hikari.HikariDataSource

### ISSUE THREAD

**Issue by G01Hu** [seata/seata#2243]
环境: spring-cloud-alibaba-seata:2.2.0.RELEASE
数据库驱动oracle
使用数据源com.zaxxer.hikari.HikariDataSource时报错java.lang.ClassCastException
而使用com.alibaba.druid.pool.DruidDataSource 则不会
我发现执行GlobalTransactionScanner.postProcessAfterInitialization方法时DruidDataSource可以获取我设置的数据库连接url 账号等信息而HikariDataSource则不会
这是为什么?

**Comment by ruoshuixuelabi** [comment]
同样遇到这个问题，咋解决的？
