### ISSUE TITLE
when disableGlobalTransaction is true, no available service 'null' found

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2250]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/20024955/74579502-f9745300-4fd5-11ea-921c-f9e7635f70ff.png)
![image](https://user-images.githubusercontent.com/20024955/74579521-1c066c00-4fd6-11ea-8d29-512208bf47ae.png)
![image](https://user-images.githubusercontent.com/20024955/74579532-27f22e00-4fd6-11ea-86f5-cfa7a51913b7.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lzylio** [comment]
https://www.cnblogs.com/javashare/p/12529434.html

**Comment by lzylio** [comment]
detail https://www.cnblogs.com/javashare/p/12529434.html

**Comment by lzylio** [comment]
beacuse vgroup_mapping or vgroupMapping
detail https://www.cnblogs.com/javashare/p/12529434.html
