### ISSUE TITLE
nacos-config.sh error

### ISSUE THREAD

**Issue by a364176773** [seata/seata#2263]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
$ sh ./nacos-config.sh
set nacosAddr=localhost:SEATA_GROUP
set group=
\033[31m Please check the cluster status. \033[0m

### Ⅵ. Environment:

- JDK version :
- OS :windows 10
- Others:

**Comment by objcoding** [comment]
https://github.com/seata/seata/pull/2262
