### ISSUE TITLE
Making "for update" configurable in beforeImage stage.

### ISSUE THREAD

**Issue by 81519434** [seata/seata#2269]
## Why you need it?
当执行update或delete语句时，beforeImage肯定会给select语句加"for update"限制，以保证数据不被脏写或者脏读。但是这会加重数据库的负担，因为我们不能要求所有的人都对表建立好了完美的索引。因此一旦执行select for update语句，就会有可能产生锁表的行为。在大流量并发时，完全有可能导致出现多个表死锁。如果业务中断，这是不被接受的。

Seata will append "for update" to select statement in beforeImage method If we execute update or delete SQL. This action will protect our data from dirty reads and dirty write. But this will give a lot of pressure to the database. Because we can't ask everyone to build a perfect index for their database. So it may cause table locking if we execute "select for update" SQL. Furthermore, Multiple tables will lock when we encounter massive traffic. It is not acceptable to crash a website for this reason.

## How it could be?
能否增加一个配置项，让开发者能根据自己的情况配置是否在beforeImage阶段进行for update。比起让网站宕机，我更能够接受脏读或者脏写。
Can you make "for update" configurable? Let developers decide if "select for update" in beforeImage stage by their own situation. I can accept dirty reads or dirty writes more than taking my website down.

**Comment by 81519434** [comment]
![image](https://user-images.githubusercontent.com/9690089/74814691-d1b52000-5332-11ea-98e3-04d34c5f2ede.png)

**Comment by c1139676919** [comment]
请问你是改了源码  把后面加的这个FOR UPDATE这一行代码注释了吗

**Comment by 0000005** [comment]
加配置，用自己魔改的版本

**Comment by c1139676919** [comment]
> 加配置，用自己魔改的版本

你好 能加个联系方式吗

**Comment by 0000005** [comment]
我已经很久没接触seata了，可能帮不了你。

**Comment by c1139676919** [comment]
> 我已经很久没接触seata了，可能帮不了你。

好的  谢谢
