### ISSUE TITLE
SQLVisitorFactory should recognize FOR UPDATE from normal SELECT SQL

### ISSUE THREAD

**Issue by sharajava** [seata/seata#227]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

SQLVisitorFactory should recognize FOR UPDATE from normal SELECT SQL.

It's WRONG that it just take any SELECT sql in transaction context as SELECT FOR UPDATE.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
please close this issue as the related problem has been fixed.
