### ISSUE TITLE
控制台显示回滚成功但实际查看数据库并未回滚

### ISSUE THREAD

**Issue by ChesterZheng** [seata/seata#2271]
诸位大神：
  我碰到一个问题，在测试项目中的控制台显示创建了新的全局事务并显示了xid，回滚也显示Successfully rollback global，但是数据库中的数据并未回滚，断点查看的时候，分支事务表没有数据，undo_log表同样没有数据
我是用的是
jdk-1.8
springcloud-Dalston.SR4
springboot-1.5.11.RELEASE
seata-server-1.0
maven依赖
![图片](https://user-images.githubusercontent.com/23701211/74823279-6e7eba00-5341-11ea-9800-5b0fdc845377.png)

seata的yml配置
![图片](https://user-images.githubusercontent.com/23701211/74823326-7fc7c680-5341-11ea-9aa5-1227c513d5e4.png)

请各位大神指点迷津
谢谢

**Comment by zjinlei** [comment]
https://seata.io/zh-cn/docs/ops/deploy-guide-beginner.html
1.DataSource proxy
2.pass xid

**Comment by upupQo** [comment]
> 诸位大神： 我碰到一个问题，在测试项目中的控制台显示创建了新的全局事务并显示了xid，回滚也显示Successfully rollback global，但是数据库中的数据并未回滚，断点查看的时候，分支事务表没有数据，undo_log表同样没有数据 我是用的是 jdk-1.8 springcloud-Dalston.SR4 springboot-1.5.11.RELEASE seata-server-1.0 maven依赖 ![图片](https://user-images.githubusercontent.com/23701211/74823279-6e7eba00-5341-11ea-9800-5b0fdc845377.png)
> 
> seata的yml配置 ![图片](https://user-images.githubusercontent.com/23701211/74823326-7fc7c680-5341-11ea-9aa5-1227c513d5e4.png)
> 
> 请各位大神指点迷津 谢谢

后来找到原因了吗，我也是seata-serv的log说rollback成功，但是db没有回滚，分支事务表没有数据，undo_log表同样没有数据。
jdk1.8 seata1.5.1
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/17664360/190651164-6bb9eeef-1039-41a7-b4f2-1a40cacde876.png">
