### ISSUE TITLE
V1.0.0版本，我用代理连数据库，一直连不上，愁死了。

### ISSUE THREAD

**Issue by aileennian** [seata/seata#2273]
我知道我的问题有可能很初级，但真 的是尽力了。

引入包：
eata-all.version=1.0.0
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>${seata-all.version}</version>
        </dependency>

    public GlobalTransactionScanner globalTransactionScanner() {
        String appId =  seataConfigProperties.getApplicationId();
        String txServiceGroup = seataConfigProperties.getTxServiceGroup();
        GlobalTransactionScanner transactionScanner = new GlobalTransactionScanner(appId, txServiceGroup);
        //seataProperties.setEnabled(true);
        return transactionScanner;
    }

### Ⅱ. Describe what happened

 ERROR io.seata.core.rpc.netty.AbstractRpcRemoting - wait response error:cost 30001 ms,ip:null,request:RegisterTMRequest{applicationId='SYX-ALI-DEMO-ORDER', transactionServiceGroup='fsp_tx_group'}
19:09:12.480 [timeoutChecker_1] ERROR io.seata.core.rpc.netty.NettyClientChannelManager - 0304 register RM failed.
io.seata.common.exception.FrameworkException: register error,role:TMROLE,err:cost 30001 ms
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:78) ~[seata-all-1.0.0.jar:1.0.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34) ~[seata-all-1.0.0.jar:1.0.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar:1.6]

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@aileennian please paste registry.conf and file.conf of seata-server and client.
