### ISSUE TITLE
seata-spring-boot-starter-1.1.0 SeataAutoConfiguration的完善

### ISSUE THREAD

**Issue by SevenSecondsOfMemory** [seata/seata#2290]
原代码：
@ConditionalOnProperty(prefix = StarterConstants.SEATA_PREFIX, name = "enableAutoDataSourceProxy", havingValue = "true", matchIfMissing = true)

name是一个数组属性，我认为使用两种方式更加完善

@ConditionalOnProperty(prefix = StarterConstants.SEATA_PREFIX, name = {"enableAutoDataSourceProxy", "enable-auto-data-source-proxy"}, havingValue = "true", matchIfMissing = true)

**Comment by xingfudeshi** [comment]
@SevenSecondsOfMemory You're right,then can you submit a PR to optimize it?It will be great!!

**Comment by slievrly** [comment]
@SevenSecondsOfMemory you can try.

**Comment by SevenSecondsOfMemory** [comment]
@xingfudeshi submitted
