### ISSUE TITLE
dubbo-compatible

### ISSUE THREAD

**Issue by jaspercloud** [seata/seata#2294]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
alibaba.dubbo.filter extends apache.dubbo.filter
![2806D6CF-EACD-479c-AA1C-EB38A8B06149](https://user-images.githubusercontent.com/3040720/75206465-74e1bb80-57b1-11ea-9baa-5a8589a3e79e.png)
![B0A7F83D-7791-4383-9A55-57091CA8D64B](https://user-images.githubusercontent.com/3040720/75206473-7c08c980-57b1-11ea-8736-59c7f14b9e15.png)
![87147C55-73BA-42e0-86AC-50712DD94382](https://user-images.githubusercontent.com/3040720/75206480-7f9c5080-57b1-11ea-8339-40fc759cef4a.png)

doc:
http://dubbo.apache.org/zh-cn/blog/dubbo-compatible.html

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
由于apache-dubbo再加载Filter时,会将alibaba-dubbo的filter一并加载,导致出现
`java.lang.NoSuchMethodError: com.alibaba.dubbo.rpc.Invoker.invoke(Lcom/alibaba/dubbo/rpc/Invocation;)Lcom/alibaba/dubbo/rpc/Result;`
即使dubbo再后续版本中修复此版本,2.7.0依然会出现该bug,所以请升级dubbo到2.7.1及以上,保证兼容.本身是alibaba-dubbo可放心使用,因为alibaba-dubbo并不包含apache-dubbo的包.
