### ISSUE TITLE
please upload the release binary to gitee or other site in china 

### ISSUE THREAD

**Issue by breakenknife** [seata/seata#2299]
![image](https://user-images.githubusercontent.com/12994391/75237566-8b603500-57fa-11ea-923e-76dadf33c62c.png)

众所周知，从github上下载二进制包非常之慢（坐标成都），全靠人品。如果方便的话，请传一份到国内网站，比如gitee，感激不尽！

**Comment by xingfudeshi** [comment]
Does [this](https://gitee.com/seata-io/seata/releases) work for you?

**Comment by breakenknife** [comment]
感谢提示！
