### ISSUE TITLE
Error in full-auto ORM framework like JPA

### ISSUE THREAD

**Issue by sherlock-hao** [seata/seata#230]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

When I integrated fescar in springboot+jpa project, local DB operation error happened.

the error message is `(SqlExceptionHelper.java:129) - SQL Error: 1054, SQLState: 42S22
14:57:58.976 ERROR [main] (SqlExceptionHelper.java:131) - Unknown column 'assetassig0_.id' in 'where clause'
14:57:58.980  INFO [main] (DefaultLoadEventListener.java:129) - HHH000327: Error performing load command : org.hibernate.exception.SQLGrammarException: could not extract ResultSet`

Then I found out when select single table data, fescar will try to build a `select *** from *** where *** for update ` to lock the data in DB, but the where clause was copy from the origin sql , but the from part  just use `from {tableName}`.

If my origin select sql is using table alias just like `select * from t_user t_user_00000_ where t_table_00000_.id = ? ` ,then fescar will build `select * from t_user where t_user_00000_.id = ?` to lock the data row,then error `Unknown column 't_user_00000_.id' in 'where clause'
` occurs.

It seems like fescar dose not suport table alias in select statement, maybe update/delete neither.But it's so common to use table alias in sql statement,and it is unavoidable in some full-auto ORM framework like JPA and Hibernate.

Please consider my  issue, thanks!

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
