### ISSUE TITLE
数据源被多次代理？

### ISSUE THREAD

**Issue by ChesterZheng** [seata/seata#2311]
我现在使用seata遇到了一个问题
我搭建的demo项目是使用SpringBoot-2.1.8，SpringCloud Greenwich.SR2, Seata 1.1，数据源Druid-1.1.10
pom使用的是spring-cloud-alibaba-seata，排除了其中的seata-spring-boot-starter和seata-all，
然后单独引用了seta-spring-boot-starter和seata-all，demo项目运行正常
但是我把demo项目中的pom依赖和yml配置移植到我的业务系统以后，启动就会报错，
说我的Hikari是空的，但我并没有使用这个数据源
于是我排除了Hikari的依赖，启动正常了，
但是调用的时候出现类似DynamicDataSource$$EnhancerBySpringCGLIB$$7ca89c70$$EnhancerByCGLIB$$ddb00ff对象，
导致AbstractRoutingDataSource类的determineTargetDataSource方法第一句
Assert.notNull(this.resolvedDataSources, "DataSource router not initialized");判断为空
我是使用自定义注解+自定义切面完成数据库的水平分库分表
曾经尝试把seata-all 1.1从pom中移除，但并没有什么作用
请问是否有办法可以解决

**Comment by xingfudeshi** [comment]
hikari is the default datasouce when using spring boot.

**Comment by ChesterZheng** [comment]
> 
> 
> hikari is the default datasouce when using spring boot.

I know that, but I didn't configure Hikari in my system. I used Druid only.

**Comment by q294881866** [comment]
This is a confusing problem. It is suggested that developer turn demo first. Develop business on the basis of demo, now it performs well.

**Comment by ChesterZheng** [comment]
> 
> 
> This is a confusing problem. It is suggested that developer turn demo first. Develop business on the basis of demo, now it performs well.

I did make a demo project, it works well, when I moved the configuration of demo proejct to my bussiness-system, It doesn't work. Now, I probably know why it doesn't work, maybe is #2321

**Comment by xingfudeshi** [comment]
Will be fixed in next release.
