### ISSUE TITLE
feature: registry.conf suffix support customize

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2314]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
English: The conf component supports reading files of type .conf,.properties,*.yml, but currently only limits reading files of type *.conf when programs depend on seata-all.

Chinese: 用户可以自定义registry.conf的后缀名

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
Optimize ConfigurationFactory.java

**Comment by slievrly** [comment]
The conf component supports reading files of type *.conf,*.properties,*.yml, but currently only limits reading files of type *.conf when programs depend on seata-all.

**Comment by wangwei-ying** [comment]
Hi, I will do it.
