### ISSUE TITLE
feature: nacos configuration center uses a single configuration item for large configuration text

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2316]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

English: When Seata use nacos as the configuration center, the configuration center will contain dozens of configuration items, which is not conducive to configuration reading. We want to combine these configuration items into a configuration of large text type.

Chinese:  nacos配置中心使用单配置项大配置文本

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
When Seata use nacos as the configuration center, the configuration center will contain dozens of configuration items, which is not conducive to configuration reading. We want to combine these configuration items into a configuration of large text type.
