### ISSUE TITLE
[mysql datetime]Cannot convert class java.sql.Timestamp to SQL

### ISSUE THREAD

**Issue by Jonven** [seata/seata#2330]
exception message:
Cannot convert class java.sql.Timestamp to SQL type requested due to java.lang.NullPointerException - null

When the data is rolled back, the undo_log table is queried and updated back to my own business table, an exception occurs. Because the modified field of my business table is of datetime type, the time format of Seata when inserting the undo_log table is accurate to milliseconds, and an error is reported when the business table is updated

I see that Seata version 0.8.0 has fixed the time issue of timestamp serialization, but this exception still occurs in version 1.1.0

**Comment by Jonven** [comment]
![image](https://user-images.githubusercontent.com/9896522/75663570-01a5e100-5cac-11ea-853d-016ea6d4acf2.png)

**Comment by slievrly** [comment]
@Jonven #1443

**Comment by slievrly** [comment]
@Jonven do you use jackson serializer? kyro and protostuff fix in #2309.

**Comment by Jonven** [comment]
@slievrly Yes, I use version 1.1.0, which uses Jackson serializer.

**Comment by zjinlei** [comment]
https://github.com/seata/seata/issues/1578
