### ISSUE TITLE
seata-server1.1.0启动时报sql错误， 

### ISSUE THREAD

**Issue by xijue987654** [seata/seata#2342]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata-server1.1.0启动时报sql错误

### Ⅱ. Describe what happened
启动服务时报错

  If there is an exception, please attach the exception trace:
LogStoreDataBaseDAO-->init()-->initTransactionNameSize() -->
ColumnInfo columnInfo = queryTableStructure(globalTable, TRANSACTION_NAME_KEY) -->
ResultSet tableRs = dbmd.getTables(null, schema, null, new String[]{"TABLE"});
```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. ResultSet tableRs = dbmd.getTables(null, schema, null, new String[]{"TABLE"});  第三个参数不能为null, 传“%”；

### Ⅵ. Environment:

- JDK version : 1.8
- OS : 
- Others:

**Comment by l81893521** [comment]
Thank you. I think you are right. We will fix it later.

**Comment by l81893521** [comment]
What's you database type and version?

**Comment by xijue987654** [comment]
datasource = "druid"
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"

**Comment by xijue987654** [comment]
mysql version: 8.0.11

**Comment by l81893521** [comment]
Thanks for you report.

**Comment by l81893521** [comment]
Fixed. You can check at #2449

**Comment by slievrly** [comment]
@xijue987654 next time you have a similar problem, you can submit a pr contribution to the community.

**Comment by xijue987654** [comment]
ok， thank you
