### ISSUE TITLE
跨schema操作的时候会多拼接一个schema前缀

### ISSUE THREAD

**Issue by hardpbl** [seata/seata#2344]
环境信息：jdk1.8+springboot+springCloud+mybatis
场景：
A服务对应了一个A schema，B服务对应了一个B schema，当我在A服务里面想操作B服务的C表的数据的时候seata会默认在前面多拼接了一个schema约束 类似于 insert into A.B.C xxx, 而此时我想要的是insert into B.C xxx，这就会使得找不到表全局事务回滚失败。
愿景：
不知能否提供一个配置可以灵活的开启自动加前缀的功能呢？

**Comment by ChangMuChen** [comment]
请问你是如何解决的，我也遇到这相同问题
