### ISSUE TITLE
optimize: Generated instances that were not actually used when the class was loaded

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2350]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/20024955/75879946-4de15480-5e57-11ea-9c28-3a216c65aa1f.png)
MysqlTableMetaCache,PostgresqlTableMetaCache ,JacksonUndoLogParser, etc. classes with static variables.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by ph3636** [comment]
Please assign it to me.
