### ISSUE TITLE
2个分支事务回滚了4次分支事务

### ISSUE THREAD

**Issue by zhuyouzhufu** [seata/seata#2352]
![image](https://user-images.githubusercontent.com/34908518/75885666-e1b81e00-5e61-11ea-984f-852027bf0e1f.png)
![image](https://user-images.githubusercontent.com/34908518/75885776-162bda00-5e62-11ea-9b14-6d322ae69671.png)
![image](https://user-images.githubusercontent.com/34908518/75885858-407d9780-5e62-11ea-8ac8-33ad2ed195ff.png)
![image](https://user-images.githubusercontent.com/34908518/75885916-58edb200-5e62-11ea-8408-6aa399d1333b.png)

**Comment by zhuyouzhufu** [comment]
说明一下：每个方法save都是单表插入，Seata的版本为1.0.0.还有一个疑问，分支事务回滚了 undo_log日志是不是就不删除了？

**Comment by zhuyouzhufu** [comment]
![image](https://user-images.githubusercontent.com/34908518/75886275-efba6e80-5e62-11ea-9002-5c90c534ea05.png)

**Comment by zhuyouzhufu** [comment]
说明一下分布式事务回滚是OK的，但是我有点疑惑为什么会2个分支事务提示回滚4次分支？是日志多输出了2次(有时候日志是提示回滚2个分支事务)？

**Comment by zhuyouzhufu** [comment]
附上正常时候的日志输出
![image](https://user-images.githubusercontent.com/34908518/75887165-53916700-5e64-11ea-8b74-56e18e1d8c41.png)

**Comment by zjinlei** [comment]
> 说明一下：每个方法save都是单表插入，Seata的版本为1.0.0.还有一个疑问，分支事务回滚了 undo_log日志是不是就不删除了？

https://seata.io/zh-cn/docs/overview/faq.html#3

**Comment by slievrly** [comment]
@zhuyouzhufu a branch transaction represents a database commit.

**Comment by xlxomg** [comment]
@zhuyouzhufu 我之前也遇到过, 可能是你的分支事务没有加@Transactional的原因,  不加的话貌似把插入undo_log也当成了一次提交, 就有两条记录了
