### ISSUE TITLE
feature: FailureHandler implement can be read from the container

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2353]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
Currently, it can only be injected through the constructor of GlobalTransactionScanner. A more deterministic way is needed.
Reference ObjectHolder.java

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by ph3636** [comment]
Please assign it to me.
