### ISSUE TITLE
feature: Set configurable service name automatically when registering with nacos

### ISSUE THREAD

**Issue by threefish** [seata/seata#2355]
## Why you need it?
希望 seata-server 在向nacos注册时自动设置可配置的服务名，目前的seata在nacos中的服务名为serverAddr不利于理解。

## Other related information
![image](https://user-images.githubusercontent.com/6268640/75942860-79ebec80-5ece-11ea-9ab9-91fa57e5ad2c.png)

**Comment by ruqinhu** [comment]
Please assign it to me.
