### ISSUE TITLE
seate客户端总是连接不上服务端?

### ISSUE THREAD

**Issue by cielswift** [seata/seata#2356]
spring boot version 2.2.5
seata version 1.1.1;

![image](https://user-images.githubusercontent.com/42295829/75946172-52e5e880-5ed7-11ea-8dae-59af72faedc4.png)

一直卡在这里
![image](https://user-images.githubusercontent.com/42295829/75946209-6d1fc680-5ed7-11ea-9c13-af40a338f68b.png)

我尝试了 seata-server.bat -p 19222 -m file
seata-server.bat -p 19222 -m db 
修改过registry 里 位file 和 nacos 都不行?
![image](https://user-images.githubusercontent.com/42295829/75946283-a9532700-5ed7-11ea-9ec3-ebf365184e2c.png)

**Comment by slievrly** [comment]
@cielswift according to the log you provided, tc server has been connected.

**Comment by LiuPing95** [comment]
注册配置的application要配置成seata服务的服务名
