### ISSUE TITLE
io.seata.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:

### ISSUE THREAD

**Issue by wchaowu** [seata/seata#2357]
启动之后访问

o.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539959368 - discarded

版本：v1.1.0

**Comment by skyuck** [comment]
我也报这个错误  版本1.2.0

**Comment by zilongfeng** [comment]
我也是！！解决了踢我
