### ISSUE TITLE
seata 无权限连接nacos1.2.0版本

### ISSUE THREAD

**Issue by jin-kinger** [seata/seata#2365]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
nacos1.2.0 最新版本，默认关闭认证：nacos.core.auth.enabled=false

当开启认证：nacos.core.auth.enabled=true后

seata 就无权限连接nacos1.2.0版本，
报错："error":"Forbidden","message":"unknown user!"

**Comment by jsbxyyx** [comment]
@a364176773

**Comment by a364176773** [comment]
i will deal

**Comment by zjinlei** [comment]
fixed.will release in 1.2.0.
