### ISSUE TITLE
there is no record in the table undo_log of datasource of dubbo-storage-service.xml after example worked

### ISSUE THREAD

**Issue by SnailDHC** [seata/seata#238]
after example worked, there is a record in the table undo_log of datasource of dubbo-account-service.xml, and also there is a record in the table undo_log of datasource of dubbo-order-service.xml, but there is no record in the table undo_log of datasource of dubbo-storage-service.xml. Is this right？And When will the data be written to the table undo_log?
![a](https://user-images.githubusercontent.com/25739214/51665513-e374a880-1ff6-11e9-85a4-287680205382.gif)

**Comment by tankilo** [comment]
To the last question     
**During phase one of each branch session**      
The change made by business code and the new record in undolog will be committed in the same local transaction    
**During phase two rollback stage of each branch session**      
The recover of the bussiness data and deleting undolog record will be committed in the same local transaction    
**During phase two commit stage of global session**      
the corresponding records of undolog will be asynchronously deleted by fescar-server

=================================================

**每个分支事务第一阶段**
业务的修改 和 对应的undolog新增 是一个本地事务里提交的。
**第二阶段全局回滚 每个分支事务回滚的时候**
从undolog里构造sql还原数据到分支事务前的修改 和 删除undolog是一个本地事务里提交的
**第二阶段全局提交**
fescar-server异步删除undolog的对应记录

**Comment by leizhiyuan** [comment]
because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
