### ISSUE TITLE
nacos-config.sh 从windows拷贝到Linux执行，报错：行15: $'\r': 未找到命令

### ISSUE THREAD

**Issue by dongwenting** [seata/seata#2385]
seata版本1.2.0-SNAPSHOT

https://github.com/seata/seata/blob/develop/script/config-center/nacos/nacos-config.sh

1、nacos-config.sh 从windows拷贝到Linux执行，报错：行15: $'\r': 未找到命令
可以通过dos2unix nacos-config.sh，修复该问题，但是能不能兼容两种系统

2、nacos-config.sh里大量\033[32m，\033[31m ，\033[0m影响阅读，请去掉

3、config.txt中配置Oracle数据库连接串时，执行nacos-config.sh通不过 
store.db.url=jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = )(PORT = 1521)) (ADDRESS = (PROTOCOL= TCP)(HOST = 4)(PORT = 1521))  (LOAD_BALANCE = no) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ) (failover_mode=(type=session)(method=basic))))
由于连接串中包含大量空格导致

**Comment by slievrly** [comment]
@objcoding

**Comment by objcoding** [comment]
Thanks for feedback, fix later

**Comment by objcoding** [comment]
2/3 ：https://github.com/seata/seata/pull/2390
