### ISSUE TITLE
optimize:  unnecessary to register branch transaction when undo is empty

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2388]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
![image](https://user-images.githubusercontent.com/20024955/76301590-7951bc80-62f9-11ea-9f88-37ff0ee163ab.png)
When database operations are unchanged, no need to register branch transaction.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by lightClouds917** [comment]
I will resolve it
