### ISSUE TITLE
seata1.1.0 release、1.2.0-SNAPSHOT fix_duplicate_proxy分支不能自动代理数据源

### ISSUE THREAD

**Issue by yougecn** [seata/seata#2392]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
测试过seata1.1.0 release、1.2.0-SNAPSHOT fix_duplicate_proxy分支不能自动代理数据源；
手工代理没问题
[数据源未自动代理日志.txt](https://github.com/seata/seata/files/4316678/default.txt)

配置信息如下
seata:
  enabled: true
  application-id: applicationName_Base
  tx-service-group: my_test_tx_group
  enableAutoDataSourceProxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091

部分依赖信息如下：
跟project中
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-seata</artifactId>
                <version>2.2.0.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>io.seata</groupId>
                <artifactId>seata-spring-boot-starter</artifactId>
                <version>1.2.0-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
子moudel中
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
        </dependency>

### Ⅵ. Environment:

- JDK version :1.8
- OS :windows7 64
- Others:
日志详见附件
[数据源未自动代理日志.zip](https://github.com/seata/seata/files/4316744/default.zip)

**Comment by xingfudeshi** [comment]
Try this PR https://github.com/seata/seata/pull/2323

**Comment by yougecn** [comment]
> Try this PR #2323

试过了，就是这个1.2.0-SNAPSHOT fix_duplicate_proxy
https://github.com/seata/seata/pull/2323

**Comment by xingfudeshi** [comment]
This bug has been fixed,will be released in next version.

**Comment by yougecn** [comment]
Thanks.

**Comment by PupilGuan** [comment]
我也遇到了，期待released
