### ISSUE TITLE
springboot+springcloud+PGSQL+Seata1.1.0  项目正常启动后 影响业务sql 

### ISSUE THREAD

**Issue by MusangZ** [seata/seata#2394]
未引入前,sql正常执行。
org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $3

**Comment by MusangZ** [comment]
解决办法:在xml里 指定字段类型  ::varchar

**Comment by l81893521** [comment]
Sorry, I m not understand what s you mean. Could you give more error detail?

**Comment by JesseRo** [comment]
```
    private void initParameterHolder() throws SQLException {
        int paramCount = targetStatement.getParameterMetaData().getParameterCount();
        this.parameters = new ArrayList[paramCount];
        for (int i = 0; i < paramCount; i++) {
            parameters[i] = new ArrayList<>();
        }
    }
```
This method above is in AbstractPreparedStatementProxy.
If postgres cannot infer preparedStatement's parameter type, excuting of _targetStatement.getParameterMetaData()_ will generate exception.
But that is no necessary, there must be other ways to get paramCount. @l81893521

**Comment by l81893521** [comment]
@JesseRo Thanks you.
