### ISSUE TITLE
Seata，并发修改同一条数据，出现回滚不成功的情况

### ISSUE THREAD

**Issue by 569844962** [seata/seata#2403]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
对同一条数据进行并发修改，发现undo表没有删除，seata service 一直提示回滚失败。

### Ⅱ. Describe what happened

1.我对一个update接口加入seata全局锁
2.对该接口进行并发测试
3.出现undo表数据没有被删除，seata服务端提示数据回滚失败；业务服务端返回日志，old value 与 new value不一致，不能回滚
![image](https://user-images.githubusercontent.com/11012453/76674795-05136380-65ee-11ea-9ead-aef789a08ca8.png)

### Ⅲ. Describe what you expected to happen
请问这个问题如何解决？希望能提供思路

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows
- Others: mysql5.7，seata 1.0

**Comment by zjinlei** [comment]
https://github.com/seata/seata-samples/blob/master/springboot-mybatis/sbm-storage-service/src/main/java/io/seata/samples/storage/service/StorageService.java

**Comment by al-verson** [comment]
大佬，这个问题你是怎么解决的呢
