### ISSUE TITLE
no available service 'null' found, please make sure registry config correct

### ISSUE THREAD

**Issue by huc003** [seata/seata#2406]
seata 调试springcloud-nacos-seata demo的时候，启动服务报错i.s.c.r.netty.NettyClientChannelManager  : no available service 'null' found, please make sure registry config correct，请问这个是什么问题，nacos注册中心serverAddr 、storage-service、order-service这三个服务都是有的

**Comment by slievrly** [comment]
@huc003 Check the business side configuration item `vgroupMapping. * ` ,it is recommended to read the Seata website `https://seata.io/zh-cn/docs/ops/deploy-guide-beginner.html `document.

**Comment by huc003** [comment]
seata-server nacos-config.txt 
--
service.vgroup_mapping.storage-service-group=default
service.vgroup_mapping.order-service-group=default
--

storage-service
application.properties
--
spring.cloud.alibaba.seata.tx-service-group=storage-service-group
--

order-service
application.properties
--
spring.cloud.alibaba.seata.tx-service-group=order-service-group
--

registry.conf
--
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"
  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3、springCloudConfig
  type = "nacos"
  nacos {
    serverAddr = "localhost"
    namespace = "public"
    group = "SEATA_GROUP"
  }
}

Starting service error
order-service、storage-service
no available service 'null' found, please make sure registry config correct

**Comment by zjinlei** [comment]
namespace = "public"

**Comment by huc003** [comment]
namespace = "public"   什么意思？去掉？

**Comment by huc003** [comment]
没有人遇到这个问题？

**Comment by qihaooo** [comment]
application.properties中配置
spring.cloud.alibaba.seata.tx-service-group=${spring.application.name}-fescar-service-group

file.conf中配置
vgroupMapping.${spring.application.name}-fescar-service-group = "default"

同时需要启动服务端，服务端如果使用docker启动需要网络共享 --network=host,同时需要更改里面的注册中心地址，和业务配置的注册中心保持一致，同时在业务的file.conf中加入seata服务端地址：
default.grouplist = "192.168.xx.xx:8091"

**Comment by qihaooo** [comment]
> 没有人遇到这个问题？
application.properties中配置
spring.cloud.alibaba.seata.tx-service-group=${spring.application.name}-fescar-service-group

file.conf中配置
vgroupMapping.${spring.application.name}-fescar-service-group = "default"

同时需要启动服务端，服务端如果使用docker启动需要网络共享 --network=host,同时需要更改里面的注册中心地址，和业务配置的注册中心保持一致，同时在业务的file.conf中加入seata服务端地址：
default.grouplist = "192.168.xx.xx:8091"

**Comment by fade-away** [comment]
这个问题是怎么解决？能否提供下方案

**Comment by pearl88** [comment]
> 这个问题是怎么解决？能否提供下方案

测试的时候经常遇到这个问题， 配置完全正确，临时解决方案：1.重启seata 2.重新发布service.vgroupMapping这个配置

**Comment by BoGeManger** [comment]
怎么解决的，好几天了，哪个好心人提供下方法

**Comment by kongfanyu** [comment]
no available service 'null' found, please make sure registry config correct
seata 1.20  同样这个问题

**Comment by huangwenyi10** [comment]
> seata 调试springcloud-nacos-seata demo的时候，启动服务报错i.s.c.r.netty.NettyClientChannelManager : no available service 'null' found, please make sure registry config correct，请问这个是什么问题，nacos注册中心serverAddr 、storage-service、order-service这三个服务都是有的

vgroup_mapping.fsp_tx_group = "default"

换成 
vgroupMapping.fsp_tx_group = "default" 可能问题就解决了，不行的话，升级seata的版本

**Comment by sluo-wind** [comment]
![image](https://user-images.githubusercontent.com/66930349/102982042-dcd56f80-4544-11eb-9a82-b7e768f22bdd.png)

**Comment by Scalaaaaaa** [comment]
看nacos上的注册信息,发现  seata-server这个服务的ip是172.xx.xx.1  , 而这个地址是docker的虚拟ip,别的机器上访问不到,  然后网上查询怎么设置seata绑定的ip, 就是seata-server.sh -h ip地址,然后绑定192.168的ip地址就可以了.因为172的ip地址  在别的机器上是ping不通的,172的地址是docker的虚拟地址,只能这个虚拟地址所在机器上才可以ping通.

**Comment by yidianyidi-xss** [comment]
> 怎么解决的，好几天了，其中好心人提供下方法

查看server端的file.conf和client端的file.conf文件，对比service{}块中的vgroupMapping.*参数是否一致。

**Comment by 316189693** [comment]
问题出在service.vgroupMapping.order-service-seata-service-group=default 这个 ‘vgroupMapping’， 以及绑定的group要对， 亲测有效

![image](https://user-images.githubusercontent.com/17778692/132018732-4294c602-d619-47ae-9141-0922f54b8e1d.png)

![image](https://user-images.githubusercontent.com/17778692/132018819-7c111721-48e5-43b7-b78c-954fde83aad7.png)

![image](https://user-images.githubusercontent.com/17778692/132018942-03f0baa1-0e84-429b-b3c7-9fa3d1a0c968.png)

![image](https://user-images.githubusercontent.com/17778692/132019141-58297f49-45c1-43c3-85ad-aea8c20f576e.png)

![image](https://user-images.githubusercontent.com/17778692/132019395-5917e3c2-989f-4db4-957c-9f1940d9a6b6.png)

![image](https://user-images.githubusercontent.com/17778692/132019438-3cb97409-75d7-4860-b804-327ebecd9301.png)

![image](https://user-images.githubusercontent.com/17778692/132019882-01ec60de-7efa-463a-a5c3-8674de2c0af9.png)

**Comment by wangjing0716** [comment]
遇到类似的问题，本地ok,开发环境就是  no available service 'seata-server' found, please make sure registry config correct
client用的1.3.0，seata-server是1.5.0，注册中心是 eureka，seata-server的配置中心是file模式。
DiscoveryClient_UNKNOWN/127.0.0.1 - was unable to refresh its cache! status = Cannot execute request on any known server

**Comment by ChengxiangA** [comment]
我遇到了类似的问题，我是通过以下方式解决的：
1. 添加映射规则（如果application.yaml里没有声明tx-service-group事物分组名，默认为{spring-application-name}-seata-service-group，只要在seata的配置文件中添加分组对应集群的映射即可，如果没有集群映射到default即可）
![image](https://user-images.githubusercontent.com/59275596/160228149-67ccd457-d8d0-4c93-9b3b-a8be1409fdff.png)

2.seata服务端和客户端的版本一定要一致
![image](https://user-images.githubusercontent.com/59275596/160228505-03226fb8-9c06-47af-b5f7-6ff80bc1abbb.png)
