### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by pengzhengfa** [seata/seata#2413]
<img width="841" alt="seata" src="https://user-images.githubusercontent.com/33858082/76825080-ddbdd000-6853-11ea-8184-a2a0adf65af4.png">

**Comment by slievrly** [comment]
@pengzhengfa can you contribute to the community to improve it?

**Comment by pengzhengfa** [comment]
Of course, thank you for giving me this opportunity

**Comment by a364176773** [comment]
contact me if you need me to handle it

**Comment by pengzhengfa** [comment]
okay, thank you

**Comment by pengzhengfa** [comment]
OK, thank you for your kind help

**Comment by pengzhengfa** [comment]
Hello, is this optimization strategy feasible? Please review

**Comment by pengzhengfa** [comment]
![image](https://user-images.githubusercontent.com/33858082/77821002-8e17b800-7121-11ea-92a9-ae15f7c98de5.png)

**Comment by pengzhengfa** [comment]
okay, thank you

**Comment by lightClouds917** [comment]
You can open this issue,then point to the pr to this issue.
