### ISSUE TITLE
Caused by: io.seata.common.exception.StoreException: Duplicate entry '2038143799' for key 'PRIMARY'

### ISSUE THREAD

**Issue by hewenjian123** [seata/seata#2416]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
please try this pr content #2412
