### ISSUE TITLE
Some improvments abount TCC are in planning or in progress?

### ISSUE THREAD

**Issue by apodemakeles** [seata/seata#2421]
1. In AT mode, seata prevents resources from suspending, as well as unnecessary rollback. e.g:
first.  TC- Rollback -> RM  
second. TM - do sth -> RM
I found it not be taken to account in TCC mode. Is it better to implement it in business code ? Or should seata handle it?

2. In additional, I'd like to code the commit/rollback methods without parameter BusinessActionContext, other parameters should be "auto-wired":
boolean rollback(@XxxParameter("opId") long opId){
...
}

**Comment by wangliang181230** [comment]
> 
> In additional, I'd like to code the commit/rollback methods without parameter BusinessActionContext, other parameters should be "auto-wired":
> boolean rollback(@XxxParameter("opId") long opId){
> ...
> }

after #3728 merged, we will start to deal with this requirement. Enhance `@BusinessActionContextParameter`.

**Comment by wangliang181230** [comment]
> 
> 
> In AT mode, seata prevents resources from suspending, as well as unnecessary rollback. e.g:
> first. TC- Rollback -> RM
> second. TM - do sth -> RM
> I found it not be taken to account in TCC mode. Is it better to implement it in business code ? Or should seata handle it?
> 

The merged pr #3545 feature: TCC mode support idempotent and anti hanging。
Is this what you need?

**Comment by apodemakeles** [comment]
> > 1. In AT mode, seata prevents resources from suspending, as well as unnecessary rollback. e.g:
> >    first. TC- Rollback -> RM
> >    second. TM - do sth -> RM
> >    I found it not be taken to account in TCC mode. Is it better to implement it in business code ? Or should seata handle it?
> 
> The merged PR #3545 feature: TCC mode support idempotent and anti hanging。
> Is this what you need?

I don't care about it anymore :)
but it seem to be right.

**Comment by wangliang181230** [comment]
> 
> 
> > > 1. In AT mode, seata prevents resources from suspending, as well as unnecessary rollback. e.g:
> > >    first. TC- Rollback -> RM
> > >    second. TM - do sth -> RM
> > >    I found it not be taken to account in TCC mode. Is it better to implement it in business code ? Or should seata handle it?
> > 
> > 
> > The merged PR #3545 feature: TCC mode support idempotent and anti hanging。
> > Is this what you need?
> 
> I don't care about it anymore :)
> but it seem to be right.

I'm sorry I didn't reply to you in time. No one has tracked `TCC` issues before. In the future, I will focus on `TCC` issues.
