### ISSUE TITLE
io.seata.common.util.StringUtils#toString 存在线程栈溢出问题

### ISSUE THREAD

**Issue by ppj19891020** [seata/seata#2423]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
HeartbeatMessage 在使用io.seata.common.util.StringUtils#toString时会出现如下异常：
```less
Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate io.seata.core.protocol.RpcMessage.toString()
MergeResultMessage xid=192.168.202.137:8091:2051472139;extraData=null;
```
![seata](https://raw.githubusercontent.com/ppj19891020/pictures/master/seata/4.png)
![seata](https://raw.githubusercontent.com/ppj19891020/pictures/master/seata/5.png)
![seata](https://raw.githubusercontent.com/ppj19891020/pictures/master/seata/6.png)
![seata](https://raw.githubusercontent.com/ppj19891020/pictures/master/seata/7.png)

### Ⅱ. Describe what happened
Tm 端debug代码的时候发现的

**Comment by zjinlei** [comment]
Thx
