### ISSUE TITLE
spring boot 使用 RegistryZooKeeperProperties 连接时，配置获取不到

### ISSUE THREAD

**Issue by kissss** [seata/seata#2432]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
当通过spring boot 加载配置，通过bean单独注入时，配置获取为空

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
Did you inject that bean directly in your project?

**Comment by xingfudeshi** [comment]
Can provide more details.
