### ISSUE TITLE
optimize: optimize LockKey's test cases in db mode

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2434]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

The lock_key field of the branch_table table has been removed [#1905].
We need to update the lock_key related test cases in the db mode.
Such as DataBaseLockManagerImplTest.java, DataBaseSessionManagerTest.java.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by lightClouds917** [comment]
assign to me
