### ISSUE TITLE
seata v1.0.0-GA服务端启动报 SQL syntax

### ISSUE THREAD

**Issue by HelloLingyun** [seata/seata#2437]
### Ⅰ环境：seata v1.0.0-GA
                   mysql-connector-java-8.0.11.jar
                   mysql 8.0.12
                   win10
                   java8
###Ⅱ 过程. 本地数据库已创建seata并导入db_store.sql，创建branch_table、global_table、lock_table。
将原来的lib的mysql-connector-java-5.1.30.jar 替换成mysql-connector-java-8.0.11.jar
然后修改了file.conf，如下图
![image](https://user-images.githubusercontent.com/31378384/77223091-6f9b4500-6b94-11ea-9837-59bbca0ccd13.png)
启动seata-server.bat，出现下面错误信息
![image](https://user-images.githubusercontent.com/31378384/77223117-b2f5b380-6b94-11ea-8fa9-7a2aae21f00e.png)

**Comment by HelloLingyun** [comment]
换mysql-connector-java-8.0.18.jar可以了

**Comment by slievrly** [comment]
@HelloLingyun There is no need to replace the mysql-driver jar in the upcoming 1.2.0 release.
