### ISSUE TITLE
can not do maven build in sub module

### ISSUE THREAD

**Issue by sharajava** [seata/seata#2438]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

I can NOT run mvn clean install in sub module. For example:

in rm-resource

> mvn clean install

Will fail on checkstyle:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project seata-rm-datasource: Failed during checkstyle execution: Unable to find configuration file at location: /Users/hashen/dev/github/fescar/rm-datasource/style/seata_checkstyle.xml: Could not find resource '/Users/hashen/dev/github/fescar/rm-datasource/style/seata_checkstyle.xml'. -> [Help 1]

Then skip checkstyle:

> mvn clean install -Dcheckstyle.skip=true

Just fail on license check:

[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:remove (default) on project seata-rm-datasource: Execution default of goal com.mycila:license-maven-plugin:3.0:remove failed: Cannot read header document /Users/hashen/dev/github/fescar/rm-datasource/style/copyright. Cause: Resource /Users/hashen/dev/github/fescar/rm-datasource/style/copyright not found in file system, classpath or URL: no protocol: /Users/hashen/dev/github/fescar/rm-datasource/style/copyright -> [Help 1]

I have to skip both checkstyle and license check:

mvn clean install -Dcheckstyle.skip=true -Dlicense.skip=true

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
please skip code verification or format cod

**Comment by Garlichead** [comment]
对maven的执行机制不熟悉 我个人想法是不是可以先分析maven的执行机制
