### ISSUE TITLE
LockConflictException问题

### ISSUE THREAD

**Issue by sj13824803000** [seata/seata#2461]
使用seata版本:1.1.0,使用file作为存储
遇到问题: 由于使用feign的超时重置多次,导致被调用的服务多次插入同一份数据,导致seata抛出异常LockConflictException: get global lock fail, xid:172.21.0.4:8091:2038828992. 发现问题后,改成不重试,依旧会抛出这个异常,知道我重启了seata才能正确插入.
想知道如果下次遇到这种情况,除了重启seata还有什么解决办法吗

**Comment by a364176773** [comment]
尝试调整client.rm.lock.retryInterval和client.rm.lock.retryTimes的值来保证获取锁的周期合理

**Comment by sj13824803000** [comment]
主要是如果不手动重启seata,这个冲突会一直存在.  而且重启不存在是因为用docker部署,重启后存储还原了

**Comment by a364176773** [comment]
> 主要是如果不手动重启seata,这个冲突会一直存在. 而且重启不存在是因为用docker部署,重启后存储还原了

重启seata是因为你的模式是file吧,请切换为db,不过无论是file还是db都应该获取失败就没了,除非是你的并发量比较大,让你造成了一直冲突的错觉,其实是其它的事务尝试获取锁超时了导致的.

**Comment by Garlichead** [comment]
> > 主要是如果不手动重启seata,这个冲突会一直存在. 而且重启不存在是因为用docker部署,重启后存储还原了
> 
> 重启seata是因为你的模式是file吧,请切换为db,不过无论是file还是db都应该获取失败就没了,除非是你的并发量比较大,让你造成了一直冲突的错觉,其实是其它的事务尝试获取锁超时了导致的.

这个错误经常遇到 我在运行demo的时候也经常出现 使用的是db模式
