### ISSUE TITLE
seata-server使用etcd3时，服务节点注册不成功

### ISSUE THREAD

**Issue by sunshaohua0221** [seata/seata#2470]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata-server使用etcd3作为注册中心时，启动成功后，客户端取不到注册中心的服务地址

### Ⅱ. Describe what happened
seata-server服务启动成功后，在etcd3查询不到注册的节点信息，关键字：registry-seata-

查看源码后，发现注册服务节点信息时，put的key没有加前缀“/”，才导致注册不成功，如果改成"/registry-seata-"，则可注册成功

### Ⅲ. Describe what you expected to happen
修复后，重新发布下可用部署包

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 选择etcd3作为注册中心
2. 启动服务
3. 查看etcd3是否注册成功，关键字：registry-seata-

### Ⅴ. Anything else we need to know?
Nothing

### Ⅵ. Environment:

- JDK version : 1.8
- OS : Windows、Linux
- Others: seata-server 1.1.0

**Comment by slievrly** [comment]
@sunshaohua0221 has the problem been solved?
