### ISSUE TITLE
问题：关于GlobalSession Xid 的问题

### ISSUE THREAD

**Issue by juaihua** [seata/seata#2483]
我看文档了解到：
TM首先会向TC申请一个全局的Xid, 然后后续的文服务调用总会传递这个 Xid, 我想知道何时、通过什么机制传输的呢？

**Comment by a364176773** [comment]
> 我看文档了解到：
> TM首先会向TC申请一个全局的Xid, 然后后续的文服务调用总会传递这个 Xid, 我想知道何时、通过什么机制传输的呢？
when using remote call. read more seata-integration module

**Comment by kissss** [comment]
jvm内部是通过 threadlocal 来传递方法级别的上下文
外部调用是通过 上下文，比如 dubbo 的 attachments
feign 是通过 header

**Comment by juaihua** [comment]
txs

**Comment by Garlichead** [comment]
这个如果自己去跟进源码 也是可以分析出来的 我个人感觉这个答案并不是重要的 关键在于自己的探索那个过程

**Comment by juaihua** [comment]
> 这个如果自己去跟进源码 也是可以分析出来的 我个人感觉这个答案并不是重要的 关键在于自己的探索那个过程

谢谢，您说的很对。

**Comment by Garlichead** [comment]
> > 这个如果自己去跟进源码 也是可以分析出来的 我个人感觉这个答案并不是重要的 关键在于自己的探索那个过程
> 
> 
> 
> 谢谢，您说的很对。

您客气了
