### ISSUE TITLE
hikari数据源发生not support sql :  (REPLACE(uuid(), '-', ''),?)    

### ISSUE THREAD

**Issue by xieshenace** [seata/seata#2485]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Error updating database.  Cause: java.sql.SQLException: io.seata.common.exception.NotSupportYetException: not support sql [insert into sts_vehicle_refueling_report
        (id, entp_id)
        values

            (REPLACE(uuid(), '-', ''),?)
         ,
            (REPLACE(uuid(), '-', ''),?)
         ,
            (REPLACE(uuid(), '-', ''),?)
         ,
            (REPLACE(uuid(), '-', ''),?)
         ,
            (REPLACE(uuid(), '-', ''),?)]

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS :
- Others:

**Comment by a364176773** [comment]
not support sql

**Comment by pengzhengfa** [comment]
This data source is not currently supported
