### ISSUE TITLE
bug-NPE:lock key is null,lead to NPE

### ISSUE THREAD

**Issue by lightClouds917** [seata/seata#2496]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened
如果查询的结果为空，最后全局锁检查时会检查不通过，并且抛异常。
  If there is an exception, please attach the exception trace:
![image](https://user-images.githubusercontent.com/33415199/78125398-8fa7ef80-7443-11ea-9da4-fc0ab76ff47a.png)

![image](https://user-images.githubusercontent.com/33415199/78125620-ddbcf300-7443-11ea-9602-4580cdd19b38.png)

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by liquanjin** [comment]
别忘了Seata-Server 的校验。该场景下，Server端也会报错：NPE

**Comment by liquanjin** [comment]
还有Seata-Server 的校验。该场景下，Server端也会报错：NPE

**Comment by lightClouds917** [comment]
> 还有Seata-Server 的校验。该场景下，Server端也会报错：NPE

Yes,when lockkey is null,we will do Two measures:
1.The rm do not send request to tc to checklock;
2.The tc need check NPE before collect RowLocks;

**Comment by Garlichead** [comment]
> > 还有Seata-Server 的校验。该场景下，Server端也会报错：NPE
> 
> Yes,when lockkey is null,we will do Two measures:
> 1.The rm do not send request to tc to checklock;
> 2.The tc need check NPE before collect RowLocks;

so What should i do. select result is null very common

**Comment by Garlichead** [comment]
this problem is solve?
