### ISSUE TITLE
@GlobalLock 的设计对代码侵入较重

### ISSUE THREAD

**Issue by liquanjin** [seata/seata#2497]
## Why you need it?

目前使用全局锁@GlobalLock时，限制条件过于苛刻——必须要添加@Transaction 注解、同时必须是for update语句。

添加@Transaction 注解好像是bug，已在Seata沟通群反馈。

SQL 语句必须添加for update ，我认为对于代码的侵入性太强，开发集成改动太大。

建议直接根据是否有@GlobalLock 注解来是否需要检查全局锁。

## How it could be?

在未添加for update 的方法上添加@GlobalLock 注解，实际效果不会触发全局锁检查。

## Other related information
无

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/78785403-afa65880-79d9-11ea-80cc-9814ca265985.png)
this is the master code

**Comment by liquanjin** [comment]
OK。

**Comment by Garlichead** [comment]
现在进度咋样了？

**Comment by hongdada** [comment]
嗯,还是不用改查询为快照读的好,代码侵入低
