### ISSUE TITLE
mybatis使用oracle数据源，update的字段含有F开头的字段时报错

### ISSUE THREAD

**Issue by zhuojiahe** [seata/seata#2501]
mybatis 的xml里面的sql为：
update USER set FAXNO = #{faxno,jdbcType=VARCHAR} where ID = #{id,jdbcType=VARCHAR}
使用oracle时报错，报错如下：
Cause: java.sql.SQLSyntaxErrorException: ORA-00904: "F": 标识符无效
备注：经测试，使用mysql不报错，只要字段以F开头，且后面含有类似#{faxno,jdbcType=VARCHAR}的配置时就报错，报错地方为targetStatement.getParameterMetaData()

**Comment by zhuojiahe** [comment]
private void initParameterHolder() throws SQLException {
        int paramCount = targetStatement.getParameterMetaData().getParameterCount();
        this.parameters = new ArrayList[paramCount];
        for (int i = 0; i < paramCount; i++) {
            parameters[i] = new ArrayList<>();
        }
    }

**Comment by Garlichead** [comment]
i think, is debug mysql under log

**Comment by zhuojiahe** [comment]
> i think, is debug mysql under log

**Comment by zhuojiahe** [comment]
> i think, is debug mysql under log
MySQL did not report an error. Oracle reported an error

**Comment by zhuojiahe** [comment]
经测试，使用ojdbc6 12.1.0.1或ojdbc 12.1.0.2会报错，切换成ojdbc6 11.2.0.4 不会报错

**Comment by Garlichead** [comment]
> 经测试，使用ojdbc6 12.1.0.1或ojdbc 12.1.0.2会报错，切换成ojdbc6 11.2.0.4 不会报错
好像 seat 对大众使用多的数据源版本稳定 我之前也遇到了mysql8有异常 切换成5则可以
