### ISSUE TITLE
get before image not correctly when column is on update current_timestamp

### ISSUE THREAD

**Issue by hecyxy** [seata/seata#2502]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
当有字段是DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP，update sql 回滚时，这个字段的时间会被更新为rollback的时间，导致这个值不一致；

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@hecyxy I will find out the cause of the problem.

**Comment by hecyxy** [comment]
> @hecyxy I will find out the cause of the problem.

thank you

**Comment by slievrly** [comment]
@hecyxy `git clone -b develop_update  https://github.com/slievrly/fescar.git`

**Comment by hecyxy** [comment]
> @hecyxy `git clone -b develop_update https://github.com/slievrly/fescar.git`
> please use this branch to make a local package to verify.

the problem has been solved,thanks

**Comment by Garlichead** [comment]
Is this the official branch?
