### ISSUE TITLE
docker 部署seata db模式错误

### ISSUE THREAD

**Issue by dcy421** [seata/seata#2503]
**file.conf配置文件**
`

store {
  mode = "db"

  file {
    dir = "sessionStore"
    maxBranchSessionSize = 16384
    maxGlobalSessionSize = 512
    fileWriteBufferCacheSize = 16384
    sessionReloadReadSize = 100
    flushDiskMode = async
  }

  db {
    datasource = "dbcp"
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://192.168.189.150:3306/seata"
    user = "root"
    password = "root"
    minConn = 1
    maxConn = 10
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
  }
}`

**file.conf.example配置文件**
`transport {
  type = "TCP"
  server = "NIO"
  heartbeat = true
  enableClientBatchSendRequest = false
  threadFactory {
    bossThreadPrefix = "NettyBoss"
    workerThreadPrefix = "NettyServerNIOWorker"
    serverExecutorThreadPrefix = "NettyServerBizHandler"
    shareBossWorker = false
    clientSelectorThreadPrefix = "NettyClientSelector"
    clientSelectorThreadSize = 1
    clientWorkerThreadPrefix = "NettyClientWorkerThread"
    bossThreadSize = 1
    workerThreadSize = "default"
  }
  shutdown {
    wait = 3
  }
  serialization = "seata"
  compressor = "none"
}
service {
  vgroupMapping.my_test_tx_group = "default"
  default.grouplist = "192.168.136.170:8091"
  enableDegrade = false
  disableGlobalTransaction = false
}
client {
  rm {
    asyncCommitBufferLimit = 10000
    lock {
      retryInterval = 10
      retryTimes = 30
      retryPolicyBranchRollbackOnConflict = true
    }
    reportRetryCount = 5
    tableMetaCheckEnable = false
    reportSuccessEnable = false
    sqlParserType = druid
  }
  tm {
    commitRetryCount = 5
    rollbackRetryCount = 5
  }
  undo {
    dataValidation = true
    logSerialization = "jackson"
    logTable = "undo_log"
  }
  log {
    exceptionRate = 100
  }
}

store {
  mode = "db"
  file {
    dir = "sessionStore"
    maxBranchSessionSize = 16384
    maxGlobalSessionSize = 512
    fileWriteBufferCacheSize = 16384
    sessionReloadReadSize = 100
    flushDiskMode = async
  }

  db {
    datasource = "dbcp"
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://192.168.189.150:3306/seata"
    user = "root"
    password = "root"
    minConn = 1
    maxConn = 10
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
  }
}

server {
  recovery {
    committingRetryPeriod = 1000
    asynCommittingRetryPeriod = 1000
    rollbackingRetryPeriod = 1000
    timeoutRetryPeriod = 1000
  }
  undo {
    logSaveDays = 7
    logDeletePeriod = 86400000
  }
  maxCommitRetryTimeout = "-1"
  maxRollbackRetryTimeout = "-1"
  rollbackRetryTimeoutUnlockEnable = false
}

metrics {
  enabled = false
  registryType = "compact"
  exporterList = "prometheus"
  exporterPrometheusPort = 9898
}`

**registry.conf配置文件**
`registry {
  type = "nacos"

  nacos {
    serverAddr = "192.168.136.170"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  type = "nacos"

  nacos {
    serverAddr = "192.168.136.170"
    namespace = ""
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}
`

**错误异样：**
`Starting seata-server ... done
Attaching to seata-server
seata-server    | 2020-04-03 00:23:15.258 INFO [main]io.seata.server.ParameterParser.init:90 -The server is running in container.
seata-server    | 2020-04-03 00:23:15.268 INFO [main]io.seata.config.FileConfiguration.<init>:101 -The file name of the operation is file:/root/seata-config/registry.conf
seata-server    | 2020-04-03 00:23:15.324 WARN [main]io.seata.config.ConfigurationFactory.<clinit>:68 -failed to load extConfiguration:not found service provider for : io.seata.config.ExtConfigurationProvider[null] and classloader : sun.misc.Launcher$AppClassLoader@4e0e2f2a
seata-server    | io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.config.ExtConfigurationProvider[null] and classloader : sun.misc.Launcher$AppClassLoader@4e0e2f2a
seata-server    | 2020-04-03 00:23:15.353 INFO [main]io.seata.common.loader.EnhancedServiceLoader.loadFile:247 -load ConfigurationProvider[Nacos] extension by class[io.seata.config.nacos.NacosConfigurationProvider]
seata-server    | 2020-04-03 00:23:15.926 INFO [main]io.seata.common.loader.EnhancedServiceLoader.loadFile:247 -load DataSourceGenerator[null] extension by class[io.seata.server.store.db.DruidDataSourceGenerator]
seata-server    | Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.store.TransactionStoreManager caused by io.seata.common.exception.StoreException: the {store.db.driverClassName} can't be empty
seata-server    |       at io.seata.core.store.db.AbstractDataSourceGenerator.getDriverClassName(AbstractDataSourceGenerator.java:59)
seata-server    |       at io.seata.server.store.db.DruidDataSourceGenerator.generateDataSource(DruidDataSourceGenerator.java:35)
seata-server    |       at io.seata.server.store.db.DatabaseTransactionStoreManager.init(DatabaseTransactionStoreManager.java:101)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:205)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:87)
seata-server    |       at io.seata.server.session.db.DataBaseSessionManager.init(DataBaseSessionManager.java:82)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:365)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:245)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.loadFile(EnhancedServiceLoader.java:205)
seata-server    |       at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:87)
seata-server    |       at io.seata.server.session.SessionHolder.init(SessionHolder.java:95)
seata-server    |       at io.seata.server.Server.main(Server.java:75)
seata-server    | 
seata-server exited with code 1`

**截图：**
![image](https://user-images.githubusercontent.com/20309960/78311979-eff27a80-7584-11ea-829f-551b819b3f88.png)

docker-compose.yml文件

`version: "3"
services:
  seata-server:
    image: seataio/seata-server:1.1.0
    hostname: seata-server
    container_name: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
      - STORE_MODE=db 
    volumes:
      - /home/seata/docker-compose/resources:/root/seata-config
      - /home/seata/docker-compose/resources/logs:/root/logs
`

**对应目录结构**

![image](https://user-images.githubusercontent.com/20309960/78312034-0a2c5880-7585-11ea-9605-d177cb1b466a.png)

**Comment by pansir1314** [comment]
请问这是如何解决的？我也遇到了一样的错误~

**Comment by dcy421** [comment]
把这  file.conf     file.conf.example   这两个文件删除掉  ，然后用sh 脚本或者 py  把参数初始化到nacos当中  再次运行就可以了

**Comment by pansir1314** [comment]
> 把这 file.conf file.conf.example 这两个文件删除掉 ，然后用sh 脚本或者 py 把参数初始化到nacos当中 再次运行就可以了

谢谢了，发现问题了，是因为register.conf中配置nacos的时候，namespace写了public~~

**Comment by Melodykuang** [comment]
@dcy421 @pansir1314  两位大哥，我这边也报错，不知道问题出在哪里了，可以发一个完整的吗，937146062@qq.com,谢谢啦
