### ISSUE TITLE
发现一个demo文档中的有一个信息的引导

### ISSUE THREAD

**Issue by Garlichead** [seata/seata#2504]
![image](https://user-images.githubusercontent.com/45086633/78314129-993c6f00-758b-11ea-82c8-4c7bc107aec5.png)
https://github.com/seata/seata-samples/tree/master/springcloud-eureka-feign-mybatis-seata
这里确实找不到seata server的简表语句 后来在同仁的指导下才找到的

**Comment by l81893521** [comment]
Can you change it and create a new pull request to us?

**Comment by Garlichead** [comment]
> Can you change it and create a new pull request to us?

ok
