### ISSUE TITLE
建议将seata在nacos中的配置放到一个DataId中

### ISSUE THREAD

**Issue by Rubbernecker** [seata/seata#2506]
在学习seata的过程中，我发现使用nacos分布式脚本时，是给每一条配置都创建了一个DataId，这样nacos中的配置可读性非常差，可否将配置放到一个DataId中，使用properties格式进行读取。

**Comment by slievrly** [comment]
@Rubbernecker can you submit a pr modification to this problem?

**Comment by Rubbernecker** [comment]
@slievrly 现在我还没有研究过seata server的源码，之后我可以抽空试着修改这方面功能

**Comment by Garlichead** [comment]
> @slievrly 现在我还没有研究过seata server的源码，之后我可以抽空试着修改这方面功能

support you
