### ISSUE TITLE
store.db.driverClassName  can't be empty

### ISSUE THREAD

**Issue by gitYhsh** [seata/seata#2512]
type:nacos
command   sh seata-server.sh -p 8039 -h 192.168.8.187 -m 'db'   
failed

**Comment by gitYhsh** [comment]
seata-server-1.1.0

**Comment by slievrly** [comment]
@gitYhsh How is store.db.driverClassName configured?

**Comment by Garlichead** [comment]
mysql config driverClassName is com.mysql.jdbc.Driver, you connect what database?

**Comment by a364176773** [comment]
please check the config type in your registry.conf file

**Comment by crashiers** [comment]
nacos配置store.db.driverClassName=mysql ，解决此问题
