### ISSUE TITLE
seate支持mongodb吗

### ISSUE THREAD

**Issue by itlidaye** [seata/seata#2513]
seate支持mongodb吗

**Comment by a364176773** [comment]
refers to mongodb transaction or session storage?

**Comment by itlidaye** [comment]
mongodb 的事务

**Comment by slievrly** [comment]
@itlidaye You can use tcc branch transaction mode to transform business.

**Comment by Garlichead** [comment]
AT model depend relational database ACID feature. Although mongodb also supports transactions, there is a difference. I do n’t understand the bottom layer.
