### ISSUE TITLE
Adding context:component-scan in examples failed

### ISSUE THREAD

**Issue by wpf5788** [seata/seata#252]
jdk1.7  环境win10 eclipse工具
单独跑例子是没有问题的 但是如果添加新的扫描
  <context:component-scan base-package="com.*"> 
       
 	   <context:exclude-filter type="annotation" 
 expression="org.springframework.stereotype.Controller" />
    </context:component-scan>  
会报错，是有依赖问题？
Unexpected exception parsing XML document from class path resource [applicationContext-dubbo.xml]; nested exception is java.lang.IllegalStateException: Context namespace element 'component-scan' and its parser class [org.springframework.context.annotation.ComponentScanBeanDefinitionParser] are only available on JDK 1.5 and higher

**Comment by wpf5788** [comment]
已解决 升级spring包

**Comment by leizhiyuan** [comment]
> 已解决 升级spring和dubbo版本解决

ok, I will close the issue, if you have other questions, please reopen it or create a new one
