### ISSUE TITLE
jdbcTemplate batchUpdate can not get targetSql

### ISSUE THREAD

**Issue by zjinlei** [seata/seata#2537]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/20024955/79040448-19617500-7c1b-11ea-820b-f742d52ee374.png)

### Ⅱ. Describe what happened
use: jdbcTemplate.batchUpdate("update storage_tbl set count = count - 1 where commodity_code = 2001");
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by HankDevelop** [comment]
请说下该问题所在seata版本，在1.1.0版本下测试是正常的
 ![1587182854(1)](https://user-images.githubusercontent.com/6049943/79627727-48bd3800-816d-11ea-9252-dc5ef8d7aaba.jpg)

**Comment by zjinlei** [comment]
Occurs in Statement, not PreparedStatement.

**Comment by HankDevelop** [comment]
in Statement mode
![image](https://user-images.githubusercontent.com/6049943/79636884-ab362880-81ad-11ea-918d-74220d786c3f.png)
