### ISSUE TITLE
对于ON UPDATE CURRENT_TIMESTAMP自动更新的时间戳字段，不能做到有效回滚

### ISSUE THREAD

**Issue by ThomasYoung1989** [seata/seata#2541]
由于当前的回滚机制是基于提交的sql做分析生成image，可能误判实际更新的字段数量，对于自动更新的时间戳字段，sql中不会提交，导致回滚后数据不对；如果是串起来的业务，对一个记录更新两次，两次更新过后发生回滚，第二次更新回滚成功，第一次更新回滚失败，报Field not equals, name update_time, old value 2020-04-11 17:34:08.0, new value 2020-04-11 17:34:10.0

**Comment by Garlichead** [comment]
都有点不懂你描述的意思 第二次更新回滚能成功  为什么第一次就失败了 如果你的字段不是sql控制的是数据库自己的 那你第二次回滚也会失败

**Comment by zjinlei** [comment]
will release in 1.3.0
