### ISSUE TITLE
spirngCloud 集成zipkin和seata的时候导致了openFeign不能远程调用服务的问题

### ISSUE THREAD

**Issue by liugongliushang** [seata/seata#2552]
![image](https://user-images.githubusercontent.com/42638927/79227274-38b60780-7e92-11ea-894c-57dab3653069.png)

**Comment by liugongliushang** [comment]
环境是jdk1.8+springboot2.2.6+springcloud(Hoxton.SR3)+spring-cloud-alibaba-2.2.0.RELEASE

**Comment by liugongliushang** [comment]
Spring Cloud Sleuth默认通过TraceFeignClientAutoConfiguration提供feign的集成，可以设置spring.sleuth.feign.enabled为false来使其无效。

**Comment by NineSwordsMonster** [comment]
> Spring Cloud Sleuth默认通过TraceFeignClientAutoConfiguration提供feign的集成，可以设置spring.sleuth.feign.enabled为false来使其无效。

无效之后我怎么去追踪服务调用链？？

**Comment by liugongliushang** [comment]
![image](https://user-images.githubusercontent.com/42638927/84011814-3f03c400-a9a9-11ea-8cd6-1054f535105f.png)


> > Spring Cloud Sleuth默认通过TraceFeignClientAutoConfiguration提供feign的集成，可以设置spring.sleuth.feign.enabled为假来代替无效。
> 
> 无效之后我怎么去追踪服务调用链？？

![image](https://user-images.githubusercontent.com/42638927/84011870-4f1ba380-a9a9-11ea-9677-8abafe1c1d03.png)
![image](https://user-images.githubusercontent.com/42638927/84011909-5b076580-a9a9-11ea-8bdb-af5025e12bc6.png)
加上这两个配置调用链接就可以接上了

**Comment by liugongliushang** [comment]
第一点：在启动类中加如忽略
@SpringBootApplication(exclude = {SeataFeignClientAutoConfiguration.class})
第二点：加入全局拦截传递XID
@Component
@ConditionalOnClass({RequestInterceptor.class,GlobalTransactional.class})
public class SetSeataInterceptor implements RequestInterceptor {
    @Override
    public void apply(RequestTemplate template) {
        
        String currentXid = RootContext.getXID();
        if (!StringUtils.isEmpty(currentXid)) {
            template.header(RootContext.KEY_XID, currentXid);
        }
    }
}

**Comment by adolph58** [comment]
感谢 @liugongliushang 困扰我几天的问题解决了

**Comment by liuzhimin1996** [comment]
@liugongliushang 
我也遇到了同样的问题
@SpringBootApplication(exclude = {SeataFeignClientAutoConfiguration.class})
我只采用了这个配置 没有做加入全局拦截传递XID

    <spring.cloud-version>Hoxton.SR12</spring.cloud-version>
    <spring.cloud.alibaba-version>2.2.8.RELEASE</spring.cloud.alibaba-version>
    <spring-boot-dependencies.version>2.3.12.RELEASE</spring-boot-dependencies.version>

       <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
      <exclusions>
        <exclusion>
          <groupId>io.seata</groupId>
          <artifactId>seata-spring-boot-starter</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.seata</groupId>
      <artifactId>seata-spring-boot-starter</artifactId>
      <version>1.5.1</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency>

为什么我没有采用第二点的措施 但是服务调用追踪没有受到影响
