### ISSUE TITLE
V1.1的seata-server源码存在缺少类导致无法编译问题

### ISSUE THREAD

**Issue by ABinLin** [seata/seata#2557]
缺失的类路径
io.seata.serializer.protobuf.generated.*
V1.1的源
码相关路径下的目录结构
![image](https://user-images.githubusercontent.com/39290009/79297463-c9cbc380-7f10-11ea-9d7d-8804c6c67605.png)

**Comment by a364176773** [comment]
根目录 mvn clean install -DskipTests=true maven版本要3.6.0以上
