### ISSUE TITLE
期望@GlobalTransactional支持ElementType.TYPE

### ISSUE THREAD

**Issue by yougecn** [seata/seata#2562]
期望@GlobalTransactional支持ElementType.TYPE，将注解添加到class上就可以该class上所有方法加上分布式事务

**Comment by a364176773** [comment]
@zjinlei please give me

**Comment by LateAutumnWindow** [comment]
+++

**Comment by pangdonghao** [comment]
+吧

**Comment by ye900424** [comment]
建议➕。一般@GlobalTransactional会加在service/manager层，且事务发起者一般是业务较上游，一个方法➕@GlobalTransactional，基本上其他方法也要➕

**Comment by lkxsoul** [comment]
场景描述：目前从上线系统使用SEATA情况来看，不是所有流程都有解决分布式事务的需求，只占了五分之一左右，因此，我觉得这种情况在方法上下效率也会更高一些，当然，我是站在我目前结合的情况来做评论的，如果有的公司业务对于一站式分布式事务需求量比较大，我觉得加在类上会更适合的，省去了每个方法上加注解的麻烦，提高了开发效率
个人观点：类中方法用注解量少得，在方法加注解即可，类中方法用注解量多的，在类上加注解，并且若类中方法有不需要分布式事务参加的，提供个可插拔的方式进行排查即可

**Comment by yougecn** [comment]
> 场景描述：目前从上线系统使用SEATA情况来看，不是所有流程都有解决分布式事务的需求，只占了五分之一左右，因此，我觉得这种情况在方法上下效率也会更高一些，当然，我是站在我目前结合的情况来做评论的，如果有的公司业务对于一站式分布式事务需求量比较大，我觉得加在类上会更适合的，省去了每个方法上加注解的麻烦，提高了开发效率
> 个人观点：类中方法用注解量少得，在方法加注解即可，类中方法用注解量多的，在类上加注解，并且若类中方法有不需要分布式事务参加的，提供个可插拔的方式进行排查即可

不全部用的话，需要保证用分布式事务和不用分布式事务的业务表没有重叠，有重叠了会有问题吧，会导致有脏数据导致分布式事务回滚失败，我的理解没问题吧

**Comment by a364176773** [comment]
> > 场景描述：目前从上线系统使用SEATA情况来看，不是所有流程都有解决分布式事务的需求，只占了五分之一左右，因此，我觉得这种情况在方法上下效率也会更高一些，当然，我是站在我目前结合的情况来做评论的，如果有的公司业务对于一站式分布式事务需求量比较大，我觉得加在类上会更适合的，省去了每个方法上加注解的麻烦，提高了开发效率
> > 个人观点：类中方法用注解量少得，在方法加注解即可，类中方法用注解量多的，在类上加注解，并且若类中方法有不需要分布式事务参加的，提供个可插拔的方式进行排查即可
> 
> 不全部用的话，需要保证用分布式事务和不用分布式事务的业务表没有重叠，有重叠了会有问题吧，会导致有脏数据导致分布式事务回滚失败，我的理解没问题吧

为什么会想到重叠了会有脏数据了?完全是两个问题,不用分布式事务就不加.这个方案不是一刀切,你可以类上也有,方法上也有,也可以二者选其一.

**Comment by lkxsoul** [comment]
> > 场景描述：目前从上线系统使用SEATA情况来看，不是所有流程都有解决分布式事务的需求，只占了五分之一左右，因此，我觉得这种情况在方法上下效率也会更高一些，当然，我是站在我目前结合的情况来做评论的，如果有的公司业务对于一站式分布式事务需求量比较大，我觉得加在类上会更适合的，省去了每个方法上加注解的麻烦，提高了开发效率
> > 个人观点：类中方法用注解量少得，在方法加注解即可，类中方法用注解量多的，在类上加注解，并且若类中方法有不需要分布式事务参加的，提供个可插拔的方式进行排查即可
> 
> 不全部用的话，需要保证用分布式事务和不用分布式事务的业务表没有重叠，有重叠了会有问题吧，会导致有脏数据导致分布式事务回滚失败，我的理解没问题吧

注解只是走个代理进入全局事务管理的一种方式，你说的是数据问题，这两个并不冲突

**Comment by elkan** [comment]
加吧，本来定义的就是全局，如果不加，在类中每个方法上加，也不优雅吧

**Comment by elkan** [comment]
> > > 场景描述：目前从上线系统使用SEATA情况来看，不是所有流程都有解决分布式事务的需求，只占了五分之一左右，因此，我觉得这种情况在方法上下效率也会更高一些，当然，我是站在我目前结合的情况来做评论的，如果有的公司业务对于一站式分布式事务需求量比较大，我觉得加在类上会更适合的，省去了每个方法上加注解的麻烦，提高了开发效率
> > > 个人观点：类中方法用注解量少得，在方法加注解即可，类中方法用注解量多的，在类上加注解，并且若类中方法有不需要分布式事务参加的，提供个可插拔的方式进行排查即可
> > 
> > 
> > 不全部用的话，需要保证用分布式事务和不用分布式事务的业务表没有重叠，有重叠了会有问题吧，会导致有脏数据导致分布式事务回滚失败，我的理解没问题吧
> 
> 为什么会想到重叠了会有脏数据了?完全是两个问题,不用分布式事务就不加.这个方案不是一刀切,你可以类上也有,方法上也有,也可以二者选其一.

大概理解他的意思，例如针对同一个业务表，分为了2个dao进行操作，一个是开启了全局事务的，一个是未开启全局事务的；但是这个问题，本质上，应该是程序设计上的问题；既然如果有部分操作不需要开启全局事务，那么即使开启了，seata本身应该也是能检测到这是个单机事务的吧？

**Comment by a364176773** [comment]
> > > > 场景描述：目前从上线系统使用SEATA情况来看，不是所有流程都有解决分布式事务的需求，只占了五分之一左右，因此，我觉得这种情况在方法上下效率也会更高一些，当然，我是站在我目前结合的情况来做评论的，如果有的公司业务对于一站式分布式事务需求量比较大，我觉得加在类上会更适合的，省去了每个方法上加注解的麻烦，提高了开发效率
> > > > 个人观点：类中方法用注解量少得，在方法加注解即可，类中方法用注解量多的，在类上加注解，并且若类中方法有不需要分布式事务参加的，提供个可插拔的方式进行排查即可
> > > 
> > > 
> > > 不全部用的话，需要保证用分布式事务和不用分布式事务的业务表没有重叠，有重叠了会有问题吧，会导致有脏数据导致分布式事务回滚失败，我的理解没问题吧
> > 
> > 
> > 为什么会想到重叠了会有脏数据了?完全是两个问题,不用分布式事务就不加.这个方案不是一刀切,你可以类上也有,方法上也有,也可以二者选其一.
> 
> 大概理解他的意思，例如针对同一个业务表，分为了2个dao进行操作，一个是开启了全局事务的，一个是未开启全局事务的；但是这个问题，本质上，应该是程序设计上的问题；既然如果有部分操作不需要开启全局事务，那么即使开启了，seata本身应该也是能检测到这是个单机事务的吧？

不用分布式事务的服务不要引入seata,他这个问题跟标题所含的功能完全无关,跟加不加类上注解没关心.单机事务要么不引入seata,要不抛弃xid绑定
