### ISSUE TITLE
期望seata支持类似spring事务管理、txlcn那种切面模式配置分布式事务及事务传播

### ISSUE THREAD

**Issue by yougecn** [seata/seata#2563]
期望seata支持类似spring事务管理、txlcn那种切面模式配置分布式事务及事务传播
1、类似txlcn切面模式配置事务嵌套、传播
2、类似spring TransactionManager那样，支持类似AspectJExpressionPointcut表达式模式指定哪些类启用分布式事务，类似DefaultTransactionAttribute指定分布式事务传播模式，类似NameMatchTransactionAttributeSource的addTransactionalMethod指定，哪些满足不通方法的事务级别
类似

**Comment by a364176773** [comment]
@slievrly @zjinlei let me finish it

**Comment by slievrly** [comment]
https://github.com/seata/seata/pull/2359#issue-384101398
