### ISSUE TITLE
seata-spring-boot-starter版本,undo_log没有新增数据

### ISSUE THREAD

**Issue by licaibo** [seata/seata#2577]
### Ⅰ. 问题描述
使用seata-spring-boot-starter,properties配置，日志显示开启事务，但是到另一个服务打断点，发现undo_log没有新增数据，最后seata-serve日志回滚显示成功了，业务数据实际没有回滚，
想问一下有哪一方面可能造成undo_log没有新增的原因

### Ⅱ. 显示日志
后台新增数据后，没有发现新增undo_log
![image](https://user-images.githubusercontent.com/8706814/79712663-0f680200-82fe-11ea-98de-d65e77325136.png)

但是seata serve日志显示了回滚成功
![image](https://user-images.githubusercontent.com/8706814/79712698-2dcdfd80-82fe-11ea-9e61-4f0dbda26842.png)

感觉像是没有触发新增undo_log，配置文件改成undo_log2不一样也没有报错，也没有新增日志

###properties配置
#seata
seata.enabled=true
seata.application-id=seataname
seata.tx-service-group=my_test_tx_group
seata.registry.type=eureka
seata.registry.eureka.service-url=http://localhost:8162/eureka
seata.registry.eureka.application=default
seata.registry.eureka.weight=1
seata.service.disable-global-transaction=false
seata.service.vgroup-mapping.my_test_tx_group=default
#seata.service.grouplist.default=127.0.0.1:8099
seata.client.undo.log-table=undo_log
seata.client.undo.log-serialization=jackson
seata.client.undo.data-validation=true
seata.client.log.exception-rate=100
seata.client.rm.report-success-enable=true
seata.client.rm.table-meta-check-enable=false
seata.client.rm.report-retry-count=5
seata.client.rm.async-commit-buffer-limit=10000
seata.client.rm.lock.retry-interval=10
seata.client.rm.lock.retry-times=30
seata.client.rm.lock.retry-policy-branch-rollback-on-conflict=true
seata.enable-auto-data-source-proxy=true

### 想请教，有可能哪一个方面原因造成undo_log没有新增数据,也没有可能是多数据源造成的？

###环境配置
- JDK version :1.8
- seata-spring-boot-starter 1.1.0
- springboot2、eureka、fegin
- eureka
- fegin
- dynamic多数据源配置，项目启动的时候动态加载多数据源

**Comment by xingfudeshi** [comment]
Your business may not be included in the global transaction management of Seata. Please refer to the example to check whether your configuration is correct.
Version 1.2.0 will be released soon. I suggest you try again after it is released.

**Comment by licaibo** [comment]
已经解决，使用dynamic-datasource-spring-boot-starter动态多数据源的，升级至3.0.0支持seata，
具体参考 :
https://www.oschina.net/news/113000/dynamic-datasource-3-0-0-released

集成demo ：
https://github.com/baomidou/dynamic-datasource-spring-boot-starter/wiki/Integration-With-Seata

**Comment by xingfudeshi** [comment]
Good!

**Comment by DropOfJupiter** [comment]
我项目A调用项目B，B可以回滚，A无法回滚，但A那边的日志也是说回滚成功了。
项目A中也是使用多数据源，但已经指定某个数据源被seata代理，情况跟你一样，A的undo_log没有数据
