### ISSUE TITLE
修改源码打包错误

### ISSUE THREAD

**Issue by clfbai** [seata/seata#2578]
日志
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project seata-config-zk: Failed during checkstyle execution: There is 1 error reported by Checkstyle 6.18 with /Users/zy/Desktop/work/seata1.1_code/seata/style/seata_checkstyle.xml ruleset. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :seata-config-zk
------------------------------------------------------------
~/Desktop/work/seata1.1_code/seata(1.1.0*) »       

### Ⅵ. Environment:

- JDK version :1.8
- OS :
- Others:
![image](https://user-images.githubusercontent.com/46588474/79716754-43492480-830a-11ea-92c5-21da4c0d5c58.png)

**Comment by xingfudeshi** [comment]
Please Use `mvn clean install -DskipTests -U`
