### ISSUE TITLE
seata.enable-auto-data-source-proxy=false无效

### ISSUE THREAD

**Issue by edwardpan** [seata/seata#2583]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用`io.seata:seata-spring-boot-starter:1.1.0`
参照文档[Seata新手部署指南](https://seata.io/zh-cn/docs/ops/deploy-guide-beginner.html)设置`seata.enable-auto-data-source-proxy=false`后不生效，仍然自动代理数据源
查看`SeataAutoConfiguration`源码后发现`SeataDataSourceBeanPostProcessor`的配置判断条件为
```
    @ConditionalOnProperty(
        prefix = "seata",
        name = {"enableAutoDataSourceProxy"},
        havingValue = "true",
        matchIfMissing = true
    )
```
且经过断点调试发现`SeataDataSourceBeanPostProcessor`仍然被创建
在`application.properties`中将配置名修改为`seata.enableAutoDataSourceProxy=false`后`SeataDataSourceBeanPostProcessor`不再创建，自动代理失效

### Ⅲ. Describe what you expected to happen
`seata.enable-auto-data-source-proxy=false` 生效，而不是`seata.enableAutoDataSourceProxy=false`

### Ⅵ. Environment:

- JDK version : 11
- OS : MacOS
- Others:

**Comment by wangliang1986** [comment]
1.2.0版本已经发布了，这个问题已经得到解决了。
