### ISSUE TITLE
nacos1.2 开启登录, docker部署seata-server:latest 使用nacos作为注册中心, 启动失败

### ISSUE THREAD

**Issue by peter-lwg** [seata/seata#2586]
1. 前置环境
   1) nacos1.2, 宿主机部署, 使用登录  (nacos.core.auth.enabled=true)
   2) docker 部署 seataio/seata-server:latest
2. 使用外部配置文见
  1) 启动命令
     docker run --name seata-server -d --restart always  -e SEATA_CONFIG_NAME=file:/root/seata-config/registry -p 8091:8091 -v $PWD/config:/root/seata-config  seataio/seata-server
  2) 配置文件
    file.conf 使用db  配置数据库
   registry.conf 配置nacos作为注册中心, 配置中心(相关配置已导入  config.txt)
    registry {
      type = "nacos"

      nacos {
        application = "seata-server"
        serverAddr = "127.0.0.1"
        namespace = "server"
        cluster = "default"
        username = "nacos"
       password = "nacos"
    }
  }

config {
  type = "nacos"

  nacos {
    serverAddr = "127.0.0.1"
    namespace = "server"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
}

启动错误信息:
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([127.0.0.1]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Apr 20 15:52:57 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

**Comment by zjinlei** [comment]
https://github.com/seata/seata/pull/2367

**Comment by peter-lwg** [comment]
nacos 设置的该空间名称即为 "server" 使用ieda 本地连接可以正常注册,获取配置文件.

**Comment by a364176773** [comment]
> nacos 设置的该空间名称即为 "server" 使用idea本地连接可以正常注册,获取配置文件.

namespace 对应的是id,不是名称,比如我有个dev对应的id是:18792dfd-28e0-4757-b03f-7e394f490d6e
要用后面这个

**Comment by peter-lwg** [comment]
![66](https://user-images.githubusercontent.com/37094524/79983985-1ef07200-84db-11ea-81c9-01c3f9d09bc3.png)

新建空间的时候填写的server

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/79986773-2ade3300-84df-11ea-863d-b803da3b929e.png)
![image](https://user-images.githubusercontent.com/19943636/79986802-33366e00-84df-11ea-9a97-3ea3abd73e21.png)
1.2测试结果没问题,晚点我测试下1.2.1的nacos

**Comment by a364176773** [comment]
> 好的 麻烦了.

是bug,清交给我来处理 @zjinlei

**Comment by a364176773** [comment]
> 好的 麻烦了.

是bug,清交给我来处理 @zjinlei

**Comment by a364176773** [comment]
最新解决方案 serverAddr使用ip:端口,而不要仅仅ip就可以了.

**Comment by slievrly** [comment]
click on the nacos console namespace to view namespace id.

**Comment by peter-lwg** [comment]
![99](https://user-images.githubusercontent.com/37094524/80100426-8ae9dd80-85a2-11ea-9235-f2b9420145af.png)

配置ip:端口  启动成功. 未存在上述问题. 
启动后出现新的问题, 关于上图问题 我是需要再配置netty的吗? 
还有一点疑问 当前容器所在宿主机为192.168.10.161, 错误信息中的 192.168.10.158 并未在file.conf 与 registry.conf 中存在.

**Comment by a364176773** [comment]
> ![99](https://user-images.githubusercontent.com/37094524/80100426-8ae9dd80-85a2-11ea-9235-f2b9420145af.png)
> 
> 配置ip:端口 启动成功. 未存在上述问题.
> 启动后出现新的问题, 关于上图问题 我是需要再配置netty的吗?
> 还有一点疑问 当前容器所在宿主机为192.168.10.161, 错误信息中的 192.168.10.158 并未在file.conf 与 registry.conf 中存在.

图中问题请忽略,这种一般由于你有健康检查或者自己访问到8091这个端口导致的.不影响功能

**Comment by peter-lwg** [comment]
好的  谢谢
