### ISSUE TITLE
联合主键不支持

### ISSUE THREAD

**Issue by a46461440** [seata/seata#2589]
## Why you need it?
代理数据源做数据库操作的时候，如果那张表包含了联合主键会报错
tableXXX contains multi PK, but current not support.

## How it could be?
希望即使是联合主键也能正常运行

**Comment by slievrly** [comment]
@a46461440 https://github.com/seata/seata/pull/2398#issue-387662866

**Comment by Garlichead** [comment]
is solve.

**Comment by jsbxyyx** [comment]
1.3 support mysql multi primary key.
