### ISSUE TITLE
1.1.0升级1.2.0 配置文件改动导致zk连接问题

### ISSUE THREAD

**Issue by pglc1026** [seata/seata#2590]
客户端使用registry.conf方式，registry.conf中**配置中心**zk的sessionTimeout和connectTimeout的命名格式由1.1.0的 `session.timeout` 和 `connect.timeout `到1.2.0变更为 `sessionTimeout` 和 `connectTimeout` 导致seata客户端在启动时获取不到正确的值，使用了0作为**默认值**，连接zk失败。

**Comment by a364176773** [comment]
please assign it to me @zjinlei @slievrly @xingfudeshi

**Comment by xingfudeshi** [comment]
> please assign it to me @zjinlei @slievrly @xingfudeshi

OK.
