### ISSUE TITLE
ControllerAdvice

### ISSUE THREAD

**Issue by wuyongc** [seata/seata#2596]
先按照springcloud-eureka-feign-mybatis-seata demo将工程运行起来。
在account服务中模拟抛出超时异常或者除0异常
order,account,storage中的数据都会回滚。

但是在account服务中添加如下代码
`@ControllerAdvice
public class BaseExceptionHandler {

@ExceptionHandler(value = Exception.class)
@ResponseBody
public Result error(Exception e) {
    e.printStackTrace();
    return new Result(20001, e.getMessage());
}
}
在account抛出除0异常后， order,storage中的数据不会回滚，order,storage均提示Branch commit result: PhaseTwo_Committed`
这个是什么原因，求解释，很急

**Comment by jsbxyyx** [comment]
repeated #2594
