### ISSUE TITLE
custom ports are not supported for consul

### ISSUE THREAD

**Issue by a364176773** [seata/seata#2599]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
custom ports are not supported for consul
![image](https://user-images.githubusercontent.com/19943636/80077363-fa020a80-857f-11ea-8f75-68e699952f18.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by helloworlde** [comment]
I found this issue also, but it could be work correctlly. It will call `org.apache.http.client.utils.URIUtils#extractHost` method before execute request, and then will trim the default port:

```java
if (host != null) {
    final int colon = host.indexOf(':');
    if (colon >= 0) {
        final int pos = colon + 1;
        int len = 0;
        for (int i = pos; i < host.length(); i++) {
            if (Character.isDigit(host.charAt(i))) {
                len++;
            } else {
                break;
            }
        }
        if (len > 0) {
            try {
                port = Integer.parseInt(host.substring(pos, pos + len));
            } catch (final NumberFormatException ex) {
            }
        }
        host = host.substring(0, colon);
    }
}
```
