### ISSUE TITLE
使用多数据库时，事务未回滚。

### ISSUE THREAD

**Issue by MrPassionFruit** [seata/seata#2602]
A服务使用oracle1数据库，B服务使用oracle2数据库。使用的是同类型数据库，但是是不同的库，此时如果A服务调用B服务，A准备提交全局事务的时候，B服务宕机了，此时B服务数据并没有回滚？请问是不支持多库操作吗？

**Comment by a364176773** [comment]
b服务重启后,或者B服务是集群,会执行回滚.如果是以下原因是不会回滚的:
![image](https://user-images.githubusercontent.com/19943636/80101854-8faf9100-85a4-11ea-93d4-69fc43d08ab0.png)

**Comment by a364176773** [comment]
A如果此时已经提交事务,那么B即使宕机也没事.
如果B是在一阶段完毕后,突然就宕机,此时会timeout异常,全局事务会回滚,当然要B上线才行,或者B有其它的节点.

**Comment by MrPassionFruit** [comment]
好的，谢谢！

**Comment by luoyonghui55** [comment]
> b服务重启后,或者B服务是集群,会执行回滚.如果是以下原因是不会回滚的:
> ![image](https://user-images.githubusercontent.com/19943636/80101854-8faf9100-85a4-11ea-93d4-69fc43d08ab0.png)

我有2个问题想请教下：
1、我试了下，B服务重启后仍然没有回滚。
数据库代理类如下：

package com.taiji.auth.config;

import com.alibaba.druid.pool.DruidDataSource;
import io.seata.rm.datasource.DataSourceProxy;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.transaction.jdbc.JdbcTransactionFactory;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.jdbc.DataSourceProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

@Configuration
public class SeataAutoConfig {

    /**
     * autowired datasource config
     */
    @Autowired
    private DataSourceProperties dataSourceProperties;

    /**
     * init durid datasource
     * @Return: druidDataSource  datasource instance
     */
    @Bean
    @Primary
    public DruidDataSource druidDataSource(){
        DruidDataSource druidDataSource = new DruidDataSource();
        druidDataSource.setUrl(dataSourceProperties.getUrl());
        druidDataSource.setUsername(dataSourceProperties.getUsername());
        druidDataSource.setPassword(dataSourceProperties.getPassword());
        druidDataSource.setDriverClassName(dataSourceProperties.getDriverClassName());
        druidDataSource.setInitialSize(0);
        druidDataSource.setMaxActive(180);
        druidDataSource.setMaxWait(60000);
        druidDataSource.setMinIdle(0);
        druidDataSource.setValidationQuery("Select 1 from DUAL");
        druidDataSource.setTestOnBorrow(false);
        druidDataSource.setTestOnReturn(false);
        druidDataSource.setTestWhileIdle(true);
        druidDataSource.setTimeBetweenEvictionRunsMillis(60000);
        druidDataSource.setMinEvictableIdleTimeMillis(25200000);
        druidDataSource.setRemoveAbandoned(true);
        druidDataSource.setRemoveAbandonedTimeout(1800);
        druidDataSource.setLogAbandoned(true);
        return druidDataSource;
    }

    @Bean
    public DataSourceProxy dataSourceProxy(){
        return new DataSourceProxy(druidDataSource());
    }
    
    @Bean
    public SqlSessionFactory sqlSessionFactory() throws Exception {
        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(dataSourceProxy());
        factoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath*:mybatis/**/*Mapper.xml"));
        factoryBean.setTransactionFactory(new JdbcTransactionFactory());
        return factoryBean.getObject();
    }
}

2、B服务是要用F5集群还是NGINX集群才能回滚？
