### ISSUE TITLE
saga流程定义的问题

### ISSUE THREAD

**Issue by liu-chao-simon** [seata/seata#2614]
请问一下，关于saga在下述场景的一点疑问：
假设一个事务涉及调用A, B, C三个服务，调用过程大致如下
{
            callService_A(...);
            ... // 一些中间步骤代码
            callService_B(...);
            ... // 一些中间步骤代码
            callService_C(...);
            
 }
请问这些穿插在A, B, C之间的流程代码应该写在哪？

**Comment by wangliang1986** [comment]
也写到各自的service里

**Comment by long187** [comment]
你也可以写在本地的的bean里，然后在callService_A()和callService_B()之间调这个bean的方法，也是通过ServiceTask来调
