### ISSUE TITLE
数据源为pg，某些情况下，PostgresqlTableMetaCache.getCacheKey()没有区分Schema

### ISSUE THREAD

**Issue by lbysimun** [seata/seata#2623]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

- 问题：当数据源为pg，发现有时候会读到另一个Schema的相同表名的DatabaseMetaData。

- 使用场景：pg的schema是在dburl里指定的，entity上没有指定schema。服务1连接的url: jdbc:postgresql://ip:port/postgres?currentSchema=postgres1 、服务2连接的url: jdbc:postgresql://ip:port/postgres?currentSchema=postgres2

- 原因：是PostgresqlTableMetaCache.getCacheKey()时，某些情况下区分Schema有bug。

- eg: 这两个服务操作的表名都为 tableA（这个表tableA在Schema为postgres1和postgres2都存在,且表结构不同）时。但是这两个服务最后生成的cacheKey为同一个：jdbc:postgresql://ip:port/postgres.tableA。这样就会导致一个服务会读到另一个服务的DatabaseMetaData，解析字段的时候就报错。

**Comment by l81893521** [comment]
Thanks for you report
