### ISSUE TITLE
DataBaseSessionManager  FileSessionManager 实现中 lockAndExecute 问题

### ISSUE THREAD

**Issue by suichen** [seata/seata#2653]
为什么 DataBaseSessionManager 中 lockAndExecute 没有 globalSession.lock()?
而 FileSessionManager 中的 lockAndExecute 中有 globalSession.lock()

**Comment by zjinlei** [comment]
FileSessionManager 是单机版共用一个实例，可以锁住。
DataBaseSessionManager 全局事务会话实例每次都是新生成的，实例锁无用，暂时想不到更好的办法。
