### ISSUE TITLE
seata 集群下找不到 xid

### ISSUE THREAD

**Issue by sulongfei001** [seata/seata#2654]
使用 spring cloud 集群 +  seata 集群 ，使用 @GlobalTransactional 注解，seata 版本1.2.0 ，报错如下
Error updating database.  Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 182.254.185.180:8091:2010657011, may be has finished.] ]

**Comment by a364176773** [comment]
Could not found global transaction xid

一般出现这个提示与服务重试及超时有关,比如A->B此时A调B超时,A默认是重试的,B等于被调了2遍,第二次被调用的B进行了响应,A发起者接收到结果后进行了提交/回滚,这次超时的B因为网络问题现在才被调用,他也收到了一样的全局事务id,进行业务处理,直到注册分支,此时全局事务已经被提交/回滚,导致当前超时的分支事务B无法注册上.

这种问题一般保证你的业务不会去超时重试,如果你需要,请确认全局事务状态,做好幂等,防止已经做过的处理重复操作.

**Comment by Garlichead** [comment]
> Could not found global transaction xid
> 
> 一般出现这个提示与服务重试及超时有关,比如A->B此时A调B超时,A默认是重试的,B等于被调了2遍,第二次被调用的B进行了响应,A发起者接收到结果后进行了提交/回滚,这次超时的B因为网络问题现在才被调用,他也收到了一样的全局事务id,进行业务处理,直到注册分支,此时全局事务已经被提交/回滚,导致当前超时的分支事务B无法注册上.
> 
> 这种问题一般保证你的业务不会去超时重试,如果你需要,请确认全局事务状态,做好幂等,防止已经做过的处理重复操作.

不太理解您的意思 假设 A 和 B 在同一个全局事务状态下 A -》 B 此时 B 如果超时 A 则会进行全局回滚了 因为B 没有返回正确的状态给A

**Comment by a364176773** [comment]
> > Could not found global transaction xid
> > 一般出现这个提示与服务重试及超时有关,比如A->B此时A调B超时,A默认是重试的,B等于被调了2遍,第二次被调用的B进行了响应,A发起者接收到结果后进行了提交/回滚,这次超时的B因为网络问题现在才被调用,他也收到了一样的全局事务id,进行业务处理,直到注册分支,此时全局事务已经被提交/回滚,导致当前超时的分支事务B无法注册上.
> > 这种问题一般保证你的业务不会去超时重试,如果你需要,请确认全局事务状态,做好幂等,防止已经做过的处理重复操作.
> 
> 不太理解您的意思 假设 A 和 B 在同一个全局事务状态下 A -》 B 此时 B 如果超时 A 则会进行全局回滚了 因为B 没有返回正确的状态给A

A默认是重试的

**Comment by sulongfei001** [comment]
这个问题在单机seata上是不存在的，只有在seata集群下才出现的错误。另外B服务在被调用期间出现 xid in change during RPC from 182.254.185.72:8091:2010936576 to null  这个警告，然后A服务就会提示找不到xid

**Comment by sulongfei001** [comment]
A 服务
![3NY)DH~R63WEPE%Q @KYXUQ](https://user-images.githubusercontent.com/30561664/81189166-df507c80-8fe8-11ea-8439-265e2970b1db.png)
B 服务
![)3M9$LMXDGWN{AW9GUH}C7H](https://user-images.githubusercontent.com/30561664/81189234-f1cab600-8fe8-11ea-8821-40a83c51b607.png)
seata 日志
![@_WUQHUR)@7UZX~2}(8JESW](https://user-images.githubusercontent.com/30561664/81189266-fabb8780-8fe8-11ea-8225-977adf878a7e.png)

**Comment by a364176773** [comment]
请确保你的回话存储时db而不是file,使用的db配置要多个tc同一个,才能保证数据共享

**Comment by Garlichead** [comment]
> Could not found global transaction xid
> 
> 一般出现这个提示与服务重试及超时有关,比如A->B此时A调B超时,A默认是重试的,B等于被调了2遍,第二次被调用的B进行了响应,A发起者接收到结果后进行了提交/回滚,这次超时的B因为网络问题现在才被调用,他也收到了一样的全局事务id,进行业务处理,直到注册分支,此时全局事务已经被提交/回滚,导致当前超时的分支事务B无法注册上.
> 
> 这种问题一般保证你的业务不会去超时重试,如果你需要,请确认全局事务状态,做好幂等,防止已经做过的处理重复操作.

您好 我复盘了一下我的思路 突然对seata在服务调用链路有点不懂了 A -》 B 超时 A 重试 如果一直调用失败 回滚 如果调用成功 此时A为什么会进行全局事务的提交或者回滚了 我的理解是A调用B 没有出现问题 等B本地事务执行完成之后才会进行全局事务的提交 现在我不理解的地方在于 为何A调用B B超时 A重试 A调用成功 此时为什么会进行全局事务状态的提交

**Comment by winywork** [comment]
我也出现了同样的问题，请问这个后来怎么解决的？ B服务日志如下，
2020-05-19 15:15:13.446  INFO 21408 --- [nio-8082-exec-3] c.i.s.l.p.s.impl.ProductServiceImpl      : [reduceStock] 扣除 1 库存成功
2020-05-19 15:15:13.462  WARN 21408 --- [nio-8082-exec-3] c.a.c.seata.web.SeataHandlerInterceptor  : xid in change during RPC from 192.168.28.134:18091:2043490192 to null
2020-05-19 15:15:13.466 ERROR 21408 --- [nio-8082-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.28.134:18091:2043490192] ]] with root cause

io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.28.134:18091:2043490192] ]

**Comment by Garlichead** [comment]
@winywork 说需要是同一个db 有按照要求处理吗

**Comment by winywork** [comment]
> @winywork 说需要是同一个db 有按照要求处理吗

目前是按照微服务的模式，一个服务单独一个db，要统一用一个db才行吗？不应该吧

**Comment by Garlichead** [comment]
@winywork  一个服务服务一个db tc是在一个集群db中或者一个db中 很多服务的db和集群tc进行协作

**Comment by jackbauer123** [comment]
> Could not found global transaction xid
> 
> 一般出现这个提示与服务重试及超时有关,比如A->B此时A调B超时,A默认是重试的,B等于被调了2遍,第二次被调用的B进行了响应,A发起者接收到结果后进行了提交/回滚,这次超时的B因为网络问题现在才被调用,他也收到了一样的全局事务id,进行业务处理,直到注册分支,此时全局事务已经被提交/回滚,导致当前超时的分支事务B无法注册上.
> 
> 这种问题一般保证你的业务不会去超时重试,如果你需要,请确认全局事务状态,做好幂等,防止已经做过的处理重复操作.

这里有点乱，首先我说下我的理解，如果A是全局主事务，调用A(TM)的时候，A会到TC去注册一个xid，此时A调用B(RM)，B会到TC注册一个xid下的branchId子事务，当A调用B超时时，A再次调用B应该用的是一个xid跟branchId，重试应该不会再到TC注册新的branchId吧？

**Comment by MrYangcg** [comment]
@sulongfei001 你好，我1.3版本也遇到这个问题了，多个server使用db模式通过同一个库共享事务信息，使用zk作为注册中心，file作为配置，单机ok，多节点就报这个错，事务表里无任何记录，请问你现在解决了吗或者定位到原因么？

**Comment by DaiZero** [comment]
@sulongfei001 我遇到的问题和你一样，请问你现在解决了吗？

**Comment by Flyfoxs** [comment]
我也遇到了同样的问题, 但是只有第一次这样, 第二次就好了.

**Comment by Flyfoxs** [comment]
通过下面的例子, 可以很容易的复现这个bug:

https://github.com/Flyfoxs/seata_example_docker_compose
* ./install.sh
*  http://127.0.0.1:18081/seata/feign (运行install.sh之后, 只有第一次打开才会有这个错, 后面就正常)
*  docker logs -f order-service

**Comment by Flyfoxs** [comment]
> 通过下面的例子, 可以很容易的复现这个bug:
> 
> https://github.com/Flyfoxs/seata_example_docker_compose
> 
> * ./install.sh
> * http://127.0.0.1:18081/seata/feign (运行install.sh之后, 只有第一次打开才会有这个错, 后面就正常)
> * docker logs -f order-service

fix 了bug, 原来是feign第一次调用的时候, timeout了
https://github.com/Flyfoxs/seata_example_docker_compose/commit/5d3ec58cabf92afadc62fc71d623a5b599f85503

**Comment by jingxiaohu** [comment]
这个错很容易复现，用jmeter 上并发  服务都是按微服务的方式独享各自的DB  TC用的file store

**Comment by Timi8080** [comment]
@sulongfei001 你好, 我理解你的苦楚了, 因为我正切身体会。那么现在你的问题解决了吗, 能否告知 !

**Comment by a364176773** [comment]
> @sulongfei001 你好, 我理解你的苦楚了, 因为我正切身体会。那么现在你的问题解决了吗, 能否告知 !

检查分支事务为什么异步了,这个跟你自己的组件有关,跟seata没有关系,只不过seata为了幂等保证,不会让一个全局事务不存在,或者已经二阶段决议的分支进行注册.
且tc的file模式是不支持集群部署的.

**Comment by sunyunsheng** [comment]
所以我也遇到这个问题了，3个seata-server，同一个seata数据库， nacos为注册和配置中心，    当只启动一个seata-server时一切正常，3个seata-server全部启动后， 每次都发生这个Could not found global transaction xid异常

**Comment by yangnima** [comment]
有解决方案吗？各位大佬

**Comment by syshlang** [comment]
> 所以我也遇到这个问题了，3个seata-server，同一个seata数据库， nacos为注册和配置中心， 当只启动一个seata-server时一切正常，3个seata-server全部启动后， 每次都发生这个Could not found global transaction xid异常

@sunyunsheng 大佬，我出现了跟你一样的问题，你的问题解决了吗

**Comment by hongshenghome** [comment]
1.6.1 也出现这个问题，单实例没问题，多实例报错[Could not found global transaction xid = 172.20.0.65:8091:9160863761421373443, may be has finished，数据库seata都是同一个
