### ISSUE TITLE
mybatis插入数据时返回的自增ID是undo_log的自增ID

### ISSUE THREAD

**Issue by f4cklangzi** [seata/seata#2655]
`==>  Preparing: insert into admin ( merchant_id, merchant_key, username, password, nick_name, note, create_time, status, role_id ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ? ) 
==> Parameters: 62(Integer), 88858818s11897(String), test(String), $2a$10$refG3rWsR3BS.b47SEA8NudBUjLApLueYz0LZ60DivpDKTOuxjYJq(String), 获取的商户名(String), 自动创建(String), 2020-05-05 09:14:37.143(Timestamp), 1(Integer), 1256(Integer)
<==    Updates: 1
==>  Preparing: SELECT LAST_INSERT_ID() 
==> Parameters: 
<==    Columns: LAST_INSERT_ID()
<==        Row: 1314
<==      Total: 1`
这里的1314不是admin表的自增ID，而是undo_log的自增ID，导致设置到实体类里面的ID错误

**Comment by zjinlei** [comment]
http://seata.io/zh-cn/docs/overview/faq.html#10
Don't use LAST_INSERT_ID

**Comment by f4cklangzi** [comment]
mybatis自动生成的代码都是用LAST_INSERT_ID获取的，那就得改所有的xml文件，这是不合理的。

**Comment by zjinlei** [comment]
去掉undo_log表的id字段
