### ISSUE TITLE
feign调用，LoadBalancerFeignClient.execute执行两次

### ISSUE THREAD

**Issue by yuanyong1014** [seata/seata#2657]
seata1.2，feign调用其他服务
第一次执行LoadBalancerFeignClient.execute成功找到可用服务
第二次执行会在第一次返回的url的head里加入tx_xid
![image](https://user-images.githubusercontent.com/50570652/81139401-31b57d00-8f98-11ea-9496-dfd4c4515d39.png)
后面继续执行会报错，因为方法里会根据ip去获取可用服务

**Comment by adolph58** [comment]
我 seata 1.2 整合 sleuth 之后也出现了这个情况，怎么解决的？
