### ISSUE TITLE
FileLocker 中  releaseLock 方法问题

### ISSUE THREAD

**Issue by suichen** [seata/seata#2661]
![image](https://user-images.githubusercontent.com/7730083/81182135-035b9000-8fe0-11ea-90aa-ba902f4f5a33.png)

红框中的代码是不是无效代码？因为下面调用了lockHolder.clear() 进行了清空，所以红框中的代码是否执行与否，这个 branchSession 的lockHolder都会变为空

**Comment by slievrly** [comment]
`BucketLockMap ` is global lock map, `lockHolder ` belong to a  certain branchSession whose key is a reference to `BucketLockMap `.
