### ISSUE TITLE
io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:10.0.75.1:8091:2043132789, lockKeys:t_storage:1

### ISSUE THREAD

**Issue by mirrorHe** [seata/seata#2686]
根据 springcloud-eureka-feign-mybatis-seata  
order调用storage  发现无法注册全局事务 查询原因是还没注册事务已经开始回滚,估计是feifn为默认时长
然后把order的等待响应时间加长
出现get global lock fail错误
seata 0.9
注册中心eureka

**Comment by lightClouds917** [comment]
1.数据库连接信息，不要用demo原本提供的，很多人都在用，数据会干扰，自己建表和库；
2.移除全局事务注解，看下整个链路是不是通的；
3.LockConflictException可能是其他全局事务持有锁，然后发生锁冲突，这种情况会重试；
可以看看这里：http://seata.io/zh-cn/docs/dev/mode/at-mode.html。
4.建议升级到1.2.0的seata;

**Comment by mirrorHe** [comment]
> 1.数据库连接信息，不要用demo原本提供的，很多人都在用，数据会干扰，自己建表和库；
> 2.可移除的事务注解，看下整个烷基是不是通的；
> 3. LockConflictException可能是其他地方事务持有锁，然后发生锁冲突，这种情况会重试；
> 可以看看这里：[http](http://seata.io/zh-cn/docs/dev/mode/at-mode.html%E3%80%82) : //seata.io/zh-cn/docs/dev/mode/at-mode.html [。](http://seata.io/zh-cn/docs/dev/mode/at-mode.html%E3%80%82)
> 4.建议升级到1.2.0的seata;

好的,谢谢.我是使用的本地的数据库.

**Comment by mirrorHe** [comment]
![image](https://user-images.githubusercontent.com/32771167/81893467-5638d700-95e0-11ea-8bc8-5866d1255de8.png)
去除掉全局注解,流程能跑通.加上之后运行还是报一样的错误,查看数据库发现许多sleep的线程

**Comment by mirrorHe** [comment]
从0.9升级到1.0解决问题

**Comment by bruce121381** [comment]
我也有这个问题而且我还是1.2.0版本的seata,在本地提交的时候这个globalLock获取失败

**Comment by manailin** [comment]
运行seata1.2 还是经常报同样的问题。求解。

**Comment by a364176773** [comment]
官网faq多看下@manailin @mengzxh
