### ISSUE TITLE
我想用源码打包，但找不到打包后的文件位置

### ISSUE THREAD

**Issue by CoderLiuyang** [seata/seata#2690]
我是个小白。pull源码后学习，想用源码打包后部署。但是我执行mvn clean package -Dmaven.test.skip=true后，找不到打包后部署文件。请大佬指点一下。

**Comment by zjinlei** [comment]
http://seata.io/zh-cn/docs/overview/faq.html#16

**Comment by yangziran** [comment]
在 distribution 模块的 target 目录下
