### ISSUE TITLE
seata-server启动时报错

### ISSUE THREAD

**Issue by a46461440** [seata/seata#2692]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用docker命令行启动
docker run 
  --name seata-server1         
  -p 8091:8091         
  -e SEATA_CONFIG_NAME=file:/seata-server/resources/registry         
  -e SERVER_NODE=1         
  -e SEATA_IP=xxx
  -e SEATA_PORT=8091         
  -v /data/docker_data/xxx:/seata-server/resources          
  --privileged=true         
  -d         
  seataio/seata-server:1.2.0

启动日志
06:13:05.055 [main] INFO io.seata.server.ParameterParser - The server is running in container.
06:13:05.121 [main] INFO io.seata.config.FileConfiguration - The configuration file used is file:/seata-server/resources/registry.conf
06:13:05.696 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
06:13:05.718 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
06:13:05.947 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
06:13:05.947 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
06:13:05.967 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
06:13:05.967 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
06:13:05.968 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
06:13:05.969 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
06:13:05.969 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
06:13:05.970 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
06:13:05.970 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
06:13:05.970 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
06:13:05.970 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
06:13:05.970 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
06:13:05.971 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
06:13:05.971 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
06:13:05.972 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1073741824 bytes
06:13:05.972 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
06:13:05.973 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
06:13:05.973 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
06:13:05.982 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 
- OS : centos 7
- Others:

**Comment by zhangxn8** [comment]
我也遇到这个问题了，store.mode 是file的时候是正常的，但是如果是db的话启动就报这个错误

**Comment by zsf513** [comment]
the same

**Comment by dmego** [comment]
@zsf513 最新的 `seataio/seata-server:latest` 镜像没有上述问题

**Comment by liuqiyang7** [comment]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/63906369/180171990-244b3247-0c11-4b64-be25-1a78bf404875.png">
我这边用1.4.2版本启动也遇到了这个问题，请问有解决方案吗？

**Comment by liuqiyang7** [comment]
> <img alt="image" width="1187" src="https://user-images.githubusercontent.com/63906369/180171990-244b3247-0c11-4b64-be25-1a78bf404875.png">
> 
> 我这边用1.4.2版本启动也遇到了这个问题，请问有解决方案吗？

问题解决，因为挂载了/seata-server/resources整个目录，但是外部只有registry.conf文件，缺少其他文件。把挂载目录改成/seata-server/resources/registry.conf解决
