### ISSUE TITLE
seata 注册nacos时，nacos中的服务名始终为serverAddr

### ISSUE THREAD

**Issue by orange-form** [seata/seata#2704]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata 的注册中心为nacos，registry.nacos.applcation = "my-seata-server"。nacos注册中心服务列表中，该seata-server的服务名始终都是serverAddr。
BTW, 我用源码启动是正确的，但是用官网下载的二进制包运行时有问题的。

nacos的版本是1.2.1，seata版本是1.2.0

**Comment by zjinlei** [comment]
registry.nacos.applcation = "my-seata-server"
applcation->application

**Comment by zjinlei** [comment]
另外1.2.0默认是seata-server，没有serverAddr了

**Comment by orange-form** [comment]
@zjinlei 
非常感谢这么及时的回复。
这个拼写错误并没有出现在我的配置中。
我找到了问题，因为spring cloud alibaba dependency中seata的版本是1.1.0，所以我的seata-server用的也是1.1.0。中间调试了其他问题，结果忘记版本的事情，误以为是最新版。
然后如果使用1.1.0的seata +  nacos 1.2.1，确实是有这个问题的。
