### ISSUE TITLE
AT 模式使用PGSQL数据库

### ISSUE THREAD

**Issue by YangQiang-ChengDu** [seata/seata#2705]
环境：
seata1.2、jackson 2.9.5、PG42.2.10
错误如下：
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.postgresql.core.v3.replication.V3ReplicationProtocol and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["beforeImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[117]->io.seata.rm.datasource.sql.struct.Field["value"]->org.postgresql.jdbc.PgArray["resultSet"]->org.postgresql.jdbc.PgResultSet["statement"]->org.postgresql.jdbc.PgStatement["connection"]->org.postgresql.jdbc.PgConnection["queryExecutor"]->org.postgresql.core.v3.QueryExecutorImpl["replicationProtocol"])

**Comment by Garlichead** [comment]
栈堆还可以更多点吗

**Comment by jsbxyyx** [comment]
@YangQiang-ChengDu please verify 2708 pr.
