### ISSUE TITLE
seata v1.2.0 连接不同数据库出现，同一库正常回滚

### ISSUE THREAD

**Issue by 903296615** [seata/seata#2722]
### Cause: java.sql.SQLException: java.sql.SQLSyntaxErrorException: Unknown column 'context' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLException: java.sql.SQLSyntaxErrorException: Unknown column 'context' in 'field list'] with root cause

java.sql.SQLSyntaxErrorException: Unknown column 'context' in 'field list'

如果是同一个库就没问题

**Comment by l81893521** [comment]
Please make sure the undo_log table in each rm datasource.

**Comment by jsbxyyx** [comment]
use latest script/at/xxx.sql.

**Comment by 903296615** [comment]
非常感谢，看了一下我的undo_log 有些数据库有content字段有些没有，估计是用了旧版本的sql
