### ISSUE TITLE
get configTypeName a little flaw

### ISSUE THREAD

**Issue by a364176773** [seata/seata#2724]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
when building a configuration, there are insufficient prompts for configuration items that do not exist or are not supported
当配置不存在或者不支持时,无法从异常提示中捕捉到对应的问题

question 1: not support register type should change to not support config type
问题1:not support register type: 应该改为not support config type:

question 2: the prompt that the configuration type that cannot be read and the configuration type is empty should be separated
问题2:应该将不支持配置中心类型,跟读不到配置中心类型的异常提示区分开

有兴趣处理的同学,可以回复你要认领即可
if you are interested in dealing with this problem, you can reply, please assign it to me

![image](https://user-images.githubusercontent.com/19943636/82774895-ac2b3b80-9e78-11ea-88c5-1ab1d770d597.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by PeineLiang** [comment]
I will fix it.
