### ISSUE TITLE
docker-compose方式启动报错，连接不上nacos

### ISSUE THREAD

**Issue by haotian6** [seata/seata#2733]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

[root@localhost seata-server]# docker-compose up
Creating network "seata-server_default" with the default driver
Creating seata-server_seata-server_1 ... done
Attaching to seata-server_seata-server_1
seata-server_1  | [0.001s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/var/log/seata_gc.log instead.
seata-server_1  | [0.008s][info   ][gc] Using G1
seata-server_1  | 2020-05-27 01:38:04.506 INFO [main]io.seata.server.ParameterParser.init:91 -The server is running in container.
seata-server_1  | 2020-05-27 01:38:04.558 INFO [main]io.seata.config.FileConfiguration.<init>:110 -The configuration file used is file:/root/seata-config/registry.conf
seata-server_1  | [0.601s][info   ][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 24M->6M(248M) 8.431ms
seata-server_1  | [7.613s][info   ][gc] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 19M->6M(248M) 5.629ms
seata-server_1  | 2020-05-27 01:38:18.295 INFO [main]io.seata.core.rpc.netty.RpcServerBootstrap.start:155 -Server started ... 
seata-server_1  | 2020-05-27 01:38:18.434 ERROR[main]io.seata.server.Server.main:95 -rpcServer init error:ErrCode:500, ErrMsg:failed to req API:/api//nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
seata-server_1  | java.lang.RuntimeException: ErrCode:500, ErrMsg:failed to req API:/api//nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
seata-server_1  | 	at io.seata.core.rpc.netty.RpcServerBootstrap.start(RpcServerBootstrap.java:160)
seata-server_1  | 	at io.seata.core.rpc.netty.AbstractRpcRemotingServer.init(AbstractRpcRemotingServer.java:140)
seata-server_1  | 	at io.seata.core.rpc.netty.RpcServer.init(RpcServer.java:59)
seata-server_1  | 	at io.seata.server.Server.main(Server.java:93)
seata-server_1  | Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: java.net.ConnectException: Connection refused (Connection refused)
seata-server_1  | 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:490)
seata-server_1  | 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:395)
seata-server_1  | 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:391)
seata-server_1  | 	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:210)
seata-server_1  | 	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
seata-server_1  | 	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:182)
seata-server_1  | 	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:170)
seata-server_1  | 	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:84)
seata-server_1  | 	at io.seata.core.rpc.netty.RpcServerBootstrap.start(RpcServerBootstrap.java:156)
seata-server_1  | 	... 3 common frames omitted
seata-server_1  | 2020-05-27 01:38:18.445 INFO [ShutdownHook]io.seata.core.rpc.netty.RpcServer.destroy:69 -destroyed rpcServer

**docker-compose.yaml文件内容**
version: "3"
services:
  seata-server:
    image: seataio/seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - /mnt/server/seata-server/conf:/root/seata-config
      - /mnt/server/seata-server/logs:/root/logs
    restart: always

**registry.conf文件内容**
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "http://127.0.0.1:8848"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "http://127.0.0.1:8848"
    namespace = ""
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8.0_231
- OS : Centos 7
- Others:

**Comment by haotian6** [comment]
已解决

**Comment by Killy412** [comment]
怎么解决的?

**Comment by wuxingye** [comment]
怎么解决的

**Comment by wallfacers** [comment]
> 已解决

你好，如何解决的
