### ISSUE TITLE
@GlobalLock select for update 是否存在脏读情况

### ISSUE THREAD

**Issue by 1040087877** [seata/seata#2736]
version：1.2.0

使用场景，
有两个Controller方法，一个全局事务@GlobalTransactional，一个@GlobalLock
@GlobalTransactional 进行update语句操作，修改userid=1，
@GlobalLock   进行select  * from xx where userid=1 for update 操作，
现在是执行到拦截器的时候没有去查全局锁，如果GlobalTransactional生命周期期间回滚是不是@GlobalLock方法查到的是脏数据，没有达到全局查锁的效果。

业务代码

> @GlobalLock
    @Override
    public Order query(String userId) {
        log.info("当前 XID: {}", RootContext.getXID());
        log.info("当前 userId: {}", userId);
        //查询订单
        Order o=orderMapper.query(userId);
        log.info("查询结束:"+o);
        return o;
    }

sql
**\<select id="query" parameterType="string" resultType="Order">
        select * from  `order`
         where user_id=#{userId} for update
    </select>**

执行到io.seata.rm.datasource.exec.SelectForUpdateExecutor#doExecute 方法

> if (RootContext.inGlobalTransaction()) {
                        //do as usual
                        statementProxy.getConnectionProxy().checkLock(lockKeys);
                    } else if (RootContext.requireGlobalLock()) {
                        //check lock key before commit just like DML to avoid reentrant lock problem(no xid thus can
                        // not reentrant)
                        statementProxy.getConnectionProxy().appendLockKey(lockKeys);
                    } else {
                        throw new RuntimeException("Unknown situation!");
                    }

由于配了@GlobalLock，只执行 statementProxy.getConnectionProxy().appendLockKey(lockKeys);，没有检查全局锁，不是会导致脏读的情况吗，还是我理解错了。谢谢

**Comment by slievrly** [comment]
@1040087877 The current solution can only read the real time value once when it is not locked by other transactions

**Comment by 1040087877** [comment]
谢谢回复，这里说的被其他事物锁定，是指本地锁还是全局锁？

我想问下，userid=x  被其他事物在全局锁期间（还未释放全局锁），
@GlobalLock 标注的当前事物执行 select  *  from where userid=x for update 时，是否会检查全局锁。


> @1040087877 The current solution can only read the real time value once when it is not lock by other transactions

**Comment by 1040087877** [comment]
@slievrly 谢谢回复，这里说的被其他事物锁定，是指本地锁还是全局锁？

我想问下，userid=x  被其他事物在全局锁期间（还未释放全局锁），
@GlobalLock 标注的当前事物执行 select  *  from where userid=x for update 时，是否会检查全局锁？

这里原来的设计是不检查全局锁的吗，必须使用@GlobalTransactional才支持检查全局锁？


thank you


> @1040087877 The current solution can only read the real time value once when it is not lock by other transactions

**Comment by ggndnn** [comment]
@1040087877 

> @slievrly 谢谢回复，这里说的被其他事物锁定，是指本地锁还是全局锁？
> 

In your case, if autocommit=true, it means `local transaction`, otherwise means `local or global transaction`.

> 我想问下，userid=x 被其他事物在全局锁期间（还未释放全局锁），
> @GlobalLock 标注的当前事物执行 select * from where userid=x for update 时，是否会检查全局锁？
> 
> 这里原来的设计是不检查全局锁的吗，必须使用@GlobalTransactional才支持检查全局锁？

I think the discussion in #1649 will give you some help.
