### ISSUE TITLE
it is better to rename com.alibaba.fescar.tm.api.FailureHandler as FailureListener

### ISSUE THREAD

**Issue by zffenger** [seata/seata#274]
1、it is better to rename com.alibaba.fescar.tm.api.FailureHandler as FailureListener for the exception will be thrown after the FailureHandler callback, it is more like a listener rather than a handler.
2、the failureHandler can be place as a field in TransactionalTemplate,  it is a good idea that such code below write in TransactionalTemplate
catch (TransactionalExecutor.ExecutionException e) {
                TransactionalExecutor.Code code = e.getCode();
                switch (code) {
                    case RollbackDone:
                        throw e.getOriginalException();
                    case BeginFailure:
                        failureHandler.onBeginFailure(e.getTransaction(), e.getCause());
                        throw e.getCause();
                    case CommitFailure:
                        failureHandler.onCommitFailure(e.getTransaction(), e.getCause());
                        throw e.getCause();
                    case RollbackFailure:
                        failureHandler.onRollbackFailure(e.getTransaction(), e.getCause());
                        throw e.getCause();
                    default:
                        throw new ShouldNeverHappenException("Unknown TransactionalExecutor.Code: " + code);

                }

**Comment by leizhiyuan** [comment]
because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
