### ISSUE TITLE
关于线程的name生成规则

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#2741]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
对于同一类型的线程, 其线程名称都是一样的, 见
![image](https://user-images.githubusercontent.com/22959373/83095418-e47b8580-a0d5-11ea-844b-c3aa4dbf9d46.png)
之前的是 `前缀_线程序号_线程总数`, 现在改成了 `前缀_前缀序号_线程总数`, 其中改动后的前缀序号在初始化线程池工厂的时候就固定了是1, 后续不会被改动.
也就是说, 对于同一个NamedThreadFactory来说, 每次产生的线程的线程名称都是一样的. 请问这样改动的目的是?
@ggndnn

**Comment by slievrly** [comment]
@caohdgege can you improve it?

**Comment by ggndnn** [comment]
@caohdgege Please refer to the PR #1710 which should explain the reason why counter prefix was added. It was not meant to solve the thread name problem. By the way, can you improve it?

**Comment by caohdgege** [comment]
@ggndnn @slievrly  我跟踪了一下这个命名规则的变更, ggndnn加了一个前缀序号，slievrly把线程序号删掉了，如果要改进这个的话，是否就只需要把slievrly的那两行加回来就可以了，同时保留ggndnn加的前缀序号的代码？
![image](https://user-images.githubusercontent.com/22959373/83138780-e701cd80-a11d-11ea-851a-02e9c46cbb58.png)

**Comment by ggndnn** [comment]
> @ggndnn @slievrly 我跟踪了一下这个命名规则的变更, ggndnn加了一个前缀序号，slievrly把线程序号删掉了，如果要改进这个的话，是否就只需要把slievrly的那两行加回来就可以了，同时保留ggndnn加的前缀序号的代码？
> ![image](https://user-images.githubusercontent.com/22959373/83138780-e701cd80-a11d-11ea-851a-02e9c46cbb58.png)

@caohdgege It looks like this.

**Comment by caohdgege** [comment]
@slievrly @ggndnn  ok，那这样的话，我把@slievrly 删掉的那两行加回来，并且发起一个新的pr？

**Comment by ggndnn** [comment]
> @slievrly @ggndnn ok，那这样的话，我把@slievrly 删掉的那两行加回来，并且发起一个新的pr？

@caohdgege fine.
