### ISSUE TITLE
AT模式下，Oracle数据库TIMESTAMP类型的字段数据不能插入UNDO_LOG表

### ISSUE THREAD

**Issue by MrPassionFruit** [seata/seata#2769]
![image](https://user-images.githubusercontent.com/36781382/83831486-1a45ed00-a71a-11ea-8d3b-c1284c63d460.png)
![image](https://user-images.githubusercontent.com/36781382/83831508-27fb7280-a71a-11ea-9d68-bfe9a31aea6c.png)
![image](https://user-images.githubusercontent.com/36781382/83831528-334e9e00-a71a-11ea-8fae-f4a18f7236d5.png)

**Comment by jsbxyyx** [comment]
refer: #2047

**Comment by MrPassionFruit** [comment]
嗯，已经搞定了，，谢谢！
