### ISSUE TITLE
1.2.0版本中 registry.conf 中的设置的apollo 配置无效

### ISSUE THREAD

**Issue by zengjizu** [seata/seata#2774]
apollo 默认读取 app.id的方式，是首先从System Property属性中读取app.id 属性，其次从系统变量中读取APP_ID ，再然后从工程的META-INFO 的app.properties中读取app.id，如果没有获取到app.id属性，则会默认为ApolloNoAppIdPlaceHolder，seata 中设置System Property的时候设置的变量名是appId，故apollo 永远读取不到 这个appId的命名空间，除非在启动的时候主动加上 app.id属性值

**Comment by objcoding** [comment]
At present, someone has submitted pr to fix this problem, so please wait for 1.3.0.

**Comment by objcoding** [comment]
https://github.com/seata/seata/pull/2639

**Comment by xingfudeshi** [comment]
This issue will be closed due to the related PR has been merged.
