### ISSUE TITLE
feature request: 二阶段commit和rollback分别增加一种分支事务的状态，用于仅暂停分支事务的重试而不中断全局事务的二阶段执行。

### ISSUE THREAD

**Issue by wangliang181230** [seata/seata#2778]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
主要为了区别于Unretryable使用。
在部分情况下，开发者仅希望当前分支事务停止重试，并不希望中止整个全局事务的二阶段执行。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
可能的场景：
1、该分支事务所涉及的数据对于当前业务来说并不重要，不希望因为该分支二阶段失败导致其他分支二阶段中止。
2、一些重试机制，可以利用此状态，将该分支事务的重试操作中止掉，而不会持续执行重试。（虽然目前还不存在相关的重试机制。）

**Comment by lightClouds917** [comment]
如果这个分支失败了不需要重试，那是不是可以理解为，他其实不纳入全局事务也行。

**Comment by wangliang1986** [comment]
> 
> 
> 如果这个分支失败了不需要重试，那是不是可以理解为，他其实不纳入全局事务也行。

是的，标志为该状态的分支由人工介入处理，其他分支继续二阶段处理。
