### ISSUE TITLE
need to optimize the current workerId generation rule of snowflake id

### ISSUE THREAD

**Issue by a364176773** [seata/seata#2785]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
at present, the workerId is randomly generated from 0-1023, which is not elegant.I hope someone can solve this problem.

目前workerId 采用随机从0-1023中生成,并不优雅,希望有同学能解决这个问题.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lj2018110133** [comment]
Please assign me the task
