### ISSUE TITLE
service.disableGlobalTransaction无效

### ISSUE THREAD

**Issue by 1026576357** [seata/seata#2798]
使用docker 部署 seataio/seata-server:latest  使用nacos进行配置

nacos配置如下:
transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.thread-factory.boss-thread-prefix=NettyBoss
transport.thread-factory.worker-thread-prefix=NettyServerNIOWorker
transport.thread-factory.server-executor-thread-prefix=NettyServerBizHandler
transport.thread-factory.share-boss-worker=false
transport.thread-factory.client-selector-thread-prefix=NettyClientSelector
transport.thread-factory.client-selector-thread-size=1
transport.thread-factory.client-worker-thread-prefix=NettyClientWorkerThread
transport.thread-factory.boss-thread-size=1
transport.thread-factory.worker-thread-size=8
transport.shutdown.wait=3
service.vgroup_mapping.my_test_tx_group=default
service.enableDegrade=false
service.disable=false
service.max.commit.retry.timeout=-1
service.max.rollback.retry.timeout=-1
service.default.grouplist=192.168.0.253:8859
service.enableDegrade=false
service.disableGlobalTransaction=false
client.async.commit.buffer.limit=10000
client.lock.retry.internal=10
client.lock.retry.times=30
client.lock.retry.policy.branch-rollback-on-conflict=true
client.table.meta.check.enable=true
client.report.retry.count=5
client.tm.commit.retry.count=1
client.tm.rollback.retry.count=1
store.mode=file
store.file.dir=file_store/data
store.file.max-branch-session-size=16384
store.file.max-global-session-size=512
store.file.file-write-buffer-cache-size=16384
store.file.flush-disk-mode=async
store.file.session.reload.read_size=100
store.db.datasource=dbcp
store.db.db-type=mysql
store.db.driver-class-name=com.mysql.jdbc.Driver
store.db.url=jdbc:mysql://192.168.0.253:3306/seata?useUnicode=true
store.db.user=root
store.db.password=Aqgj,123
store.db.min-conn=1
store.db.max-conn=3
store.db.global.table=global_table
store.db.branch.table=branch_table
store.db.query-limit=100
store.db.lock-table=lock_table
recovery.committing-retry-period=1000
recovery.asyn-committing-retry-period=1000
recovery.rollbacking-retry-period=1000
recovery.timeout-retry-period=1000
transaction.undo.data.validation=true
transaction.undo.log.serialization=jackson
transaction.undo.log.save.days=7
transaction.undo.log.delete.period=86400000
transaction.undo.log.table=undo_log
transport.serialization=seata
transport.compressor=none
metrics.enabled=false
metrics.registry-type=compact
metrics.exporter-list=prometheus
metrics.exporter-prometheus-port=9898
support.spring.datasource.autoproxy=false

registry.conf如下:
registry {

  type = "nacos"
 
  nacos {
    serverAddr = "192.168.0.253:8848"
    namespace = "public"
    cluster = "default"
  }
 
}
 
config {

  type = "nacos"
 
  nacos {
    serverAddr = "192.168.0.253:8848"
    namespace = "public"
  }
 
 file {
    name = "/root/seata-config/file.conf"
  }
 
}
jar版本     <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.0.0</version>
        </dependency>

idea控制台一直报错Could not found property service.disableGlobalTransaction, try to use default value instead.
![MXBST)@2XRDCK0JIILX@IO7](https://user-images.githubusercontent.com/49665120/84483391-d92a7b80-accb-11ea-86a2-76c82d608bac.png)

**Comment by slievrly** [comment]
@1026576357 upgrade to seata-spring-boot-starter 1.2.0
