### ISSUE TITLE
SEATA支持SQLSERVER2012吗？

### ISSUE THREAD

**Issue by newlinbaolin** [seata/seata#2804]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
@newlinbaolin currently   not support.

**Comment by newlinbaolin** [comment]
谢谢！那我现在的业务数据库都是SQLSERVER2012，请问有什么办法实现分布式事务？

**Comment by a364176773** [comment]
> 谢谢！那我现在的业务数据库都是SQLSERVER2012，请问有什么办法实现分布式事务？

您可以尝试tcc或者saga模式来解决
