### ISSUE TITLE
build before image with limit

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#2805]
## Why you need it?
mysql环境下：
用limit去更新数据的时候，包超大了，然后抛异常了。。。
the env: mysql
the package send to mysql is too big where using limit，and throws a exception

## How it could be?
对于如下SQL(语句中包含了limit的)
`update order_tbl set count=2 where user_id=1001 and commodity_code=2001 limit 1`
在生成before_image的时候的查询语句为
`SELECT id, count FROM order_tbl WHERE user_id = 1001 AND commodity_code = 2001 FOR UPDATE`
问题是，对于这么一个更新语句的话，其实我们应该是只需要知道第一条的数据是什么，然后构建before_image的时候，应该也是只需要知道第一条的数据就可以了吧，而不需要把符合条件的都查询出来，请问，为什么在构建before_image的SQL的时候没有把 limit 的条件加上？
能否在构建before_image的时候，把limit条件和order by加上(如果有的话)。

as for the sql(include limit):
`update order_tbl set count=2 where user_id=1001 and commodity_code=2001 limit 1`
the sql that build the before image:
`SELECT id, count FROM order_tbl WHERE user_id = 1001 AND commodity_code = 2001 FOR UPDATE`
the question is that, why we ignore the limit when build the before image? we just need to know the row that will be update. 
can the limit and the order by condition be add when build before image sql.

## Other related information
主要的生成before_image的SQL的代码：
the main code that build the before image sql :
```java
// seata version 1.3.0-SNAPSHOT
// UpdateExecutor
private String buildBeforeImageSQL(TableMeta tableMeta, ArrayList<List<Object>> paramAppenderList) {
    SQLUpdateRecognizer recognizer = (SQLUpdateRecognizer)sqlRecognizer;
    StringBuilder prefix = new StringBuilder("SELECT ");
    StringBuilder suffix = new StringBuilder(" FROM ").append(getFromTableInSQL());
    String whereCondition = buildWhereCondition(recognizer, paramAppenderList);
    if (StringUtils.isNotBlank(whereCondition)) {
        suffix.append(" WHERE ").append(whereCondition);
    }
    suffix.append(" FOR UPDATE");
    StringJoiner selectSQLJoin = new StringJoiner(", ", prefix.toString(), suffix.toString());
    if (ONLY_CARE_UPDATE_COLUMNS) {
        List<String> updateColumns = recognizer.getUpdateColumns();
        if (!containsPK(updateColumns)) {
            selectSQLJoin.add(getColumnNameInSQL(tableMeta.getEscapePkName(getDbType())));
        }
        for (String columnName : updateColumns) {
            selectSQLJoin.add(columnName);
        }
    } else {
        for (String columnName : tableMeta.getAllColumns().keySet()) {
            selectSQLJoin.add(ColumnUtils.addEscape(columnName, getDbType()));
        }
    }
    return selectSQLJoin.toString();
}
```

**Comment by slievrly** [comment]
@caohdgege What is the business scenario of update xxx where xxx limit 1? For limit 1, I think it is uncertain.

**Comment by caohdgege** [comment]
1. 把积分最高的某个人的状态改成无效（和order by一起使用）。
2. uncertain 指的是update和select获取到的不是同一列？还是？

a. Change the status of the person with the highest score to invalid(with `order by`).
b. the meaning of `uncertain` is ?
