### ISSUE TITLE
seata与springbatch发生出冲突

### ISSUE THREAD

**Issue by yueyuanyu** [seata/seata#2815]
### Ⅰ. Issue Description
我在尝试与我们的项目整合时,启动报错,原因是seata代理与springbatch的@stepscope发生冲突
报错如下
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.batchMultiSendPartitioner': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:355)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
	at io.seata.spring.util.SpringProxyUtils.findTargetClass(SpringProxyUtils.java:57)
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:210)
	... 78 common frames omitted
```

### Ⅲ. Describe what you expected to happen
定位到springbatch的stepscope注解:
![image](https://user-images.githubusercontent.com/33542699/85009081-7126da00-b190-11ea-9ead-689b023099a2.png)
我猜测应该是与springbatch的@stepScope注解冲突导致此异常, 但我们的项目中多处使用到了springbatch 无法更换.
### Ⅴ. Anything else we need to know?
我确实不知道改如何解决此冲突,求助
### Ⅵ. Environment:

- JDK version :1.8
- Others: springcloud版本 E  seata版本 1.2.0(使用0.9.0也是这个错)

**Comment by jsbxyyx** [comment]
@yueyuanyu can you provide reappear demo?

**Comment by yueyuanyu** [comment]
> @yueyuanyu can you provide reappear demo?

我是在尝试与我们项目整合时发生的错误,我无法提供给你我们的项目,但是基本上问题锁定在seata代理与springbatch上了。 比如 我将Springbatch的@StepScope注解注释掉后就能启动了,但是注释掉后我的批处理部分将不能正常使用。

**Comment by yueyuanyu** [comment]
> @yueyuanyu can you provide reappear demo?

@stepScope的作用是将springbatch相关的bean延后初始化，报错部分则是seata（GlobalTransactionScanner.wrapIfNecessary（））尝试代理时获取这些被@stepScope注释的bean的StepContext为空报的错

**Comment by yueyuanyu** [comment]
> @yueyuanyu can you provide reappear demo?

我确定几乎所有用到springbatch的项目尝试整合seata时都会遇到这个问题，我确实尝试了很久都无法解决

**Comment by jsbxyyx** [comment]
@yueyuanyu 你可以简单的搭建一个可以重现的demo出来

**Comment by yueyuanyu** [comment]
> @yueyuanyu 你可以简单的搭建一个可以重现的demo出来

这是一个简单的复现demo  https://gitee.com/yueyuanyu/springbatch-seata-error-demo

**Comment by jsbxyyx** [comment]
@yueyuanyu 403 无法下载

**Comment by yueyuanyu** [comment]
> @yueyuanyu 403 无法下载
@jsbxyyx 
https://gitee.com/yueyuanyu/springbatch-seata-error-demo.git

**Comment by jsbxyyx** [comment]
@yueyuanyu ![image](https://user-images.githubusercontent.com/26616196/85239680-72ddef80-b467-11ea-8111-2f741f887c44.png)

**Comment by yueyuanyu** [comment]
> @yueyuanyu ![image](https://user-images.githubusercontent.com/26616196/85239680-72ddef80-b467-11ea-8111-2f741f887c44.png)

不好意思是我的疏忽 权限打开了

**Comment by a364176773** [comment]
还是打不开

**Comment by yueyuanyu** [comment]
> 还是打不开

可以了  麻烦你再试下

**Comment by yueyuanyu** [comment]
> 还是打不开

请问有思路了吗

**Comment by xingfudeshi** [comment]
Maybe the bean with step scope should be skipped.

**Comment by yueyuanyu** [comment]
> Maybe the bean with step scope should be skipped.

请问如何忽略掉呢   seata不是代理的是数据源吗  我看到有这样一个属性 
![image](https://user-images.githubusercontent.com/33542699/85948683-c4650d80-b984-11ea-9ef4-74043af97cb0.png)但注释上说的是忽略的DataSourcebean

**Comment by xingfudeshi** [comment]
> > Maybe the bean with step scope should be skipped.
> 
> 请问如何忽略掉呢 seata不是代理的是数据源吗 我看到有这样一个属性
> ![image](https://user-images.githubusercontent.com/33542699/85948683-c4650d80-b984-11ea-9ef4-74043af97cb0.png)但注释上说的是忽略的DataSourcebean

Yes.excludedForAutoProxying only works for datasouce bean.

**Comment by xingfudeshi** [comment]
Please try to use @Scope(value="step",proxyMode= ScopedProxyMode.INTERFACES) instead @StepScope.see if it works.

**Comment by yueyuanyu** [comment]
![image](https://user-images.githubusercontent.com/33542699/85963360-d1671880-b9e7-11ea-906d-bc851883c1c8.png)
![image](https://user-images.githubusercontent.com/33542699/85963372-e0e66180-b9e7-11ea-8985-d5654d4c34d8.png)
这个方法不起作用(包括使用提示信息)

**Comment by yueyuanyu** [comment]
Need help!

**Comment by yueyuanyu** [comment]
加入配置stepscope autoparoxy=true 目前不报错了 但紧接着的下一个问题是flyway初始化时一直卡在'xxxx'is up to date. No migration necessary.
![image](https://user-images.githubusercontent.com/33542699/86216876-40dc3400-bbb1-11ea-9d88-0f7b8c7b9f7d.png)

**Comment by yueyuanyu** [comment]
目前发现的带有scope注解的会出错 包括refreshScope

**Comment by wangliang1986** [comment]
> 
> 
> 目前发现的带有scope注解的会出错 包括refreshScope

seata的GlobalTransactionScanner扫描时，导致了scope的AOP提前执行了。
可以考虑在seata端添加一个配置项来排除某些类的扫描。

**Comment by liangliangmax** [comment]
在声明ItemReader的地方要使用ItemReader这种顶层接口，而不能使用JdbcPagingItemReader等具体的子类，加上@StepScope启动就不会报错了，我这边是有效的^_^

**Comment by chapterBegin** [comment]
> > @yueyuanyu 你可以简单的搭建一个可以重现的demo出来
> 
> @jsbxyyx 这是一个简单的复现demo https://gitee.com/yueyuanyu/springbatch-seata-error-demo

你例子里面这个job是拿来干嘛用的？
` 
@Bean
    public Job multiSendJob(){
        return  jobBuilderFactory.get("multiSendJob")
                .start(multiSendStep())
                .build();
    }
`
