### ISSUE TITLE
seata可靠性问题

### ISSUE THREAD

**Issue by VanPersies** [seata/seata#2823]
请问下对于最新版本develop分支，对于at、tcc、saga、xa四种模式，在seata server都宕机的情况下，有没有做可靠性设计？

**Comment by slievrly** [comment]
@VanPersies Seata cluster mode is stateless.

**Comment by haixuzhao** [comment]
这句话该怎么理解呢？

**Comment by VanPersies** [comment]
> @VanPersies Seata cluster mode is stateless.
比如at模式下，回滚时服务器宕机或网络抖动，导致只有部分RM收到回滚命令，这块有补偿措施不？

**Comment by VanPersies** [comment]
> 这句话该怎么理解呢？

比如at模式下，回滚时服务器宕机或网络抖动，导致只有部分RM收到回滚命令

**Comment by xingfudeshi** [comment]
Please check the WorkProcess part over here. http://seata.io/en-us/docs/overview/what-is-seata.html
