### ISSUE TITLE
seata 1.2.0和elastic job整合的时候报错

### ISSUE THREAD

**Issue by taikeung** [seata/seata#2835]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
spring boot 2.1.4 release  +  spring cloud alibaba 2.1.2 release + elastic job 2.1.5
```
                  <dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-dubbo</artifactId>
		</dependency>

		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-seata</artifactId>
			<exclusions>
				<exclusion>
					<groupId>io.seata</groupId>
					<artifactId>seata-spring-boot-starter</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>io.seata</groupId>
			<artifactId>seata-spring-boot-starter</artifactId>
			<version>1.2.0</version>
		</dependency>
                
                <dependency>
			<groupId>com.dangdang</groupId>
			<artifactId>elastic-job-lite-spring</artifactId>
		</dependency>

```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

启动报错
Error creating bean with name 'quartzDataSourceInitializer': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariDataSource.getTargetObject()Ljava/lang/Object;
Related cause: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'configurableEnvironmentConfiguration': Requested bean is currently in creation: Is there an unresolvable circular reference?

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$5b0725c9.getTargetObject(<generated>)

The following method did not exist:

    com.zaxxer.hikari.HikariDataSource.getTargetObject()Ljava/lang/Object;

The method's class, com.zaxxer.hikari.HikariDataSource, is available from the following locations:

    jar:file:/tonder/app/risk-engine/backup/640/risk-engine.jar!/BOOT-INF/lib/HikariCP-3.2.0.jar!/com/zaxxer/hikari/HikariDataSource.class

It was loaded from the following location:

    jar:file:/tonder/app/risk-engine/backup/640/risk-engine.jar!/BOOT-INF/lib/HikariCP-3.2.0.jar!/

Action:

Correct the classpath of your application so that it contains a single, compatible version of com.zaxxer.hikari.HikariDataSource

其中：
 +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.1.4.RELEASE:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:3.2.0:compile

 +- org.quartz-scheduler:quartz:jar:2.3.1:compile
[INFO] |  |        |  +- com.mchange:mchange-commons-java:jar:0.2.15:compile
[INFO] |  |        |  \- com.zaxxer:HikariCP-java7:jar:2.4.13:compile

但是我把其中任意一个exclude掉也还是报上述错误，但是去掉seata或者去掉elastic job的话，项目能正常启动

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
@xingfudeshi can you help to look at the problem?

**Comment by xingfudeshi** [comment]
@AndyHooo Could you please provide a demo which can re-produce this problem?

**Comment by xingfudeshi** [comment]
> @xingfudeshi can you help to look at the problem?

I'll do it.

**Comment by xingfudeshi** [comment]
Will this happen again now?@taikeung
