### ISSUE TITLE
使用@GlobalTransactional AT模式事务回滚异常

### ISSUE THREAD

**Issue by hsoftxl** [seata/seata#2851]
使用一段时间发现 seata server 的 lock_table 和 branch_table 有数据, global_table 没有数据,
业务上会出现 
![image](https://user-images.githubusercontent.com/6965803/86322103-ed2f2080-bc6c-11ea-9194-c3ffab9c01da.png)

请问这个问题如何排查, 能不能简单描述一下从哪里下手排查问题.

**Comment by lv-lele** [comment]
at 在高并发的情况下，一致性是可以保证的，但是吞吐量不高。原因就是一阶段会出现全局锁的竞争 
seata-seaver配置中 更改client.rm.lock.retryTimes和client.rm.lock.retryInterval来调整，或者用tcc
