### ISSUE TITLE
undo_log记录的数据ID问题

### ISSUE THREAD

**Issue by HongKing** [seata/seata#2855]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
我业务中用的数据ID是由雪花算法生成的，最近发现有undo_log数据，进行数据回滚处理时，发现undo_log中的ID与我业务表中的ID不一致。

### Ⅱ. Describe what happened
比如：我业务中的数据ID为：99365378025088832 但是记录到undo_log中的却是：99365378025088830
![图片](https://user-images.githubusercontent.com/1324004/86455988-01018200-bd54-11ea-9f6c-3cb752867c1f.png)
![图片](https://user-images.githubusercontent.com/1324004/86455926-ea5b2b00-bd53-11ea-823c-94a1ed58385d.png)

### Ⅴ. Anything else we need to know?
由于用的是1.0版本，暂时还没有升级到最新版，不知道新版本是否有类似问题

### Ⅵ. Environment:
- version: 1.0
- JDK version :1.8
- OS : centos6.5
- Others:

**Comment by a364176773** [comment]
请升级版本，估计是long类型丢失精度导致。我记得新版本已经处理了

**Comment by HongKing** [comment]
@a364176773 好的，谢谢，我先试试。

**Comment by xuxuhui** [comment]
> @a364176773 好的，谢谢，我先试试。

后面这个问题是怎么解决的
