### ISSUE TITLE
测试和开发环境共用seata-server时，seata-server怎么配置注册进nacos的是公网ip

### ISSUE THREAD

**Issue by chenyduan** [seata/seata#2874]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by tanzzj** [comment]
配置ip的话，使用-h参数指定

**Comment by ccDuan** [comment]
之前我的描述有问题，是开发和测试共用部署在服务器上的seata-server,结果本地获取到的server端的ip是服务器内网ip,我查了nacos的说明是nacos客户端配置spring.cloud.nacos.discovery.ip =，那seata-server作为nacos的客户端要怎么配置注册的ip。

**Comment by xuxinjian1993** [comment]
seata使用docker部署时，启动参数可以设置seata_ip，这个IP就是你在nacos里面看到的seata-server的IP，你把这个IP写成你的公网IP就行

**Comment by yuzhihaoGitHub** [comment]
> seata使用docker部署时，启动参数可以设置seata_ip，这个IP就是你在nacos里面看到的seata-server的IP，你把这个IP写成你的公网IP就行

可以把docker-compose.yml发我一份吗，哥们
