### ISSUE TITLE
使用mybatisplus做动态数据源时undo_log的记录不会删除

### ISSUE THREAD

**Issue by xwcarl** [seata/seata#2878]
问题描述
在微服务中使用mybatisplus动态数据源插件做动态数据源时，提交事务回滚事务都正常，事务处理完后undo_log的记录没有删除

**Comment by a364176773** [comment]
i will follow up

**Comment by a364176773** [comment]
@huayanYu I need to communicate with you. I hope you can contact me

**Comment by a364176773** [comment]
automatic proxy and custom data source can only choose one of two
