### ISSUE TITLE
add spock ut

### ISSUE THREAD

**Issue by sanshuiyijing233** [seata/seata#289]
Spock is a testing and specification framework for Java and Groovy applications. What makes it stand out from the crowd is its beautiful and highly expressive specification language. Thanks to its JUnit runner, Spock is compatible with most IDEs, build tools, and continuous integration servers. Spock is inspired from JUnit, RSpec, jMock, Mockito, Groovy, Scala, Vulcans, and other fascinating life forms.

form spockframework.

I'd like to introduce such a beautiful language to this project.Although need some kind of learning cost, but using a very comfortable and convenient.

**Comment by sanshuiyijing233** [comment]
If there is no coverage test report, can add the following configuration in pom file

**Comment by leizhiyuan** [comment]
because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
