### ISSUE TITLE
实际参数值与官方文档中默认值不一致

### ISSUE THREAD

**Issue by guang384** [seata/seata#2903]
[官方文档](https://seata.io/zh-cn/docs/user/configurations.html)中关于参数配置提到如下配置拥有默认值

![image](https://user-images.githubusercontent.com/1582168/87758873-e47b4480-c83f-11ea-9d43-b2eae4bd8b1d.png)

但是实际执行时，发现这些参数无默认值，需要手工指定

![image](https://user-images.githubusercontent.com/1582168/87759222-8438d280-c840-11ea-9b5b-b12bc45ededf.png)
![image](https://user-images.githubusercontent.com/1582168/87759228-8864f000-c840-11ea-95ac-3a5e3abc7028.png)

(store.mode=db)

**Comment by cmonkey** [comment]
mode 等于什么

**Comment by guang384** [comment]
> mode 等于什么

store.mode=db

**Comment by cmonkey** [comment]
有用配置中心吗

**Comment by guang384** [comment]
> 有用配置中心吗

是的 ，用的 zk

**Comment by dongguangming** [comment]
以代码为准，一般技术文档都是落后于代码的
