### ISSUE TITLE
Seata的AT事务回滚没有记录undo_log日志

### ISSUE THREAD

**Issue by aral-sea** [seata/seata#2916]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

eata-spring-boot-starter, yaml配置，日志显示开启事务，服务代码错误回滚，发现undo_log没有新增数据，最后seata-serve日志回滚显示成功了， 想问一下有哪一方面可能造成undo_log没有新增的原因
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
事务回滚只是delete的操作，没有执行add操作。
![图片](https://user-images.githubusercontent.com/49829910/88140936-3bf52800-cc25-11ea-8df9-27695f04f173.png)

按照正常的undu_log的回滚记录
![图片](https://user-images.githubusercontent.com/49829910/88141136-93939380-cc25-11ea-8eb7-ddc1485153aa.png)

如果调试源码的情况下就执行add的undo_log的日志，不调试的情况下，add没有执行，不知道为什么？
![图片](https://user-images.githubusercontent.com/49829910/88141412-259b9c00-cc26-11ea-8e92-a921a6b667a4.png)

### Ⅵ. Environment:

- JDK version :1.8
- OS : win10、CentoS7
- seata-spring-boot-starter: 1.2
- spring-cloud-alibaba-seata: 2.2.0.RELEASE
- spring-boot-starter-parent:2.1.6.RELEASE
- spring-cloud-dependencies:Greenwich.SR2
- mybatis-plus:3.1.2

**Comment by slievrly** [comment]
@aral-sea GlobalFinished means that the local transaction is not complete, so there is no need to record undo log.

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/3026
入门问题请查看此处
