### ISSUE TITLE
serta k8s部署问题

### ISSUE THREAD

**Issue by hanyidreamer** [seata/seata#2919]
## Why you need it?
 1、k8s中registry.conf是如何区分环境的，测试生产不同注册中心和配置中心需要打两份镜像么？
2、k8s部署集群server，通过ng ingress暴露给容器外client链接，client工作情况下部署最后一个pod关闭了15分钟，请问是有优雅关闭处理了SIGTERM信号么？
谢谢！

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
@hanyidreamer 1. SEATA_ENV https://seata.io/zh-cn/docs/ops/deploy-by-docker.html

2. todo

**Comment by hanyidreamer** [comment]
@slievrly 2已经解决了忘了过来处理issue，建议官方k8s resource require和limit配置下（没看最新代码也可能是我版本不新），主机资源不足卡顿k8s部署kill执行命令很久到达，k8s日志现象只看到污点相关提示（我的缺require和limit配置）

**Comment by hanyidreamer** [comment]
1我也处理了，拷贝所有环境的config文件夹部署，通过启动脚本结合环境变量修改classpath生效对应环境启动（类似spring.profile.active），多环境只需打包一次一个镜像
