### ISSUE TITLE
optimization of global lock contention cycle

### ISSUE THREAD

**Issue by a364176773** [seata/seata#2943]
## Why you need it?
the global lock contention cycle design cannot satisfy some scenarios
目前全局锁竞争周期只能通全局配置，而一些事务需要竞争更加久，或者尽快的退出锁竞争的场景，无法满足。

## How it could be?
client.rm.lock.retryInterval
client.rm.lock.retryTimes

at present, only the above two values can be set to achieve a reasonable cycle of lock competition, but the vast majority of scenarios may require more detailed and targeted Settings
For example, the contention cycle configuration of global lock can be obtained by annotation, the configuration on the
Design scheme：
annotation is read first, and the global configuration is not used.

目前只能通过对以上两个值的设置来达到锁竞争的一个周期合理化，但是绝大部分的场景可能需要更加细致的设置，具有针对性的设置
设计方案：
比如可通过注解拿到全局锁的竞争周期配置，优先读取注解上的配置，无则进行使用全局的配置。

**Comment by selfishlover** [comment]
let me try to optimize this.
