### ISSUE TITLE
seata 1.3.0 使用 seata-server.bat windows 启动乱码问题 

### ISSUE THREAD

**Issue by Liuzebiao** [seata/seata#2954]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by Liuzebiao** [comment]
[2m2020-07-31 15:32:32.660[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36mio.seata.config.FileConfiguration       [0;39m [2m:[0;39m The configuration file used is registry.conf
[2m2020-07-31 15:32:33.647[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36mcom.alibaba.druid.pool.DruidDataSource  [0;39m [2m:[0;39m {dataSource-1} inited
[2m2020-07-31 15:32:34.025[0;39m [32m INFO[0;39m [2m---[0;39m [2m[           main][0;39m [36mi.s.core.rpc.netty.NettyServerBootstrap [0;39m [2m:[0;39m Server started, listen port: 8091

 java.io.IOException: 杩滅▼涓绘満寮鸿揩鍏抽棴浜嗕竴涓幇鏈夌殑杩炴帴銆?

**Comment by wangliang181230** [comment]
1.3.0的新功能，在控制台打印日志可带颜色。
windows的控制台不支持颜色字体输出，你可以自己去server/config/logback.xml里把%clr(xxxx){color}外面这个删掉。就不会乱码了。

**Comment by wangliang181230** [comment]
不过，程序上应该可以优化掉，自动判断是否windows环境，我明天抽空看看能不能优化掉。

**Comment by Liuzebiao** [comment]
好的，谢谢啦

在 2020-08-03 20:49:36，wangliang181230 <notifications@github.com> 写道：


1.3.0的新功能，在控制台打印日志可带颜色。
windows的控制台不支持颜色字体输出，你可以自己去server/config/logback.xml里把%clr(xxxx){color}外面这个删掉。就不会乱码了。

**Comment by wangliang181230** [comment]
我提了一个PR了，1.4.0版本出来后，可以不用手动修改logback.xml了。

**Comment by Liuzebiao** [comment]
哇，点赞👍🏻

在 2020-08-04 11:55:56，wangliang181230 <notifications@github.com> 写道：


我提了一个PR了，1.4.0版本出来后，可以不用手动修改logback.xml了。

**Comment by wangliang181230** [comment]
这个也是我弄出来的锅。哈哈。

**Comment by Liuzebiao** [comment]
seata 开发者？贡献者？大佬牛逼。哈哈










在 2020-08-04 16:52:50，"wangliang181230" <notifications@github.com> 写道：

这个也是我弄出来的锅。哈哈。

**Comment by wangliang181230** [comment]
小小贡献者，不足挂齿。

**Comment by Liuzebiao** [comment]
哈哈，那也牛叉。向大佬学习。













在 2020-08-04 17:25:21，"wangliang181230" <notifications@github.com> 写道：

小小贡献者，不足挂齿。

**Comment by LearnJA** [comment]
seata使用bat文件启动的时候  出现这么一行乱码日志：[0;39m [36mio.seata.config.FileConfiguration       [0;39m [2m:[0;39m The configuration file used is registry.conf   然后就闪退了   这是咋回事儿

**Comment by wangliang181230** [comment]
这个是颜色符，bat打开的窗口不支持显示。按照上面说的在logback.xml里把%clr(){xxxx}删掉就行。
至于闪退，跟这个颜色符无关，可能是你的配置问题。

**Comment by LearnJA** [comment]
谢谢！  日志上有显示
![image](https://user-images.githubusercontent.com/44966567/93162182-c1d5b100-f746-11ea-971a-d87c49136473.png) registry.conf的字样  但是这个配置文件里面只是按照正常的修改   主要是  我昨天都能启动  今天就不行了  很迷

**Comment by LearnJA** [comment]
我找到原因了    seata服务注册的nacos工作空间似乎没办法自定义 只能默认public   我添加其他工作空间id 就会闪退关闭  不填就只能注册到默认piblic上   这一点是因为我填写工作空间配置方式不对吗？  我试了名称和id  id闪退 名称能启动但注册不上nacos

**Comment by wudino11983** [comment]
1.4版本还是存在乱码，未解决该问题啊
![图1](https://user-images.githubusercontent.com/9353147/98088821-ea636700-1ebc-11eb-937d-5459e4535231.PNG)

**Comment by yangqingwen200** [comment]
> 1.4版本还是存在乱码，未解决该问题啊
> 
> ![Feige图片20201104164256](https://user-images.githubusercontent.com/9353147/98089004-23034080-1ebd-11eb-9a10-242fb8ce7da7.png)

win7在可以修改conf/logback.xml中appender name="CONSOLE"的charset, 改为GBK(和dos窗口编码格式一致);
win10可以修改powershell的窗口编码格式, 改成UTF-8;
