### ISSUE TITLE
分支事务删除锁的时候报错导致lock_table无法被删除（根据代码判断，全局事务提交也有可能有类似的问题）

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#2976]
## 版本信息
OS: centos7.6
seata-version: 1.3.0
模式：AT
## 起因
1. TM端发生回滚
2. TC端在删除lock_table对应记录时报错(数据库死锁)，LogStoreDataBaseDAO#deleteBranchTransactionDO
3. 上面的Exception被代码消费忽略，DataBaseLockManager#releaseLock
4. 回滚忽略异常进行进行

## 结果
lock_table中报错的那条记录最终没有被删除，导致对应的记录一直被锁住。

## 主要原因代码分析
```java
// GlobalSession#removeBranch
for (SessionLifecycleListener lifecycleListener : lifecycleListeners) {
    lifecycleListener.onRemoveBranch(this, branchSession);
}
branchSession.unlock();
remove(branchSession);
```
```java
// DataBaseLockManager#releaseLock
try {
    return getLocker().releaseLock(branchSession.getXid(), branchSession.getBranchId());
} catch (Exception t) {
    LOGGER.error("unLock error, xid {}, branchId:{}", branchSession.getXid(), branchSession.getBranchId(), t);
    return false;
}
```
以上是在删除分支事务的主要代码，其中，生命周期监听者在`onRemoveBranch`的时候，把分支事务branch_table对应的记录已经删除了。
当分支事务在`LockStoreDataBaseDAO#unLock`的时候报错，其异常被上层的`DataBaseLockManager#releaseLock`捕获并消费，返回了false，而同时可以看到`GlobalSession#removeBranch`的时候，并没有判断`DataBaseLockManager#releaseLock`的返回值就继续执行了，再上层就会认为这次的锁删除已经成功了(但是事实上并没有)。

## 预期目标
当unlock报错的时候，通过补偿或者其他方式，把对应的lock_table的记录删除。

## Version information
OS: centos7.6
seata-version: 1.3.0

**Comment by a364176773** [comment]
你可以帮忙优化这个问题吗？我的思路是，目前全局事务是有个定时任务不断的查询，然后去处理，如果你想把已经没有全局事务，也没有分支事务信息，但锁还在被占用的话，我认为你也可以模仿全局事务的做法。

**Comment by caohdgege** [comment]
我再研究一下FileLocker和RedisLocker之后，看一下该如何优化。

**Comment by caohdgege** [comment]
补充一下：
在进行全局提交的时候，有两个地方会去删除锁，第一个是在`DefaultCore#commit`，在判断shouldCommit的时候有第一次判断，会一次性删除所有的对应的lock_table的数据，第二次是在`BranchSession#unlock`的时候。
而在进行全局回滚的时候，只有在`BranchSession#unlock`进行删除lock_table，在判断shouldRollback的时候没有去删除锁。
同时，看到`GlobalSession#commit`的注释中写的是锁应该在分支事务提交的时候再释放，但是事实上他在分支事务提交之前就已经释放了，这个是属于遗漏？

```java
// GlobalSession#commit
boolean shouldCommit = SessionHolder.lockAndExecute(globalSession, () -> {
    // the lock should release after branch commit
    // Highlight: Firstly, close the session, then no more branch can be registered.
    globalSession.closeAndClean();
    if (globalSession.getStatus() == GlobalStatus.Begin) {
        globalSession.changeStatus(GlobalStatus.Committing);
        return true;
    }
    return false;
});
```
```java
// GlobalSession#rollback
boolean shouldRollBack = SessionHolder.lockAndExecute(globalSession, () -> {
    globalSession.close(); // Highlight: Firstly, close the session, then no more branch can be registered.
    if (globalSession.getStatus() == GlobalStatus.Begin) {
        globalSession.changeStatus(GlobalStatus.Rollbacking);
        return true;
    }
    return false;
});
```

**Comment by wangliang181230** [comment]
> 
> 
> 补充一下：
> 在进行全局提交的时候，有两个地方会去删除锁，第一个是在`DefaultCore#commit`，在判断shouldCommit的时候有第一次删除(`GlobalSession#closeAndClean`)，会一次性删除所有的对应的lock_table的数据，第二次是在`BranchSession#unlock`的时候。
> 而在进行全局回滚的时候，只有在`BranchSession#unlock`进行删除lock_table，在判断shouldRollback的时候没有去删除锁。
> 同时，看到`GlobalSession#commit`的注释中写的是锁应该在分支事务提交的时候再释放，但是事实上他在分支事务提交之前就已经释放了，这个是属于遗漏？
> 
> ```java
> // GlobalSession#commit
> boolean shouldCommit = SessionHolder.lockAndExecute(globalSession, () -> {
>     // the lock should release after branch commit
>     // Highlight: Firstly, close the session, then no more branch can be registered.
>     globalSession.closeAndClean();
>     if (globalSession.getStatus() == GlobalStatus.Begin) {
>         globalSession.changeStatus(GlobalStatus.Committing);
>         return true;
>     }
>     return false;
> });
> ```
> 
> ```java
> // GlobalSession#rollback
> boolean shouldRollBack = SessionHolder.lockAndExecute(globalSession, () -> {
>     globalSession.close(); // Highlight: Firstly, close the session, then no more branch can be registered.
>     if (globalSession.getStatus() == GlobalStatus.Begin) {
>         globalSession.changeStatus(GlobalStatus.Rollbacking);
>         return true;
>     }
>     return false;
> });
> ```

全局提交时的注释信息有误，现在已经删除掉了。
