### ISSUE TITLE
咨询关于Seata分布式事务

### ISSUE THREAD

**Issue by jmbkeyes** [seata/seata#2983]
系统里有微服务：用户、库存、订单，都使用seata代理了数据源。 假如有如下操作（假定余额100）
操作1：使用Seata AT模式，用户下单，扣用户余额10，扣库存
操作2：未使用分布式事务，调用了用户服务充值100
当操作1完成了大部分分支事务，全局事务还没有提交时，进行操作2成功后，操作1由于某些原因导致事务回滚， 
此时用户的余额是回滚到下单前的100还是其他？

**Comment by a364176773** [comment]
回滚不了，只能无限重试，可人工介入，因为事务发生的数据被修改了，导致一致性已经被破坏。
