### ISSUE TITLE
transform seata-server into spring-boot project

### ISSUE THREAD

**Issue by a364176773** [seata/seata#2984]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

为了更加符合如今潮流，可将seata-server改造为spring-boot项目
in order to be more in line with the current trend, seata-server can be transformed into a spring-boot project

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by spilledyear** [comment]
I will do it
