### ISSUE TITLE
AT,XA模式命名的来源

### ISSUE THREAD

**Issue by flysnow911** [seata/seata#2991]
AT,XA模式的命名是怎么来的, 全称是什么？ google了一下，没找到。
谁能解答一下？
谢谢！

**Comment by averyzhujinbo** [comment]
AT 我自己理解应该是 Auto Transaction  seata AT模式，分布式事务全局监控，全局提交/回滚都是自动完成的
XA 应该是关系型数据库本身支持的分布式事务特性，比如Oracle MySQL 数据库都支持分布式事务 XA协议

**Comment by a364176773** [comment]
xa：eXtended Architecture  at就是二楼所说的
