### ISSUE TITLE
 lock retry policy may cause useless operation

### ISSUE THREAD

**Issue by hecyxy** [seata/seata#2995]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
the target of the feature is to optimize retry policy.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

code position：io.seata.rm.datasource.exec.AbstractDMLBaseExecutor#executeAutoCommitTrue
when  lock conflict exception occurs and execute retry policy , it will execute executeAutoCommitFalse (getBeforeImage、executeSql、getAfterImage) uselessly and repeatedly. And we will just need to retry to commit.

1. executeAutoCommitFalse(getBeforeImage、executeSql、getAfterImage) 
2. commit -> lock conflict occurs
3. executeAutoCommitFalse(getBeforeImage、executeSql、getAfterImage)  again
4. commit -> lock conflict occurs
5. executeAutoCommitFalse(getBeforeImage、executeSql、getAfterImage)  again
6. commit successfully (lock disappear)
cause useless action

**Comment by ggndnn** [comment]
As said before, if retryPolicyBranchRollbackOnConflict=true (default), when lock conflict, data will rollback, so to execute the statement here repeatedly is useful and necessary. If you do not have more questions, please close this issue.

**Comment by hecyxy** [comment]
> As said before, if retryPolicyBranchRollbackOnConflict=true (default), when lock conflict, data will rollback, so to execute the statement here repeatedly is useful and necessary. If you do not have more questions, please close this issue.

the issue doesn't mean that it will cause dirty data.
when lock conflict exception occurs, executeAutoCommitFalse is totally useless, because lock exception occurs in commit action. you just need to retry the commit action. when lock conflict disappears, then it will execute successfully.

**Comment by ggndnn** [comment]
> > As said before, if retryPolicyBranchRollbackOnConflict=true (default), when lock conflict, data will rollback, so to execute the statement here repeatedly is useful and necessary. If you do not have more questions, please close this issue.
> 
> the issue doesn't mean that it will cause dirty data.
> when lock conflict exception occurs, executeAutoCommitFalse is totally useless, because lock exception occurs in commit action. you just need to retry the commit action. when lock conflict disappears, then it will execute successfully.

There is nothing to do with dirty data, never. When commit generated lock conflict exception, according to the default retry police, data will roll back, that means we should execute sql statement again next time. Maybe I didn't express it clearly, please check the code, especially `LockRetryPolicy`.

**Comment by hecyxy** [comment]
> > > As said before, if retryPolicyBranchRollbackOnConflict=true (default), when lock conflict, data will rollback, so to execute the statement here repeatedly is useful and necessary. If you do not have more questions, please close this issue.
> > 
> > 
> > the issue doesn't mean that it will cause dirty data.
> > when lock conflict exception occurs, executeAutoCommitFalse is totally useless, because lock exception occurs in commit action. you just need to retry the commit action. when lock conflict disappears, then it will execute successfully.
> 
> There is nothing to do with dirty data, never. When commit generated lock conflict exception, according to the default retry police, data will roll back, that means we should execute sql statement again next time. Maybe I didn't express it clearly, please check the code, especially `LockRetryPolicy`.

i understand your meaning. we just have different strategy. In seata's design, Lock retry policy doesn't work when lock conflict exception happens.because executeAutoCommitFalse must cause exception and then rollback.

**Comment by ggndnn** [comment]
> > > > As said before, if retryPolicyBranchRollbackOnConflict=true (default), when lock conflict, data will rollback, so to execute the statement here repeatedly is useful and necessary. If you do not have more questions, please close this issue.
> > > 
> > > 
> > > the issue doesn't mean that it will cause dirty data.
> > > when lock conflict exception occurs, executeAutoCommitFalse is totally useless, because lock exception occurs in commit action. you just need to retry the commit action. when lock conflict disappears, then it will execute successfully.
> > 
> > 
> > There is nothing to do with dirty data, never. When commit generated lock conflict exception, according to the default retry police, data will roll back, that means we should execute sql statement again next time. Maybe I didn't express it clearly, please check the code, especially `LockRetryPolicy`.
> 
> i understand your meaning. we just have different strategy. In seata's design, Lock retry policy doesn't work when lock conflict exception happens.because executeAutoCommitFalse must cause exception and then rollback.

Seata actually has two strategy, the default one, as said above, would release local X lock (by rollback) and quick fail when conflict, the other one, would try the best to get the global lock meanwhile holding the local X lock when conflict. We can't tell which one is better, it's dependent. If you are interested, we had a lock retry policy discussion #1469 before. I think, there are indeed something should be improved, but not like this issue, which should be closed. Thanks for your efforts.

**Comment by hecyxy** [comment]
> > > > > As said before, if retryPolicyBranchRollbackOnConflict=true (default), when lock conflict, data will rollback, so to execute the statement here repeatedly is useful and necessary. If you do not have more questions, please close this issue.
> > > > 
> > > > 
> > > > the issue doesn't mean that it will cause dirty data.
> > > > when lock conflict exception occurs, executeAutoCommitFalse is totally useless, because lock exception occurs in commit action. you just need to retry the commit action. when lock conflict disappears, then it will execute successfully.
> > > 
> > > 
> > > There is nothing to do with dirty data, never. When commit generated lock conflict exception, according to the default retry police, data will roll back, that means we should execute sql statement again next time. Maybe I didn't express it clearly, please check the code, especially `LockRetryPolicy`.
> > 
> > 
> > i understand your meaning. we just have different strategy. In seata's design, Lock retry policy doesn't work when lock conflict exception happens.because executeAutoCommitFalse must cause exception and then rollback.
> 
> Seata actually has two strategy, the default one, as said above, would release local X lock (by rollback) and quick fail when conflict, the other one, would try the best to get the global lock meanwhile holding the local X lock when conflict. We can't tell which one is better, it's dependent. If you are interested, we had a lock retry policy discussion #1469 before. I think, there are indeed something should be improved, but not like this issue, which should be closed. Thanks for your efforts.

thank your for your explanation!
