### ISSUE TITLE
seata团队好，我再发起方使用了 @GlobalTransactional  但是在业务方 RootContext.getXID() 获取不到xid，应该是上下文传递到其他微服务没成功，需要我们自己来解决吗？还是说有哪个配置不对

### ISSUE THREAD

**Issue by xiebin2015** [seata/seata#2999]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by wangliang181230** [comment]
需要引用spring-cloud-starter-alibaba-seata依赖。这个依赖里才有xid传递的功能。
seata-spring-boot-starter依赖，并没有传递功能。

**Comment by wangliang181230** [comment]
![图片](https://user-images.githubusercontent.com/1527893/89854369-5720db00-dbc6-11ea-8c24-d9000b5b569c.png)

**Comment by xiebin2015** [comment]
好的 解决了  谢谢
