### ISSUE TITLE
请问@GlobalTransactional是否支持嵌套，在调试过程中发现一个类A，下有两个 public的方法 m1、m2，m1方法调用了m2，@GlobalTransactional注解标识在m2上，GlobalTransactionalInterceptor拦截代理的访问为m1,而不是m2，导致获取不到注解对象，最终使分布式事务不生效

### ISSUE THREAD

**Issue by xiebin2015** [seata/seata#3000]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by wangliang181230** [comment]
这个是最觉的springAOP不生效的一个坑。
类内部调用时，内部被调用的方法，不会触发任何AOP。
多学习吧，兄弟。

**Comment by wangliang181230** [comment]
你应该要这样写。
`
@ Service
public class Service1 {

    @ Autowired
    private Service1 self;

    public void m1() {
        //this.m2(); // 这样写，不会触发AOP
        self.m2();
    }

    @ GlobalTransactional
    publiv void m2() {
    }

}
`

**Comment by xiebin2015** [comment]
明白了 ，感谢
