### ISSUE TITLE
seata性能疑问

### ISSUE THREAD

**Issue by xiebin2015** [seata/seata#3003]
seata团队好
  学习和运用了SeaTa分布式解决方案，有疑问如下
1、seata AT模式应用层基于SQL解析很好的实现了自动补偿，但是测试过程中执行一个sql，需要经历 before image,sql执行，after image， 写入undo log，再获取全局事务XID的时候还要和TC发生IO，多次IO性能耗损严重
2、全局锁的引入实现了隔离性，但同时带来了阻塞问题，降低并发性
基于此，seata相较于非事务处理 性能下降百分比大概是多少？
3、如果出现回滚，执行逆向sql，删除 undo log之后才释放 TC的全局锁，释放锁的时间更长

个人压测得到的结果数据很不好看，在同等环境下，不加事务吞吐量是加了事务的百倍以上，对seata的配置基本都是默认的配置，求正解，谢谢

**Comment by a364176773** [comment]
最后一句话我认为你并没有使用seata1.3的版本。
理论上是本地事务的五倍

**Comment by xiebin2015** [comment]
我确定用的是seata1.3的版本

**Comment by xiebin2015** [comment]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.0.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.3.0</version>
        </dependency>

**Comment by a364176773** [comment]
> 我确定用的是seata1.3的版本

我昨晚测了一下，50并发100请求下，并且是对同一个数据进行update，平均400ms左右。

**Comment by a364176773** [comment]
1.4测了一下，redis模式70ms，db90ms，200并发1000请求
