### ISSUE TITLE
saga 模式如何更好的支持springcloud + feign 调用模式（建议作者把文档和入门demo做得更规范一点）

### ISSUE THREAD

**Issue by averyzhujinbo** [seata/seata#3011]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
自己按照官方saga demo改造了一下代码，支持springcloud + feign的调用方式，事务发起方提示没有undo_log表，官方文档里面没有说要建undo_log表啊？(只好手动执行了一下undo_log 表脚本)
查看了一下 branch_table 表数据发现 branch_type = AT
saga 模式与 at模式到底有什么关系？大佬能否回到一下？还是说我自己集成错误？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

配置代码：
1.saga分布式事务发起方增加配置类
@Slf4j
@Configuration
public class InitProcessCtrlStateMachineEngine {
    @Resource
    private DataSource dataSource;

    @Bean("stateMachineEngine")
    public ProcessCtrlStateMachineEngine getProcessCtrlStateMachineEngine(){
        ProcessCtrlStateMachineEngine processCtrlStateMachineEngine = new ProcessCtrlStateMachineEngine();
        processCtrlStateMachineEngine.setStateMachineConfig(getDbStateMachineConfig());
        return processCtrlStateMachineEngine;

    }

    @Bean("dbStateMachineConfig")
    public DbStateMachineConfig getDbStateMachineConfig(){
        DbStateMachineConfig dbStateMachineConfig = new DbStateMachineConfig();
        dbStateMachineConfig.setDataSource(dataSource);
        org.springframework.core.io.Resource[] resources = null;
        try {
            PathMatchingResourcePatternResolver pathMatchingResourcePatternResolver = new PathMatchingResourcePatternResolver();
            resources = pathMatchingResourcePatternResolver.getResources("statelang/*.json");
        }catch (IOException ioe){
            log.error("load json file error the message = "+ioe.getMessage());
            ioe.printStackTrace();
        }
        dbStateMachineConfig.setResources(resources);
        dbStateMachineConfig.setEnableAsync(true);
        dbStateMachineConfig.setThreadPoolExecutor(initThreadPoolExecutorFactoryBean());
        dbStateMachineConfig.setApplicationId("seata-txsaga-business");
        dbStateMachineConfig.setTxServiceGroup("my_test_tx_group");
        return dbStateMachineConfig;
    }

    @Bean("threadExecutor")
    public ThreadPoolExecutor initThreadPoolExecutorFactoryBean(){
        ThreadPoolExecutorFactoryBean threadPoolExecutorFactoryBean = new ThreadPoolExecutorFactoryBean();
        threadPoolExecutorFactoryBean.setThreadNamePrefix("SAGA_ASYNC_EXE_");
        threadPoolExecutorFactoryBean.setCorePoolSize(1);
        threadPoolExecutorFactoryBean.setMaxPoolSize(20);
        return (ThreadPoolExecutor)threadPoolExecutorFactoryBean.getObject();
    }

    @Bean
    public StateMachineEngineHolder initStateMachineEngineHolder(){
        StateMachineEngineHolder stateMachineEngineHolder = new StateMachineEngineHolder();
        stateMachineEngineHolder.setStateMachineEngine(getProcessCtrlStateMachineEngine());
        return  stateMachineEngineHolder;
    }
}

发起方调用saga ：
    public boolean reduceInventoryAndBalance(Long accountId,Integer amount,Integer count,String goodsCode){
        StateMachineEngine stateMachineEngine = (StateMachineEngine)MyApplicationContextAware.getApplicationContext().getBean("stateMachineEngine");
        Map<String, Object> startParams = new HashMap<>(3);
        String businessKey = String.valueOf(System.currentTimeMillis());
        startParams.put("businessKey", businessKey);
        startParams.put("accountId", accountId);
        startParams.put("count", count);
        startParams.put("goodsCode", goodsCode);
        startParams.put("amount", amount);
        StateMachineInstance inst = stateMachineEngine.startWithBusinessKey("reduceInventoryAndBalance", null, businessKey, startParams);
        log.info("saga execute state={} xid={}",inst.getStatus(),inst.getId());
        return true;
    }

**Comment by long187** [comment]
https://github.com/seata/seata/pull/2838

**Comment by wlcqy** [comment]
大佬 问题解决了吗
