### ISSUE TITLE
使用yml配置时候会报找不到globalTransactionScanner ，conf则不会

### ISSUE THREAD

**Issue by LiuRuiPeng2333** [seata/seata#3013]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
 ### error
![image](https://user-images.githubusercontent.com/44105320/90092865-bc0e3980-dd5c-11ea-8bef-ffa078dde141.png)

### Ⅰ. yml Description
seata:
  enabled: true # 1.0新特性，需要依赖seata-spring-boot-starter,默认为true
  tx-service-group: geekplus_tx_group
  config:
  transport:
    type: TCP #default value is TCP
    server: NIO #default value is NIO
    heartbeat: true #enable heartbeat
    enable-client-batch-send-request: true
    serialization: seata
    compressor: none
    shutdown:
      wait: 3 #when destroy server, wait seconds

  registry:
    type: redis
    redis:
      serverAddr: 192.168.11.211:6379
      db: 1
      password: 
      cluster: Seata-Service
    service:
      vgroup-mapping: my_test_tx_group
      disable-global-transaction: false
      disableGlobalTransaction: false

  client:
    support:
      spring:
        datasource-autoproxy: false

### Ⅱ. java bean

      @Bean
    public GlobalTransactionScanner globalTransactionScanner() {
        return new GlobalTransactionScanner(applicationId, "my_test_tx_group");
    }

### Ⅲ. pom 
 <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>1.3.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <version>2.1.0.RELEASE</version>
            <exclusions>
                <exclusion>
                    <artifactId>seata-all</artifactId>
                    <groupId>io.seata</groupId>
                </exclusion>
            </exclusions>
        </dependency>

### Ⅵ. Environment:

- JDK version :1.8
-seata Server :1.3

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/3026
整合上问题看着
