### ISSUE TITLE
 yml配置注册redis的时候，报类型转换异常，没有读取到redis的db属性

### ISSUE THREAD

**Issue by LiuRuiPeng2333** [seata/seata#3015]
### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/44105320/90111732-a3644a80-dd81-11ea-9841-ecc2fb710e56.png)

### 
![image](https://user-images.githubusercontent.com/44105320/90112325-68164b80-dd82-11ea-8270-17c262cf80b8.png)

### Ⅱ. yml

![image](https://user-images.githubusercontent.com/44105320/90111836-c68efa00-dd81-11ea-864b-3212d5c516b0.png)

- JDK version : 1.8
- Seata Server :1.3

**Comment by a364176773** [comment]
图挂了，可以直接贴异常堆栈之类的日志吗

**Comment by xingfudeshi** [comment]
What is the value of registry.redis.db?@LiuRuiPeng2333
