### ISSUE TITLE
客户端注册成功了，也能全局回滚，但是fileListener一直在报error

### ISSUE THREAD

**Issue by LiuRuiPeng2333** [seata/seata#3020]
![image](https://user-images.githubusercontent.com/44105320/90211225-b9761780-de22-11ea-897e-719c1b362d2b.png)

**Comment by a364176773** [comment]
1.3的bug，1.4将会修复他，你可以先使用file以外的配置中心，或者把订阅对应的dataid配置上，只要value不为null，就不会出现这个日志
