### ISSUE TITLE
建议别做1.4.0版本了的新功能，问题这么多先在1.3.0做小版本迭代把问题改完。

### ISSUE THREAD

**Issue by cay914** [seata/seata#3021]
建议别做1.4.0版本了的新功能，问题这么多先在1.3.0做小版本迭代把问题改完。
先把产品做稳定吧，感觉从1.3.0到1.4.0夸度有点大。每个版本都有问题，问题越滚越多。
还不如先把问题先解决了再做新版本。我们要的是稳定啊，这样显得seata真的不成熟。
每次都掉坑里，心累
建议如1.3.1

**Comment by 81519434** [comment]
什么坑，能列举一下吗？
另外哪里可以看到1.4预发布的内容？

**Comment by l81893521** [comment]
Thanks for your advise, bug can you report the real problem?

**Comment by a364176773** [comment]
建议先看教程哦，亲～

**Comment by sabersword** [comment]
@81519434 你好,感谢你提交的多主键PR,我确实需要这个功能,非常感谢 #2398 
有个小问题想讨论一下,你在PR里提到不支持修改主键,我测试过update SQL修改主键能执行且不会报错,全局事务正常结束.
如果遇到全局回滚的场景,在only-care-update-columns=false的配置下分支事务也正常回滚,但实际上数据并没有回滚.
是不是考虑加个预防机制,遇到update SQL修改主键报错?

**Comment by longting** [comment]
一年半的项目1000次commit ，严重不足！

**Comment by wangliang181230** [comment]
为了控制代码质量，一个PR必须2～3人通过才能合并。commit少也是没办法的。

**Comment by wangliang181230** [comment]
为了控制代码质量，一个PR必须2～3人通过才能合并。commit少也是没办法的。

**Comment by wangliang181230** [comment]
为了控制代码质量，一个PR必须2～3人通过才能合并。commit少也是没办法的。

**Comment by 81519434** [comment]
> @81519434 你好,感谢你提交的多主键PR,我确实需要这个功能,非常感谢 #2398
> 有个小问题想讨论一下,你在PR里提到不支持修改主键,我测试过update SQL修改主键能执行且不会报错,全局事务正常结束.
> 如果遇到全局回滚的场景,在only-care-update-columns=false的配置下分支事务也正常回滚,但实际上数据并没有回滚.
> 是不是考虑加个预防机制,遇到update SQL修改主键报错?

刚刚开始 是写了，后来去掉了，按道理是需要加上。 但是这个属于是破坏性升级，我不知道@a364176773  @l81893521 是否同意这样的改动，如果同意我可以提pr

**Comment by a364176773** [comment]
> > @81519434 你好,感谢你提交的多主键PR,我确实需要这个功能,非常感谢 #2398
> > 有个小问题想讨论一下,你在PR里提到不支持修改主键,我测试过update SQL修改主键能执行且不会报错,全局事务正常结束.
> > 如果遇到全局回滚的场景,在only-care-update-columns=false的配置下分支事务也正常回滚,但实际上数据并没有回滚.
> > 是不是考虑加个预防机制,遇到update SQL修改主键报错?
> 
> 刚刚开始 是写了，后来去掉了，按道理是需要加上。 但是这个属于是破坏性升级，我不知道@a364176773 @l81893521 是否同意这样的改动，如果同意我可以提pr

请问是在回滚前修改了主键,还是什么意思?目前讨论的是加预防机制还是做到允许修改主键?

**Comment by sabersword** [comment]
> > > @81519434 你好,感谢你提交的多主键PR,我确实需要这个功能,非常感谢 #2398
> > > 有个小问题想讨论一下,你在PR里提到不支持修改主键,我测试过update SQL修改主键能执行且不会报错,全局事务正常结束.
> > > 如果遇到全局回滚的场景,在only-care-update-columns=false的配置下分支事务也正常回滚,但实际上数据并没有回滚.
> > > 是不是考虑加个预防机制,遇到update SQL修改主键报错?
> > 
> > 
> > 刚刚开始 是写了，后来去掉了，按道理是需要加上。 但是这个属于是破坏性升级，我不知道@a364176773 @l81893521 是否同意这样的改动，如果同意我可以提pr
> 
> 请问是在回滚前修改了主键,还是什么意思?目前讨论的是加预防机制还是做到允许修改主键?

如果一个分支事务的SQL在一阶段修改了某一行的主键,在二阶段branch rollback success, 但实际上这一行数据并没有回滚.
我们考虑是不是一阶段遇到修改主键的SQL就报错, 不让分支事务注册, 来保证事务一致性

**Comment by 81519434** [comment]
@a364176773 你可以看下我刚刚提的这个bug #3066

**Comment by l81893521** [comment]
I will close the issue. we can talk in the issues that include the real problem.
