### ISSUE TITLE
seata+mybatis-plus，数据库插入数据，针对时间字段localdatetime 报如下错误

### ISSUE THREAD

**Issue by yuanchaogithub** [seata/seata#3023]
org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='workTime', mode=IN, javaType=class java.time.LocalDateTime, jdbcType=TIME, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #7 with JdbcType TIME . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: Error

**Comment by a364176773** [comment]
https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo

参考

**Comment by FerociousRadish** [comment]
请问是怎么解决的
