### ISSUE TITLE
服务器启动只连接127.0.0.1:8091

### ISSUE THREAD

**Issue by ywscn** [seata/seata#3024]
我使用的1.3.0的版本，目前seata已经注册到了nacos上，我在配置文件中配置了
grouplist:
 default: 192.168.31.224:8091(我本地的ip)
但是在服务启动的时候不会加载我指定的ip，只加载127.0.0.1的ip

**Comment by wujincheng2333** [comment]
service.vgroup-mapping 也要指定（nacos配置文件里面）。并且 这个名称要跟客户端分组名称一致 (客户端配置)

**Comment by ywscn** [comment]
> service.vgroup-mapping也要指定（nacos配置文件里面）。和这个名称要跟客户端分组名称一致（客户端配置）

这个我配置了
NettyPool create channel to transactionRole:TMROLE,address:127.0.0.1:8091,msg:< RegisterTMRequest{applicationId='daiyu-order', transactionServiceGroup='my_test_tx_group'} >
这是启动打印的

**Comment by wujincheng2333** [comment]
> my_test_tx_group

my_test_tx_group这个是默认的，你的服务名称也是这个？seata.tx-service-group或spring.cloud.alibaba.seata.tx-service-group 这两个配置的服务组要跟你的nacos上一样，默认情况下是appName+"-seata-service-group"  ,所以你的事务组是：daiyu-order-seata-service-group，但你nacos上的配置只是默认的my_test_tx_group

**Comment by ywscn** [comment]
> > my_test_tx_group
> 
> my_test_tx_group这个是替换的，你的服务名称也是这个？seata.tx-service-group或spring.cloud.alibaba.seata.tx-service-group这两个配置的服务组要跟你的nacos上一样，情况下是appName +“-seata-service-group”，所以你的事务组是：daiyu-order-seata-service-group，但你nacos上的配置只是很小的my_test_tx_group

service.vgroupMapping.my_test_tx_group     这个是nacos的配置
seata：
   tx-service-group: my_test_tx_group    这个是代码配置文件的配置

**Comment by ywscn** [comment]
> > my_test_tx_group
> 
> my_test_tx_group这个是替换的，你的服务名称也是这个？seata.tx-service-group或spring.cloud.alibaba.seata.tx-service-group这两个配置的服务组要跟你的nacos上一样，情况下是appName +“-seata-service-group”，所以你的事务组是：daiyu-order-seata-service-group，但你nacos上的配置只是很小的my_test_tx_group

现在报no available service 'null' found, please make sure registry config correct这个错
我看了分组和名字都是一样的，seata也注册到nacos了，也在同一个注册中心

**Comment by a364176773** [comment]
https://www.bilibili.com/video/BV1Cf4y1X7vR
https://www.bilibili.com/video/BV12Q4y1A7Nt
这两个教程看一遍还不行,那就看十遍

**Comment by wujincheng2333** [comment]
> > > my_test_tx_group
> > 
> > 
> > my_test_tx_group这个是替换的，你的服务名称也是这个？seata.tx-service-group或spring.cloud.alibaba.seata.tx-service-group这两个配置的服务组要跟你的nacos上一样，情况下是appName +“-seata-service-group”，所以你的事务组是：daiyu-order-seata-service-group，但你nacos上的配置只是很小的my_test_tx_group
> 
> 现在报no available service 'null' found, please make sure registry config correct这个错
> 我看了分组和名字都是一样的，seata也注册到nacos了，也在同一个注册中心

是不是订阅nacos配置失败了，导致没有拉取线上的配置，nacos线上有分组配置，也要对应。就是你提交到nacos时的分组

**Comment by ywscn** [comment]
> > > > my_test_tx_group
> > > 
> > > 
> > > my_test_tx_group这个是替换的，你的服务名称也是这个？seata.tx-service-group或spring.cloud.alibaba.seata.tx-service-group这两个配置的服务组要跟你的nacos上一样，情况下是appName +“-seata-service-group”，所以你的事务组是：daiyu-order-seata-service-group，但你nacos上的配置只是很小的my_test_tx_group
> > 
> > 
> > 现在报找不到可用的服务'null'，请确保注册表配置正确。这个错
> > 我看了分组和名字都是一样的，seata也注册到nacos了，同时同一个注册中心
> 
> 是不是订阅nacos配置失败了，导致没有拉取线上的配置，nacos线上有分组配置，也要对应。就是你提交到nacos时的分组

分组是对的，邪门了，本地好使，提交到测试线就不行了

**Comment by zr9883** [comment]
配置这个就好了  seata.service.grouplist.seata-server=106.53.xxx.xxx:8091

**Comment by zr9883** [comment]
seata.service.grouplist.seata-server=xxx.xxx.xxx.xxx:8091

**Comment by JuxerH** [comment]
> seata.service.grouplist.seata-server=xxx.xxx.xxx.xxx:8091

这个是正解
