### ISSUE TITLE
store.mode=redis时，如果单个分支事务里面对多条数据操作，只能释放两条锁

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#3029]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
store.mode=redis时，如果单个分支事务里面对多条数据操作，只能释放两条锁

### Ⅱ. Describe what happened
当我尝试用store.mode=redis时，进行了一次批量插入100条数据，然后当事务完成的时候，在redis执行`key *`还有98条锁+一条SEATA_LOCK_XID_192.168.80.133:8091:38366418866016256。
其中在判断`GlobalSession#commit`判断`shouldCommit`的时候调用过一次，然后在branchCommit的时候的`branchSession#unlock`有调用过一次`RedisLocker#releaseLock`删除了一条。一共删除了两条。

看一下主要的代码，主要的分析见代码注释
```
@Override
public boolean releaseLock(String xid, List<Long> branchIds) {
    if (CollectionUtils.isEmpty(branchIds)) {
        // no lock
        return true;
    }
    try (Jedis jedis = JedisPooledFactory.getJedisInstance()) {
        String lockListKey = getXidLockKey(xid);
        // 获取xid对应的所有lock_key
        // 并且转换成一个Set，这个Set的设置让会删除那条锁变得不确定
        Set<String> keys = lRange(jedis, lockListKey);
        if (CollectionUtils.isNotEmpty(keys)) {
            List<String> delKeys = new ArrayList<>();
            // 从redis获取lock_keys对应的数据
            List<String> values = jedis.mget(keys.toArray(new String[0]));
            // 假如这里有100个values
            // 然后branchIds有一个元素，正常的删除分支事务的话，branchIds就是一个元素(假设是 38359493382246400 )
            for (String value : values) {
                Iterator<Long> it = branchIds.iterator();
                while (it.hasNext()) {
                    Long branchId = it.next();
                    LockDO lock = JSON.parseObject(value, LockDO.class);
                    if (lock != null && Objects.equals(lock.getBranchId(), branchId)) {
                        delKeys.add(getLockKey(lock.getRowKey()));
                        // 最主要的问题在这里
                        // 当拿到第一个lockDO，并且对应的branchId为 38359493382246400 ，对应上了branchId的时候
                        // 这里就调用了it.remove()了，导致了branchIds列表变成了一个空列表
                        // 再然后的话，后续的lock无论是否为 38359493382246400 ，都不会被删除
                        it.remove();
                        break;
                    }
                }
            }
            if (CollectionUtils.isNotEmpty(delKeys)) {
                Pipeline pipeline = jedis.pipelined();
                pipeline.del(delKeys.toArray(new String[0]));
                for (String key : delKeys) {
                    pipeline.lrem(lockListKey, 0, key);
                }
                pipeline.sync();
            }
        }
        return true;
    }
}
```

### Ⅲ. Describe what you expected to happen

删除对应的it.remove()，让每次删除的时候可以删除全部的lock。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

store.mode=redis，然后进行一次批量操作即可，查看redis的锁释放情况。

### Ⅴ. Anything else we need to know?
none

### Ⅵ. Environment:

- JDK version :  jdk1.8.0_261
- OS : Ubuntu18.04 LTS
- Others: seata 1.4.0-SNAPSHOT

**Comment by a364176773** [comment]
1.4修复，你可以用钉钉群里的快照版，或者直接通过目前最新的develop打包使用------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;caohdgege&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月16日(星期天) 晚上9:05
收件人:&nbsp;&quot;seata/seata&quot;<seata@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[seata/seata] store.mode=redis时，如果单个分支事务里面对多条数据操作，只能释放两条锁 (#3029)

**Comment by caohdgege** [comment]
最近的快照包已经修复了吗？我这个测试的时候，就是用的当前的develop的分支的代码，并且是今晚八点才同步过的。

**Comment by a364176773** [comment]
我似乎明白你的意思了，现在有点晚了，明天我们可以交流下，方便的话加一下钉钉群------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;caohdgege&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月16日(星期天) 晚上11:14
收件人:&nbsp;&quot;seata/seata&quot;<seata@noreply.github.com&gt;;
抄送:&nbsp;&quot;FUNKYE&quot;<364176773@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] store.mode=redis时，如果单个分支事务里面对多条数据操作，只能释放两条锁 (#3029)

**Comment by caohdgege** [comment]
OK，我刚刚扫码加了，明天可以在钉钉群沟通一下。

**Comment by a364176773** [comment]
感谢你发现这个问题
