### ISSUE TITLE
can not rollback the local transaction

### ISSUE THREAD

**Issue by XuyangJava2E** [seata/seata#303]
when i used the dataSourceProxy of fescar , the global transaction  can commit and rollback correctly;
But the lcoal transaction can not rollback successfully

eg:
web
`
@Controller
public class OrderController {

    @Autowired
    private OrderService orderService;

    @GetMapping("/doOrder")
    @ResponseBody
    public String doOrder() {
        orderService.createOrder();
        return "success";
    }
}
`
service
`
@Transactional
public class OrderServiceImpl implements OrderService {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Override
    public void createOrder() {
        jdbcTemplate.update("INSERT INTO order_tbl(`user_id`, `commodity_code`, `count`, `money`) VALUES (NULL, NULL, 0, 0);");
       throw new RuntimeException("1");
    }

}
`
ask the url: http://localhost:8080/doOrder ;
can not rollback the transaction;

if i use the DataSource of Druid，this problem will not arise;

**Comment by tankilo** [comment]
use com.alibaba.fescar.spring.annotation.GlobalTransactional instead of org.springframework.transaction.annotation.Transactional

**Comment by XuyangJava2E** [comment]
> use com.alibaba.fescar.spring.annotation.GlobalTransactional instead of org.springframework.transaction.annotation.Transactional

好的，谢谢！
但是我这里依旧有一个问题：
GlobalTransactionScanner其实是利用了Spring的postProcessAfterInitialization的特性，那么在扫描是是否可以改成先扫描类注解呢？业务中有一个问题是无法预知哪个方法会在将来出现在分布式事务中，所以我们会在所有的方法都会加上@GlobalTransactional的注解，那么是否可以将@GlobalTransactional改成和@Transactional一样呢？这样可以省去开发的一些步骤

**Comment by tankilo** [comment]
> > use com.alibaba.fescar.spring.annotation.GlobalTransactional instead of org.springframework.transaction.annotation.Transactional
> 
> 好的，谢谢！
> 但是我这里依旧有一个问题：
> GlobalTransactionScanner其实是利用了Spring的postProcessAfterInitialization的特性，那么在扫描时是否可以改成先扫描类注解呢？业务中有一个问题是无法预知哪个方法会在将来出现在分布式事务中，所以我们会在所有的方法都会加上@GlobalTransactional的注解，那么是否可以将@GlobalTransactional改成和@transactional一样呢？这样可以省去开发的一些步骤


在这点上我很同意你的意见。 
因为fescar允许其他全局事务在一阶段提交本地事务，即使是一个单条sql的本地事务修改，也需要加@GlobalTransactional注解，都需要走fescar。
目前的demo没有考虑到实际的业务情况，在被调的dubbo服务上都没加上@GlobalTransactional的注解，所以才没暴露出嵌套事务时候的bug。
