### ISSUE TITLE
升级到1.3.0后Druid手动代理数据源出问题

### ISSUE THREAD

**Issue by suifengerquaa** [seata/seata#3033]
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.rm.datasource.DataSourceProxy]: Factory method 'dataSource' threw exception; nested exception is io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.util.DbTypeParser

**Comment by well-John** [comment]
在meta-inf.services目录下增加io.seata.sqlparser.util.DbTypeParser文件指定DbTypeParser即可
