### ISSUE TITLE
关于docker指定seata配置文件registry报错问题，版本1.3.0

### ISSUE THREAD

**Issue by wxywizard** [seata/seata#3038]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用docker启动seate-server指定配置文佳启动一直报错 config type can not be null
我的启动命令
docker run --name seate-server -p 8091:8091 -e SEATA_IP=172.20.32.41 -e SEATA_PORT=8091 -e SEATA_CONFIG_NAME=file:/opt/wxy/software/seata-config/registry -v /User/seata/config:/opt/wxy/software/seata-config seataio/seata-server
并且/opt/wxy/software/seata-config/registry.conf 这个文件我的config.type配置的是nacos
### 报错信息
Exception in thread "main" io.seata.common.exception.NotSupportYetException: config type can not be null
        at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:106)
        at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90)
        at io.seata.server.ParameterParser.init(ParameterParser.java:87)
        at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
        at io.seata.server.Server.main(Server.java:72)

### Ⅵ. Environment:

- JDK version :1.8
- OS :centos 7
- Others:

**Comment by likang19** [comment]
请问！大姥怎么解决的啊

**Comment by lanzhenkai** [comment]
遇到了同样问题

**Comment by lanzhenkai** [comment]
找到问题了 因为挂载目录没权限的原因导致
问题复现：
docker run --name seata-server \
        -p 8091:8091 \
        -e SEATA_CONFIG_NAME=file:/root/seata-config/registry \
        -v /data/seata-server/conf:/root/seata-config  \
		--privileged=true \
        seataio/seata-server:1.3.0 \
启动日志失败 报错：
Exception in thread "main" io.seata.common.exception.NotSupportYetException: config type can not be null

问题思考： 大概率是配置文件  -v 没有同步成功导致读取文件失败。
问题排查：
删除掉环境变量 SEATA_CONFIG_NAME  重新启动，让容器以默认配置file方式启动
docker run --name seata-server \
        -p 8091:8091 \
        -v /data/seata-server/conf:/root/seata-config  \
		--privileged=true \
        seataio/seata-server:1.3.0
容器启动成功。
进入容器查看  -v目录是否映射成功：
docker exec -it seata-server sh
进入挂载目录：
$ cd /root/seata-config
查看目录：
~/seata-config # ls
ls: can't open '.': Permission denied
提示当前目录无权限
问题定位成功。

解决方法：
①：给当前容器权限 增加启动参数：	--privileged=true 
完整启动命令：
docker run --name seata-server \
        -p 8091:8091 \
        -e SEATA_CONFIG_NAME=file:/root/seata-config/registry \
        -v /data/seata-server/conf:/root/seata-config  \
		--privileged=true \
        seataio/seata-server:1.3.0\

②： 
自定义Dockerfile  FROM  seataio/seata-server:1.3.0
在Dockerfile  中添加新建目录命令 RUN mkdir -p /root/seata-config 
复制 配置文件到 /root/seata-config  中
增加用户读写权限
执行docker build 构建自己的镜像 然后启动

**Comment by wxywizard** [comment]
出现类似问题，请排查挂载目录。

**Comment by Melodykuang** [comment]
怎么解决啊
################docker-compose.yml start#################

version: '3.8'
services:
  seata:
    image: seataio/seata-server:1.3.0
    container_name: seata
    privileged: true
    ports:
      - "8091:8091"
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./conf:/root/seata-config
      - ./seata_logs:/root/logs
################docker-compose.yml end#################

################registry start#################
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "192.168.149.128:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }
  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "192.168.149.128:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
  consul {
    serverAddr = "127.0.0.1:8500"
  }
  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }
  etcd3 {
    serverAddr = "http://localhost:2379"
  }
  file {
    name = "file.conf"
  }
}
################registry end#################

启动报错：
seata    | 2020-09-08 12:59:40.445  INFO --- [           main] io.seata.server.Server                   : The server is running in container.
seata    | Exception in thread "main" io.seata.common.exception.NotSupportYetException: config type can not be null
seata    |      at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:106)
seata    |      at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:90)
seata    |      at io.seata.server.ParameterParser.init(ParameterParser.java:87)
seata    |      at io.seata.server.ParameterParser.<init>(ParameterParser.java:60)
seata    |      at io.seata.server.Server.main(Server.java:72)
seata exited with code 1

**Comment by aakejiang** [comment]
@Melodykuang 
- SEATA_CONFIG_NAME=file:/root/seata-config/registry
确保 /root/seata-config/registry.conf 是存在的，后缀是.conf

**Comment by Melodykuang** [comment]
@aakejiang 还是不可以啊

**Comment by Melodykuang** [comment]
@aakejiang 大哥方便发一个文件吗？937146062@qq.com

**Comment by Melodykuang** [comment]
@lanzhenkai 大佬怎么解决的 @wxywizard

**Comment by dshengping** [comment]
有解决这个问题？

**Comment by xiajipeng** [comment]
我看了权限没问题, 文件也存在, 命令也没有问题, 各种方案试了一天还是报这个错
