### ISSUE TITLE
TM能不能对commit/rollback结果进行处理

### ISSUE THREAD

**Issue by wugangbao** [seata/seata#3041]
真心求教，实际交易场景中，TM需要管理交易状态，该状态取决于RM的commit/rollback结果，目前没有找到好的实现办法。
如回滚失败需要先记为交易未知，重试后回滚成功需要记为交易失败。
FailureHandler能够解决第一个问题，但是无法解决第二个问题。
用Hook做好像也不太合适，求指点

**Comment by a364176773** [comment]
能描述的清楚一些吗？问题二我也不知道是那个
