### ISSUE TITLE
Seata 1.3.0 不支持consul集群配置

### ISSUE THREAD

**Issue by daoxincc** [seata/seata#3047]
io.seata.discovery.registry.consul:172行 未对多地址做解析处理

**Comment by a364176773** [comment]
Can you help Seata solve this problem

**Comment by ztelur** [comment]
plz assign to me @a364176773

**Comment by ztelur** [comment]
目前consul注册中心不支持多地址。底层使用的ecwid ConsulClient不支持多ip地址，所以这个现阶段估计很难处理。Spring Cloud Discovery Consul 也是只支持单地址。
