### ISSUE TITLE
DeleteExecutor should build "after image" according to the DB

### ISSUE THREAD

**Issue by sabersword** [seata/seata#3048]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
DeleteExecutor build an empty "after image". 
In some scenarios,  SQL "delete from account_tbl where status =0 limit 1", there are serveral "status=0" records, but  I  want to delete one of them.
When a global rollback happens,seata would consider it as "dirty write" , and the rollback fails.

### Ⅲ. Describe what you expected to happen

DeleteExecutor should build "after image" according to the DB

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win10

**Comment by a364176773** [comment]
I'll take care of it

**Comment by caohdgege** [comment]
之前我针对update问的时候，即构建beforeImage的时候忽略了limit参数，给的回答似乎是limit的行为是不确定的，所以在构建镜像的时候忽略了它，看你这里的修改，是把limit参数加上了？
那如果可以加上limit的话，是否update那边可以一并修改？
