### ISSUE TITLE
seata tcc 模式中 try 阶段没有看到框架中提到的lock?

### ISSUE THREAD

**Issue by averyzhujinbo** [seata/seata#3057]
seata 1.3 jdk 1.8   seata tcc 模式中没有看到官方文档中提到的共享数据锁，这部分处理需要使用seata 框架的技术人员自己处理共享数据一致性问题是这样吗？

**Comment by wangliang181230** [comment]
@GlobalLock + select for update

**Comment by averyzhujinbo** [comment]
尝试过 at 模式加锁 使用 @GlobalLock + select for update 是可以的，tcc 模式尝试过在try 方法，commit 方法，cancel 方法上没有起作用。具体怎么用可以说明一下吗？

**Comment by wangliang181230** [comment]
先问下，你是什么场景，为什么TCC里要用共享数据锁？
TCC的原理在于预留资源，二阶段确认预留资源或回滚预留资源，这个应该是不需要使用分布式锁的。

**Comment by wangliang181230** [comment]
> 
> 
> 尝试过 at 模式加锁 使用 @GlobalLock + select for update 是可以的，tcc 模式尝试过在try 方法，commit 方法，cancel 方法上没有起作用。具体怎么用可以说明一下吗？

@GlobalLock + select for update的作用是防止AT事务正在操作的数据被其他地方脏读写，所以你单单用在TCC上是没用的。

**Comment by averyzhujinbo** [comment]
比如就拿官方的例子，个人账户，去买东西下订单，扣库存这个业务。非并发环境没有问题，可以正常提交事务，遇到异常可以正常回滚。但是在并发环境下，比如模拟20个用户同时下订单，就会出问题。系统中确实产生了20笔订单，但是余额只扣了4次，库存只扣了5次。数据一致性出了问题。几个服务没有出现任何执行异常，不知什么原因。

**Comment by wangliang181230** [comment]
不可能的，肯定是你自己的代码问题。

**Comment by wangliang181230** [comment]
不可能的，肯定是你自己的代码问题。

**Comment by wangliang181230** [comment]
你的sql发一下看看。

**Comment by averyzhujinbo** [comment]
调用方：
 @Override
    @GlobalTransactional(name = "tccBusinessBuyGodds",timeoutMills = 20000)
    public Boolean buyGoods(Long accountId,String goodsCode, Integer quantity, Integer amount) {
        log.info("==========>开始执行seata 全局事务，事务id={}", RootContext.getXID());

        //支付金额
        amount = amount * quantity;
        remoteTxTccAccountService.payMonery(accountId,amount);
        //创建订单
        boolean orderResult = remoteTxTccOrderService.createOrder(goodsCode,quantity,amount);
        //扣减库存
        boolean storageResult = remoteTxTccStorageService.deduct(goodsCode,quantity);


        log.info("=========>结束执行seata 全局事务，事务id={}", RootContext.getXID());
       return Boolean.TRUE;
    }


表结构sql：
CREATE TABLE `t_seata_tcc_account` (
  `account_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `balance` int(11) DEFAULT '0' COMMENT '账户余额',
  `frozen_balance` int(11) DEFAULT '0' COMMENT '冻结金额',
  PRIMARY KEY (`account_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='会员账户表';
被调用方：账户扣减金额,TCC接口

@LocalTCC
public interface TxTccAccountService extends IService<TxTccAccount> {

    @TwoPhaseBusinessAction(name = "TxTccAccountService", commitMethod = "commit", rollbackMethod = "cancel")
    public boolean prepare(BusinessActionContext context,
                           @BusinessActionContextParameter(paramName = "accountId") Long accountId,
                           @BusinessActionContextParameter(paramName = "ammount") Integer ammount);

    public boolean commit(BusinessActionContext context);

    public boolean cancel(BusinessActionContext context);
}

被调用方：账户扣减金额,TCC接口实现类：
@Slf4j
@Service
public class TxTccAccountImpl extends ServiceImpl<TxTccAccountMapper, TxTccAccount> implements TxTccAccountService {
    @Resource
    private TxTccAccountMapper txTccAccountMapper;

    @Override
    @Transactional(rollbackFor = Exception.class)
    public boolean prepare(BusinessActionContext context, Long accountId, Integer amount) {
        QueryWrapper<TxTccAccount> wrapper = new QueryWrapper<>();
        wrapper.setEntity(new TxTccAccount().setAccountId(accountId));
        wrapper.last(" for update");
        TxTccAccount txTccAccount = txTccAccountMapper.selectOne(wrapper);
        if(amount > txTccAccount.getBalance()){
            throw new RuntimeException("余额不足!");
        }
        txTccAccount.setFrozenBalance(amount);
        txTccAccountMapper.updateById(txTccAccount);
        log.info("TxTccAccountImpl 分支事务已就绪,xid={}",context.getXid());
        return true;
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public boolean commit(BusinessActionContext context) {
        Long accountId = Long.parseLong(context.getActionContext("accountId").toString());
        QueryWrapper<TxTccAccount> wrapper = new QueryWrapper<>();
        wrapper.setEntity(new TxTccAccount().setAccountId(accountId));
        wrapper.last(" for update");
        TxTccAccount txTccAccount = txTccAccountMapper.selectOne(wrapper);
        txTccAccount.setBalance(txTccAccount.getBalance() - txTccAccount.getFrozenBalance());
        txTccAccount.setFrozenBalance(0);
        txTccAccountMapper.updateById(txTccAccount);
        log.info("TxTccAccountImpl 分支事务已提交,xid={}",context.getXid());
        return true;
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public boolean cancel(BusinessActionContext context) {
        Long accountId = Long.parseLong(context.getActionContext("accountId").toString());
        QueryWrapper<TxTccAccount> wrapper = new QueryWrapper<>();
        wrapper.setEntity(new TxTccAccount().setAccountId(accountId));
        wrapper.last(" for update");
        TxTccAccount txTccAccount = txTccAccountMapper.selectOne(wrapper);
        txTccAccount.setFrozenBalance(0);
        txTccAccountMapper.updateById(txTccAccount);
        log.info("TxTccAccountImpl 分支事务已回滚,xid={}",context.getXid());
        return true;
    }
}
其他几个服务类似我就不贴代码了，这样写有问题吗？

**Comment by wangliang181230** [comment]
为什么不直接使用`update t_seata_tcc_account set balance = balance - ?, frozen_balance = frozen_balance + ? where balance >= ?`，非要先把数据查出来再操作，浪费性能。
你`select for update`再`update`，完全是在浪费行锁，还要启用事务，没有一点好处。

另外，你的代码里有BUG。冻结金额每次直接set，实际上也应该要做加减处理。像我上面这条SQL一样。

**Comment by wangliang181230** [comment]
你的cancel方法里，根本就没有的预留金额回滚到余额里。

**Comment by wangliang181230** [comment]
先自己好好检查一下代码吧。

**Comment by averyzhujinbo** [comment]
非常感谢！代码确实有点问题，另外只是求证一下tcc 执行机制概念，官方说明是 try 加冻结金额，confirm 才是扣减余额并讲冻结字段=0 ，cancel 只是讲try 冻结字段=0.

**Comment by wangliang181230** [comment]
还在注意幂等性的支持。
目前seata没有提供幂等性的功能。需要自己实现。

**Comment by averyzhujinbo** [comment]
try  confirm 并不是同步执行，在并发环境下，有可能会出现数据错误把。比如第一个用户执行try 成功后还没有来得急执行 commit/cancel 被第二个用户执行了try 然后第一个用户再执行commit/cancel 就会出现冻结字段脏数据。seata tcc 这个是怎么处理？

**Comment by wangliang181230** [comment]
> 
> 
> try confirm 并不是同步执行，在并发环境下，有可能会出现数据错误把。比如第一个用户执行try 成功后还没有来得急执行 commit/cancel 被第二个用户执行了try 然后第一个用户再执行commit/cancel 就会出现冻结字段脏数据。seata tcc 这个是怎么处理？

第一个请求资源都预留出来了，第二个请求又不需要管预留出来的资源提交了还是回滚了。继续预留新的资源就行了啊。
所以冻结金额是做加减，而不是set.

**Comment by wangliang181230** [comment]
打个比方：
我有100元。
有两个朋友来问我借钱。
第一个朋友A打电话过来说，明天下午要借40元，这时候，我把50元预留出来，不用掉也不借他人。此时，我的余额60，冻结金额40。
第二个朋友B打电话过来说，明天上午要借30元，我继续在余额60元里预留30元出来，此时，我的余额30，冻结金额70。
到了第二天早上，朋友B来借钱了，我借了他30元。此时，我的余额30，冻结金额40。到这里，你也发现了，第二个朋友的借钱请求，并没有影响第一个朋友借钱的请求。
到了下午，朋友A来了，我再借他40元。此时，我的余额30，冻结金额0。朋友A欠我40，朋友B欠我30。总计：100。数据一致性没有被破坏。

**Comment by averyzhujinbo** [comment]
非常感谢！现在彻底明白tcc利用冻结字段预留机制来达到数据隔离目的，只要编写代码处理幂等性问题了。

**Comment by Rock-liyi** [comment]
> 打个比方： 我有100元。 有两个朋友来问我借钱。
> 
> 第一个朋友A打电话过来说，明天下午要借40元，这时候，我把40元预留出来，不用掉也不借他人。此时，我的余额100-40=60，冻结金额0+40=40。 第二个朋友B打电话过来说，明天上午要借30元，我继续在余额60元里预留30元出来，此时，我的余额60-30=30，冻结金额40+30=70。
> 
> 到了第二天早上，朋友B来借钱了，我借了他30元。此时，我的余额30，冻结金额70-30=40。到这里，你也发现了，第二个朋友的借钱请求，并没有影响第一个朋友借钱的请求。 到了下午，朋友A来了，我再借他40元。此时，我的余额30，冻结金额40-40=0。朋友A欠我40，朋友B欠我30。总计：100。数据一致性没有被破坏。
> 
> TCC是不会对数据加全局锁的。一阶段的每个分支事务都已经提交。和AT不一样，AT加过全局锁。



针对这个场景，我请教一下，比如不是两个朋友借钱的场景，而是一个还一个借的场景， 朋友A要还40元，朋友B要借40元，在同一个全家事务下，朋友A 在try 阶段中，说要还钱（try），但是没有真正还(commit), 那么是不是 在try 阶段中就无法借给朋友B？ 
必须要先朋友Acommit  还了， 朋友B才能借？

**Comment by Rock-liyi** [comment]
> 打个比方： 我有100元。 有两个朋友来问我借钱。
> 
> 第一个朋友A打电话过来说，明天下午要借40元，这时候，我把40元预留出来，不用掉也不借他人。此时，我的余额100-40=60，冻结金额0+40=40。 第二个朋友B打电话过来说，明天上午要借30元，我继续在余额60元里预留30元出来，此时，我的余额60-30=30，冻结金额40+30=70。
> 
> 到了第二天早上，朋友B来借钱了，我借了他30元。此时，我的余额30，冻结金额70-30=40。到这里，你也发现了，第二个朋友的借钱请求，并没有影响第一个朋友借钱的请求。 到了下午，朋友A来了，我再借他40元。此时，我的余额30，冻结金额40-40=0。朋友A欠我40，朋友B欠我30。总计：100。数据一致性没有被破坏。
> 
> TCC是不会对数据加全局锁的。一阶段的每个分支事务都已经提交。和AT不一样，AT加过全局锁。



针对这个场景，我请教一下，比如不是两个朋友借钱的场景，而是一个还一个借的场景， 朋友A要还40元，朋友B要借40元，在同一个全家事务下，朋友A 在try 阶段中，说要还钱（try），但是没有真正还(commit), 那么是不是 在try 阶段中就无法借给朋友B？ 
必须要先朋友Acommit  还了， 朋友B才能借？

**Comment by wangliang181230** [comment]
> 针对这个场景，我请教一下，比如不是两个朋友借钱的场景，而是一个还一个借的场景， 朋友A要还40元，朋友B要借40元，在同一个全家事务下，朋友A 在try 阶段中，说要还钱（try），但是没有真正还(commit), 那么是不是 在try 阶段中就无法借给朋友B？ 必须要先朋友Acommit 还了， 朋友B才能借？

朋友A准备还钱，try阶段是将朋友A的余额减40，冻结金额加0+40=40。我的余额和冻结金额都没有任何影响。
朋友B来借钱，我的冻结金额减30。朋友余额+30。

这时朋友A到我家了，还我40元（commit）。朋友A冻结金额减40-40=0。我的余额加40。

并不两位朋友的借还并不互相影响。无论按什么顺序。我的余额和冻结金额，都是加减操作。

**Comment by wangliang181230** [comment]
> 明白了，但是在朋友B来借钱的时候，朋友A还没有真正还钱， 由于我的金额跟冻结金额都是0， 我怎么判断是否可以借给朋友呢？ 这个场景的前提是需要允许负数存在么？

当然不允许负数。直接提示余额不足。

**Comment by Rock-liyi** [comment]
> > 明白了，但是在朋友B来借钱的时候，朋友A还没有真正还钱， 由于我的金额跟冻结金额都是0， 我怎么判断是否可以借给朋友呢？ 这个场景的前提是需要允许负数存在么？
> 
> 当然不允许负数。直接提示余额不足。

我们目前就是卡在这里，不知道该怎么判断是不是负数

**Comment by wangliang181230** [comment]
> > 当然不允许负数。直接提示余额不足。
> 
> 我们目前就是卡在这里，不知道该怎么判断是不是负数

预留资源肯定是不允许被其他请求操作的，只能由原请求的二阶段来commit或rollback。
能请求的只有原资源池里的资源。资源不足时，直接是驳回请求的。
