### ISSUE TITLE
文档能优化下吗，文档内容太少了。现在的文档感觉没什么作用。

### ISSUE THREAD

**Issue by kenny19940602** [seata/seata#3063]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/3026  入门往这里看
如果有其他需要，欢迎详细点提出缺的地方

**Comment by l81893521** [comment]
I will close the issue, we can talk in the issue that include the specific problem and welcome for your contribution.
