### ISSUE TITLE
【BUG】rollback will failed if update sql contains pk

### ISSUE THREAD

**Issue by 81519434** [seata/seata#3066]
- [ x ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
For example ,there is a table：
```
CREATE TABLE `test` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `code` varchar(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ';
```
if I execute this SQL, it will not rollback correctly.
```
UPDATE `test` SET `id`='2' WHERE `code`='dog' and `id` ='1';
```

### Ⅱ. Describe what happened
Building the after image will be failed because this SQL changed the pk value.  And the after image building is based on before image. After this execution of this update SQL, the current pk value is different from before images. So building after image will not find any record when using the wrong pk.

![image](https://user-images.githubusercontent.com/9690089/91374563-0c03fa80-e84b-11ea-8f15-a25d33494ef7.png)

### Ⅲ. Describe what you expected to happen
Prohibit the execution of this type of SQL.

### Ⅴ. Anything else we need to know?
There are other bugs that I found. please check #3036.

### Ⅵ. Environment:

- JDK version :
- OS :
- Others: seata 1.3.0

**Comment by a364176773** [comment]
I have understood the problem. What is your opinion on this?

**Comment by 81519434** [comment]
There are two options:
1. Prohibit the execution of this type of SQL.
2. If the update SQL changed pk value then use the real pk value from update SQL when building after image. Rather than based on before image.

**Comment by 81519434** [comment]
Which do you think is better?

**Comment by l81893521** [comment]
In my opinion, I think use log to warn users instead of prohibit it will be better.

**Comment by l81893521** [comment]
By the way, you can use real pk to build the after image, and use log to warn users.

**Comment by 81519434** [comment]
Since it can rollback correctly, why should I warn users?

**Comment by sabersword** [comment]
I don't think we would warn users but do nothing.Transcational consistency is the most important feature of Seata, we may prohibit  this type of SQL or build the after image with the update SQL.

**Comment by 81519434** [comment]
I agree with you. @sabersword
