### ISSUE TITLE
Check lock in TC when use @GlobalLock

### ISSUE THREAD

**Issue by l81893521** [seata/seata#3067]
## Why you need it?
For now if you want to use @GlobalLock, you must use it with @Transactional, and check the global lock when transaction commit.
But it will cause two problems:
1. Can not check global lock when use @GlobalLock Independently.
2. Check global lock can not retry.

If you want to fix it, please comment "Please assign it to me" is this issue.
## Other related information

**Comment by caohdgege** [comment]
回复第二点，不只有GlobalLock+SelectForUpdate才会没有重试；在GlobalTransaction下，如果分支事务加了@Transactional注解，也重试不了。
Reply to the second point, not only GlobalLock+SelectForUpdate will not retry; under GlobalTransaction, if the branch transaction is annotated with @Transactional, it will not be retried.

**Comment by caohdgege** [comment]
Please assign it to me
