### ISSUE TITLE
使用XA模式时，没有启动全局事务也会自动进行代理

### ISSUE THREAD

**Issue by GSheep** [seata/seata#3072]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用XA模式时，如果程序设置了类似健康检查，或者是设置了spring.datasource.durid.validation-query: SELECT 1 FROM DUAL，也会自动进行代理

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
```
Just paste your stack trace here!
```
运行时的配置：
![image](https://user-images.githubusercontent.com/12742145/91690672-f2d7b280-eb98-11ea-95b9-8692eeba49ec.png)
![image](https://user-images.githubusercontent.com/12742145/91690698-fe2ade00-eb98-11ea-8897-98da824a33cf.png)
mysql8.0.11

![image](https://user-images.githubusercontent.com/12742145/91690579-c7ed5e80-eb98-11ea-866b-25b81473411e.png)
![image](https://user-images.githubusercontent.com/12742145/91690594-d2a7f380-eb98-11ea-9cd3-fca0fcf193a4.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win7
- Others:

**Comment by a364176773** [comment]
I will deal with the problem
