### ISSUE TITLE
AT模式下Service层抛出RuntimeException,undo_log没有插入数据

### ISSUE THREAD

**Issue by oldRabbitForz** [seata/seata#3077]
AT模式下Service层跑出RuntimeException,undo_log没有插入数据

**Comment by oldRabbitForz** [comment]
在分支事务中，抛出RuntimeException无回滚console,undo_log表未插入回滚记录。但是抛出Exception就可以。

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/3026 先看教程好好整合吧
