### ISSUE TITLE
release 1.3.0，全局事务Propagation.REQUIRES_NEW没有正常运行

### ISSUE THREAD

**Issue by Maestroqiua** [seata/seata#3079]
io.seata.tm.api.TransactionalTemplate中

```
public Object execute(TransactionalExecutor business) throws Throwable {
        // 1 get transactionInfo
        TransactionInfo txInfo = business.getTransactionInfo();
        if (txInfo == null) {
            throw new ShouldNeverHappenException("transactionInfo does not exist");
        }
        // 1.1 get or create a transaction
        GlobalTransaction tx = GlobalTransactionContext.getCurrentOrCreate();

        // 1.2 Handle the Transaction propatation and the branchType
        Propagation propagation = txInfo.getPropagation();
        SuspendedResourcesHolder suspendedResourcesHolder = null;
        try {
            switch (propagation) {
                case NOT_SUPPORTED:
                    suspendedResourcesHolder = tx.suspend(true);
                    return business.execute();
                case REQUIRES_NEW:
                    suspendedResourcesHolder = tx.suspend(true);
                    break;
                case SUPPORTS:
                    if (!existingTransaction()) {
                        return business.execute();
                    }
                    break;
                case REQUIRED:
                    break;
                case NEVER:
                    if (existingTransaction()) {
                        throw new TransactionException(
                                String.format("Existing transaction found for transaction marked with propagation 'never',xid = %s"
                                        ,RootContext.getXID()));
                    } else {
                        return business.execute();
                    }
                case MANDATORY:
                    if (!existingTransaction()) {
                        throw new TransactionException("No existing transaction found for transaction marked with propagation 'mandatory'");
                    }
                    break;
                default:
                    throw new TransactionException("Not Supported Propagation:" + propagation);
            }


            try {

                // 2. begin transaction
                beginTransaction(txInfo, tx);

                Object rs = null;
                try {

                    // Do Your Business
                    rs = business.execute();

                } catch (Throwable ex) {

                    // 3.the needed business exception to rollback.
                    completeTransactionAfterThrowing(txInfo, tx, ex);
                    throw ex;
                }

                // 4. everything is fine, commit.
                commitTransaction(tx);

                return rs;
            } finally {
                //5. clear
                triggerAfterCompletion();
                cleanUp();
            }
        } finally {
            tx.resume(suspendedResourcesHolder);
        }

    }
```

在判断propation之前获取了当前的全局事务对象：
` GlobalTransaction tx = GlobalTransactionContext.getCurrentOrCreate();`

在判断propation时，挂起了当前全局事务：
```
case REQUIRES_NEW:
                    suspendedResourcesHolder = tx.suspend(true);
                    break;
```

但之后执行业务代码之前并没有重新创建全局事务：
```
                // 2. begin transaction
                beginTransaction(txInfo, tx);

                Object rs = null;
                try {

                    // Do Your Business
                    rs = business.execute();

                } catch (Throwable ex) {

                    // 3.the needed business exception to rollback.
                    completeTransactionAfterThrowing(txInfo, tx, ex);
                    throw ex;
                }

                // 4. everything is fine, commit.
                commitTransaction(tx);
```

直至最后，无论是beginTransaction方法、commitTransaction方法还是triggerAfterCompletion里的回滚方法，都是以参与者的身份执行，并不会与TC进行通信，没办法起到Propagation.REQUIRES_NEW的目的

应该在该代码break之前
```
case REQUIRES_NEW:
                    suspendedResourcesHolder = tx.suspend(true);
                    break;
```
重新创建全局事务：
```
tx = GlobalTransactionContext.getCurrentOrCreate();
```

**Comment by a364176773** [comment]
break后  
beginTransaction(txInfo, tx);  创建新的事务

**Comment by wangliang181230** [comment]
目前，单单看代码，的确很难发现这个BUG。
如果可以的话，请贡献者帮忙添加一些注释或者重构一下代码。

**Comment by Maestroqiua** [comment]
> 问题存在，你能否帮忙修复此问题？

可以修复，请问该提交到哪个分支或release版本呢？

**Comment by wangliang181230** [comment]
提交到develop分支。

**Comment by Maestroqiua** [comment]
> 提交到develop分支。

OK。

> > 问题存在，你能否帮忙修复此问题？
> 
> 可以修复，请问该提交到哪个分支或release版本呢？

现在源码的注释确实太少了，版本更新但官网的文档没有更新，对开发者不太友好

**Comment by ktluo56** [comment]
我也遇到了，这个问题提交了吗

**Comment by wangliang181230** [comment]
> 
> 
> > 问题存在，你能否帮忙修复此问题？
> 
> 可以修复，请问该提交到哪个分支或release版本呢？

问下，关于这个issue，没见你提交修复的PR啊？

**Comment by qiua774706383** [comment]
> > > 问题存在，你能否帮忙修复此问题？
> > 
> > 
> > 可以修复，请问该提交到哪个分支或release版本呢？
> 
> @Maestroqiua 问下，关于这个issue，没见你提交修复的PR啊？

不好意思，最近比较忙，我会尽快提交

**Comment by Maestroqiua** [comment]
> > > 问题存在，你能否帮忙修复此问题？
> > 
> > 
> > 可以修复，请问该提交到哪个分支或release版本呢？
> 
> @Maestroqiua 问下，关于这个issue，没见你提交修复的PR啊？

不好意思，最近比较忙，我尽快提交

**Comment by wangliang181230** [comment]
> 
> 
> > > > 问题存在，你能否帮忙修复此问题？
> > > 
> > > 
> > > 可以修复，请问该提交到哪个分支或release版本呢？
> > 
> > 
> > @Maestroqiua 问下，关于这个issue，没见你提交修复的PR啊？
> 
> 不好意思，最近比较忙，我尽快提交

额，好的，我刚还把我本地的分支提交掉了呢。哈哈。你参照一下吧。
尽快提交一下吧。

**Comment by Maestroqiua** [comment]
> > > > > 问题存在，你能否帮忙修复此问题？
> > > > 
> > > > 
> > > > 可以修复，请问该提交到哪个分支或release版本呢？
> > > 
> > > 
> > > @Maestroqiua 问下，关于这个issue，没见你提交修复的PR啊？
> > 
> > 
> > 不好意思，最近比较忙，我尽快提交
> 
> 额，好的，我刚还把我本地的分支提交掉了呢。哈哈。你参照一下吧。
> 尽快提交一下吧。

respect。我抓紧时间模拟测试

**Comment by Maestroqiua** [comment]
> > > > > 问题存在，你能否帮忙修复此问题？
> > > > 
> > > > 
> > > > 可以修复，请问该提交到哪个分支或release版本呢？
> > > 
> > > 
> > > @Maestroqiua 问下，关于这个issue，没见你提交修复的PR啊？
> > 
> > 
> > 不好意思，最近比较忙，我尽快提交
> 
> 额，好的，我刚还把我本地的分支提交掉了呢。哈哈。你参照一下吧。
> 尽快提交一下吧。

你提交的pr，我review了一下
mandatory的判断貌似错了，应该tx为null时才抛出异常

![image](https://user-images.githubusercontent.com/15166549/93955488-780e4b80-fd82-11ea-9fab-cdd6fecf5ac6.png)

**Comment by wangliang181230** [comment]
哦，是哦，我弄反了。谢谢反馈。

**Comment by wangliang181230** [comment]
我注释信息是写着not existsing，代码写反了。

**Comment by Maestroqiua** [comment]
> 哦，是哦，我弄反了。谢谢反馈。

我这边顺道改吧

**Comment by wangliang181230** [comment]
嗯。

**Comment by Maestroqiua** [comment]
> 嗯。
已提交pr。

我这里提出一个疑问：

场景
方法M1 -RPC调用-> 方法M2

M1、M2都使用@GlobalTransactional注解，即都会执行TransactionalTemplate.execute
M2使用Propagation.SUPPORTS/REQUIRED/MANDATORY三种属性之一

当方法执行到M2服务的`beginTransaction(txInfo, tx);`一步，需要启动事务，但实际上流转至M2的Xid所指向的全局事务在M1已经向TC注册启动了

TransactionalTemplate.execute(TransactionalExecutor business)
![image](https://user-images.githubusercontent.com/15166549/93956539-04217280-fd85-11ea-83ea-490761842e9b.png)
![image](https://user-images.githubusercontent.com/15166549/93956538-0388dc00-fd85-11ea-9304-5221fa035374.png)

看TM的begin方法：

DefaultGlobalTransaction.begin(int timeout, String name)
![image](https://user-images.githubusercontent.com/15166549/93956583-1a2f3300-fd85-11ea-8e01-1d4320607071.png)

DefaultTransactionManager.begin(String applicationId, String transactionServiceGroup, String name, int timeout)
![image](https://user-images.githubusercontent.com/15166549/93956599-21eed780-fd85-11ea-8b5c-1470104d6b78.png)

与TC通信启动全局事务时，只根据TC返回的code判断启动失败，然后就直接抛出异常了。

因为我没看TC端的源码，不知道是否是做了重复启动的全局事务的校验，现在流程能正常的跑，应该是有做校验的吧？
但我认为TM对全局事务的操作前，应该增加对当前全局事务状态的判断以增强代码健壮性。

**Comment by wangliang181230** [comment]
![图片](https://user-images.githubusercontent.com/1527893/93962482-7f872200-fd8d-11ea-94fb-bd99554282f6.png)
这里有对角色进行校验的。

**Comment by wangliang181230** [comment]
'Propagation.MANDATORY'不存在BUG的，是我刚才弄错了。

**Comment by Maestroqiua** [comment]
> ![图片](https://user-images.githubusercontent.com/1527893/93962482-7f872200-fd8d-11ea-94fb-bd99554282f6.png)
> 这里有对角色进行校验的。

哦哦明白了，之前有看到这段代码。
pr好像被travis block掉了，我没看太懂是哪里有问题，能麻烦你帮我看看嘛？
https://github.com/seata/seata/pull/3143#issue-491436762

**Comment by wangliang181230** [comment]
标题改一下吧。

**Comment by Maestroqiua** [comment]
> 'Propagation.MANDATORY'不存在BUG的，是我刚才弄错了。

不好意识，我改了pr名字和描述了

**Comment by wangliang181230** [comment]
![Uploading 图片.png…]()

**Comment by Maestroqiua** [comment]
https://github.com/seata/seata/issues/3079#issuecomment-697108725

图片看不到哦

**Comment by wangliang181230** [comment]
有一个import没用到，删掉就行了。

**Comment by Maestroqiua** [comment]
> 有一个import没用到，删掉就行了。

好的

**Comment by wangliang181230** [comment]
额，seata的管理员认为我那个完成度高一些，决定这次先用我的PR了。
你有空帮忙再去看看其他issue，看看还有哪些能帮忙修复的吧。不好意思啊。

**Comment by Maestroqiua** [comment]
> 额，seata的管理员认为我那个完成度高一些，决定这次先用我的PR了。
> 你有空帮忙再去看看其他issue，看看还有哪些能帮忙修复的吧。不好意思啊。

那你记得提交mandatory的改动

**Comment by wangliang181230** [comment]
好的。谢谢。
