### ISSUE TITLE
升级1.3后使用dubbo注解形式的tcc模式没有执行commit或rollback方法

### ISSUE THREAD

**Issue by lixb3911** [seata/seata#3080]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
demo：
  @Override
    public boolean prepare(BusinessActionContext actionContext,int num) {
        String xid = actionContext.getXid();
        System.out.println("TccActionOne prepare, xid:" + xid +  ", a:" + num);
        return true;
    }

    @Override
    public boolean commit(BusinessActionContext actionContext) {
        String xid = actionContext.getXid();
        System.out.println("TccActionOne commit, xid:" + xid + ", a:" + actionContext.getActionContext("a"));
        ResultHolder.setActionOneResult(xid, "T");
        return true;
    }

    @Override
    public boolean rollback(BusinessActionContext actionContext) {
        String xid = actionContext.getXid();
        System.out.println("TccActionOne rollback, xid:" + xid + ", a:" + actionContext.getActionContext("a"));
        ResultHolder.setActionOneResult(xid, "R");
        return true;
    }

    @GlobalTransactional
    public String doTransactionCommit() {
        //事务参与者
        BusinessActionContext businessActionContext = new BusinessActionContext();
        Map<String, Object> actionContext = new HashMap();
        actionContext.put("accountNo", 22L);
        actionContext.put("amount", 33L);
        businessActionContext.setActionContext(actionContext);
        boolean result = storageService.prepare(businessActionContext, 1);
        if (!result) {
            throw new RuntimeException("TccActionOne failed.");
        }
        return RootContext.getXID();
    }
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by wangliang181230** [comment]
TCC与@GlobalTransactional不能在同一接口中使用。
GlobalTransactionalScanner里，先扫描了@GlobalTransactional，如果扫描到了，就不会再扫描TCC了。

**Comment by lixb3911** [comment]
我是分开的用的是官网的例子

**Comment by lixb3911** [comment]
> TCC与@GlobalTransactional不能在同一个类中使用。
> GlobalTransactionalScanner里，先扫描了@GlobalTransactional，如果扫描到了，就不会再扫描TCC了。

我是分开的用的是官网的例子

**Comment by wangliang181230** [comment]
那你仔细看一下日志打印，是否有打印过这个bean添加了tcc拦截器。

**Comment by lixb3911** [comment]
> 那你仔细看一下日志打印，是否有打印过这个bean添加了tcc拦截器。

打印什么关键字
