### ISSUE TITLE
Seata XA模式环调XAER_NOTA: Unknown XID

### ISSUE THREAD

**Issue by 2583662495** [seata/seata#3085]
参考Seata AT模式示例改造为XA，非环调下正常，环调的话就会出现如下异常：
Seata XA模式环调：com.mysql.jdbc.jdbc2.optional.MysqlXAException: XAER_NOTA: Unknown XID
com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
最后超时异常回滚

**Comment by a364176773** [comment]
xa不支持环掉，因为他不可重入锁。
