### ISSUE TITLE
Seata是否有提供健康检查的api或提供健康检查的方式

### ISSUE THREAD

**Issue by redflowflag** [seata/seata#3087]
咨询下，我们计划把Seata部署在k8s上，想了解下Seata是否有提供健康检查的api或提供健康检查的方式。

**Comment by helloworlde** [comment]
可以使用 telnet

**Comment by pencilso** [comment]
没用，直接用telnet的话，seataServer会报错，然后telnet会提示Connection closed by foreign host.

**Comment by pencilso** [comment]
楼主解决了吗

**Comment by a364176773** [comment]
访问seata  7091端口的health接口
