### ISSUE TITLE
LockManager LOCK_MAP not persist AND single node problem?

### ISSUE THREAD

**Issue by HunterPan** [seata/seata#309]
目前，LockManager只有一个实现类，里面的LOCK_MAP也没持久化，重启全局锁就丢了，项目未来会考虑持久化吧？而且持久化好处是server可以多点部署了

**Comment by sharajava** [comment]
Lock Map will be restored when rebooting according to session logs. Plan to add restoring logic in 0.3.0. 👍

**Comment by leizhiyuan** [comment]
waiting for this pr,https://github.com/seata/seata/pull/942

**Comment by leizhiyuan** [comment]
support db mode now in 0.6.0
