### ISSUE TITLE
通过添加注解使得RM不纳入当次分布式事务上下文

### ISSUE THREAD

**Issue by Gordonman** [seata/seata#3093]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
TM开启分布式事务后，会生成全局xid放到head中传递给RM，假如在被调用的RM中，有一个RM不想使用分布式事务，是否可以通过注解的方式屏蔽掉？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
RM是通过拦截器从http head中查TX_XID,有的话放入线程上下文中，ConnectionProxy代理类会判断上下文中是否有TX_XID，那只是将TX_XID从上下文中去除就可以屏蔽掉分布式事务对当前RM的作用

**Comment by a364176773** [comment]
不想加入的分支事务，加入全局事务注解，并配置对应事务传播即可

**Comment by Gordonman** [comment]
谢谢答复，你的意思是在RM的相关类上加上@GlobalTransactional吗？那么请问如何配置事务传播呢，我在@GlobalTransactional没有看到相关配置，seata版本是1.1.0

**Comment by Gordonman** [comment]
已经在最新版本的代码中找到了
