### ISSUE TITLE
使用pg数据库作为数据源，PostgresqlTableMetaCache 解析存在问题，multi pk only support mysql!

### ISSUE THREAD

**Issue by JasonMsbaby** [seata/seata#3098]
<img width="828" alt="WX20200909-142100@2x" src="https://user-images.githubusercontent.com/11964522/92562022-ded23600-f2a7-11ea-9cc9-5d3d43c1f13b.png">
如上图所示，在进行pg数据库表结构解析时，如果写的sql语句没有带schema，则schema为空，后续所有该表对应的列以及索引缓存信息将会聚合所有schema下相同表名的列和索引。
<img width="817" alt="WX20200909-142128@2x" src="https://user-images.githubusercontent.com/11964522/92562144-0fb26b00-f2a8-11ea-8c2c-c675f2a99ba5.png">

导致后面会出现多个主键检测异常

<img width="991" alt="WX20200909-142156@2x" src="https://user-images.githubusercontent.com/11964522/92562202-23f66800-f2a8-11ea-90d6-bed235531848.png">

**Comment by a364176773** [comment]
目前不支持mysql以外的数据库多主键，欢迎各位能人异士贡献这块支持的pr

**Comment by JasonMsbaby** [comment]
> 目前不支持mysql以外的数据库多主键，欢迎各位能人异士贡献这块支持的pr

并不是mysql数据库多主键的问题，是pg多schema下出现相同表名，导致解析bug，将所有相同表名的所有字段认为是一个表下的字段，导致出现多个主键

**Comment by wangjing0716** [comment]
那怎么解决的？

**Comment by wangjing0716** [comment]
pg 的 审计表，rev + id 联合主键 ，导致报错 multi pk only support mysql!
