### ISSUE TITLE
Does Fescar support spring-data-jpa?

### ISSUE THREAD

**Issue by reddysainathn** [seata/seata#31]
This is a real solution for multiple transactions to handle it over a global transaction, 

Does `fescar` support spring-data-jpa?

Thank you.

**Comment by sharajava** [comment]
Fescar is based on JDBC. I think it's not a problem working with spring-data-jpa. I don't familiar with spring-data-jpa, but I think there should be JDBC under it, isn't it?

It will be nice if you can try solutions base on spring-data-jpa + Fescar. 👍  Thank you 💯

**Comment by reddysainathn** [comment]
Ok, I understand now. Will try an example.

**Comment by leizhiyuan** [comment]
please see seata-samples
