### ISSUE TITLE
时期序列化格式问题

### ISSUE THREAD

**Issue by TwilightTian** [seata/seata#3107]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在使用oracle数据库时,数据库时间字段为timestamp时.seata在插入undolog序列化对象时,时间会丢失毫秒数.
具体方法在 AbstractUndoLogManager.flushUndoLogs 中 的 UndoLogParser parser = UndoLogParserFactory.getInstance();
byte[] undoLogContent = parser.encode(branchUndoLog); 序列化工具为fastjson及kryo都有这种情况.
这个问题应该和seata本身无关. 但是还是希望能有个配置的地方.

**Comment by slievrly** [comment]
@TwilightTian https://github.com/seata/seata/issues/2047
