### ISSUE TITLE
 关于seata与mycat集成时碰到的BUG，请教一下是否为seata无法解决的bug

### ISSUE THREAD

**Issue by Longinusss** [seata/seata#3108]
mycat已经做了分库分表，我发现springboot集成seata,user-service与good-service模拟分布式扣款事务
连接mycat时（逻辑库TESTDB），若mycat配置文件schema.xml的节点对应的数据库名字不全为TESTDB，则会爆出空指针异常或者找不到表的错误，请问此错误可以避免吗？
（我把第一个事务数据库改为了TESTDB，此事务即正常，第二项事务由于已做了分库分表，数据库名字不好直接改）
报错：
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: can't find table define in schema T_PRODUCT schema:TESTDB
	at

数据库连接：
datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.147:8066/TESTDB?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false

mycat配置文件：schema.xml:

  <dataNode name="dn1" dataHost="host1" database="testdb" />
  
  <dataNode name="dn2" dataHost="host2" database="TESTDB" />
  <dataNode name="dn3" dataHost="host3" database="testdb" />

**Comment by slievrly** [comment]
@Longinusss Instead of using seata directly, seata should be integrated by the framework behind mycat's routing layer.

**Comment by Longinusss** [comment]
@slievrly 能否说明一下mycat背后的路由层框架是什么？

**Comment by a364176773** [comment]
> @slievrly 能否说明一下mycat背后的路由层框架是什么？

应该由框架团队来提供集成兼容方案，比如shardingsphere就集成了seata
