### ISSUE TITLE
Seata以Nacos为注册中心DB模式集成用户名账号携带“+”有问题

### ISSUE THREAD

**Issue by SanjiFlip** [seata/seata#3111]
2020-09-11 15:59:59.150 ERROR[main]com.alibaba.druid.pool.DruidDataSource.init:878 -init datasource error, url: jdbc:mysql://xx.xx.xx.xx:3306/seata?useUnicode=true
java.sql.SQLException: Access denied for user 'root'@'xx.xx.xx.xx' (using password: YES)
这个需要重新修改数据库密码，重新导入脚本

**Comment by PeineLiang** [comment]
这个问题与Seata和Nacos无关吧

**Comment by slievrly** [comment]
@SanjiFlip What is the value of this configuration item（`store.db.user`） displayed in the Nacos configuration center?

**Comment by tanchangmin** [comment]
版本：1.4.2
信息注册到nacos之后启动seata，如果mysql登录密码里面有英文逗号“,”也会报这个错，把密码改了就好
