### ISSUE TITLE
seata 集成nacos 注册 拉取一直是127.0.0.1

### ISSUE THREAD

**Issue by hehanpeng** [seata/seata#3112]
在nacos 上注册seata ，服务可以查看到， 但是spring 应用一直报错，拉取的地址一直都是127.0.0.1

NettyClientChannelManager 0101 can not connect to 127.0.0.1:8091 cause:can not register RM,err:can not connect to services-server.
io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to service

**Comment by xiaobai14** [comment]
我也是使用nacos作为注册中心和配置中心，启动seata-server之前，已经执行nacos-config.sh 初始化配置到nacos了，启动seata后，在nacos也看到注册的seata服务 但是集成seata时一直拉取的地址是127.0.0.1
版本： nacos 1.3     spring-cloud-alibaba:2.2.1.RELEASE
