### ISSUE TITLE
[etcd3] config operation timeout,cost:5004 ms,op:GET,dataId:store.mode

### ISSUE THREAD

**Issue by aakejiang** [seata/seata#3114]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Get config operation timeout using etcd 3 as configuration service.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
ERROR --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5004 ms,op:GET,dataId:store.mode
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

registry.conf:
```
registry {
  type = "etcd3"

  etcd3 {
    cluster = "default"
    serverAddr = "http://127.0.0.1:2379"
  }
}

config {
  type = "etcd3"

  etcd3 {
    serverAddr = "http://127.0.0.1:2379"
  }
}

```

i can get the right response using curl:

```
~ curl -L http://127.0.0.1:2379/v3/kv/range -X POST -d '{"key": "c3RvcmUubW9kZQ=="}'
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"15","raft_term":"3"},"kvs":[{"key":"c3RvcmUubW9kZQ==","create_revision":"10","mod_revision":"10","version":"1","value":"ZGI="}],"count":"1"}%
```

it's correct while using etcd client command:
```
~ ETCDCTL_API=3  etcdctl --endpoints http://127.0.0.1:2379 get store.mode
store.mode
db
```

### Ⅴ. Anything else we need to know?

- Install etcd-v3.4.13 by docker in MacOS

docker run \
 -p 2379:2379 \
 -p 2380:2380 \
 --mount type=bind,source=~/data/etcd,destination=/etcd-data \
 --name etcd-v3.4.13 \
 quay.io/coreos/etcd:v3.4.13 \
 /usr/local/bin/etcd \
 --name etcd-v3.4.13 \
 --data-dir /etcd-data \
 --listen-client-urls http://0.0.0.0:2379 \
 --advertise-client-urls http://0.0.0.0:2379 \
 --log-level info \
 --logger zap \
 --log-outputs stderr

**Comment by slievrly** [comment]
@aakejiang upgrade seata version to 1.3.0

**Comment by aakejiang** [comment]
@slievrly i'm using the version 1.3.0.

**Comment by lihuadong7364** [comment]
@slievrly 1.3.0 consul同样的问题
