### ISSUE TITLE
源码代码不全

### ISSUE THREAD

**Issue by LearnJA** [seata/seata#3121]
大佬们  你们上传代码的时候是不是漏提交文件夹了 ^&^!   今天拉源码跑的时候 
![image](https://user-images.githubusercontent.com/44966567/93321682-08113a00-f845-11ea-99e9-7729077f28ef.png)这块儿文件夹路径没有啊！ 查看了一下仓库：
![image](https://user-images.githubusercontent.com/44966567/93322688-2deb0e80-f846-11ea-94e5-b19474121d61.png) 也是没有，且 仓库代码里也是有这个路劲的：
![image](https://user-images.githubusercontent.com/44966567/93322981-89b59780-f846-11ea-8391-a63b81ef94a8.png)

还是说 我搞错了

**Comment by wangliang181230** [comment]
install一下就可以了。

**Comment by xingfudeshi** [comment]
Protobuf related files need to be generated,As they are not part of source code.
`mvn clean install -DskipTests -U`
