### ISSUE TITLE
批量新增回滚一条数据问题

### ISSUE THREAD

**Issue by KissSai** [seata/seata#3125]
1.3.0使用 tk.mybatis.mapper.additional.insert.InsertListMapper.insertList 时，只会回滚第一条数据，其它的数据并未回滚到。

场景：
       同一个事物下 
            （1）A服务调用B服务修改信息（成功）
            （2）A服务调用C服务批量新增（成功）
            （3）A服务调用D服务修改信息（失败，抛异常）

结果：C服务数据只会回滚一条数据。

C服务批量新增 sql 格式：

INSERT INTO test( one,two ) VALUES ( ?,? ) , ( ?,? ) , ( ?,? ) , ( ?,? ),( ?,? )

**Comment by KissSai** [comment]
{
	"@class": "io.seata.rm.datasource.undo.BranchUndoLog",
	"xid": "192.168.200.247:8093:49872388258533376",
	"branchId": 49872388367585281,
	"sqlUndoLogs": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
				"sqlType": "INSERT",
				"tableName": "test",
				"beforeImage": {
					"@class": "io.seata.rm.datasource.sql.struct.TableRecords$EmptyTableRecords",
					"tableName": "test",
					"rows": ["java.util.ArrayList", []]
				},
				"afterImage": {
					"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
					"tableName": "test",
					"rows": ["java.util.ArrayList", [{
								"@class": "io.seata.rm.datasource.sql.struct.Row",
								"fields": ["java.util.ArrayList", [{
											"@class": "io.seata.rm.datasource.sql.struct.Field",
											"name": "one",
											"keyType": "PRIMARY_KEY",
											"type": 4,
											"value": 485
										}, {
											"@class": "io.seata.rm.datasource.sql.struct.Field",
											"name": "two",
											"keyType": "NULL",
											"type": 12,
											"value": "503984373930921984"
										}
									]]
							}
						]]
				}
			}
		]]
}
undo_log 中rollback_info 信息只记录了一条数据

**Comment by caohdgege** [comment]
Fail to get auto-generated keys, use 'SELECT LAST_INSERT_ID()' instead. Be cautious, statement could be polluted. Recommend you set the statement to return generated keys.

**Comment by KissSai** [comment]
你尝试用  tk.mybatis.mapper.additional.insert.InsertListMapper.insertList 这个试一下呢

**Comment by KissSai** [comment]
> `Fail to get auto-generated keys, use 'SELECT LAST_INSERT_ID()' instead. Be cautious, statement could be polluted. Recommend you set the statement to return generated keys.`
> 看一下有没有这段日志，如果有的话，你在SQL对应的xml里面加上useGeneratedKeys应该就好了。
> 如果你没有加上useGeneratedKeys，seata就会用select last_insert_id()去查询你插入的主键来构建afterImage，这样出错回滚的时候就只能滚一条了。

你尝试使用  tk.mybatis.mapper.additional.insert.InsertListMapper.insertList 这个批量新增试一下呢

**Comment by 511098425** [comment]
> > `Fail to get auto-generated keys, use 'SELECT LAST_INSERT_ID()' instead. Be cautious, statement could be polluted. Recommend you set the statement to return generated keys.`
> > 看一下有没有这段日志，如果有的话，你在SQL对应的xml里面加上useGeneratedKeys应该就好了。
> > 如果你没有加上useGeneratedKeys，seata就会用select last_insert_id()去查询你插入的主键来构建afterImage，这样出错回滚的时候就只能滚一条了。
> 
> 你尝试使用 tk.mybatis.mapper.additional.insert.InsertListMapper.insertList 这个批量新增试一下呢

就是不能用这个，应该要用special下面的insertList就正常了
