### ISSUE TITLE
启动 seata server，并注册到 nacos，服务列表中经常没有列出服务。

### ISSUE THREAD

**Issue by lemos1235** [seata/seata#3127]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
启动 seata server，并注册到 nacos，服务列表中经常没有列出服务。

### Ⅵ. Environment:

- JDK version : 1.8
- OS : win10

**Comment by a364176773** [comment]
please check your configuration or network
