### ISSUE TITLE
希望 GlobalTransactionScanner 的 order 优先级设置高点

### ISSUE THREAD

**Issue by squallliu** [seata/seata#3152]
如果使用 AbstractAutoProxyCreator 来创建本地事务代理，本地事务和全局事务的顺序会不可预测（order相等），会报 Could not register branch into global session xid 的错误，目前我们是把自己的优先级设置低了

**Comment by wangliang181230** [comment]
这个问题跟Scanner优先级无关，而是跟Advisor插入的位置有关。
我提交过一个PR，可自定义TM和TCC的interceptor的order。#3064

**Comment by squallliu** [comment]
如果Scanner不调的话，if(!AopUtils.isAopProxy(bean)) 这里直接返回了，你改的代码没机会执行哇

**Comment by wangliang181230** [comment]
> 
> 
> 如果Scanner不调的话，if(!AopUtils.isAopProxy(bean)) 这里直接返回了，你改的代码没机会执行哇

如果是执行`bean = super.wrapIfNecessary(bean, beanName, cacheKey);`这段代码的话，由spring自动进行排序的。

**Comment by wangliang181230** [comment]
请阅读`spring`相关的源码。

**Comment by squallliu** [comment]
我说的就是由 spring 自动排序这里不对啊，应该设置 order，进入 if(AopUtils.isAopProxy(bean)) 的逻辑，这样全局事务就在本地事务之前了啊

**Comment by wangliang181230** [comment]
本地事务的order也可以改的。只要改的比全局事务的order要大就好。默认情况下，本地事务的order就是最大值。而全局事务的order是最小值+1000，默认情况下已经能保证在前了。
除非用户自己配置错了。

**Comment by squallliu** [comment]
现在的版本还不行吧

**Comment by wangliang181230** [comment]
嗯，我的PR还没合并呢。
