### ISSUE TITLE
 add rollback_info field unzip for undolog

### ISSUE THREAD

**Issue by a364176773** [seata/seata#3159]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

When the amount of data that needs to be rolled back is very large, it is very slow to read undolog from the database, we should optimize it as much as possible
当需要回滚的数据量非常大时，从数据库中读取undolog是非常慢的，我们要尽可能的优化他

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by caohdgege** [comment]
plz assign to me
