### ISSUE TITLE
optimization after a unique index conflict occurs in undolog

### ISSUE THREAD

**Issue by a364176773** [seata/seata#3160]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

When a resource suspension occurs, an undolog with a status of 1 will be inserted to prevent resource suspension problems. When a unique index conflict occurs, a strategy should be adopted to delete the preventive undolog

资源防悬挂的策略是插入一条status为1的undolog，此时发生唯一索引冲突时，说明已经起到了防悬挂的作用，理论上应该放入一个队列中异步删除，避免出现大量的status=1的undolog

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by caohdgege** [comment]
这个加了之后，原本的定时删除应该还是要保留吧？

**Comment by a364176773** [comment]
> 这个加了之后，原本的定时删除应该还是要保留吧？

yes

**Comment by imherewait** [comment]
i want to try it, please assign it to me, thanks.

**Comment by a364176773** [comment]
> i want to try it, please assign it to me, thanks.

ok

**Comment by imherewait** [comment]
悬挂出现的机率较低，但以防万一我这里还是用有界队列吧，入队不成功的悬挂记录丢给日清理任务去做；我看日清理任务只清理了回滚和提交状态的记录，悬挂记录也是走到终态了是否也要加上一并清除？

**Comment by imherewait** [comment]
> > i want to try it, please assign it to me, thanks.
> 
> ok

AsyncWorker是对二阶段完成的undolog缓存满再批量处理，若客户端宕机可能清理不掉，undolog没有像tcc_fence_log一样的日清理任务吗？另外对于悬挂状态的undolog清理，我直接复用AsyncWorker的队列及处理逻辑是否合理?

**Comment by a364176773** [comment]
> > > i want to try it, please assign it to me, thanks.
> > 
> > 
> > ok
> 
> AsyncWorker是对二阶段完成的undolog缓存满再批量处理，若客户端宕机可能清理不掉，undolog没有像tcc_fence_log一样的日清理任务吗？另外对于悬挂状态的undolog清理，我直接复用AsyncWorker的队列及处理逻辑是否合理?

tc会下发undolog删除之类，默认7天前的会进行删除，复用AsyncWorker我觉得是可行的，你可以先试试
