### ISSUE TITLE
AbstractHttpExecutor  Map<String, String> convert(Map<String, Object> param)  Repeated conditional tests

### ISSUE THREAD

**Issue by everyhook1** [seata/seata#3161]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
    public static Map<String, String> convert(Map<String, Object> param) {
        return param.keySet().stream().filter(key -> param.get(key) != null && param.get(key) != null).collect(Collectors.toMap(key -> key, key -> param.get(key).toString()));
    }
there has a Repeated conditional tests in the code

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
1.remove Repeated conditional tests
2.keySet().stream()->map.foreach
    public static Map<String, String> convert(Map<String, Object> param) {
        Map<String, String> covertMap = new HashMap<>();
        param.forEach((key, value) -> {
            if (value != null) {
                covertMap.put(key, value.toString());
            }
        });
        return covertMap;
    }

**Comment by caohdgege** [comment]
it has been fixed in #3134
3134那个pr已经修复了
