### ISSUE TITLE
High availability for Seata

### ISSUE THREAD

**Issue by amit2103** [seata/seata#3163]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
Running Seata without HA seems to be a serious bottleneck as it it will be a single point of failure

## How it could be?

What do we need to do to enable HA in Seata ? There is go version of the service which is supposedly HA, however that version has zero documentation to set it up

To make the Java version HA what are the changes we need to do ?

**Comment by slievrly** [comment]
@amit2103 https://seata.io/zh-cn/docs/ops/deploy-ha.html

**Comment by amit2103** [comment]
@slievrly  Thanks , but most of it is Chinese, an example will help in English

**Comment by caohdgege** [comment]
> @slievrly Thanks , but most of it is Chinese, an example will help in English

https://seata.io/en-us/docs/ops/deploy-ha.html

**Comment by l81893521** [comment]
I will close this issue later. If you still have problem and you can keep report to us.
