### ISSUE TITLE
SQL的where条件中在构建查询beforeImage时，包含 "\n" 会被替换成 " "

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#3164]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
SQL的where条件中在构建查询beforeImage时，包含 "\n" 会被替换成 " "
以及根据代码中的备注，说明是由于druid的bug，具体指的是？@81519434 

![image](https://user-images.githubusercontent.com/22959373/94571295-678a3380-02a2-11eb-9dd2-1f659a626152.png)
![image](https://user-images.githubusercontent.com/22959373/94571355-7a9d0380-02a2-11eb-99c9-f95913d73113.png)
![image](https://user-images.githubusercontent.com/22959373/94571388-838dd500-02a2-11eb-9473-5faf89d19f96.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by 81519434** [comment]
这个是我之前顺手改的，可能之前的druid版本有点问题。
我看最近更新了druid的版本，我本地再测的时候，没有异常了。

**Comment by caohdgege** [comment]
那也就是说可以把 把换行换成空格 的那一段字节删掉了？

**Comment by 81519434** [comment]
嗯嗯
你如果想提pr，可以再测下

**Comment by caohdgege** [comment]
ok，到时候我测试一下两个版本的druid，看一下具体的问题是什么

**Comment by caohdgege** [comment]
> 嗯嗯
> 你如果想提pr，可以再测下

我测试了新旧版本的druid(1.1.12和1.1.23)，where条件里面包含 \n 都是可以正常解析的![image](https://user-images.githubusercontent.com/22959373/95573494-1f1b0480-0a5e-11eb-823a-5be0b36349d6.png)
用的是以下的SQL
```sql
update user set logo='\n'\nwhere id\n=#{id} \nand \nlogo='\n\r'\n
```
@81519434 文俊哥对那个bug还有印象吗?我这边重新不出来 ![image](https://user-images.githubusercontent.com/22959373/95573494-1f1b0480-0a5e-11eb-823a-5be0b36349d6.png)

**Comment by 81519434** [comment]
那你删掉这部分代码吧，太久了，我也忘记怎么重现了。

**Comment by 81519434** [comment]
有问题再说，毕竟这个解决方案也很垃圾
