### ISSUE TITLE
在windows启动seata，没启动成功

### ISSUE THREAD

**Issue by xqs41621** [seata/seata#3168]
[2m2020-09-30 14:27:54.708[0;39m [32m INFO[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2020-09-30 14:32:54.710[0;39m [32m INFO[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2020-09-30 14:37:54.711[0;39m [32m INFO[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2020-09-30 14:42:54.713[0;39m [32m INFO[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2020-09-30 14:47:54.716[0;39m [32m INFO[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration
[2m2020-09-30 14:52:54.718[0;39m [32m INFO[0;39m [2m---[0;39m [2m[trap-executor-0][0;39m [36mc.n.d.s.r.aws.ConfigClusterResolver     [0;39m [2m:[0;39m Resolving eureka endpoints via configuration

这是cmd日志，说好像是没注册成功，但是我在eureka上面，能看到服务已经注册

**Comment by slievrly** [comment]
@wangliang181230

**Comment by wangliang181230** [comment]
启动成功的，只是日志里的颜色符乱码了，bat不支持。现在最新快照版本已经修复了，1.3.0的话，打开logback.xml里把%clr（text）｛color｝把，%clr（）｛color｝都删了，留下text内容。就好了。

**Comment by xqs41621** [comment]
感谢
