### ISSUE TITLE
AppTest code question

### ISSUE THREAD

**Issue by snailshen2014** [seata/seata#317]
86 lines in AppTest, in the execute method, throw an exception, the transaction rollback throws ShouldNeverHappenException

![916e3289-aea8-4d6e-be3b-b0b82198381f](https://user-images.githubusercontent.com/8650701/51887977-7aaf7680-23d0-11e9-86b3-4a25d63b4780.jpg)
![2](https://user-images.githubusercontent.com/8650701/51887989-87cc6580-23d0-11e9-90e2-951109e27505.jpg)

**Comment by leizhiyuan** [comment]
please use the latest code to test it, thanks

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
