### ISSUE TITLE
工程代码包错误：seata/serializer/seata-serializer-fst/src/main/java/io.seata.serializer.fst/

### ISSUE THREAD

**Issue by danlley** [seata/seata#3171]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
问题：路径seata/serializer/seata-serializer-fst/src/main/java/io.seata.serializer.fst/中“io.seata.serializer.fst”目前是一层文件夹的名称，导致工程导入eclipse时，无法进行代码识别，导致工程报错

### Ⅱ. Describe what happened

路径““io.seata.serializer.fst””在工程导入eclipse时不可识别

### Ⅲ. Describe what you expected to happen
变更工程源代码路径““io.seata.serializer.fst””为“io/seata/serializer/fst”

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

工程导入eclipse可重现

### Ⅴ. Anything else we need to know?
无

### Ⅵ. Environment: win7+eclipse

- JDK version :JDK8
- OS :win7
- Others:

**Comment by slievrly** [comment]
Can others reproduce this phenomenon? I used the develop branch.
![image](https://user-images.githubusercontent.com/8758457/95586022-a6727300-0a72-11eb-9828-3c6436a6f62c.png)

**Comment by jsbxyyx** [comment]
![image](https://user-images.githubusercontent.com/26616196/95696548-2153ad80-0c6e-11eb-9f46-8493557dd59e.png)

@slievrly this is bug.
