### ISSUE TITLE
seata使用场景问题

### ISSUE THREAD

**Issue by pojun8866** [seata/seata#3173]
有两个独立工程，业务接口工程和数据接口工程。
业务接口只操作业务相关内容，不涉及db。数据接口操作数据库增删改查把它们注册到nacos 通过dubbo实现通信。
问能否使用seata控制业务接口的事务回滚？

**Comment by wolf8334** [comment]
对数据接口的操作是否都来自业务接口？
也即，前端发起ajax调用到业务接口，业务接口通过nacos调用数据接口，数据接口或接口们操作一个或多个数据库，实现业务操作。
如果是这样的话，个人感觉你需要的是Spring Transaction。

**Comment by pojun8866** [comment]
> 对数据接口的操作是否都来自业务接口？
> 也即，前端发起ajax调用到业务接口，业务接口通过nacos调用数据接口，数据接口或接口们操作一个或多个数据库，实现业务操作。
> 如果是这样的话，个人感觉你需要的是Spring Transaction。

是的都来自业务接口。
业务接口调用多个数据接口，两个完全独立工程，在业务接口用Spring Transaction也不能影响到数据接口吧。感觉无法做到事务控制。
