### ISSUE TITLE
ERROR [,,,] 4199 --- [fileListener_16] io.seata.config.FileConfiguration        : fileListener execute error:org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@681e144 has been closed already

### ISSUE THREAD

**Issue by qianmi-chenyufei** [seata/seata#3174]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
不支持热重启，热部署
