### ISSUE TITLE
AT 模式和 Spring @Transactional 注解连用无法进行手动回滚

### ISSUE THREAD

**Issue by dingthu-goo** [seata/seata#3176]
### **Ⅰ. Issue Description**

> 有俩个服务，A调用B，A服务在入口使用@GlobalTransactional @Transactional(rollbackFor = Exception.class)注解。A服务向数据库新增一条数据后通过feign调用B服务。B服务抛出一个异常。feign在降级的情况下通过GlobalTransactionContext.reload(RootContext.getXID()).rollback();进行手动回滚。这种情况下报错，但数据正常回滚了。
> ```
>org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 172.16.238.1:85:58146375518392320, may be has finished.] ]
>	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:334)
>	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:744)
>	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:712)
>	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631)
>	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
>	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:150)
>	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:104)
>	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:147)
>	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:122)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
>	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
>	at com.wlcb.jpower.service.impl.CoreUserServiceImpl$$EnhancerBySpringCGLIB$$59645e9f.savetest(<generated>)
>	at com.wlcb.jpower.controller.UserController.test(UserController.java:331)
>	at com.wlcb.jpower.controller.UserController$$FastClassBySpringCGLIB$$8fab1733.invoke(<generated>)
>	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
>	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
>	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
>	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
>	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
>	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
>	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
>	at com.wlcb.jpower.controller.UserController$$EnhancerBySpringCGLIB$$ec802ab3.test(<generated>)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.lang.reflect.Method.invoke(Method.java:498)
>	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
>	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
>	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
>	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
>	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
>	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
>	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
>	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
>	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
>	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
>	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:90)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at com.wlcb.jpower.module.common.page.PageFilter.doFilter(PageFilter.java:38)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at com.wlcb.jpower.module.configurer.xss.XssFilter.doFilter(XssFilter.java:47)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
>	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
>	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
>	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
>	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
>	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
>	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
>	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
>	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
>	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
>	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
>	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
>	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
>	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
>	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
>	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>	at java.lang.Thread.run(Thread.java:748)
>Caused by: java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 172.16.238.1:85:58146375518392320, may be has finished.] ]
>	at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:157)
>	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:218)
>	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:196)
>	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:184)
>	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:289)
>	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:183)
>	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:331)
>	... 98 common frames omitted
>Caused by: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 172.16.238.1:85:58146375518392320, may be has finished.] ]
>	at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:69)
>	at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
>	at io.seata.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:238)
>	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:216)
>	... 103 common frames omitted

### **Ⅱ. Issue Images**

  **A服务service入口**
![image](https://user-images.githubusercontent.com/69645169/95645000-63091a80-0aed-11eb-9bf5-c958a9d3f757.png)

  **feign降级**
![image](https://user-images.githubusercontent.com/69645169/95645038-c5fab180-0aed-11eb-87be-cbef44ac802e.png)
![image](https://user-images.githubusercontent.com/69645169/95645034-baa78600-0aed-11eb-8aa1-0da655f3848e.png)

  **B服务抛出异常**
![image](https://user-images.githubusercontent.com/69645169/95645030-a4012f00-0aed-11eb-96b1-f7bedc25cd1e.png)

  **A服务报错**
![image](https://user-images.githubusercontent.com/69645169/95645086-65b83f80-0aee-11eb-8eb4-6eee3054d498.png)

### **Ⅲ. Describe what you expected to happen**

> 在和本地事务连用的情况下，怎么在feign降级的时候进行事务回滚？

### **Ⅳ. Anything else we need to know?**
> 

> 只有@GlobalTransactional @Transactional(rollbackFor = Exception.class)连用的情况下会报错，单独使用@GlobalTransactional注解可正常执行。

> 数据可以正常回滚，只是在全局事务提交时，报错找不到全局事务

> 去掉feign降级里面的手动回滚的代码也可正常执行，但是数据不会回滚

### **Ⅴ. Environment**

- JDK version : 1.8
- OS :  macOS 10.15.2 

****各位有遇到的这种情况怎么解决吗****

**Comment by junjiex123** [comment]
我现在遇到了，如何解决，只能手动提交，手动回滚，不用注解吗

**Comment by haorenlin** [comment]
关掉了，是解决了么，我是只用了@GlobalTransactional。
代码大致如下：
`
//1调用A服务

//2本地修改

//3调用B服务

`
然后项目报错：io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = **********:8091:97709006117621760 status = AsyncCommitting, cause by globalSession not active] ]

seata报错：io.seata.core.exception.GlobalTransactionException: Could not register branch into global session xid = **********:8091:97710984377880576 status = AsyncCommitting, cause by globalSession not active

**Comment by junjiex123** [comment]
> 关掉了，是解决了么，我是只用了@GlobalTransactional。
> 代码大致如下：
> `
> //1调用A服务
> 
> //2本地修改
> 
> //3调用B服务
> 
> `
> 然后项目报错：io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = **********:8091:97709006117621760 status = AsyncCommitting, cause by globalSession not active] ]
> 
> seata报错：io.seata.core.exception.GlobalTransactionException: Could not register branch into global session xid = **********:8091:97710984377880576 status = AsyncCommitting, cause by globalSession not active

我也想知道怎么解决
