### ISSUE TITLE
执行事务时，global表中生成一条数据，branch表，lock表，undo_log表中无数据生成

### ISSUE THREAD

**Issue by pojun8866** [seata/seata#3181]
使用nacos1.3.2注册中心。
seata使用0.9.0版本，数据库mysql，
A工程调用B工程，采用
@DubboTransported(protocol = "dubbo")
@FeignClient
方式rpc调用。
在@GlobalTransactional方法中异常前打断点，global表中会生成一条数据，继续运行数据会被删除，branch表，lock表，undo_log表中始终无数据生成。
求大神指点。

**Comment by xiaoxiongmao-liu** [comment]
遇到同样问题，经过仔细检查，发现全局事务id没有传递到分支事务，原因是SeataFeignClient没有对FeignClient进行代理，但是启动加载项目的时候，SeataFeignClient加载了，暂时未解决，求大神指点下

**Comment by pojun8866** [comment]
> 遇到同样问题，经过仔细检查，发现全局事务id没有传递到分支事务，原因是SeataFeignClient没有对FeignClient进行代理，但是启动加载项目的时候，SeataFeignClient加载了，暂时未解决，求大神指点下，另外配置seata时，我把enableAutoDataSourceProxy设置成了false，感觉是这里影响的，但是不知道怎么改，这个配置不能改，这个改了项目启动会报错，和项目其他的包起冲突

我自己的原因 执行的sql是select语句所以没生成分支事务 不需要SeataFeignClient代理 代理数据源DataSourceProxy就行了
