### ISSUE TITLE
update 表名 set id = B where id = A 对这种SQL无法回滚

### ISSUE THREAD

**Issue by wangjing0716** [seata/seata#3182]
merge sql error, dbType postgresql, druid-1.1.16, sql : UPDATE 表名 SET  WHERE "id" = ?  

com.alibaba.druid.sql.parser.ParserException: syntax error, expect EQ, actual LITERAL_ALIAS pos 33, line 1, column 30, token LITERAL_ALIAS "id"

版本：
spring-cloud-alibaba-seata 2.2.0.RELEASE
seata-spring-boot-starter 1.3.0

**Comment by ChinaJeckXu** [comment]
啊这，，还有更新ID主键的这种SQL操作吗？好吧！

**Comment by wangjing0716** [comment]
是啊，比较特殊；
我们这种操作来源如下，
1）微服务之间的数据同步，通过接口调用，保持2边id一致，update 来 改变 JPA自动生成的id；
2）一个服务下，A表的记录也保存到 B表，（A表的记录B表一定有，B表的记录A表不一定有），保存到B表时，需ID和A表ID一致，也需要update主键；
反正就是有这种操作


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 上午10:41
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"明天你好"<2515847748@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] update 表名 set id = B where id = A 对这种SQL无法回滚 (#3182)





 
啊这，，还有更新ID主键的这种SQL操作吗？好吧！

**Comment by ChinaJeckXu** [comment]
> 是啊，比较特殊； 我们这种操作来源如下， 1）微服务之间的数据同步，通过接口调用，保持2边id一致，update 来 改变 JPA自动生成的id； 2）一个服务下，A表的记录也保存到 B表，（A表的记录B表一定有，B表的记录A表不一定有），保存到B表时，需ID和A表ID一致，也需要update主键； 反正就是有这种操作
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "seata/seata" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月19日(星期一) 上午10:41 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"明天你好"<2515847748@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] update 表名 set id = B where id = A 对这种SQL无法回滚 (#3182) 啊这，，还有更新ID主键的这种SQL操作吗？好吧！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这个需求的SQL场景貌似Insert replace 更合适一些。

**Comment by slievrly** [comment]
#3129

**Comment by wangjing0716** [comment]
Forbidding execute SQL which updates pk value?
使用seata, 禁止更改主键？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 中午1:18
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"明天你好"<2515847748@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] update 表名 set id = B where id = A 对这种SQL无法回滚 (#3182)





 
#3129

**Comment by l81893521** [comment]
After discussion, we decide prohibit update primary key, because seata base on primary key create before image and after image.

**Comment by l81893521** [comment]
I will close this issue later. If still have more question. Our waiting for your next report.
