### ISSUE TITLE
Seata 是否支持SqlServer

### ISSUE THREAD

**Issue by wqd0214** [seata/seata#3185]
我在使用Seata时报  io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder 的错误，于是我前往seata-all中去查找，未发现有SqlServer的实现，请问目前是不支持SqlServer吗？

![image](https://user-images.githubusercontent.com/17613111/95809435-57159680-0d41-11eb-8378-0aa856c1bbeb.png)

**Comment by wqd0214** [comment]
通过实现SqlServer相关插件完成支持。

**Comment by yourselfo** [comment]
遇到同样的问题 请问使用了什么插件

**Comment by wqd0214** [comment]
编写了SQLServer的实现，但目前没有解决完联合主键的问题。


| |
wqd_1994
|
|
wqd_1994@163.com
|
签名由网易邮箱大师定制


在2020年10月21日 15:42，wang jie<notifications@github.com> 写道：

遇到同样的问题 请问使用了什么插件

**Comment by kamyam** [comment]
2022年了还打算实现吗

**Comment by Acechengui** [comment]
同问???什么时候能支持sqlserver

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4033
