### ISSUE TITLE
seata可否支持tk.mybatis的通用接口？

### ISSUE THREAD

**Issue by yuanlin-work** [seata/seata#3192]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

seata可否支持tk.mybatis的通用接口？
如：
@Mapper
public interface ProductMapper extends BaseMapper<Product>

调用通用接口的insert或者update方法，并不会触发分支事务的rollback动作

**Comment by ls9527** [comment]
seata的AT模式用的是代理数据源的方式实现的。  跟你用通用mapper没有关系。 纯jdbc, spring jpa, mybatis-plus,通用mapper 都只是数据源上层的框架，  随便用哪个都能支持才对

**Comment by a364176773** [comment]
> seata的AT模式用的是代理数据源的方式实现的。 跟你用通用mapper没有关系。 纯jdbc, spring jpa, mybatis-plus,通用mapper 都只是数据源上层的框架， 随便用哪个都能支持才对

well
