### ISSUE TITLE
no available service 'default' found, please make sure registry config corre 异常

### ISSUE THREAD

**Issue by licheng1013** [seata/seata#3199]
三个服务同样的配置,,一个正确启动,其他挂掉....
seata 1.3.0

**Comment by wangliang181230** [comment]
基本上是你自己的配置问题。

**Comment by licheng1013** [comment]
除了  application.name 和端口 不一样其他的配置都一样,,一开始能正常运行两个服务,,改了下config.txt的数据库连接,导下nacos就只能运行一个服务....其他则no available service 'default' found, please make sure registry config corre
