### ISSUE TITLE
问大家一个问题。为什么seata不支持 代理 springboot自动装配的数据源

### ISSUE THREAD

**Issue by boychenfei** [seata/seata#3208]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
我们都知道seata是基于数据源代理来控制本地事务，
seata 0.9以后支持数据源自动代理。
那么为什么seata不支持  代理springboot自动装配的数据源呢？(需要独立配置数据源，使用springboot自动装配数据源就不行)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by l81893521** [comment]
Seata already support auto proxy in 1.3.0.
