### ISSUE TITLE
mongo可不可以用seata实现分布式事务

### ISSUE THREAD

**Issue by xqs41621** [seata/seata#3213]
mongo可不可以用seata实现分布式事务

**Comment by ls9527** [comment]
TCC模式可以用，AT 模式不行。AT模式必须是SQL规范的才行

**Comment by LiujunjieALiling** [comment]
> TCC模式可以用，AT 模式不行。AT模式必须是SQL规范的才行

会使MongoDB的性能降低的严重吗？

**Comment by ls9527** [comment]
AT 模式会解析你的SQL语句， 然后生成回滚日志。  MONGODB 生成不了。 
 TCC模式可以用，  不会降低MONGODB的性能。

**Comment by LiujunjieALiling** [comment]
> AT 模式会解析你的SQL语句， 然后生成回滚日志。 MONGODB 生成不了。
> TCC模式可以用， 不会降低MONGODB的性能。

MongoDB + ES 一致性保证也可以的吧 ？   性能也不会有影响吗？

**Comment by MrLiuFang** [comment]
MongoDB 的文档储存是有序的，建议只做新增，查询动作，修改的话要提前预留字段空间，修改前和修改后的字段大小应该一至，否则会发生文档前后移动现象将是灾难性的。删除必然会发生文档移动。所以根据官方的说法事物不事物已经不重要了。io会抗不住。
