### ISSUE TITLE
调用没有自动传递xid

### ISSUE THREAD

**Issue by tangyongjian-tz** [seata/seata#3217]
#seata1.3+nacos1.3 fegin 没有自动传递xid

调用方代码
 @GlobalTransactional(timeoutMills = 300000, name = "test_seate_all_transaction_name",rollbackFor = Exception.class )
    @Override
    public Object zhix(String tx) {
        String xId = RootContext.getXID();
        jdbcTemplate.update("update seata_test set name = 'basic_"+ UuidUtil.uuid() +"' where id = 1");
        String txt = checkRfidClient.textTx(xId);
        if(System.currentTimeMillis()%2 == 0)
        {
            System.out.println(1/0);
        }
        return FastMap.newDefaultInstance()
                .set("Tx txt",txt);
    }

#被调用方
    @RequestMapping(value = "/rfid/test")
    @Transactional
    public Object testTx(@RequestBody  String xId){
        RootContext.bind(xId);//必须指定，否则拿到null??
        jdbcTemplate.update("update seata_test set name = 'rfid_"+ UuidUtil.uuid() +"' where id = 1");
        return xId+"_testTx";
    }

**Comment by caohdgege** [comment]
检查一下你引入的依赖

**Comment by tangyongjian-tz** [comment]
#我是这样做的  

       <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.1.RELEASE</version>
             <exclusions>
                 <exclusion>
                     <groupId>io.seata</groupId>
                     <artifactId>seata-spring-boot-starter</artifactId>
                 </exclusion>
                 <exclusion>
                     <groupId>io.seata</groupId>
                     <artifactId>seata-all</artifactId>
                 </exclusion>
             </exclusions>
        </dependency>

**Comment by a364176773** [comment]
如果传递了就会自动bind，无须你手动bind

**Comment by tangyongjian-tz** [comment]
我重写过 feign.RequestInterceptor ，有关系吗

**Comment by ls9527** [comment]
看一下你的 RequestInterceptor.  按照例子来看， 你需要加入绑定XID到对象头的操作。

例如seata-samples项目中有这样一段： 

```
@Override
    public ClientHttpResponse intercept(HttpRequest httpRequest, byte[] bytes, ClientHttpRequestExecution clientHttpRequestExecution) throws IOException {
        HttpRequestWrapper requestWrapper = new HttpRequestWrapper(httpRequest);
        String xid = RootContext.getXID();
        if (StringUtils.isNotEmpty(xid)) {
            requestWrapper.getHeaders().add(RootContext.KEY_XID, xid);
        }

        return clientHttpRequestExecution.execute(requestWrapper, bytes);
    }
```

feign 才能把xid通过请求头带给被调用方

**Comment by tangyongjian-tz** [comment]
@ls9527 这些操作 spring-cloud-starter-alibaba-seata 帮我们做了

**Comment by ls9527** [comment]
spring-cloud-starter-alibaba-seata 凭什么要把 XID 的传递操作给做了？   

官方源码的 http 和 feign 的例子，都是需要自己搞定XID传递的。  

seata 项目的 io.seata.integration.http.DefaultHttpExecutor 加入了 TransactionPropagationIntercepter
seata-sample 项目的 feign 也是加入了 io.seata.samples.common.interceptor.SeataRestTemplateInterceptor 。

http 形式传递XID 一定是通过请求头。  这一点你可以在被调用方看看，  看看请求头有没有XID， 没有就是调用方的问题。有的话就是被调用方的解析问题

**Comment by tangyongjian-tz** [comment]
@ls9527  com.alibaba.cloud.seata.rest.SeataRestTemplateInterceptor ，不清楚为什么没有传递成功，还需要自己手动传递，但是解析成功了

**Comment by tangyongjian-tz** [comment]
谢谢大家，我这里已经解决了

**Comment by CleverFella** [comment]
> 谢谢大家，我这里已经解决了
麻烦问一下怎么解决的吗 我也遇到了相同的问题

**Comment by tangyongjian-tz** [comment]
自己在header里传递和解析 xid

**Comment by CleverFella** [comment]
> 自己在header里传递和解析 xid

![image](https://user-images.githubusercontent.com/43055449/97965278-10bdcf80-1df5-11eb-9731-eac6faa997f2.png)
我已经配置了还是有问题 服务器一直报警告
![image](https://user-images.githubusercontent.com/43055449/97965347-2e8b3480-1df5-11eb-84d8-33c41e8a143b.png)

**Comment by tangyongjian-tz** [comment]
@CleverFella  手动在过滤器中获取并绑定KEY_XID

**Comment by CleverFella** [comment]
> @CleverFella 手动在过滤器中获取并绑定KEY_XID

您好 有具体的实现代码吗

**Comment by tangyongjian-tz** [comment]
@CleverFella 你试试注入这个
@Bean
    public SeataHandlerInterceptor seataHandlerInterceptor(){
        return new SeataHandlerInterceptor();
    }

**Comment by CleverFella** [comment]
> @CleverFella 你试试注入这个
> @bean
> public SeataHandlerInterceptor seataHandlerInterceptor(){
> return new SeataHandlerInterceptor();
> }

![image](https://user-images.githubusercontent.com/43055449/97968489-a9eee500-1df9-11eb-99de-c7a6dd5ea79c.png)
是直接把bean注入到feignconfig里面吗

**Comment by tangyongjian-tz** [comment]
@CleverFella 可以，你试试

**Comment by CleverFella** [comment]
> @CleverFella 可以，你试试

还有服务器报这个警告，没用呢

**Comment by tangyongjian-tz** [comment]
所有服务都加了？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;CleverFella&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月3日(星期二) 下午5:47
收件人:&nbsp;&quot;seata/seata&quot;<seata@noreply.github.com&gt;;
抄送:&nbsp;&quot;tangyongjian-tz&quot;<664080004@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] 调用没有自动传递xid (#3217)

**Comment by CleverFella** [comment]
都加了呢

**Comment by tangyongjian-tz** [comment]
明天再看吧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;CleverFella&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月3日(星期二) 晚上6:03
收件人:&nbsp;&quot;seata/seata&quot;<seata@noreply.github.com&gt;;
抄送:&nbsp;&quot;tangyongjian-tz&quot;<664080004@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] 调用没有自动传递xid (#3217)

**Comment by CleverFella** [comment]
> 明天再看吧------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;CleverFella&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月3日(星期二) 晚上6:03 收件人:&nbsp;&quot;seata/seata&quot;<seata@noreply.github.com&gt;; 抄送:&nbsp;&quot;tangyongjian-tz&quot;<664080004@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] 调用没有自动传递xid (#3217)

好的

**Comment by zhousheng2** [comment]
@tangyongjian-tz @CleverFella 请问是怎么解决的？我现在使用seata1.4.0版本也出现了这个问题，可否贴一下代码

**Comment by spencexu** [comment]
> @tangyongjian-tz @CleverFella 请问是怎么解决的？我现在使用seata1.4.0版本也出现了这个问题，可否贴一下代码

<dependency>
            <groupId>com.alibaba.cloud</groupId>
            
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <version>2.2.0.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.3.0</version>
        </dependency>

这是我的seata配置方式，不需要手动传递xid

**Comment by spencexu** [comment]
> @tangyongjian-tz @CleverFella 请问是怎么解决的？我现在使用seata1.4.0版本也出现了这个问题，可否贴一下代码

```java
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <!--加入spring-cloud-alibaba-seata，解决xid不传递问题-->
    <artifactId>spring-cloud-alibaba-seata</artifactId>
    <version>2.2.0.RELEASE</version>
    <exclusions>
        <exclusion>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>io.seata</groupId>
    <artifactId>seata-spring-boot-starter</artifactId>
    <version>1.3.0</version>
</dependency>
```
这是我得修改方式，没有手动传递xid，使用的是seata1.3

**Comment by zhousheng2** [comment]
@spencexu 很感谢，我的问题已经解决了，我使用的是seata1.4.0版本，由于SC与seata兼容性有点问题，server端使用14.0版本，client端使用1.3.0版本，我的xid没传递是因为使用公司组件继承了WebMvcConfigurationSupport或实现了WebMvcConfigurer接口，我重写了此类，将SeataHandlerInterceptor拦截器添加进去即可解决

**Comment by zhousheng2** [comment]
另外，我总结了xid没传递的3种情况：
![image](https://user-images.githubusercontent.com/35722213/102573326-32ff7880-4129-11eb-907f-5b711b5d3fc6.png)

**Comment by zhangxiangfeng** [comment]
##### 场景 A-B
##### 服务A 都没有xid，日志如下：
```
DEBUG i.s.i.h.TransactionPropagationInterceptor xid in RootContext[null] xid in HttpContext[null]
```
server 1.4  
client 依赖jar 是1.4.0 seata-all

**Comment by tangyongjian-tz** [comment]
seata需要手动绑定 xid




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张相逢"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 晚上7:19
收件人: "seata/seata"<seata@noreply.github.com&gt;; 
抄送: "664080004"<664080004@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [seata/seata] 调用没有自动传递xid (#3217)





 
场景 A-B
 
服务A 都没有xid，日志如下：
 DEBUG i.s.i.h.TransactionPropagationInterceptor xid in RootContext[null] xid in HttpContext[null]  
server 1.4
 client 依赖jar 是1.4.0 seata-all

**Comment by zhousheng2** [comment]
不需要手动绑定xid，我的依赖配置如下:
` 
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        
       <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <version>2.2.0.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.3.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>druid</artifactId>
                    <groupId>com.alibaba</groupId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by 852675742** [comment]
> 不需要手动绑定xid，我的依赖配置如下:
> `
> 
> ```
>     
>     <dependency>
>         <groupId>org.springframework.cloud</groupId>
>         <artifactId>spring-cloud-starter-openfeign</artifactId>
>     </dependency>
>     
>    <dependency>
>         <groupId>com.alibaba.cloud</groupId>
>         <artifactId>spring-cloud-alibaba-seata</artifactId>
>         <version>2.2.0.RELEASE</version>
>         <exclusions>
>             <exclusion>
>                 <groupId>io.seata</groupId>
>                 <artifactId>seata-spring-boot-starter</artifactId>
>             </exclusion>
>         </exclusions>
>     </dependency>
>     <dependency>
>         <groupId>io.seata</groupId>
>         <artifactId>seata-spring-boot-starter</artifactId>
>         <version>1.3.0</version>
>         <exclusions>
>             <exclusion>
>                 <artifactId>druid</artifactId>
>                 <groupId>com.alibaba</groupId>
>             </exclusion>
>         </exclusions>
>     </dependency>
> ```
> 
> `
> @tangyongjian-tz 我的server端使用1.4.0版本，由于seata1.4.0与SC兼容性问题，client端使用1.3.0版本，你的xid需要手动传递，可能是你的项目组件继承了WebMvcConfigurationSupport或实现了WebMvcConfigurer接口

你说的是很对的，我之前也是碰到过项目中继承了WebMvcConfigurationSupport，添加了拦截器导致无法正常传递XID，只需要把SeataHandlerInterceptor注入进来，并添加到拦截器链路中即可，仅仅注入进来是不可以的，打断点不会进去，调试不易啊，还好搞好了

**Comment by DropOfJupiter** [comment]
> 我重写过 feign.RequestInterceptor ，有关系吗

我项目也重写了feign.RequestInterceptor ，所以需要手动绑定，将xid传递下去
