### ISSUE TITLE
一个版本一套配置，福报社是不想干了吗？

### ISSUE THREAD

**Issue by WswSummer15** [seata/seata#3225]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
1.1之前的配置改动确实有影响到了用户的迭代,从1.1之后,基本上都是维持原有配置就可用(除第三方配置中心,因为第三方配置注册中心会迭代后,增加配置,seata为了满足用户需求会跟进)
