### ISSUE TITLE
Add deflater compressor support for seata-compressor module.

### ISSUE THREAD

**Issue by dongzl** [seata/seata#3232]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information

Add deflater compressor support for seata-compressor module.

**Comment by dongzl** [comment]
Do we need to support `deflater compressor`? if need, please assign to me, I want to finish it, thanks!

**Comment by l81893521** [comment]
We will review it later.
