### ISSUE TITLE
zookeeper连接问题

### ISSUE THREAD

**Issue by farawayliu** [seata/seata#3265]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
不清楚是bug，还是环境问题。建议专业的测试进行验证下。情况如下：
seata：1.3.0
zookeeper：3.4.12
在seata的机器上，telnet zk的地址能通，zooInspector也能连上zk。但是seata启动就报zk连接超时的错。

我做了以下测试：
- seata原生依赖的zk是zookeeper-3.4.14.jar。我更换成3.4.12，seata启动正常。换回3.4.14，seata启动报错。
- seata直接连zk的地址，seata启动报错。seata连接宿主机映射zk的地址，seata启动正常。

第一个测试结果证明是seata依赖的zk版本有问题，第二测试结果证明是我的环境有问题。还需要进行进一步测试。

- JDK version : 1.8
- OS : centos 7
- Others:

**Comment by xingfudeshi** [comment]
Have you solved your problem？Please make sure seata can connect your zk server.

**Comment by farawayliu** [comment]
> Have you solved your problem？Please make sure seata can connect your zk server.

the problem is solved temporarily by replacing `zookeeper-3.4.12.jar`.

**Comment by hylyLLL** [comment]
> zookeeper

你好，请问解决了，我的seata-server服务器确保是能够与zk服务器通信的，但是seata-server就是不行，TM,RM都可以，就是TC不行
