### ISSUE TITLE
Error creating bean with name 'globalTransactionScanner'

### ISSUE THREAD

**Issue by crystallizes** [seata/seata#3266]
springboot2.3+seata1.4+dubbo2.7配置启动项目时一直报错
Exception encountered during context initialization - 
cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'globalTransactionScanner' defined in class path resource 
[com/example/db_comsumer/config/SeataAutoConfig.class]: 
Bean instantiation via factory method failed; 
nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: 
Factory method 'globalTransactionScanner' threw exception; 
nested exception is io.seata.common.exception.NotSupportYetException: config type can not be null

**Comment by ls9527** [comment]
要配置 seata.config.type=file.  当然要看你把配置中心的配置设置在哪里了

**Comment by ls9527** [comment]
要配置 seata.config.type=file.  当然要看你把配置中心的配置设置在哪里了

**Comment by crystallizes** [comment]
设了也不行，在resources目录下放了file.conf和registry.cof，seata就直接windows版运行，提供者正常运行，消费者一样的配置无法正常运行，重新新建一个项目配置也不行，太奇怪

**Comment by crystallizes** [comment]
> 要配置 seata.config.type=file. 当然要看你把配置中心的配置设置在哪里了

设了也不行，在resources目录下放了file.conf和registry.cof，seata就直接windows版运行，提供者正常运行，消费者一样的配置无法正常运行，重新新建一个项目配置也不行，太奇怪

**Comment by ls9527** [comment]
> > 要配置 seata.config.type=file. 当然要看你把配置中心的配置设置在哪里了
> 
> 设了也不行，在resources目录下放了file.conf和registry.cof，seata就直接windows版运行，提供者正常运行，消费者一样的配置无法正常运行，重新新建一个项目配置也不行，太奇怪

根据你目前提供的错误信息，  只能是 config.type 未配置的问题。  如果有其他问题， 需要提供更多的错误信息

**Comment by crystallizes** [comment]
> 要配置 seata.config.type=file. 当然要看你把配置中心的配置设置在哪里了

**Comment by crystallizes** [comment]
> 要配置 seata.config.type=file. 当然要看你把配置中心的配置设置在哪里了

**Comment by crystallizes** [comment]
> 要配置 seata.config.type=file. 当然要看你把配置中心的配置设置在哪里了

**Comment by crystallizes** [comment]
> 要配置 seata.config.type=file. 当然要看你把配置中心的配置设置在哪里了

一个新建的项目，windows版本下直接运行seata和zookeeper,里面就放了一个类SeataAutoConfig，resources下放了registry.conf 和file.conf，运行的时候就报那个错
=============================== SeataAutoConfig ==================================
@Configuration
public class SeataAutoConfig {
    @Autowired
    private DataSourceProperties dataSourceProperties;
    @Bean
    @Primary
    public DruidDataSource druidDataSource(){
        DruidDataSource druidDataSource = new DruidDataSource();
        druidDataSource.setUrl(dataSourceProperties.getUrl());
        druidDataSource.setUsername(dataSourceProperties.getUsername());
        druidDataSource.setPassword(dataSourceProperties.getPassword());
        druidDataSource.setDriverClassName(dataSourceProperties.getDriverClassName());
        druidDataSource.setInitialSize(0);
        druidDataSource.setMaxActive(180);
        druidDataSource.setMaxWait(60000);
        druidDataSource.setMinIdle(0);
        druidDataSource.setValidationQuery("Select 1 from DUAL");
        druidDataSource.setTestOnBorrow(false);
        druidDataSource.setTestOnReturn(false);
        druidDataSource.setTestWhileIdle(true);
        druidDataSource.setTimeBetweenEvictionRunsMillis(60000);
        druidDataSource.setMinEvictableIdleTimeMillis(25200000);
        druidDataSource.setRemoveAbandoned(true);
        druidDataSource.setRemoveAbandonedTimeout(1800);
        druidDataSource.setLogAbandoned(true);
        return druidDataSource;
    }
    @Bean
    public DataSourceProxy dataSourceProxy(DruidDataSource druidDataSource){
        return new DataSourceProxy(druidDataSource);
    }
    @Bean
    public SqlSessionFactory sqlSessionFactory(DataSourceProxy dataSourceProxy) throws Exception {
        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(dataSourceProxy);
        factoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath*:/mapper/*.xml"));
        return factoryBean.getObject();
    }
    @Bean
    public GlobalTransactionScanner globalTransactionScanner(){
        return new GlobalTransactionScanner("gts-seata-example", "my_test_tx_group");
    }
}
========================== registry.conf ======================
registry {
 type = "file"
 file {
  name = "file.conf"
 }
}
===========================  file.conf ============================
transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #enable heartbeat
  heartbeat = true
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
  shutdown {
    # when destroy server, wait seconds
    wait = 3
  }
  serialization = "seata"
  compressor = "none"
}
service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"
  #only support single node
  default.grouplist = "127.0.0.1:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
  #unit ms,s,m,h,d represents milliseconds, seconds, minutes, hours, days, default permanent
  max.commit.retry.timeout = "-1"
  max.rollback.retry.timeout = "-1"
}
client {
  rm {
    asyncCommitBufferLimit = 10000
    lock {
      retryInterval = 10
      retryTimes = 30
      retryPolicyBranchRollbackOnConflict = true
    }
    reportRetryCount = 5
    tableMetaCheckEnable = false
    reportSuccessEnable = false
    sqlParserType = druid
  }
  tm {
    commitRetryCount = 5
    rollbackRetryCount = 5
  }
  undo {
    dataValidation = true
    logSerialization = "jackson"
    logTable = "undo_log"
  }
  log {
    exceptionRate = 100
  }
}

## transaction log store
store {
  ## store mode: file、db
  mode = "db"

  ## file store
  file {
    dir = "sessionStore"

    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    max-branch-session-size = 16384
    # globe session size , if exceeded throws exceptions
    max-global-session-size = 512
    # file buffer size , if exceeded allocate new buffer
    file-write-buffer-cache-size = 16384
    # when recover batch read size
    session.reload.read_size = 100
    # async, sync
    flush-disk-mode = async
  }

  ## database store
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "druid"
    ## mysql/oracle/h2/oceanbase etc.
    db-type = "mysql"
    driver-class-name = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://127.0.0.1:3306/fsm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true"
    user = "root"
    password = "123456"
    min-conn = 1
    max-conn = 3
    global.table = "global_table"
    branch.table = "branch_table"
    lock-table = "lock_table"
    query-limit = 100
  }
}
lock {
  ## the lock store mode: local、remote
  mode = "remote"

  local {
    ## store locks in user's database
  }

  remote {
    ## store locks in the seata's server
  }
}
recovery {
  #schedule committing retry period in milliseconds
  committing-retry-period = 1000
  #schedule asyn committing retry period in milliseconds
  asyn-committing-retry-period = 1000
  #schedule rollbacking retry period in milliseconds
  rollbacking-retry-period = 1000
  #schedule timeout retry period in milliseconds
  timeout-retry-period = 1000
}

transaction {
  undo.data.validation = true
  undo.log.serialization = "jackson"
  undo.log.save.days = 7
  #schedule delete expired undo_log in milliseconds
  undo.log.delete.period = 86400000
  undo.log.table = "undo_log"
}

## metrics settings
metrics {
  enabled = false
  registry-type = "compact"
  # multi exporters use comma divided
  exporter-list = "prometheus"
  exporter-prometheus-port = 9898
}

support {
  ## spring
  spring {
    # auto proxy the DataSource bean
    datasource.autoproxy = false
  }
}

**Comment by ls9527** [comment]
registry.conf

```
registry {
  type = "file"
}
# 这个配置中心的配置是必须的
config {
  type = "file"
}
```

**Comment by Huzhen757** [comment]
> registry.conf
> 
> ```
> registry {
>   type = "file"
> }
> # 这个配置中心的配置是必须的
> config {
>   type = "file"
> }
> ```

谁说一定要配置file的？registry下面的这个type属性是可以指定其他的，file 、nacos 、eureka、redis、zk、consul、etcd3、sofa，配置哪个就用哪个，而不是必须
