### ISSUE TITLE
oracle数据库无效的列类型

### ISSUE THREAD

**Issue by Jkanon** [seata/seata#3267]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
oracle数据库，开启GlobalTransactional注解，插入操作都报无效的列类型，不开启事务就没有问题

### Ⅱ. Describe what happened
如上
Cause: java.sql.SQLException: 无效的列类型
; uncategorized SQLException; SQL state [99999]; error code [17004]; 无效的列类型; nested exception is java.sql.SQLException: 无效的列类型]

### Ⅲ. Describe what you expected to happen
正常插入数据

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
结合Mybatis-plus进行多数据源操作

### Ⅵ. Environment:

- JDK version :1.8
- OS : win7
- Others: seata-spring-boot-starter

**Comment by Jkanon** [comment]
ojdbc版本从6升级到8，问题解决

**Comment by jim1991** [comment]
非常感谢！！解决了我的问题~
