### ISSUE TITLE
在MySQL8.0数据库innodb模式下测试，只能回滚一个

### ISSUE THREAD

**Issue by crystallizes** [seata/seata#3269]
在环境seata1.4 + dubbo2.7,生产者端数据库回滚成功，消费者端一侧的数据库回滚失败。

========================= 消费者端发起测试 ============================
@RestController
public class LaunchController {

    @Resource
    private UsersService usersService;
    @Resource
    private OerderService oerderService;

    private boolean flag;

    @GlobalTransactional(name = "gts-seata-example")
    @Transactional
    @RequestMapping("/st")
    public void st() {
        System.out.println("开始全局事务。XID="+ RootContext.getXID());
        oerderService.insertData("75"); //消费者数据
        usersService.insertOrder("jobs",44); //生产者者数据
        if (!flag) {
            throw new RuntimeException("测试抛异常后，分布式事务回滚！");
        }
    }
}
========================= 生产者日志 ==========================
WARN 2024 --- ServiceLoader$InnerEnhancedServiceLoader : Load [io.seata.rm.datasource.undo.parser.ProtostuffUndoLogParser] class fail. io/protostuff/runtime/IdStrategy
INFO 2024 --- i.s.c.r.p.c.RmBranchRollbackProcessor    : rm handle branch rollback process:xid=172.25.48.1:8091:69356619103735808,branchId=69356623541309440,branchType=AT,resourceId=jdbc:mysql://127.0.0.1:3306/dbs,applicationData=null
INFO 2024 --- io.seata.rm.AbstractRMHandler            : Branch Rollbacking: 172.25.48.1:8091:69356619103735808 69356623541309440 jdbc:mysql://127.0.0.1:3306/dbs
INFO 2024 --- i.s.r.d.undo.AbstractUndoLogManager      : xid 172.25.48.1:8091:69356619103735808 branch 69356623541309440, undo_log deleted with GlobalFinished
INFO 2024 --- io.seata.rm.AbstractRMHandler            : Branch Rollbacked result: PhaseTwo_Rollbacked

========================= 消费者日志 ============================
INFO 9544 --- [p-nio-69-exec-5] io.seata.tm.TransactionManagerHolder     : TransactionManager Singleton io.seata.tm.DefaultTransactionManager@23715dbb
INFO 9544 --- [p-nio-69-exec-5] i.seata.tm.api.DefaultGlobalTransaction  : Begin new global transaction [172.25.48.1:8091:69356619103735808]
开始全局事务。XID=172.25.48.1:8091:69356619103735808
INFO 9544 --- i.seata.tm.api.DefaultGlobalTransaction  : [172.25.48.1:8091:69356619103735808] rollback status: Rollbacked
ERROR 9544 --- o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/st] due to exception [测试抛异常后，分布式事务回滚！]
java.lang.RuntimeException: 测试抛异常后，分布式事务回滚！
	at com.example.db_comsumer.Controller.LaunchController.st(LaunchController.java:39) ~[classes/:0.0.1-SNAPSHOT]

========================= seata控制台日志 ============================
INFO --- i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=172.25.48.1:8091:69356619103735808,extraData=null
,clientIp:127.0.0.1,vgroup:my_test_tx_group
INFO --- io.seata.server.coordinator.DefaultCore  : Rollback branch transaction successfully, xid = 172.25.48.1:8091:69356619103735808 branchId = 69356623541309440
INFO --- io.seata.server.coordinator.DefaultCore  : Rollback global transaction successfully, xid = 172.25.48.1:8091:69356619103735808.

**Comment by caohdgege** [comment]
只能回滚一个指的是？
oerderService.insertData 和 usersService.insertOrder 是远程调用插入还是本服务调用插入？

**Comment by crystallizes** [comment]
> oerderService.insertData 和 usersService.insertOrder
在本项目里插入---  oerderService.insertData("75"); //消费者数据
在调用另一个项目里插入---   usersService.insertOrder("jobs",44); //生产者者数据

========= 生产者新建一个项目，消费者建一个项目，然后在消费者里调用调用两个插入

**Comment by crystallizes** [comment]
> 只能回滚一个指的是？
> oerderService.insertData 和 usersService.insertOrder 是远程调用插入还是本服务调用插入？

**Comment by caohdgege** [comment]
oerderService 和 usersService 是在同一个服务里面的？

**Comment by crystallizes** [comment]
usersService 在一个服务里，oerderService 在另外一个服务里，然后在oerderService 服务里同时调用oerderService 和 usersService测试




------------------&nbsp;原始邮件&nbsp;------------------&nbsp;
发件人:                                                                                                                        "seata/seata"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 中午11:49
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"2831751548"<2831751548@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] 在MySQL8.0数据库innodb模式下测试，只能回滚一个 (#3269)





 
oerderService 和 usersService 是在同一个服务里面的？
