### ISSUE TITLE
请问哪里可以看到grpc的接口文档

### ISSUE THREAD

**Issue by JerryZhou343** [seata/seata#3271]
不懂Java 想要通过grpc的通信方式对接seata，但是翻遍了仓库没有找到对应的接口描述文件（proto）；请问哪位大佬通过grpc通信对接过seata，可以分享下经验吗？

**Comment by xingfudeshi** [comment]
Thank you, but Seata currently only supports Seata.For details about GRPC,please refers to https://github.com/seata/seata/tree/develop/integration/grpc/src/main/java/io/seata/integration/grpc.See if it helps.

**Comment by JerryZhou343** [comment]
现在不支持 GRPC 协议吗？大概看了下，server启动的时候listener上rpc消息解码器只有seata，没看到grpc协议相关监听。这个文件看了，是关于gprc server端的拦截器；
1. SEATA 现在能支持GRPC 通信吗？
2. 接口描述proto文件有吗？
