### ISSUE TITLE
Seata AT应用到线上，如何优雅升级？

### ISSUE THREAD

**Issue by LeechanX** [seata/seata#3272]
现在希望将我们线上业务用Seata AT模式方式升级，但是直接升级有个问题：

新老代码都在同时跑，如果涉及同一个资源的操作，那么会产生冲突，造成无法回滚。
请问贵团队可有一些优雅升级的建议吗？

**Comment by a364176773** [comment]
通过注册中心的group来划分新老client与server端隔离开新老版本的，然后client端的一些rpc，远程调用等，也可以利用微服务框架的配置，比如dubbo的group来隔离开老client端，等新版上线后，关掉老client端的流量入口，client端响应完毕后直接下线。
