### ISSUE TITLE
能否提供一个基于SpringBoot版的SAGA模式的sample

### ISSUE THREAD

**Issue by ghost0224** [seata/seata#3273]
能否像AT模式一样，SAGA模式也提供一个基于SpringBoot的sample版本，目前的sample工程中只有spring版的，与Springboot集成比较麻烦，要用到哪些配置项也不清楚。

**Comment by wangliang181230** [comment]
@ghost0224 ，看这个PR #2838 ，应该是你想要的吧。

**Comment by shelimingming** [comment]
我看这个pr还没有合并，那目前saga模式还支持springboot配置吗？

**Comment by wangliang181230** [comment]
你自己先把Properties和AutoConfiguration的类加到你自己的项目或框架里，就可以啦。
