### ISSUE TITLE
seata-server 是必须要启的吗？

### ISSUE THREAD

**Issue by ywf4026** [seata/seata#3276]
刚接触seata，发现文档有说要启动seata-server，这个是必须的吗？考虑到要系统要新加这么个依赖，会把原来系统变复杂了。请问是这样的吗，谢谢！

**Comment by ZaneGeng** [comment]
要启动，类似nacos注册中心一样

**Comment by xingfudeshi** [comment]
Yes.it must be started properly before you begin your global transaction.
