### ISSUE TITLE
seata回滚失败，status自动改成1

### ISSUE THREAD

**Issue by ZaneGeng** [seata/seata#3277]
1、@GlobalTransactional和@Transactional可以一起使用吗
2、mysql5.8使用seata回滚后，有个字段status回滚失败，会自动改成1，和奇怪

**Comment by caohdgege** [comment]
第一点见官网Q&A第22点
Q: 22. AT 模式和 Spring @Transactional 注解连用时需要注意什么 ？
A:
@Transactional 可与 DataSourceTransactionManager 和 JTATransactionManager 连用分别表示本地事务和XA分布式事务，大家常用的是与本地事务结合。当与本地事务结合时，@Transactional和@GlobalTransaction连用，@Transactional 只能位于标注在@GlobalTransaction的同一方法层次或者位于@GlobalTransaction 标注方法的内层。这里分布式事务的概念要大于本地事务，若将 @Transactional 标注在外层会导致分布式事务空提交，当@Transactional 对应的 connection 提交时会报全局事务正在提交或者全局事务的xid不存在。

第二点是什么表的status会变成1？如果这个表值的是undo_log的话，那这个是正常的。

**Comment by ZaneGeng** [comment]
> 第一点见官网Q&A第22点
> Q: 22. AT 模式和 Spring @transactional 注解连用时需要注意什么 ？
> A:
> @transactional 可与 DataSourceTransactionManager 和 JTATransactionManager 连用分别表示本地事务和XA分布式事务，大家常用的是与本地事务结合。当与本地事务结合时，@transactional和@GlobalTransaction连用，@transactional 只能位于标注在@GlobalTransaction的同一方法层次或者位于@GlobalTransaction 标注方法的内层。这里分布式事务的概念要大于本地事务，若将 @transactional 标注在外层会导致分布式事务空提交，当@transactional 对应的 connection 提交时会报全局事务正在提交或者全局事务的xid不存在。
> 
> 第二点是什么表的status会变成1？如果这个表值的是undo_log的话，那这个是正常的。

status是我的业务表一个字段，不是seata的undo_log表，在回滚时会莫名改成1

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/100192652-4b66e380-2f2d-11eb-8fdf-0e8956261f38.png)

**Comment by 178180793** [comment]
遇到了同样的问题，说一下解决的方案。
首先检查mysql的status的字段类型，如果是tinyint类型并且长度为1的话，
建议修改类型为int ,或者增加长度为2，因为mysql默认把tinyint(1)的当成了boolean类型。
所以存入undolog表的时候状态字段就变成1了。
修改之后seata就没问题了。
希望能帮到你。

**Comment by ZaneGeng** [comment]
> 遇到了同样的问题，说一下解决的方案。
> 首先检查mysql的status的字段类型，如果是tinyint类型并且长度为1的话，
> 建议修改类型为int ,或者增加长度为2，因为mysql默认把tinyint(1)的当成了boolean类型。
> 所以存入undolog表的时候状态字段就变成1了。
> 修改之后seata就没问题了。
> 希望能帮到你。

感谢分享，问题按此方法得以解决！

**Comment by huan415** [comment]
```yaml
spring.datasource.url: jdbc:mysql://ip:port/xxx?useUnicode=true&characterEncoding=utf-8&tinyInt1isBit=false
```
我也遇到过，是这样解决的（`tinyInt1isBit=false`）

**Comment by wangliang181230** [comment]
@huan415 @ZaneGeng @178180793 现在已通过代码修复该BUG，PR：https://github.com/seata/seata/pull/6068
