### ISSUE TITLE
undo_log needs to contain the primary key.

### ISSUE THREAD

**Issue by djkdeveloper** [seata/seata#3278]
版本：
spring-cloud-dependencies   Hoxton.SR8
spring-cloud-alibaba-dependencies 2.2.3.RELEASE
spring-cloud-starter-alibaba-seata  2.2.3.RELEASE
seata 1.3
nacos 1.3.2 
微服务加入 @GlobalTransactional 报错  说undo_log 没主键
手动加入主键后正常， 遇到异常也能正常回滚
但是我看文档说1.3 undo_log 是不需要主键的

**Comment by djkdeveloper** [comment]
重复代理

**Comment by cuixingrui** [comment]
怎么解决的？我这测试也遇到了这个问题
