### ISSUE TITLE
tcc 模式

### ISSUE THREAD

**Issue by djkdeveloper** [seata/seata#3279]
tcc模式我看也必须要要有undo_log表
我的理解 undo_log 表不是at模式用的吗？
tcc不是业务上的回滚吗 怎么也需要undo_log表的

**Comment by wangliang181230** [comment]
tcc的回滚是自定义开发的，它并不需要undo_log表。
但是tcc的幂等和防悬挂，需要一张本地表。目前该功能还在计划阶段。

**Comment by djkdeveloper** [comment]
我现在的场景是

**Comment by wangliang181230** [comment]
场景是？

**Comment by djkdeveloper** [comment]
额。。没了   已经解决了 是@localtcc加措地方了

**Comment by djkdeveloper** [comment]
额。。没了 已经解决了 是@localtcc加措地方了

**Comment by wangliang181230** [comment]
哦，就是群里的那位啊。好的。
