### ISSUE TITLE
seata 1.3  读写分离

### ISSUE THREAD

**Issue by djkdeveloper** [seata/seata#3280]
seata版本 1.3.0
目前的框架是springclod的 但是做了数据库的读写分离配置如下：
`   
 /**
     * 主库
     */
    @Bean(name = "master", destroyMethod = "close", initMethod = "init")
    @Primary
    @ConfigurationProperties(prefix = "spring.datasource.druid.master")
    public javax.sql.DataSource master() {
        return DataSourceBuilder.create().type(DruidDataSource.class).build();
    }

    /**
     * 从库
     */
    @Bean(name = "slave1")
    @ConfigurationProperties(prefix = "spring.datasource.druid.slave1")
    public javax.sql.DataSource slave1() {
        return DataSourceBuilder.create().type(DruidDataSource.class).build();
    }

    /**
     * 动态数据源
     */
    @Bean("dynamicDataSource")
    public javax.sql.DataSource dynamicDataSource() {
        DynamicDataSource dynamicDataSource = new DynamicDataSource();
        dynamicDataSource.setWriteDataSource(master());
        List<Object> reads = new ArrayList<>();
        reads.add(slave1());
        dynamicDataSource.setReadDataSources(reads);
        return dynamicDataSource;
    }

    /**
     * 事务管理器配置
     *
     * @return 返回事务管理器
     */
    @Bean
    public PlatformTransactionManager transactionManager() {
        return new LecshopTransactionManager(dynamicDataSource());
    }

    /**
     * mybatis配置
     */
    @Bean
    @ConfigurationProperties(prefix = "mybatis")
    public SqlSessionFactoryBean sqlSessionFactoryBean() throws IOException {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setMapperLocations(new PathMatchingResourcePatternResolver().getResources("classpath*:/mapper/**Mapper.xml"));
        sqlSessionFactoryBean.setDataSource(dynamicDataSource());
        return sqlSessionFactoryBean;
    }
`
目前的疑惑：
这个配置什么都没改  seata at模式我试过了能正常用
但是如果如果我配置了2个库的话 seata 怎么知道undo_log 要插读库还是写库？
还是说我上面要改下 应该改成什么样子 求大佬请教下

**Comment by caohdgege** [comment]
seata是用你执行dml的那个connection去插入undo_log的，读写分离的时候dml的connection肯定是连的写的库，所以undo_log也是走的写库

**Comment by djkdeveloper** [comment]
已解决
