### ISSUE TITLE
What's the Different?

### ISSUE THREAD

**Issue by lightClouds917** [seata/seata#33]
There are too many distributed transaction frameworks ,like tcc_transaction,byteTcc,Hmily,raincat .I  do not know how to choose them.

**Comment by sharajava** [comment]
will publish a wiki about principle and design later. in short, Fescar focus on easy-to-use (without requirements of design on business layer) and high-performance.

**Comment by lightClouds917** [comment]
Do I need to worry about idempotency of a operation?

**Comment by tinycedar** [comment]
> There are too many distributed transaction frameworks ,like tcc_transaction,byteTcc,Hmily,raincat .I do not know how to choose them.

Have you tried use one of above frameworks ?

**Comment by lightClouds917** [comment]
Hmily,raincat ,But our company is using LCN.I am trying byteTcc now.

**Comment by cullenx** [comment]
> Do I need to worry about idempotency of a operation?

me too

**Comment by tinycedar** [comment]
> > Do I need to worry about idempotency of a operation?
> 
> me too

No, you don't. Global transaction will be rollback if exception occurs within any branch transaction, so it it just like local transaction.
