### ISSUE TITLE
如何用AT模式处理分布式数据库的场景

### ISSUE THREAD

**Issue by zhenglzh** [seata/seata#3302]
AT模式下客户端建了一个undolog 和本地事务一起提交，当是分布式数据库 在不同数据下， 如order 做了8个分片，这时的undolog也得跟着做8个分片，库存 一个分片 ，undolog也是一个分片，  目前seata 应该是全局的undolog 该如何解决这种情况呢

**Comment by 726411951** [comment]
用sharding jdbc分片的么，那边的github上有适配seata的example，附上地址可以看一看
https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/transaction-example/transaction-base-seata-spring-boot-example

**Comment by zhenglzh** [comment]
> 用sharding jdbc分片的么，那边的github上有适配seata的example，附上地址可以看一看
> https://github.com/apache/shardingsphere/tree/master/examples/shardingsphere-jdbc-example/transaction-example/transaction-base-seata-spring-boot-example

恩谢谢 大概了解了，在不同分片处理的时候 ，undolog 跟随着也是当前分片 所以还是可以一个事务内提交

**Comment by tjptoby** [comment]
请问这样的话，分片后你的性能能上去吗
