### ISSUE TITLE
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'dataSource' is expected to be of type 'io.seata.rm.datasource.DataSourceProxy' but was actually of type 'com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$2c292ce9'

### ISSUE THREAD

**Issue by lehug** [seata/seata#3305]
### Ⅰ. Issue Description
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'dataSource' is expected to be of type 'io.seata.rm.datasource.DataSourceProxy' but was actually of type 'com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$2c292ce9'

### Ⅱ. Describe what happened

仅仅的改动是 升级了下版本
implementation("io.seata:seata-spring-boot-starter:1.3.0")  改为 implementation("io.seata:seata-spring-boot-starter:1.4.0")

DataSourceConfiguration 这个配置没有做改动

@Configuration
public class DataSourceConfiguration {

    @Bean
    @ConfigurationProperties(prefix = "spring.datasource")
    public DataSource druidDataSource() {
        return new DruidDataSource();
    }

    @Primary
    @Bean("dataSource")
    public DataSourceProxy dataSource(DataSource druidDataSource) {
        return new DataSourceProxy(druidDataSource);
    }

    @Bean
    public SqlSessionFactory sqlSessionFactory(DataSourceProxy dataSourceProxy) throws Exception {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSourceProxy);
        sqlSessionFactoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath*:/mapper/*.xml"));
        sqlSessionFactoryBean.setTransactionFactory(new SpringManagedTransactionFactory());
        return sqlSessionFactoryBean.getObject();
    }

}

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : openjdk 11
- OS : deepin linux
- Others:

ps:
https://github.com/seata/seata-samples/blob/master/springcloud-eureka-feign-mybatis-seata/pom.xml
这个demo为何不更新去使用com.alibaba.cloud:spring-cloud-starter-alibaba-seata:2.2.3.RELEASE ？

**Comment by xingfudeshi** [comment]
seata-spring-boot-starter do will the auto configurations,please try to remove these code:
```
@Primary
@Bean("dataSource")
public DataSourceProxy dataSource(DataSource druidDataSource) {
    return new DataSourceProxy(druidDataSource);
}
```

**Comment by lehug** [comment]
> seata-spring-boot-starter do will the auto configurations,please try to remove these code:
> 
> ```
> @Primary
> @Bean("dataSource")
> public DataSourceProxy dataSource(DataSource druidDataSource) {
>     return new DataSourceProxy(druidDataSource);
> }
> ```

not well for me.

**Comment by xingfudeshi** [comment]
Can paste exception traces?

**Comment by xingfudeshi** [comment]
![image](https://user-images.githubusercontent.com/24457941/100690769-3a512300-33c2-11eb-8892-77252506c7f5.png)

**Comment by lehug** [comment]
> Can paste exception traces?

@Bean
public SqlSessionFactory sqlSessionFactory(DataSourceProxy dataSourceProxy) throws Exception {
    SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
    sqlSessionFactoryBean.setDataSource(dataSourceProxy);
    sqlSessionFactoryBean.setMapperLocations(new PathMatchingResourcePatternResolver()
            .getResources("classpath*:/mapper/*.xml"));
    sqlSessionFactoryBean.setTransactionFactory(new SpringManagedTransactionFactory());
    return sqlSessionFactoryBean.getObject();
}

我把上面的注释掉，然后好了～

**Comment by xingfudeshi** [comment]
Good!

**Comment by myideato** [comment]
> > 可以粘贴异常痕迹吗？
> 
> @bean
> 公共SqlSessionFactory sqlSessionFactory（DataSourceProxy dataSourceProxy）引发异常{
> SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean（）;
> sqlSessionFactoryBean.setDataSource（dataSourceProxy）;
> sqlSessionFactoryBean.setMapperLocations（new PathMatchingResourcePatternResolver（）.
> getResources（“ classpath *：/ mapper / *。xml”））;
> sqlSessionFactoryBean.setTransactionFactory（new SpringManagedTransactionFactory（））;
> 返回sqlSessionFactoryBean.getObject（）;
> }
> 
> 我把上面的注释掉，然后好了〜

但这样注释掉，分支事务失效了，我经历过

**Comment by lehug** [comment]
> 但这样注释掉，分支事务失效了，我经历过

求助，那你是怎么解决的？

**Comment by guanayan** [comment]
求助，这是一个大众性的问题，We need help!

**Comment by guanayan** [comment]
我的application.yml中多加了这个，OK了
`seata:
  #取消datasource自动代理（此处尤为重要）
  enable-auto-data-source-proxy: false`

**Comment by lixiaoabc** [comment]
> 我的application.yml中多加了这个，OK了
> `seata: #取消datasource自动代理（此处尤为重要） enable-auto-data-source-proxy: false`

你这样关闭了分布式事务，没有把数据源交给seata代理

**Comment by lehug** [comment]
```
步骤三：数据源代理(不支持自动和手动配置并存,不支持XA数据源自动代理)
0.9.0版本开始seata支持自动代理数据源
    1.1.0: seata-all取消属性配置，改由注解@EnableAutoDataSourceProxy开启，并可选择jdk proxy或者cglib proxy
    1.0.0: client.support.spring.datasource.autoproxy=true
    0.9.0: support.spring.datasource.autoproxy=true
手动配置可参考下方的例子
    @Primary
    @Bean("dataSource")
    public DataSourceProxy dataSource(DataSource druidDataSource) {
    	//AT 代理 二选一
        return new DataSourceProxy(druidDataSource);
        //XA 代理
        return new DataSourceProxyXA(druidDataSource)
    }
```
@guanayan 官网这样写的,改成 @EnableAutoDataSourceProxy,不再手动写这个bean了
