### ISSUE TITLE
找不到io.seata.serializer.protobuf.generated这个包，是不是没有提交代码？

### ISSUE THREAD

**Issue by chincelyluo** [seata/seata#3315]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by suichen** [comment]
mvn clean package 后自动生成

**Comment by nikorliu** [comment]
> * [ ]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> ### Ⅰ. Issue Description
> ### Ⅱ. Describe what happened
> If there is an exception, please attach the exception trace:
> 
> ```
> Just paste your stack trace here!
> ```
> 
> ### Ⅲ. Describe what you expected to happen
> ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> 1. xxx
> 2. xxx
> 3. xxx
> 
> ### Ⅴ. Anything else we need to know?
> ### Ⅵ. Environment:
> * JDK version :
> * OS :
> * Others:
执行 seata-serializer工程下的 mvn protobuf:compile就可以生成相应的代码了
