### ISSUE TITLE
Execute the test method in AppTest error --tx_read_only

### ISSUE THREAD

**Issue by duanyaxin** [seata/seata#332]
将对应module下面的pom依赖jar包mysql-connector-java(5.1.35)，改成5.1.45解决问题

**Comment by kingj1261** [comment]
I also meet similar question ,after search in google i found the reason because of the version of mysql-connector-jar is not suitable of the mysql server you used,for example 

mysql  Ver 8.0.13 for osx10.13 on x86_64 (Homebrew) should use mysql connector version of 8.xx

**Comment by leizhiyuan** [comment]
please retest it  based on the latest code, thanks.

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
