### ISSUE TITLE
when the TM was closed, the lock not release. So when the TM reopen, the lock is conflict

### ISSUE THREAD

**Issue by xyzhimo** [seata/seata#333]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
when RM register branch to TC, and execute the report method, i debug a breakpoint on the `AbstractDMLBaseExecutor#executeAutoCommitTrue` at the **return** statement, then i close the TM, consume the breakpoint, i found the undo log exists the db, and i reopen the TM, the lock key was still existed.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
1. the undo log was not deleted.
2. the branch transaction lock key was dead, but not release.

### Ⅲ. Describe what you expected to happen
1. the undo log was deleted.
2. the lock key was released by TC.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. breakpoint on the `AbstractDMLBaseExecutor#executeAutoCommitTrue` at the **return** statement.
2. close the TM.
3. consume the breakpoint.
4. reopen the TM

### Ⅴ. Anything else we need to know?
i think the TM was closed, but the TC not realized, so the TC still hold the lock, and in the time, The RM was not closed.

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
