### ISSUE TITLE
支持不带 file: 前缀的文件路径

### ISSUE THREAD

**Issue by hoverruan** [seata/seata#3344]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

在一次 docker 方式配置 SEATA_CONFIG_NAME 时，忘了加配置文件路径加上 file: 前缀，导致没有读取我们指定的配置文件

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

支持 SEATA_CONFIG_NAME=/root/seata-config/registry 这样的配置格式，
因为这比较符合大家日常的习惯，几乎不需要文档说明

## Other related information

如果可以的话，可以在官网增加文件路径的格式说明

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/101428317-6ed15b80-393b-11eb-8ff9-4ac8673ab03f.png)
