### ISSUE TITLE
全局事务回滚。

### ISSUE THREAD

**Issue by zhouixi** [seata/seata#3347]
createOrder 创建订单没有加seata 相关的注解。
在business出现异常的时候。是如何被全局事务管理 ，并回滚的。

**Comment by a364176773** [comment]
通过发起者传递xid，纳入分支事务，当发起者调用参与者的服务异常的时候，或者发起者自身异常，就会向tc告知二阶段状态，如果是回滚，tc就会同步下发到rm去回滚

**Comment by zhouixi** [comment]
> 通过发起者传递xid，纳入分支事务，当发起者调用参与者的服务异常的时候，或者发起者自身异常，就会向tc告知二阶段状态，如果是回滚，tc就会同步下发到rm去回滚

就是说。所到之处。留了种子的，都会依次回滚？xid起作用？他是怎么知道xid对应哪个服务的。
