### ISSUE TITLE
How about use 'mvn versions' to update version ? 

### ISSUE THREAD

**Issue by lovepoem** [seata/seata#335]
## Why you need it?

https://github.com/alibaba/fescar/blob/40ea4eb9276eeeca17f9caecdea5ffe0b49ce292/changeVersion.sh#L4

I think replacement is not a very good method 

## How it could be?
  What about use `mvn versions:set -DnewVersion=NEW_VERSION`

**Comment by slievrly** [comment]
@lovepoem I will try

**Comment by leizhiyuan** [comment]
now it has been supported by another way.

I will close the issue, if you have other questions, please reopen it or create a new one
