### ISSUE TITLE
Seata支持故障转移嘛？

### ISSUE THREAD

**Issue by wtlihao** [seata/seata#3352]
环境：Seata-Server两台集群
测试用例：
业务发起请求过程中，命中一台Seata-Server的时候 突然关闭这台，发现报了NPE错误，请问会有这个情况嘛？

**Comment by slievrly** [comment]
@wtlihao Pls paste the error stack information.

**Comment by a364176773** [comment]
> 环境：Seata-Server两台集群
> 测试用例：
> 业务发起请求过程中，命中一台Seata-Server的时候 突然关闭这台，发现报了NPE错误，请问会有这个情况嘛？

有可能，这个是基于你的注册中心是什么且注册中心的健康检查是如何做的，即使是dubbo，springcloud服务，宕机时，也不能完全保证能瞬间转移到另一台节点上。

**Comment by wtlihao** [comment]
已解决，应该request进来seata-server执行 瞬间运维通过kill -9命令杀掉纪进程了
