### ISSUE TITLE
java.sql.SQLException:  Failed to fetch schema of ...

### ISSUE THREAD

**Issue by PingWang201209** [seata/seata#3353]
测试环境
----------------------
nacos		1.2.1
seata server	1.4.0
seata-all		1.4.0
sharding-jdbc	4.0.1

问题描述
----------------------
单独使用 seata AT、XA、TCC 都是正常的
单独使用 sharding-jdbc 	   都是正常的

但，两者结合一起就出现下面的问题
---------------
java.sql.SQLException: 
Failed to fetch schema of t_storage

Caused by: 
io.seata.common.exception.ShouldNeverHappenException: 
Could not found any index in the table: t_storage

get tablemeta failed

可以确定如下
---------------
1）表对应的主键、索引在 information_schema 存在
2）jdbc 连接串目前已经添加 useInformationSchema=false
3）seata.client.rm.table-meta-check-enable = false

**Comment by slievrly** [comment]
@elim2wang show index from t_storage

**Comment by elim2wang** [comment]
> @elim2wang show index from t_storage

![image](https://user-images.githubusercontent.com/75713016/101602718-7d9e3800-3a39-11eb-9657-144cb133b97d.png)

**Comment by elim2wang** [comment]
mysql> show index from t_storage;
+-----------+------------+----------------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table     | Non_unique | Key_name       | Seq_in_index | Column_name    | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+-----------+------------+----------------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| t_storage |          0 | PRIMARY        |            1 | id             | A         |           1 |     NULL | NULL   |      | BTREE      |         |               |
| t_storage |          0 | commodity_code |            1 | commodity_code | A         |           1 |     NULL | NULL   | YES  | BTREE      |         |               |
+-----------+------------+----------------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+

**Comment by elim2wang** [comment]
today i debug raw code into MysqlTableMetaCache.java, found schemaName+catalogName is not expected in sharding-jdbc,
in this case sharding-jdbc will directly return const 'logic-db', so exception will throw. i'm not sure change current logic like below:
![image](https://user-images.githubusercontent.com/75713016/101603583-c0acdb00-3a3a-11eb-80cc-bc7c25abbc14.png)
![image](https://user-images.githubusercontent.com/75713016/101603605-c7d3e900-3a3a-11eb-8665-f236d70403aa.png)

**Comment by slievrly** [comment]
@elim2wang thanks for your feedback.

**Comment by wuchuanpeng2018** [comment]
try sharding-jdbc 4.0.1 to sharding-jdbc 4.1.0

**Comment by PingWang201209** [comment]
yes, i changed from 4.0.1 to 4.1.0. it is expected. thk a ton
