### ISSUE TITLE
docker容器开放的端口不是8091，指定启动端口，并且注册到nacos的问题

### ISSUE THREAD

**Issue by shiersong** [seata/seata#3358]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
我们是把seata server放到docker中启动（采用的是AT模式），但是docker中暴露的端口不是8091

### Ⅱ. Describe what happened
无论怎么样设置启动参数，启动的端口始终是8091，并且注册到nacos的端口也始终是8091
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
希望在docker容器中，能够通过启动参数设置启动端口，设置暴露给nacos的端口

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
针对上面说的两个问题，简单的来说，我们是不是得这样做：
1、修改seata/server/src/main/java/io/seata/server/env/ContainerHelper.java中的isRunningInContainer方法，注释掉方法中所有的逻辑，然后让这个方法直接返回false;
2、指定一个暴露给nacos的端口的启动参数，然后修改seata/server/src/main/java/io/seata/server/Server.java文件中的main方法，将这一行设置XID端口的代码XID.setPort(nettyRemotingServer.getListenPort());改成按照这个启动参数指定的端口设置XID端口。

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
http://seata.io/zh-cn/docs/ops/deploy-by-docker.html

**Comment by shiersong** [comment]
谢谢您！
非常感谢！
这个文档我倒是看过。
主要是我们这边的docker的配置（包括暴露什么样的端口）不是我们这边掌控的（实质上是别人做了一个docker容器给我们用，但是暴露的端口、映射的端口都不是8091），所以咨询了这个问题。
