### ISSUE TITLE
rollback should be done immediately when the current XA transaction is abnormal

### ISSUE THREAD

**Issue by a364176773** [seata/seata#3361]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
If the current xa branch is abnormal, the rollback function will be called, and at this time, the xa rollback of this resource is not performed, but it will be executed after the second-stage notification, which will make the data lock longer.
And after rollback in one stage, you can directly report the state of the first stage of the branch, which can make the server reduce the number of operations to issue notification information
当前xa分支如果异常,会调用rollback函数,而此时并没有对此资源进行xa rollback,而是等到了二阶段通知才执行,这会让数据锁定的时间更长.
且当一阶段状态为rollback后,可直接执行xarollback,直接上报分支一阶段状态,可使server减少一次下发通知信息

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lj2018110133** [comment]
Please assign this task to me
