### ISSUE TITLE
seata 1.4  调用feign的时候xid为空

### ISSUE THREAD

**Issue by cslvista1** [seata/seata#3366]
环境：
seata 1.4
oracle 11g
XA模式
Spring Cloud 

问题说明：
A通过调用feign调用B，在A的函数体里调用RootContext.getXID()有值，但是调用feign的时候，发现RootContext.getXID()为null。导致调用feign后，在B函数里RootContext.getXID()也为null,B返回后发现在A里再次调用RootContext.getXID()又正常了，这是怎么回事，如果我手动配置拦截器，加上requestTemplate.header("TX_XID", xid); 那么在B里调用RootContext.getXID()也是正常的。

**Comment by slievrly** [comment]
@cslvista1 use spring-cloud-starter-alibaba-seata（spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-seata/pom.xml）dependency？

**Comment by cslvista1** [comment]
> @cslvista1 use spring-cloud-starter-alibaba-seata（spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-seata/pom.xml）dependency？
这是我的配置
		<dependency>
			<groupId>io.seata</groupId>
			<artifactId>seata-all</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-seata</artifactId>
			<version>2.0.0.RELEASE</version>
			<exclusions>
				<exclusion>
					<artifactId>seata-all</artifactId>
					<groupId>io.seata</groupId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by cslvista1** [comment]
> @cslvista1 use spring-cloud-starter-alibaba-seata（spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-seata/pom.xml）dependency？
这是我的配置，请您指教

<dependency>
       <groupId>io.seata</groupId>
      <artifactId>seata-all</artifactId>
      <version>1.4.0</version>
</dependency>
     <dependency>
     <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
   <version>2.0.0.RELEASE</version>
   <exclusions>
       <exclusion>
       <artifactId>seata-all</artifactId>
      <groupId>io.seata</groupId>
      </exclusion>
     </exclusions>
</dependency>

**Comment by MentosL** [comment]
1.4版本中加入了TransactionPropagationIntercepter用来解决的

**Comment by amykiki** [comment]
我也遇到这个问题了， 回退使用seata-spring-boot-starter 1.3.0的版本xid就有了

**Comment by a364176773** [comment]
需要注册TransactionPropagationIntercepter

**Comment by dinghuang** [comment]
如果你的feign用了hystrix，如果是信号量的模式就没问题，如果是线程池的模式，就需要修改策略，网上有例子，具体是
extends HystirxConcurrencyStrategy，然后重写他的warpCallable方法，RootContext.getXID(),然后传递到RequestAttributes，
最后你写一个feign的拦截器，就可以拿到这个XID，手动放到header里面，就好了

**Comment by DropOfJupiter** [comment]
@Slf4j
@Component
public class FeignRequestInterceptor implements RequestInterceptor {

	@Override
	public void apply(RequestTemplate requestTemplate) {
			String seataXid= RootContext.getXID();
			if (StringUtils.isNotBlank(seataXid)) {
				requestTemplate.header(RootContext.KEY_XID,seataXid);
			}
			log.info("Feign拦截请求路径添加头部信息：{}", JSON.toJSONString(requestTemplate.headers()));
		}
	}
}
我是这么解决的，把xid放头部传递下去

**Comment by DropOfJupiter** [comment]
> @slf4j
> @component
> public class FeignRequestInterceptor implements RequestInterceptor {
> 
> ```
> @Override
> public void apply(RequestTemplate requestTemplate) {
> 		String seataXid= RootContext.getXID();
> 		if (StringUtils.isNotBlank(seataXid)) {
> 			requestTemplate.header(RootContext.KEY_XID,seataXid);
> 		}
> 		log.info("Feign拦截请求路径添加头部信息：{}", JSON.toJSONString(requestTemplate.headers()));
> 	}
> }
> ```
> 
> }
> 我是这么解决的，把xid放头部传递下去

但如果feign使用了hystrix，需要将熔断策略从线程池改成信号量
![image](https://user-images.githubusercontent.com/23180104/129474370-fb4c7637-f927-41b3-b8bc-4891b34ea241.png)
