### ISSUE TITLE
The data in undo_log has not been deleted. How to distinguish whether the commit fails or the rollback delete fails.

### ISSUE THREAD

**Issue by Rich1-King** [seata/seata#337]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by JohnAddison** [comment]
if i use my definition exception extends RuntimeException; transaction rollbacked,but undo_log has not been deleted。

**Comment by JohnAddison** [comment]
if i use my definition exception extends RuntimeException; transaction rollbacked,but undo_log has not been deleted。 fescar version: 0.4.2

**Comment by leizhiyuan** [comment]
maybe you should use global_table and branch_table to ensure  after 0.6.0

**Comment by Rich1-King** [comment]
> maybe you should use global_table and branch_table to ensure after 0.6.0

Thanks, you are right. I use 0.8.0 now.
