### ISSUE TITLE
globalTransactionScanner listener optimize

### ISSUE THREAD

**Issue by a364176773** [seata/seata#3377]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
when disableGlobalTransaction is true, it means that the global transaction is not currently enabled. At this time, you need to monitor the change of disableGlobalTransaction to initialize the component, and if the initial value of disableGlobalTransaction is false, then there is no need to monitor disableGlobalTransaction
在disableGlobalTransaction为true时，说明目前未开启全局事务，此时需要监听disableGlobalTransaction的变化来初始化组件，而如果disableGlobalTransaction一开始的值为false，那么无需进行监听disableGlobalTransaction

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lj2018110133** [comment]
Please give me the task
