### ISSUE TITLE
Seata1.4.x 版本，DataSourceProxy 启动后，数据源代理成功，执行一次后，数据源代理失效

### ISSUE THREAD

**Issue by zhangxiangfeng** [seata/seata#3389]
**Seata1.4.x 版本，DataSourceProxy 启动后，数据源代理成功，执行一次后，数据源代理失效**

**如何判断到这个情况？**

> debug 运行项目，断点打到：io.seata.rm.datasource.DataSourceProxy#getConnection()

第一次断点停住了，放开后，重新发请求，断点失效了。查看内存数据，如下图：

![微信截图_20201218193546](https://user-images.githubusercontent.com/10842186/102610528-50076c00-4168-11eb-860b-de3085cc98ac.png)

**Comment by a364176773** [comment]
请提供复现demo,1.4.x我测试过,并无此问题
