### ISSUE TITLE
buildAfterImageSQL时，如果更新语句的字段是库名加上表名字段getUpdateColumns获取不到更新字段

### ISSUE THREAD

**Issue by sustly** [seata/seata#3395]
buildAfterImageSQL时，如果数据库链接是全称getUpdateColumns获取不到更新字段。
如果数据库链接，如update seata.test.info，其中seata为库名字，test是表名，
@Override
    public List<String> getUpdateColumns() {
        List<SQLUpdateSetItem> updateSetItems = ast.getItems();
        List<String> list = new ArrayList<>(updateSetItems.size());
        for (SQLUpdateSetItem updateSetItem : updateSetItems) {
            SQLExpr expr = updateSetItem.getColumn();
            if (expr instanceof SQLIdentifierExpr) {
                list.add(((SQLIdentifierExpr)expr).getName());
            } else if (expr instanceof SQLPropertyExpr) {
                // 这里拿出来的owner是seata.test，会把它当作SQLPropertyExpr
                SQLExpr owner = ((SQLPropertyExpr)expr).getOwner();
                if (owner instanceof SQLIdentifierExpr) {
                    list.add(((SQLIdentifierExpr)owner).getName() + "." + ((SQLPropertyExpr)expr).getName());
                }
            } else {
                throw new SQLParsingException("Unknown SQLExpr: " + expr.getClass() + " " + expr);
            }
        }
        return list;
    }

如果更新语句为： update seata.test set seata.test.info = "test" where seata.test.id = 1，则getUpdateColumns返回值是一个空的list

**Comment by slievrly** [comment]
@sustly which seata version do u use？

**Comment by sustly** [comment]
> @sustly which seata version do u use？

seata-all-1.4.1

**Comment by sustly** [comment]
> @sustly which seata version do u use？

@slievrly seata-all-1.4.1

**Comment by sustly** [comment]
@slievrly 如果更新语句为： update seata.test set seata.test.info = "test" where seata.test.id = 1，则getUpdateColumns返回值是一个空的list

**Comment by caohdgege** [comment]
> @slievrly 如果更新语句为： update seata.test set seata.test.info = "test" where seata.test.id = 1，则getUpdateColumns返回值是一个空的list

问个问题，如果你的jdbc连到了A库，然后你的updateSQL的表名是 B.table_name，那么对应的undo_log你要放在哪里，A还是B？

**Comment by sustly** [comment]
@caohdgege 我是指定了一个专门的undo_log表，在某个库里
