### ISSUE TITLE
seata feign 开启降级事务不回滚怎么处理

### ISSUE THREAD

**Issue by MichealJou** [seata/seata#3398]

**Comment by MichealJou** [comment]
seata feign 开启降级事务不回滚怎么处理

**Comment by slievrly** [comment]
hystrix fallback should throw execption.

**Comment by flightefore** [comment]
手动抛错，不然catch住错误就不会往上回滚事件

**Comment by a364176773** [comment]
https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo﻿ 参考这个demo的处理

**Comment by MichealJou** [comment]
已经抛了 关闭feign 降级就好用 开启就不能回滚
