### ISSUE TITLE
A服务调用B服务时，远程调用的B服务接口如果集成了jboss，那么B对应的分支事务没有注册到seata服务端，发生异常不会全局回滚

### ISSUE THREAD

**Issue by beyond233** [seata/seata#3399]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@beyond233 Does the data source of service B use DatasourceProxy?

**Comment by beyond233** [comment]
> @ beyond233服务B的数据源是否使用DatasourceProxy？

用了 ，我项目里依赖的是spring-cloud-starter-alibaba-seata包，application配置也配置了enable-auto-data-source-proxy为true

**Comment by beyond233** [comment]
> @beyond233 Does the data source of service B use DatasourceProxy?

我刚刚断点调试的时候发现B服务里MYSQLInsertExecutor执行插入SQL的时候报错，说找不到xid: 
java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.56.1:8091:85053037214699520, may be has finished.] ]

**Comment by slievrly** [comment]
> > @beyond233 Does the data source of service B use DatasourceProxy?
> 
> 我刚刚断点调试的时候发现B服务里MYSQLInsertExecutor执行插入SQL的时候报错，说找不到xid:
> java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.56.1:8091:85053037214699520, may be has finished.] ]

This exception is the global transaction timeout (the default value is 60s) or the call service B timeout.

**Comment by beyond233** [comment]
> > > @beyond233 Does the data source of service B use DatasourceProxy?
> > 
> > 
> > 我刚刚断点调试的时候发现B服务里MYSQLInsertExecutor执行插入SQL的时候报错，说找不到xid:
> > java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.56.1:8091:85053037214699520, may be has finished.] ]
> 
> This exception is the global transaction timeout (the default value is 60s) or the call service B timeout.

A调用B后，A能够成功注册分支事务到seata服务端，B服务不能成功注册。另外，我怎么判断数据源有没有正确进行数据源代理呢

![image](https://user-images.githubusercontent.com/39663915/102980217-312b2000-4542-11eb-9fcd-d8cdffca71a2.png)

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/102984772-1019fd80-4549-11eb-96d2-61597dae7cea.png)

**Comment by beyond233** [comment]
> > > @beyond233 Does the data source of service B use DatasourceProxy?
> > 
> > 
> > 我刚刚断点调试的时候发现B服务里MYSQLInsertExecutor执行插入SQL的时候报错，说找不到xid:
> > java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.56.1:8091:85053037214699520, may be has finished.] ]
> 
> This exception is the global transaction timeout (the default value is 60s) or the call service B timeout.

我在这个新issue里重新详细描述了问题，并提供了一个复现bug的demo，麻烦看看呢。地址 https://github.com/seata/seata/issues/3409
