### ISSUE TITLE
TC hangs, there is no restore root.data after restart and only the client ip is recorded in root.data.

### ISSUE THREAD

**Issue by cauchy88** [seata/seata#340]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

TC挂了，重启后没有restore root.data并且root.data里面只记录了客户端ip
即使restore了root.data，但是里面只有clientip，没有Port信息
### Ⅱ. Describe what happened
当TC挂了并重启后，由于通过ip+port才能定位到是哪个client，但没有port信息；
会出现及时重载也无法找到对应的客户端
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by sharajava** [comment]
Should be a bug. Let's try to fix it. It'll be great if you can share your fix. 👍

**Comment by leizhiyuan** [comment]
is it fixed?

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
