### ISSUE TITLE
docker启动时，环境变量“SEATA_IP”配置成域名无效

### ISSUE THREAD

**Issue by javac2005** [seata/seata#3401]
### docker启动时，环境变量“SEATA_IP”配置成域名无效
我用的是官方docker镜像
官方文档对此环境变量的描述是：指定seata-server启动的IP，该IP用于向注册中心注册时使用，如eureka等。
我配置成如“a.b.c”的域名，发现无效，nacos的服务详情里还是IP。
该环境变量是不是只能是IP，无法配置成如“a.b.c”的域名？

**Comment by slievrly** [comment]
@javac2005 Can you ping `x.x.x` pass in docker?

**Comment by javac2005** [comment]
> @javac2005 Can you ping `x.x.x` pass in docker?

@slievrly 
Yes I can. "SEATA_IP=baidu.com" and "SEATA_PORT=80", but Still invalid.
I guess that it can't configure the domain name, only IP available.

**Comment by flightefore** [comment]
在Server.java启动代码中有校验IP有效性代码，域名不识别，会被改成本地IP，
我改的这段代码
 /* if (NetUtil.isValidIp(parameterParser.getHost(), false)) {
            XID.setIpAddress(parameterParser.getHost());
        } else {
            XID.setIpAddress(NetUtil.getLocalIp());
        }*/
        if(parameterParser.getHost() != null && !parameterParser.getHost().equals("")){
            XID.setIpAddress(parameterParser.getHost());
        }else{
            //XID.setIpAddress("seata-server");
            XID.setIpAddress(NetUtil.getLocalIp());
        }
并且在向注册中心注册时需要改掉IP验证有效性,以redis为例
RedisRegistryServiceImpl中得register方法修改
public void register(InetSocketAddress address) {
        NetUtil.validAddress(address);
        String serverAddr = address.getHostString()+":"+address.getPort(); //NetUtil.toStringAddress(address);
        try (Jedis jedis = jedisPool.getResource()) {
            jedis.hset(getRedisRegistryKey(), serverAddr, ManagementFactory.getRuntimeMXBean().getName());
            jedis.publish(getRedisRegistryKey(), serverAddr + "-" + RedisListener.REGISTER);
        }
    }

**Comment by javac2005** [comment]
@flightefore 多谢
```
private static final Pattern IP_PATTERN = Pattern.compile("\\d{1,3}(\\.\\d{1,3}){3,5}$");
public static boolean isValidIp(String ip, boolean validLocalAndAny) {
        if (validLocalAndAny) {
            return ip != null && IP_PATTERN.matcher(ip).matches();
        } else {
            return ip != null && !ANY_HOST.equals(ip) && !LOCALHOST.equals(ip) && IP_PATTERN.matcher(ip).matches();
        }

    }
```
分析源码发现，这里确实只能写IP，不能写域名！太坑了！

**Comment by javac2005** [comment]
@flightefore 多谢，看来只能改源码了！

**Comment by xingfudeshi** [comment]
@javac2005 Hostname will be supported after latest release.

**Comment by aohanhe** [comment]
我没有使用域名，使用SEATA_IP指定了ip 结果还是注册成了虚拟机的ip

**Comment by mutou2015** [comment]
> 我没有使用域名，使用SEATA_IP指定了ip 结果还是注册成了虚拟机的ip

哥们，我也碰到这个问题了，后来解决了没

**Comment by siao-string** [comment]
> > 我使用域名，使用 SEATA_IP 指定了结果还是没有注册成为虚拟机的 ip
> 
> 哥们，我也有这个问题了，后来没解决了
我也是这个文题，怎么解决啊

**Comment by tengfei666666** [comment]
> 我没有使用域名，使用SEATA_IP指定了ip 结果还是注册成了虚拟机的ip

我也是一样的问题，请问怎么解决啊？

**Comment by siao-string** [comment]
> > 我使用域名，使用 SEATA_IP 指定了结果还是没有注册成为虚拟机的 ip
> 
> 我也是的问题，请问怎么解决啊？

--hostname 真实IP

**Comment by chunde743001734** [comment]
我也遇到了

**Comment by chunde743001734** [comment]
有大神解决了吗?

**Comment by flightefore** [comment]
改他源码，把那层ip校验去掉。具体哪个类上忘记了，你可以追他的启动代码很快就看到的
----- 原始邮件 -----
发件人：chunde743001734 ***@***.***>
收件人：seata/seata ***@***.***>
抄送人：flightefore ***@***.***>,  Mention ***@***.***>
主题：Re:_[seata/seata]_docker启动时，环境变量“SEATA_IP”配置成域名无效_(#3401)
日期：2022年09月03日 09点38分



有大神解决了吗?



&mdash;

**Comment by chunde743001734** [comment]
我后来用1.5.2的docker镜像 SEATA_IP 参数有效

**Comment by flightefore** [comment]
那可以啊，已经还没就看seata源码了。不知道这些更新了
----- 原始邮件 -----
发件人：chunde743001734 ***@***.***>
收件人：seata/seata ***@***.***>
抄送人：flightefore ***@***.***>,  Mention ***@***.***>
主题：Re:_[seata/seata]_docker启动时，环境变量“SEATA_IP”配置成域名无效_(#3401)
日期：2022年09月09日 11点10分



我后来用1.5.2的docker镜像 SEATA_IP 参数有效



&mdash;
