### ISSUE TITLE
Could not found global transaction xid = ip:8091:86933268920868864, may be has finished

### ISSUE THREAD

**Issue by songsirSmall** [seata/seata#3419]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅵ. Environment:

- JDK version :1.8
- OS :Linux

**Comment by caohdgege** [comment]
可能是以下几种情况：异步分支，网络重试，超时回滚，本地事务注解在全局事务注解之上。

可以在TC端的日志中搜索一下你对应的xid，对应的全局事务是什么情况。

**Comment by lvxianzheng** [comment]
seata server目前是没有状态的，每个server都有定时器，定时操作数据的时候不加锁，压力测试的时候就容易产生这个问题。
问题不严重，极端情况使用tcc可能会有悬挂事务产生。
针对这个问题，以后我会贡献几个Pr来解决高性能时的几个问题。

软件的正常设计是对于共享数据，应当加锁，或者保证数据不冲突，seata在设计的时候可能为简单，放弃了这点原则。

**Comment by a364176773** [comment]
> seata server目前是没有状态的，每个server都有定时器，定时操作数据的时候不加锁，压力测试的时候就容易产生这个问题。
> 问题不严重，极端情况使用tcc可能会有悬挂事务产生。
> 针对这个问题，以后我会贡献几个Pr来解决高性能时的几个问题。
> 
> 软件的正常设计是对于共享数据，应当加锁，或者保证数据不冲突，seata在设计的时候可能为简单，放弃了这点原则。

tcc悬挂后续我们会解决，而这个问题issue里的问题不是悬挂产生，而是分支事务注册的时候，seata二阶段已经决议或者完成了导致的，说到底还是这个rm让tm无法感知，2楼说的几个点都是产生的原因，而定时操作数据并不会让一阶段事务决议（除超时外），跟你上诉的几个点没什么关系，定时操作数据后续通过raft集成会改善此问题。另外你说的悬挂是因为多tc导致多个定时任务可能进行多次下发二阶段，可能会出现幂等问题，但是悬挂的原因是一阶段注册后，提交本地事务时，事务已经二阶段决议导致的。如果是一个同步的调用，为什么会出现一阶段注册时，作为consumer的tm没得到provider的响应就二阶段决议了，不知道这个问题你思考过没

**Comment by lvxianzheng** [comment]
这个错误正常情况下1阶段不会发生，只有异常情况下才可能发生
对于at,2阶段是定时任务产生的，多个tc由于没有锁，可能导致对同一事务发起多次2阶段提交，当第1个tc 请求提交后，清理了该事务的数据之后，第2个tc 再处理，就会发生这样的情况。

**Comment by a364176773** [comment]
> 这个错误正常情况下1阶段不会发生，只有异常情况下才可能发生
> 对于at,2阶段是定时任务产生的，多个tc由于没有锁，可能导致对同一事务发起多次2阶段提交，当第1个tc 请求提交后，清理了该事务的数据之后，第2个tc 再处理，就会发生这样的情况。

这个异常是rm注册的时候抛出的异常,跟第二个tc再处理没有关系
