### ISSUE TITLE
关于编码风格的探讨

### ISSUE THREAD

**Issue by yydzxz** [seata/seata#3423]
不是bug, 就是想探讨下
为啥要用`!`这种反向逻辑
![image](https://user-images.githubusercontent.com/13087806/103326052-9c687b00-4a89-11eb-8554-3c2b14b57976.png)

截图中的代码
```java
    /**
     * Is empty boolean.
     *
     * @param map the map
     * @return the boolean
     */
    public static boolean isEmpty(Map<?, ?> map) {
        return !isNotEmpty(map);
    }

    /**
     * Is not empty boolean.
     *
     * @param map the map
     * @return the boolean
     */
    public static boolean isNotEmpty(Map<?, ?> map) {
        return map != null && !map.isEmpty();
    }
```

1. 正向判断感觉更合理一些
```java
    public static boolean isEmpty(Map<?, ?> map) {
        return map == null || map.isEmpty();
    }
    public static boolean isNotEmpty(Map<?, ?> map) {
        return !isEmpty(map);
    }
```
2. `isNotEmpty`其实没多大必要封装, 虽然提倡语义化,但是这个有点过头了个人感觉

**Comment by a364176773** [comment]
话说图挂了，可以直接发文字描述吗

**Comment by slievrly** [comment]
@yydzxz I see what you mean, we haven't fully thought about this detail yet, but it's really a matter of code style, like anything else.
![image](https://user-images.githubusercontent.com/8758457/103330928-9e890480-4a9e-11eb-98d1-63d0ddad2cb5.png)

**Comment by yydzxz** [comment]
> 话说图挂了，可以直接发文字描述吗

common/src/main/java/io/seata/common/util/CollectionUtils.java 截图在这个文件77行左右
