### ISSUE TITLE
引入swagger后导致项目seata报空指针（seata+shardingsphere+swagger）去掉swagger全部正常，有这种情况吗？

### ISSUE THREAD

**Issue by WalkFly** [seata/seata#3424]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
请提交异常堆栈
