### ISSUE TITLE
TM在事务发起的时候，如果有增删改数据库会生成undo_log吗？还是只有被调用的才会生成undo_log?

### ISSUE THREAD

**Issue by WalkFly** [seata/seata#3425]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by caohdgege** [comment]
一个服务可以同时是TM和RM，只要他配置了seata的数据库代理那就会生成。
