### ISSUE TITLE
雪花算法在高并发下的时钟回拨

### ISSUE THREAD

**Issue by xiaoxiongmao-liu** [seata/seata#3426]
seata 1.3.0
注册配置中心：nacos
模式：db
在进行压力测试时发现，请求量比较大时，seata生成branchId会出现clock backwords错误，请解决下

**Comment by a364176773** [comment]
> seata 1.3.0
> 注册配置中心：nacos
> 模式：db
> 在进行压力测试时发现，请求量比较大时，seata生成branchId会出现clock backwords错误，请解决下
1.5改善此情况,但是目前1.3的版本还是需要你们避免时钟回拨
