### ISSUE TITLE
seata1.4.0报错Could not found global transaction xid = xxx(ip):8091:89400785040838656, may be has finished

### ISSUE THREAD

**Issue by zpg851105** [seata/seata#3434]
使用的jar包为

> <dependency> 
       <groupId>io.seata</groupId>
       <artifactId>seata-spring-boot-starter</artifactId>
       <version>1.4.0</version>
</dependency>

将registry.conf文件删除，将配置文件放到properties文件中，A服务调用B服务一直报错这个

seata.enabled=true
seata.application-id=pay
seata.tx-service-group=my_test_tx_group
seata.service.vgroupMapping.my_test_tx_group=default
seata.registry.file.name=file.conf
seata.registry.type=nacos
seata.registry.nacos.server-addr=xxx:8848
seata.registry.nacos.group=DEV_GROUP
seata.registry.nacos.namespace=d5e6e80b-2ca7-4c28-a905-5ab98d44e05d
seata.registry.nacos.cluster=default
seata.config.type=nacos
seata.config.file.name=file.conf
seata.config.nacos.namespace=d5e6e80b-2ca7-4c28-a905-5ab98d44e05d
seata.config.nacos.server-addr=xxx:8848
seata.config.nacos.group=DEV_GROUP
seata.enable-auto-data-source-proxy=true
seata.use-jdk-proxy=true

这个为配置文件，如果将registry.conf文件放到resources目录下面就不会报错这个，A调用B成功

**Comment by litianyu1992** [comment]
异步分支，网络重试，超时回滚，本地事务注解在全局事务注解之上，tc集群用的模式是file（这个模式只能单机部署） 检查这几种可能性

**Comment by zpg851105** [comment]
> 异步分支，网络重试，超时回滚，本地事务注解在全局事务注解之上，tc集群用的模式是file（这个模式只能单机部署） 检查这几种可能性

第一点异步分支没懂，但是第二三四点都没有，用的是db模式，毕竟用直接改成registry.conf就不会出现这个问题了，将seata-spring-boot-starter的jar包改成seata-all的jar包就行了          或者         把@GlobalTransactional注解去掉也能成功

**Comment by litianyu1992** [comment]
异步分支就是启动一个线程异步执行，线程提交晚于主线程

**Comment by a364176773** [comment]
> > 异步分支，网络重试，超时回滚，本地事务注解在全局事务注解之上，tc集群用的模式是file（这个模式只能单机部署） 检查这几种可能性
> 
> 第一点异步分支没懂，但是第二三四点都没有，用的是db模式，毕竟用直接改成registry.conf就不会出现这个问题了，将seata-spring-boot-starter的jar包改成seata-all的jar包就行了 或者 把@GlobalTransactional注解去掉也能成功

跟jar没关系，用all，你的seata组件确定初始化了？starter是帮你做了初始化，检查自己的provider接口是不是由于网络重试被调了超过2次把

**Comment by zpg851105** [comment]
> > > 初始分支，网络重试，超时回滚，本地事务注解在一系列事务注解之上，tc占用用的模式是file（这个模式只能单机部署）检查这几种
> > 
> > 
> > 第一点异步分支没懂，但是第二三四点都没有，用的是db模式，毕竟用直接改成registry.conf就不会出现这个问题了，将seata-spring-boot-starter的jar包改成seata-all的jar包就行了或把@GlobalTransactional注解去掉也能成功
> 
> 跟jar没关系，用all，你的seata组件确定初始化了？starter是帮你完成初始化，检查自己的provider接口是不是由于网络重试被调了超过2次把

何为seata组件初始化？我这边已经将feign超时设了和禁止重试都尝试了，但是问题是依然还没有成功，用<dependency>
      <groupId>io.seata</groupId>
      <artifactId>seata-all</artifactId>
      <version>1.4.0</version>
    </dependency>
和registry.conf文件代替seata-spring-boot-starter这个jar包就没问题

**Comment by zpg851105** [comment]
> > > 异步分支，网络重试，超时回滚，本地事务注解在全局事务注解之上，tc集群用的模式是file（这个模式只能单机部署） 检查这几种可能性
> > 
> > 
> > 第一点异步分支没懂，但是第二三四点都没有，用的是db模式，毕竟用直接改成registry.conf就不会出现这个问题了，将seata-spring-boot-starter的jar包改成seata-all的jar包就行了 或者 把@GlobalTransactional注解去掉也能成功
> 
> 跟jar没关系，用all，你的seata组件确定初始化了？starter是帮你做了初始化，检查自己的provider接口是不是由于网络重试被调了超过2次把

或者说你这边看能不能帮忙看下是哪里的配置有问题导致总是调用失败呢，我的微信15302715352，多谢
