### ISSUE TITLE
seata1.4.0报错Could not found global transaction xid =192.168.1.154:8091:89400785040838656, may be has finished

### ISSUE THREAD

**Issue by zpg851105** [seata/seata#3438]
使用seata-all这个jar包和放在resource目录下registry.conf这个配置文件能够完美运行A->B，但是用seata-spring-boot-starter和将registry.conf文件删除，将配置放到yml或者properties文件下一直报错这个，将@GlobalTransactional注释掉又能成功，我已经将feign超时配置了很长，重试也给禁止了，依然显示这个错（A和B服务）
下面为超时配置
#ribbon.MaxAutoRetries只能设置成0或者不配置,否则会重试
ribbon.MaxAutoRetries=0
ribbon.MaxAutoRetriesNextServer=0

#超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=20000
#需要大于hystrix超时时间
ribbon.ReadTimeout=30000
ribbon.ConnectTimeout=10000

feign.client.config.default.connectTimeout=60000
feign.client.config.default.readTimeout=60000
feign.hystrix.enabled=true

下面为seata配置
seata.enabled=true
seata.application-id=${spring.application.name}
seata.tx-service-group=my_test_tx_group
seata.registry.type=nacos
seata.registry.nacos.server-addr=192.168.1.154:8848
seata.registry.nacos.namespace=d5e6e80b-2ca7-4c28-a905-5ab98d44e05d
seata.registry.nacos.cluster=default
seata.config.type=nacos
seata.config.nacos.namespace=d5e6e80b-2ca7-4c28-a905-5ab98d44e05d
seata.config.nacos.server-addr=192.168.1.154:8848
seata.config.nacos.group=DEV_GROUP
seata.enable-auto-data-source-proxy=true
seata.data-source-proxy-mode=AT

之前有回复说【
异步分支，网络重试，超时回滚，本地事务注解在全局事务注解之上，tc集群用的模式是file（这个模式只能单机部署） 检查这几种可能性
】
经检查肯定都不存在，因为1用的是db模式2只用了@GlobalTransactional这个注解3超时也设置了很长，openfeign的重试也关了
最为奇怪的是使用seata-all这个jar包可以使用seata-spring-boot-starter一直报错
【1】Could not register branch into global session xid = 192.168.1.154:8091:89833378232143872 status = TimeoutRollbacking while expecting Begin
或者
【2】Could not found global transaction xid =192.168.1.154:8091:89400785040838656, may be has finished

本人研究了好几天了，如果有清楚的可以加我微信15302715352或者能够给个有效的回复，多谢大神们

**Comment by slievrly** [comment]
@zpg851105 Can you refine a simple and reproducible sample?

**Comment by a364176773** [comment]
多个tc节点之间的时区需要一致，不然会出现a节点begin时，到b节点定时任务判断是否超时时的不准确产生

**Comment by dongfsgf** [comment]
请问你解决了吗？我也遇到了，第一次就报错，后面没问题了

**Comment by dongfsgf** [comment]
请问楼主解决了吗
