### ISSUE TITLE
seata支持阿里云PolarDB-X吗?

### ISSUE THREAD

**Issue by zhong2312** [seata/seata#3445]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

用的是seate1.4版本，数据库用PolarDB-X做分库分表。
实际运行发现seate自动生产并执行的sql会导致数据库死锁，执行几小时都没执行完。
如：select * from table LIMIT 1 这种语句就执行了几小时。
```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by slievrly** [comment]
@zhong2312 supports, but Seata does not have the appropriate sharding keys, which can lead to poor performance.
