### ISSUE TITLE
mybatis代理数据源问题

### ISSUE THREAD

**Issue by 13691098994** [seata/seata#3453]
使用@GlobalTransactional(name = "createLog", timeoutMills = 60000, rollbackFor = Exception.class)注解时，mybatis的insert方法，出现了以下问题：
- | [] | [20210108 18:07:51.617] | [TID: N/A] | [DEBUG] | [L8000100961421] | [http-nio-8080-exec-1] | [c.e.c.m.m.C.insert] | [--> ==>  Preparing: INSERT INTO `cmp_redeem_batch_info` ( `redeem_batch_id`,`batch_source`,`redeem_batch_no`,`coupon_batch_no`,`redeem_title`,`redeem_count`,`redeem_remain_count`,`redeem_status`,`redeem_remarks`,`valid_start_time`,`valid_end_time`,`create_time`,`update_time`,`del_flag` ) VALUES( ?,?,?,?,?,?,?,?,?,?,?,?,?,? ) ] |
- | [] | [20210108 18:07:52.094] | [TID: N/A] | [WARN] | [L8000100961421] | [http-nio-8080-exec-1] | [i.s.r.d.exec.mysql.MySQLInsertExecutor] | [--> Fail to get auto-generated keys, use 'SELECT LAST_INSERT_ID()' instead. Be cautious, statement could be polluted. Recommend you set the statement to return generated keys.] |
- | [] | [20210108 18:07:52.115] | [TID: N/A] | [ERROR] | [L8000100961421] | [http-nio-8080-exec-1] | [c.e.c.m.s.i.CmpRedeemBatchInfoServiceImpl] | [--> 生成兑换码批次-->插入兑换码批次表失败] |
- | [] | [20210108 18:07:52.169] | [TID: N/A] | [ERROR] | [L8000100961421] | [http-nio-8080-exec-1] | [c.e.iot.exception.GlobalExceptionHandler] | [--> GlobalExceptionHandler->handler exception:] |
c

redeem_batch_id是表的自增int类型主键，使用@GlobalTransactional注解时，出现上述异常，但是如果不使用注解，则没有异常，且mybatis打印的sql语句，也不会出现redeem_batch_id这一列，非常奇怪！

**Comment by a364176773** [comment]
用最新的undolog库和seata搭建

**Comment by caohdgege** [comment]
@Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")

**Comment by chrisjiangfeng** [comment]
解决了吗  哥
