### ISSUE TITLE
can only use seata-spring-boot-starter, not use spring-cloud-starter-alibaba-seata?

### ISSUE THREAD

**Issue by zhangzl0119** [seata/seata#3460]
our project use 2.0.x springboot, but spring-cloud-starter-alibaba-seata 2.2.x RELEASE depend on 2.2.x+ version springboot, we can't to improve springboot version. I see spring-cloud-starter-alibaba-seata code , feign module depend on high version. If  not use this module, my project can run ok?

**Comment by slievrly** [comment]
If you want to use Spring Cloud components like Feigin, Hystrix, etc., you need to depend on spring-cloud-starter-alibaba-seata. spring-cloud-starter-alibaba-seata is compatible with multiple Spring Cloud versions.  https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by zhangzl0119** [comment]
thanks. I want to use Spring Cloud components, but out project depend on spring2.0.x and cloud Finchley. If we use spring-cloud-starter-alibaba-seata 2.2.x, our project can't to run. I find spring-cloud-loadbalancer jar must depend on heigh version cloud , try to 
compatible with heigh Spring Cloud versions, but our springboot2.0.x project can't to compatible with height spring cloud version. only when I improve to springboot version to 2.2.5.RELEASE+, spring-cloud-starter-alibaba-seata 2.2.1.RELEASE can worker well. Do you have some good way to compatible with springboot2.0.x and spring-cloud-starter-alibaba-seata 2.2.1.RELEASE?

**Comment by slievrly** [comment]
@zhangzl0119 how about spring-cloud-starter-alibaba-seata:2.0.3.RELEASE, but you may need to upgrade to the Seata version.

**Comment by zhangzl0119** [comment]
@slievrly we  want to use spring-cloud-starter-alibaba-seata 2.2.1.RELEASE, but not worker well with out springboot2.0.x version. So I want to find some way to compatible.

**Comment by slievrly** [comment]
@zhangzl0119 so the core of the problem is that the Spring Cloud depends on the lowest version of Spring Boot.

**Comment by zhangzl0119** [comment]
@slievrly I try to remove spring-cloud-loadbalancer code, the lowest version of Spring Boot can run well.
