### ISSUE TITLE
请问下，seata如何整合PolarDB-X（drds）呢？AT模式，drds 5.6版本

### ISSUE THREAD

**Issue by sustly** [seata/seata#3461]
我看官网上说这样写：
conn.setAutoCommit(false);
try (Statement stmt = conn.createStatement()) {
    stmt.execute("SET drds_transaction_policy = '2PC'");
}
但是手动提交的话，如何让seata管理呢？求大佬指点，

**Comment by slievrly** [comment]
@sustly Just treat DRDS as a normal database.

**Comment by sustly** [comment]
@slievrly But when using the version of drds5.6, seata will report an error when using drds, and it prompts that cross-database transactions are not supported when performing transaction operations on drds 5.6.

**Comment by sustly** [comment]
https://help.aliyun.com/document_detail/118061.html?spm=a2c4g.11186623.2.5.33ed5ecbrFCEgP , How to use it on seata?
