### ISSUE TITLE
how to disable seata when run unit test？

### ISSUE THREAD

**Issue by verify31** [seata/seata#3462]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
how to disable seata when run unit test？

### Ⅱ. Describe what happened

I hava try config this in application.properties in the test folder in resources folder ，but not work，
seata.enabled=false
seata.enable-auto-data-source-proxy=false

seata version ：seata all 1.4

### Ⅲ. Describe what you expected to happen

support jump seata when I run unit test。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : jdk 8
- OS :
- Others:

**Comment by slievrly** [comment]
seata.service.disable-global-transaction=true

**Comment by verify31** [comment]
> seata.service.disable-global-transaction=true

still load seata ...
