### ISSUE TITLE
[Feature]: Add the transaction group to Metrics

### ISSUE THREAD

**Issue by xuande** [seata/seata#3471]
## Why you need it?
There is no transaction group information in Metrics, so it is recommended to add transaction grouping attribute to support statistics according to transaction group.
每个应用可以在Nacos中定义各自的事务分组，也可以多个业务关联紧密的应用共享一个事务分组，metrics中增加group属性可以通过prometheus根据分组查询.

## How it could be?
Before:
`seata_transaction{instance="localhost:9898",job="seata",meter="timer",role="tc",statistic="total",status="rollbacked"}`
After:
`seata_transaction{instance="localhost:9898",job="seata",meter="timer",role="tc",statistic="total",status="rollbacked", group="order-service-group"}`

**Comment by caohdgege** [comment]
https://github.com/seata/seata/pull/3371 这个pr里面已经添加了对于applicationId，是否还有必要添加group到Metrics的统计里面？

**Comment by xuande** [comment]
> #3371 这个pr里面已经添加了对于applicationId，是否还有必要添加group到Metrics的统计里面？

每个应用可以在Nacos中定义各自的事务分组，也可以多个业务关联紧密的应用共享一个事务分组，metrics中增加group属性可以通过prometheus根据分组查询。所以还是建议增加group属性
