### ISSUE TITLE
1.4.0版本关于事务分组的配置service.default.grouplist

### ISSUE THREAD

**Issue by CNWangTy** [seata/seata#3473]
当启用nacos作为注册中心的时候，service.default.grouplist这个配置是不是不起作用？这种情况下只能指向某个集群（例如default）而不是具体的地址？请问本身就是这么设计的么？

**Comment by caohdgege** [comment]
是的，在用了nacos(或者其他支持的)注册中心的时候，TM/RM就可以通过注册中心去拿对应的服务了，而不需要写死在配置里面了
