### ISSUE TITLE
多个微服务，但是用的同一个数据库，这种场景支持吗？

### ISSUE THREAD

**Issue by lehug** [seata/seata#3474]
按照多微服务部署的，但是微服务其实都是用的同一个数据库，seata at支持这种模式吗？ 共用一个undo_log表，我看表结构似乎是可以的，毕竟同一个xid，但是branch_id还是不同的。seata_server的branch_table, global_table这些也和client端共用一个db，有问题吗？
请对项目更了解的大侠，从技术实现层面帮我确认下

**Comment by lvxianzheng** [comment]
1.4目前没有发现问题，1.3有bug

**Comment by lehug** [comment]
> 1.4目前没有发现问题，1.3有bug

谢谢，我也是用1.4，打算测试环境跑一下。你和我的使用场景一样？其实我是可以整合service层，不用分布式事务的，不过想着实践下新技术，所以这样用了

**Comment by lvxianzheng** [comment]
我的场景更复杂，一个调用链上的服务使用多个库，也有多个服务使用同一个库的

分布式事务会引入太多的复杂性，业务需求那就没办法了

**Comment by a364176773** [comment]
支持

**Comment by lehug** [comment]
明白了，谢谢
