### ISSUE TITLE
discard long time none received connection报错，请问是什么原因？

### ISSUE THREAD

**Issue by myideato** [seata/seata#3477]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by caohdgege** [comment]
这个应该是druid那边连接池的空闲连接检测，不关seata事

**Comment by xuande** [comment]
druid的问题，使用druid-1.1.22.jar替换druid-1.1.23.jar
