### ISSUE TITLE
zookeeper issue

### ISSUE THREAD

**Issue by 516471820** [seata/seata#3483]
when i import nodes to zk,  when start seata ,report a issue: unknown store mode:?? t db,   so  how can i solve it
![image](https://user-images.githubusercontent.com/55741095/105470971-314f4480-5cd5-11eb-9ed3-c1bf8ef952b8.png)

**Comment by xingfudeshi** [comment]
> when i import nodes to zk, when start seata ,report a issue: unknown store mode:?? �t �db, so how can i solve it
> ![image](https://user-images.githubusercontent.com/55741095/105470971-314f4480-5cd5-11eb-9ed3-c1bf8ef952b8.png)

It seems the string of store mode can't be read properly.Have you ever tried to change the encoding of a file?
