### ISSUE TITLE
Transaction problem

### ISSUE THREAD

**Issue by zhouzongyu** [seata/seata#350]
如果使用GlobalTransactional，问题是本地@Transactional注解的话，事务好像是失效的

**Comment by zhangthen** [comment]
I've had this problem too.  
The reason is that spring declarative transactions conflict with GlobalTransactionScanner in terms of dynamic proxy.

**Comment by hsz8250** [comment]
无法用@transactional注解做本地事务控制，如果某一个接口中出现2个数据库DML语句，如果整个事务出现异常，此接口的2个数据操作会得到记录和回滚吗？

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.

**Comment by qcmoke** [comment]
> 无法用@transactional注解做本地事务控制，如果某一个接口中出现2个数据库DML语句，如果整个事务出现异常，此接口的2个数据操作会得到记录和回滚吗？

我也有同样的问题，本地事务@transactional无法作回滚
