### ISSUE TITLE
seata1.4+oracle+redis, afterImage's rows no record, data not rollback

### ISSUE THREAD

**Issue by Jesliexie** [seata/seata#3506]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

**table pk length over than 16, rollback fails.**

### Ⅱ. Describe what happened

serverA call serverB

serverA: insert a record into tableA
serverB: insert a record into tableB, throw Exception

if pk (long) length >= 17 afterImage's rows no record(insert), exception happens, undolog is deleted, but serverA's data is remains

if pk (long) length = 16, afterImage's rows has records(insert), rollback successfully, serverA's data is deleted.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows 10
- Others: oracle 11g

**Comment by caohdgege** [comment]
plz try to use BigDecimal as your pk's java type

**Comment by Jesliexie** [comment]
thx.use BigDecimal replace Long is ok. Long max length is 19 , but why 17 fails,  seata datasource proxy cause?

**Comment by caohdgege** [comment]
According to the doc of oracle db, when your length of decimal is more than 19（include），you are suppose to use BigDecimal as your pk‘s java type or it will work unexpect when you use PreparedStatement#setObject(int,Object,int). but i am not sure why your Dividing point is 17 but not 19.

中文版。。。
根据Oracle官方的文档，如果你的decimal的长度>=19的话，那你的Java类型就应该是使用BigDecimal而不是long(即使long可以放得下)。如果你的decimal的长度>=19并且你用long作为你的java类型的话，在使用PreparedStatement#setObject(int,Object,int)的时候，他的结果可能跟你预期的有点差异，在查询后置镜像的时候就会查询不出对应的数据，也就导致了你所说的回滚不了。
但是Oracle的文档那边的分界点是19，我不知道为什么你这边在长度>=17的时候用long就不行了。。。

**Comment by Jesliexie** [comment]
thx again。Long 确实只能精度到部分19位数字，最大值 9223372036854775807。所以>=19位，要使用BigDecimal。
