### ISSUE TITLE
事务回滚结束后，undo_log表中存在log_status为1的记录，这个是正常的吗

### ISSUE THREAD

**Issue by yylstudy** [seata/seata#3508]
### Ⅰ. Issue Description
使用seata+nacos
业务方法使用@GlobalTransactional，业务方法调用发生异常，数据正确回滚，但是undo_log表中存在log_status为1的数据，
根据官方文档介绍，log_status为1的数据的数据是防悬挂措施，那这个log_status为1的undo_log数据在整个事务回滚完成后会删除吗？
然后把seata的服务端和客户端改成file模式，重新进行上面的操作，undo_log不会存在log_status为1的数据，是nacos模式和file模式配置的问题吗？希望得到回答，谢谢。

### Ⅱ. Environment:
- JDK version : 1.8
- OS : win10
- spring-boot-2.2.2.RELEASE
- dubbo-2.7.5
- seata-spring-boot-starter-1.4.0
- nacos-client-1.1.3

**Comment by slievrly** [comment]
@yylstudy as expected.

**Comment by wechat361** [comment]
问题解决了没，我也遇到这种情况了
