### ISSUE TITLE
seata 1.4.1 疑似版本兼容问题,启动报错。

### ISSUE THREAD

**Issue by cjh184987650** [seata/seata#3517]
spring-cloud-starter-alibaba-seata 
2.2.5.RELEASE

seata-spring-boot-starter
1.4.1

spring-cloud-starter-openfeign
2.2.6.RELEASE

spring-cloud-starter-loadbalancer
2.2.6.RELEASE

启动报错：
Error creating bean with name 'feignClient' defined in class path resource [org/springframework/cloud/openfeign/ribbon/DefaultFeignLoadBalancedConfiguration.class]: Initialization of bean failed; nested exception is java.lang.IllegalAccessError: tried to access class org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient from class com.alibaba.cloud.seata.feign.SeataFeignObjectWrapper

spring-cloud-starter-alibaba-seata 换成 2.2.0.RELEASE
seata-spring-boot-starter  换成  1.4.0
侧启动正常。

**Comment by a364176773** [comment]
请反馈至spring cloud alibaba社区
