### ISSUE TITLE
io.seata.core.rpc.netty.ChannelManager#getChannelFromSameClientMap

### ISSUE THREAD

**Issue by jianglianggithub** [seata/seata#3520]
这个函数好像有点问题应该 在使用高级for循环 遍历的时候 remove 会报错吧

**Comment by jianglianggithub** [comment]
当前1.4.0版本

**Comment by dmego** [comment]
@jianglianggithub  在这个方法中，参数 `clientChannelMap` 是一个 `ConcurrentHashMap`。对于 `ConcurrentHashMap` 而言，边遍历边删除或者增加操作不会产生异常，因为其内部已经做了维护，遍历的时候都能获得最新的值。即便是多个线程一起删除、添加元素也是没问题的。

**Comment by jianglianggithub** [comment]
@dmego Thanks♪(･ω･)ﾉ   我多虑了不好意思
