### ISSUE TITLE
ID 生成支持雪花模型，时钟回拨问题未处理，io.seata.common.util.IdWorker

### ISSUE THREAD

**Issue by GourdErwa** [seata/seata#3527]
server 部署机器如果出现时钟回拨，生成的 id 可能会重复。
```java
    private long getNewestTimestamp() {
        return System.currentTimeMillis() - twepoch;
    }
```
@selfishlover

**Comment by a364176773** [comment]
你应该解决的是时钟回拨问题，目前的雪花id最新develop已经做了优化，但是并不能完全解决回拨的问题，雪花算法本身就是依赖于时间戳

**Comment by selfishlover** [comment]
develop版的算法只支持server运行中的时钟回拨，但不支持重启后的时钟回拨，例如这样：

**Comment by GourdErwa** [comment]
我们发号器服务做了心跳记录，启动时候检查时间差，出现回拨情况时延迟启动。

另一个问题：
serverNode 配置，如果启动时候 serverNode 配置出现重复，也可能会出现重复，这个属于配置容错性检测。
我们处理方式：服务做了心跳，判断心跳周期。k8s下使用有状态服务启动，保证服务节点 ID 的唯一性。

@a364176773  @selfishlover 

以上建议性问题不予解决可以关闭该问题。

**Comment by selfishlover** [comment]
要支持重启后的时间回拨问题的话，只能设法持久化时间戳进度(通过写文件之类的~)。延迟启动的话不太好，要是回拨幅度很大呢？得延迟多久？
serverNode设置重复的话，目前server之间也没有直接交流的途径，没法知道其它节点是不是跟自己重复~

**Comment by GourdErwa** [comment]
> 要支持重启后的时间回拨问题的话，只能设法持久化时间戳进度(通过写文件之类的~)。延迟启动的话不太好，要是回拨幅度很大呢？得延迟多久？
如果真的出现回拨了，属于生产机器问题，这种情况延迟启动可以接收的。极端情况时钟因为硬件或者网络就秒级别的问题，除非人为修改时间做测试忘记修改回去。

> serverNode设置重复的话，目前server之间也没有直接交流的途径，没法知道其它节点是不是跟自己重复~
对，如果做配置容错性校验也需要增加额外的功能，看项目对该问题的取舍了。

**Comment by a364176773** [comment]
> > 要支持重启后的时间回拨问题的话，只能设法持久化时间戳进度(通过写文件之类的~)。延迟启动的话不太好，要是回拨幅度很大呢？得延迟多久？
> > 如果真的出现回拨了，属于生产机器问题，这种情况延迟启动可以接收的。极端情况时钟因为硬件或者网络就秒级别的问题，除非人为修改时间做测试忘记修改回去。
> 
> > serverNode设置重复的话，目前server之间也没有直接交流的途径，没法知道其它节点是不是跟自己重复~
> > 对，如果做配置容错性校验也需要增加额外的功能，看项目对该问题的取舍了。

目前1.4版本会直接采用mac地址做servernode，理论上不会重复，你们用的是什么版本？

**Comment by GourdErwa** [comment]
> > > 要支持重启后的时间回拨问题的话，只能设法持久化时间戳进度(通过写文件之类的~)。延迟启动的话不太好，要是回拨幅度很大呢？得延迟多久？
> > > 如果真的出现回拨了，属于生产机器问题，这种情况延迟启动可以接收的。极端情况时钟因为硬件或者网络就秒级别的问题，除非人为修改时间做测试忘记修改回去。
> > 
> > 
> > > serverNode设置重复的话，目前server之间也没有直接交流的途径，没法知道其它节点是不是跟自己重复~
> > > 对，如果做配置容错性校验也需要增加额外的功能，看项目对该问题的取舍了。
> 
> 目前1.4版本会直接采用mac地址做servernode，理论上不会重复，你们用的是什么版本？

我们没有用 seata ，是有一个专门的发号器服务采用 k8s 有状态部署。

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/3175
