### ISSUE TITLE
Redis中的已提交事务分支未被清除

### ISSUE THREAD

**Issue by tanggen** [seata/seata#3530]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
当二阶段事务提交之后，redis中的事务分支未被清除，导致redis中遗留了大量的status = 8的全局事务，另外此时若重启tc，tc会读取redis中的事务，光读取数据都要花上10几分钟

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
二阶段事务提交后，清除事务分支，重启时，补偿删除已提交的事务分支

**Comment by tanggen** [comment]
这个问题说的不是很严谨，严格来说，在TC刚启动时，也会清除redis中的已提交事务，只是当事务发起速度过快时，情除提交事务的速度远远跟不上提交的速度，进而增大了TC的压力，最终不知什么原因导致TC不再清除已提交事务分支，即使重启，也不会继续清除

**Comment by tanggen** [comment]
根据代码的逻辑可以看出，异步提交任务每秒执行一次，读取所有状态为8的任务，循环检查并删除分支事务，但如果事务提交过快，每秒钟删除的事务少于提交的事务，则会导致事务session积压过多，1个TC的情况下session积压非常严重，过多的session积压也影响了TC的运行速度，甚至OOM

**Comment by a364176773** [comment]
已被异步化处理
