### ISSUE TITLE
AOP动态创建/关闭Seata分布式事务中怎么获取GlobalTransactionRole 

### ISSUE THREAD

**Issue by yuncpu** [seata/seata#3532]
seata版本1.4.0
开发环境为 idea 
注册中心eureka
AOP实现的demo：(http://seata.io/zh-cn/blog/seata-spring-boot-aop-aspectj.html)
_________________________________________________
 RT：
     AOP中通过@Before来发起或者参与事务，参考源码GlobalTransactionContext中的
  [ public static GlobalTransaction getCurrentOrCreate() {
        GlobalTransaction tx = getCurrent();
        if (tx == null) {
            return createNew();
        }
        return tx;
    }](url)

当@AfterReturning时API方式中没有获取当前 GlobalTransactionRole的方法？？？

**Comment by a364176773** [comment]
i will follow up on this issue
