### ISSUE TITLE
seata的server端可以作为springboot项目启动么，如何修改呢？

### ISSUE THREAD

**Issue by Broomhildall** [seata/seata#3535]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/3009

**Comment by Broomhildall** [comment]
@a364176773 我拜读并调试了#3009的server-boot分支，我的思路是在一个spring-boot项目中引入seata-server 包的方式，将其作为server端启动，并且seata版本更新，只需要更新包的版本就可以，能力有限，不知方向是否正确。

**Comment by spilledyear** [comment]
@Broomhildall 如果server-boot分支的代码合并后， server模块本身就是一个 springboot工程了，但官方还是提供了脚本部署的方式，你也可以直接基于源码打包，打包之后的server模块就是一个springboot应用
