### ISSUE TITLE
微服务无法配置seataServer的ip跟端口，一直连接127.0.0.1:8091

### ISSUE THREAD

**Issue by a871545252** [seata/seata#3538]
i.s.c.r.netty.NettyClientChannelManager  : will connect to 127.0.0.1:8091

NettyPool create channel to transactionRole:RMROLE,address:127.0.0.1:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://192.168.1.182:3306/zhjd_w', applicationId='zhjd-web', transactionServiceGroup='zhjd-tx-service-group'} >

我将seata-server放在192.168.1.182上面的
![image](https://user-images.githubusercontent.com/51905887/108795742-02710a80-75c2-11eb-9f9e-088a2aa361f9.png)
![image](https://user-images.githubusercontent.com/51905887/108795768-0f8df980-75c2-11eb-8d5d-f0e1fafc4982.png)

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/3026
