### ISSUE TITLE
1.4.1 版本 AT模式 回滚异常：明明undo_log已经删除，而后删除的undo又被add添加！！！！！！

### ISSUE THREAD

**Issue by wwkin** [seata/seata#3547]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
![image](https://user-images.githubusercontent.com/24583799/109094706-62e48100-7755-11eb-85eb-ca3a1cdd4507.png)

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen

回滚删除undo_log就不要再add已删除的undo_log

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- seata version:1.4.1
- OS :
- Others:

**Comment by caohdgege** [comment]
能否提供其他相关信息？TC端的日志是怎么样的？一台TC还多多台？偶发的还是？

**Comment by wwkin** [comment]
![image](https://user-images.githubusercontent.com/24583799/109120116-7fe27980-7780-11eb-9c6f-552d1810fb1c.png)
只部署一台1.4.1版本的Seata；
是偶发的，上午我重复把数据库表undo_log脏数据清空，然后试了很多次重现过几次，再后来就暂时没发生，
![image](https://user-images.githubusercontent.com/24583799/109120753-4f4f0f80-7781-11eb-91d6-ceda2fa56e35.png)
这是我yml配置
![image](https://user-images.githubusercontent.com/24583799/109120856-73aaec00-7781-11eb-9dde-e91c5620600b.png)
这是我maven依赖

**Comment by wwkin** [comment]
除了undo_log表数据被添加，其他业务表及branch ，global表都正常回滚

**Comment by caohdgege** [comment]
`Rollback branch transaction fail and will retry, xid = `，`Rollback branch transaction exception, xid = `
请问TC的日志中是否有这两句的日志？

**Comment by caohdgege** [comment]
问题定位到了，我们看一下怎么解决。

**Comment by wwkin** [comment]
嗯，发现只要上次有后添加的undo_log信息，而后重复上次相同调用操作，这个undo_log日志后续都是累加，都没被删掉

**Comment by caohdgege** [comment]
> 嗯，发现只要上次有后添加的undo_log信息，而后重复上次相同调用操作，这个undo_log日志后续都是累加，都没被删掉

这个是定时任务删除的，七天后才会被删除。

**Comment by wwkin** [comment]
哦，
![image](https://user-images.githubusercontent.com/24583799/109124028-6c85dd00-7785-11eb-9e68-61450272ca96.png)
学习了，谢谢
1.什么情况会导致undo_log再次被添加来防止悬挂，而正常情况没有这个add操作？
2.宕机或是Seata服务器升级等操作会影响这个数据定时删除结果吗，方便告知此处定时删除位置吗？

**Comment by caohdgege** [comment]
针对第一点，有以下可能会出来
1. 这个全局事务是数据全局回滚的，然后运行的时间超过了默认的阈值12s(从开启事务算起)，然后就会触发重试回滚，你出现的属于这种情况。后期会把这个12s修改的长一点来解决这个问题，大概会是2*事务超时时间。
2. 注册了分支，但是还没有进行本地事务提交就发生了异常
3. 多TC争抢

**Comment by caohdgege** [comment]
第二点 DefaultCoordinator中搜索undoLogDelete这个关键字，只要你还有TC或者，就不会影响。

**Comment by wwkin** [comment]
**谢谢**
顺便问一句可以帮忙看看其他问题吗，https://github.com/seata/seata/issues/3548
