### ISSUE TITLE
AT模式下，有复合主键的表会报错，使用上有问题吗，哪里有测试用例可以参考一下？

### ISSUE THREAD

**Issue by cnzdq** [seata/seata#3553]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用的是seata1.4.0，mysql，at模式，事务中有个表是复合主键会报错，是我配置问题吗，哪里有测试用例可以参考一下呢？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
io.seata.common.exception.NotSupportYetException: user_permission contains multi PK, but current not support.
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS :
- Others:

**Comment by caohdgege** [comment]
1.4.0是支持了MySQL的多主键的，检查一下你的依赖的seata-all版本是不是1.4.0的

**Comment by cnzdq** [comment]
![image](https://user-images.githubusercontent.com/30411977/109590525-17601780-7b47-11eb-8699-dac159e9fb62.png)
这个依赖是对的吗？

**Comment by caohdgege** [comment]
看一下pom文件是怎么写的

**Comment by cnzdq** [comment]
这是一个 service 层的子模块：

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>platform-admin</artifactId>
        <groupId>com.cnzdq</groupId>
        <version>1.0.1-test</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>platform-admin-service</artifactId>

    
    <dependencies>
        <dependency>
            <groupId>com.cnzdq</groupId>
            <artifactId>platform-common-excption</artifactId>
            <version>1.0.1-test</version>
        </dependency>
        <dependency>
            <groupId>com.cnzdq</groupId>
            <artifactId>platform-admin-dao</artifactId>
            <version>1.0.1-test</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.3.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.cnzdq</groupId>
            <artifactId>platform-zdcrm-provider</artifactId>
            <version>1.0.1-test</version>
        </dependency>
    </dependencies>

</project>`

**Comment by caohdgege** [comment]
TableMeta#getPrimaryKeyMap 的方法打个断点，然后看一下是哪个版本的？

**Comment by cnzdq** [comment]
还真是的，实际运行的是1.1.0版的：

![image](https://user-images.githubusercontent.com/30411977/109613199-cc0c3000-7b6b-11eb-913e-b14e4cccdea8.png)
