### ISSUE TITLE
Seata从1.2.0支持XA协议,Mycat支持XA分布式事务,是不是说明Seata和Mycat可以一起用？

### ISSUE THREAD

**Issue by ZongjieWu** [seata/seata#3556]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
@ZongjieWu In fact, it's not. Here you need MyCat to integrate Seata using the DataSourceProxyXA as the datasource  proxy.
