### ISSUE TITLE
xid must not be blank，seata 1.4.0

### ISSUE THREAD

**Issue by zyfjxust** [seata/seata#3559]
client 引入 1.4.0版本的seata的时候，会报错  xid must not be blank

我们看到下面很多issure都是这个问题，但很多都去自定义拦截器，或者修改MVCCOnfigure,  

解决方法就是：将client  1.4.0 降级到  1.3.0 ,亲测有效，同时升级到1.4.1 也可，但是群里有人聊到 1.4.1 有个脏写的bug

![image](https://user-images.githubusercontent.com/10087025/109639270-f0770500-7b89-11eb-87e9-d5d356b18e0c.png)

**Comment by zyfjxust** [comment]
还有问题可以私聊我

**Comment by 852675742** [comment]
您好，请问下我现在也碰到这个问题了，怎么解决啊？之前用的1.0版本没问题
![image](https://user-images.githubusercontent.com/19749064/114964767-ef800580-9ea1-11eb-80a4-00e2370eea80.png)
