### ISSUE TITLE
mysql驱动8.0时，JacksonUndoLogParser 反序列化报错

### ISSUE THREAD

**Issue by cloudX2019** [seata/seata#3566]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
      mysql驱动8.0时，JacksonUndoLogParser 反序列化报错。数据库类型datetime会被映射为LocalDateTime类型

### Ⅱ. Describe what happened
     mysql驱动8.0时，数据库类型datetime会被映射为LocalDateTime类型。 JacksonUndoLogParser在反序列化时无法处理导致异常

### Ⅲ. Describe what you expected to happen
    mysql驱动8.0时   数据也能正常序列化和反序列化到数据库

### Ⅵ. Environment:

- JDK version :  11
- OS :  mac os
- Others: mysql驱动 8.0

**Comment by karry-jiang** [comment]
哥们解决了没

**Comment by cloudX2019** [comment]
这个问题有人提交pr了，但是目前还没合并进去 。估计要等到1.5.0版本了

**Comment by zq1355100052** [comment]
我也遇到同样的问题了，我用的是seata1.4.0

**Comment by zyplanke** [comment]
MySQL版本不能高于8.0.22，高于则报此错

**Comment by cloudX2019** [comment]
这个问题新版本1.4.2以上 已经解决了（提供了自定义序列化的spi）。
自己在项目中实现JacksonSerializer接口即可

**Comment by edifangyi** [comment]
> 这个问题新版本1.4.2以上 已经解决了（提供了自定义序列化的spi）。 自己在项目中实现JacksonSerializer接口即可

请问如何实现自定义序列化的spi，并且使用，O(∩_∩)O

**Comment by cloudX2019** [comment]
> > 这个问题新版本1.4.2以上 已经解决了（提供了自定义序列化的spi）。自己在项目中实现JacksonSerializer即可
> 
> 如何自定义序列化的spi，并使用，O(∩_∩)O

https://blog.csdn.net/zh0134/article/details/115612416
