### ISSUE TITLE
seata 1.2.0 FileConfiguration.java 问题

### ISSUE THREAD

**Issue by tan-zhuo** [seata/seata#3571]
![image](https://user-images.githubusercontent.com/32378959/111283249-e1a84c00-8679-11eb-99b0-8a7234ca6f7f.png)
![image](https://user-images.githubusercontent.com/32378959/111283448-1c11e900-867a-11eb-973e-7114186e2f44.png)

在spring bean加载完成之后，如果bean接口方法上标注了 GlobalTransactional 注解将会为此 bean 的 GlobalTransactionalInterceptor 添加一个 FileListener，在 bean 相当多的情况下会创建许多线程池，造成资源浪费。
查看代码逻辑是每一个 bean 可以单独配置 关闭或开启 GlobalTransactionalInterceptor.disable 的状态，但所有的 FileListener.dataId 指向 file.conf->service.disableGlobalTransaction 值 当 file 文件被修改时则线程异步读取配置文件，检查文件修改时间是否变动，如果变动过则会获取最新配置值，执行之后会把最新的修改时间赋值到自身 targetFileLastModified ，可惜自身是一个单例模式，线程赋值最新文件修改时间后，其他守护线程一样也不能获取到修改值。所以我认为这里的设计可能会存在一定的问题 :）

![image](https://user-images.githubusercontent.com/32378959/111287805-8a58aa80-867e-11eb-9f19-f59cbed9d8f0.png)

![image](https://user-images.githubusercontent.com/32378959/111287262-0272a080-867e-11eb-9793-ef1163246af5.png)

**Comment by a364176773** [comment]
已做优化,谢谢反馈
https://github.com/seata/seata/pull/3222
