### ISSUE TITLE
k8s环境部署高可用seata注册IP问题

### ISSUE THREAD

**Issue by warthur1214** [seata/seata#3583]
使用官方文档的yaml在k8s上部署的seata，注册中心使用nacos。
注册IP是pod里自动分配的IP，而使用SEATA_IP是设置的固定IP。
如果部署多个节点SEATA_IP如何配置。另外是否可以使用k8s分配的hostname注册nacos？

![image](https://user-images.githubusercontent.com/13415982/111869808-04a96780-89bc-11eb-9a7d-f9fd05f0ea59.png)

**Comment by luofei-china** [comment]
seata中心用nacos，不需要配置SEATA_IP。
