### ISSUE TITLE
TC server 可能存在 GlobalSessionLock 无法被释放的问题

### ISSUE THREAD

**Issue by ymwangzq** [seata/seata#3585]
看到这里代码觉得存在隐患：
场景举例：
AT 模式下，全局事务提交时，会将 GlobalSession 状态修改为 AsyncCommitting，等待异步提交。此时还没有释放 GlobalSessionLock。
在异步提交的过程中，如果在 SessionHelper.endCommitted 过程中，
globalSession.changeStatus(GlobalStatus.Committed) 成功，但是
globalSession.end() 内部删除锁记录操作失败，看起来会导致锁记录再也没有机会被删除。

相关代码：
https://github.com/seata/seata/blob/d28274d4f29ce58d62aac37d87296446feb5ae4b/server/src/main/java/io/seata/server/session/SessionHelper.java#L95

**Comment by nimo10050** [comment]
我也发现了同样的问题,  不需要解决吗?  是因为问题出现概率小, 数据量不会太多吗?

**Comment by a364176773** [comment]
> 我也发现了同样的问题, 不需要解决吗? 是因为问题出现概率小, 数据量不会太多吗?

先释放锁才会改为异步，没问题
