### ISSUE TITLE
postgresql   JDBC连接多Schema导致undo_log表无法清空

### ISSUE THREAD

**Issue by wangtianmiao** [seata/seata#3591]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
使用如下JDBC URL连接 postgresql 数据库
jdbc:postgresql://ip:port/db?currentSchema=schema1,commonschema
jdbc:postgresql://ip:port/db?currentSchema=schema2,commonschema

### Ⅱ. Describe what happened
导致ChannelManager#dbKeytoSet 方法在拆分字符串时出现错误(Constants.DBKEYS_SPLIT_CHAR = ",")。
使得与RM无法通讯，undo_log表无法清空
源码如下：
```
private static Set<String> dbKeytoSet(String dbkey) {
        if (StringUtils.isNullOrEmpty(dbkey)) {
            return null;
        }
        return new HashSet<String>(Arrays.asList(dbkey.split(Constants.DBKEYS_SPLIT_CHAR)));
    }
```

### Ⅲ. Describe what you expected to happen
应使用其它分隔符，目前我自己修改源码，使用“,,”作为分隔符（String DBKEYS_SPLIT_CHAR = ",,";）

### Ⅵ. Environment:

- JDK version : Java 8
- OS : CentOs 7
- Others: postgresql 数据库

**Comment by caohdgege** [comment]
请问是否方便提个pr修复一下？

**Comment by wangtianmiao** [comment]
> 请问是否方便提个pr修复一下？
已提交

**Comment by siaron** [comment]
这个有什么解决方案吗?

**Comment by wangtianmiao** [comment]
> 这个有什么解决方案吗?

我的方案可以临时解决。

修改:Constants类中的DBKEYS_SPLIT_CHAR为“,,”
替换两个引用的地方就行
分别是ChannelManager和RmNettyRemotingClient
