### ISSUE TITLE
order服务在最后抛出异常，此时account服务宕机，导致事务无法回滚，undo_log数据不清空

### ISSUE THREAD

**Issue by yanjingyun** [seata/seata#3593]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
我使用项目的案例进行测试，在order方法的最后写了一个抛出异常（此时已经请求完storage和account服务请求），这时候把account服务弄宕机了，此时事务回滚不成功？
代码如下：
@GlobalTransactional(name = "fsp-create-order",rollbackFor = Exception.class)
public void create(Order order) {
    LOGGER.info("------->交易开始");
    //本地方法
    orderDao.create(order);

    //远程方法 扣减库存
    storageApi.decrease(order.getProductId(),order.getCount());

    //远程方法 扣减账户余额

    LOGGER.info("------->扣减账户开始order中");
    accountApi.decrease(order.getUserId(),order.getMoney());
    LOGGER.info("------->扣减账户结束order中");

    LOGGER.info("------->交易结束");
    throw new RuntimeException("测试抛出异常，同时停掉account账户服务，查看事务是否回滚成功"); // 新增
}

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by caohdgege** [comment]
account服务起来或者有其他连接到account的服务起来之后才能继续回滚。

还有。。。吐槽一下。。。一般这种issue。。。建议都放一下日志，版本等等信息。。。
