### ISSUE TITLE
LockRetryPolicy execute 配置判断逻辑反了

### ISSUE THREAD

**Issue by ymwangzq** [seata/seata#3604]
这里条件貌似反了

https://github.com/seata/seata/blob/2dac3a5062ed5fe5dd027fac6105dbcd32767f9e/rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java#L329

**Comment by a364176773** [comment]
仔细阅读,并没有反,一个是没开始本地事务时,seata在connection之外重试,此时的好处是遇到锁冲突是进行rollback释放本地锁,而另一个是开始本地事务下,为了防止占用了本地锁而导致二阶段回滚的事务无法回滚的问题,所以在connectionproxy内默认是不争取锁
