### ISSUE TITLE
使用seata-saga模式进行服务编排为什么还需要seata-server开启事务控制

### ISSUE THREAD

**Issue by fighting0510** [seata/seata#3608]
seata-saga模式中状态机的实现，为什么要引入TC，不是很理解。

个人理解如下：
状态图中可以根据某个服务的调用状态(异常/业务异常)来决定流程走向，比如 正向流程如下  Ta、Tb、Tc（都为更新类服务），对应反向为Ca、Cb、Cc，若Tb执行异常，则根据Tb状态进行Cb、Ca进行补偿即可，不需要在开始及结束与TC交互，因为如果依赖TC，则必须保证TC高可用，否则影响正常交易

**Comment by a364176773** [comment]
基本上tc只是一个辅助事务状态的记录,比如日后要做控制台时,可以输出saga这块事务的运转情况,主要还是收集client端的report

**Comment by majiaji** [comment]
> 基本上tc只是一个辅助事务状态的记录,比如日后要做控制台时,可以输出saga这块事务的运转情况,主要还是收集client端的report

是否有开关可以关闭tc呢
