### ISSUE TITLE
seata and RocketMQ Transaction Msg

### ISSUE THREAD

**Issue by web1992** [seata/seata#3612]
## Why you need it?
 I want use `seata` + `RocketMQ Transaction` in our appliaction.
So I need to know `seata GlobalStatus` to decision my `RocketMQ Transaction` commit or rollback.

But now, I did not find some API to query GlobalStatus. Because GlobalStatus always to` Finished`  status.

I didn't know GlobalStatus is successful or failed.

So, How I can know GlobalStatus is successful or failed?

**Comment by a364176773** [comment]
或许在tm端的TransactionHook可用帮助你，在tm发起者的函数内利用TransactionHookManager注册hook，再tm决议二阶段的时候，你的hook就可以帮你完成一些事情

**Comment by web1992** [comment]
> 或许在tm端的TransactionHook可用帮助你，在tm发起者的函数内利用TransactionHookManager注册hook，再tm决议二阶段的时候，你的hook就可以帮你完成一些事情

TransactionHook 只能在 TM 服务器中使用。而在 RM 角色的服务器中无法使用。有点尴尬
