### ISSUE TITLE
seata访问报错

### ISSUE THREAD

**Issue by wang7143** [seata/seata#3618]
`Java HotSpot(TM) 64-Bit Server VM warning: Cannot open file D:\QQ文件接收\spring_cloud\seata\bin\\../logs/seata_gc.log due to No such file or directory

15:18:16,166 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:18:16,166 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:18:16,167 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/QQ%e6%96%87%e4%bb%b6%e6%8e%a5%e6%94%b6/spring_cloud/seata/conf/logback.xml]
15:18:16,168 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
15:18:16,168 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/D:/QQ%e6%96%87%e4%bb%b6%e6%8e%a5%e6%94%b6/spring_cloud/seata/lib/seata-server-1.4.1.jar!/logback.xml]
15:18:16,168 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/D:/QQ%e6%96%87%e4%bb%b6%e6%8e%a5%e6%94%b6/spring_cloud/seata/conf/logback.xml]
15:18:16,262 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:18:16,268 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/D:/QQ%e6%96%87%e4%bb%b6%e6%8e%a5%e6%94%b6/spring_cloud/seata/conf/logback.xml]
15:18:16,268 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
15:18:16,271 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Adding LoggerContextListener of type [io.seata.server.logging.listener.SystemPropertyLoggerContextListener] to the object stack
15:18:16,271 |-INFO in ch.qos.logback.classic.joran.action.LoggerContextListenerAction - Starting LoggerContextListener
15:18:16,271 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [io.seata.server.logging.logback.ColorConverter]
15:18:16,271 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [io.seata.server.logging.logback.WhitespaceThrowableProxyConverter]
15:18:16,271 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wEx with class [io.seata.server.logging.logback.ExtendedWhitespaceThrowableProxyConverter]
15:18:16,274 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:18:16,277 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
15:18:16,285 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:18:16,527 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:18:16,807 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ALL]
15:18:17,101 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2083117811 - Archive files will be limited to [2048 MB] each.
15:18:17,238 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2083117811 - Will use gz compression
15:18:17,240 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2083117811 - Will use the pattern C:/Users/wang/logs/seata/history/seata-server.8091.all.%d{yyyy-MM-dd}.%i.log for the active file
15:18:17,278 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@9660f4e - The date pattern is 'yyyy-MM-dd' from file name pattern 'C:/Users/wang/logs/seata/history/seata-server.8091.all.%d{yyyy-MM-dd}.%i.log.gz'.
15:18:17,278 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@9660f4e - Roll-over at midnight.
15:18:17,282 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@9660f4e - Setting initial period to Thu Apr 08 13:52:05 CST 2021
15:18:17,284 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@2083117811 - Cleaning on start up
15:18:17,284 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
15:18:17,284 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
15:18:17,284 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:18:17,287 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ALL] - Active log file name: C:\Users\wang/logs/seata/seata-server.8091.all.log
15:18:17,287 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ALL] - File property is set to [C:\Users\wang/logs/seata/seata-server.8091.all.log]
15:18:17,289 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:18:17,289 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [WARN]
15:18:17,293 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1518864111 - Archive files will be limited to [2048 MB] each.
15:18:17,294 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1518864111 - Will use gz compression
15:18:17,294 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1518864111 - Will use the pattern C:/Users/wang/logs/seata/history/seata-server.8091.warn.%d{yyyy-MM-dd}.%i.log for the active file
15:18:17,294 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6c49835d - The date pattern is 'yyyy-MM-dd' from file name pattern 'C:/Users/wang/logs/seata/history/seata-server.8091.warn.%d{yyyy-MM-dd}.%i.log.gz'.
15:18:17,294 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6c49835d - Roll-over at midnight.
15:18:17,296 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Removed  0 Bytes of files
15:18:17,296 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6c49835d - Setting initial period to Thu Apr 08 13:51:50 CST 2021
15:18:17,296 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1518864111 - Cleaning on start up
15:18:17,296 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
15:18:17,297 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
15:18:17,297 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:18:17,298 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[WARN] - Active log file name: C:\Users\wang/logs/seata/seata-server.8091.warn.log
15:18:17,298 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[WARN] - File property is set to [C:\Users\wang/logs/seata/seata-server.8091.warn.log]
15:18:17,298 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
15:18:17,298 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR]
15:18:17,300 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1585787493 - Archive files will be limited to [2048 MB] each.
15:18:17,300 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1585787493 - Will use gz compression
15:18:17,301 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1585787493 - Will use the pattern C:/Users/wang/logs/seata/history/seata-server.8091.error.%d{yyyy-MM-dd}.%i.log for the active file
15:18:17,301 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@67205a84 - The date pattern is 'yyyy-MM-dd' from file name pattern 'C:/Users/wang/logs/seata/history/seata-server.8091.error.%d{yyyy-MM-dd}.%i.log.gz'.
15:18:17,301 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@67205a84 - Roll-over at midnight.
15:18:17,303 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@67205a84 - Setting initial period to Thu Apr 08 12:57:22 CST 2021
15:18:17,304 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1585787493 - Cleaning on start up
15:18:17,304 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
15:18:17,304 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
15:18:17,305 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:18:17,306 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - Active log file name: C:\Users\wang/logs/seata/seata-server.8091.error.log
15:18:17,306 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - File property is set to [C:\Users\wang/logs/seata/seata-server.8091.error.log]
15:18:17,307 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:18:17,307 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ALL] to Logger[ROOT]
15:18:17,308 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [WARN] to Logger[ROOT]
15:18:17,308 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR] to Logger[ROOT]
15:18:17,308 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
15:18:17,308 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:18:17,310 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Removed  0 Bytes of files
15:18:17,310 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7d0587f1 - Registering current configuration as safe fallback point

SLF4J: A number (18) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
15:18:17.407  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is registry
15:18:17.422  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is D:\QQ鏂囦
欢鎺ユ敹\spring_cloud\seata\conf\registry.conf
15:18:17.569  INFO --- [                     main] io.seata.config.FileConfiguration        : The file name of the operation is file.conf
15:18:17.570  INFO --- [                     main] io.seata.config.FileConfiguration        : The configuration file used is file.conf
15:18:20.975  INFO --- [                     main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
15:18:24.200  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, listen port: 8091
15:18:31.985  INFO --- [ttyServerNIOWorker_1_1_16] i.s.c.r.n.AbstractNettyRemotingServer    : channel exx:Adjusted frame length exceeds 8388608: 539959368 - discarded,channel:[id: 0xeea51276, L:/0:0:0:0:0:0:0:1:8091 - R:/0:0:0:0:0:0:0:1:10142]
15:18:31.993  WARN --- [ttyServerNIOWorker_1_1_16] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 8388608: 539959368 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.seata.core.rpc.netty.v1.ProtocolV1Decoder.decode(ProtocolV1Decoder.java:83) ~[seata-core-1.4.1.jar:na]
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
<==`
更换版本结果差不多，网上没找打原因

**Comment by wang7143** [comment]
我以为端口是通过网页访问的，所以才出现这样的错误。

**Comment by alexanderliu-creator** [comment]
> 我以为端口是通过网页访问的，所以才出现这样的错误。

服务器还是启动不起来，想请问下具体怎么解决的呢

**Comment by yuanbindada** [comment]
一样碰到这个问题
