### ISSUE TITLE
TC server DataBaseSessionManager.lockAndExecute 没有对 global session 加锁

### ISSUE THREAD

**Issue by ymwangzq** [seata/seata#3619]
https://github.com/seata/seata/blob/da3dbc0259579f3ffc40f13440b8a8ba0ffa188f/server/src/main/java/io/seata/server/storage/db/session/DataBaseSessionManager.java#L194

TC server DataBaseSessionManager.lockAndExecute 没有对 global session 加锁，可能存在客户端认为成功提交，但是实际上被 TC 超时回滚

**Comment by a364176773** [comment]
举个例子?目前看起来加锁是没有意义的,即便是成功提交,超时回滚就回滚了,Seata在at下已经解决了资源悬挂问题,这个我认为没有什么不良影响,除了你说的可能刚注册上,事务就被回滚了,但是什么情况下刚注册上事务就超时回滚了,事务是60秒默认,如果你的业务要执行60秒,是不是太夸张了点?即便是本地事务也存在事务超时的情况,事务的超时回滚更多的是一个兜底的作用,到了时间我给你回滚了,至于超时的问题,应该是一个阈值,你的业务就应该被限制在这个阈值内,尽可能的去优化,而不是去怪,你怎么超时了呢

**Comment by ymwangzq** [comment]
我的理解是这样：
对于 GlobalCommitRequest 来说，如果 TC 返回 AsyncCommitting or Committed，那么用户就认为全局事务提交成功了，这个事务就应保证不会被回滚。如果 TC 返回了 AsyncCommitting or Committed，但是事务又被回滚，则会让用户难以处理。这里没加锁的话就有可能出现这样的问题。原因如下：

以AT模式提交流程为例，TC 处理过程如下：
1. 判断当前 globalSession.getStatus() == GlobalStatus.Begin
2. 将 globalSession 状态修改为 AsyncCommitting
3. 返回 AsyncCommitting，告诉用户提交成功

TC 内检查超时流程如下：
a. 判断 globalSession.getStatus() == GlobalStatus.Begin，且超过了过期时间
b. 将 globalSession 状态修改为 TimeoutRollbacking

由于检查 globalSession.getStatus() 和修改之间没有加锁，并且不是cas操作，因此可能出现以下的执行顺序：

1. 提交流程中，通过 globalSession.getStatus() == GlobalStatus.Begin 校验
a. 超时检查流程中，通过 globalSession.getStatus() == GlobalStatus.Begin 校验，且刚刚好超过了过期时间
2. 提交流程中，将 globalSession 状态修改为 AsyncCommitting
b. 超时检查流程中，将 globalSession 状态修改为 TimeoutRollbacking，导致当前事务后续无法被 handleAsyncCommitting 任务扫描到，而是被 handleRetryRollbacking 任务扫描到，并执行回滚
3. 提交流程中，返回 AsyncCommitting，告诉用户提交成功

最终的现象是：用户发起的 commit 请求收到了 AsyncCommitting，用户认为当前事务已经提交。但是实际上事务被回滚了。

**Comment by a364176773** [comment]
> 我的理解是这样：
> 对于 GlobalCommitRequest 来说，如果 TC 返回 AsyncCommitting or Committed，那么用户就认为全局事务提交成功了，这个事务就应保证不会被回滚。如果 TC 返回了 AsyncCommitting or Committed，但是事务又被回滚，则会让用户难以处理。这里没加锁的话就有可能出现这样的问题。原因如下：
> 
> 以AT模式提交流程为例，TC 处理过程如下：
> 
> 1. 判断当前 globalSession.getStatus() == GlobalStatus.Begin
> 2. 将 globalSession 状态修改为 AsyncCommitting
> 3. 返回 AsyncCommitting，告诉用户提交成功
> 
> TC 内检查超时流程如下：
> a. 判断 globalSession.getStatus() == GlobalStatus.Begin，且超过了过期时间
> b. 将 globalSession 状态修改为 TimeoutRollbacking
> 
> 由于检查 globalSession.getStatus() 和修改之间没有加锁，并且不是cas操作，因此可能出现以下的执行顺序：
> 
> 1. 提交流程中，通过 globalSession.getStatus() == GlobalStatus.Begin 校验
> 2. 超时检查流程中，通过 globalSession.getStatus() == GlobalStatus.Begin 校验，且刚刚好超过了过期时间
> 3. 提交流程中，将 globalSession 状态修改为 AsyncCommitting
> 4. 超时检查流程中，将 globalSession 状态修改为 TimeoutRollbacking，导致当前事务后续无法被 handleAsyncCommitting 任务扫描到，而是被 handleRetryRollbacking 任务扫描到，并执行回滚
> 5. 提交流程中，返回 AsyncCommitting，告诉用户提交成功
> 
> 最终的现象是：用户发起的 commit 请求收到了 AsyncCommitting，用户认为当前事务已经提交。但是实际上事务被回滚了。
> 
> 这里应该有两种解决方案：
> 
> 1. 使用cas方式修改 globalSession status
> 2. 检查 globalSession status 和修改 globalSession status 之间，对 global session 加锁

这个问题对一致性没有什么影响,但是这个足以说明业务的执行不合理造成同时间2中状态的误判,不过你说的cas方式我觉得是可以的,但是我觉得我们的问题不应该在中间件层面,而在业务上,这个只是治标不治本,假设我们做了cas,这个用户就每次都能commit了吗?按照他容易到超时的边界才执行完业务来看,他也容易遇到超时回滚的问题,所以我们只能治标而已.

**Comment by ymwangzq** [comment]
不是避免超时回滚，而是避免 commit 返回成功，但是其实回滚了的问题

**Comment by a364176773** [comment]
> 不是避免超时回滚，而是避免 commit 返回成功，但是其实回滚了的问题

说白了就是避免被误回滚,问题的重点不是seata导致的,在超时的边缘疯狂试探的行为本身就有问题

**Comment by a364176773** [comment]
我们先行记录此问题,感谢同学的反馈,也希望同学能继续参与到社区的code review,issue,也欢迎提一些bug fix ,optimize的pr

**Comment by ymwangzq** [comment]
好的～

**Comment by caohdgege** [comment]
plz assign me

**Comment by caohdgege** [comment]
fixed

**Comment by 412165137lzh** [comment]
> fixed

兄弟，哪里fixed了？  我看1.5.2还是有这个问题呀，修复了吗

**Comment by 412165137lzh** [comment]
> 我们先行记录此问题,感谢同学的反馈,也希望同学能继续参与到社区的code review,issue,也欢迎提一些bug fix ,optimize的pr

大佬，目前我们项目组用的是1.5.2，分析源码的时候也发现了这个问题，用的也是DataBaseSessionManager，这个问题虽然极端，但是确实是设计上的失误，我看源码确实没有修复，请问有计划修复吗大佬

**Comment by codhealer** [comment]
考虑了一个方案，增加一个TM侧的超时时间，比全局超时时间略短。在TM侧进行通知TC提交前，先增加超时判断，如果超时了就直接报错了，通知TC回滚；而不是通知TC提交。这样子TM没挂的时候，超时就不会进到timeout里面；如果TM挂了就由timeout补偿进行回滚。
加这个时间也有一个好处，可以尽量跟返回外部系统的状态保持一致。假设外部系统的超时时间是65s，TM超时是60s。如果交易超过60秒的时候，都会保证返回给外部系统是超时失败。

**Comment by pengten** [comment]
> > 我们先行记录此问题,感谢同学的反馈,也希望同学能继续参与到社区的code review,issue,也欢迎提一些bug fix ,optimize的pr
> 
> 大佬，目前我们项目组用的是1.5.2，分析源码的时候也发现了这个问题，用的也是DataBaseSessionManager，这个问题虽然极端，但是确实是设计上的失误，我看源码确实没有修复，请问有计划修复吗大佬

This issue has been fixed

**Comment by 412165137lzh** [comment]
> 
I didnt find the fixed code on source1.5.2, I still think the issue is not fixed
did you fix it on 1.5.2 ? please tell me how you fix

**Comment by 412165137lzh** [comment]
> > > 我们先行记录此问题,感谢同学的反馈,也希望同学能继续参与到社区的code review,issue,也欢迎提一些bug fix ,optimize的pr
> > 
> > 
> > 大佬，目前我们项目组用的是1.5.2，分析源码的时候也发现了这个问题，用的也是DataBaseSessionManager，这个问题虽然极端，但是确实是设计上的失误，我看源码确实没有修复，请问有计划修复吗大佬
> 
> This issue has been fixed

I didnt find the fixed code on source1.5.2, I still think the issue is not fix.
did you fix on version1.5.2 , can you tell me how you fix (hope post the source code line ) , really thinks.

**Comment by a364176773** [comment]
> > 我们先行记录此问题,感谢同学的反馈,也希望同学能继续参与到社区的code review,issue,也欢迎提一些bug fix ,optimize的pr
> 
> 大佬，目前我们项目组用的是1.5.2，分析源码的时候也发现了这个问题，用的也是DataBaseSessionManager，这个问题虽然极端，但是确实是设计上的失误，我看源码确实没有修复，请问有计划修复吗大佬

db没有修复，redis修复了，使用watch+状态转换规则，禁止commit转rollback和反之，只允许begin向二阶段状态转变。
db有乐观锁pr https://github.com/seata/seata/pull/4383 ，唯一并发的就是timeoutcheck的线程和决议的线程会使事务状态改变，其他地方不会有并发，无需在redis和db下对globalsession加锁，每次加锁会影响性能
