### ISSUE TITLE
分支事务没回滚

### ISSUE THREAD

**Issue by zq1355100052** [seata/seata#3623]
我现在用的是一个简单的服务调用，A(Order)-->B(User),不管A还是B抛出异常，A都可以回滚，但是B不会回滚，我断点查看A到B的XID传递过来了，我看seata-server的日志打印发现只有A注册分支事务成功，B没有注册分支事务，不知道是什么原因。
18:48:35.700  INFO --- [verHandlerThread_1_47_500] i.s.c.r.processor.server.RegRmProcessor  : RM register success,message:RegisterRMRequest{resourceIds='jdbc:mysql://192.168.132.128:3306/user', applicationId='user-service', transactionServiceGroup='my_test_tx_group'},channel:[id: 0xc019cecb, L:/192.168.132.128:8091 - R:/192.168.132.1:53403],client version:1.4.0
18:49:34.631  INFO --- [ettyServerNIOWorker_1_2_2] i.s.c.r.processor.server.RegTmProcessor  : TM register success,message:RegisterTMRequest{applicationId='user-service', transactionServiceGroup='my_test_tx_group'},channel:[id: 0x0de2b809, L:/192.168.132.128:8091 - R:/192.168.132.1:53441],client version:1.4.0
user服务项目也已正常注册了TM和RM.

下面是我模拟异常看seata-server的日志
18:55:39.758  INFO --- [verHandlerThread_1_48_500] i.s.s.coordinator.DefaultCoordinator     : Begin new global transaction applicationId: order-service,transactionServiceGroup: my_test_tx_group, transactionName: add(com.zq.order.model.OrderInfo),timeout:60000,xid:192.168.132.128:8091:124222448874291200
18:55:39.786  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=192.168.132.128:8091:124222448874291200,branchType=AT,resourceId=jdbc:mysql://192.168.132.128:3306/study,lockKey=order_info:50,clientIp:192.168.132.1,vgroup:my_test_tx_group
18:55:39.788  INFO --- [verHandlerThread_1_49_500] i.seata.server.coordinator.AbstractCore  : Register branch successfully, xid = 192.168.132.128:8091:124222448874291200, branchId = 124222449016897536, resourceId = jdbc:mysql://192.168.132.128:3306/study ,lockKeys = order_info:50
18:55:40.297  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=192.168.132.128:8091:124222448874291200,extraData=null,clientIp:192.168.132.1,vgroup:my_test_tx_group
18:55:40.315  INFO --- [verHandlerThread_1_50_500] io.seata.server.coordinator.DefaultCore  : Rollback branch transaction successfully, xid = 192.168.132.128:8091:124222448874291200 branchId = 124222449016897536
18:55:40.319  INFO --- [verHandlerThread_1_50_500] io.seata.server.coordinator.DefaultCore  : Rollback global transaction successfully, xid = 192.168.132.128:8091:124222448874291200.

发现只有orderRegister branch successfully，没有看到user的，有没有大佬遇到过的？

**Comment by a364176773** [comment]
检查b服务的数据源代理,有没有正确的使用被代理的数据源进行操作数据库
