### ISSUE TITLE
请问下SAGA模式下Status.UN状态是怎么处理的？

### ISSUE THREAD

**Issue by lanlanlanlanlanchengzhu** [seata/seata#3628]
针对Status.UN的处理逻辑代码在哪儿呢？

**Comment by lanlanlanlanlanchengzhu** [comment]
阅读了process、route、以及ServiceTaskHandlerInterceptor的pre、postProcess方法，都没有找到对应的处理逻辑

![image](https://user-images.githubusercontent.com/31987529/114336765-3d36fe00-9b82-11eb-8954-54d4da0cf0a8.png)


这里如果是FA或者UN怎么处理呢？

**Comment by anselleeyy** [comment]
@lanlanlanlanlanchengzhu 

这个状态可以用来判断向tc上报的全局事务状态，可以看这里io.seata.saga.engine.store.db.DbAndReportTcStateLogStore#reportTransactionFinished

同时如果开启了分支事务的上报，也有相应的逻辑处理，io.seata.saga.engine.store.db.DbAndReportTcStateLogStore#branchReport
