### ISSUE TITLE
I am considering to contribute, but need Chines pages in English

### ISSUE THREAD

**Issue by FrankLeymann** [seata/seata#363]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I have significant background in transaction processing and transaction models, but my Chinese does not exist.  Do you consider to translate all information into English at some point in time?

### Ⅲ. Describe what you expected to happen
Translate Chinese text in the Wiki into English.

**Comment by slievrly** [comment]
@FrankLeymann ，we will soon arrange community members to do this work, and all Chinese documents will have corresponding English documents. Welcome to the community of fescar.

**Comment by kezhenxu94** [comment]
> @FrankLeymann ，we will soon arrange community members to do this work, and all Chinese documents will have corresponding English documents. Welcome to the community of fescar.

@slievrly contributors are also willing to offer help if there is a clear translation plan and process to see which part is being translated, I suggest opening issues for each module that can be taken by contributors/members, @FrankLeymann before it's done, you can use something like Google translate plugin to translate, which is usually enough to understand the meaning.

**Comment by slievrly** [comment]
> > @FrankLeymann ，we will soon arrange community members to do this work, and all Chinese documents will have corresponding English documents. Welcome to the community of fescar.
> 
> @slievrly contributors are also willing to offer help if there is a clear translation plan and process to see which part is being translated, I suggest opening issues for each module that can be taken by contributors/members, @FrankLeymann before it's done, you can use something like Google translate plugin to translate, which is usually enough to understand the meaning.

@kezhenxu94  I will , thank u.
