### ISSUE TITLE
不使用spring-cloud-starter-alibaba-seata，如何在上下文自动传递XID

### ISSUE THREAD

**Issue by JerryWwang** [seata/seata#3646]
如下图，是项目中依赖。
想请教在不使用依赖的情况下如何自动传递XID
项目中已经加入了SeataHandlerInterceptor

感谢
![image](https://user-images.githubusercontent.com/82087906/115208858-9fb66e00-a12f-11eb-9ff7-95d4273a1a36.png)
![image](https://user-images.githubusercontent.com/82087906/115209305-0e93c700-a130-11eb-971e-2c4babac5260.png)

**Comment by a364176773** [comment]
任意形式,只要参与方能接收到后进行取值rootcontextbind unbind
