### ISSUE TITLE
MySQL8.0

### ISSUE THREAD

**Issue by EiLunge** [seata/seata#3650]
Unknown system variable 'tx_read_only'   使用MySQL8.0发现seata出现这个异常 是我seata版本原因吗

**Comment by aldler** [comment]
add 'service.vgroupMapping.tx_read_only' to your seata's config.

**Comment by slievrly** [comment]
@EiLunge  Pls  paste the detailed error stack.

**Comment by EiLunge** [comment]
The problem has been solved because 8.0 requires Greenwich mean time，Thank you 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月29日(星期四) 晚上7:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [seata/seata] MySQL8.0 (#3650)





 
@EiLunge  Pls  paste the detailed error stack.

**Comment by slievrly** [comment]
@EiLunge If you like you can share the detailed solution, may help to others.
