### ISSUE TITLE
先insert一条数据，再update这条数数据，制造异常，回滚失败

### ISSUE THREAD

**Issue by catman002** [seata/seata#3657]
先insert一条数据，再update这条数数据，制造异常，回滚失败，如：
```
insert  xxTable xxxxx         (id=1)
update  xxTable xxxx where id=1
1/0
```
这种情况下回滚失败，是不支持吗？

### Ⅵ. Environment:

- JDK version :
- OS : centos
- Others: seata 1.4.1

**Comment by a364176773** [comment]
支持，确认你的undolog建表sql是最新的，以及tc端的branch table

**Comment by catman002** [comment]
@a364176773 

三克油啊，果然是建表sql并不是最新造成的，谢了，🙏。
