### ISSUE TITLE
springcloud-nacos-seata中seata-all版本版本有问题，起不起来

### ISSUE THREAD

**Issue by chenglong0527** [seata/seata#3659]
springcloud-nacos-seata
分布式事务组件seata的使用demo，AT模式，集成nacos、springboot、springcloud、mybatis-plus，数据库采用mysql

demo中使用的相关版本号，具体请看代码。如果搭建个人demo不成功，验证是否是由版本导致，由于目前这几个项目更新比较频繁，版本稍有变化便会出现许多奇怪问题

seata 0.8.0
spring-cloud-alibaba-seata 2.1.0.RELEASE
spring-cloud-starter-alibaba-nacos-discovery 0.2.1.RELEASE
springboot 2.0.6.RELEASE
springcloud Finchley.RELEASE
显示seata为0.8.0的seata server但是代码中的seata-all的版本为1.0.01直接导致启动失败，获取不到服务

**Comment by a364176773** [comment]
升级
