### ISSUE TITLE
seata在集成acitiviti工作引擎时无法对流程的表数据进行事务的回滚?

### ISSUE THREAD

**Issue by treespringace** [seata/seata#3660]
![image](https://user-images.githubusercontent.com/83049927/115810696-f1f1da80-a420-11eb-88a9-60f143b57efe.png)

### Ⅴ. Anything else we need to know?
seata在集成acitiviti工作引擎时无法对流程的表数据进行事务的回滚?,业务是这样的 
全局事务从A服务发起---->B服务处理----->调用C(acitiviti服务)    A服务发生异常,AB服务均回滚了事务而C(activiti)服务没有执行回滚,但是通过控制台可以看出C服务收到了全局事务的idx

### Ⅵ. Environment:

- JDK version :1.8
- OS :window10
- Others:activiti 5.22

**Comment by aldler** [comment]
You should controll local transation, add   @Transactional(rollbackFor = Exception.class) to service.
