### ISSUE TITLE
1.4.1 server 控制台乱码

### ISSUE THREAD

**Issue by semmaLuan** [seata/seata#3667]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by wangliang181230** [comment]
windows下的吗？如果是的话，在seata-server.bat文件里加上一行
```
chcp 65001
```
