### ISSUE TITLE
insert into  ....  ....  ON DUPLICATE KEY UPDATE.... 这种情况下误删数据。

### ISSUE THREAD

**Issue by catman002** [seata/seata#3669]
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

insert into  ....  ....  ON DUPLICATE KEY UPDATE.... 这种情况下误删数据：
1. 分支服务 对存在id=1的数据执行这条语句
2. bussiness服务 制造异常
3. 分支回滚了，但是会把id=1的数据删除了 ！

这个回滚应该不对吧！

### Ⅵ. Environment:

- JDK version : 15
- OS : centos7.9
- Others: mysql5.7
- seata: 1.4.1

**Comment by a364176773** [comment]
目前不支持这个语句，未来将有计划

**Comment by catman002** [comment]
@a364176773 OK ok!
