### ISSUE TITLE
UUIDGenerator of Fescar-Server will generate duplicated UUID after TC restart.

### ISSUE THREAD

**Issue by binzhaomobile** [seata/seata#367]
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
According to current algorithm, when the TC is restarted ,duplicated UUID will be generated. 

### Ⅱ. Describe what happened

  The bug can be recurrenced by the following unit test:

```
package com.alibaba.fescar.server;

import java.util.HashSet;
import java.util.Set;
import org.testng.annotations.Test;

public class UUIDGeneratorTest {
    private static final int UUID_GENERATE_COUNT = 10;
    private static final long TC_RESTART_DURATION_MS = 5 * 1000;
    private static final int SERVER_NODE_ID = 1;
    private Set<Long> idSet = new HashSet<>(UUID_GENERATE_COUNT * 3);

    @Test
    public void testGenerateUUID() {
        try {
            UUIDGenerator.init(SERVER_NODE_ID);
            for (int i = 0; i < UUID_GENERATE_COUNT; i++) {
                idSet.add(UUIDGenerator.generateUUID());
            }
            /*Simulation: the TC reboot spends 5 seconds*/
            Thread.sleep(TC_RESTART_DURATION_MS);
            UUIDGenerator.init(SERVER_NODE_ID);
            Long id;
            for (int j = 0; j < UUID_GENERATE_COUNT; j++) {
                id = UUIDGenerator.generateUUID();
                if (idSet.contains(id)) {
                    System.out.println("Duplicated UUID found, the value is：" + id);
                    break;
                }
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
The console output is:
Duplicated UUID found, the value is：3712197

### Ⅲ. Describe what you expected to happen
UUID should not be duplicated when the TC is restarted.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
see the unit test code above.

### Ⅴ. Anything else we need to know?
No.

### Ⅵ. Environment:
This bug is not related with environment, it is an algorithm bug.
- JDK version :
- OS :
- Others:

**Comment by zhengyangyong** [comment]
I think it may casue by `UUID.addAndGet((current - base) / 1000);` in `init` method; it seems want generated uuid long at a certain range partition by `serverNodeId`

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
