### ISSUE TITLE
AT模式，seata-server1.4的store-mode配置为db，branch_table，global_table，lock_table 在debug 模式下，全局事务未走完，这三张表里没有数据，undo_log表里有数据

### ISSUE THREAD

**Issue by logiyan** [seata/seata#3673]
AT模式，seata-server1.4的store-mode配置为db，branch_table，global_table，lock_table 在debug 模式下，全局事务未走完，这三张表里没有数据，undo_log表里有数据。
全局事务是有生效的。

**Comment by a364176773** [comment]
请提供你是如何代理数据源的,还是说交给seata自动代理

**Comment by Surrin1999** [comment]
@a364176773 我也发生了同样的问题，请关注我最新提出的issue

**Comment by lovingfeel** [comment]
我今天也碰到了，启动命令加上这个 seata-server.bat -p 8091 -h 127.0.0.1 -m db ;配置信息导入nacos的时 用官方提供的脚本，不要新建文件写入配置
