### ISSUE TITLE
请问支持单应用单库的多线程事务吗？

### ISSUE THREAD

**Issue by zyh0github** [seata/seata#3674]
请问支持单应用单库的多线程事务吗？

## Why you need it?
 Is your feature request related to a problem? Please describe in details
我们的应用领域不是互联网，是工业领域，单库单表数据量很大(单表千万级和亿级)、但是由于业务梳理和历史原因在分库分表上非常困难。
现在有这样一些场景：假设一个接口请求里，需要对三张大表进行修改，现在是串行的，所以耗时较长。想并行起来，但是多线程事务不好管理。

想使用AT模式，请问seata支持单应用单库的多线程事务吗？非常感谢

可以假定数据库压力能支撑、业务上可以并行不会冲突、不能分库（因为业务上非常困难、其他场景经常连这三张表）

除此之外，还想问一下
1.seata能支持全局事务内的多个数据源分布式事务的**并行**吗？或者后续会考虑支持吗

2.使用AT模式的单应用单库的多线程事务是否能提升响应时间呢？
AT模式好像要执行3条SQL（before image、business sql、after image）耗时是不是会变成原来的接近3倍？多线程并行起来性能能否提升是否也得取决于 原来的sql串行和每条sql的3倍耗时并行起来 谁更快哈？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by sustly** [comment]
你可以参考一下，https://github.com/caohdgege/seata-async

**Comment by zyh0github** [comment]
> 你可以参考一下，https://github.com/caohdgege/seata-async

很棒啊，我们这边研究一下。希望能把这个特性加入到seata内，如果这样就更好了。先用seata做单库多线程事务，随着业务发展后面再用seata管理分库事务，哈哈。

**Comment by zyh0github** [comment]
> 你可以参考一下，https://github.com/caohdgege/seata-async

很棒啊，我们这边研究一下，非常感谢。希望能把这个特性加入到seata内，如果这样就更好了。先用seata做单库多线程事务，随着业务发展后面再用seata管理分库事务。

**Comment by zyh0github** [comment]
> 你可以参考一下，https://github.com/caohdgege/seata-async

很棒啊，我们这边研究一下，非常感谢。希望能把这个特性加入到seata内，这样就更好了。先用seata做单库多线程事务，随着业务发展后面再用seata管理分库事务。

**Comment by zyh0github** [comment]
> 你可以参考一下，https://github.com/caohdgege/seata-async

很棒啊，我们这边研究一下，非常感谢。希望能把这个特性加入到seata内，这样就更好了。先用seata做单库多线程事务，随着业务划分完成后再用seata管理分库事务。

**Comment by caohdgege** [comment]
> > 你可以参考一下，https://github.com/caohdgege/seata-async
> 
> 很棒啊，我们这边研究一下，非常感谢。非常希望能把这个特性加入到seata内，这样就更好了。先用seata做单库多线程事务，随着业务划分完成后再用seata管理分库事务，哈哈。

那个没加入到seata内，是因为可以让用户自定义切点，实现比较高的扩展性，作为独立的依赖的使用难度应该也不高。
