### ISSUE TITLE
TC宕机后的故障恢复

### ISSUE THREAD

**Issue by wugangbao** [seata/seata#3676]
## Why you need it?
TC以集群部署，单点宕机后，RM等内存中信息如何恢复

## How it could be?
当TC单点故障，重启恢复时，TC只能按照文件配置重新启动并注册。但像RM类的信息，是维护在TC的内存中的，此时并不能恢复，RM也不会再次向TC注册，那是不是意味着TC宕机恢复后就无法继续加入集群提供服务了

**Comment by wugangbao** [comment]
另外，RM启动时有机制能够确保通知到所有TC吗，没有找到这一块的逻辑，还望指教

**Comment by a364176773** [comment]
rm会通过注册中心得到可用的tc列表,并注册到所有可用的tc上,如果你用的是file做注册中心,那么如果tc的ip变动了,或者挂了几台,rm是无法感知的
