### ISSUE TITLE
项目集成Seata导致Fegin组件远程调用失败

### ISSUE THREAD

**Issue by MarioSir** [seata/seata#3681]
项目版本：Spring Cloud Alibaba  2.3.8-SNAPSHOT+seata 1.4.0
运行结果：ERROR 7948 --- [x-mate-search-1] v.m.c.feign.fallback.MateFeignFallback   : MateFeignFallback:[vip.mate.resume.feign.IResumeSearchProvider.resumeReceiveOrRelease] serviceId:[mate-search] message:[[500 Internal Server Error] during [POST] to [http://mate-search/inner/search/resumeReceiveOrRelease] [IResumeSearchProvider#resumeReceiveOrRelease(ResumeParamDto)]: [{"code":500,"msg":"Content type 'application/x-www-form-urlencoded' not supported","time":1619579749264}]]
远程接口：
 /**
     * 领取简历/领取释放更新简历领取状态
     *
     * @param resumeParamDto
     * @return
     */
    @PostMapping(ResumeSearchUrlConstant.TALENT_RESUME_SEARCH_RECEIVE_OR_RELEASE)
    Result<?> resumeReceiveOrRelease(@RequestBody ResumeParamDto resumeParamDto);

疑问：没有集成Seata远程调用没有任何问题，集成之后出现接口application/x-www-form-urlencoded' not supported问题

**Comment by a364176773** [comment]
请反馈至spring cloud alibaba社区
