### ISSUE TITLE
`Optimize Request:` Improve code quality.（提升代码质量请求）

### ISSUE THREAD

**Issue by wangliang181230** [seata/seata#3690]
Use the `SonarLint` plugin, `FindBugs` plugin or other plugin to analysis the `seata` project.
There will be a lot of code quality problems, even bugs. I hope people who are interested can help optimize the code.

使用`SonarLint`插件、`FindBugs`插件或其他插件来分析`seata`项目源码。
会找出非常多的代码质量问题，甚至有可能是隐藏的BUG。希望有兴趣的同学能够帮助提升代码质量。
在seata的源码中找找茬，提PR参与社区共建。
非常感谢。

# the analysis report like this（分析报告如下）:
![图片](https://user-images.githubusercontent.com/1527893/116498025-5c9c8d80-a8db-11eb-9a62-c5a6df21323e.png)

**Comment by horizonzy** [comment]
Nice job.

**Comment by hermitcai** [comment]
Nice job.

**Comment by mask616** [comment]
Nice job.

**Comment by samz406** [comment]
good

**Comment by slievrly** [comment]
Welcome everyone to participate in contribution, even a meaningful comments for Seata community is also very valuable.
