### ISSUE TITLE
support mariadb AT mode

### ISSUE THREAD

**Issue by a364176773** [seata/seata#3697]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/19943636/116657524-25081100-a9c1-11eb-9f7b-55fdd6796eb9.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by pengten** [comment]
Maybe mariadb is the same as mysql
