### ISSUE TITLE
在nacos服务管理中查看seata-server频繁上下线

### ISSUE THREAD

**Issue by 1ten1** [seata/seata#3703]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
部署了两个seata-server，在nacos中查看服务列表中的seata-server，正常是显示实例数是2，健康实例数也是2。
但是过一会再刷新，看到实例数是2，健康实例数是1。或者实例数和健康实例数都是1，或者都是0.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8.1
- OS :linux
- docker Image:seataio/seata-server   1.4.1
- nacos: 2.0.0
- mysql: 5.7

**Comment by a364176773** [comment]
检查网络

**Comment by 1ten1** [comment]
是nacos集群的问题，注册的服务没有同步
