### ISSUE TITLE
想请问一下xid的设计思路？

### ISSUE THREAD

**Issue by Broomhildall** [seata/seata#3710]
在阅读和调试源代码中发现xid是根据ip+port+transactionId生成的而transactionId是雪花算法生成的。我的理解是既然transactionId是一个唯一的id了，那xid为什么不直接使用transactionId而又添加了ip和port呢？

**Comment by xingfudeshi** [comment]
xid is generated using ip+port+transactionId, and the purpose is to better locate the problematic services when there is a problem.
