### ISSUE TITLE
请问项目启动报错是怎么回事呢？ no available service found in cluster 'default'

### ISSUE THREAD

**Issue by TateTang** [seata/seata#3712]
no available service found in cluster 'default', please make sure registry config correct and keep your seata server running

**Comment by a364176773** [comment]
事务分组在配置中心未配置
Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt﻿
﻿
升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR

**Comment by TateTang** [comment]
> 事务分组在配置中心未配置
> Seata整合1.2教程: [https://www.bilibili.com/video/BV12Q4y1A7Nt﻿](https://www.bilibili.com/video/BV12Q4y1A7Nt%EF%BB%BF)
> ﻿
> 升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR

事务分组在配置中心配置了的，这个是在defult集群中找不到可用服务

**Comment by a364176773** [comment]
> > 事务分组在配置中心未配置
> > Seata整合1.2教程: [https://www.bilibili.com/video/BV12Q4y1A7Nt﻿](https://www.bilibili.com/video/BV12Q4y1A7Nt%EF%BB%BF)
> > ﻿
> > 升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR
> 
> 事务分组在配置中心配置了的，这个是在defult集群中找不到可用服务

这是读不到你的事务分组对应的值，读的到显示的就是集群名而不是null，好好看教程吧，你自己的问题

**Comment by a364176773** [comment]
抱歉看错了，检查tc，如果是nacos就看namespace group cluster的值，client端对应正确即可，教程仔细看吧，说到底还是你自己的问题

**Comment by TateTang** [comment]
> 抱歉看错了，检查tc，如果是nacos就看namespace group cluster的值，client端对应正确即可，教程仔细看吧，说到底还是你自己的问题

好的，谢谢啦
