### ISSUE TITLE
AT模式,事务回滚存在的问题

### ISSUE THREAD

**Issue by zkoalas** [seata/seata#3721]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

Seata用的是AT模式
这里有两个方法,三个业务线
两个业务分别是:
1.下单业务(扣减库存,生成订单)
2.采购业务(采购了商品补仓)

@GlobalTransactional //seata的分布式事务
public void doOrder(){
1)扣减库存
2)生成订单
}

//没有使用seata的分布式事务,默认数据库的事务
public void doAdditional(){
3)增加库存
}

当业务1执行成功并提交后,业务3相继执行成功并提交,此时执行业务2时,发生错误. seata要回滚, 回滚业务1.
因为seata的回滚是补偿机制,是否会覆盖业务3已经修改后的数据?

举例:初始值为:1000个商品,业务1扣减了100个库存,db中现在是900个,此时undo_log日志中记录是肯定是1000个.
业务3此时执行,修改了db的商品数量为:1900(进货1000),
现在执行到业务2,发生了异常,seata要回滚了,进行补偿,此时拿出undo_log日志中的1000个覆盖了,此时db中的1900,变成了1000.是这样吗?

根据官网所知,doOrder()方法中会有一个全局锁,全局锁,是seata自己的锁,不会跟mysql本地事务的锁,互斥吧? 所以doAdditional()方法会执行成功并提交事务,数据回滚会被覆盖成1000的

出现了脏数据问题!!!!!!

**Comment by hy0619** [comment]
doAdditional 放到分布式事务 ：
 doAdditional 方法上加@GlobalTransaction 注解，此时 doAdditional 方法上的全局事务的transaction_id和 doOrder 方法上的全局事务的transaction_id是不相同的，那么 doAdditional 增加库存依然是可以执行成功的 ，此时 若doOrder 方法 rollback ， undolog中的afterimage 和当前数据不相同【doadditional 增加库存成功】，导致回滚失败 出现脏数据。所以想问下 把doAdditional也放到分布式事务中 如何解决这个问题，不吝赐教！！！

**Comment by hy0619** [comment]
doAdditional 上加@GlobalTransaction 就可以了么

**Comment by luckyqiao** [comment]
> doAdditional 上加@GlobalTransaction 就可以了么， 是不是分支事务register的时候给branchSession加锁了 ，这样doAdditional无法修改库存数据？

是的，会加一个全局锁
