### ISSUE TITLE
Seata  undo_log无回滚日志，seata和@Transactional冲突 

### ISSUE THREAD

**Issue by codeCompilor** [seata/seata#3725]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

在测试过程中，在服务没有完全走完，打了断点进入调试模式，发现Seata  branch_table、lock_table 、undo_log无数据，只有global_table有数据，但Seata 事务能正常提交、回滚。

但为什么没数据呢？

最开始是@GlobalTransactional和@Transactional两个注解一起使用，虽然Seata事务能正常提交和回滚，但后面发现Seata  undo_log无数据，只有global_table有一条数据，其它表也没有数据

原因竟然是：seata的@GlobalTransactional和@Transactional冲突 

后面所有项目的所有方法都改成只使用@GlobalTransactional时，所有表都有数据了，而且Seata事务也能正常提交和回滚。

**@GlobalTransactional和@Transactional不兼容？不能一起使用？**

代码主要调用：saveClazzAndStudentError()

具体代码如下：

```
@Transactional
	@Override
	public Clazz save() {
		Clazz clazz = new Clazz();
		clazz.setClazzName("班级：" + RandomUtil.randomString(5));
		
		this.baseMapper.insert(clazz);
		
		return clazz;
	}
	
	
	@GlobalTransactional(rollbackFor = Throwable.class)
	@Transactional
	@Override
	public void saveClazzAndStudentError() {
		Clazz clazz = this.save();
		Result resultStudent=  restTemplate.getForObject("http://" + myNacosServiceName + "/student/saveError", Result.class);
		
		log.info("clazz=" + JsonUtil.toJson(clazz));
		log.info("resultStudent=" + JsonUtil.toJson(resultStudent));
	}
```

### Ⅵ. Environment:

- JDK version :jdk8
- OS :Windows10
- Others:Seata1.4.2

**Comment by ZaneGeng** [comment]
@GlobalTransactional和@transactional可以一起用，在Q&A 22中有解释

**Comment by javaCoderLead** [comment]
> @GlobalTransactional和@transactional可以一起用，在Q&A 22中有解释

@Transactional 只能位于标注在@GlobalTransaction的同一方法层次或者位于@GlobalTransaction 标注方法的内层。

这里说是可以一起用的。

**Comment by caohdgege** [comment]
@Transactional加在这里...那你的断点打在哪里的... 本地事务隔离了呀 怎么可能在数据库看到undo_log, 然后你没有进行本地事务commit, 也不会去注册分支事务和lock_table, 所以那边也肯定没数据的

**Comment by a364176773** [comment]
先把本地事务搞明白

**Comment by catman002** [comment]
@a364176773 点评好犀利

**Comment by codeCompilor** [comment]
> 先把本地事务搞明白demo那么多都用了本地事务注解，你搁着说不能混用，有没有想过是你操作上哪方面的问题？

嗯，你回去补脑子吧，我知道了还要提问？

**Comment by luckyqiao** [comment]
> > 先把本地事务搞明白demo那么多都用了本地事务注解，你搁着说不能混用，有没有想过是你操作上哪方面的问题？
> 
> 嗯，你回去补脑子吧，我知道了还要提问？

对于入门使用的问题，首先应该自己查。 项目的维护者既没有这么多精力，更没有这个义务去解答一些简单的入门使用问题。 issue区也不是用于解答使用问题的地方，如果你使用有问题，可以自己去查资料，或者通过钉群去询问他人。  在这里提一些入门问题，在浪费了项目资源的同时，还对维护者进行攻击，这种行为无法被接受。

**Comment by codeCompilor** [comment]
> @transactional加在这里...那你的断点打在哪里的... 本地事务隔离了呀 怎么可能在数据库看到undo_log, 然后你没有进行本地事务commit, 也不会去注册分支事务和lock_table, 所以那边也肯定没数据的


谢谢

**Comment by codeCompilor** [comment]
> > > 先把本地事务搞明白demo那么多都用了本地事务注解，你搁着说不能混用，有没有想过是你操作上哪方面的问题？
> > 
> > 
> > 嗯，你回去补脑子吧，我知道了还要提问？
> 
> 对于入门使用的问题，首先应该自己查。 项目的维护者既没有这么多精力，更没有这个义务去解答一些简单的入门使用问题。 issue区也不是用于解答使用问题的地方，如果你使用有问题，可以自己去查资料，或者通过钉群去询问他人。 在这里提一些入门问题，在浪费了项目资源的同时，还对维护者进行攻击，这种行为无法被接受。

我都笑了，在这里提了一个问题，有时间就回答，没时间就不要回答，而不是像你这样扯东扯西，没有一点作用。这个东西除了给我解答之外，后面还会有人遇到。大家都忙，像你这样的也就这样吧
