### ISSUE TITLE
apollo配置cluster的key与文档不一致

### ISSUE THREAD

**Issue by zh7158** [seata/seata#3736]
### Ⅰ. Issue Description
1.4.2版本集成apollo的配置项问题，文档中apollo集群cluster的key是‘cluster’，实际上代码中定义的是‘seata’
io.seata.config.apollo.ApolloConfiguration
private static final String APOLLO_CLUSTER = "seata";

**Comment by a364176773** [comment]
develop已经修复，1.5.0发布会修复
