### ISSUE TITLE
seata1.4.2docker镜像问题

### ISSUE THREAD

**Issue by phper666** [seata/seata#3757]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
我们现在采用dockerhub提供的镜像来部署，地址：https://hub.docker.com/layers/seataio/seata-server/1.4.2/images/sha256-dd89be061a8d378ad478eee83ea7fcbdf353b3d2e97671673f187dd0bbf33160?context=explore
目前我们使用的是1.4.2的版本，1.4.2版本有一个优化是我们需要的，那就是支持nacos dataId的方式来获取配置。所以我们使用了你们提供的镜像版本为1.4.2。
1、发现了一些问题，项目默认是不支持mysql8.0+,需要把原来的mysql-connector-java-5.1.35.jar删掉，换成mysql-connector-java-8.0.19.jar。所以我们需要制作一个新的镜像，在dockerfile里面使用RUN命名实现mysql的jar包复制，采用dockerhub提供的1.4.2版本作为基础镜像去修改时，发现不支持sh的命令，会报container_linux.go:367: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory
2、我们使用你们提供的latest镜像，发现里面的版本1.5.0-SNAPSHOT，该版本我们试过了，不支持nacos dataId方式获取配置

能否重新提供一个1.4.2版本支持/bin/sh命令的镜像？
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
@helloworlde @slievrly PTAL

**Comment by helloworlde** [comment]
@phper666 @a364176773 
1.4.2 和 1.5.0-SNAPSHOT 已经重新推送，在 1.4.2 和 1.5.0-SNAPSHOT 中基础镜像版本与之前不同；重新推送后已包含 sh 等常用命令；
MySQL lib 可以在 /seata-server/libs/jdbc 路径下找到

**Comment by phper666** [comment]
谢谢～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HelloWood ***@***.***&gt;
发送时间: 2021年5月20日 21:29
收件人: seata/seata ***@***.***&gt;
抄送: phper666 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[seata/seata] seata1.4.2docker镜像问题 (#3757)





 
@phper666 @a364176773
 1.4.2 和 1.5.0-SNAPSHOT 已经重新推送，在 1.4.2 和 1.5.0-SNAPSHOT 中基础镜像版本与之前不同；重新推送后已包含 sh 等常用命令；
 MySQL lib 可以在 /seata-server/libs/jdbc 路径下找到

**Comment by a364176773** [comment]
> @phper666 @a364176773
> 1.4.2 和 1.5.0-SNAPSHOT 已经重新推送，在 1.4.2 和 1.5.0-SNAPSHOT 中基础镜像版本与之前不同；重新推送后已包含 sh 等常用命令；
> MySQL lib 可以在 /seata-server/libs/jdbc 路径下找到
