### ISSUE TITLE
Inccorect BOM definition

### ISSUE THREAD

**Issue by JasonMing** [seata/seata#3761]
BOM, aka Bill-of-Material, is a "pom" type artifact that **declare all modules with version of current component**.
Commonly, BOMs should NOT contain declarations not belong to current component.
However, `seata-bom` imports `spring-framework-bom` and declares all dependencies seata use except the seata modules.
This is really a bad practice and it breaks the semantic of BOM!

**Comment by xingfudeshi** [comment]
@JasonMing Thank you for your suggestion. Can you submit a PR to optimize it?

**Comment by JasonMing** [comment]
I would like to move all the seata required dependencies from `seata-bom` to `seata-parent` to keep the parent managing versions of seata dependencies, then declare all modules in seata-bom.
But this change may break the behavior of seata-bom, is that ok?

**Comment by slievrly** [comment]
@JasonMing In fact, I think it is more reasonable to replace 'seata-bom' with 'seata-dependencies'.

**Comment by xingfudeshi** [comment]
@JasonMing I agree with @slievrly .

**Comment by JasonMing** [comment]
@slievrly does the `seata-dependencies`  contain both **seata modules** and **dependencies seata used**?
If so, when importing `seata-dependencies`, the versions in user project of  *dependencies seata used*  **MAY or MAY NOT** be management, it's all decided by the position when the import placed (maven resolve rule is "nearest wins, first wins"). This is very annoying to the user, *"why my dependencies are not aligned any more after importing `seata-dependencies`!?"*
If there is really necessary to include dependencies seat used, I suggest that separate to two modules:
- `seata-bom`, contains only modules
- `seata-dependencies` imports `seata-bom` and also define the dependencies seata used

**Comment by slievrly** [comment]
> @slievrly does the `seata-dependencies` contain both **seata modules** and **dependencies seata used**?
> If so, when importing `seata-dependencies`, the versions in user project of _dependencies seata used_ **MAY or MAY NOT** be managed, it's all decided by the position when the import placed (maven resolve rule is "nearest wins, first wins"). This is very annoying to the user, _"why my dependencies are not aligned any more after importing `seata-dependencies`!?"_
> If there is really necessary to include dependencies seat used, I suggest that separate to two modules:
> 
> * `seata-bom`, contains only modules
> * `seata-dependencies` imports `seata-bom` and also define the dependencies seata used

look forward you submit a PR to resolve this issue.

**Comment by wangliang181230** [comment]
@JasonMing Any progress recently?

**Comment by JasonMing** [comment]
@wangliang181230 Sorry for long time no response, you know, there is too much work from my company recently.

**Comment by wangliang181230** [comment]
> 
> 
> @wangliang181230 Sorry for long time no response, you know, there is too much work from my company recently.

Do you have time to solve this issue in the near future?

**Comment by JasonMing** [comment]
> > @wangliang181230 Sorry for long time no response, you know, there is too much work from my company recently.
> 
> Do you have time to solve this issue in the near future?

PR #3870 is ready~

**Comment by wangliang181230** [comment]
> 
> PR #3870 is ready~

Oh, I see. I'll review it.

**Comment by JasonMing** [comment]
BTW, for more refined control of build, It's better to replace maven with  gradle,  like spring/spring-boot  and many opensource projects did.
If using gradle, the bom will no longer require enumerating all modules by hand, and root project can configure the common settings for all submodules in one place. That will more friendly for managing the standalone modules like "seata-bom" and "seata-all".
