### ISSUE TITLE
seata与sentinel循环依赖

### ISSUE THREAD

**Issue by yujun110** [seata/seata#3766]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
sentinel-alibaba:2.2.2，seata:2.2.0,启动报错，循环依赖，内网环境，没法复制报错。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by a364176773** [comment]
请反馈到spring-cloud-alibaba社区
