### ISSUE TITLE
Seata  Saga模式ServiceTask State的ServiceType是SpringBean，为什么无法调用FeignClient代理对象方法

### ISSUE THREAD

**Issue by heibainengliang** [seata/seata#3771]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在使用seata saga模式时，ServiceTask 的方法调用是通过feignclient远程调用目标方法，但报
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'dictConsumer' available，
如果ServiceTask 的方法调用是当前服务的bean则可以执行。

### Ⅵ. Environment:

- JDK version : 1.8
- OS :
- Others:  'io.seata', name: 'seata-all', version: "1.4.0"

**Comment by heibainengliang** [comment]
SpringBeanServiceInvoker类的doInvoke方法中获取service bean方式：
Object bean = applicationContext.getBean(state.getServiceName());
所以通过applicationContext.getBean获取feign实例，需要在定义@FeignClient时指定qualifier属性。
例如：@FeignClient(value = "xxx",path = "/dict",fallbackFactory = DictApiFallback.class, qualifier = "dictApi")

**Comment by wangliang181230** [comment]
是需要手动配置的。
我记得，默认情况下，FeignClient生成的bean的名称是对应服务的application-name。
