### ISSUE TITLE
seata 1.4.2 集成springboot项目 在启用consul配置中心的时候，项目无法完成启动，一直获取配置失败

### ISSUE THREAD

**Issue by G-LION-G** [seata/seata#3772]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

 最近项目中考虑引入seata作为分布式事务解决方案，最开始我们是用springboot的yml配置文件作为配置中心，并做了压测，效果符合理想，后来参照官网高可用部署方式，我们用consul作为配置中心，就出现问题了，业务项目启动不起来，一直卡在读取配置，就像这样：

```
ERROR 45365 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5000 ms,op:GET,dataId:transport.threadFactory.workerThreadPrefix
ERROR 45365 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5003 ms,op:GET,dataId:transport.threadFactory.shareBossWorker
ERROR 45365 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5000 ms,op:GET,dataId:transport.type
ERROR 45365 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5001 ms,op:GET,dataId:transport.threadFactory.workerThreadSize
```
上面这个错误，断点调试 发现最开始是在SpringBootConfigurationProvider#get(dataId) 里面 获取 ConfigConsulProperties.class 这个bean 的时候卡住一段时间，大概有30秒，导致没有及时获取到consul连接配置，consul客户端没有及时完成初始化，这导致读取consul服务上配置数据超时失败，但是疑惑的是，后来consul客户端完成了初始化后，consul客户端从注册中心获取seata服务确总是失败，一直出现下面的错误，无法完成启动

```
ERROR 45365 --- [eoutChecker_2_1] i.s.c.r.netty.NettyClientChannelManager  : no available service found in cluster 'kun-ming', please make sure registry config correct and keep your seata server running
ERROR 45365 --- [eoutChecker_1_1] i.s.c.r.netty.NettyClientChannelManager  : no available service found in cluster 'kun-ming', please make sure registry config correct and keep your seata server running
```

我们事务组的配置如下：
service.vgroupMapping.ji9_tx_group = kun-ming

注册中心该服务其实是存在的

### Ⅲ. Describe what you expected to happen

我期望这个错误不应该存在，应该按照配置，能够在注册中心找到服务，期望这个问题尽快修复

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

最后我在ConsulRegisttryServiceImpl#refreshCluster(cluster) 方法中发现了问题，
refreshCluster(cluster) -调用-> getHealthyServices(getClusterName(), -1, -1)
其实getHealthService方法的service 参数应该使用上层方法refreshCluster(cluster) 传入的cluster 参数，而不应该从getClusterName() 获取服务名，因为getClusterName()获取的服务名是本地文件配置的。

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : centos 8 
- Others: 
 seata: seata-spring-boot-starter 1.4.2
springboot: 2.3.10.RELEASE
配置中心: consul
注册中心: consul

**Comment by a364176773** [comment]
server端的consul.cluster=kun-ming？

**Comment by a364176773** [comment]
server端的consul.cluster=kun-ming？

**Comment by a364176773** [comment]
粗略看了下，好像是存在问题，因为传入的cluster，但是用的却是getClusterName()，从本地读了clsutername，而不是getServiceGroup，或者直接使用cluster，我来处理，希望你有空可以参与测试，谢谢反馈

**Comment by G-LION-G** [comment]
server端的配置是consul.cluster=kun-ming

**Comment by G-LION-G** [comment]
另外希望能处理掉SpringBootConfigurationProvider#get(dataId) 这个方法获取configbean 会卡住的问题，😄😄。

**Comment by a364176773** [comment]
> 另外希望能处理掉SpringBootConfigurationProvider#get(dataId) 这个方法获取configbean 会卡住的问题，😄😄。

卡住？详细讲讲？

**Comment by a364176773** [comment]
目前先用default做cluster吧，因为client端默认拿的现在都是default，因为读错配置项了= -，等修复后再自定义

**Comment by G-LION-G** [comment]
1. ConfigurationFactory load registry配置文件的时候，在seata-springbootstarter环境下会被SpringBootConfigurationProvider 代理，所以ConfigurationFactory load 的registry 配置 是 yml 文件的 seata.regitry 配置内容；
2. ConfigurationFactory buildConfiguration 构造出来的配置类 也会被SpringBootConfigurationProvider代理，SpringBootConfigurationProvider 在读取 yml 中 seata.config.consul 这个配置内容时，是用 applicationContext.getBean(ConfigConsulProperties.class) 这个方式读取配置内容， 用这个方式这行getbean操作会卡住一段一时间，至少会卡住30秒以上，这样不能即使读取到consul的serveraddr配置内容，无法及时完成consulclient的初始化，也影响了 seatarm 初始化时获取配置
3. 这个问题导致 项目启动时间过长

**Comment by a364176773** [comment]
> 1. ConfigurationFactory load registry配置文件的时候，在seata-springbootstarter环境下会被SpringBootConfigurationProvider 代理，所以ConfigurationFactory load 的registry 配置 是 yml 文件的 seata.regitry 配置内容；
> 2. ConfigurationFactory buildConfiguration 构造出来的配置类 也会被SpringBootConfigurationProvider代理，SpringBootConfigurationProvider 在读取 yml 中 seata.config.consul 这个配置内容时，是用 applicationContext.getBean(ConfigConsulProperties.class) 这个方式读取配置内容， 用这个方式这行getbean操作会卡住一段一时间，至少会卡住30秒以上，这样不能即使读取到consul的serveraddr配置内容，无法及时完成consulclient的初始化，也影响了 seatarm 初始化时获取配置
> 3. 这个问题导致 项目启动时间过长

单独提一个issue，我抽空测一下

**Comment by G-LION-G** [comment]
好的，单独提了个issue #3777

**Comment by G-LION-G** [comment]
另外，还提了个需求，希望能够支持配置中心 自定义目录 #3778
