### ISSUE TITLE
@GlobalTransaction分支事务提交时检查lock_table表记录发现锁冲突后，重试一次就执行成功了，第二次不再检查了。

### ISSUE THREAD

**Issue by qq928389526** [seata/seata#3779]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
方法打上了全局事务注解 @GlobalTransaction，分支事务未打上@Transaction注解(4.1版本)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
调用链路：AbstractDMLBaseExecutor.execute ->connectionProxt.doRetryOnLockConflict ->connectionProxy.commit (这一步遇到了LockConflictException,然后执行rollback， rollback中执行了context.reset清空了xid等参数。)，遇到锁冲突重试执行到connectionProxy.doCommit的时候，直接执行了targetConnection.commit提交了分支事物（这个时候lock_table的记录锁还是在的。）

如果打上了Transaction注解，路由从AbstractDMLBaseExecutor.execute变成了ConnectionProxy.execute. LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT是true,遇到锁冲突直接不重试了（但是AbstractDMLBaseExecutor.execute为什么遇到LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT是true就重试，这两个类if判断反着来是为什么）

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 8
- OS :windows
- Others:

**Comment by a364176773** [comment]
1.4.2已经解决

**Comment by a364176773** [comment]
内重试反着来是为了保证开启本地事务下的重试时由于有本地锁持有且不会释放,所以需要反着来直接抛出异常回滚本地事务,优先让其他二阶段事务通过
外重试是不开启本地事务下的情况下会rollback释放本地锁,再重置前后镜像和sql,由于会rollback释放锁,所以允许多次重试.
想让内重试也可以得到锁就需要在本地事务注解下加入对需要修改的数据先通过select for update查询,再去update即可

**Comment by qq928389526** [comment]
可以只升级本地seata的包版本，不升级远程tc服务的版本，tc服务仍然是1.4.1，本地包版本是1.4.2  会有影响吗

**Comment by a364176773** [comment]
> 可以只升级本地seata的包版本，不升级远程tc服务的版本，tc服务仍然是1.4.1，本地包版本是1.4.2 会有影响吗

不影响,server端有空再挑个时间平滑升级即可
