### ISSUE TITLE
k8s seata集群模式store mode为db，Could not found global transaction xid

### ISSUE THREAD

**Issue by xrwang8** [seata/seata#3782]
![image](https://user-images.githubusercontent.com/68765051/120068439-47ba4200-c0b3-11eb-8873-0cd6b1abae05.png)
seata副本树为1时没有问题
seata副本数量大于一百分百出现改报错。副本时区都为UTC

**Comment by caohdgege** [comment]
不一定是时区，你两台机器的时间差超过一分钟基本上都不行了

**Comment by a364176773** [comment]
如何认为你是db模式,而不是file?

**Comment by xrwang8** [comment]
> 如何认为你是db模式,而不是file?

![image](https://user-images.githubusercontent.com/68765051/120127627-74c13e80-c1f2-11eb-9f10-d03a5b5b1ec2.png)

**Comment by a364176773** [comment]
不支持dataid内容是yml，换properties解决
