### ISSUE TITLE
seata 的锁是怎么实现的

### ISSUE THREAD

**Issue by pwjbj** [seata/seata#3787]
seata 的本地锁是不是就是mysql 的锁， 全局锁是什么样的逻辑呢，申请全局锁 是把tablename:key 插入带lock_table 中么， 移除全局锁 把这条记录删除，tablename:key 这个记录在 lock_table中就说明占用着全局锁么

**Comment by xyz327** [comment]
是的，具体实现是在 https://github.com/seata/seata/blob/develop/server/src/main/java/io/seata/server/storage/db/lock/LockStoreDataBaseDAO.java
