### ISSUE TITLE
seata和mybatis-plus冲突

### ISSUE THREAD

**Issue by lizihang4869** [seata/seata#3790]
在使用了seata之后，同时使用mybatis-plus操作数据库会使plus的增强插件都失效，比如plus的分页插件，自动填充功能，尤其是使用了plus的自动填充功能之后seata还会使plus的修改数据报错。希望官方可以重视一下这个问题，毕竟plus在mysql开发过程中确实极大的方便了开发

**Comment by a364176773** [comment]
没有冲突，自己整合的时候构建了个新的sqlsessionfactory导致，用mybatisplus自己的那个即可

**Comment by lizihang4869** [comment]
https://blog.csdn.net/zihangba/article/details/117440424?spm=1001.2014.3001.5501,您可以看看我发布的这个问题，确实使用了seata之后，mybatis-plus的所有插件功能都失效了。

**Comment by a364176773** [comment]
> [https://blog.csdn.net/zihangba/article/details/117440424?spm=1001.2014.3001.5501,您可以看看我发布的这个问题，确实使用了seata之后，mybatis-plus的所有插件功能都失效了。](https://blog.csdn.net/zihangba/article/details/117440424?spm=1001.2014.3001.5501,%E6%82%A8%E5%8F%AF%E4%BB%A5%E7%9C%8B%E7%9C%8B%E6%88%91%E5%8F%91%E5%B8%83%E7%9A%84%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%8C%E7%A1%AE%E5%AE%9E%E4%BD%BF%E7%94%A8%E4%BA%86seata%E4%B9%8B%E5%90%8E%EF%BC%8Cmybatis-plus%E7%9A%84%E6%89%80%E6%9C%89%E6%8F%92%E4%BB%B6%E5%8A%9F%E8%83%BD%E9%83%BD%E5%A4%B1%E6%95%88%E4%BA%86%E3%80%82)

不会失效，失效是因为你构建了sqlsessionfactory，mybatis plus 的springbootstarter的依赖自动会构建这东西

**Comment by a364176773** [comment]
去看看mybatisplus自己的sessionfactory源码里干了什么吧

**Comment by a364176773** [comment]
https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-boot-starter/src/main/java/com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.java

**Comment by a364176773** [comment]
return mybatisSqlSessionFactoryBean; 就是个错误的配置
return mybatisSqlSessionFactoryBean.getObject();
