### ISSUE TITLE
seata 1.3和mybatis plus3.4.1 冲突

### ISSUE THREAD

**Issue by XuJingJingZhenShuaiA** [seata/seata#3793]
最近整合spring cloud alibaba全家桶
发现mybatis plus自带方法部分不可用（insert可以用）Wrappers不可用

参考这两篇博文没能解决
http://seata.io/zh-cn/blog/seata-mybatisplus-analysis.html
http://seata.io/zh-cn/blog/springboot-dubbo-mybatisplus-seata.html

希望有大佬指点一下

**Comment by a364176773** [comment]
> 最近整合spring cloud alibaba全家桶
> 发现mybatis plus自带方法部分不可用（insert可以用）Wrappers不可用
> 
> 参考这两篇博文没能解决
> http://seata.io/zh-cn/blog/seata-mybatisplus-analysis.html
> http://seata.io/zh-cn/blog/springboot-dubbo-mybatisplus-seata.html
> 
> 希望有大佬指点一下

请提供异常堆栈信息

**Comment by XuJingJingZhenShuaiA** [comment]
> > 最近整合spring cloud alibaba全家桶
> > 发现mybatis plus自带方法部分不可用（insert可以用）Wrappers不可用
> > 参考这两篇博文没能解决
> > http://seata.io/zh-cn/blog/seata-mybatisplus-analysis.html
> > http://seata.io/zh-cn/blog/springboot-dubbo-mybatisplus-seata.html
> > 希望有大佬指点一下
> 
> 请提供异常堆栈信息

emmmmmmm......
他不是报错的那种 比如查询返回null 新增返回0 这都没有异常
但是自定义的sql就很正常 另外 insert方法可用

**Comment by xingfudeshi** [comment]
@XuJingJingZhenShuaiA Can you debug it,please?
