### ISSUE TITLE
Could not found global transaction xid是否会导致数据库连接没被释放

### ISSUE THREAD

**Issue by ouyangguowei** [seata/seata#3802]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
生产接入了单机的seata，由于某个dubbo接口耗时较高，导致调用超时，然后dubbo默认发起了两次重试，业务日志中是看到了如下异常：
 Could not commit JDBC transaction; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.151.131:8091:142229867813416960, may be has finished.]

由于当前业务也算处在高峰期，几分钟后就报数据就连接池拿不到连接的错了
![image](https://user-images.githubusercontent.com/15991270/120629013-eec62180-c497-11eb-9c36-41f57dc72750.png)

然后根据报错的具体信息看源码
![image](https://user-images.githubusercontent.com/15991270/120628964-e1a93280-c497-11eb-8b0e-7bb0f4aadf26.png)

想问，在recognizeLockKeyConflictException抛出异常后，后面的commit()就不会被执行到，那连接什么时候会被释放
这是导致数据库连接被打满的原因吗？？？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- OS : linux
- Others:

**Comment by ouyangguowei** [comment]
版本1.4

**Comment by a364176773** [comment]
不会出现，close是框架层调用的，seata只是代理
最简单的一个测试，自己jdbc写端代码，接口里rootcontextbind一个根本不存在的xid，自己按规范写jbdc的操作， datasource用的是seata代理后的那个datasource做验证，当然前提是你了解什么时候连接池才会回收连接，否者连接池没有回收连接你转嫁到seata上，认为是seata的问题就不对了
