### ISSUE TITLE
Bean named 'dataSourceProxy' is expected to be of type 'io.seata.rm.datasource.DataSourceProxy' but was actually of type 'com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$d38bdd7b'

### ISSUE THREAD

**Issue by lixiaoabc** [seata/seata#3805]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Bean named 'dataSourceProxy' is expected to be of type 'io.seata.rm.datasource.DataSourceProxy' but was actually of type 'com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$d38bdd7b'

### Ⅱ. Describe what happened
seata1.4.2  when i start the project
```
@Configuration
@EnableConfigurationProperties({MybatisPlusProperties.class})
public class DataSourceConfiguration {


  @Bean
  @ConfigurationProperties(prefix = "spring.datasource")
  public DataSource dataSource() {
    return new DruidDataSource();
  }

  @Bean
  public DataSourceProxy dataSourceProxy(DataSource dataSource) {
    return new DataSourceProxy(dataSource);
  }

  @Bean
  public SqlSessionFactory sqlSessionFactoryBean(DataSourceProxy dataSourceProxy,
      MybatisPlusProperties mybatisProperties) {
    MybatisSqlSessionFactoryBean bean = new MybatisSqlSessionFactoryBean();
    bean.setDataSource(dataSourceProxy);

    ResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
    try {
      Resource[] mapperLocaltions = resolver
          .getResources(mybatisProperties.getMapperLocations()[0]);
      bean.setMapperLocations(mapperLocaltions);

      if (StringUtils.isNotBlank(mybatisProperties.getConfigLocation())) {
        Resource[] resources = resolver.getResources(mybatisProperties.getConfigLocation());
        bean.setConfigLocation(resources[0]);
      }
      return bean.getObject();
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }
}
```

**Comment by a364176773** [comment]
使用druid，而不要用druid-spring-boot-starter

**Comment by wangliang181230** [comment]
```
@bean
public DataSourceProxy dataSourceProxy(DataSource dataSource) {
    return new DataSourceProxy(dataSource);
}
```
返回类型改成`DataSource`就可以了。

**Comment by wangliang181230** [comment]
哦，根本原因不是类型不匹配啊。

**Comment by selfishlover** [comment]
Register DataSourceProxy bean by yourself is discouraged since 1.3. If you are using seata starter, you don't need to care about DataSourceProxy(starter would process it automatically), just register and use Datasource bean in your old way.

**Comment by lixiaoabc** [comment]
> Register DataSourceProxy bean by yourself is discouraged since 1.3. If you are using seata starter, you don't need to care about DataSourceProxy(starter would process it automatically), just register and use Datasource bean in your old way.

thankyou ,project start success,

**Comment by lixiaoabc** [comment]
> ```
> @bean
> public DataSourceProxy dataSourceProxy(DataSource dataSource) {
>     return new DataSourceProxy(dataSource);
> }
> ```
> 
> 返回类型改成`DataSource`就可以了。

我把这个去掉启动成功了
