### ISSUE TITLE
获取业务对象自增id时，实际值变成了undo表的自增id了

### ISSUE THREAD

**Issue by ZaynJiang** [seata/seata#3811]
业务对象主键使用@GeneratedValue(strategy = GenerationType.IDENTITY)自增，插入数据库后，代码立即获取主键值实际为undo表的自增id。

![image](https://user-images.githubusercontent.com/11373799/120988634-525e9080-c7b1-11eb-931e-df5e5de6a5fe.png)
![image](https://user-images.githubusercontent.com/11373799/120988663-5a1e3500-c7b1-11eb-8cbd-c1480aedf066.png)

**Comment by jsbxyyx** [comment]
You can delete the primary key id of the undo_log table
你可以删除undo_log表主键id

**Comment by ZaynJiang** [comment]
> You can delete the primary key id of the undo_log table
> 你可以删除undo_log表主键id
ok,我试下
