### ISSUE TITLE
官方文档《最佳实践3：client的精细化控制》

### ISSUE THREAD

**Issue by abel533** [seata/seata#3815]
## 最佳实践3：client的精细化控制

假定现在存在seata集群，Guangzhou机房实例运行在性能较高的机器上，Shanghai集群运行在性能较差的机器上
现存微服务架构项目projectA、projectA中有微服务ServiceA、ServiceB、ServiceC与ServiceD
其中ServiceD的流量较小，其余微服务流量较大
那么此时，我们可以将ServiceD微服务引流到Shanghai集群中去，将高性能的服务器让给其余流量较大的微服务（反之亦然，若存在某一个微服务流量特别大，我们也可以单独为此微服务开辟一个更高性能的集群，并将该client的virtual group指向该集群，其最终目的都是保证在流量洪峰时服务的可用）

![image](https://user-images.githubusercontent.com/1787798/121315205-b1034600-c93a-11eb-90f0-bf37af76dc43.png)

## 疑问？
如果A,B,C要用到D服务，在这种情况下的分布式事务，ABC和D连的不同的TC？事务还能在ABC和D之间传递吗？

**Comment by wangliang181230** [comment]
一般情况下，会使用异步二阶段来消峰，而不是使用另一个TC来消峰。
这样反而会提高运维的成本，以及seata机制的改造。

**Comment by a364176773** [comment]
可以传播，只要主备都是用的同一个数据库即可
