### ISSUE TITLE
拉取代码后本地编译不了 seata-serializer-protobuf  这个模块下提示类找不到

### ISSUE THREAD

**Issue by Daley-wdl** [seata/seata#3819]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/22542716/121453747-371f9b00-c9d4-11eb-9428-1c55a932739b.png)

### Ⅱ. Describe what happened

启动server报错，查看seata-serializer-protobuf 这个module ，确实没有相关类

![image](https://user-images.githubusercontent.com/22542716/121453850-6930fd00-c9d4-11eb-812e-dc51b40deb2a.png)

`
    <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>seata-serializer-all</artifactId>
            <version>${project.version}</version>
     </dependency>
`

这个是 server模块里引入的序列化包，但是这个包会把 serializer 模块里所有的序列化类型都引入，个人认为，应该只需引入一个就可以，于是做了如下修改
![image](https://user-images.githubusercontent.com/22542716/121454128-da70b000-c9d4-11eb-9149-ce7bf7afacbf.png)

果然报错消失，启动成功
![image](https://user-images.githubusercontent.com/22542716/121454419-52d77100-c9d5-11eb-8dad-7dc760078d69.png)

### Ⅲ. Describe what you expected to happen

 这个问题是我编译的过程操作不对吗

### Ⅵ. Environment:

- JDK version : 1.8
- OS : mac
- Others:  seata 分支版本 1.4.2

**Comment by a364176773** [comment]
官网faq，还有你排除了all，未来client端使用了kryo fst等序列化，你server端怎么解析？你只弄了个seata默认的序列化依赖
