### ISSUE TITLE
请教关于全局回滚或提交决议的问题

### ISSUE THREAD

**Issue by ZaynJiang** [seata/seata#3821]
我看有文档说二阶段是否提交，是tc结合各个rm上报状态来判断回滚或提交的。

         但是实际我看tm代码，是tm catch到异常就会通知tc通知各个rm回滚，tm没有异常就通知commit，不管各rm一阶段上报的状态是否失败。

        这个是否矛盾呢，设计是这样的吗，还是我理解有误。

        我自己试验A调用B和C服务，C入库主健重复异常，这样应该是C的一阶段上报失败了，但是A吃掉调C的异常，最终没全局回滚。

      请问如果是这样的话，rm上报一阶段的状态有什么用呢，是否提交回滚完全根据tm感知异常情况

**Comment by a364176773** [comment]
不会管rm的状态,因为rm的状态也不代表是最终状态
1.rm report在提交时部分事务模式是关闭report的,因为是tm决议,可以提升性能
2.tm决议简单快速性能相对tc来说,tc压力就被各个tm所分散
3.rm report如果是回滚时,tc会直接跳过他,因为rm report失败说明本地事务已经回滚其分支,无需浪费时间去再下发回滚通知

**Comment by ZaynJiang** [comment]
> 不会管rm的状态,因为rm的状态也不代表是最终状态
> 1.rm report在提交时部分事务模式是关闭report的,因为是tm决议,可以提升性能
> 2.tm决议简单快速性能相对tc来说,tc压力就被各个tm所分散
> 3.rm report如果是回滚时,tc会直接跳过他,因为rm report失败说明本地事务已经回滚其分支,无需浪费时间去再下发回滚通知



> 不会管rm的状态,因为rm的状态也不代表是最终状态
> 1.rm report在提交时部分事务模式是关闭report的,因为是tm决议,可以提升性能
> 2.tm决议简单快速性能相对tc来说,tc压力就被各个tm所分散
> 3.rm report如果是回滚时,tc会直接跳过他,因为rm report失败说明本地事务已经回滚其分支,无需浪费时间去再下发回滚通知

理解了，谢谢
