### ISSUE TITLE
用develop编译apm-skywalking的agent插件部署后显示很多ip地址

### ISSUE THREAD

**Issue by stevenliuit** [seata/seata#3827]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/4044994/122023094-ca543880-cdf9-11eb-8a89-7497e0ce4ae6.png)
![image](https://user-images.githubusercontent.com/4044994/122023318-fff92180-cdf9-11eb-9ded-1186a940e9a0.png)
打的是develop的分支代码 在master上和其他分支没有找到ext的目录
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zhaoyuguang** [comment]
Repeat issue, please follow up the https://github.com/seata/seata/issues/3810  progress

**Comment by zhaoyuguang** [comment]
If possible, please help test the PR of this issue repair

**Comment by stevenliuit** [comment]
> If possible, please help test the PR of this issue repair

测试了 合并的这个：https://github.com/zhaoyuguang/seata/tree/fix_sw_peer_split_0
发现图像变大了 
![image](https://user-images.githubusercontent.com/4044994/122037060-d09ce180-ce06-11eb-94f5-8953ae927049.png)

这个PR还是有问题

**Comment by zhaoyuguang** [comment]
替换新的探针需要重启应用服务 才能生效

**Comment by stevenliuit** [comment]
> 替换新的探针需要重启应用服务 才能生效

重启了seata应用 然后出现了一大片 用的是你那个seata-fix_sw_peer_split_0打的包。我在seata的server添加的参数是这个
-javaagent:/opt/appdata/agent/skywalking-agent.jar -Dskywalking.agent.service_name=seata_tc -Dskywalking.collector.backend_service=10.6.50.39:11800 -Dskywalking.plugin.jdbc.trace_sql_parameters=true -Dskywalking.plugin.seata.server=true

**Comment by stevenliuit** [comment]
> 替换新的探针需要重启应用服务 才能生效

是应用服务也添加探针吗？我这两种都试了 一个是应用上 一个是seata的服务上

**Comment by zhaoyuguang** [comment]
是的 seata 客户端服务端 都要引入seata插件
你的部署SkyWalking插件库不是统一的么？

**Comment by stevenliuit** [comment]
> 是的 seata 客户端服务端 都要引入seata插件
> 你的部署SkyWalking插件库不是统一的么？

客户端没重启 我重启客户端试试吧 20多个项目不敢轻易重启 哎……！！！

**Comment by slievrly** [comment]
@stevenliuit fixed in #3810
