### ISSUE TITLE
seata server端读取nacos配置问题

### ISSUE THREAD

**Issue by Daley-wdl** [seata/seata#3829]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

     起因是我尝试把seata server的启动模式改成nacos读取配置，并且nacos的文件格式是yaml，那么我很自然的就配置成如下的格式了，但是当我启动server的时候，却发现 store.mode 始终是file，我很不解，明明配置的db模式，于是debug源码，发现读出来的样子是一行一行解析出来的key-value，这里会不会造成一些误解

![image](https://user-images.githubusercontent.com/22542716/122394662-d03c4c00-cfa8-11eb-82a7-60a5c408dcf5.png)

![image](https://user-images.githubusercontent.com/22542716/122394592-bb5fb880-cfa8-11eb-892e-d5e5a50b27fb.png)

![image](https://user-images.githubusercontent.com/22542716/122395451-91f35c80-cfa9-11eb-9e01-6ca7c972acf2.png)

我把配置修改成下面，就可以读到了
![image](https://user-images.githubusercontent.com/22542716/122395715-d67ef800-cfa9-11eb-8b3d-45a33eab6489.png)

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

这里是不是可以识别一下nacos的文件格式来适配呢？

**Comment by a364176773** [comment]
后续会支持yaml的解析,目前只能支持properties

**Comment by chenlei3641** [comment]
Please assign it to me
