### ISSUE TITLE
seata是否支持修改global_table中事务的超时时间，默认60

### ISSUE THREAD

**Issue by liuyuyan914** [seata/seata#3832]
## Why you need it?
有些长事务60s处理不完，但业务上允许超过60s

## How it could be?
可以动态设置全局事务的超时时间

**Comment by wangliang181230** [comment]
`@GlobalTransactional`注解上，可以修改的。

**Comment by wangliang181230** [comment]
如果想全局修改，也可以在client端修改配置`seata.tm.default-global-transaction-timeout=60000`

**Comment by liuyuyan914** [comment]
> 如果想全局修改，也可以在client端修改配置`seata.tm.default-global-transaction-timeout=60000`

好的，感谢
