### ISSUE TITLE
Global lock wait timeout问题请教

### ISSUE THREAD

**Issue by ZaneGeng** [seata/seata#3833]
![微信截图_20210622094529](https://user-images.githubusercontent.com/13901003/122849789-c2871d80-d33e-11eb-8eba-f7bf7d554ac4.png)

在订单服务中，修改产品库存的时候爆出错误如上图。

seata1.4版本，使用AT模式

**Comment by ZaneGeng** [comment]
seata1.4版本，使用AT模式

**Comment by wangliang181230** [comment]
首先，你要知道AT模式的原理，在数据一致性方面，它是基于分布式锁来防止数据二阶段提交前被脏写。
所以，你要查一下，你这条数据是否存在哪个分支事务还没有回滚掉，导致分布式锁没有释放。使下一次更新数据时，锁还存在，且一直没释放导致获取锁失败。

**Comment by wangliang181230** [comment]
报出这个错，是很正常的现象，你要解决的是为什么之前的事务没有回滚成功。
产生这个现象的原因，大部分是你业务数据被脏写了。
需检查其他地方还有哪里的代码在修改这条数据，但是没有使用分布式事务或GlobalLock

**Comment by ZaneGeng** [comment]
> 报出这个错，是很正常的现象，你要解决的是为什么之前的事务没有回滚成功。
> 产生这个现象的原因，大部分是你业务数据被脏写了。
> 需检查其他地方还有哪里的代码在修改这条数据，但是没有使用分布式事务或GlobalLock

的确是业务有个分支占用着锁没有释放，也同步找到一篇文章有类似解释：https://blog.csdn.net/CSDN877425287/article/details/112304665，谢谢

**Comment by a364176773** [comment]
所有写场景请保证是从有globaltransational注解下进入
