### ISSUE TITLE
sofarpc 组件 sofaRequest.addRequestProp 和  RpcInternalContext.getContext().setAttachment 的key 报错

### ISSUE THREAD

**Issue by ShihuiXu** [seata/seata#3835]
![image](https://user-images.githubusercontent.com/19235156/123031052-42cc8200-d416-11eb-8979-7898dd88392a.png)
![image](https://user-images.githubusercontent.com/19235156/123031085-4fe97100-d416-11eb-9839-2c869bd926dd.png)

sofa rpc  sofaRequest.addRequestProp 和  RpcInternalContext.getContext().setAttachment 的key 要求以“.”或者“_”开头，不然会报错，截图部分是本人修改后的。

**Comment by a364176773** [comment]
请补充报错异常信息

**Comment by ShihuiXu** [comment]
我是通过httpClient 调用 sofa-rpc rest协议，自定义实现Jersey过滤器，然后取出header中的TX_XID绑定，再进入sofarpc TransactionContextProviderFilter过滤器。异常信息没有打印，这边通过debug展示异常位置。
![9(76{NB21Z@}4K~@XNX8WAL](https://user-images.githubusercontent.com/19235156/123187396-aa450900-d4cc-11eb-9006-4385b19d085d.png)
![3DU99UFLCTI0U YW_U%N1ZY](https://user-images.githubusercontent.com/19235156/123187408-b03aea00-d4cc-11eb-8eb9-e9d5fbd5dbd3.png)

**Comment by delosEco** [comment]
![image](https://user-images.githubusercontent.com/30037372/134880571-be443882-f4c4-4187-aeef-21f4ac5c5187.png)
这个TransactionContextProviderFilter如果从RootContext的threadLocal中获取了对应的TX_XID，会出现这个不符合sofarpc的key规则的错误。
