### ISSUE TITLE
[Discussion]Metrics in Seata

### ISSUE THREAD

**Issue by zhengyangyong** [seata/seata#384]
Hi everyone, as we know `Metrics` is in fescar roadmap, it used to improve system observability, here is my idea:

### Concepts
1. Fescar is a middle-ware and will integrated into other system, so must import other lib(jar) as less as possible in order to reduce the risk of dependency conflicting;
2. The implement of the metrics must high-performance and low resource-usage, otherwise will reduce the throughput of original system;
3. Plug-In style activation, whether metrics take effect depend on whether has any metrics implement jar had imported;
4. Do not use spring, because there are so many released version of spring and easy make dependency conflicting;
5. First we can export small number of core metrics into prometheus, then we can add more metrics and connect to more monitor system as requirement from community.

### New Modules
I will add two new modules:

![default](https://user-images.githubusercontent.com/374335/52621689-ef130b00-2ee2-11e9-909c-b8f56a74a8aa.png)

- fescar-metrics: basic metrics api module without implement,include interface of`Gauge`,`Counter`,`Timer`,`Registry`,`Publisher` etc... we can implement them with many components such as [spectator](http://netflix.github.io/spectator/en/latest/), [dropwizard metrics](https://metrics.dropwizard.io/4.0.0/getting-started.html), and implement publish metrics data to [prometheus](https://prometheus.io/docs/introduction/overview/), zabbix etc...

| Meter Type | Description                                                  |
| ---------- | ------------------------------------------------------------ |
| Gauge      | Single value often used to record the current(latest) value like temperature, live users etc... |
| Counter    | Often used to record count value, need output `total`, `count`, `max`, `average` and `tps`, the average = `total` / `count`, and the tps = `total` / `cycle(window time)` |
| Timer      | Often used to record time delay, need output `total`,`count`,`max` and `average`, the average = `total` / `count`, it's increment method include TimeUnit and support microsecond precision |

*All metrics type will inherited from `Meter`, and export data to `Measurement` when measure() called.*

- fescar-metrics-prometheus: metrics implement with a simple meter implement and publish to  prometheus for default scenario, will implement as higher formance as possible and reduce the resource usage.

#### How Metrics Module Load
Will use EnhancedServiceLoader not Spring because Spring will remove at v1.5.x, so whether metrics is enabled depends on any metrics implement module is imported.

#### Default Export Metrics
I think we can export TC metrics first, included :
* fescar.transaction(role=tc,meter=gauge,status=active/committed/rollback) : current active/committed/rollback transaction count
* fescar.transaction(role=tc,meter=counter,statistic=count,status=committed/rollback) :  current cycle(window time) committed/rollback transaction count
* fescar.transaction(role=tc,meter=counter,statistic=tps,status=committed/rollback) : current cycle(window time) committed/rollback transaction per second
* fescar_transaction(role=tc,meter=timer,statistic=total,status=committed/rollback) : current cycle(window time) committed/rollback total transaction milliseconds
* fescar_transaction(role=tc,meter=timer,statistic=count,status=committed/rollback) : current cycle(window time) committed/rollback transaction count
* fescar_transaction(role=tc,meter=timer,statistic=average,status=committed/rollback) : current cycle(window time) committed/rollback average transaction milliseconds
* fescar_transaction(role=tc,meter=timer,statistic=max,status=committed/rollback) : current cycle(window time) committed/rollback max transaction milliseconds

TM:
coming soon.. , such as
fescar.transaction(role=tm,name={GlobalTransactionalName},meter=gauge,status=active) : current active transaction number separated by transaction name

RM:
coming soon.. , such as 
fescar.transaction(role=rm,name={BranchTransactionalName},mode=at/mt,meter=gauge,status=active) : current active branch transaction number separated by transaction name

**Comment by jovany-wang** [comment]
I'll take a look at this issue.

**Comment by zwjtech** [comment]
I'll take a look at this issue.

**Comment by luyiisme** [comment]
I don't think it is a good idea to create a metric api module in seata. 
Seata is not a  framework or an application container. 
I recommend  that Seata provides some ways to expose its status ,and  make actions which can change key statuses can be intercepted.
For example, the coordinator can emit an event when executes a  global Commit, a metric listener can registed and observe the event.
we can create many metric modules for metric providers. such as: "seata-metrics-promethues","seata-metrics-Dropwizard"...

对于 seata 创建一套自有 metrics api (包括注册表，时钟等组件概念)的方式感觉过重了，不是个好主意。 实际上 seata 核心代码部分不引入和管理维护这些概念，也可以达到度量的目标。 推荐 seata 完善提供一些扩展机制，比如事件机制，或一些拦截器的注入等方式，方便外部能感兴趣和响应 seata 的重要状态变更行为。 Metrics 代码埋点工具有很多既有方案（比如 promethues,Dropwizard,lookout...）都可以面向 seata 的扩展机制实现相应的埋点接入（当然我们可以默认提供一种实现，但所有三方工具都是平等的）。  而且上述扩展的机制，后续可以带来更多的可能性，不止是 metrics。

**Comment by zhengyangyong** [comment]
从开发者角度来看非常赞成先做扩展机制，再考虑metrics的实现；
从使用者（用户）角度来看是否提供默认metrics实现也许需要重新审视roadmap。
