### ISSUE TITLE
nacos-config.sh 执行脚本报错

### ISSUE THREAD

**Issue by hudailiggg** [seata/seata#3841]
执行脚本报语法错误：
[root@mongo nacos]# sh ./nacos-config.sh -h 127.0.0.1 -p 8848 -g SEATA_GROUP -t 5a3c7d6c-f497-4d68-a71a-2e5e3340b3ca -u nacos -w nacos
./nacos-config.sh: line 15: $'\r': command not found
./nacos-config.sh: line 18: syntax error near unexpected token `$'in\r''
'/nacos-config.sh: line 18: `  case $opt in

**Comment by huan415** [comment]
dos2unix nacos-config.sh

**Comment by hongwen1993** [comment]
笑死
