### ISSUE TITLE
AT模式下，分支事务如何进行标记失败？

### ISSUE THREAD

**Issue by ifrush** [seata/seata#3842]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
A->B，A-C。 C 做了一些业务逻辑上判断，再不抛出异常的情况下如何标记本分支事务执行失败？
## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
在业务代码中使用TransationManageHolder.get().rollback() 以及GlobalTransactionContext.getCurrentOrCreate().rollBack() 都会提示 may be has finished。

**Comment by a364176773** [comment]
自己c返回的result里放个code，自己业务上读取判断不就行了吗
