### ISSUE TITLE
事务结束时没有清空RpcContext中的事务ID

### ISSUE THREAD

**Issue by lanok2770** [seata/seata#3844]
事务结束时只清空了本地RootContext中的事务ID，而没有清空RpcContext中的事务ID，导致A事务结束后同一个线程中再去RPC调用其他服务B，A依然会从RpcContext中传递事务ID，而下B服务拿着这个事务ID去 seata-server 中查找不到（被A服务事务结束时删掉了），导致异常
![image](https://user-images.githubusercontent.com/86766571/124084701-d8ed5180-da81-11eb-80ed-12346473f468.png)

**Comment by lanok2770** [comment]
> 事务结束时只清空了本地RootContext中的事务ID，而没有清空RpcContext中的事务ID，导致A事务结束后同一个线程中再去RPC调用其他服务B，A依然会从RpcContext中传递事务ID，而下B服务拿着这个事务ID去 seata-server 中查找不到（被A服务事务结束时删掉了），导致异常
![image](https://user-images.githubusercontent.com/86766571/124083220-341e4480-da80-11eb-864e-3b3efa888537.png)

**Comment by a364176773** [comment]
> > 事务结束时只清空了本地RootContext中的事务ID，而没有清空RpcContext中的事务ID，导致A事务结束后同一个线程中再去RPC调用其他服务B，A依然会从RpcContext中传递事务ID，而下B服务拿着这个事务ID去 seata-server 中查找不到（被A服务事务结束时删掉了），导致异常
> > ![image](https://user-images.githubusercontent.com/86766571/124083220-341e4480-da80-11eb-864e-3b3efa888537.png)

请提供复现的demo，rpc框架是什么，如果是spring cloud，那么从http请求头获取，压根不需要清理，而seata在rm响应的时候会镜像情况rootcontext中的xid，如果你频繁遇到这个问题，要么是服务重试，要么是异步化调用，要么是服务超时

**Comment by a364176773** [comment]
你给的信息完全没有这个xid什么时候被决议的，决议状态是什么，就凭这个截图信息无法判断

**Comment by lanok2770** [comment]
RPC框架是Dubbo，RootContext 不清理的话不是一直会存在线程内存中吗？就算事务结束了依然会在后续的RPC调用中往后传递

**Comment by a364176773** [comment]
> RPC框架是Dubbo，RootContext 不清理的话不是一直会存在线程内存中吗？就算事务结束了依然会在后续的RPC调用中往后传递
> ![image](https://user-images.githubusercontent.com/86766571/124086931-1a7efc00-da84-11eb-8e7c-f45cba09546f.png)

,你这个是一个线程,又不是2个线程,事务B本身就会清除呀,你加到注解seataTest上不就好了,不过我明白了你的意思,我觉得如果你一直是这样使用的话,是你用法有问题,就应该放到最外层做为事务的开启,你现在是单个线程,隐私传参完毕后,没有清空,下一次rpc又把这参数带过去了

**Comment by Jettisons** [comment]
我来认领这个任务

**Comment by lanok2770** [comment]
注解不能加到seataTest上，因为我就只是想在callBServer 中用事务， callCServer 只是调用C服务记录一下业务日志，所以不管前面是否异常回滚，C都要正常提交

**Comment by lvekee** [comment]
在一个全局事务中，如果需要某些业务逻辑不在全局事务的管辖范围内，则在调用前，把 XID 解绑：String unbindXid = RootContext.unbind();

**Comment by lvekee** [comment]
待相关业务逻辑执行完成，再把 XID 绑定回去，即可实现全局事务的恢复：RootContext.bind(unbindXid);

**Comment by lvekee** [comment]
> 注解不能加到seataTest上，因为我就只是想在callBServer 中用事务， callCServer 只是调用C服务记录一下业务日志，所以不管前面是否异常回滚，C都要正常提交

可以在seataTest上加注解然后在C服务手动解绑xid

**Comment by lanok2770** [comment]
> > 注解不能加到seataTest上，因为我就只是想在callBServer 中用事务， callCServer 只是调用C服务记录一下业务日志，所以不管前面是否异常回滚，C都要正常提交
> 
> 可以在seataTest上加注解然后在C服务手动解绑xid

这只是个例，还有可能调用很多其他服务，总不能在所有服务上都手动解绑一次，我现在的做法是@GlobalTransactional注解退出的时候加拦截器，手动清空 RootContext 的XID，但是我觉得框架应该也改一下，尽量能像 spring 的 @Transactional 一样使用

**Comment by slievrly** [comment]
@lanok2770 dubbo version？

**Comment by slievrly** [comment]
I found some problems. `RpcContext.removeContext() ` is different between dubbo 2.7.0 and 2.7.4.

dubbo 2.7.0
ContextFilter ， it just act on provider filter, so it can't clean the consumer‘s attachment.
![image](https://user-images.githubusercontent.com/8758457/124220524-84ed7600-db30-11eb-929a-984eda333453.png)

dubbo 2.7.4
In addition to `ContextFilter`, here's one `ConsumerContextFilter`, it can clean the consumer‘s attachment.
![image](https://user-images.githubusercontent.com/8758457/124220887-2ecd0280-db31-11eb-85a9-1c9cf45a93bb.png)

**Comment by qq928389526** [comment]
全局事物提交或者回滚时，DefaultGlobalTransaction 中commit和rollback  调用了suspend,并已经在该方法中unbind了xid

**Comment by a364176773** [comment]
经查看dubbo源码，是有做清除的，seata自身的也做了清除，未来透传的实现那块的传参会由seata自身来清除，以防rpc框架升级迭代后导致不统一，或者有bug的问题

**Comment by slievrly** [comment]
@qq928389526 `RpcContext`(from dubbo package) not clean the attachment.

**Comment by lanok2770** [comment]
@slievrly dubbo version 2.7.10
![image](https://user-images.githubusercontent.com/86766571/124245138-45378600-db52-11eb-8fa2-f0d4e9d058b3.png)

**Comment by a364176773** [comment]
> @slievrly dubbo version 2.7.10
> ![image](https://user-images.githubusercontent.com/86766571/124245138-45378600-db52-11eb-8fa2-f0d4e9d058b3.png)

![image](https://user-images.githubusercontent.com/19943636/124254108-5042e400-db5b-11eb-9308-338184d3cda8.png)
在这呢

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/124254160-5d5fd300-db5b-11eb-95fe-1c48f8ea8d7f.png)
包括3.0都有做清理

**Comment by a364176773** [comment]
https://dubbo.apache.org/zh/docs/v2.7/user/examples/attachment/
如果你觉得seata写的有问题,应该去看下dubbo如何描述这个隐式传参的功能的
`setAttachment 设置的 KV 对，在完成下面一次远程调用会被清空，即多次远程调用要多次设置。`
不过seata后续会保证主动情况自己的key,避免背锅

**Comment by lanok2770** [comment]
> > @slievrly dubbo version 2.7.10
> > ![image](https://user-images.githubusercontent.com/86766571/124245138-45378600-db52-11eb-8fa2-f0d4e9d058b3.png)
> 
> ![image](https://user-images.githubusercontent.com/19943636/124254108-5042e400-db5b-11eb-9308-338184d3cda8.png)
> 在这呢
这个是集群调用的拦截器，正常调用没有走到这里

**Comment by a364176773** [comment]
> > > @slievrly dubbo version 2.7.10
> > > ![image](https://user-images.githubusercontent.com/86766571/124245138-45378600-db52-11eb-8fa2-f0d4e9d058b3.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19943636/124254108-5042e400-db5b-11eb-9308-338184d3cda8.png)
> > 在这呢
> > 这个是集群调用的拦截器，正常调用没有走到这里

请问你的seata test函数是rpc调用进来的吗？

**Comment by lanok2770** [comment]
> > > > @slievrly dubbo version 2.7.10
> > > > ![image](https://user-images.githubusercontent.com/86766571/124245138-45378600-db52-11eb-8fa2-f0d4e9d058b3.png)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/19943636/124254108-5042e400-db5b-11eb-9308-338184d3cda8.png)
> > > 在这呢
> > > 这个是集群调用的拦截器，正常调用没有走到这里
> 
> 请问你的seata test函数是rpc调用进来的吗？

是的

**Comment by a364176773** [comment]
> > > > > @slievrly dubbo version 2.7.10
> > > > > ![image](https://user-images.githubusercontent.com/86766571/124245138-45378600-db52-11eb-8fa2-f0d4e9d058b3.png)
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/19943636/124254108-5042e400-db5b-11eb-9308-338184d3cda8.png)
> > > > 在这呢
> > > > 这个是集群调用的拦截器，正常调用没有走到这里
> > 
> > 
> > 请问你的seata test函数是rpc调用进来的吗？
> 
> 是的

rpc进来的貌似是不生效的，我们接下来测试一下，进行修复，谢谢
