### ISSUE TITLE
on update current_timestamp类型字段导致全局回滚失败

### ISSUE THREAD

**Issue by qq928389526** [seata/seata#3846]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

全局事物先调用下游服务新增，然后调用下游服务修改。之后全局回滚。 针对修改的全局回滚执行回滚语句 update修改成功后，
由于数据库字段修改时间设置成on update current_timestamp，导致字段修改时间自动变了。后续针对新增的回滚比对时发现修改时间和afterimage不一致，导致全局回滚失败。seata可以支持回滚比对镜像的时候不比对某个字段吗
## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by caohdgege** [comment]
client.undo.onlyCareUpdateColumns = false 或者 更新的时候手动更新on update的字段

**Comment by caohdgege** [comment]
跟 #3036 重复了，有需要讨论的可以过去那个issue，这个先关闭。
