### ISSUE TITLE
@GlobalTransaction和@Transaction

### ISSUE THREAD

**Issue by redfish110** [seata/seata#3861]
@GlobalTransaction(rollback = Exception.class)
public void methodA(){
    methodB();
   int a = 3/0;
}

@Transaction(rollback = Exception.class)
public void methodB(){
}

如上代码，A方法(被@GlobalTransaction修饰)调用B方法(被@Transaction修饰)。
B，方法没有抛出异常。但是A方法后续抛出异常，B方法不会回滚。

问：@GlobalTransaction不会回滚被@Transaction修饰的方法吗。

**Comment by slievrly** [comment]
@redfish110 
1.  RootCotext.getXID() make sure global tractional in effect.
2. Does the datasource of method B proxy by DatasourceProxy?

**Comment by gelibo** [comment]
@redfish110 
A方法上不仅要加   @GlobalTransactional(rollbackFor = Exception.class)  也要加   @Transactional(rollbackFor = Exception.class)
这样正常的事务才能传递。
@GlobalTransactional 是分布式事务用的。
@Transactional是本身服务的事务用的。
