### ISSUE TITLE
配置能否通过nacos的一个dataid读取文件形式，而不是把config.txt每条数据作为一个配置

### ISSUE THREAD

**Issue by zxiaozhou** [seata/seata#3871]
## Why you need it?
 配置能否通过nacos的一个dataid读取文件形式，而不是把config.txt每个值作为一个键并且还需要命令批量导入
1.  这个导入进nacos配置数量太多了，管理不是很方便；
2.  直接弄成一个yml,或者一个properties文件更加合理；
3.  这么多条数据，要是想直接在配置中心修改，那简直就是噩梦。如果文件修改，还得运行脚本更新，这也太麻烦了吧。

**Comment by a364176773** [comment]
1.4.2支持

**Comment by zxiaozhou** [comment]
@a364176773 是不是配置中dataId指定nacos的值，，如果是，，我发现无效，，依然还是获取单挑的，，请问下是要删除单挑的吗？？？
