### ISSUE TITLE
数据回滚ip不对应问题

### ISSUE THREAD

**Issue by leelun** [seata/seata#3873]
我电脑的ip为192.168.10.100
但是当回滚的时候出现
i.s.r.d.undo.AbstractUndoLogManager      : xid 192.168.56.1:8091:5071209044670349323 branch 5071209044670349324, undo_log deleted with GlobalFinished
我电脑安装了vm虚拟机，ip为192.168.56.1
但是我在file.conf配置了  default.grouplist = "127.0.0.1:8091"

**Comment by a364176773** [comment]
xid是tc的ip port加雪花算法，跟你client配置无关
