### ISSUE TITLE
store.mode 为redis 支持HA 吗？

### ISSUE THREAD

**Issue by wshgo** [seata/seata#3882]
如题
store.mode 为redis 支持HA 吗？
如果支持 如何配置集群？

**Comment by pangshuqiang** [comment]
其实刚刚接触Seata时，我也在想为什么不直接Redis上推广（假设Redis有持久化并是HA模式），性能是不是应该比数据库好很多，但是其中的原有也没去了解过。

**Comment by a364176773** [comment]
用sentinel，跟db模式一样，多个tc共用一套存储即可ha

**Comment by a364176773** [comment]
> 其实刚刚接触Seata时，我也在想为什么不直接Redis上推广（假设Redis有持久化并是HA模式），性能是不是应该比数据库好很多，但是其中的原有也没去了解过。

Redis做到HA考验用户的部署架构设计,就跟可靠消息最终一致性一样,前提是可靠,但是很多人忽略了可靠二字
