### ISSUE TITLE
seata 1.4.0启动报错no available service found in cluster '{}', please make sure registry config correct and keep your seata server running

### ISSUE THREAD

**Issue by niuzhimin** [seata/seata#3884]
描述:
    springBoot版本:2.2.5
    使用seata1.2.0启动正常
    切换为1.4.0启动报错，配置都一样
         报错信息:  no available service found in cluster '{}', please make sure registry config correct and keep your 
                                                   seata server running

**Comment by SitD4C** [comment]
同遇到这个问题，lz解决了吗，也是1.4.0。照着1.3.0的视频教程写的
