### ISSUE TITLE
Seata AT 性能压测堪忧

### ISSUE THREAD

**Issue by wshgo** [seata/seata#3885]
事务日志存储在DB,
我的服务间调用如下图![image](https://user-images.githubusercontent.com/15864304/126314772-584aa106-6dea-4ca2-a6ba-3b2610dd0eae.png)

业务服务端调用链 Storage Server-->Order Server -->Account Server
如下图是压测结果
机器配置：CPU: i7-1165G7  RAM: 16GB
![image](https://user-images.githubusercontent.com/15864304/126314619-f952f034-b9f9-4043-8490-cdf69c5ca5cf.png)
 
Seata Version: seata-server-1.4.2
TPS:110/s
Seata Mode:AT
Seata transaction log store:DB
操作数据1000条
我的问题是：这个可以优化吗？还是我机器不行。这个官方有压测性能报告？

**Comment by a364176773** [comment]
不写版本号，不写具体压测tps，不写事务模式，不写操作了多少条数据，如何判断

**Comment by wshgo** [comment]
> 不写版本号，不写具体压测tps，不写事务模式，不写操作了多少条数据，如何判断

Seata Version: seata-server-1.4.2
TPS:110/s
Seata Mode:AT
操作数据1000条

**Comment by a364176773** [comment]
> > 不写版本号，不写具体压测tps，不写事务模式，不写操作了多少条数据，如何判断
> 
> Seata Version: seata-server-1.4.2
> TPS:110/s
> Seata Mode:AT
> Seata transaction log store:DB
> 操作数据1000条

数据不正常,我压测过,平均rt100+ms而已
