### ISSUE TITLE
Seata AT 每秒200个并发,出现脏读  一直 Rollback failed

### ISSUE THREAD

**Issue by wshgo** [seata/seata#3888]
Seata Version: seata-server-1.4.2
Seata Mode:AT
每秒200个并发请求
调用链:  扣库存-->下单-->扣款
扣款操作只是针对同一个商品Id,做update 操作
undolog:
{
	"@class": "io.seata.rm.datasource.undo.BranchUndoLog",
	"xid": "172.19.18.113:8091:3576015385001175007",
	"branchId": 3576015385001181330,
	"sqlUndoLogs": ["java.util.ArrayList", [{
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "product",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "product",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": 4,
					"value": 1
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "stock",
					"keyType": "NULL",
					"type": 4,
					"value": 465
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "product",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": 4,
					"value": 1
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "stock",
					"keyType": "NULL",
					"type": 4,
					"value": 463
				}]]
			}]]
		}
	}, {
		"@class": "io.seata.rm.datasource.undo.SQLUndoLog",
		"sqlType": "UPDATE",
		"tableName": "product",
		"beforeImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "product",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": 4,
					"value": 1
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "stock",
					"keyType": "NULL",
					"type": 4,
					"value": 471
				}]]
			}]]
		},
		"afterImage": {
			"@class": "io.seata.rm.datasource.sql.struct.TableRecords",
			"tableName": "product",
			"rows": ["java.util.ArrayList", [{
				"@class": "io.seata.rm.datasource.sql.struct.Row",
				"fields": ["java.util.ArrayList", [{
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "id",
					"keyType": "PrimaryKey",
					"type": 4,
					"value": 1
				}, {
					"@class": "io.seata.rm.datasource.sql.struct.Field",
					"name": "stock",
					"keyType": "NULL",
					"type": 4,
					"value": 469
				}]]
			}]]
		}
	}]]
}
表:
![image](https://user-images.githubusercontent.com/15864304/126448238-17664d4e-5eb5-412c-9c59-0815142a6f4e.png)
log:
无法回滚原因 : Field not equals, name stock, old value 463, new value 471

![image](https://user-images.githubusercontent.com/15864304/126447736-47cc72eb-459b-4daa-ad0e-caf08e165d90.png)
![image](https://user-images.githubusercontent.com/15864304/126447835-fea33293-c5fc-4623-ade9-a62029518fbf.png)

**Comment by a364176773** [comment]
说明事务没有纳入到全局事务管理范畴,保证写函数的入口一定是从globaltransactional注解进入的,如果有什么定时任务是本地事务运行,可能就会脏写正在分布式调用链中的数据
