### ISSUE TITLE
nacos-config.sh support ash shell

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#3892]
## Why you need it?
The current nacos-config.sh only support bash shell, expect to make it support ash either.
If you want to support it, please comment "Please assign it to me" is this issue.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by lvekee** [comment]
Please assign it to me

**Comment by xjlgod** [comment]
Please assign it to me
