### ISSUE TITLE
not found service provider for : io.seata.core.store.DistributedLocker

### ISSUE THREAD

**Issue by slievrly** [seata/seata#3894]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/8758457/126611352-b96680db-a0a8-4b15-8e14-3684f6aecb1f.png)

lockerType=file

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by zhaixuepan** [comment]
<img width="960" alt="a17cb608cc95777ecf134ae830a06e2" src="https://user-images.githubusercontent.com/15258081/127362841-57145e60-eae9-4d2f-bb8d-e0424cbafa8f.png">

**Comment by DerNiGeDer** [comment]
I also have this problem , but  I change the version of seata-serve to solve it ,and your configuration must be right
docker pull seataio/seata-server:1.4.2

**Comment by caohdgege** [comment]
#3487 has fixed
