### ISSUE TITLE
多数据源下 UndoLogManager 接口的batchDeleteUndoLog 执行失败

### ISSUE THREAD

**Issue by lkj7b226** [seata/seata#3896]
项目中使用了多数据源， dataSouce 是动态取的。UndoLogManager 操作日志的的方法undo 使用的代理数据源DataSourceProxy，执行没问题，但是batchDeleteUndoLog 却是直接使用Connection ，无法获取到正确连接。能否修改成DataSourceProxy？

**Comment by a364176773** [comment]
你代理的问题，参考https://github.com/baomidou/dynamic-datasource-spring-boot-starter 进行代理你的数据源
