### ISSUE TITLE
Seata 1.4.2，服务端和客户端日志限制正常回滚，但是数据库的数据没有回滚，undo_log表中也没有数据

### ISSUE THREAD

**Issue by shanafilan** [seata/seata#3913]
依赖如下：
![image](https://user-images.githubusercontent.com/38583248/127202202-9928d268-bc43-45ff-a7c0-efa0497ef7c0.png)
使用的是自动代理
![image](https://user-images.githubusercontent.com/38583248/127202375-3e981383-0a16-4e39-8240-ca1a54bafcdc.png)

想请问下是我数据源代理有问题吗？

**Comment by a364176773** [comment]
Seata常见问题：http://seata.io/zh-cn/docs/overview/faq.html﻿
﻿
Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt﻿
﻿
升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR﻿
﻿
TCC整合教程: http://seata.io/zh-cn/blog/integrate-seata-tcc-mode-with-spring-cloud.html
﻿
文字版教程
﻿
﻿https://mp.weixin.qq.com/s/2KSidJ72YsovpJ94P1aK1g﻿
﻿
tcc+at 整合demo:
https://github.com/wangliang181230/seata-starters-and-demos
﻿
springcloud整合demo:
﻿
﻿https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo

 1.3教程兼容1.4.x
