### ISSUE TITLE
Does the `asyncCommit` method in the `GlobalSession` class have extra operations? 

### ISSUE THREAD

**Issue by tian-qingzhao** [seata/seata#3917]
## Why you need it?
For example, from DefaultCore's commit method, which commits a global transaction.  Then in a class in GlobalSession asyncCommit method calls the `this.changeStatus (GlobalStatus. AsyncCommitting);` here is the real state of change,  But below and call the `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` seemed change state, but didn't see the state changes.  So I feel like I have an extra step.  

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/127449163-028c56c1-09c6-47d8-a175-6487c3701e14.png)
![image](https://user-images.githubusercontent.com/19943636/127449210-aa3169b6-21ba-4022-8c5f-e4c8f7bd5b63.png)

**Comment by tian-qingzhao** [comment]
I mean `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` will eventually be called to `transactionStoreManager.writeSession(LogOperation.GLOBAL_UPDATE, session)` ,Its event type is Update. `this.changeStatus(GlobalStatus.AsyncCommitting);` Will eventually call `transactionStoreManager.writeSession(logOperation, sessionStorable)`,Its event type is also Update,This is equivalent to changing status twice, but the value is the same.

**Comment by a364176773** [comment]
1.4.2 use changestatus
develop use setStatus

**Comment by tian-qingzhao** [comment]
> 1.4.2 use changestatus
> develop use setStatus
> there's no problem like you said

I see. Thank you very much.

**Comment by tian-qingzhao** [comment]
> 1.4.2 use changestatus
> develop use setStatus
> there's no problem like you said

if use changestatus，so `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` is also change database information .
![2222](https://user-images.githubusercontent.com/57293296/127616045-468fc4e3-164e-4fcf-86be-c27e70a5ed06.png)

**Comment by a364176773** [comment]
> > 1.4.2 use changestatus
> > develop use setStatus
> > there's no problem like you said
> 
> if use changestatus，so `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` is also change database information .
> ![2222](https://user-images.githubusercontent.com/57293296/127616045-468fc4e3-164e-4fcf-86be-c27e70a5ed06.png)

you could say that.

**Comment by tian-qingzhao** [comment]
> > > 1.4.2 use changestatus
> > > develop use setStatus
> > > there's no problem like you said
> > 
> > 
> > if use changestatus，so `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` is also change database information .
> > ![2222](https://user-images.githubusercontent.com/57293296/127616045-468fc4e3-164e-4fcf-86be-c27e70a5ed06.png)
> 
> you could say that.
So the second line changes the state and doesn't change. What does it do?

**Comment by a364176773** [comment]
> > > > 1.4.2 use changestatus
> > > > develop use setStatus
> > > > there's no problem like you said
> > > 
> > > 
> > > if use changestatus，so `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` is also change database information .
> > > ![2222](https://user-images.githubusercontent.com/57293296/127616045-468fc4e3-164e-4fcf-86be-c27e70a5ed06.png)
> > 
> > 
> > you could say that.
> > So the second line changes the state and doesn't change. What does it do?

so the latest code has been modified

**Comment by tian-qingzhao** [comment]
> > > > > 1.4.2 use changestatus
> > > > > develop use setStatus
> > > > > there's no problem like you said
> > > > 
> > > > 
> > > > if use changestatus，so `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` is also change database information .
> > > > ![2222](https://user-images.githubusercontent.com/57293296/127616045-468fc4e3-164e-4fcf-86be-c27e70a5ed06.png)
> > > 
> > > 
> > > you could say that.
> > > So the second line changes the state and doesn't change. What does it do?
> 
> so the latest code has been modified

Ok, thank you very much!

**Comment by a364176773** [comment]
> > > > > > 1.4.2 use changestatus
> > > > > > develop use setStatus
> > > > > > there's no problem like you said
> > > > > 
> > > > > 
> > > > > if use changestatus，so `SessionHolder.getAsyncCommittingSessionManager().addGlobalSession(this);` is also change database information .
> > > > > ![2222](https://user-images.githubusercontent.com/57293296/127616045-468fc4e3-164e-4fcf-86be-c27e70a5ed06.png)
> > > > 
> > > > 
> > > > you could say that.
> > > > So the second line changes the state and doesn't change. What does it do?
> > 
> > 
> > so the latest code has been modified
> 
> Ok, thank you very much!

you are welcome, if you have any thoughts or suggestions in the future, please continue to communicate
