### ISSUE TITLE
seata-server.bat无法启动

### ISSUE THREAD

**Issue by tiankazma** [seata/seata#3920]
seata 1.4.0 版本, 本地无法启动
报错如下:
Unrecognized VM option 'CMSParallelRemarkEnabled'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by a364176773** [comment]
请使用jdk8

**Comment by tanzzj** [comment]
这个是因为你使用了高版本的jdk导致。高版本的jdk取消了cms处理器，转而采用了zgc代替他。
解决方案有两个，选其中之一便可：
1、降级jdk版本
2、在seata的启动脚本中删除cms的jdk命令
