### ISSUE TITLE
集成TKMyabtis insertSelective 获取自增主键报错

### ISSUE THREAD

**Issue by liumouNo1** [seata/seata#3923]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata1.4.2集成时，使用tkmyabtis的 insertSelective方法在获取自增主键 AbstractStatementProxy的getGeneratedKeys()时报了Fail to get auto-generated keys, use 'SELECT LAST_INSERT_ID()' instead. Be cautious, statement could be polluted. Recommend you set the statement to return generated keys 错误。像关闭掉getGeneratedKeys的缓存我也试了，但没有效果，打断点时执行完insertSelective方法后数据正确的插入到了数据库中，但返回的result = -1，jdk 1.8 mysql 是8
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by liumouNo1** [comment]
如果不用@GlobalTractional注解 就不会发生该错误。 目前的调用时 A方法标注了@GlobalTractional 里面调用了B B标注了@Transactional B里面调用了C C 方法没有表中事务，C里面调用了insertSelective方法

**Comment by a364176773** [comment]
Q: 10.为什么mybatis没有返回自增ID?
A: 方案1.需要修改mybatis的配置: 在@Options(useGeneratedKeys = true, keyProperty = "id")或者在xml中指定useGeneratedKeys 和 keyProperty属性
方案2.删除undo_log表的id字段

**Comment by a364176773** [comment]
http://seata.io/zh-cn/docs/overview/faq.html

**Comment by liumouNo1** [comment]
> Q: 10.为什么mybatis没有返回自增ID?
> A: 方案1.需要修改mybatis的配置: 在@options(useGeneratedKeys = true, keyProperty = "id")或者在xml中指定useGeneratedKeys 和 keyProperty属性
> 方案2.删除undo_log表的id字段

好像我这个问题和这个没有关系，虽然getGeneratedKeys报了Fail to get auto-generated keys, use 'SELECT LAST_INSERT_ID()' instead. Be cautious, statement could be polluted. Recommend you set the statement to return generated keys 这个错误，但是数据库里数据是正常插入的，主键也返回到了实体类中，但是导致insertSelective方法返回的值是-1。
