### ISSUE TITLE
k8s 部署seata 开发环境. 注册到nacos的ip是否可以自定义?

### ISSUE THREAD

**Issue by siaron** [seata/seata#3925]
## Why you need it?
在k8s部署seata的开发环境. nacos 2.0.2 注册中心. 本地开发通过kubefwd将seata server代理出来. 供本地访问.注册时不能使用pod 的ip需要使用k8s service的name.
1. 如何使用自定义的ip来代替seata的默认获取服务器的ip选项. 

## How it could be?
有没有配置的选项
```
    nacos {
        ip = "svc-seata-server"
  }
```

## Other related information
1. k8s 服务间通信使用serviceName通信.

**Comment by a364176773** [comment]
configmap 环境注入 SEATA_IP

**Comment by siaron** [comment]
这个只能是一个ip格式吗? 
```
  - name: SEATA_IP
     value: "seata-server"
```
我只想用"seata-server"作为服务的调用. 现在又会将`seata-server` 这个主机解析出来ip再去注册.

**Comment by siaron** [comment]
@a364176773 有什么方式吗?

**Comment by zxiaozhou** [comment]
@a364176773 在容器中SEATA_IP，，根本不生效

**Comment by a364176773** [comment]
> @a364176773 在容器中SEATA_IP，，根本不生效

1.5上已修复
