### ISSUE TITLE
集成tkMybatis insertSelective方法返回-1

### ISSUE THREAD

**Issue by liumouNo1** [seata/seata#3928]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
#3923 也是我提的，但被关闭了 给予的帮助和我的问题没有什么联系，可能是我描述的有问题。seata用的1.4，当@GlobalTransactional注解下调用了TKmybatis的insertSelective方法，导致了返回的结果是-1，并且报了一个错误在获取自增主键 AbstractStatementProxy的getGeneratedKeys()时报了Fail to get auto-generated keys, use 'SELECT LAST_INSERT_ID()' instead. Be cautious, statement could be polluted. Recommend you set the statement to return generated keys，但我不知道这个错误和这个问题是否有关，因为虽然返回了-1,但数据库里的数据是正常插入的，且实体类里自增主键也正确回显了。如果用普通的@Transactional注解就是正常返回1。我想问一下因为使用了@GlobalTransactional导致insertSelective返回值为-1是BUG么，有办法解决么？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by caohdgege** [comment]
无法复现, 请提供更多的信息. 包括但不限于各个版本信息, 复现的demo, 测试的库表信息等.

**Comment by liumouNo1** [comment]
抱歉，找到问题所在了，是因为实体类主键上标注的主键生成策略是@GeneratedValue(strategy = GenerationType.IDENTITY)
改为@GeneratedValue(generator = "JDBC")就没问题了
