### ISSUE TITLE
@GlobalTransactional不生效怎么办

### ISSUE THREAD

**Issue by WeiAhongun** [seata/seata#3929]
打了断点后global_table表中的数据是存在的
![image](https://user-images.githubusercontent.com/76947917/128286359-c778028e-6bad-42e7-b04d-8ae368da2d90.png)
日志打印回滚成功
![image](https://user-images.githubusercontent.com/76947917/128286456-f467346b-0b0f-4b4f-84fd-fc653cc53e3b.png)
但实际上数据库的数据还是插入，并没有回滚，是不是少配置了什么东西
下面是我的配置，配错了吗
![image](https://user-images.githubusercontent.com/76947917/128286752-4ff0524d-8973-4659-8fc6-7b5466e2147f.png)
![image](https://user-images.githubusercontent.com/76947917/128286765-93d0f67f-06f6-42ea-b233-9dadf73296c8.png)

**Comment by a364176773** [comment]
Seata常见问题：http://seata.io/zh-cn/docs/overview/faq.html

Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt

升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR

TCC整合教程: http://seata.io/zh-cn/blog/integrate-seata-tcc-mode-with-spring-cloud.html

文字版教程

https://mp.weixin.qq.com/s/2KSidJ72YsovpJ94P1aK1g

tcc+at 整合demo:
https://github.com/wangliang181230/seata-starters-and-demos

springcloud整合demo:

https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo 
（上述demo内附1.3整合文字版）
