### ISSUE TITLE
seata 的 xa 模式是否解决了资源悬挂问题？

### ISSUE THREAD

**Issue by wangshangming** [seata/seata#3938]
我理解 xa 模式下，也可能会出现先 `xa rollback xid` 再 `xa prepare xid`。想请教下，seata 是怎么处理的？

**Comment by a364176773** [comment]
首先明确一下，在mysql中一个connection开启xa事务的时候，比如xid为1234，此时一个下发回滚的指令到达client端，此时处于隔离情况，这个回滚的指令使用的connection如果不是开启xa事务的conn，就会rollback失败抛出XAER_NOTA: Unknown XID
如果是使用开启xa事务的conn，那么会抛出XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state，除非事务已经end
那么我们按seata的xa流程来分析 start xa事务前，先进行registy，先拿到branchid，再进行xa start，那么就有了你的疑问，悬挂问题
好，我们看下二阶段是如何下发的，首先tc会找到registy时的client的连接，去找到start的这个事务client，此时拿到的是同一个xaconnection，此时有3个结果
1.rollback 失败，因为xa事务还未end
2.rollback 成功，成功那么说明业务线程进行了end，那么此时说明业务线程的prepare会失败，因为xa事务已经回滚了，资源也就都释放了，此时会抛出 XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state的错误
3.rollback 成功，业务prepare也成功，说明下发之类的时候业务线程已经完成了对xa事务的prepare，所以这个结果没任何问题
所以资源悬挂的问题xa自身特性+tc针对发起事务的client进行rollback操作，就解决了资源悬挂的问题
如果是prepare之前client宕机了，那么这个xa事务资源直接就会释放了，无需rollback都不会有问题，如果prepare之后，那么其他的client就能找到这个xa，所以tc找不到发起的client连接，就会找其他的节点回滚，此时由于已经prepare了，rollback就是一个正常操作了

**Comment by wangshangming** [comment]
明白了，感谢回答

**Comment by a364176773** [comment]
之前我看错了代码，client的连接存储是在end和prepare之后进行的，所以存在end之前如果下发就会出现找不到xid无法回滚成功
