### ISSUE TITLE
seata 是否能够支持通过API的形式获取全局事务的链路信息？

### ISSUE THREAD

**Issue by Accelerator96** [seata/seata#3941]
## Why you need it?
想通过页面来展示 seata中事务的全部链路(db中的数据

## How it could be?
可以在第三方的平台中集成分布式事务的链路信息

**Comment by JaredTan95** [comment]
https://github.com/seata/seata/issues/3875
https://github.com/seata/seata/issues/3876
https://github.com/seata/seata/issues/3877
https://github.com/seata/seata/issues/3878
