### ISSUE TITLE
update 全局事务表数据精度问题

### ISSUE THREAD

**Issue by BillBillLi** [seata/seata#3957]
在io.seata.server.storage.db.store.LogStoreDataBaseDAO#updateGlobalTransactionDO更新全局事务表的时候，使用的sql是这句：update  #global_table#    set status = ?,       gmt_modified = now() where xid = ?
在这句中，事务没结束的时候，status是1，而当status没变，并且更新和插入隔的时间很短的情况下，由于now()只是精确到了秒的情况下，此时now()获取到的数据和之前插入全局事务表的gmt_modified是相同的（因为精度只是到秒而已），此时，代码中ps.executeUpdate() > 0 就会是false，这样就会抛出异常从而导致全局事务失败

**Comment by BillBillLi** [comment]
实际上此时事务是个正常的状态

**Comment by a364176773** [comment]
根本原因是seata1.4.2时连续变更状态了2次造成此问题，目前已修复，是否要加精度需要另外商讨，欢迎留言交流

**Comment by caohdgege** [comment]
ref #3626
