### ISSUE TITLE
seata支持跨库请求吗 ？比如：A服务调用B服务时，A服务数据库是oracle，B服务数据库是mysql，此时事务ok吗？

### ISSUE THREAD

**Issue by MrPassionFruit** [seata/seata#3958]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
没问题

**Comment by MrPassionFruit** [comment]
好的，谢谢
