### ISSUE TITLE
执行insert into select时报异常

### ISSUE THREAD

**Issue by zdtjss** [seata/seata#3964]
从日志看数据库层insert into select执行成功，报错的堆栈中无数据库驱动层抛出的异常信息。
数据库版本MySQL5.7
数据库驱动版本8.0.22
seata客户端版本1.3.0或1.4.2
seata服务端版本1.3.0
观察seata客户端源码（BaseInsertExecutor），报错位置如下最后一个if处判断为false（!insertRows.isEmpty()为true），导致无法为pkValuesMap赋值。
if (statementProxy instanceof PreparedStatementProxy) {
            PreparedStatementProxy preparedStatementProxy = (PreparedStatementProxy) statementProxy;

            List<List<Object>> insertRows = recognizer.getInsertRows(pkIndexMap.values());
            if (insertRows != null && !insertRows.isEmpty()) {

**Comment by jsbxyyx** [comment]
不支持 insert into select

**Comment by zdtjss** [comment]
> 不支持 insert into select

是不能被支持，还是暂不支持

**Comment by jsbxyyx** [comment]
@zdtjss 暂时不支持，如果你愿意，可以提交一个PR，非常感谢

**Comment by caohdgege** [comment]
same with #3965 , 后续有进展在那边继续
