### ISSUE TITLE
oracle 插入数据如果超过1000长度，数据插入不进去

### ISSUE THREAD

**Issue by yjyi** [seata/seata#3973]
seata版本：1.4.2
oracle版本：12c
数据表当中有个字段设计为VARCHAR2, 长度为4000，
如果去掉seata事务，则可以插入长度为4000的字符，如果加上，长度大于1000，那么字段为空，小于1000可以正常插入，无异常错误，
如果将数据类型改成CLOB，那么会报如下错误

![CF9CCD0B-707C-4f02-B95D-0426483DEF86](https://user-images.githubusercontent.com/9957850/130383921-a5aea14d-59e4-446d-ad21-e7c7200718de.png)

**Comment by a364176773** [comment]
@jsbxyyx

**Comment by jsbxyyx** [comment]
fix later

**Comment by caohdgege** [comment]
可以提供一份完整堆栈吗？

**Comment by yjyi** [comment]
![lALPD26eQBujcu3NAg_NBHs_1147_527](https://user-images.githubusercontent.com/9957850/130717180-834491dd-191e-487b-bdd2-90198fd1a8f0.png)
这是接着上面报错的截图，不过这是另外一个问题，主要是字段超过1000插入不进去，不知道这2个是不是同一个问题@ caohdgege

**Comment by yjyi** [comment]
项目要上线，卡在这个问题上了，看看能不能尽快解决，需要什么支持，我都及时响应，谢谢了@caohdgege

**Comment by caohdgege** [comment]
表结构/字段类型方便贴一下？字段名你可以改一下，数据类型，长度保持一致即可；还有Java对应的数据类型；对应的SQL方便也可以贴一下。

**Comment by yjyi** [comment]
表结构很简单，就是一张表test,   字段ID, VARCHAR2, 64,  字段TEST, VARCHAR2(或者CLOB), 4000, JAVA都是String，
==>  Preparing: insert into ZT_TEST2021813(ID_,TEST) values (?,?,?,?,?,?,?,?) 
==> Parameters: 1430362753712893954(String), YM4BWY5IKL-eyJsaWNDIyLTA4LTEwIiwiZXh0ZW5kZWQiOmZhbHNlfSx7ImNvZGUiOiJETSIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjpmYWxzZX0seyJjb2RlIjoiUlNGIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOnRydWV9LHsiY29kZSI6IlBDIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOmZhbHNlfSx7ImNvZGUiOiJSQyIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjpmYWxzZX0seyJjb2RlIjoiQ0wiLCJwYWlkVXBUbyI6IjIwMjItMDgtMTAiLCJleHRlbmRlZCI6ZmFsc2V9LHsiY29kZSI6IldTIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOmZhbHNlfSx7ImNvZGUiOiJSRCIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjpmYWxzZX0seyJjb2RlIjoiUlMwIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOmZhbHNlfSx7ImNvZGUiOiJSTSIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjpmYWxzZX0seyJjb2RlIjoiQUMiLCJwYWlkVXBUbyI6IjIwMjItMDgtMTAiLCJleHRlbmRlZCI6ZmFsc2V9LHsiY29kZSI6IlJTViIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjp0cnVlfSx7ImNvZGUiOiJEQyIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjpmYWxzZX0seyJjb2RlIjoiUlNVIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOmZhbHNlfSx7ImNvZGUiOiJEUCIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjp0cnVlfSx7ImNvZGUiOiJQREIiLCJwYWlkVXBUbyI6IjIwMjItMDgtMTAiLCJleHRlbmRlZCI6dHJ1ZX0seyJjb2RlIjoiUFdTIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOnRydWV9LHsiY29kZSI6IlBTSSIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjp0cnVlfSx7ImNvZGUiOiJQQ1dNUCIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjp0cnVlfSx7ImNvZGUiOiJQUFMiLCJwYWlkVXBUbyI6IjIwMjItMDgtMTAiLCJleHRlbmRlZCI6dHJ1ZX0seyJjb2RlIjoiUEdPIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOnRydWV9LHsiY29kZSI6IlBQQyIsInBhaWRVcFRvIjoiMjAyMi0wOC0xMCIsImV4dGVuZGVkIjp0cnVlfSx7ImNvZGUiOiJQUkIiLCJwYWlkVXBUbyI6IjIwMjItMDgtMTAiLCJleHRlbmRlZCI6dHJ1ZX0seyJjb2RlIjoiUFNXIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOnRydWV9LHsiY29kZSI6IlJTIiwicGFpZFVwVG8iOiIyMDIyLTA4LTEwIiwiZXh0ZW5kZWQiOnRydWV9XSwibWV0YWRhdGEiOiIwMTIwMjEwODExRVBKQTAwMDAwOSIsImhhc2giOiIyNTcwNTI2NS8wOjQ4MzAwMjEzOCIsImdyYWNlUGVyaW9kRGF5cyI6MCwiYXV0b1Byb2xvbmdhdGVkIjpmYWxzZSwiaXNBdXRvUHJvbG9uZ2F0ZWQiOmZhbHNlfQ==-cj2bMGKFLLyaQnq9kulRVEyeCs2K1NO1KLMPbnm48ZNmcIr9KjsMu/TcZdf/s217Jy1+aRf3twtURbOSNf4Y4rEUr7y6sckafzwT+oRf023rc2/obObpEP+GoE8NjskcKtV2UYWCTwcCJ4sLtdImiWyOB8rJV2aW16iu++5OJ2G7Z4y0YJ5+DNdKQyPsiO+5+uzqYmJUP8CiN9tebe7MUbZ3Va/S2xiRZwMHDWRqkxbM54E01Ma4jTEfHYxy2wIH7R4gcZYZO9fX7b5n3nPLK0Vhq6vWMl2me2Waqlkb2vC1z7WNU/By6wns5MoZoxX80FTOhn8n7Vq/YJxko0XZSA==-MIIETDCCAjSgAwIBAgIBDTANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDDA1KZXRQcm9maWxlIENBMB4XDTIwMTAxOTA5MDU1M1oXDTIyMTAyMTA5MDU1M1owHzEdMBsGA1UEAwwUcHJvZDJ5LWZyb20tMjAyMDEwMTkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCP4uk4SlVdA5nuA3DQC+NsEnZS9npFnO0zrmMWcz1++q2UWJNuGTh0rwi+3fUJIArfvVh7gNtIp93rxjtrQAuf4/Fa6sySp4c32MeFACfC0q+oUoWebhOIaYTYUxm4LAZ355vzt8YeDPmvWKxA81udqEk4gU9NNAOz1Um5/8LyR8SGsSc4EDBRSjcMWMwMkYSauGqGcEUK8WhfplsyF61lKSOFA6VmfUmeDK15rUWWLbOMKgn2cxFA98A+s74T9Oo96CU7rp/umDXvhnyhAXSukw/qCGOVhwKR8B6aeDtoBWQgjnvMtPgOUPRTPkPGbwPwwDkvAHYiuKJ7Bd2wH7rAgMBAAGjgZkwgZYwCQYDVR0TBAIwADAdBgNVHQ4EFgQUJNoRIpb1hUHAk0foMSNM9MCEAv8wSAYDVR0jBEEwP4AUo562SGdCEjZBvW3gubSgUouX8bOhHKQaMBgxFjAUBgNVBAMMDUpldFByb2ZpbGUgQ0GCCQDSbLGDsoN54TATBgNVHSUEDDAKBggrBgEFBQcDATALBgNVHQ8EBAMCBaAwDQYJKoZIhvcNAQELBQADggIBAB2J1ysRudbkqmkUFK8xqhiZaYPd30TlmCmSAaGJ0eBpvkVeqA2jGYhAQRqFiAlFC63JKvWvRZO1iRuWCEfUMkdqQ9VQPXziE/BlsOIgrL6RlJfuFcEZ8TK3syIfIGQZNCxYhLLUuet2HE6LJYPQ5c0jH4kDooRpcVZ4rBxNwddpctUO2te9UU5/FjhioZQsPvd92qOTsV+8Cyl2fvNhNKD1Uu9ff5AkVIQn4JU23ozdB/R5oUlebwaTE6WZNBs+TA/qPj+5/wi9NH71WRB0hqUoLI2AKKyiPw++FtN4Su1vsdDlrAzDj9ILjpjJKA1ImuVcG329/WTYIKysZ1CWK3zATg9BeCUPAV1pQy8ToXOq+RSYen6winZ2OO93eyHv2Iw5kbn1dqfBw1BuTE29V2FJKicJSu8iEOpfoafwJISXmz1wnnWL3V/0NxTulfWsXugOoLfv0ZIBP1xH9kmf22jjQ2JiHhQZP7ZDsreRrOeIQ/c4yR8IQvMLfC0WKQqrHu5ZzXTH4NO3CwGWSlTY74kE91zXB5mwWAx1jig+UXYc2w4RkVhy0//lOmVya/PEepuuTTI4+UJwC7qbVlh5zfhj8oTNUXgN0AOc+Q0/WFPl1aw5VV/VrO8FCoB15lFVlpKaQ1Yh+DVU8ke+rt9Th0BCHXe0uZOEmH0nOnH/0onD(String)
<==    Updates: 1
这是业务日志，TEST字段是VARCHAR2的情况，数据TEST字段为空，如果TEST字段是CLOB类型，那么就报上面的错误@caohdgege

**Comment by jsbxyyx** [comment]
@yjyi can you provide create table sql script

**Comment by caohdgege** [comment]
方便加一下群（最好是钉钉群）？
![image](https://user-images.githubusercontent.com/22959373/130719653-7e891b91-5299-4d34-8830-d1a40473e54a.png)

**Comment by yjyi** [comment]
已经加群了，create table test { "ID_" varchar2(64 BYTE) NOT NULL,  "TEST" CLOB visible}@jsbxyyx  @caohdgege

**Comment by caohdgege** [comment]
1. 可否发一下对应的Oracle驱动？
2. 你是在原有服务上集成的？还是新的服务？如果是新的服务，是否方便提供一个完整的复现Demo？

**Comment by yjyi** [comment]
原有服务集成使用的，@caohdgege
驱动
[ojdbc7.zip](https://github.com/seata/seata/files/7044192/ojdbc7.zip)

**Comment by jsbxyyx** [comment]
加timeout和上面的异常没有关系
