### ISSUE TITLE
这是个书写错误么?

### ISSUE THREAD

**Issue by 531411211** [seata/seata#3983]
在官方文档的常见问题中4中,提到的这个注解@GlobalTransaction我并没有找到,我猜想应该是说的这个@GlobalTransactional吧?
![image](https://user-images.githubusercontent.com/20436008/131168541-53e942e1-f82f-48f6-8297-65976739343f.png)

常见问题连接:https://seata.io/zh-cn/docs/overview/faq.html

**Comment by slievrly** [comment]
@531411211 it's a typo, you can submit a PR to fix it.

**Comment by xingfudeshi** [comment]
Fixed
