### ISSUE TITLE
SeataDataSourceAutoConfiguration condition has been mismatched

### ISSUE THREAD

**Issue by hyfsy** [seata/seata#3986]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I imported the v1.4.2 **seata-spring-boot-starter** package, `@EnableAutoDataSourceProxy` annotation are not used, I want `SeataDataSourceAutoConfiguration` can be configured automatically, but the `@ConditionalOnBean(DataSource.class)` annotations on the `SeataDataSourceAutoConfiguration` class has been mismatched.

### Ⅱ. Describe what happened
I'm using `HikariDataSource`, I find hikari bean is also a conditional bean and after this match.

### Ⅲ. Describe what you expected to happen
I hope add an `@AutoConfigureAfter(DataSourceAutoConfiguration.class)` annotation to this class.

**Comment by zcj772393532** [comment]
I have the same problem,when i delete @EnableAutoDataSourceProxy,seata can't rollback; when i add @EnableAutoDataSourceProxy seata can't  be disabled.
I have a demo,https://gitee.com/zhouacai/seata-eureka-feign-jpa.

**Comment by a364176773** [comment]
> I have the same problem,when i delete @EnableAutoDataSourceProxy,seata can't rollback; when i add @EnableAutoDataSourceProxy seata can't be disabled.
> I have a demo,https://gitee.com/zhouacai/seata-eureka-feign-jpa.
seata-spring-boot-starter @EnableAutoDataSourceProxy 无效，starter依赖会自动代理，如果需要关闭显示在properties上写上seata.enable=false

**Comment by zcj772393532** [comment]
不使用@EnableAutoDataSourceProxy，不会进入SeataDataSourceAutoConfiguration，也不会成功回滚

**Comment by a364176773** [comment]
> 不使用@EnableAutoDataSourceProxy，不会进入SeataDataSourceAutoConfiguration，也不会成功回滚

看依赖的，自己看官方demo springboot的有几个用了这个注解

**Comment by bearxsh** [comment]
我用的也是Hikari连接池，spingboot集成seata-spring-boot-starter。1.4.1版本可以正常自动数据源，之后更高的版本无法自动代理，必须使用@EnableAutoDataSourceProxy注解才行。debug后发现`SeataDataSourceAutoConfiguration`类的注解`@ConditionalOnBean(DataSource.class)`不生效，这块代码是1.4.2加的。

**Comment by bearxsh** [comment]
原因：`spring-boot-autoconfigure`自动配置`Hikari连接池`的操作发生在了`seata-spring-boot-starter`自动配置`SeataDataSourceAutoConfiguration`的操作的后面，导致`ConditionalOnBean(DataSource.class)`注解失效。

解决办法：`SeataDataSourceAutoConfiguration`配置类增加`@AutoConfigureOrder(Ordered.LOWEST_PRECEDENCE)`注解，调整顺序，确保`SeataDataSourceAutoConfiguration`类的配置在最后执行。

另一种方法是：增加注解`@AutoConfigureAfter({DataSource.class})`并删除掉`ConditionalOnBean(DataSource.class)`注解。
