### ISSUE TITLE
all_cons_columns查出的主键名和all_indexes中的索引名字不一致导致事物异常

### ISSUE THREAD

**Issue by Musknine** [seata/seata#3987]
### Ⅰ. Issue Description
事物启动异常

### Ⅱ. Describe what happened
![1630296053502_1630294964657_8FA84DE8-EA11-4fd3-979B-863ED99F4833](https://user-images.githubusercontent.com/89766728/131295441-abea5cfd-4e4d-40d9-a795-979b1093af22.png)
如图：构造tablemeta信息时，通过两个sql查询表的相关索引信息，在图中1的位置，通过查询all_indexes取得所有的索引，
[在图中2，3位置通过查询all_cons_columns设置主键，但是由于all_indexes查出来的信息不包含all_cons_columns查出来的信息，就导致没有执行到第3步。
查询数据库的索引信息如下图：
![1630295961095_7FB4AC8F-8B4B-494e-A709-5AAABCC91D4D](https://user-images.githubusercontent.com/89766728/131297259-928d5c42-db52-4548-83c0-36a69dfbcd2b.png)
![1630295961211_9623A18E-26E8-4a98-818D-349D138C2BDA](https://user-images.githubusercontent.com/89766728/131297274-7b319744-0249-4fd6-a29d-9d78bffac8ee.png)
查询的sql是根据debug整理出来的：
select null as table_cat,
       owner as table_schem,
       table_name,
       0 as NON_UNIQUE,
       null as index_qualifier,
       null as index_name, 0 as type,
       0 as ordinal_position, null as column_name,
       null as asc_or_desc,
       num_rows as cardinality,
       blocks as pages,
       null as filter_condition
from all_tables
where table_name = '表名'
  and owner = '数据库名'
union
select null as table_cat,
       i.owner as table_schem,
       i.table_name,
       decode (i.uniqueness, 'UNIQUE', 0, 1),
       null as index_qualifier,
       i.index_name,
       1 as type,
       c.column_position as ordinal_position,
       c.column_name,
       null as asc_or_desc,
       i.distinct_keys as cardinality,
       i.leaf_blocks as pages,
       null as filter_condition
from all_indexes i, all_ind_columns c
where i.table_name = '表名'
  and i.owner = '数据库名'
  and i.index_name = c.index_name
  and i.table_owner = c.table_owner
  and i.table_name = c.table_name
  and i.owner = c.index_owner
order by non_unique, type, index_name, ordinal_position
;
SELECT NULL AS table_cat,
       c.owner AS table_schem,
       c.table_name,
       c.column_name,
       c.position AS key_seq,
       c.constraint_name AS pk_name
FROM all_cons_columns c, all_constraints k
WHERE k.constraint_type = 'P'
  AND k.table_name = '表名'
  AND k.owner like '数据库名' escape '/'
  AND k.constraint_name = c.constraint_name 
  AND k.table_name = c.table_name 
  AND k.owner = c.owner 
ORDER BY column_name;

Just paste your stack trace here!
io.seata.common.exception.NotSupportYetException: ACT_RU_EXECUTION needs to contain the primary key.
	at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyMap(TableMeta.java:126)
	at io.seata.rm.datasource.sql.struct.TableMeta.getPrimaryKeyOnlyName(TableMeta.java:140)

### Ⅴ. Anything else we need to know?
驱动的maven坐标：
<dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>12.2.0.1</version>
 </dependency>

基中一个表的语句（由于表是历史表，最原始的开发建表语句，中间有过什么操作的相关记录都遗失了，并且数据库有一批表有这种情况）：
-- Create table
create table ACT_RU_EXECUTION
(
  id_               NVARCHAR2(64) not null,
  rev_              NUMBER,
  proc_inst_id_     NVARCHAR2(64),
  business_key_     NVARCHAR2(255),
  parent_id_        NVARCHAR2(64),
  proc_def_id_      NVARCHAR2(64),
  super_exec_       NVARCHAR2(64),
  act_id_           NVARCHAR2(255),
  is_active_        NUMBER(1),
  is_concurrent_    NUMBER(1),
  is_scope_         NUMBER(1),
  is_event_scope_   NUMBER(1),
  suspension_state_ NUMBER,
  cached_ent_state_ NUMBER,
  tenant_id_        NVARCHAR2(255) default '',
  name_             NVARCHAR2(255),
  lock_time_        TIMESTAMP(6)
)
tablespace DB_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 3
    next 8
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate indexes 
create index ACT_IDX_EXEC_BUSKEY on ACT_RU_EXECUTION (BUSINESS_KEY_)
  tablespace DB_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 5M
    next 1M
    minextents 1
    maxextents unlimited
  );
create index ACT_IDX_EXE_PARENT on ACT_RU_EXECUTION (PARENT_ID_)
  tablespace DB_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
create index ACT_IDX_EXE_PROCDEF on ACT_RU_EXECUTION (PROC_DEF_ID_)
  tablespace DB_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 6M
    next 1M
    minextents 1
    maxextents unlimited
  );
create index ACT_IDX_EXE_PROCINST on ACT_RU_EXECUTION (PROC_INST_ID_)
  tablespace DB_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 5M
    next 1M
    minextents 1
    maxextents unlimited
  );
create index ACT_IDX_EXE_SUPER on ACT_RU_EXECUTION (SUPER_EXEC_)
  tablespace DB_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
create unique index SYS_C0012210 on ACT_RU_EXECUTION (ID_)
  tablespace DB_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 5M
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table ACT_RU_EXECUTION
  add primary key (ID_);
-- Create/Recreate check constraints 
alter table ACT_RU_EXECUTION
  add check (IS_EVENT_SCOPE_ IN (1,0));
alter table ACT_RU_EXECUTION
  add check (IS_SCOPE_ IN (1,0));
alter table ACT_RU_EXECUTION
  add check (IS_CONCURRENT_ IN (1,0));
alter table ACT_RU_EXECUTION
  add check (IS_ACTIVE_ IN (1,0));

### Ⅵ. Environment:

- JDK version :1.8
- seata1.4.2
- spring cloud Hoxton.SR12
- spring boot 2.3.12.RELEASE
- oracle 12.2.0.1.0
- jdbc driver ojdbc8 12.2.0.1

**Comment by a364176773** [comment]
@jsbxyyx @l81893521 一起看看
