### ISSUE TITLE
服务本身职责只是RM  能否只初始化RMClient 不初始化TMClient 

### ISSUE THREAD

**Issue by Dawnxzc** [seata/seata#3989]
由于公司的服务分层，公司大概只有10%的服务是承担TM角色的，大部分服务都不需要初始化TM，只担任RM角色，能否添加配置达到服务启动时只初始化RMClient / TMClient

**Comment by a364176773** [comment]
rm是否有方法上加了globaltransactional注解?

**Comment by objcoding** [comment]
可以看下这篇文章的分析：
https://seata.io/zh-cn/blog/seata-at-mode-start-rm-tm.html

**Comment by Dawnxzc** [comment]
已解决

**Comment by Dawnxzc** [comment]
> rm是否有方法上加了globaltransactional注解?

我看了代码io.seata.spring.annotation.GlobalTransactionScanner#initClient 并做了调试，有没有加@GlobalTransactional注解都会执行TMClient.init()

**Comment by Dawnxzc** [comment]
> 可以看下这篇文章的分析：
> https://seata.io/zh-cn/blog/seata-at-mode-start-rm-tm.html

看了现在的代码，您的pr是没有被合并的。
您的说法 “Seata后续优化需要考虑 当参与方出现异常时，是否可以直接由参与方的 TM client 发起全局回滚？”   如果真的考虑这样优化，影响还是比较大的

**Comment by Dawnxzc** [comment]
> 可以看下这篇文章的分析：
> https://seata.io/zh-cn/blog/seata-at-mode-start-rm-tm.html

看了现在的代码，您的pr是没有被合并的。
您的说法 “Seata后续优化需要考虑 当参与方出现异常时，是否可以直接由参与方的 TM client 发起全局回滚？”   如果真的考虑这样优化，影响还是比较大的

**Comment by a364176773** [comment]
> > 可以看下这篇文章的分析：
> > https://seata.io/zh-cn/blog/seata-at-mode-start-rm-tm.html
> 
> 看了现在的代码，您的pr是没有被合并的。
> 您的说法 “Seata后续优化需要考虑 当参与方出现异常时，是否可以直接由参与方的 TM client 发起全局回滚？” 如果真的考虑这样优化，影响还是比较大的

参与方回滚的风险很大，因为tm那边可能不知道，如果出现用户编码上的bug，会导致后续的调用抛出not found xid的异常，至于为什么tm跟rm很大程度是一起，个人觉得，1.资源隔离 2.rm自身的单机事务也需要开启globaltransational来保证隔离性，否者将有可能脏写正在进行分布式事务中的数据 3.规范性，rm是tm，tm是tm
至于rm和tm共用某些功能，比如同个地址的channel完全可共享之类的，正在考虑

**Comment by Dawnxzc** [comment]
> > > 可以看下这篇文章的分析：
> > > https://seata.io/zh-cn/blog/seata-at-mode-start-rm-tm.html
> > 
> > 
> > 看了现在的代码，您的pr是没有被合并的。
> > 您的说法 “Seata后续优化需要考虑 当参与方出现异常时，是否可以直接由参与方的 TM client 发起全局回滚？” 如果真的考虑这样优化，影响还是比较大的
> 
> 参与方回滚的风险很大，因为tm那边可能不知道，如果出现用户编码上的bug，会导致后续的调用抛出not found xid的异常，至于为什么tm跟rm很大程度是一起，个人觉得，1.资源隔离 2.rm自身的单机事务也需要开启globaltransational来保证隔离性，否者将有可能脏写正在进行分布式事务中的数据 3.规范性，rm是tm，tm是tm
> 至于rm和tm共用某些功能，比如同个地址的channel完全可共享之类的，正在考虑

作者在这个issue中确实这么回复的 “Here are some points to consider: whether the provider directly send a globalRollback request when an exception occurs in the provider. if want to support this feature, need to enable the transactionManager on the provider.”

https://github.com/seata/seata/pull/1936
