### ISSUE TITLE
seata和openfeign冲突问题

### ISSUE THREAD

**Issue by Hxd2018** [seata/seata#3995]
seata和openfeign冲突问题
依赖如下：
    
![image](https://user-images.githubusercontent.com/37855805/131595539-6c9129a9-ce95-49c3-90a8-100f0086ae69.png)
![image](https://user-images.githubusercontent.com/37855805/131595723-83002801-df43-44a7-a703-ae57f3b01848.png)

启动报错，网上搜索都是版本问题， 此配置是按照官网的版本配置 而且修改seata版本后依旧不能解决问题
问题如下：
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'seataBeanPostProcessor' defined in class path resource [com/alibaba/cloud/seata/feign/SeataFeignClientAutoConfiguration$FeignBeanPostProcessorConfiguration.class]: Unsatisfied dependency expressed through method 'seataBeanPostProcessor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'seataFeignObjectWrapper' defined in class path resource [com/alibaba/cloud/seata/feign/SeataFeignClientAutoConfiguration$FeignBeanPostProcessorConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.alibaba.cloud.seata.feign.SeataFeignObjectWrapper] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
![image](https://user-images.githubusercontent.com/37855805/131596197-bb8010e4-5c3d-49f0-8235-de7ddd5079d0.png)

然后修改依赖为
![image](https://user-images.githubusercontent.com/37855805/131598546-157577ab-fca6-4c51-9f11-5cdf140a95a0.png)

报错换成了
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'dataSource' is expected to be of type 'io.seata.rm.datasource.DataSourceProxy' but was actually of type 'com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$dbd72180'
![image](https://user-images.githubusercontent.com/37855805/131598618-1f067342-5ef5-47b0-9eaf-47e1eca2a1bf.png)

**Comment by a364176773** [comment]
第一个冲突是你版本冲突，具体问题反馈至spring-cloud-alibaba社区
第二个，不要引入druid-spring-boot-starter依赖，或者关闭其自动装载的类
