### ISSUE TITLE
seata集群，全局事务提交的时候，redis的事务报错：返回null

### ISSUE THREAD

**Issue by dashenghuo** [seata/seata#3996]
<img width="671" alt="lALPD3lGvJ315I_NAabNBT4_1342_422" src="https://user-images.githubusercontent.com/27012214/131646417-0ebf82b1-7359-48a8-86fd-cc53e1d33755.png">

- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

如上图。由于WATCH本身的作用是“监视key是否被改动过”，而且支持同时监视多个key，只要还没真正触发事务，WATCH都会尽职尽责的监视，一旦发现某个key被修改了，在执行EXEC时就会返回nil，表示事务无法触发。
分析：被 其他 tc  抢先执行了， watch 的全局事务key的value 已经被改了，导致EXEC返回值为null， 这个 tc  报错

### Ⅲ. Describe what you expected to happen

对EXEC返回值 做null判断，如果为null，则日志记录“已经被其他tc执行了”；不为null，则继续。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by lightClouds917** [comment]
I will fix it.please assign to me. @a364176773
