### ISSUE TITLE
develop(v1.5) tcc 增强方案可能存在缺陷

### ISSUE THREAD

**Issue by x-shadow-man** [seata/seata#3997]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
在1.5.0(develop)版本中，对TCC的增强方案目前只覆盖了空提交、空回滚的处理，并未覆盖悬挂和并发情况的处理

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
我想尝试修复这个问题，请把这个任务分配给我，谢谢！

**Comment by a364176773** [comment]
![Uploading image.png…]()
一阶段如果发生registy后就回滚，那么二阶段回滚查询不到本地事务记录表的数据，会直接插入一条记录，此时还在一阶段的tcc事务会直接唯一索引冲突而回滚本地事务，悬挂问题解决。
并发是指什么问题？

**Comment by feng081212** [comment]
悬挂问题现在的方案已经解决了

**Comment by x-shadow-man** [comment]
> ![image](https://user-images.githubusercontent.com/19943636/131794905-1a7415e0-ee25-41f5-825f-809ae280516a.png)
> 一阶段如果发生registy后就回滚，那么二阶段回滚查询不到本地事务记录表的数据，会直接插入一条记录，此时还在一阶段的tcc事务会直接唯一索引冲突而回滚本地事务，悬挂问题解决。
> 并发是指什么问题？

嗯。刚才跟同事 check 了，发现悬挂问题新版本已经解决了，但是并发这块可能还是可能有一些问题。你看是否可以让我们尝试修复一下看看。

**Comment by feng081212** [comment]
prepare 和 rollback 都是在 transactionTemplate.execute() 方法内执行的（  transactionTemplate 是org.springframework.transaction.support.TransactionTemplate），所以prepare 和 rollback都是开启了本地事务。rollback 中的 TCCFenceDO tccFenceDO = TCC_FENCE_DAO.queryTCCFenceDO(conn, xid, branchId) 和 insertTCCFenceLog(conn, xid, branchId, actionName, TCCFenceConstant.STATUS_TRIED) 会竞争数据库的锁资源，所以不存在 prepare 和 rollback 并行执行的问题。

**Comment by feng081212** [comment]
prepare 和 rollback 都是在 transactionTemplate.execute() 方法内执行的（ transactionTemplate 是org.springframework.transaction.support.TransactionTemplate），所以prepare 和 rollback都是开启了本地事务。rollback 中的 TCCFenceDO tccFenceDO = TCC_FENCE_DAO.queryTCCFenceDO(conn, xid, branchId) 和 prepare 中的 insertTCCFenceLog(conn, xid, branchId, actionName, TCCFenceConstant.STATUS_TRIED) 会竞争数据库的锁资源，所以不存在 prepare 和 rollback 并行执行的问题。

**Comment by SDuper** [comment]
发生了空回滚的时候，tcc_fence_log表里面插入的状态是4，然后定时器默认每天清理一次一天前的tcc_fence_log数据，目前看只清理2，3状态的数据，4状态的数据，就一直放库里存着吗？为什么不一并把4清理了？
