### ISSUE TITLE
分布式事务与本地事务共存时，导致本地事务异常后无法正常回滚

### ISSUE THREAD

**Issue by Tancen** [seata/seata#3999]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

分布式事务与本地事务共存时，导致本地事务异常后无法正常回滚
准备表 test1, test2,
接口 test1,
@Transactional(rollbackFor=Exception.class)
void tes1(...)
{
insert into test1 ...
int v = 1 / 0;   //主动产生异常
insert into test2 ...
}

接口 test2,
@GlobalTransactional(rollbackFor=Exception.class)
void tes2(...)
{
......
}

### Ⅱ. Describe what happened

当请求接口 test1 时, test1 表有记录，test 2 表没有

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
当请求接口 test1 时, test1、test2都没记录

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows
- Others:
- seata 1.4.2 
- spring boot 2.4.5

**Comment by a364176773** [comment]
先理解好什么是本地事务吧。。。。。

**Comment by Tancen** [comment]
那请问怎么解决这个问题呢？

**Comment by Tancen** [comment]
另外，可能没写清楚，test1和test2在同一个数据库，它确实时本地事务

**Comment by a364176773** [comment]
AT模式不会影响本地事务，没有问题，有问题就是你自己判断有误，或者代码有问题

**Comment by Tancen** [comment]
@RestController
public class Test
{
    @Autowired
    TestMapper testMapper;

    @Transactional(rollbackFor=Exception.class)
    @RequestMapping(value = "test1", method = RequestMethod.POST)
    void test1(@Param("id") Integer id, @Param("v") Integer v)
    {
        testMapper.insert(id, v);
        int a = 1/0;
        testMapper.insert2(id, v);
    }

    @GlobalTransactional(rollbackFor=Exception.class)
    @RequestMapping(value = "test2", method = RequestMethod.POST)
    void test2(@Param("id") Integer id, @Param("v") Integer v)
    {
        testMapper.insert2(id, v);
    }
}

这是核心测试代码, 请问一下这里哪里导致test1不能回滚？
数据库用的是mysql， 配置是常规配置，我想应该已经是处于AT模式了

**Comment by Pinocchio2018** [comment]
@Tancen 你好，请问如果不加@GlobalTransactional的话，`testMapper.insert(id, v);`能回滚成功吗

**Comment by Tancen** [comment]
能的

**Comment by Tancen** [comment]
@a364176773 希望大家心态能平和一些，不是所有开发者都是傻子

**Comment by Pinocchio2018** [comment]
@Tancen 请问你代理数据源了吗，如果没有的话，可以参考seata-samples工程
你调用的是`test1()`吧？怎么这方法没加 `@GlobalTransactional`呢
要不改成这样试试
```java
@RestController
public class Test {

    @Autowired
    TestMapper testMapper;
    
    @Transactional(rollbackFor=Exception.class)
    @GlobalTransactional(rollbackFor=Exception.class)
    @RequestMapping(value = "test1", method = RequestMethod.POST)
    void test1(@Param("id") Integer id, @Param("v") Integer v)
    {
        testMapper.insert(id, v);
      
        testMapper.insert2(id, v);
        int a = 1/0;
    }
    
}

```

**Comment by a364176773** [comment]
> @a364176773 希望大家心态能平和一些，不是所有开发者都是傻子

觉得我说的有问题，就去看源码，实现原理

**Comment by a364176773** [comment]
如果原理源码上那里影响了本地事务回滚再来说，反正你也不相信我说的，那你何必来社区问？

**Comment by Tancen** [comment]
@a364176773  '先理解好什么是本地事务吧。。。。。'， 我说的是这句。你这不是正常的解决问题的态度

**Comment by Tancen** [comment]
之前不回滚的问题，我们做了后续的测试，由于一开始是项目出了本地事务无法回滚的问题，单独写了测试demo，这个demo有个问题，就是 controller 是不能通过注解跑事务的。后来我们补了一个 service层，经过测试发现多数据源的情况下，主数据源下 Transactional 可以生效，其它数据源不行

**Comment by Tancen** [comment]
@a364176773 你可以不回答，但你的回答就是态度有问题。给人的感觉就是其他人都是傻逼，阿里的人就是这副尿性

**Comment by Tancen** [comment]
@a364176773 关问题的速度比什么都快，感觉像是有KPI一样

**Comment by a364176773** [comment]
> @a364176773 你可以不回答，但你的回答就是态度有问题。给人的感觉就是其他人都是傻逼，阿里的人就是这副尿性

我不是阿里的

**Comment by a364176773** [comment]
> 之前不回滚的问题，我们做了后续的测试，由于一开始是项目出了本地事务无法回滚的问题，单独写了测试demo，这个demo有个问题，就是 controller 是不能通过注解跑事务的。后来我们补了一个 service层，经过测试发现多数据源的情况下，主数据源下 Transactional 可以生效，其它数据源不行

多数据源本身不支持事务，更加证明了我上面说的，叫你去了解什么是本地事务，本地事务没玩明白，没搞懂，就上分布式事务，然后出一些基本事务常识能判断的问题，就来社区提issue，仿佛是seata造成的，其实完全是自己的问题，然后还信誓旦旦的态度态度，我想问你啥时候对学习能有问问题那么积极？如果你学习有那么积极，早就debug看了下connectionProxy干了什么，spring本地事务怎么支持的，为什么多数据源不支持事务

**Comment by a364176773** [comment]
> 之前不回滚的问题，我们做了后续的测试，由于一开始是项目出了本地事务无法回滚的问题，单独写了测试demo，这个demo有个问题，就是 controller 是不能通过注解跑事务的。后来我们补了一个 service层，经过测试发现多数据源的情况下，主数据源下 Transactional 可以生效，其它数据源不行

多数据源本身不支持事务，更加证明了我上面说的，叫你去了解什么是本地事务，本地事务没玩明白，没搞懂，就上分布式事务，然后出一些基本事务常识能判断的问题，就来社区提issue，仿佛是seata造成的，其实完全是自己的问题，然后还信誓旦旦的态度态度，我想问你啥时候对学习能有问问题那么积极？如果你学习有那么积极，早就debug看了下connectionProxy干了什么，spring本地事务怎么支持的，为什么多数据源不支持事务

**Comment by Tancen** [comment]
> > 之前不回滚的问题，我们做了后续的测试，由于一开始是项目出了本地事务无法回滚的问题，单独写了测试demo，这个demo有个问题，就是 controller 是不能通过注解跑事务的。后来我们补了一个 service层，经过测试发现多数据源的情况下，主数据源下 Transactional 可以生效，其它数据源不行
> 
> 多数据源本身不支持多个数据源的事务，更加证明了我上面说的，叫你去了解什么是本地事务，本地事务没玩明白，没搞懂，就上分布式事务，然后出一些基本事务常识能判断的问题，就来社区提issue，仿佛是seata造成的，其实完全是自己的问题，然后还信誓旦旦的态度态度，我想问你啥时候对学习能有问问题那么积极？如果你学习有那么积极，早就debug看了下connectionProxy干了什么，spring本地事务怎么支持的，为什么多数据源无法通过transactional直接多数据源事务

抱歉我描述不清晰，配置是多数据源，但在当时场景下只用了一个数据源。很多事情你太多的过于主观判断，这很让人反感。你不是阿里的人，但你代表的阿里，希望你能明白，你的举动不代表你个人

**Comment by Tancen** [comment]
虽然最终不一定是seata的问题，但你不应该在还没了解情况前说seata就没问题。难道现在的版本就一定一个bug都没有吗？

**Comment by a364176773** [comment]
> > > 之前不回滚的问题，我们做了后续的测试，由于一开始是项目出了本地事务无法回滚的问题，单独写了测试demo，这个demo有个问题，就是 controller 是不能通过注解跑事务的。后来我们补了一个 service层，经过测试发现多数据源的情况下，主数据源下 Transactional 可以生效，其它数据源不行
> > 
> > 
> > 多数据源本身不支持多个数据源的事务，更加证明了我上面说的，叫你去了解什么是本地事务，本地事务没玩明白，没搞懂，就上分布式事务，然后出一些基本事务常识能判断的问题，就来社区提issue，仿佛是seata造成的，其实完全是自己的问题，然后还信誓旦旦的态度态度，我想问你啥时候对学习能有问问题那么积极？如果你学习有那么积极，早就debug看了下connectionProxy干了什么，spring本地事务怎么支持的，为什么多数据源无法通过transactional直接多数据源事务
> 
> 抱歉我描述不清晰，配置是多数据源，但在当时场景下只用了一个数据源。很多事情你太多的过于主观判断，这很让人反感。你不是阿里的人，但你代表的阿里，希望你能明白，你的举动不代表你个人

我代表不了阿里，seata是属于开源社区的，不是强绑定阿里希望你明白

**Comment by a364176773** [comment]
> 虽然最终不一定是seata的问题，但你不应该在还没了解情况前说seata就没问题，并且还进行常识攻击。难道现在的版本就一定一个bug都没有吗？

肯定有bug呀，但是对一个你的描述瞬间就能判断出来与seata无关的问题，我的回复有什么问题吗？以前我参与社区的时候是知无不言言无不尽，但是我参与的这么长时间，我发现直接给答案是解决不了问题的，只有引导式回答才行，给一定的相关提示，比如让你了解本地事务，如果你了解透彻了，这个问题不就自己有答案了吗，这提高能力的是你，节约时间的是大家，而如果直接给答案，节约的是提问者时间，耗费的是回答者时间，为何不能共同进步？

**Comment by Tancen** [comment]
> > 虽然最终不一定是seata的问题，但你不应该在还没了解情况前说seata就没问题，并且还进行常识攻击。难道现在的版本就一定一个bug都没有吗？
> 
> 肯定有bug呀，但是对一个你的描述瞬间就能判断出来与seata无关的问题，我的回复有什么问题吗？以前我参与社区的时候是知无不言言无不尽，但是我参与的这么长时间，我发现直接给答案是解决不了问题的，只有引导式回答才行，给一定的相关提示，比如让你了解本地事务，如果你了解透彻了，这个问题不就自己有答案了吗，这提高能力的是你，节约时间的是大家，而如果直接给答案，节约的是提问者时间，耗费的是回答者时间，为何不能共同进步？

你可以引导，但就像我说的，你别把其他人像傻子一样看待。像国外的项目，开发者提问题，如果他们觉得线索不够清晰，会让开发者提供更详细的线索。而不是像你现在这样，一开始就表示“你连基础概念都不懂”
steata 是属于开源社区，但是是阿里组织的，并且阿里依然在维护，你被吸纳进去，作为维护者，私下里你可以代表你自己，但在这里你代表的是整个团体
