### ISSUE TITLE
seata1.4 zk 连接问题

### ISSUE THREAD

**Issue by hylyLLL** [seata/seata#4009]
![image](https://user-images.githubusercontent.com/46893979/132459473-77ee7a27-4174-4662-8028-176039c60d2e.png)
![image](https://user-images.githubusercontent.com/46893979/132459576-6e375425-5ed2-4afd-bdde-9c638f4b7f22.png)
![image](https://user-images.githubusercontent.com/46893979/132459609-2900cab5-c627-4be4-b944-1690c51ed1a9.png)
![image](https://user-images.githubusercontent.com/46893979/132459861-a4ab9ae0-5ae6-4100-9cda-cd67b1e999ab.png)

seata-server连接zk无法获取配置信息

**Comment by hylyLLL** [comment]
zk和seata-server能够正常运行，全局事务也能够正常运行，但是当zk服务和seata-server不在同一个太服务器上就连接超时，telnet zk的服务器是正常的

**Comment by a364176773** [comment]
自己写用zkclient写一个对该zk的连接程序放到seata-server在的服务器上试试，源码是标准的zkclient使用方式，建议你去阅读下源码进行进一步排查

**Comment by hylyLLL** [comment]
> 自己写用zkclient写一个对该zk的连接程序放到seata-server在的服务器上试试，源码是标准的zkclient使用方式，建议你去阅读下源码进行进一步排查

我写了一个初始化seata配置参数到zookeeper的小应用是可以成功的
