### ISSUE TITLE
Shiro注册自定义Realm，导致RM的resourceids为null，没有执行数据源代理，并且必须使用jdk代理

### ISSUE THREAD

**Issue by zhaozhengxin1005** [seata/seata#4010]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/44998204/132685183-6c7ef363-8237-4472-b6a4-ae6a0d37ec12.png)
![image](https://user-images.githubusercontent.com/44998204/132685301-e96a95fe-92f3-4eb7-ab81-f6b89d103e07.png)

### Ⅱ. Describe what happened

![image](https://user-images.githubusercontent.com/44998204/132685148-4dbe6660-186b-49c1-94a3-8eccefc22627.png)、

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:   1.4.2
- OS :
- Others: shiro 1.7.1

**Comment by zhaozhengxin1005** [comment]
这种情况，会导致resourceids为null的服务无法回滚事务，undo日志生成了并且自动删除了，但是就是数据没有回滚

**Comment by a364176773** [comment]
试试手动代理,关了自动代理

**Comment by zhaozhengxin1005** [comment]
我用官网提供的手动方式，提示我循环依赖了

**Comment by zhaozhengxin1005** [comment]
![image](https://user-images.githubusercontent.com/44998204/132689831-c849d3c1-84cf-4aa0-a014-2ec1b24d3b67.png)

**Comment by a364176773** [comment]
自动代理有没有关闭，看下你的配置

**Comment by zhaozhengxin1005** [comment]
![image](https://user-images.githubusercontent.com/44998204/132690282-b06bb402-b7a1-432c-98ef-10a9afd29f53.png)

**Comment by zhaozhengxin1005** [comment]
![image](https://user-images.githubusercontent.com/44998204/132690450-57f99e56-7fe9-450c-9ff9-bd1456eab93b.png)

**Comment by a364176773** [comment]
@Primary
    @Bean("dataSource")
    public DataSource dataSource(DataSource 你数据源的beanname) {
    	//AT 代理 二选一
        return new DataSourceProxy(druidDataSource);
        //XA 代理
        return new DataSourceProxyXA(druidDataSource)
    }
关闭自动代理
seata:
  enable-auto-data-source-proxy: false

**Comment by zhaozhengxin1005** [comment]
使用了手动数据源代理，解决了此问题
