### ISSUE TITLE
seata  server和client端在读取consul中的k/v超时的问题

### ISSUE THREAD

**Issue by treespringace** [seata/seata#4012]
所有的业务服务和seata服务以及注册中心consul都在一个服务器上，读取consul中配置信息能正常读取，但是在下列的环境中就会存在超时的问题。
          业务服务在A服务器中部署且注册中心是consul-01，seata服务也在A服务中部署**但是**注册中心和配置中心连接的是consul-02，会出现下列错误：

1. 此时启动seata服务时日子打印获取store.mode超时
2. 业务服务启动时，获取service.disableGlobalTransaction配置超时
3. 上述两种情况虽然发生了，全局事务依然能够生效
![image](https://user-images.githubusercontent.com/83049927/132832343-de308dbc-f3c4-4797-97c6-784597a3cb3d.png)
![image](https://user-images.githubusercontent.com/83049927/132832408-77ee2377-68ec-4c94-8c48-9a9407de35a5.png)

**Comment by a364176773** [comment]
检查相应配置中心有没有该dataid
