### ISSUE TITLE
In the case of multiple networks, does support select an ip address by  `nacos.inetutils.preferred-networks` 

### ISSUE THREAD

**Issue by xuande** [seata/seata#4029]
## Why you need it?
Seata注册到nacos中，当存在多网卡时会随机选择一个，是否支持通过设置`nacos.inetutils.preferred-networks`，选择某个某个网卡上的IP地址。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
@xuande #3886

**Comment by xuande** [comment]
> @xuande #3886

Thanks
