### ISSUE TITLE
seata 使用 mybatis-plug 时，批量插入无法返回主键，不加全局事务的时候正常

### ISSUE THREAD

**Issue by pikachulight** [seata/seata#4030]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata 使用 mybatis-plug 时，批量插入无法返回主键，不加全局事务的时候正常

### Ⅲ. Describe what you expected to happen

增加了全局事务注解后，可以正常拿到自增长的主键id

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

pg 数据库，mybatis-plus，批量插入，mybatis那边拿不到主键，但是 seata 的前后镜像可以拿到主键

### Ⅵ. Environment:

- JDK version : 11
- Seata version:  1.42
- OS : windows
- Others: pg

**Comment by a364176773** [comment]
Q: 10.为什么mybatis没有返回自增ID?
A: 方案1.需要修改mybatis的配置: 在@Options(useGeneratedKeys = true, keyProperty = "id")或者在xml中指定useGeneratedKeys 和 keyProperty属性
方案2.删除undo_log表的id字段

**Comment by pikachulight** [comment]
> Q: 10.为什么mybatis没有返回自增ID?
> A: 方案1.需要修改mybatis的配置: 在@options(useGeneratedKeys = true, keyProperty = "id")或者在xml中指定useGeneratedKeys 和 keyProperty属性
> 方案2.删除undo_log表的id字段

已指定useGeneratedKeys 和 keyProperty属性，但是无效
