### ISSUE TITLE
Seata AT模式 如果操作的主键id，回滚日志要如何生成

### ISSUE THREAD

**Issue by AudiVehicle** [seata/seata#4031]
读了下seata的官方文档，对于undo_log的生产有一个疑问，阐述如下：

对于正常的update sql，我看官方文档写的是，先根据where 条件找到数据「前镜像」，然后执行sql，然后根据数据的主键id找到数据的「后镜像」

那，如果刚好业务sql操作的就是主键id呢？比如 update xx set id=15 where id=10  这种要如何生成undo_log?

谢谢

**Comment by a364176773** [comment]
不允许修改主键值

**Comment by AudiVehicle** [comment]
明白  3q
