### ISSUE TITLE
Springboot2.3.4 postgresql mybatis-plus3.2使用seta1.4.2 AT模式时无法获取自增id

### ISSUE THREAD

**Issue by xuehairui** [seata/seata#4035]
Springboot2.3.4 postgresql mybatis-plus3.2使用seta1.4.2 AT模式时无法获取自增id
尝试使用seata常见问题中的2种方式修复,但是发现都不生效 调用save方法仍然获取不到id

**Comment by pikachulight** [comment]
我也遇到这个问题，很奇怪，前后镜像的构建是可以拿到主键id的。但是mybatis-plugs就是拿不到

**Comment by xuehairui** [comment]
> 我也遇到这个问题，很奇怪，前后镜像的构建是可以拿到主键id的。但是mybatis-plugs就是拿不到

可以分享下你是怎么解决的嘛

**Comment by caohdgege** [comment]
提供一下表结构，复现demo，pg版本等等

**Comment by pikachulight** [comment]
> 提供一下表结构，复现demo，pg版本等等

https://github.com/pikachulight/seate-bug-fix 相关版本以及初始化sql都在这个仓库列出

**Comment by pikachulight** [comment]
> 提供一下表结构，复现demo，pg版本等等

具体表现为加了全局事务的主键无法返回，没有全局事务的主键正常返回

**Comment by pikachulight** [comment]
> > 我也遇到这个问题，很奇怪，前后镜像的构建是可以拿到主键id的。但是mybatis-plugs就是拿不到
> 
> 可以分享下你是怎么解决的嘛

seata-1.42特有的bug,切成1.41就可以了

**Comment by pikachulight** [comment]
> 1.4.2跟1.4.1这块代码没有做过变动，建议再次调试，或者提供复现demo

我上面有复现demo的，https://github.com/pikachulight/seate-bug-fix
