### ISSUE TITLE
在同一个项目里，XA与TCC模式是否可同时使用?

### ISSUE THREAD

**Issue by zhangqingshan-1** [seata/seata#4037]
如题，在同一个项目里，XA与AT模式是否可同时使用，若支持混用，则要注意哪些问题，有相关文档没有呢？若不支持，未来有支持打算没有，大概何时能发布？麻烦告知下，多谢啦！

**Comment by a364176773** [comment]
可以，但是xa不允许资源重入，如果数据被tcc先改，xa再改没问题，如果xa改了想用tcc在预留资源啥的就不行了
