### ISSUE TITLE
@GlobalTransactional在1.1.0版本开始，不启动seata-server服务也能进行回滚？

### ISSUE THREAD

**Issue by xianaofei** [seata/seata#4040]
@GlobalTransactional
    public void createOrder(OrderCreateDTO orderCreateDTO) {
        // 扣库存
        int storageStatus = orderMapper.updateStorageCount(orderCreateDTO.getCount(), orderCreateDTO.getCommodityCode());
        if (storageStatus == 0) {
            throw new BaseException("库存不足");
        }
        
        // 生成订单
        StorageDO commodity = orderMapper.getStorageByCommodityCode(orderCreateDTO.getCommodityCode());
        int i = 10 / 0;
        OrderDO orderDO = new OrderDO();
        BeanUtils.copyProperties(orderCreateDTO, orderDO);
        orderDO.setMoney(orderCreateDTO.getCount() * commodity.getPrice());
        dubboOrderService.createOrder(orderDO);
    }

     <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
            <version>1.1.0</version>
        </dependency>

不启动seata-server.bat。通过接口调用时
如果使用1.0.0版本直接报错no seata server。
但是如果把版本换成1.1.0版本及以上，也能够控制回滚，请问是GlobalTransactional 注解在高版本已经不需要启动seata server服务了吗？

**Comment by a364176773** [comment]
出现幻觉了吧，哪里用了切点表达式的事务，本地事务给回滚了吧

**Comment by xianaofei** [comment]
没有使用本地事务，也没有AOP。请各位换版本自测一下试试。
