### ISSUE TITLE
Maven compile fail because of druid version

### ISSUE THREAD

**Issue by xilou31** [seata/seata#4047]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
编译过程中 (mvn clean package) ，发现使用Druid模块的都编译不过。
去druid搜相关问题，发现可能是版本原因。
https://github.com/alibaba/druid/issues/4309
Seata因为没有指定版本，因此使用的是最新版1.2.6。
将druid制定版本为1.2.5即可编译通过。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

![image](https://user-images.githubusercontent.com/44915143/135076162-9d9c1c5a-7a94-4171-bbce-5df9051dfa6d.png)

### Ⅲ. Describe what you expected to happen
![image](https://user-images.githubusercontent.com/44915143/135076374-6b50fef0-178b-4e6f-a046-f0fbdbcaf25f.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. git clone seata/seata
2. mvn clean package

### Ⅵ. Environment:

- JDK version : 1.8.0_261 
- Seata version: 1.5
- OS : Macos
- Others:

**Comment by a364176773** [comment]
mvn -Prelease-seata -Dmaven.test.skip=true clean install -U
