### ISSUE TITLE
求解有个疑问seata的回滚出现ABA问题的话有解决方案吗

### ISSUE THREAD

**Issue by xuejmnet** [seata/seata#4049]
求解有个疑问seata的回滚出现ABA问题的话有解决方案吗

**Comment by xuejmnet** [comment]
seata的回滚是根据undolog来进行数据校验回滚如果回滚的时候出现了aba问题校验后置镜像一样是否会有问题

**Comment by Pinocchio2018** [comment]
你好，seata AT模式会有全局锁的。不会发生aba问题

**Comment by xuejmnet** [comment]
> 你好，seata AT模式会有全局锁的。不会发生aba问题

谢谢

**Comment by a364176773** [comment]
不会，根据branch下发，branch的表是有时间戳字段的，根据你注册的时候按顺序回滚，如果出现不按顺序，请看下你的branch table的表是否datetime字段精度是否设置

**Comment by xuejmnet** [comment]
> 不会，根据branch下发，branch的表是有时间戳字段的，根据你注册的时候按顺序回滚，如果出现不按顺序，请看下你的branch table的表是否datetime字段精度是否设置

因为有可能会出现对应表不需要参与全局事务的情况
