### ISSUE TITLE
seata server显示回滚成功 控制台也显示回滚成功 但实际并没有回滚

### ISSUE THREAD

**Issue by nanxia990105** [seata/seata#4061]
springboot 2.3.3 配置了本地文件启动 seata控制台也都收到了生产者的注册，消费者也注册到seata server
![image](https://user-images.githubusercontent.com/64909808/136667193-5c10a3e4-1ff9-4365-8956-6aba4cd26af2.png)

但是实际并没有回滚 的操作 即使按照文档里面的编码而不是注解也是同样的消费者控制台与seata server控制台都是已经回滚或回滚成功的标识

![IV)~WV` (C~LAW)QT6`E$G9](https://user-images.githubusercontent.com/64909808/136667268-7e0bfdc1-dc0c-42c5-9486-48d9ae0e34d4.png)
并且在官方群说的数据库代理和xid不一致 也都是进入到对应的方法里的 所以数据库代理和xid应该不是这里的问题，断点也都捕捉到了
![D YMHIE(H{~JKB@IPYES_FM](https://user-images.githubusercontent.com/64909808/136667348-00368fae-189e-4064-b339-380d6306753a.png)
所以我不太明白是哪里出了问题。。。。
也是不得已占用宝贵的issues 往大佬解答一下
- JDK version :1.8
- Seata version:  1.3.0
- OS :
- Others:

**Comment by a364176773** [comment]
既然在群里就看公告教程

**Comment by nanxia990105** [comment]
群里教程，公告都是正常流程，我也是看文档流程搭建，现在是找不到问题的方向，是配置还是个人代码方向，望大佬解答一下

**Comment by a364176773** [comment]
debug connection#proxy registry如果有进, 并且成功注册上肯定能回滚
