### ISSUE TITLE
请教，XA模式无法回滚

### ISSUE THREAD

**Issue by whxxxxx** [seata/seata#4087]
数据源代理AT模式可以回滚，改为XA就无法回滚。seata-server有日志rollback success，但是实际数据库中没回滚

@Bean("dataSourceProxy")
    public DataSource dataSource(DruidDataSource druidDataSource) {
        // DataSourceProxy for AT mode
//         return new DataSourceProxy(druidDataSource);

        // DataSourceProxyXA for XA mode
        return new DataSourceProxyXA(druidDataSource);
    }

io.seata.server.coordinator.DefaultCore  : Rollback global transaction successfully, xid = 172.16.26.44:8091:1432333448546185253.

**Comment by a364176773** [comment]
你关掉自动代理了没？如果你是1.4.2，你可以自动代理为xa，把手动代理关了，详细看script文件夹里的client的properties或yaml示例，我昨天刚测试的xa

**Comment by whxxxxx** [comment]
> 你关掉自动代理了没？如果你是1.4.2，你可以自动代理为xa，把手动代理关了，详细看script文件夹里的client的properties或yaml示例，我昨天刚测试的xa

改为自动代理后，其中一个分支成功了，有日志Branch Rollbacked result: PhaseTwo_Rollbacked，但是另一个分支还是没成功。
