### ISSUE TITLE
关于oracles数据库使用XA/TCC模式问题

### ISSUE THREAD

**Issue by dakongyi258** [seata/seata#4117]
我遇到个场景，当有多个微服务的数据源指向统一oracle数据库(版本不限)，使用XA或者TCC模式均报错，但切换成不同一数据源的时候正常。错误如下：
### Cause: java.sql.SQLException: failed to start xa branch 179.16.10.226:8091:6719565797042716861 since XAErr (-3): A resource manager error has occured in the transaction branch. ORA-2079 SQLErr (0)
; uncategorized SQLException; SQL state [null]; error code [0]; failed to start xa branch 179.16.10.226:8091:6719565797042716861 since XAErr (-3): A resource manager error has occured in the transaction branch. ORA-2079 SQLErr (0); nested exception is java.sql.SQLException: failed to start xa branch 179.16.10.226:8091:6719565797042716861 since XAErr (-3): A resource manager error has occured in the transaction branch. ORA-2079 SQLErr (0)] with root cause
java.sql.SQLSyntaxErrorException: ORA-02079: 无法联接要提交的分布式事务处理

**Comment by a364176773** [comment]
oracle 无法对资源进行重入，用tcc即可，tcc不要进行代理数据源，并关闭自动代理

**Comment by dakongyi258** [comment]
非常感谢，确实可以
