### ISSUE TITLE
Could not register branch into global session xid = status = RollbackRetrying 到底怎么从业务层面解决a？

### ISSUE THREAD

**Issue by yangnima** [seata/seata#4119]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

为什么分支事务注册时, 全局事务状态不是begin

 异常：Could not register branch into global session xid = status = Rollbacked（还有Rollbacking、AsyncCommitting等等二阶段状态） while expecting Begin
描述：分支事务注册时，全局事务状态需是一阶段状态begin，非begin不允许注册。属于seata框架层面正常的处理，用户可以从自身业务层面解决。
出现场景（可继续补充）
  1. 分支事务是异步，全局事务无法感知它的执行进度，全局事务已进入二阶段，该异步分支才来注册
  2. 服务a rpc 服务b超时（dubbo、feign等默认1秒超时），a上抛异常给tm，tm通知tc回滚，但是b还是收到了请求（网络延迟或rpc框架重试），然后去tc注册时发现全局事务已在回滚
  3. tc感知全局事务超时(@GlobalTransactional(timeoutMills = 默认60秒))，主动变更状态并通知各分支事务回滚，

到底怎么从业务层面解决啊？

**Comment by yangnima** [comment]
求各位大佬解答

**Comment by a364176773** [comment]
就是上面说的解决,禁止服务重试,保证没有异步进行的分支,如果还出现bollbacked就别管了,正常抛异常,比如你a调b,调不通,a就决议回滚事务,此时b收到了刚才的请求进行了业务处理,这是为了保证幂等,保证一致性,禁止了这个由于网络异常造成不一致的可能,抛出异常回滚掉这个独立的分支事务的进行,保证了一致性
