### ISSUE TITLE
docker-compose最新版本部署seate无法读取到registry.conf

### ISSUE THREAD

**Issue by HydraWu-Spotec** [seata/seata#4120]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seate的docker-compose.yaml内容如下:
version: "3"
services:
  seata-server:
    image: seataio/seata-server:latest
    container_name: seata-server4tmd
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
      - STORE_MODE=db
    volumes:
      - ./conf:/root/seata-config
    ports:
      - "38091:8091"
    restart: always

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
启动docker后logs会打印出:load Configuration from :Spring Configuration
看2.0源码后发现这条日志在FileConfiguration类中打印,此处应该无法读取到registry这个文件
(前提)已将registry.conf正确映射到docker容器内,进入后能正常cat出内容
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 11
- Seata version:  latest
- OS : deepin
- Others:

**Comment by slievrly** [comment]
@HydraWu-Spotec If you are using the latest version of server, the configuration file it reads is

https://github.com/seata/seata/blob/develop/server/src/main/resources/application.yml

**Comment by HydraWu-Spotec** [comment]
> @HydraWu-Spotec If you are using the latest version of server, the configuration file it reads is
> 
> https://github.com/seata/seata/blob/develop/server/src/main/resources/application.yml

所以我需要映射这个application.yml到容器吗

**Comment by a364176773** [comment]
不要使用latest版本，请使用release的版本，之前的部署教程不兼容latest
