### ISSUE TITLE
请问如何在docker中部署，我看官方文档并没用，就连官网的https都掉了，请问是不维护了吗？

### ISSUE THREAD

**Issue by bnyte** [seata/seata#4127]

**Comment by bnyte** [comment]
在官方文档中的部署连容器内部的路径都是错的，实在是离谱。

**Comment by a364176773** [comment]
> 在官方文档中的部署连容器内部的路径都是错的，实在是离谱。

官方当时基于的是1.4.2写的，目前latest不是release版本，拉1.4.2

**Comment by a364176773** [comment]
> 在官方文档中的部署连容器内部的路径都是错的，实在是离谱。

官方当时基于的是1.4.2写的，目前latest不是release版本，拉1.4.2
