### ISSUE TITLE
What is the full name of the AT mode?

### ISSUE THREAD

**Issue by Yuan0Teng** [seata/seata#4130]
TCC = Try Commit Cancel
XA = eXtended Architecture
saga = a long story of heroic achievement , just a word
AT = ???

so , What is the full name of the AT mode?

**Comment by tanzzj** [comment]
Automatic (Branch) Transaction Mode

**Comment by Yuan0Teng** [comment]
> Automatic (Branch) Transaction Mode

appreciate !
