### ISSUE TITLE
请教一下，为什么seata里面的redis都不支持集群模式呀

### ISSUE THREAD

**Issue by dyingstraw** [seata/seata#4131]
https://github.com/seata/seata/blob/f67644a0d5acc803a5098540a234e9370dce589c/server/src/main/java/io/seata/server/storage/redis/JedisPooledFactory.java#L103

有点疑惑。请教一下，为什么seata里面的redis都不支持集群模式呀，是有其他设计方面的考虑吗~

**Comment by a364176773** [comment]
以二阶段协议的性能下降和tps的峰值，redis单机和sentinel模式已经绰绰有余了，redis-cluster不一定能提升性能，而且存在更大一致性丢失的风险，比如宕机。 且redis-cluster不支持mget pipeline等措施，每一个命令都要通过内置的算法找到对应的redis去发请求，在一定比例的并发下负载均衡，提升吞吐，但是在目前的调研下，对tc没有实质性的吞吐和性能提升，在低并发下，还增加了多次网络io的开销，没有意义

**Comment by cloudkthuang** [comment]
请问现在1.6.1版本可以支持redis cluster 模式了吗
