### ISSUE TITLE
seata.enabled和seata.enable2个配置项命名不统一

### ISSUE THREAD

**Issue by dyingstraw** [seata/seata#4132]
https://github.com/seata/seata/blob/6f877fafd0bc4ad2f4840e7940c93493f9aa45d5/seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataDataSourceAutoConfiguration.java#L36

这里是seata.enabled
另一个seataAutoConfig又是seata.enable  两个命名不统一

感觉很奇怪

**Comment by a364176773** [comment]
develop已经修复
