### ISSUE TITLE
xa模式获取channel导致的资源悬挂问题

### ISSUE THREAD

**Issue by lcmvs** [seata/seata#4138]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
xa模式，获取channel导致的资源悬挂问题

### Ⅱ. Describe what happened

XA模式下，TC日志分布式事务回滚成功，实际上数据库中的分支事务未回滚，导致资源永远无法处理。

### Ⅲ. Describe what you expected to happen

TC日志记录的分布式事务回滚成功，数据库中的分支事务也应该回滚成功。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

order，account，storage三个服务，resource_id是相同的，也就是相同数据库，不同应用的场景下

1.开启了一个全局事务
2.然后order和tm的channel断了
3.tm会选择一个resource_id相同的服务，作为替代，比如account
4.发生xaer_note的异常，最终会发生资源悬挂的问题。

### Ⅴ. Anything else we need to know?

```java
    public static Channel getChannel(String resourceId, String clientId) {
        Channel resultChannel = null;

        String[] clientIdInfo = readClientId(clientId);

        if (clientIdInfo == null || clientIdInfo.length != 3) {
            throw new FrameworkException("Invalid Client ID: " + clientId);
        }

        String targetApplicationId = clientIdInfo[0];
        String targetIP = clientIdInfo[1];
        int targetPort = Integer.parseInt(clientIdInfo[2]);

        ConcurrentMap<String, ConcurrentMap<String, ConcurrentMap<Integer,
            RpcContext>>> applicationIdMap = RM_CHANNELS.get(resourceId);

        if (targetApplicationId == null || applicationIdMap == null ||  applicationIdMap.isEmpty()) {
            if (LOGGER.isInfoEnabled()) {
                LOGGER.info("No channel is available for resource[{}]", resourceId);
            }
            return null;
        }

        ConcurrentMap<String, ConcurrentMap<Integer, RpcContext>> ipMap = applicationIdMap.get(targetApplicationId);

        if (ipMap != null && !ipMap.isEmpty()) {
            // Firstly, try to find the original channel through which the branch was registered.
            ConcurrentMap<Integer, RpcContext> portMapOnTargetIP = ipMap.get(targetIP);
            if (portMapOnTargetIP != null && !portMapOnTargetIP.isEmpty()) {
                RpcContext exactRpcContext = portMapOnTargetIP.get(targetPort);
                if (exactRpcContext != null) {
                    Channel channel = exactRpcContext.getChannel();
                    if (channel.isActive()) {
                        resultChannel = channel;
                        if (LOGGER.isDebugEnabled()) {
                            LOGGER.debug("Just got exactly the one {} for {}", channel, clientId);
                        }
                    } else {
                        if (portMapOnTargetIP.remove(targetPort, exactRpcContext)) {
                            if (LOGGER.isInfoEnabled()) {
                                LOGGER.info("Removed inactive {}", channel);
                            }
                        }
                    }
                }

                // The original channel was broken, try another one.
                if (resultChannel == null) {
                    for (ConcurrentMap.Entry<Integer, RpcContext> portMapOnTargetIPEntry : portMapOnTargetIP
                        .entrySet()) {
                        Channel channel = portMapOnTargetIPEntry.getValue().getChannel();

                        if (channel.isActive()) {
                            resultChannel = channel;
                            if (LOGGER.isInfoEnabled()) {
                                LOGGER.info(
                                    "Choose {} on the same IP[{}] as alternative of {}", channel, targetIP, clientId);
                            }
                            break;
                        } else {
                            if (portMapOnTargetIP.remove(portMapOnTargetIPEntry.getKey(),
                                portMapOnTargetIPEntry.getValue())) {
                                if (LOGGER.isInfoEnabled()) {
                                    LOGGER.info("Removed inactive {}", channel);
                                }
                            }
                        }
                    }
                }
            }

            // No channel on the this app node, try another one.
            if (resultChannel == null) {
                for (ConcurrentMap.Entry<String, ConcurrentMap<Integer, RpcContext>> ipMapEntry : ipMap
                    .entrySet()) {
                    if (ipMapEntry.getKey().equals(targetIP)) { continue; }

                    ConcurrentMap<Integer, RpcContext> portMapOnOtherIP = ipMapEntry.getValue();
                    if (portMapOnOtherIP == null || portMapOnOtherIP.isEmpty()) {
                        continue;
                    }

                    for (ConcurrentMap.Entry<Integer, RpcContext> portMapOnOtherIPEntry : portMapOnOtherIP.entrySet()) {
                        Channel channel = portMapOnOtherIPEntry.getValue().getChannel();

                        if (channel.isActive()) {
                            resultChannel = channel;
                            if (LOGGER.isInfoEnabled()) {
                                LOGGER.info("Choose {} on the same application[{}] as alternative of {}", channel, targetApplicationId, clientId);
                            }
                            break;
                        } else {
                            if (portMapOnOtherIP.remove(portMapOnOtherIPEntry.getKey(),
                                portMapOnOtherIPEntry.getValue())) {
                                if (LOGGER.isInfoEnabled()) {
                                    LOGGER.info("Removed inactive {}", channel);
                                }
                            }
                        }
                    }
                    if (resultChannel != null) { break; }
                }
            }
        }

        if (resultChannel == null) {
            resultChannel = tryOtherApp(applicationIdMap, targetApplicationId);

            if (resultChannel == null) {
                if (LOGGER.isInfoEnabled()) {
                    LOGGER.info("No channel is available for resource[{}] as alternative of {}", resourceId, clientId);
                }
            } else {
                if (LOGGER.isInfoEnabled()) {
                    LOGGER.info("Choose {} on the same resource[{}] as alternative of {}", resultChannel, resourceId, clientId);
                }
            }
        }

        return resultChannel;

    }
```

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.2
- OS :
- Others:

**Comment by a364176773** [comment]
1.支持resourceid的自定义，来区分多个表
2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为
你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件

**Comment by lcmvs** [comment]
> 1.支持resourceid的自定义，来区分多个表 2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为 你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件

我觉得方案一更加合适，而且xa模式既然hold住连接，我觉得不应该再选择其他的服务，而且同一个服务的其他实例也不应该选择吧？

**Comment by a364176773** [comment]
> > 1.支持resourceid的自定义，来区分多个表 2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为 你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件
> 
> 我觉得方案一更加合适，而且xa模式既然hold住连接，我觉得不应该再选择其他的服务，而且同一个服务的其他实例也不应该选择吧？

好，我觉得你源码阅读的挺到位，仔细的，有没有兴趣认领下这个pr？

**Comment by lcmvs** [comment]
> > > 1.支持resourceid的自定义，来区分多个表 2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为 你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件
> > 
> > 
> > 我觉得方案一更加合适，而且xa模式既然hold住连接，我觉得不应该再选择其他的服务，而且同一个服务的其他实例也不应该选择吧？
> 
> 好，我觉得你源码阅读的挺到位，仔细的，有没有兴趣认领下这个pr？

resourceid的自定义我没啥思路，seata很多地方我还不是很熟，我本来的想法是，tc提交或者回滚的时候判断一下是不是xa，xa就不去获取其他实例的channel了。

**Comment by a364176773** [comment]
> > > > 1.支持resourceid的自定义，来区分多个表 2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为 你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件
> > > 
> > > 
> > > 我觉得方案一更加合适，而且xa模式既然hold住连接，我觉得不应该再选择其他的服务，而且同一个服务的其他实例也不应该选择吧？
> > 
> > 
> > 好，我觉得你源码阅读的挺到位，仔细的，有没有兴趣认领下这个pr？
> 
> resourceid的自定义我没啥思路，seata很多地方我还不是很熟，我本来的想法是，tc提交或者回滚的时候判断一下是不是xa，xa就不去获取其他实例的channel了。

这个想法在以前是行得通，而现在都是跑在容器里，当一个容器销毁重建时，他的ip是会变的，这样将永远重试无法恢复。
你可以看下jdbcutils#initDataSourceResource 自己可以想下怎么做比较优雅，比如config.getConfig读一个配置，这个配置可以直接是appname之类的能代表这个服务的集群都是相同的即可
不过我突然想到，如果你的order有2个节点，一个运行时channel断了，是不是也请求到了另一个去？是否一样有这个问题？

**Comment by lcmvs** [comment]
> > > > > 1.支持resourceid的自定义，来区分多个表 2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为 你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件
> > > > 
> > > > 
> > > > 我觉得方案一更加合适，而且xa模式既然hold住连接，我觉得不应该再选择其他的服务，而且同一个服务的其他实例也不应该选择吧？
> > > 
> > > 
> > > 好，我觉得你源码阅读的挺到位，仔细的，有没有兴趣认领下这个pr？
> > 
> > 
> > resourceid的自定义我没啥思路，seata很多地方我还不是很熟，我本来的想法是，tc提交或者回滚的时候判断一下是不是xa，xa就不去获取其他实例的channel了。
> 
> 这个想法在以前是行得通，而现在都是跑在容器里，当一个容器销毁重建时，他的ip是会变的，这样将永远重试无法恢复。 你可以看下jdbcutils#initDataSourceResource 自己可以想下怎么做比较优雅，比如config.getConfig读一个配置，这个配置可以直接是appname之类的能代表这个服务的集群都是相同的即可 不过我突然想到，如果你的order有2个节点，一个运行时channel断了，是不是也请求到了另一个去？是否一样有这个问题？

我的理解是一个服务多个节点，选择了其他节点，也是有这个问题的。

**Comment by a364176773** [comment]
> > > > > > 1.支持resourceid的自定义，来区分多个表 2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为 你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件
> > > > > 
> > > > > 
> > > > > 我觉得方案一更加合适，而且xa模式既然hold住连接，我觉得不应该再选择其他的服务，而且同一个服务的其他实例也不应该选择吧？
> > > > 
> > > > 
> > > > 好，我觉得你源码阅读的挺到位，仔细的，有没有兴趣认领下这个pr？
> > > 
> > > 
> > > resourceid的自定义我没啥思路，seata很多地方我还不是很熟，我本来的想法是，tc提交或者回滚的时候判断一下是不是xa，xa就不去获取其他实例的channel了。
> > 
> > 
> > 这个想法在以前是行得通，而现在都是跑在容器里，当一个容器销毁重建时，他的ip是会变的，这样将永远重试无法恢复。 你可以看下jdbcutils#initDataSourceResource 自己可以想下怎么做比较优雅，比如config.getConfig读一个配置，这个配置可以直接是appname之类的能代表这个服务的集群都是相同的即可 不过我突然想到，如果你的order有2个节点，一个运行时channel断了，是不是也请求到了另一个去？是否一样有这个问题？
> 
> 我的理解是一个服务多个节点，选择了其他节点，也是有这个问题的。

那还是得走方案二，方案二得社区一起讨论一下，目前看看有没有参数把channel的心跳改长点吧，这个仅限于channel断开，到client还在跑prepare的情况吧

**Comment by lcmvs** [comment]
> > > > > > > 1.支持resourceid的自定义，来区分多个表 2.升级上次的方案，用分布式锁和分布式缓存，串行化branch的提交和二阶段下发的行为 你觉得哪个更合适，如果自定义resourceid的话，改动小，感觉也能接受，个人觉得可以支持前者，这样也不耦合其他组件
> > > > > > 
> > > > > > 
> > > > > > 我觉得方案一更加合适，而且xa模式既然hold住连接，我觉得不应该再选择其他的服务，而且同一个服务的其他实例也不应该选择吧？
> > > > > 
> > > > > 
> > > > > 好，我觉得你源码阅读的挺到位，仔细的，有没有兴趣认领下这个pr？
> > > > 
> > > > 
> > > > resourceid的自定义我没啥思路，seata很多地方我还不是很熟，我本来的想法是，tc提交或者回滚的时候判断一下是不是xa，xa就不去获取其他实例的channel了。
> > > 
> > > 
> > > 这个想法在以前是行得通，而现在都是跑在容器里，当一个容器销毁重建时，他的ip是会变的，这样将永远重试无法恢复。 你可以看下jdbcutils#initDataSourceResource 自己可以想下怎么做比较优雅，比如config.getConfig读一个配置，这个配置可以直接是appname之类的能代表这个服务的集群都是相同的即可 不过我突然想到，如果你的order有2个节点，一个运行时channel断了，是不是也请求到了另一个去？是否一样有这个问题？
> > 
> > 
> > 我的理解是一个服务多个节点，选择了其他节点，也是有这个问题的。
> 
> 那还是得走方案二，方案二得社区一起讨论一下，目前看看有没有参数把channel的心跳改长点吧，这个仅限于channel断开，到client还在跑prepare的情况吧

方案一不用服务名，用instance-id之类的东西也是可以的吧？

**Comment by a364176773** [comment]
问题梳理：
1.rm 进行 一阶段prepare操作时，网络抖动，channel断开
2.tm决议回滚
3.由于tc找不到第一步时的rmchannel，改用其他channel
4.其余channel由于第一个rm没进行end&prepare，导致找不到该xid的xa事务
5.认为此xa事务已完成，事务回滚成功
造成结果：
rm 1阶段完成后，资源悬挂

**Comment by lcmvs** [comment]
> 问题梳理： 1.rm 进行 一阶段prepare操作时，网络抖动，channel断开 2.tm决议回滚 3.由于tc找不到第一步时的rmchannel，改用其他channel 4.其余channel由于第一个rm没进行end&prepare，导致找不到该xid的xa事务 5.认为此xa事务已完成，事务回滚成功 造成结果： rm 1阶段完成后，资源悬挂

不仅仅是rollback会发生资源悬挂，commit也会
1.rm1完成一阶段
2.tm断开rm1的channel（rm1没挂，还持有数据库连接）
3.tm选择rm2的channel进行commit
4.发生XAException.XAER_NOTA异常，资源悬挂

**Comment by a364176773** [comment]
> > 问题梳理： 1.rm 进行 一阶段prepare操作时，网络抖动，channel断开 2.tm决议回滚 3.由于tc找不到第一步时的rmchannel，改用其他channel 4.其余channel由于第一个rm没进行end&prepare，导致找不到该xid的xa事务 5.认为此xa事务已完成，事务回滚成功 造成结果： rm 1阶段完成后，资源悬挂
> 
> 不仅仅是rollback会发生资源悬挂，commit也会 1.rm1完成一阶段 2.tm断开rm1的channel（rm1没挂，还持有数据库连接） 3.tm选择rm2的channel进行commit 4.发生XAException.XAER_NOTA异常，资源悬挂

prepard之后会上报一阶段，如果失败应该是直接回滚事务了，tm决议应该是rollback才对，为何会最终决议为commit？

**Comment by a364176773** [comment]
记错了,一阶段commit时不会进行一阶段提交,所以是有可能的,但是出现一阶段还在end还没走到prepare时就出现二阶段,还是要注意一点网络问题,先减少发生概率吧

**Comment by a364176773** [comment]
我又想了想，出现commit到分支事务还没走到prepare，导致其他rm找不到该xid,说明该分支重入了2次，1没做幂等导致分支进了2次，出现了服务重试，，所以tm认为没有调用时的timeout，2出现异常而tm捕获没抛出去，导致认为是提交而不是回滚

**Comment by lcmvs** [comment]
> 我又想了想，出现commit到分支事务还没走到prepare，导致其他rm找不到该xid,说明该分支重入了2次，1没做幂等导致分支进了2次，出现了服务重试，，所以tm认为没有调用时的timeout，2出现异常而tm捕获没抛出去，导致认为是提交而不是回滚

完成一阶段的那个数据库连接如果没有断开，就选择其他的数据库连接进行commit或者rollback，就会发生XAException.XAER_NOTA异常，资源悬挂。

**Comment by a364176773** [comment]
> > 我又想了想，出现commit到分支事务还没走到prepare，导致其他rm找不到该xid,说明该分支重入了2次，1没做幂等导致分支进了2次，出现了服务重试，，所以tm认为没有调用时的timeout，2出现异常而tm捕获没抛出去，导致认为是提交而不是回滚
> 
> 完成一阶段的那个数据库连接如果没有断开，就选择其他的数据库连接进行commit或者rollback，就会发生XAException.XAER_NOTA异常，资源悬挂。

之前的测试表示mysql在prepare后必须hold连接才可以使用，oracle就不必，不知道是否是版本导致的，你可以试试prepare后释放连接，看是否能正常commit

**Comment by lcmvs** [comment]
> > > 我又想了想，出现commit到分支事务还没走到prepare，导致其他rm找不到该xid,说明该分支重入了2次，1没做幂等导致分支进了2次，出现了服务重试，，所以tm认为没有调用时的timeout，2出现异常而tm捕获没抛出去，导致认为是提交而不是回滚
> > 
> > 
> > 完成一阶段的那个数据库连接如果没有断开，就选择其他的数据库连接进行commit或者rollback，就会发生XAException.XAER_NOTA异常，资源悬挂。
> 
> 之前的测试表示mysql在prepare后必须hold连接才可以使用，oracle就不必，不知道是否是版本导致的，你可以试试prepare后释放连接，看是否能正常commit

我自测用的是MySQL 5.7.24
prepare后，连接没有断开，使用另一个连接进行commit或rollback，就会发生XAER_NOTA异常
prepare后，连接断开，使用另一个连接进行commit或rollback，正常执行。

**Comment by a364176773** [comment]
> > > > 我又想了想，出现commit到分支事务还没走到prepare，导致其他rm找不到该xid,说明该分支重入了2次，1没做幂等导致分支进了2次，出现了服务重试，，所以tm认为没有调用时的timeout，2出现异常而tm捕获没抛出去，导致认为是提交而不是回滚
> > > 
> > > 
> > > 完成一阶段的那个数据库连接如果没有断开，就选择其他的数据库连接进行commit或者rollback，就会发生XAException.XAER_NOTA异常，资源悬挂。
> > 
> > 
> > 之前的测试表示mysql在prepare后必须hold连接才可以使用，oracle就不必，不知道是否是版本导致的，你可以试试prepare后释放连接，看是否能正常commit
> 
> 我自测用的是MySQL 5.7.24 prepare后，连接没有断开，使用另一个连接进行commit或rollback，就会发生XAER_NOTA异常 prepare后，连接断开，使用另一个连接进行commit或rollback，正常执行。

谢谢，这里我抽空也测一下，先把这个问题解决掉，或者你可以提个pr，让mysql在prepare后释放连接，我来review即可

**Comment by lcmvs** [comment]
> > > > > 我又想了想，出现commit到分支事务还没走到prepare，导致其他rm找不到该xid,说明该分支重入了2次，1没做幂等导致分支进了2次，出现了服务重试，，所以tm认为没有调用时的timeout，2出现异常而tm捕获没抛出去，导致认为是提交而不是回滚
> > > > 
> > > > 
> > > > 完成一阶段的那个数据库连接如果没有断开，就选择其他的数据库连接进行commit或者rollback，就会发生XAException.XAER_NOTA异常，资源悬挂。
> > > 
> > > 
> > > 之前的测试表示mysql在prepare后必须hold连接才可以使用，oracle就不必，不知道是否是版本导致的，你可以试试prepare后释放连接，看是否能正常commit
> > 
> > 
> > 我自测用的是MySQL 5.7.24 prepare后，连接没有断开，使用另一个连接进行commit或rollback，就会发生XAER_NOTA异常 prepare后，连接断开，使用另一个连接进行commit或rollback，正常执行。
> 
> 谢谢，这里我抽空也测一下，先把这个问题解决掉，或者你可以提个pr，让mysql在prepare后释放连接，我来review即可

要是一阶段每次都关闭数据库连接，应该会性能很差吧

**Comment by a364176773** [comment]
> > > > > > 我又想了想，出现commit到分支事务还没走到prepare，导致其他rm找不到该xid,说明该分支重入了2次，1没做幂等导致分支进了2次，出现了服务重试，，所以tm认为没有调用时的timeout，2出现异常而tm捕获没抛出去，导致认为是提交而不是回滚
> > > > > 
> > > > > 
> > > > > 完成一阶段的那个数据库连接如果没有断开，就选择其他的数据库连接进行commit或者rollback，就会发生XAException.XAER_NOTA异常，资源悬挂。
> > > > 
> > > > 
> > > > 之前的测试表示mysql在prepare后必须hold连接才可以使用，oracle就不必，不知道是否是版本导致的，你可以试试prepare后释放连接，看是否能正常commit
> > > 
> > > 
> > > 我自测用的是MySQL 5.7.24 prepare后，连接没有断开，使用另一个连接进行commit或rollback，就会发生XAER_NOTA异常 prepare后，连接断开，使用另一个连接进行commit或rollback，正常执行。
> > 
> > 
> > 谢谢，这里我抽空也测一下，先把这个问题解决掉，或者你可以提个pr，让mysql在prepare后释放连接，我来review即可
> 
> 要是一阶段每次都关闭数据库连接，应该会性能很差吧

何出此言?

**Comment by a364176773** [comment]
如果不关闭才是性能差的原因,一阶段hold连接,这个连接无法归还到连接池,并发量必定被连接池数量卡死

**Comment by lcmvs** [comment]
> 如果不关闭才是性能差的原因,一阶段hold连接,这个连接无法归还到连接池,并发量必定被连接池数量卡死

这样的话，其实在一阶段，抛异常时报告分支状态前关闭连接，和finally里面关闭连接，是不是能够规避资源悬挂的问题？

**Comment by a364176773** [comment]
> > 如果不关闭才是性能差的原因,一阶段hold连接,这个连接无法归还到连接池,并发量必定被连接池数量卡死
> 
> 这样的话，其实在一阶段，抛异常时报告分支状态前关闭连接，和finally里面关闭连接，是不是能够规避资源悬挂的问题？

个人觉得仅能改善，因为end和prepare不是一个原子动作，在end时，出现回滚去了其他rm回滚一样会找不到xa事务

**Comment by lcmvs** [comment]
> > > 如果不关闭才是性能差的原因,一阶段hold连接,这个连接无法归还到连接池,并发量必定被连接池数量卡死
> > 
> > 
> > 这样的话，其实在一阶段，抛异常时报告分支状态前关闭连接，和finally里面关闭连接，是不是能够规避资源悬挂的问题？
> 
> 个人觉得仅能改善，因为end和prepare不是一个原子动作，在end时，出现回滚去了其他rm回滚一样会找不到xa事务

prepare前断开连接，会释放资源。
既然释放资源了，其他rm执行回滚也无所谓了吧？也不会发生资源悬挂的问题。

**Comment by a364176773** [comment]
> > > > 如果不关闭才是性能差的原因,一阶段hold连接,这个连接无法归还到连接池,并发量必定被连接池数量卡死
> > > 
> > > 
> > > 这样的话，其实在一阶段，抛异常时报告分支状态前关闭连接，和finally里面关闭连接，是不是能够规避资源悬挂的问题？
> > 
> > 
> > 个人觉得仅能改善，因为end和prepare不是一个原子动作，在end时，出现回滚去了其他rm回滚一样会找不到xa事务
> 
> prepare前断开连接，会释放资源。 既然释放资源了，其他rm执行回滚也无所谓了吧？也不会发生资源悬挂的问题。

如果在prepare之前时候发起了回滚,其余rm帮忙回滚的时候找不到这个事务,不就悬挂了?

**Comment by a364176773** [comment]
我们昨晚讨论了下，目前觉得引入全局锁和缓存将prepare跟二阶段串行有点把简单问题复杂化了，目前我们准备做的方式是直接在tc端增加对xa分支的二阶段重试时长，比如一个branch悬挂了，那么1分钟的时间进行重试，很大几率就可以解决悬挂，如果是因为正常的rpc timeout，导致tc不知道二阶段状态，也可以在1分钟后停止重试，认为其已被正常回滚，不知道你怎么看？

**Comment by lcmvs** [comment]
> 大几率就可以解决

你的意思是发生rm出现XAER_NOTA异常，不直接当作已经完成二阶段，而是进行重试，tc尝试重试一分钟，一分钟以后才当作二阶段已经完成？

这样的话，其实我在想，rm在执行prepare前，判断一下执行时间是否大于1分钟，如果大于直接抛异常？

**Comment by a364176773** [comment]
> > 大几率就可以解决
> 
> 你的意思是发生rm出现XAER_NOTA异常，不直接当作已经完成二阶段，而是进行重试，tc尝试重试一分钟，一分钟以后才当作二阶段已经完成？
> 
> 这样的话，其实我在想，rm在执行prepare前，判断一下执行时间是否大于1分钟，如果大于直接抛异常进行回滚？

是的，你说的方式也可以，但是难免会有误判，我觉得可以本地超时+tc超时，这样缓解了tc要1分钟进行重试多次的问题，你有没有兴趣提个pr来做这块？不明白的可以问我，你把钉钉号发我邮箱，我加你 364176773@qq.com
