### ISSUE TITLE
1.4.2版本AT模式下，seata数据库的三张表（global_table、lock_table、branch_table）Debug过程中无任何数据

### ISSUE THREAD

**Issue by Surrin1999** [seata/seata#4142]
### Ⅰ. Issue Description
本问题与[issue#3673](https://github.com/seata/seata/issues/3673)的内容一致，是对此issue的补充
环境: Seata最新版本（1.4.2）、JDK1.8、SCA2021.1

    <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    </dependency>
    
    <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
        <exclusions>
            <exclusion>
                <groupId>io.seata</groupId>
                <artifactId>seata-spring-boot-starter</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>io.seata</groupId>
        <artifactId>seata-spring-boot-starter</artifactId>
        <version>1.4.2</version>
    </dependency>
当使用默认的AT模式时（其他模式没测试过），在debug过程中照理来说在这三个表中应该是有数据的，然而只发现在各个库的undo_log表中有数据。此外。。全局事务回滚功能是可以正常使用的，只是在debug过程中这三个表没有数据显得很奇怪
### Ⅱ. Describe what happened
下面放上涉及的各个数据库的图
![image](https://user-images.githubusercontent.com/37960540/142222580-29ecc2c7-310d-49b1-a2d3-d7acdce9190e.png)
下面是debug过程中，三个表中无数据的gif图，可以看到undo_log是有数据的，并且在某个分支事务发生了异常的情况下也能正常进行分布式事务回滚

![issue](https://user-images.githubusercontent.com/37960540/142224641-b7bc9a12-0d03-43d1-acc7-6caeddd3f60a.gif)

### Ⅲ. Describe what you expected to happen
debug过程中那三个表应该有记录分布式事务中各表信息

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.4.2
- OS : win11
- Spring Cloud Alibaba: 2021.1

**Comment by a364176773** [comment]
﻿https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo 
（上述demo内附1.3整合文字版）
1.3及以上通用教程: https://www.bilibili.com/video/BV1Cf4y1X7vR
说明tc用的可能还是file,多看几遍教程吧

**Comment by Surrin1999** [comment]
> https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo （上述demo内附1.3整合文字版） 1.3及以上通用教程: https://www.bilibili.com/video/BV1Cf4y1X7vR 说明tc用的可能还是file,多看几遍教程吧

写了那么大段就直接给我close了？？？能不能尊重下别人的贡献？？这个是我写的配置，哪里有问题？？
![image](https://user-images.githubusercontent.com/37960540/142231483-5b45571b-9094-4dcc-9a4f-4b7b6ceb6048.png)
![image](https://user-images.githubusercontent.com/37960540/142231515-d50d2e39-5624-4fca-998b-fa71f757ca21.png)

**Comment by a364176773** [comment]
我真是服了，张口闭口尊重，敢问你们尊重过写博客，写文档，写教程，录视频，在各大用户群答疑，issue，pr相关的贡献者，其他人跟着教程，文档都成功了，你的意思是说有bug？那有bug其他人怎么上生产的，出问题不先从自己身上找原因，张口闭口尊重，你的自尊很重要，其他人的就不重要了？你的时间很宝贵，其他人的时间不宝贵了？拜托，你自己学习，你自己折腾成长的是你，而无私，无形中帮助你的人，对他而言这早就已经轻车熟路了，毫无成长可言，如果你对技术还有一定的敬畏之心，请你保持好你的耐心，把文档和教程一字不漏的看清楚，如果你觉得文档写的太隐晦，你可以来贡献，而不是问一堆大家都已经成功了的问题，却保持着觉得这个是bug的心态，如果人人都来issues问重复性问题，入门级问题，而不是需要技术支持，反馈bug，功能探讨，那么要官网那么多文档何用？
