### ISSUE TITLE
A调用B  B插入数据后  A抛出异常 B插入的数据不会回滚 

### ISSUE THREAD

**Issue by lizilove** [seata/seata#4143]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
   用的seata-server版本1.4  客户端 1.4   demo用的seata-example  demo里面本身是order-server调用 stock-server  然后stock-server抛出异常，order-server发生回滚 这个没有问题  ，     我改写了逻辑为 order-server调用 stock-server插入数据  然后order-server再抛出异常，结果stock-server不会回滚 ， 断点查看undo_log也没有数据 

### Ⅱ. Describe what happened
改写之前的代码
![56fe8346765daaf44763316b1156376](https://user-images.githubusercontent.com/42531908/142370899-9d5a7434-1f5a-481b-87bf-7f8ab18b0fcc.png)

  改写之后的代码
![image](https://user-images.githubusercontent.com/42531908/142370850-44dbee53-1223-4751-b775-777362f1d7c2.png)

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4
- OS :
- Others:

**Comment by helang0616** [comment]
是不是因为你两边都写了@GlobalTransactional

**Comment by 303470934** [comment]
> 



> 是不是因为你两边都写了@GlobalTransactional

两边都写了@GlobalTransactional 才正确。我按照提问者的描述，同样的jdk和seata，复测了下，并没有发生不回滚的情况。请仔细检查下你的代码 。

**Comment by MrWangDage** [comment]
老哥们，我也是1.4.0  tcc模式    file配置   ,同样的问题，A.B  A异常  A回滚   B没有回滚，但是 B异常时，就可以全部回滚。 tcc不依赖undo.log，”救救我“

rm配置：
![image](https://user-images.githubusercontent.com/30967441/147661152-5e1350cd-26d7-47f6-87da-e8b84ba97c6c.png)
tm配置：
![image](https://user-images.githubusercontent.com/30967441/147661124-12fbd5e2-815c-41a6-92f7-216c8a86ca50.png)

当前场景下rm的日志：
![image](https://user-images.githubusercontent.com/30967441/147661256-9c5071fe-96d3-4b63-b6a2-11465a4e1143.png)
