### ISSUE TITLE
增加maven的描述信息

### ISSUE THREAD

**Issue by duansheli** [seata/seata#4145]
## current is 
https://mvnrepository.com/artifact/io.seata/seata-core/1.4.2 

![image](https://user-images.githubusercontent.com/8579595/142439374-32a4fb74-73a7-4afc-b422-44fcc09c87fd.png)

## hope like this

https://mvnrepository.com/artifact/redis.clients/jedis/3.7.0

![image](https://user-images.githubusercontent.com/8579595/142439045-f0e27746-d558-48eb-a78e-8922d630e662.png)

**Comment by slievrly** [comment]
@duansheli thanks for your feedback. Usually we use seata-all or seata-spring-boot-starter dependencies.

https://mvnrepository.com/artifact/io.seata/seata-all/1.4.2

![image](https://user-images.githubusercontent.com/8758457/142810845-999e61c4-bb85-41c3-9402-91ae04689128.png)
