### ISSUE TITLE
seata1.4.1版本启动出现链接不上的问题

### ISSUE THREAD

**Issue by yljcode1** [seata/seata#4148]
Unable to load authentication plugin 'caching_sha2_password'

**Comment by yljcode1** [comment]
以前都能启动，突然就出现这个问题了

**Comment by Pinocchio2018** [comment]
@yljcode1 能不能增加些情况描述呀。我在seata的代码里搜了搜caching_sha2_password，没什么结果啊

**Comment by a364176773** [comment]
如果之前能连上现在连不上了，应该自己排查一下，根据这个提示，如果你是mysql8，请保证配置了驱动是mysql8的

**Comment by yljcode1** [comment]
后面发现是驱动的原因，只要在seata的lib包下添加mysql8的驱动就可以了
