### ISSUE TITLE
1.4.2版本config使用nacos的dataId配置项不支持yml文件格式配置，文件名也不能使用中划线-隔开，例如seata-server.properties是不行的

### ISSUE THREAD

**Issue by wuhewei** [seata/seata#4150]
如题

**Comment by a364176773** [comment]
文件名不支持中划线隔开不是很明白是什么意思，yml会在1.5进行支持

**Comment by wuhewei** [comment]
好的，非常感谢回复，关于我设置dataId = "seata-server.properties"读取不到的问题，是因为group没配置对，个人操作问题。
@a364176773
