### ISSUE TITLE
多个调用中，GlobalTransation不生效

### ISSUE THREAD

**Issue by yljcode1** [seata/seata#4153]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
business服务调用order服务以及storage服务，在business服务TM上添加注解@GloabalTransaction,其中order服务又调用account服务来进行对account的修改，本身对order进行生成，在Order服务上添加注解@GloabalTransaction，当出现business服务出现异常时，account所操作的数据库并没用进行回滚，而其他的服务均进行回滚，导致全局事务不一致

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
如何解决这个服务调用服务这个问题

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.3.0
- OS :
- Others:

**Comment by Pinocchio2018** [comment]
是说的seata-samples吧？具体哪个demo呢？

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/143352757-a7e87fda-e0e7-4b82-be60-417afb037123.png)
如图debug排查

**Comment by yljcode1** [comment]
Communications link failure这个报错是说明没有代理数据源吗

**Comment by yljcode1** [comment]
是springcloud-seata-demo的一个项目

**Comment by a364176773** [comment]
> Communications link failure这个报错是说明没有代理数据源吗

要么就给出堆栈，就这个看不出来，你先debug这快代码

**Comment by yljcode1** [comment]
![image](https://user-images.githubusercontent.com/92766952/143371009-97ee30dc-2355-47ed-bbd5-b412632fff82.png)

**Comment by yljcode1** [comment]
我刚debug，在出错前有个库的undo_log文件没有生成记录，可能就是没有走代理数据源。
我后面手动配置数据proxy，他那边直接循环依赖了

**Comment by yljcode1** [comment]
![Uploading image.png…]()

**Comment by yljcode1** [comment]
![image](https://user-images.githubusercontent.com/92766952/143371421-e11bee45-9a54-4ae9-8d00-4ae18cd9392d.png)

**Comment by a364176773** [comment]
我觉得代理应该成功了，而是你xid传递有问题，由于你没有xid传递成功，导致每个globaltransational下都begin了个新的事务，导致某些回滚，某些没回滚，调用的入口加globaltransational，其余被调用的微服务接口不要加，直接debug看下rootcontext里有没有xid

**Comment by a364176773** [comment]
我发现你close了这个issue，方便的话请留下你的问题解决方案，以便帮助到更多相同问题的用户，谢谢
