### ISSUE TITLE
seata的调用使得出错

### ISSUE THREAD

**Issue by yljcode1** [seata/seata#4154]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/92766952/143387058-5bfc73cf-0169-4ba2-a3d6-01ec09148d1e.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
这个异常是mysql驱动抛出来的，不是seata
