### ISSUE TITLE
applicationId: null, txServiceGroup: null-seata-service-group

### ISSUE THREAD

**Issue by luopan1990911** [seata/seata#4160]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Error creating bean with name 'globalTransactionScanner' defined in class path resource [io/seata/spring/boot/autoconfigure/SeataAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: applicationId: null, txServiceGroup: null-seata-service-group 
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 启动项目就是提示applicationId: null, txServiceGroup: null-seata-service-group
2. 在windows系统上运行正常，windows上的jdk也是1.8.0

### Ⅵ. Environment:

- JDK version : jdk1.8.0_91
- Seata version:  1.4.2
- OS : MacOS Catalina
- Others: 在windows系统上运行正常

**Comment by a364176773** [comment]
https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo 
（上述demo内附1.3整合文字版）
Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt

升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR
