### ISSUE TITLE
使用canal监听能监听到抛异常前插入的数据和抛异常后回滚删除的数据

### ISSUE THREAD

**Issue by MumfordSons** [seata/seata#4170]
有啥办法解决吗

**Comment by tanzzj** [comment]
Seata的AT模式是在框架级做的全局事务，实际上TM/RM/TC的数据交互是数据库级别的，canal基于binlog进行数据同步，肯定是可以监听到全局事务未提交，但本地事务已经提交的消息

**Comment by MumfordSons** [comment]
> Seata的AT模式是在框架级做的全局事务，实际上TM/RM/TC的数据交互是数据库级别的，canal基于binlog进行数据同步，肯定是可以监听到全局事务未提交，但本地事务已经提交的消息

了解了，感谢。 所以同时使用这两框架有冲突。

**Comment by a364176773** [comment]
> > Seata的AT模式是在框架级做的全局事务，实际上TM/RM/TC的数据交互是数据库级别的，canal基于binlog进行数据同步，肯定是可以监听到全局事务未提交，但本地事务已经提交的消息
> 
> 了解了，感谢。 所以同时使用这两框架有冲突。

你可以使用tcc，saga或xa

**Comment by tanzzj** [comment]
> > Seata的AT模式是在框架级做的全局事务，实际上TM/RM/TC的数据交互是数据库级别的，canal基于binlog进行数据同步，肯定是可以监听到全局事务未提交，但本地事务已经提交的消息
> 
> 了解了，感谢。 所以同时使用这两框架有冲突。

其实不能说有冲突，回滚的log对canal来说肯定也能监听到，最终会一致

**Comment by MumfordSons** [comment]
> > > Seata的AT模式是在框架级做的全局事务，实际上TM/RM/TC的数据交互是数据库级别的，canal基于binlog进行数据同步，肯定是可以监听到全局事务未提交，但本地事务已经提交的消息
> > 
> > 
> > 了解了，感谢。 所以同时使用这两框架有冲突。
> 
> 你可以使用tcc，saga或xa

好的，我去了解下，谢谢

**Comment by MumfordSons** [comment]
> > > Seata的AT模式是在框架级做的全局事务，实际上TM/RM/TC的数据交互是数据库级别的，canal基于binlog进行数据同步，肯定是可以监听到全局事务未提交，但本地事务已经提交的消息
> > 
> > 
> > 了解了，感谢。 所以同时使用这两框架有冲突。
> 
> 其实不能说有冲突，回滚的log对canal来说肯定也能监听到，最终会一致

不好意思，表达的意思不够准确，主要是我这边项目中会有用到canal做些异步消息下发，如果是用at模式，就会导致异常前会提前下发消息
