### ISSUE TITLE
关于TCC fence的一些疑惑

### ISSUE THREAD

**Issue by SDuper** [seata/seata#4180]
看了下1.5.0-snapshot版本中，关于tcc的悬挂，空回滚，幂等的处理方式是采用的 tcc_fence_log表来解决的。但是还有几个疑惑的问题一直没想明白，想请教下。
1：prepare 方法 被包在了 transactionTemplate.execute方法中，如果发生异常，会被本地事务回滚，然后tcc_fence_log表中就没有对应的数据，导致rollback方法的时候，只会往 tcc_fence_log表中插入一条状态为：STATUS_SUSPENDED=4的记录。然后就结束了；
   这样感觉tcc模式就强依赖数据库的事务了，如果prepare 方法中有些redis之类的操作，本来发生异常时期望在rollback中做逆操作来恢复，但是用了fence之后，但凡能执行rollback的时候，tcc_fence_log都是没有对应记录的，不会执行业务方真正写在rollback方法中的逻辑了。是这样理解的吗？

2：定时器默认每天清理一次一天前的tcc_fence_log数据，目前看只清理2，3状态的数据，4状态的数据，就一直放库里存着吗？为什么不一并把4清理了？

3：
           transactionTemplate.execute(status -> {
               ....
            } catch (Throwable t) {
                status.setRollbackOnly();
                throw new SkipCallbackWrapperException(t);
            }
 调用status.setRollbackOnly() 是担心用户noRollbackFor SkipCallbackWrapperException这个异常，导致不回滚，而设置的吗？

**Comment by a364176773** [comment]
1.正常情况，做防止资源悬挂的措施，包括at也是插一条status=1的undolog来防止的
你要理解tcc是什么，1阶段预留资源，二阶段使用资源，所以本身就是利用了本地事务的特性来达到原子性和隔离性，你拿redis来举例是没用的，因为redis没用真正的事务，如何预留资源和使用资源呢，tcc是tcc，利用tcc一阶段空执行二阶段来插入redis数据，那只是利用，而不是真正的tcc
2.发生的记录较低，可以手动删，但是我觉得也可以清除，可以一起讨论下
3.以防万一作用

**Comment by a364176773** [comment]
redis，mongodb等不提供防悬挂功能，目前只支持数据库

**Comment by SDuper** [comment]
好的，知道了，感谢答疑！
