### ISSUE TITLE
被SpringBootConfigurationProvider代理的FileConfiguration怎么刷新配置

### ISSUE THREAD

**Issue by wanglaomo** [seata/seata#4181]
## Why you need it?
spring-boot-starter中FileConfiguration被SpringBootConfigurationProvider代理，当我想要刷新Seata配置时（eg：关闭全局事务），我发现是没有入口的。

**Comment by a364176773** [comment]
目前是无法刷新的,建议通过专门的配置中心来处理

**Comment by wanglaomo** [comment]
修改io.seata.spring.boot.autoconfigure.properties下的Properties类，通过FileListener的onChangeEvent，可以实现类似动态刷新的效果，这种方法推荐吗？

**Comment by a364176773** [comment]
> 修改io.seata.spring.boot.autoconfigure.properties下的Properties类，通过FileListener的onChangeEvent，可以实现类似动态刷新的效果，这种方法推荐吗？

可以改源码,刷新application-xxx.yml或properties,或者特定文件,或者spi扩展自己的配置中心
