### ISSUE TITLE
Data remanence problems in lock and branch under specific circumstances

### ISSUE THREAD

**Issue by lvekee** [seata/seata#4182]
## Why you need it?
Data remanence is known to occur in the following cases
1.After lock acquisition the machine goes down，the lock data will remain
2.When the lock is obtained, the TC phase II rollback happens when the branch is registered, and the lock and branch will remain
If you want to fix it, please comment "Please assign it to me" is this issue.

已知在以下情况会发生数据残留
1.lock获取到宕机，将残留lock数据
2.lock获取到，branch注册时刚好出现tc二阶段回滚，将残留lock和branch
如果你有兴趣修复这个问题的话, 请在下方留言 Please assign it to me

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by objcoding** [comment]
Please assign it to me

**Comment by a364176773** [comment]
此问题仅出现再网络不稳定或tc宕机的极端情况下，但是需要有一个兜底的处理，欢迎大家在此讨论或认领该任务
This problem only occurs in extreme situations where the network is unstable or the service is down, but there needs to be a way to deal with it, and everyone is welcome to discuss or receive this task here

**Comment by objcoding** [comment]
Please assign it to me
