### ISSUE TITLE
用达梦数据库feign调用时，一直报这个错误：io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder

### ISSUE THREAD

**Issue by Bourne1314** [seata/seata#4185]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
the error happening when I using DM databse through feign to operation my data in DM database达梦数据库;
io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
nested exception is org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder] with root cause

io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder
```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
如何引入的？

**Comment by Bourne1314** [comment]
多谢，是引入错误。多谢啦。开发者人美心善。

**Comment by halower** [comment]
@Bourne1314 我也是DM 出现一个问题了，感觉没有配置错误，2022-11-10 08:55:12.669 ERROR 10876 --- [nio-9092-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder] with root cause

**Comment by Bourne1314** [comment]
你用的版本应该没有适配seata、你需要去官方钉钉群里寻求开发者的版本支持。好像是#3572issue

**Comment by windqg** [comment]
我的应用连接Kingbase金仓数据库也报这个错：io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder 是啥原因？连接MySQL是没问题的。

**Comment by Bourne1314** [comment]
你好，应该是seata版本不对，有个branch版本是可以的。可以具体到issue里面查一下。或用最新版本，看他们发布的更新日志应该已经适配了。
&nbsp;


张招君
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月30日(星期一) 中午1:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/incubator-seata] 用达梦数据库feign调用时，一直报这个错误：io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder (Issue #4185)














 
我的应用连接Kingbase金仓数据库也报这个错：io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder 是啥原因？连接MySQL是没问题的。

**Comment by HalleyLi** [comment]
> 我的应用连接Kingbase金仓数据库也报这个错：io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder 是啥原因？连接MySQL是没问题的。

你好，请问你解决了嘛，我们现在连接Kingbase也是同一个错误

**Comment by HalleyLi** [comment]
> 该是seata版本不对

你好，请问是哪个版本是可以正常work的呢
