### ISSUE TITLE
> 关掉了，是解决了么，我是只用了@GlobalTransactional。

### ISSUE THREAD

**Issue by Green524** [seata/seata#4194]
> 关掉了，是解决了么，我是只用了@GlobalTransactional。
> 代码大致如下：
> `
> //1调用A服务
> 
> //2本地修改
> 
> //3调用B服务
> 
> `
> 然后项目报错：io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = **********:8091:97709006117621760 status = AsyncCommitting, cause by globalSession not active] ]
> 
> seata报错：io.seata.core.exception.GlobalTransactionException: Could not register branch into global session xid = **********:8091:97710984377880576 status = AsyncCommitting, cause by globalSession not active

我也想知道怎么解决

_Originally posted by @junjiex123 in https://github.com/seata/seata/issues/3176#issuecomment-768115104_

**Comment by Green524** [comment]
解决了吗

**Comment by a364176773** [comment]
不是bug,官网faq
