### ISSUE TITLE
事务提交后，查询到的数据仍然是未提交之前的数据，多次查询之后，就能查到更新后的数据

### ISSUE THREAD

**Issue by tiantiankexiao** [seata/seata#4200]
### Ⅰ. Issue Description
在做退款功能时，事务使用了本地事务@Transactional注解。一开始我查询到的退款单是待退款状态(如果是其他状态会抛异常)，然后进行了一系列操作。最后将退款单修改为退款成功状态，在代码执行期间使用了分布式锁。

当前端连续发送同一请求的时候，第一次事务执行完毕，第二次执行代码发现查询该退款单还是待退款状态(应该是退款完成状态才对)，第三次依旧如此，直到有一次查询到的退款单是退款完成状态

但是当事务使用@GlobalTransactional 注解时，就不会出现上述情况。代码第一次执行之后，第二次执行查询到的退款单就是退款完成的状态。
整个操作并不涉及多个库的分布式事务，为什么会发生上述情况？

### Ⅵ. Environment:

- JDK version :  1.8.0_181
- Seata version: 1.3.0  
- OS :  windows
- Others: springcloud alibaba 2.2.6.RELEASE

**Comment by a364176773** [comment]
seata没有对事务隔离级别做强制设置，你也没用globaltransational去发起事务，不会对你业务有任何影响，跟seata无关

**Comment by tiantiankexiao** [comment]
确实与seata无关,感谢你的回复
