### ISSUE TITLE
Why run with branch type saga, the field status of global_table is began when the transaction is finish?

### ISSUE THREAD

**Issue by mengzhigang** [seata/seata#4205]
写了个测试项目，跑了下saga模式，存储都是mysql存储，
1.  结果是第一次能正确跑完的，第二次的时候报io.seata.core.exception.BranchTransactionException: Global lock acquire failed xid ...
2.  global_table里的事务的状态时1，是begain状态，重新启动项目的时候，疯狂重试。研究一个星期都没整明白
3.  我看DefaultCoordinator里有个DefaultCore，我随便翻翻便找到个SagaCore，我尝试替换了下，结果client端报xid为null空指针，持续懵逼

希望大佬能帮我解惑，膜拜大佬：）

**Comment by mengzhigang** [comment]
This is the image when SagaCore replace DefaultCore.
![截屏2021-12-14 下午6 19 47](https://user-images.githubusercontent.com/37127400/145980968-81788b5d-6a83-40cc-9e63-b9cb17afab08.png)
![截屏2021-12-14 下午6 20 46](https://user-images.githubusercontent.com/37127400/145981015-b71d2fd1-526c-4287-bbb8-3985af0a3885.png)

**Comment by a364176773** [comment]
saga模式记得关闭数据源自动代理,如果你依赖的seata-all 请不要手动代理

**Comment by mengzhigang** [comment]
听了大佬的意见，在我本地测试成功了，但在项目上又出现了问题
项目上自己拿到了sqlSessionFactory做commit操作，然后跑去做branchregister，结果上锁失败，好像是往lock表里插数据的时候失败。
