### ISSUE TITLE
Could not found global transaction xid = %s, may be has finished

### ISSUE THREAD

**Issue by anonymous-lj** [seata/seata#4211]
使用jmeter本地测试时，并发数越高越容易复现，出现xid找不到情况
![image](https://user-images.githubusercontent.com/54050325/146354295-8dc0e1ec-ceeb-4d9b-9446-92bf35a3315f.png)

官方文档FAQ26，提出来的可能原因，已经确认过是没有的，A调用B、C两个服务，只是简单的数据插入
1. 未发生超时异常
2. B、C服务未发生异常，但是B、C服务会出现请求TC找不到xid情况
3. 单节点与多节点TC一样会复现，不存在时区导致异常
4. com.alibaba.cloud.seata.web.SeataHandlerInterceptor的afterCompletion在断点过程RootContext.getXID()一直是null，也不是绑定未清除

而且TC会爆出如下异常
![image](https://user-images.githubusercontent.com/54050325/146355476-bd836220-2c7d-4d69-90d3-c000a7b62c0e.png)

**Comment by anonymous-lj** [comment]
依赖配置如下

**Comment by anonymous-lj** [comment]
依赖配置如下
seata-spring-boot-starter 1.4.2
spring-cloud-starter-alibaba-seata 2.2.7.RELEASE
![image](https://user-images.githubusercontent.com/54050325/146356397-da215b91-637d-4c14-89b8-2d36b54e852c.png)

代码逻辑如下
![image](https://user-images.githubusercontent.com/54050325/146356489-9257c121-9aea-4732-8bdd-3ec2a98397d4.png)
![image](https://user-images.githubusercontent.com/54050325/146356517-5c000aeb-ca51-4620-b5b0-a4643e9b951a.png)
![image](https://user-images.githubusercontent.com/54050325/146356567-34fd4d6e-1c97-4045-b188-7b9bca6096f9.png)

nacos配置如下
#设置db模式
store.mode=db
#配置数据库配置
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.jdbc.Driver
store.db.url=jdbc:mysql://xxxxx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B0&rewriteBatchedStatements=true
store.db.user=xxxx
store.db.password=xxx
store.db.minConn=5
store.db.maxConn=30
store.db.maxWait=5000
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.lockTable=lock_table
store.db.queryLimit=100
#client和server通信编解码方式	
transport.serialization=seata
#client和server通信数据压缩方式
transport.compressor=none
#client和server通信心跳检测开关
transport.heartbeat=true
#服务端配置
server.undo.logSaveDays=7
server.undo.logDeletePeriod=86400000
server.maxCommitRetryTimeout=-1
server.maxRollbackRetryTimeout=-1
server.recovery.committingRetryPeriod=1000
server.recovery.asynCommittingRetryPeriod=1000
server.recovery.rollbackingRetryPeriod=1000
server.recovery.timeoutRetryPeriod=1000
metrics.enabled=true
metrics.registryType=compact
metrics.exporterList=prometheus
metrics.exporterPrometheusPort=9898
#客户端配置
service.vgroupMapping.framework_tx_group=default
service.disableGlobalTransaction=false
transport.enableClientBatchSendRequest=true
client.log.exceptionRate=100
client.tm.degradeCheck=false
client.tm.degradeCheckAllowTimes=10
client.tm.degradeCheckPeriod=3000
client.rm.reportSuccessEnable=false
client.rm.asynCommitBufferLimit=10000
client.rm.lock.retryInterval=10
client.rm.lock.retryTimes=30
client.rm.lock.retryPolicyBranchRollbackOnConflict=true
client.rm.reportRetryCount=5
client.rm.tableMetaCheckEnable=false
client.tm.commitRetryCount=5
client.tm.rollbackRetryCount=5
client.undo.dataValidation=true
client.undo.logSerialization=jackson
client.undo.logTable=undo_log

**Comment by a364176773** [comment]
官网faq

**Comment by anonymous-lj** [comment]
如果是框架内可预测的事件导致了全局事务被删 TC端应该能打印出对应日志吧 可是TC端没发现关于被这条异常XID被删除的日志

**Comment by anonymous-lj** [comment]
![image](https://user-images.githubusercontent.com/54050325/146515298-216ba808-784d-45a5-a26f-9b44fda05dfd.png)

**Comment by anonymous-lj** [comment]
这条xid 总耗时才320ms 已有的答案验证过才来找你们的 无奈
![image](https://user-images.githubusercontent.com/54050325/146516191-5e19eed3-db51-4fcf-9621-8086f9caf10e.png)

**Comment by anonymous-lj** [comment]
数据库读写分离导致

**Comment by a364176773** [comment]
> 数据库读写分离导致

我记得官网有说不要用读写分离的

**Comment by zxdelete1** [comment]
大佬，找到原因了吗

**Comment by chengshihard** [comment]
大佬，找到原因了吗

**Comment by shinebigfool** [comment]
我提一个可能的比较蠢的原因，我的两个微服务连的不是一个seata集群，会报这种错
