### ISSUE TITLE
Seata为什么自称为高性能?

### ISSUE THREAD

**Issue by menghuan123** [seata/seata#4214]
Seata为什么自称为高性能? 能总结一下哪里实现是高性能吗？

**Comment by a364176773** [comment]
https://blog.funkye.icu/2020/10/09/seata-at-xa/

**Comment by menghuan123** [comment]
> 
没有看到哪里有高性能的体现,后期会有undoLog压缩的规划,大佬有seata为了实现高性能做了哪些优化的文档吗？

**Comment by a364176773** [comment]
都全面解析对比了传统分布式事务XA了，还不明白为什么高性能吗？
undolog压缩1.4.2已经有了，提升了大量数据修改时undolog的读取和插入效率
redis模式提升了计算与存储分离下的性能
AT解析，一阶段提前释放本地锁，二阶段决议提交时释放全局锁，无需将数据锁定持续到二阶段结束，这里就已经相对传统二阶段事务尤其是XA提升了，TCC XA 都需要二阶段驱动，而AT模式在二阶段决议提交时分布式事务就已经完成了，无需再次驱动rm进行二阶段动作
这些都是细节，你能看仔细理解吗？

**Comment by menghuan123** [comment]
> 

可以的,感谢大佬解答
