### ISSUE TITLE
mysql数据库的undo_log表 

### ISSUE THREAD

**Issue by Heuan** [seata/seata#4219]
1.mysql数据库的undo_log表 什么版本去掉了自增主键的，1.4.2试过会报缺少id
2.mysql 插入undo_log 会出现 Lock wait timeout exceeded，它的自增主键已经到了id=216500614769430529

**Comment by a364176773** [comment]
问题1不存在，所以问题2不存在

**Comment by a364176773** [comment]
请确保没有版本依赖冲突和重复代理数据源
