### ISSUE TITLE
使用Redis保存事务日志,seata是如何保证Redis和本地事务执行的一致的？

### ISSUE THREAD

**Issue by menghuan123** [seata/seata#4225]
使用Redis保存事务日志,seata是如何保证Redis和本地事务执行的一致的？

**Comment by a364176773** [comment]
undolog不由redis存储
tc支持redis存储模式，但在tc意外宕机下，有几率出现脏数据，因为redis本身就没有真正意义上的事务支持

**Comment by menghuan123** [comment]
> tc支持redis存储模式，但在tc意外宕机下，有几率出现脏数据，因为redis本身就没有真正意义上的事务支持

是的,我看到全局锁也有redis lua的实现,redis在极端场景还是会存在丢失数据的可能性,这里为了高性能还是会存在一致性的风险

**Comment by a364176773** [comment]
> > tc支持redis存储模式，但在tc意外宕机下，有几率出现脏数据，因为redis本身就没有真正意义上的事务支持
> 
> 是的,我看到全局锁也有redis lua的实现,redis在极端场景还是会存在丢失数据的可能性,这里为了高性能还是会存在一致性的风险

是的，可以理解为为了高性能，而容忍一致性风险，在之前的测试中，redis模式在秒杀模拟压测，及200条数据随机下单扣库存的测试中，大幅度领先db模式
之后我们会考虑大量采用lua脚本的形式去处理，让一致性完全交给redis服务，而非seata，虽然redis的lua脚本的原子性和事务的原子性并不相同，但是这样风险会降低很多
