### ISSUE TITLE
 Please check the cluster status. 

### ISSUE THREAD

**Issue by nanfangyoumeng-an** [seata/seata#4226]
set nacosAddr=127.0.0.1:8848
set group=SEATA_GROUP
 Please check the cluster status. 

所有配置都确认无误

**Comment by a364176773** [comment]
让你检查的应该是nacos，自己手动去nacos上挨个录入也是个办法

**Comment by nanfangyoumeng-an** [comment]
> 让你检查的应该是 nacos，自己手动去 nacos 上挨个录入也是个办法

这个nacos-config.sh有版本问题吗？默认部署的seata没有这个文件，需要从GitHub上pull一个文件下来，然后运行这个sh文件出了异常

**Comment by a364176773** [comment]
> 

Please check the cluster status 你自己可以打开这个脚本看下为什么会输出Please check the cluster status,一般就是由于你上面配置nacos地址之类的不正确才输出的,看下script下这个脚本所在位置的readme

**Comment by BLEACHIN** [comment]
手动在dos界面试下如下命令：
》curl -X POST http://127.0.0.1:1111/nacos/v1/cs/configs?dataId=transport.type&group=SEATA_GROUP&content=TCP&tenant=&username=nacos&password=nacos

没返回true就是没执行成功。

在nacos前端界面——》配置列表 手动新增配置，看下是否成功

没成功的话，看下nacos连的mysql是否是5.6或5.7的，若是5.5，则升级下mysql数据库到5.6或5.7。
