### ISSUE TITLE
Can't rollback because of length of tinyint

### ISSUE THREAD

**Issue by Sivyer9303** [seata/seata#4229]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
In one globaltransaction,there are three operation,when some excpetion occur.only two operation rollback.
the operation not rollback is contains tinyint changes.
It is treated as a boolean type by seata because of its length equals 1.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
tinyint can be treated as int.
maybe it need a configuration to adapt

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. create a table with column that its tinyint and length equal 1.
2. invoke a global transaction.
3. rollback this transaction

### Ⅵ. Environment:

- JDK version : JDK8 
- Seata version:   1.4.1
- OS : linux
- Others:

**Comment by Sivyer9303** [comment]
sry.I have finded the same issue.

**Comment by wangliang181230** [comment]
@Sivyer9303 bugfix by https://github.com/seata/seata/pull/6068
