### ISSUE TITLE
高并发压测时，会低概率出现死锁现象

### ISSUE THREAD

**Issue by zxbu** [seata/seata#4230]
压测条件：8个线程，每个分布式事务跨3个服务，大概有4个分支事务。 大概有万分之一概率在分布式事务二阶段commit时，协调器出现死锁。 
而且一旦死锁，TM是不会处理的，故业务代码正常执行，但过了一分钟，协调器检查死锁会做超时回滚操作，导致业务数据莫名奇妙被回滚

我自己分析的死锁的原因是：
1. 分支事务commit后，协调器会执行 releaseLock 操作，执行的SQL类似： `delete from lock_table where xid = '10.244.127.44:8091:2071867764324439688' and branch_id = 2071867764324439800` 
2. 全局事务 commit后，协调器会执行  releaseGlobalSessionLock 操作，执行的SQL类型：`delete from lock_table where xid = '10.244.127.44:8091:2071867764324439688' and branch_id in (2071867764324439719,2071867764324439743,2071867764324439775,2071867764324439800)`

在高并发的情况下，这种sql会出现死锁

我计划这么解决：
分支事务commit后，不再执行 releaseLock  操作，等到TM 二阶段commit时，执行releaseGlobalSessionLock 时，依然可以正常释放。

请问我的猜测正确吗？是否有没顾及到的地方？

**Comment by a364176773** [comment]
如果数据库默认是可重复读，试试改为读已提交，可重复读级别的间隙锁，有可能会引起死锁

**Comment by zxbu** [comment]
> 如果数据库默认是可重复读，试试改为读已提交，可重复读级别的间隙锁，有可能会引起死锁

我不是太精通DB。但这种情况应该不是间隙锁，是主键导致的死锁。 
这是已知问题吗？ 感觉应该挺常见的

**Comment by a364176773** [comment]
> > 如果数据库默认是可重复读，试试改为读已提交，可重复读级别的间隙锁，有可能会引起死锁
> 
> 我不是太精通DB。但这种情况应该不是间隙锁，是主键导致的死锁。 这是已知问题吗？ 感觉应该挺常见的

1步骤的时候已经提交事务了，才走到步骤2，如何引起死锁？这是串行不是并行
先咨询dba看下seata所用数据库是否是rr隔离级别如果是，改成rc在测试

**Comment by zxbu** [comment]
![image](https://user-images.githubusercontent.com/32785355/147331092-ed182619-b9b6-47de-a4e5-0e1557140223.png)
这是当时的事务日志
步骤1和步骤2的执行时序应该不能严格保证吧？ 
我改成rc再试一下吧，但感觉不像是这个原因
@a364176773

**Comment by a364176773** [comment]
> 

同个事务下严格保证,因为是串行的,不同事务下,比如事务1执行了releaseLock 事务二也在执行releaseGlobalLock ,可能就是因为间隙锁死锁了,非唯一索引就会引起间隙锁产生,先改成rc在压测看看吧,自行也可以搜索下innodb 间隙锁死锁的一些案例和原理
