### ISSUE TITLE
全局事务没了，分支事务和全局锁依然存在

### ISSUE THREAD

**Issue by tuwenlin** [seata/seata#4232]
1.5.0版本，某一个分支事务做分支事务注册时，由于网络波动的原因，抛出了RPCTimeout异常，随后进行了全局回滚，回滚过程中网络正常，全局事务和已经注册的分支事务被成功remove了，在全局事务被remove之前，分支事务的注册请求到达TC了，全局锁写入成功，分支事务注册成功，并且在判断全局事务事务存在之后，成功注册分支事务之前，由于全局回滚的原因，全局事务被remove了，导致这个注册成功的分支事务和锁没有了全局事务，这条数据一直被全局锁锁住

**Comment by a364176773** [comment]
这个问题存在，而且也有具体的issue，后续会通过unlock条件为xid的形式来释放全局锁或者延迟globalsession的delete时间，来确认是否还有其他的branchsession为处理

**Comment by tuwenlin** [comment]
> 这个问题存在，而且也有具体的issue，后续会通过unlock条件为xid的形式来释放全局锁或者延迟globalsession的delete时间，来确认是否还有其他的branchsession为处理

好的，那我把这个issue关闭吧

**Comment by a364176773** [comment]
可以留着,后续我会进行兜底处理

**Comment by objcoding** [comment]
https://github.com/seata/seata/issues/4182

**Comment by Bughue** [comment]
> 

请问一下，这个问题在1.4.2会存在吗

**Comment by tuwenlin** [comment]
> > 
> 
> 请问一下，这个问题在1.4.2会存在吗

存在的，#4233 已经解决

> > 
> 
> 请问一下，这个问题在1.4.2会存在吗

**Comment by tuwenlin** [comment]
> > 
> 
> 请问一下，这个问题在1.4.2会存在吗

存在这个问题，#4233已经解决
