### ISSUE TITLE
使用了seata代理了数据源后  从数据库查出的某些字段为null  控制台显示回滚成功  但是数据库也没回滚

### ISSUE THREAD

**Issue by Leryoo** [seata/seata#4234]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened
数据库版本用的8.0 seata版本用的是1.1.0
 从数据库查出的某些字段为null 
![image](https://user-images.githubusercontent.com/46736410/147431104-2cac8bb5-5d11-45cd-8c5d-5f00bfb57f1f.png)

 而且 远程调用其他服务进行修改的时候  控制台和终端都显示了回滚成功过  但是数据库里面也没有回滚  log表里面也没有数据
![image](https://user-images.githubusercontent.com/46736410/147431582-281020b7-93eb-46c8-8e59-1dcbc396c177.png)
![image](https://user-images.githubusercontent.com/46736410/147431695-3f6902a9-c468-4f0a-a0f2-842ec9b3184e.png)

配置文件file.conf
![image](https://user-images.githubusercontent.com/46736410/147431961-ed615aa7-ae29-4dc8-8ec9-3bc4903b3989.png)

第一次用这些 求大佬指教

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.10
- Nacos :1.4.2
- Others:

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/147432655-dec69453-6d89-40e2-8a6e-6613c8beb204.png)
Seata整合1.2教程: https://www.bilibili.com/video/BV12Q4y1A7Nt

升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR
https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo 
（上述demo内附1.3整合文字版）
