### ISSUE TITLE
optimize request: optimize the lock logic when before image is empty

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#4236]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
for now, when acquire lock, seata will check whether the global lock has been holded by other global transaction. but for insert or part of insert ignore into(may be more), if the before image is empty, it means that the target rows is not exists when the current global transaction execute, so it can skip check lock and acquire lock directly.

当前Seata在执行acquire lock之前，都需要去检查当前的全局锁是否被其他全局事物持有。但是对于insert into或者部分的insert ignore into的操作，如果before image是空的，那也就意味着当前需要操作的行不存在的，也就不存在说当前的全局锁被其他全局事物所持有。因此当before image是空的时候，我们可以跳过check lock的步骤，直接执行插入全局锁即可。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information
it can do base on the #3733

**Comment by a364176773** [comment]
good issue

**Comment by Pinocchio2018** [comment]
```java
package io.seata.server.lock;

public abstract class AbstractLockManager implements LockManager {

    @Override
    public boolean acquireLock(BranchSession branchSession) throws TransactionException {
        if (branchSession == null) {
            throw new IllegalArgumentException("branchSession can't be null for memory/file locker.");
        }
        String lockKey = branchSession.getLockKey();
        if (StringUtils.isNullOrEmpty(lockKey)) {
            // no lock
            return true;
        }
        // get locks of branch
        List<RowLock> locks = collectRowLocks(branchSession);  // if doing insert , skip check lock
        if (CollectionUtils.isEmpty(locks)) {
            // no lock
            return true;
        }
        return getLocker(branchSession).acquireLock(locks);
    }

```
指的是这里吧？
