### ISSUE TITLE
Seata压测性能

### ISSUE THREAD

**Issue by menghuan123** [seata/seata#4242]
seata 生产有人进行过压测吗?不加事务和加分布式事务,性能差异比是多少?

**Comment by zhangxiangfeng** [comment]
30%左右

**Comment by jianchengfeng** [comment]
同等资源，TCC模式在A B 两个服务分别加钱和减钱简单场景下，一组测试数据，仅供阅读
<img width="662" alt="压测-修改" src="https://user-images.githubusercontent.com/10721613/154423361-956e759e-eb33-460e-ba47-a67fd893310c.png">

**Comment by jingshanglu** [comment]
关于 seata 的性能，有官方的测试报告吗？AT 模式，1.4.2 版本，seata server 单节点，file 存储模式，两个分支事务，200 并发，TPS 3000 +， RT 160+ms, 不知道这个结果是否符合预期？
