### ISSUE TITLE
k8s 容器中偶尔出现链接被重置

### ISSUE THREAD

**Issue by Brainhu** [seata/seata#4244]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
k8s 容器部署 server1.4.2 偶尔会出现 connection reset by peer 

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
08:13:56.092  WARN --- [ettyServerNIOWorker_1_1_2] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
==>
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
<==
```

### Ⅲ. Describe what you expected to happen

希望没有异常警告
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

k8s 配置按官网高可用

### Ⅴ. Anything else we need to know?
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: seata-ha-server
  name: seata-ha-server
  namespace: devops
  resourceVersion: '87282061'
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: seata-ha-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2021-12-06T21:21:34+08:00'
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: seata-ha-server
    spec:
      containers:
        - env:
            - name: SEATA_CONFIG_NAME
              value: 'file:/root/seata-config/registry'
          image: 'docker.io/seataio/seata-server:latest'
          imagePullPolicy: IfNotPresent
          name: seata-ha-server
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/seata-config
              name: seata-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: seata-ha-server-config
          name: seata-config

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: seata-ha-server
  name: seata-ha-server
  namespace: devops
  resourceVersion: '87279049'
spec:
  clusterIP: 10.96.228.11
  clusterIPs:
    - 10.96.228.11
  ports:
    - name: http
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app.kubernetes.io/name: seata-ha-server
  sessionAffinity: None
  type: ClusterIP

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.2
- OS : 
- Others:

**Comment by Brainhu** [comment]
> * [ ]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
> 
> ### Ⅰ. Issue Description
> k8s 容器部署 server1.4.2 偶尔会出现 connection reset by peer
> 
> ### Ⅱ. Describe what happened
> If there is an exception, please attach the exception trace:
> 
> ```
> An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
> ==>
> 08:13:56.092  WARN --- [ettyServerNIOWorker_1_1_2] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
> ==>
> java.io.IOException: Connection reset by peer
>         at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_212]
>         at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_212]
>         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_212]
>         at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_212]
>         at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_212]
>         at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
>         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
> <==
> ```
> 
> ### Ⅲ. Describe what you expected to happen
> 希望没有异常警告
> 
> ### Ⅳ. How to reproduce it (as minimally and precisely as possible)
> k8s 配置按官网高可用
> 
> ### Ⅴ. Anything else we need to know?
> apiVersion: apps/v1 kind: Deployment metadata: annotations: {} labels: app.kubernetes.io/name: seata-ha-server name: seata-ha-server namespace: devops resourceVersion: '87282061' spec: progressDeadlineSeconds: 600 replicas: 3 revisionHistoryLimit: 10 selector: matchLabels: app.kubernetes.io/name: seata-ha-server strategy: rollingUpdate: maxSurge: 25% maxUnavailable: 25% type: RollingUpdate template: metadata: annotations: kubectl.kubernetes.io/restartedAt: '2021-12-06T21:21:34+08:00' creationTimestamp: null labels: app.kubernetes.io/name: seata-ha-server spec: containers: - env: - name: SEATA_CONFIG_NAME value: 'file:/root/seata-config/registry' image: 'docker.io/seataio/seata-server:latest' imagePullPolicy: IfNotPresent name: seata-ha-server ports: - containerPort: 8091 name: http protocol: TCP resources: {} terminationMessagePath: /dev/termination-log terminationMessagePolicy: File volumeMounts: - mountPath: /root/seata-config name: seata-config dnsPolicy: ClusterFirst restartPolicy: Always schedulerName: default-scheduler securityContext: {} terminationGracePeriodSeconds: 30 volumes: - configMap: defaultMode: 420 name: seata-ha-server-config name: seata-config
> 
> apiVersion: v1 kind: Service metadata: annotations: {} labels: app.kubernetes.io/name: seata-ha-server name: seata-ha-server namespace: devops resourceVersion: '87279049' spec: clusterIP: 10.96.228.11 clusterIPs: - 10.96.228.11 ports: - name: http port: 8091 protocol: TCP targetPort: 8091 selector: app.kubernetes.io/name: seata-ha-server sessionAffinity: None type: ClusterIP
> 
> ### Ⅵ. Environment:
> * JDK version : 1.8
> * Seata version:  1.4.2
> * OS :
> * Others:

补充配置：
registry {
    type = "file"
}
config {
  type = "nacos"
  nacos {
    serverAddr = "ip:port"
    group = "SEATA_GROUP"
    namespace = "seata-dev"
  }
}

**Comment by slievrly** [comment]
@Brainhu From the current information cannot determine the root cause.
