### ISSUE TITLE
Mac m1 Arm架构编译seata--->serializer--->seata-serializer-protobuf报错

### ISSUE THREAD

**Issue by kingylhq** [seata/seata#4245]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata-serializer-protobuf编译报错，protobuf插件也装过试了还是不可以，还尝试过用 osx-x86_64强导入也不可以！

### Ⅱ. Describe what happened

[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project seata-serializer-protobuf: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.3.0
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.3.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.3.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]   	1) io.seata:seata-serializer-protobuf:jar:1.4.2
[ERROR]   	2) com.google.protobuf:protoc:exe:osx-aarch_64:3.3.0
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   io.seata:seata-serializer-protobuf:jar:1.4.2
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   alimaven (http://maven.aliyun.com/nexus/content/groups/public/, releases=true, snapshots=false)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen

可以修改导入jar或者其他的方式能正常编译

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?

直接启动 seata下的server报错  java: 程序包io.seata.serializer.protobuf.generated不存在

### Ⅵ. Environment:

- JDK version :  oracle jdk1.8
- Seata version:  1.4.2
- OS : Mac M1 max
- Others:

**Comment by GoodBoyCoder** [comment]
参考官网[FAQ](https://seata.io/zh-cn/docs/overview/faq.html#11)

**Comment by lay-g** [comment]
settings 里面 profiles 标签内添加：
```
    <profile>
      <id>x86</id>
      <properties>
        <os.detected.classifier>osx-x86_64</os.detected.classifier>
      </properties>
    </profile>
```
命令：`mvn package ... -Px86`
或者settings里面添加：
```
  <activeProfiles>
    <activeProfile>x86</activeProfile>
  </activeProfiles>
```

**Comment by a364176773** [comment]
2020 mac air路过，没有问题

**Comment by doubleDimple** [comment]
Execute the following Maven command under the project root path：
./mvnw clean install -DskipTests=true
