### ISSUE TITLE
[Feature]: Realize the interface of console: get global lock in the file mode

### ISSUE THREAD

**Issue by lightClouds917** [seata/seata#4258]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
1.实现file模式下，控制台中获取全局锁的接口。
原型图：https://github.com/seata/seata/discussions/4217
接口文档：[#4195](https://github.com/seata/seata/issues/4195)
2.注意：需要实现分页功能

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by miaoxueyu** [comment]
Please assign it to me
