### ISSUE TITLE
[Feature]: Realize the interface of console: get global session in the redis mode

### ISSUE THREAD

**Issue by lightClouds917** [seata/seata#4261]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
1.实现redis模式下，控制台中获取全局事务列表的接口。
原型图：#4217
接口文档：#4195
2.注意：需要实现分页功能

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by doubleDimple** [comment]
I claim this issue. Please assign it to me
