### ISSUE TITLE
optimize build UndoItem logic

### ISSUE THREAD

**Issue by caohdgege** [seata/seata#4280]
## Why you need it?
The under codes, it will query after image even the affected rows == 0.

如下代码，即使受影响条数==0的时候，也会在SQL执行完成之后去查询后镜像，但是这是一个无意义的操作。

```java
    protected T executeAutoCommitFalse(Object[] args) throws Exception {
        if (!JdbcConstants.MYSQL.equalsIgnoreCase(getDbType()) && isMultiPk()) {
            throw new NotSupportYetException("multi pk only support mysql!");
        }
        TableRecords beforeImage = beforeImage();
        T result = statementCallback.execute(statementProxy.getTargetStatement(), args);
        TableRecords afterImage = afterImage(beforeImage);
        prepareUndoLog(beforeImage, afterImage);
        return result;
    }
```

## How it could be?

when the affected rows==0, just return the result without doing somethings else.
当受影响条数==0的时候，可以立即返回，而不需要继续执行构建后镜像等操作。

## Other related information

requirement: a pr to optimize & add the test case
要求：pr中需要包含代码优化以及对应的测试用例的补充

If you want to optimize it, please comment "Please assign it to me" in this issue.
如果有兴趣优化的，可以在下方留言please assign it to me

**Comment by xiaochangbai** [comment]
Please assign it to me
