### ISSUE TITLE
consul注册地址配置问题

### ISSUE THREAD

**Issue by shz940724** [seata/seata#4290]
当用consul作为seata的注册中心事,在springboot的配置文件里配置seata信息seata.config.consul.server-addr时为什么会自动多拼接了一个默认的8500端口,例如配置:seata.config.consul.server-addr: 127.0.0.1:8888,那么到consul读取配置时的地址会变成127.0.0.1:8888:8500这样,导致地址错误读取失败

**Comment by slievrly** [comment]
@shz940724 Pls provide the version information.

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/153348438-0100f835-215d-4b3a-9f06-0f2681d57e1d.png)
Please explain how to reproduce.
