### ISSUE TITLE
sh seata-server.sh -p 8091 -h 127.0.0.1 -m db   why goes wrong?

### ISSUE THREAD

**Issue by SpriderMan** [seata/seata#4291]
![image](https://user-images.githubusercontent.com/18304842/149299455-5d2cc4eb-aaf9-40f0-a579-8e5dc463d322.png)

**Comment by a364176773** [comment]
检查你的store.db.datasource是否配置了值为druid，hikari，dbcp 3选一

**Comment by pengten** [comment]
datasource可能没配置

**Comment by pengten** [comment]
like this
![image](https://user-images.githubusercontent.com/30648785/149307991-1936550f-6c90-4e18-942c-07b2afb60922.png)

**Comment by SpriderMan** [comment]
![image](https://user-images.githubusercontent.com/18304842/149323761-f2f028b8-5d85-49e5-a6bd-534454a80355.png)

**Comment by SpriderMan** [comment]
sh seata-server.sh为什么没有使用这个文件？
![Uploading image.png…]()

**Comment by SpriderMan** [comment]
sh seata-server.sh为什么没有使用这个文件file.conf？

**Comment by a364176773** [comment]
> sh seata-server.sh为什么没有使用这个文件file.conf？

你的配置中心配置成了zk，那么就不会读取file.conf
