### ISSUE TITLE
seata_server三张表以及业务undo_log表没数据

### ISSUE THREAD

**Issue by Shmily-candy** [seata/seata#4301]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

spring cloud nacos + mp整合seata后 被调用方发生异常,调用方收到异常，提示:

rollback status: Finished

但是sever端三张表没数据、undo_log表debug的时候也没记录，请问是什么原因?
spring cloud版本:Hoxton.SR9
nacos discivery/config 版本:2.2.6.RELEASE
seata相关:
<dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.4.2</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2.2.6.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by miaoxueyu** [comment]
分布式事务完整结束掉后，这些都是会被删除掉的。可以在业务逻辑中加个断点去看看

**Comment by Shmily-candy** [comment]
全程都是 加了断点的

**Comment by Shmily-candy** [comment]
都是debug跟进的

**Comment by miaoxueyu** [comment]
那你用的应该不是DB模式,可以检查下

**Comment by Shmily-candy** [comment]
刚刚又跟了一下  只有global_table有数据 会自动清理掉

**Comment by kk1234kk4321** [comment]
> 分布式事务完整结束掉后，这些都是会被删除掉的。可以在业务逻辑中加个断点去看看

我也是加了断点没有数据，很奇怪
