### ISSUE TITLE
mybatisplus->InnerInterceptor 改sql表前缀，undo_log定位不到此前缀的数据库

### ISSUE THREAD

**Issue by tanzhong1** [seata/seata#4313]
业务日志： INSERT INTO lt_order_private_long_test_yns.lt_visit_skill_config  ( content, create_time )  VALUES  ( ?,? )；

[ERROR] [XNIO-1 task-14] [io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit:224] - process connectionProxy commit error: Table 'lt_order_public.undo_log' doesn't exist

原因： 之前本来也是 INSERT INTO lt_order_public_yns.这样的，由于我做了sql的动态修改，改成了上面的业务日志模样，然而我不知道seata怎么也相应的改成这个库前缀去， 官方文档里面 我没能看到有效的信息，所以想请问一下 开发团队 有无办法 ？ 
![085c1cdbbf8c17cf886a1756e1c145e](https://user-images.githubusercontent.com/48664798/149929214-feb121a0-8549-4dbe-8bdc-c8f82f58dec3.png)
![1642505382(1)](https://user-images.githubusercontent.com/48664798/149929415-457a7a33-2fd3-4dec-a869-538df8aa7570.jpg)

**Comment by pengten** [comment]
原sql是。 INSERT INTO It_order_public.xxxxxxx
你动态修改成了 INSERT INTO lt_order_private_long_test_yns.xxxxxxx

是这个意思？

**Comment by pengten** [comment]
intercepter实现可以贴下

**Comment by tanzhong1** [comment]
可以加你微信，或者qq 具体详聊吗？

-->intercepter : 

@Configuration
@ConditionalOnWebApplication(type = SERVLET)
public class SeataConfig implements WebMvcConfigurer {

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new SeataHandlerInterceptor());
    }

}

--> 配置信息：
![1643008088(1)](https://user-images.githubusercontent.com/48664798/150737244-dc53eae2-1a5b-42a2-9eb7-91142479922e.jpg)

![1643008133(1)](https://user-images.githubusercontent.com/48664798/150737349-157ebbc2-3b75-46dd-aaa2-6b15df71a5d7.jpg)
 
--.> 主动调用方
![1643008188(1)](https://user-images.githubusercontent.com/48664798/150737460-c060c21c-afac-4ed1-bccc-8259d25cf1b3.jpg)


--> feign被调用方： 

![1643008303(1)](https://user-images.githubusercontent.com/48664798/150737707-fbb04ad9-3bcb-4b2d-b60a-b87f3e3000b3.jpg)

**Comment by pengten** [comment]
没看到你改表名的代码呢

**Comment by caohdgege** [comment]
这个东西看起来是你的动态数据源的问题。

seata的undo_log表是跟DataSource挂钩的，然后DataSource在jdbc连接的时候就已经指定了schema(即你的lt_order_private_long_test_yns和lt_order_public应该要是两个DataSource才对的)。然后你在这里的TableNameInterceptor看情况是只修改了表名，并没有使用lt_order_private_long_test_yns的DataSource，因此也就没有找到对应的undo_log表。

**Comment by tanzhong1** [comment]
谢谢大佬们的反馈，已经解决了
