### ISSUE TITLE
No documentation found about some configuration parameters

### ISSUE THREAD

**Issue by jxl4650152** [seata/seata#4319]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
No description about some configurations found in documentation, i.e. `store.session.mode` `store.lock.mode`.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
Add missing documentation on some configuration parameters.

**Comment by a364176773** [comment]
Can you supplement the relevant documentation for us? Please submit https://github.com/seata/seata.github.io here
