### ISSUE TITLE
undo_log表中字段rollback_info内容出现乱码

### ISSUE THREAD

**Issue by lbj812** [seata/seata#4329]
字符集：utf8
undo_log表中字段rollback_info内容出现乱码
![image](https://user-images.githubusercontent.com/30791781/150713841-d2c21caf-6993-4f70-bf3b-0f85c3ded051.png)

**Comment by a364176773** [comment]
能说下里面原内容是什么吗？

**Comment by lbj812** [comment]
![image](https://user-images.githubusercontent.com/30791781/150714350-5c183b34-3475-4e20-aefd-96563b77c627.png)

**Comment by slievrly** [comment]
只是显示乱码，还是无法回滚。如果只是显示，执行下 set names utf8;

**Comment by SeaOtterZX** [comment]
你好，我也出现了类似的问题，请问你的解决了吗？我是Flowable工作流里的一些表回滚时，里面有中文，导致乱码，回滚报错
