### ISSUE TITLE
能否优化下linux启动脚本，脚本无法后台挂起，每个人都要改一遍，这也太麻烦了

### ISSUE THREAD

**Issue by zxiaozhou** [seata/seata#4334]
## Why you need it?
 能否优化下启动脚本，脚本无法后台挂起，，想要后台挂起要么运行前加nohup,,要么就修改脚本。每个人都要去弄一次，太麻烦了。。可以参考nacos的启动脚本。。。

**Comment by a364176773** [comment]
develop下已经改了
