### ISSUE TITLE
decode data file error when server upgrade

### ISSUE THREAD

**Issue by slievrly** [seata/seata#4337]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

server: 1.4.2 -> develop

![image](https://user-images.githubusercontent.com/8758457/150943958-9afd76fc-3f81-4c15-a1cd-fb108d256f7f.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
我pr里修了
