### ISSUE TITLE
[optimize]when tcc commit/rollback do nothing 

### ISSUE THREAD

**Issue by liucaijin** [seata/seata#4338]
## Why you need it?
 TCC commit or rollback maybe do nothing sometime。Can add annotation let don't be called。
 TCC 的 commit和rollback有时会是执行一个空操作，但是每次都会调用，可以通过注解标识它不被调用吗？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by objcoding** [comment]
是因为悬挂和空回滚的问题，1.5版本有防悬挂挂功能，你可以看下官网博客：
https://seata.io/zh-cn/blog/seata-tcc.html

**Comment by slievrly** [comment]
It does not conform to the design idea of TCC transaction mode.
