### ISSUE TITLE
Can fescar work without fescar-server?

### ISSUE THREAD

**Issue by TenzeTseng** [seata/seata#435]
## Why you need it?
I want to integrate fescar into my project, but I don't want to start fescar-server.

## How it could be?
It would be better to have a LocalServer like RpcServer.

## Other related information

**Comment by slievrly** [comment]
@TenzeTseng Currently not supported, but it is actually supported

**Comment by lovepoem** [comment]
[Another decentralization question] When I used fescar-server in my business project . If the fescar-server service group is down , how can  
 I ensure the business project  run well  temporarily ?

**Comment by slievrly** [comment]
Distributed transactions cannot be executed if all servers in the cluster are hung. Distributed transaction degradation is automatically done by the number of errors in the time period. For an implementation without a server, the business database is also required to hold the transaction record and lock state of the transaction. Similarly, the distributed transaction of the database does not work properly.

**Comment by skyesx** [comment]
@TenzeTseng have a look at EasyTransaction, there's something you want

**Comment by leizhiyuan** [comment]
because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
