### ISSUE TITLE
develop分支无法打成jar包

### ISSUE THREAD

**Issue by TimLang** [seata/seata#4356]
mvn package -DskipTests

报如下错误：

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact io.seata:seata-dependencies:pom:1.5.0-SNAPSHOT @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 35, column 25
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-context:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 329, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-core:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 333, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-beans:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 337, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-aop:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 341, column 21
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-webmvc:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 345, column 21
[ERROR] 'dependencies.dependency.version' for io.netty:netty-all:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 350, column 21
[ERROR] 'dependencies.dependency.version' for org.antlr:antlr4:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 354, column 21
[ERROR] 'dependencies.dependency.version' for com.alibaba:fastjson:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 358, column 21
[ERROR] 'dependencies.dependency.version' for com.alibaba:druid:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 362, column 21
[ERROR] 'dependencies.dependency.version' for com.typesafe:config:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 366, column 21
[ERROR] 'dependencies.dependency.version' for org.slf4j:slf4j-api:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 370, column 21
[ERROR] 'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 374, column 21
[ERROR] 'dependencies.dependency.version' for commons-lang:commons-lang:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 379, column 21
[ERROR] 'dependencies.dependency.version' for org.apache.commons:commons-pool2:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 383, column 21
[ERROR] 'dependencies.dependency.version' for commons-pool:commons-pool:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 387, column 21
[ERROR] 'dependencies.dependency.version' for com.google.protobuf:protobuf-java:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 391, column 21
[ERROR] 'dependencies.dependency.version' for org.apache.dubbo:dubbo:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 396, column 21
[ERROR] 'dependencies.dependency.version' for com.alibaba:dubbo:jar is missing. @ io.seata:seata-all:${revision}, /Users/lang/eclipse-workspace/seata/all/pom.xml, line 401, column 21

**Comment by TimLang** [comment]
在all文件夹下

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/overview/faq.html
