### ISSUE TITLE
saga模式会有防悬挂功能吗

### ISSUE THREAD

**Issue by Bughue** [seata/seata#4368]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
saga模式可能会碰到类似tcc的悬挂问题，是否有解决方案？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
希望saga模式能有防悬挂的功能

**Comment by slievrly** [comment]
currently not support.

**Comment by long187** [comment]
防悬挂实际上在业务上做是最好的，因为业务上始终是要保存流水的。同时saga模式目前设计的前提假设是兼容遗留系统，也就是说服务提交方并没有接入seata客户端，所以实际上是做不到上面提到的那种防悬挂。

**Comment by Bughue** [comment]
> 防悬挂实际上在业务上做是最好的，因为业务上始终是要保存流水的。同时saga模式目前设计的前提假设是兼容遗留系统，也就是说服务提供方并没不需要接入seata客户端，所以实际上是做不到上面提到的那种防悬挂。

是的，我们分析了一轮之后也觉得还是业务做比较好。
