### ISSUE TITLE
db/redis mode must be thread-safe when changing the transaction state

### ISSUE THREAD

**Issue by a364176773** [seata/seata#4372]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
db/redis模式需串行更改事务状态,假设事务A在tm端进行决议提交，此时到达了tc端，而tc端刚好发现这个事务达到了超时，就会更改状态为超时回滚，而这两个动作是并行的，导致决议提交时删除了全局锁，又恰好被改为超时回滚，导致分支事务被回滚，回滚时可能会发现数据已经无法对上了（全局锁被删了）

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
1.redis可使用锁+读+改的方式或lua脚本来保证原子性修改
2.db模式可以使用乐观锁形式，updatestatus时，必须现在的status是当前globalsession的status否则要失败
有其他更好的方案欢迎讨论

**Comment by Bughue** [comment]
please assign it to me

**Comment by pengten** [comment]
其实是不是参照file，扩展两个加锁的策略就行了

**Comment by Bughue** [comment]
> 其实是不是参照file，扩展两个加锁的策略就行了

你说的是仿照FileTransactionStoreManager，在writeSession里面直接加一个对应的分布式锁吗？我想过这个方式，但是这样似乎防止不了互相覆盖，假如commit线程去更新完成才发生rollback线程去更新的话，commit的时候执行成功了也往下走，rollback的时候执行成功也往下走。最终数据还是会不一致。
我现在也算是在扩展加锁的策略，但思路是拿到global的预期状态（begin），然后往下传到writeSession，再在这里面用乐观锁的方式去更新global的表，成功的往下走，不成功的抛异常。你看看我的方案有没有什么问题？或者还有什么建议不？

**Comment by pengten** [comment]
> > 其实是不是参照file，扩展两个加锁的策略就行了
> 
> 你说的是仿照FileTransactionStoreManager，在writeSession里面直接加一个对应的分布式锁吗？我想过这个方式，但是这样似乎防止不了互相覆盖，假如commit线程去更新完成才发生rollback线程去更新的话，commit的时候执行成功了也往下走，rollback的时候执行成功也往下走。最终数据还是会不一致。 我现在也算是在扩展加锁的策略，但思路是拿到global的预期状态（begin），然后往下传到writeSession，再在这里面用乐观锁的方式去更新global的表，成功的往下走，不成功的抛异常。你看看我的方案有没有什么问题？或者还有什么建议不？

我是指在 SessionHolder.lockAndExecute 里面，加全局锁。   以前对file是有实现的，db/redis没有实现，所以目前db/redis就会存在并发修改问题。   但是如果这里加全局锁，相当于并行改串行，会一定程度影响吞吐；总觉得这块逻辑导致file和db/redis的行为不一致，使得事务行为和存储有一定的耦合。
