### ISSUE TITLE
大神，fescar能否进入生产环境

### ISSUE THREAD

**Issue by c8439** [seata/seata#438]
fescar能否进入生产环境

**Comment by slievrly** [comment]
Please wait for the 1.0 release

**Comment by xianwei** [comment]
> Please wait for the 1.0 release

1.0大概什么时间会发布啊。

**Comment by slievrly** [comment]
> > Please wait for the 1.0 release
> 
> 1.0大概什么时间会发布啊。

Expected in late May

**Comment by wwftw** [comment]
English please

**Comment by yuchonghua** [comment]
I am looking forward to the release of fescar 1.0 and expect fescar to be more compatible with spring boot and spring cloud.

**Comment by yuchonghua** [comment]
I am very much looking forward to the release of fescar 1.0.

> Finished up some issues related to fescar and spring boot, spring cloud

----

>* https://github.com/alibaba/fescar/issues/587
>* https://github.com/alibaba/fescar/issues/33#issuecomment-453407106
>* https://github.com/alibaba/fescar/pull/684
>* https://github.com/alibaba/fescar/issues/683
>* https://github.com/alibaba/fescar/issues/636#issue-423317954
>* https://github.com/alibaba/fescar/pull/573
>* https://github.com/alibaba/fescar/issues/549
>* https://github.com/alibaba/fescar/issues/52#issuecomment-470096685
>* https://github.com/alibaba/fescar/issues/221
>* https://github.com/alibaba/fescar/issues/303#issuecomment-458044383
>* https://github.com/alibaba/fescar/issues/350#issuecomment-465479755
>* https://github.com/alibaba/fescar/issues/31#issuecomment-453343440
>* https://github.com/alibaba/fescar/issues/166
>* https://github.com/alibaba/fescar/issues/163#issuecomment-455396312
>* https://github.com/alibaba/fescar/issues/557
>* https://github.com/alibaba/fescar/issues/646#issuecomment-475967368
>* https://github.com/alibaba/fescar/issues/641#issuecomment-475542774
>* https://github.com/alibaba/fescar/issues/527
>* https://github.com/alibaba/fescar/issues/486
>* [Spring boot example](https://github.com/alibaba/fescar/pull/281)、https://github.com/alibaba/fescar/issues/59
>* https://github.com/alibaba/fescar/issues/181#issue-400829908
>* https://github.com/alibaba/fescar/issues/252#issuecomment-457126923

---

I am very much looking forward to the release of fescar 1.0.

**Comment by slievrly** [comment]
come soon

**Comment by leizhiyuan** [comment]
after 1.0 released, we will notify everyone

duplicate as https://github.com/seata/seata/issues/932, I will close the issue, if you have other questions, please reopen it or create a new one
