### ISSUE TITLE
tc-server 已经启动，为什么会报 io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server ？

### ISSUE THREAD

**Issue by SpriderMan** [seata/seata#4381]
tc-server 已经启动，为什么会报 io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server ？

![image](https://user-images.githubusercontent.com/18304842/154016558-6582c5bb-1acc-4581-88cd-e924c0b57d9a.png)

**Comment by a364176773** [comment]
检查自己应用跟172.16.20.96:8091的网络通不通
