### ISSUE TITLE
大佬，关于retryPolicyBranchRollbackOnConflict=false的疑问

### ISSUE THREAD

**Issue by SpriderMan** [seata/seata#4384]
![image](https://user-images.githubusercontent.com/18304842/154205599-70f4bfc1-45f8-4d88-b15f-2c99256166be.png)

有个疑问，如果事务分支a 和事务分支b，如果在执行事务分支b的时候获取全局锁失败的话，那如果应该重新完整地从@Globaltransational的TM端重新发起的话，那事务分支a还要再重新执行一遍？ 还是全局回滚后在重新tm发起执行事务a和事务b？

**Comment by pengten** [comment]
@SpriderMan 这个开关只会重新获取全局锁，并不会重新执行事务逻辑。
