### ISSUE TITLE
docker 启动设置 SEATA_IP 在注册中心不生效

### ISSUE THREAD

**Issue by Mike-Acb** [seata/seata#4392]
## Why you need it?
注册中心的ip 还是。容器的IP。。。。没读取到SEATA_IP 里面的ip ,好像是--cgroupns private 的原因，

## How it could be?

https://github.com/seata/seata/blob/a38b8736e4b0ceb844fe3efbee190de8a56b054d/server/src/main/java/io/seata/server/ParameterParser.java#L72   里面判断/proc/1/cgroup 容器是否在运行，

但是进入容器里面cat是 **0::/**  

参考：https://stackoverflow.com/questions/69002675/on-debian-11-bullseye-proc-self-cgroup-inside-a-docker-container-does-not-sho
--cgroupns host 在run 的时候设置这个 可以解决。。。。。

## Other related information
1. 本地启动 redis 注册中心 
2. clone https://github.com/Mike-Acb/seata
2. 路径下运行

```shell
docker run --name seata-server  \
  -p 8091:8091 \
  -e SEATA_IP=192.168.1.1 \
  -e SEATA_PORT=8091 \
  -e SEATA_CONFIG_NAME=file:/root/seata-config/registry_test \
  -v $PWD:/root/seata-config  \
  -d  seataio/seata-server:1.4.2
```

本地redis  运行  得到注册的IP 和上面 SEATA_IP=192.168.1.1 不一致。。使用啦容器的 IP

```shell
redis-cli HGETALL registry.redis.default 
```

OS: mac 11.2.3
Docker Engine v20.10.12

**Comment by liuqiufeng** [comment]
please assign it to me

**Comment by luodaoyi** [comment]
这个问题在1.42的docker 镜像中依然存在 每次用docker-compose部署 都会得到内网的ip
按照上面的提示 改成docker命令启动 貌似解决了这个问题了

```bash
docker run --rm --name seata-server  --cgroupns host \
  -p 8091:8091 \
  -e SEATA_IP=192.168.99.11 \
  -e SEATA_CONFIG_NAME=file:/root/registry.conf \
  -e STORE_MODE=db \
  -v /opt/seata/data/:/root/  \
  -d  seataio/seata-server:1.4.2

```

**Comment by guoshuaiping** [comment]
> 这个问题在1.42的docker 镜像中依然存在 每次用docker-compose部署 都会得到内网的ip 按照上面的提示 改成docker命令启动 貌似解决了这个问题了
> 
> ```shell
> docker run --rm --name seata-server  --cgroupns host \
>   -p 8091:8091 \
>   -e SEATA_IP=192.168.99.11 \
>   -e SEATA_CONFIG_NAME=file:/root/registry.conf \
>   -e STORE_MODE=db \
>   -v /opt/seata/data/:/root/  \
>   -d  seataio/seata-server:1.4.2
> ```

此方案确实可行，感谢大佬分享~

**Comment by 320187240** [comment]
da

> > 这个问题在1.42的docker 镜像中依然存在 每次用docker-compose部署 都会得到内网的ip 按照上面的提示 改成docker命令启动 貌似解决了这个问题了
> > ```shell
> > docker run --rm --name seata-server  --cgroupns host \
> >   -p 8091:8091 \
> >   -e SEATA_IP=192.168.99.11 \
> >   -e SEATA_CONFIG_NAME=file:/root/registry.conf \
> >   -e STORE_MODE=db \
> >   -v /opt/seata/data/:/root/  \
> >   -d  seataio/seata-server:1.4.2
> > ```
> 
> 此方案确实可行，感谢大佬分享~
有人知道是什么原因吗，或者后续的版本中正常吗？
