### ISSUE TITLE
docker镜像里有log4j-1.2.17.jar

### ISSUE THREAD

**Issue by carllhw** [seata/seata#4404]
```bash
~ docker run -ti --rm --entrypoint sh seataio/seata-server:1.4.2
/seata-server # ls -l /seata-server/libs/ | grep log4j
-rw-r--r--    1 root     root        489884 Jan  1  1970 log4j-1.2.17.jar

~ docker run -ti --rm --entrypoint sh seataio/seata-server:latest
# ls -l /seata-server/libs/ | grep log4j
-rw-r--r-- 1 root root  489884 Jan  1  1970 log4j-1.2.17.jar
-rw-r--r-- 1 root root  292301 Jan  1  1970 log4j-api-2.13.3.jar
-rw-r--r-- 1 root root   17461 Jan  1  1970 log4j-to-slf4j-2.13.3.jar
```

https://logging.apache.org/log4j/1.2/index.html

log4j 1.2 已经不再维护且有很多漏洞

**Comment by pengten** [comment]
感觉这三个jar都移除？ @a364176773

**Comment by a364176773** [comment]
> 感觉这三个jar都移除？ @a364176773

经测试是
```
 <groupId>com.101tec</groupId>
            <artifactId>zkclient</artifactId>
```
里面带的,理论上不适用zk做注册中心和配置中心,不会有影响,seata自身日志采用logback
你可以帮忙测试一下排除掉
```
            <exclusions>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
```
zk作为seata的注册中心是否能正常使用,如果可以的话,就直接排除,如果不行,为了保证有用户可以正常使用seata-server暴露到zk中,目前就不能排除

**Comment by pengten** [comment]
> > 感觉这三个jar都移除？ @a364176773
> 
> 经测试是
> 
> ```
>  <groupId>com.101tec</groupId>
>             <artifactId>zkclient</artifactId>
> ```
> 
> 里面带的,理论上不适用zk做注册中心和配置中心,不会有影响,seata自身日志采用logback 你可以帮忙测试一下排除掉
> 
> ```
>             <exclusions>
>                 <exclusion>
>                     <groupId>log4j</groupId>
>                     <artifactId>log4j</artifactId>
>                 </exclusion>
>             </exclusions>
> ```
> 
> zk作为seata的注册中心是否能正常使用,如果可以的话,就直接排除,如果不行,为了保证有用户可以正常使用seata-server暴露到zk中,目前就不能排除

I will try it
