### ISSUE TITLE
logTable 配置不生效

### ISSUE THREAD

**Issue by zclcs** [seata/seata#4413]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/50291896/155939944-5f2a281a-716b-4636-a8e6-648e7f09b80b.png)

### Ⅱ. Describe what happened

启动获取变量正常，删除sql执行的是默认的

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by GoodBoyCoder** [comment]
请提供一下seata版本以及配置log table的方式方便排查，此外确认一下配置的undolog表中是否有数据

**Comment by zclcs** [comment]
> 请提供一下seata版本以及配置log table的方式方便排查，此外确认一下配置的undolog表中是否有数据

seata版本 1.4.2 
![image](https://user-images.githubusercontent.com/50291896/155943069-3e260f78-84c3-4b23-bff6-9441a51ef5ce.png)
![image](https://user-images.githubusercontent.com/50291896/155943113-4213493d-0f90-485b-891e-f105e28f148c.png)

**Comment by liuqiufeng** [comment]
配置中心为nacos，seata相关的配置应该放到nacos上吧？

**Comment by zclcs** [comment]
> 配置中心为nacos，seata相关的配置应该放到nacos上吧？

是放在nacos上的，为了方便截图，我取下来了

**Comment by liuqiufeng** [comment]
> > 配置中心为nacos，seata相关的配置应该放到nacos上吧？
> 
> 是放在nacos上的，为了方便截图，我取下来了

nacos配置时带seata前缀吗？如果是，请尝试去掉seata前缀试试。如：client.undo.logTable=undo_log

**Comment by zclcs** [comment]
> > > 配置中心为nacos，seata相关的配置应该放到nacos上吧？
> > 
> > 
> > 是放在nacos上的，为了方便截图，我取下来了
> 
> nacos配置时带seata前缀吗？如果是，请尝试去掉seata前缀试试。如：client.undo.logTable=undo_log

1. nacos这样配报错，也获取不到日志表表名
![image](https://user-images.githubusercontent.com/50291896/156086622-68dc518f-16ea-4766-94bf-d8d9fdddaef7.png)
2. nacos这样配，能获取到表名，但是执行sql表名还是不对
![image](https://user-images.githubusercontent.com/50291896/156086963-4640acb0-2108-4aaf-a7c7-678fdb3c4075.png)

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/156088621-0c500266-5dee-4f7e-88ef-409d5ee3e5cc.png)
seata 用的druid连接池老是报这个，大佬们知道咋去掉嘛

**Comment by liuqiufeng** [comment]
> > > > 配置中心为nacos，seata相关的配置应该放到nacos上吧？
> > > 
> > > 
> > > 是放在nacos上的，为了方便截图，我取下来了
> > 
> > 
> > nacos配置时带seata前缀吗？如果是，请尝试去掉seata前缀试试。如：client.undo.logTable=undo_log
> 
> 1. nacos这样配报错，也获取不到日志表表名
>    ![image](https://user-images.githubusercontent.com/50291896/156086622-68dc518f-16ea-4766-94bf-d8d9fdddaef7.png)
> 2. nacos这样配，能获取到表名，但是执行sql表名还是不对
>    ![image](https://user-images.githubusercontent.com/50291896/156086963-4640acb0-2108-4aaf-a7c7-678fdb3c4075.png)

那我也不知道了，我是菜鸟，哈哈。debug看看吧

**Comment by zclcs** [comment]
> > > > > 配置中心为nacos，seata相关的配置应该放到nacos上吧？
> > > > 
> > > > 
> > > > 是放在nacos上的，为了方便截图，我取下来了
> > > 
> > > 
> > > nacos配置时带seata前缀吗？如果是，请尝试去掉seata前缀试试。如：client.undo.logTable=undo_log
> > 
> > 
> > 
> > 1. nacos这样配报错，也获取不到日志表表名
> >    ![image](https://user-images.githubusercontent.com/50291896/156086622-68dc518f-16ea-4766-94bf-d8d9fdddaef7.png)
> > 2. nacos这样配，能获取到表名，但是执行sql表名还是不对
> >    ![image](https://user-images.githubusercontent.com/50291896/156086963-4640acb0-2108-4aaf-a7c7-678fdb3c4075.png)
> 
> 那我也不知道了，我是菜鸟，哈哈。debug看看吧

dubug 配置项有值，所以我才来提issues

**Comment by liuqiufeng** [comment]
> 
貌似是这里取的表名：io.seata.rm.datasource.undo.AbstractUndoLogManager#UNDO_LOG_TABLE_NAME

**Comment by zclcs** [comment]
> > 
> 
> 貌似是这里取的表名：io.seata.rm.datasource.undo.AbstractUndoLogManager#UNDO_LOG_TABLE_NAME

tmd，本地bebug就是不跑删除语句，日了狗了

**Comment by ninggc** [comment]
> > > 
> > 
> > 
> > 貌似是这里取的表名：io.seata.rm.datasource.undo.AbstractUndoLogManager#UNDO_LOG_TABLE_NAME
> 
> tmd，本地bebug就是不跑删除语句，日了狗了

可以试试debug一下，相关代码
1. io.seata.rm.datasource.undo.AbstractUndoLogManager#deleteUndoLog
2. io.seata.rm.datasource.undo.AbstractUndoLogManager#batchDeleteUndoLog
一方面看有没有调用，一方面看一下组装的sql对不对

**Comment by zclcs** [comment]
debug配置的值没错

![image](https://user-images.githubusercontent.com/50291896/156093423-14b3e4a2-8795-4dee-8787-8ad235437f7f.png)

**Comment by GoodBoyCoder** [comment]
> 

删除是延迟异步的操作，若要debug可以执行一个dml语句，然后AbstractUndoLogManager#flushUndoLogs打断点，这一步会将前后镜像的undo_log持久化，使用的logtable与delete相同

**Comment by GoodBoyCoder** [comment]
> ![image](https://user-images.githubusercontent.com/50291896/156088621-0c500266-5dee-4f7e-88ef-409d5ee3e5cc.png) seata 用的druid连接池老是报这个，大佬们知道咋去掉嘛

这个是Druid对于长时间空闲的Connection的检测日志，如果一个Connection空闲时间超过给定时间就会打印该日志并丢弃连接；可以配置禁用ping方式的检查改用检测语句（validateQuery）的方式刷新该时间

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/156127900-6f8b3ccb-606b-4f1b-8844-d9bd10285b69.png)
还是老样子，表名到这就是这样了
![image](https://user-images.githubusercontent.com/50291896/156128076-98077ed1-ae59-45bc-b512-e77f5b021c6a.png)
感觉应该是这里的问题

**Comment by GoodBoyCoder** [comment]
> ![image](https://user-images.githubusercontent.com/50291896/156127900-6f8b3ccb-606b-4f1b-8844-d9bd10285b69.png) 还是老样子，表名到这就是这样了 ![image](https://user-images.githubusercontent.com/50291896/156128076-98077ed1-ae59-45bc-b512-e77f5b021c6a.png) 感觉应该是这里的问题

是的，可以进去getConfig方法看看具体的配置获取流程有没有问题

**Comment by zclcs** [comment]
> > ![image](https://user-images.githubusercontent.com/50291896/156127900-6f8b3ccb-606b-4f1b-8844-d9bd10285b69.png) 还是老样子，表名到这就是这样了 ![image](https://user-images.githubusercontent.com/50291896/156128076-98077ed1-ae59-45bc-b512-e77f5b021c6a.png) 感觉应该是这里的问题
> 
> 是的，可以进去getConfig方法看看具体的配置获取流程有没有问题

![image](https://user-images.githubusercontent.com/50291896/156136655-7ed836a5-4077-4461-a224-bb33d66ab72b.png)
获取是 null的

**Comment by zclcs** [comment]
> > > ![image](https://user-images.githubusercontent.com/50291896/156127900-6f8b3ccb-606b-4f1b-8844-d9bd10285b69.png) 还是老样子，表名到这就是这样了 ![image](https://user-images.githubusercontent.com/50291896/156128076-98077ed1-ae59-45bc-b512-e77f5b021c6a.png) 感觉应该是这里的问题
> > 
> > 
> > 是的，可以进去getConfig方法看看具体的配置获取流程有没有问题
> 
> ![image](https://user-images.githubusercontent.com/50291896/156136655-7ed836a5-4077-4461-a224-bb33d66ab72b.png) 获取是 null的

我看这里获取的是dataId, 新版不是配置一个properties 就行了嘛

**Comment by zclcs** [comment]
> > ![image](https://user-images.githubusercontent.com/50291896/156127900-6f8b3ccb-606b-4f1b-8844-d9bd10285b69.png) 还是老样子，表名到这就是这样了 ![image](https://user-images.githubusercontent.com/50291896/156128076-98077ed1-ae59-45bc-b512-e77f5b021c6a.png) 感觉应该是这里的问题
> 
> 是的，可以进去getConfig方法看看具体的配置获取流程有没有问题
![image](https://user-images.githubusercontent.com/50291896/156138080-bb8a41b4-836e-4535-92d5-a31f9ddcaa39.png)

现在尴尬的是debug时间太久了，nacos报 -401

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/156139072-8cae6e3f-a666-4bba-8c68-373bd8afbcfa.png)
![image](https://user-images.githubusercontent.com/50291896/156139118-3ac0b6d7-854d-41e9-b2bd-4cfd39536bb6.png)
找的真的是dataId

**Comment by zclcs** [comment]
哪seata配置下的表名有啥用啊

**Comment by GoodBoyCoder** [comment]
1.4.2版本开始支持从一个Nacos dataId中获取所有配置信息，具体配置详情可参考[官网](https://seata.io/zh-cn/docs/user/configuration/nacos.html)

**Comment by zclcs** [comment]
> 1.4.2版本开始支持从一个Nacos dataId中获取所有配置信息，具体配置详情可参考[官网](https://seata.io/zh-cn/docs/user/configuration/nacos.html)

这个我配了，但是properties文件貌似不支持环境变量，如果我想每个服务都用不同的表名咋办

**Comment by zclcs** [comment]
> 1.4.2版本开始支持从一个Nacos dataId中获取所有配置信息，具体配置详情可参考[官网](https://seata.io/zh-cn/docs/user/configuration/nacos.html)

![image](https://user-images.githubusercontent.com/50291896/156142353-6f8a39c8-692c-40d2-b60d-e6437a97a024.png)
有个小问题，配置中心有两个一毛一样的配置

**Comment by GoodBoyCoder** [comment]
> > 1.4.2版本开始支持从一个Nacos dataId中获取所有配置信息，具体配置详情可参考[官网](https://seata.io/zh-cn/docs/user/configuration/nacos.html)
> 
> ![image](https://user-images.githubusercontent.com/50291896/156142353-6f8a39c8-692c-40d2-b60d-e6437a97a024.png) 有个小问题，配置中心有两个一毛一样的配置

估计重复的会被覆盖，你也可以提一个PR改正

**Comment by zclcs** [comment]
> > 1.4.2版本开始支持从一个Nacos dataId中获取所有配置信息，具体配置详情可参考[官网](https://seata.io/zh-cn/docs/user/configuration/nacos.html)
> 
> 这个我配了，但是properties文件貌似不支持环境变量，如果我想每个服务都用不同的表名咋办

这个问题呢

**Comment by GoodBoyCoder** [comment]
> > > 1.4.2版本开始支持从一个Nacos dataId中获取所有配置信息，具体配置详情可参考[官网](https://seata.io/zh-cn/docs/user/configuration/nacos.html)
> > 
> > 
> > 这个我配了，但是properties文件貌似不支持环境变量，如果我想每个服务都用不同的表名咋办
> 
> 这个问题呢

若是服务之间需要不同的配置，可以设置不同的nacos的dataId来实现吧（提供一个思路，这一块我了解的不多

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/156481676-605eb974-9f3b-4588-b0ff-3fbf90d29962.png)
所以在client端这个配置没啥用是嘛

**Comment by zclcs** [comment]
> > > > 1.4.2版本开始支持从一个Nacos dataId中获取所有配置信息，具体配置详情可参考[官网](https://seata.io/zh-cn/docs/user/configuration/nacos.html)
> > > 
> > > 
> > > 这个我配了，但是properties文件貌似不支持环境变量，如果我想每个服务都用不同的表名咋办
> > 
> > 
> > 这个问题呢
> 
> 若是服务之间需要不同的配置，可以设置不同的nacos的dataId来实现吧（提供一个思路，这一块我了解的不多

但是去拿dataId的配置是写死的啊。总不可能每个服务块都搞不同的GROUP吧

**Comment by zclcs** [comment]
seata 的 healthcheck 该怎么写，有没有大佬知道
![image](https://user-images.githubusercontent.com/50291896/156492888-43d79fbe-cc2c-4137-8f0c-5f4ed5b5f703.png)
这样不行

**Comment by GoodBoyCoder** [comment]
> ![image](https://user-images.githubusercontent.com/50291896/156481676-605eb974-9f3b-4588-b0ff-3fbf90d29962.png) 所以在client端这个配置没啥用是嘛

若是配置了配置中心，目前来说本地的配置就无效，两者不会互补

**Comment by a364176773** [comment]
> ![image](https://user-images.githubusercontent.com/50291896/156481676-605eb974-9f3b-4588-b0ff-3fbf90d29962.png) 所以在client端这个配置没啥用是嘛

不支持占位符的解析，spring中是spring会去解析，在seata中seata自身没去解析这种${xxxx}，有个办法可以生效
将使用springcloud的配置中心改为nacos，seata的配置中心config.type改为file
然后将你上面这串配置放到你spring cloud需要拉取的远程配置中，这样就可以了，这样seata是通过spring去解析的，而不是自己解析
