### ISSUE TITLE
Implementation of front-end page of globalsession query interface

### ISSUE THREAD

**Issue by lvekee** [seata/seata#4416]
## Why you need it?
Implementation of front-end page of globalsession query interface
If you want to fix it, please comment "Please assign it to me" is this issue.

全局事务查询接口前端页面的实现
如果你有兴趣修复这个问题的话, 请在下方留言 Please assign it to me

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by liuqiufeng** [comment]
Please assign it to me
