### ISSUE TITLE
同时使用不同版本mysql时，空指针

### ISSUE THREAD

**Issue by peng19832** [seata/seata#4418]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
后端使用mysql8.0.15和mysql8.0.25时，日子抛出空指针异常

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
![2a0a20b8ab82e6308b11dcb7d4ceedf](https://user-images.githubusercontent.com/9590209/156089406-86734eb6-aa70-4d2d-9451-a163dbdc7dfb.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 后端使用不同版本mysql
比如，8.0.15和8.0.25

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  2.2.1
- OS : centos7
- Others:

**Comment by xingfudeshi** [comment]
Temporarily closed due to no reply for a long time, welcome to discuss at any time
