### ISSUE TITLE
tcc one-phase data need to be limited in size

### ISSUE THREAD

**Issue by funky-eyes** [seata/seata#4421]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
tcc目前支持将一些数据保存到tc，在二阶段下发回滚或提交的时候会带下来，但是这些数据并没有进行合理的限制，导致如果盲目report大数据的话会对tc造成负担，而且对分支注册的效率也会降低，需要限制一下最大大小，老版本client没有本地判断所以需要tc端也进行判断，最佳方式是两边都加，超过大小可以抛出异常提示，这个大小允许手动配置，默认值可以设置一个相对较小的值，如128k等

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by Bughue** [comment]
plz assign to me

**Comment by caohdgege** [comment]
方案上为什么不是对APPdata进行压缩，而是选择抛异常？

**Comment by Bughue** [comment]
> 方案上为什么不是对APPdata进行压缩，而是选择抛异常？

有道理，这种字符串的压缩率应该是很高的，这样的话在tc端存的就是个压缩值，压缩和解压都在客户端做。 @a364176773 一起看看？
