### ISSUE TITLE
seata无法指定配置文件

### ISSUE THREAD

**Issue by WalkFly** [seata/seata#4426]
这是我的创建容器
docker run --name seate-server -p 8091:8091  -e SEATA_PORT=8091 -e SEATA_CONFIG_NAME=file:/root/seata-config/registry -v /usr/local/seata:/root/seata-config seataio/seata-server

并且我的配置文件registry.conf 和file.conf 都已经放在了宿主/usr/local/seata目录下

**Comment by a364176773** [comment]
seata是latest？如果是改成1.4.2

**Comment by WalkFly** [comment]
> 1.4.2

你好！刚尝试一下成功了，版本要指定为1.4.2而且创建容器的命令也要带上版本号
docker run --name seate-server -p 8091:8091 -e SEATA_PORT=8091 -e SEATA_CONFIG_NAME=file:/root/seata-config/registry -v /usr/local/seata:/root/seata-config seataio/seata-server:1.4.2

最后：万分感谢！
