### ISSUE TITLE
大佬 关于全局锁的问题？

### ISSUE THREAD

**Issue by SpriderMan** [seata/seata#4437]
如果server.maxCommitRetryTimeout=-1 server.maxRollbackRetryTimeout=-1   如果一个分支事务一直重试没有成功的话，全局锁就会一直得不到释放？那该其他业务功能需要该全局锁的话就会一直失败？

**Comment by pengten** [comment]
回滚失败不会释放锁，但是提交失败会释放

**Comment by a364176773** [comment]
> 

关注问题是不是关注的不是要点,如果规范使用为什么会出现回滚一直失败的问题?

**Comment by SpriderMan** [comment]
> 回滚失败不会释放锁，但是提交失败会释放

谢谢，提交会释放，我看到了
![image](https://user-images.githubusercontent.com/18304842/156887890-25af7c42-6316-4180-95b3-ac43dac28e06.png)

**Comment by a364176773** [comment]
> > 回滚失败不会释放锁，但是提交失败会释放
> 
> 谢谢，提交会释放，我看到了 ![image](https://user-images.githubusercontent.com/18304842/156887890-25af7c42-6316-4180-95b3-ac43dac28e06.png)

不是这
