### ISSUE TITLE
Questions about seata transaction isolation level

### ISSUE THREAD

**Issue by nianxiaoyi** [seata/seata#4439]
I am evaluating the use of seata to solve distributed transaction coordination problems in my work. 
Regarding the use of seata as a distributed transaction coordination framework, there are several issues that I would like to ask the experts.
1. Is it required to integrate nacos for spring based microservice to use seata? As far as I know, seata passes the global transaction xid through the feign call. If my framework is not based on nacos, how should I transparently transmit the xid for seata?
2. during a cross-service transaction being executed, if the service in which branch transaction has not been committed was restarted, can data consistency still be guaranteed? if TC wait timeout, and then decide rollback the global transaction, the data consistency seems to be guaranteed (assuming no "dirty writes" before rollback)?
3. The global transaction isolation level provided by seata is based on the database isolation level. The default isolation level of the mysql database is repeatable read, so the default isolation level of branch transactions when using seata+mysql is repeatable read, is it right? Does the @Globaltransactional(level="REPEATABLE_READ") annotation of spring-tx also take effect for the local branch transaction in global transaction context?
4. Seata global transaction "read committed "isolation level" is implemented through global locks. This needs to prevent new branch transactions from reading and writing data that has actually been committed to the database, which is equivalent to adding exclusive records to those committed row records. so are these exclusive locks utilizing the database's own lock or  implemented specially by seata?
5. When dirty writes are found in global transaction rollback, manual intervention is required. Does seata support alarm notification?

**Comment by a364176773** [comment]
1.xid传递跟nacos没有半毛钱关系,详细看官网的新人文档
2.分支事务只要是高可用部署的>=2,那么你重启其中一个节点,另一个节点会用来二阶段提交/回滚,这是没任何问题,如果只有一个节点,那么等这个分支事务启动会下发提交指令给它进行二阶段提交/回滚,事务超时那种是针对一阶段还未决议的事务,决议了的都是通过异步方式补偿达到最终一致性
3.是的
4.跟读已提交没有什么关系,通过数据库的x锁交换tc端的全局锁达到数据的隔离
5.目前只能通过tm端实现FailureHandler,在onRollbackRetrying的时候发出告警
建议先通过官网faq,和新人文档阅读来解惑

**Comment by nianxiaoyi** [comment]
> 1.xid传递跟nacos没有半毛钱关系,详细看官网的新人文档 2.分支事务只要是高可用部署的>=2,那么你重启其中一个节点,另一个节点会用来二阶段提交/回滚,这是没任何问题,如果只有一个节点,那么等这个分支事务启动会下发提交指令给它进行二阶段提交/回滚,事务超时那种是针对一阶段还未决议的事务,决议了的都是通过异步方式补偿达到最终一致性 3.是的 4.跟读已提交没有什么关系,通过数据库的x锁交换tc端的全局锁达到数据的隔离 5.目前只能通过tm端实现FailureHandler,在onRollbackRetrying的时候发出告警 建议先通过官网faq,和新人文档阅读来解惑

感谢，结合你提到的点与部分文档，基本上了解了它的大体机制
