### ISSUE TITLE
AT模式下，fastJson序列化时，对于Mysql DATE相关类型全部序列化成了字符串，导致镜像对比出错

### ISSUE THREAD

**Issue by renliangyu857** [seata/seata#4443]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
针对issue#4402 对AT模式下的mysql db type做了一轮测试 https://github.com/seata/seata/pull/4402
2) AT模式下，fastJson序列化时，对于Mysql DATE相关类型全部序列化成了字符串，导致二阶段回滚数据校验时镜像对比出错。DataCompareUtils类中convertType()方法目前只对TIMESTAMP类型做了特殊处理，应该要加上DATE和TIME类型的处理
![image](https://user-images.githubusercontent.com/28523136/156978334-0d8811fd-f366-45e2-8025-35828ccf3765.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
在Mysql5及Mysql8下都可以复现该问题，可以使用https://github.com/seata/seata/pull/4402的测试用例进行测试

### Ⅵ. Environment:

- JDK version :jdk8
- Seata version:  1.4.2
- OS :windows
- Others:mysql: 5.7.24或8.0.12

**Comment by xjlgod** [comment]
please assign to me
