### ISSUE TITLE
插入undo_log的前置镜像和后置镜像数据 和 查询出来的undo_log的数据不一致,而且是同一种序列化 FST

### ISSUE THREAD

**Issue by apl0219** [seata/seata#4454]
![dbfa9bfc93c1c9d36309468cf27e16b](https://user-images.githubusercontent.com/52915158/157426814-c30641c4-954a-447c-bd2e-cbcf2220f272.png)
这是插入的数据
![52fa6acff1b8717f7c31076adbeaa14](https://user-images.githubusercontent.com/52915158/157426867-b3410cbb-fff2-4528-a725-409b0079bb94.png)
这是查询的数据
![d1ecd7a27d57fee805f2a5c1e2c21e1](https://user-images.githubusercontent.com/52915158/157426918-25c7ee52-837d-4b2a-b48d-ac26100bbf62.png)
这是拿undo_log回滚的数据，
他们的数据大小都不一致，
seata-server:1.4.2
seata客户端 
<dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.4.0</version>
</dependency>

**Comment by pengten** [comment]
现象是什么？无法回滚吗？

**Comment by huyu-tom** [comment]
现象就是我采用了shardingjdbc+druid 插入数据 blob二进制数据，他会莫名奇妙的多出好多多余的数据出来，导致seata反序列化的时候一直失败，导致一直回滚失败

**Comment by huyu-tom** [comment]
我发现问题了，shardingJdbc的代理，我们通过 setBlob()设置二进制的数据 ，他最终会在 ShardingPreparedStatement类,代理成setObjct()设置的内容，你们可以用最原生的JDBC，分别用setBlob() 和 setObjct()方法设置相同的内容,setObjct()方法会导致二进制的数据会不一样 
![b3ba7997fcb0b09897f36158f6fa704](https://user-images.githubusercontent.com/54206202/157468784-716bbfe9-b06e-43b2-abeb-88182a44a5f6.png)
![c1a9fd4d34c67739798d3e8df31ba2d](https://user-images.githubusercontent.com/54206202/157468809-3971bb01-ca5d-46b6-aee4-74426274cfd8.png)
![0d72251f02cad4d017b0a3ae19fc5aa](https://user-images.githubusercontent.com/54206202/157469408-7eebceb0-07ce-49f6-a2de-ed1495a01d0a.png)
![2c4e5f5654d1297fbb151fd02468f48](https://user-images.githubusercontent.com/54206202/157469444-6cdf6fad-2a81-429c-923f-8c35e209456a.png)
根据以上提供的源码debug图

**Comment by caohdgege** [comment]
修复：https://github.com/seata/seata/pull/3555
分析：https://github.com/seata/seata/issues/3541

检查一下你的驱动版本和client版本，如果符合上面的条件的话，任意升级其中一个可以解决

**Comment by caohdgege** [comment]
> 

我们 已经 不setBlob了。。。
