### ISSUE TITLE
AT 模式判断全局事务状态，如果回滚后，redis数据清空

### ISSUE THREAD

**Issue by pha183** [seata/seata#4485]

**Comment by pengten** [comment]
获取可以考虑在全局事务中加入一个针对redis的TCC分支

**Comment by azhsmesos** [comment]
这个问题是不是类似于at模式下事物1需要获取一堆锁但是目前锁不够，获取一半后发现锁不够，就要回滚丢掉之前的锁重新尝试获取，丢掉之前获取的锁就相当于redis del 命令
