### ISSUE TITLE
The singleton pattern fetches multiple objects

### ISSUE THREAD

**Issue by Oliverwqcwrw** [seata/seata#4486]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

In `io.seata.config.consul.ConsulConfiguration`

I find `getInstance` and `getConsulClient` all use class `ConsulConfiguration.class` lock,

when `ConsulConfiguration` and `ConsulClient` is null,Multiple threads executing these two methods simultaneously may return multiple objects, So I suggest using two different locks for singletons

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by pengten** [comment]
If it's not safe to use one lock, why wouldn't it be a problem to use two?

**Comment by Oliverwqcwrw** [comment]
I was wrong
