### ISSUE TITLE
develop分支，Eureka做注册中心，修改事务分组的集群名，并不会去获取最新的集群IP列表

### ISSUE THREAD

**Issue by tuwenlin** [seata/seata#4488]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
develop分支，Eureka做注册中心，修改事务分组的集群名，并不会去获取最新的集群IP列表
EurekaRegistryServiceImpl 132行的refreshCluster方法，触发CacheRefreshedEvent事件时执行，参数还是初始化的clusterUpperName,而不会是128行获取的clusterUpperName

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by pengten** [comment]
@lcmvs Is there a flaw here?

**Comment by lcmvs** [comment]
> * 
> * xxx

的确有这个问题，一直监听旧的集群了

**Comment by tuwenlin** [comment]
> > * xxx
> 
> 的确有这个问题，一直监听旧的集群了

那我给修复一下吧

**Comment by lcmvs** [comment]
> > > * xxx
> > 
> > 
> > 的确有这个问题，一直监听旧的集群了
> 
> 那我给修复一下吧

嗯嗯
