### ISSUE TITLE
AT模式下undo_log相关信息可以改为使用redis存吗，公司禁止使用大字段longblob

### ISSUE THREAD

**Issue by zsy2713** [seata/seata#4498]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by caohdgege** [comment]
1. 直接回答你的问题：不行
2. 原因解释：undo_log的存储要保证与你本地的dml处在同一个本地事务范围内，才能保证原子性
3. 方案选择：可以根据你们的具体业务评估 MediumBlob 是否足够(如果出现存不下的情况会报错)
