### ISSUE TITLE
采用TCC模式进行测试，在TM端通知TC端进行全局提交后，TC接收到请求进行全局提交处理，如果TC端模拟宕机操作，此时数据库中global_table和branch_table相应事务记录仍然存在，可是在过几十秒后记录被删除，这是什么原理呢？

### ISSUE THREAD

**Issue by zbelieve** [seata/seata#4507]
而且还想问下如果TC端在一段时间后（十几分钟）再次重启，这时候之前未执行完的事务就无法继续进行了，这样不会产生问题么？

**Comment by pengten** [comment]
TC重启后会继续推进事务完成，没有问题。已经完成的事务会被删除。

**Comment by zbelieve** [comment]
您好，请问下在TM端通知TC端进行全局提交后，TC接收到请求进行全局提交处理，还没有通知分支进行commit,此时TC端模拟宕机（直接终止TC端程序），mysql中global_table和branch_table相应事务记录此时仍然存在，可是在过几十秒后记录被删除，这是什么原理呢？我用的1.4.2版本.
