### ISSUE TITLE
seata1.4.2版本AT模式数据源mysql切换oracle后修改插入报错

### ISSUE THREAD

**Issue by shi-junhui** [seata/seata#4534]
问题描述：多数据源配置，AT模式，GlobalTransactional注解，由mysql库切换到oracle库后，插入或修改语句报错，报"ORA-00933: SQL 命令未正确结束"
个人分析：跟踪代码发现当切换数据源到oracle时，数据源正常切换，但默认数据库类型依旧是mysql,导致在执行插入oracle时报错
seata版本：1.4.2
springboot版本：2.2.1.RELEASE

**Comment by a364176773** [comment]
请问你这个动态数据源如何代理？

**Comment by shi-junhui** [comment]
baomidou3.3.6

**Comment by shi-junhui** [comment]
> 请问你这个动态数据源如何代理？

baomidou3.3.6

**Comment by a364176773** [comment]
> > 请问你这个动态数据源如何代理？
> 
> baomidou3.3.6

有没有关闭seata自身的动态代理和手动代理？

**Comment by shi-junhui** [comment]
> > > 请问你这个动态数据源如何代理？
> > 
> > 
> > baomidou3.3.6
> 
> 有没有关闭seata自身的动态代理和手动代理？

没有关闭

**Comment by a364176773** [comment]
根据官网faq上的和baomidou的动态数据源结合注意事项处理下即可
