### ISSUE TITLE
seata 的service源码项目日志替换成log4j2

### ISSUE THREAD

**Issue by shining-stars-lk** [seata/seata#4549]
seata 的service源码项目日志替换成log4j2可以吗
版本：1.4.2

**Comment by a364176773** [comment]
麻烦阐述下具体需求

**Comment by shining-stars-lk** [comment]
我们公司的日志使用的log4j2，现在要引入seata 我看server的源码项目使用的是logback，想替换成log4j2来实现控制台、文件、logstash的输出。实现起来复杂吗。
![image](https://user-images.githubusercontent.com/40255310/163532291-9fe29e18-030c-471f-a347-036f836072d7.png)
改这几个文件就可以了吗

**Comment by 106umao** [comment]
> 

我刚刚看了以下，seata-server里都是直接依赖的slf4j-api。如果要替换实现的话不止修改这几个文件，还需要在pom.xml文件里替换一些依赖，比如slf4j-log4j12桥接器等。实现起来并不复杂。
