### ISSUE TITLE
Oracle使用1.4.2版本主键超过16位时Insert操作不会回滚，在Undo_log表中未查询到Insert的记录

### ISSUE THREAD

**Issue by ZDAw** [seata/seata#4552]

**Comment by caohdgege** [comment]
Java的字段类型改成BigDecimal，这玩意是驱动层面不肯返回数据

**Comment by WeiJiaBin** [comment]
![image](https://user-images.githubusercontent.com/58247520/200255706-a2ee3380-ccb0-448e-b766-4eacaa360ec9.png)
兄弟，试试更改驱动，我改了以后正常了
