### ISSUE TITLE
 How to exclude some method not join the global transaction? 如果排除全局事务中某些方法不参与全局事务

### ISSUE THREAD

**Issue by douxiaofeng99** [seata/seata#4553]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
在某些服务中，存在如获取序列（通过序列定义表）、插入日志，这些方法被纳管到全局事务后，导致序列获取重复。即使改写序列获取为getConnection模式，程序主动提交（conn.commit()），还会导致序列重复。seata.enableAutoDataSourceProxy=false设置这个也没效果。
诉求：
     在全局事务中，需要某些表的修改即使全局不成功，也提交

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
加个globaltransational在对应的方法上设置事务传播为notsupport
