### ISSUE TITLE
Non-fescar distributed transaction data reading

### ISSUE THREAD

**Issue by linmenghuai** [seata/seata#456]
非fescar事务读取时候是否会由于fescar分布式事务回滚导致脏读情况？fescar全局锁只能控制有注册的锁，对于不是fescar分布式事务下的业务，随时都有可能读取到脏数据，请问这个问题如何解决处理？

**Comment by slievrly** [comment]
In principle, the data modification entry needs to be handed over to fescar for management. But there will be a more lightweight transaction annotation for the scenario where the user can determine that there is only a local transaction but does not want to read the middle state data. This annotation performs better than fescar's global transaction annotation.

**Comment by linmenghuai** [comment]
Thank you for your answer.Then which version of this annotation is developed?

**Comment by slievrly** [comment]
@linmenghuai Has been developed to wait for review
