### ISSUE TITLE
ShardingJDBC分布式事务无法正常回滚

### ISSUE THREAD

**Issue by newchendb** [seata/seata#4573]
Shardingsphere-JDBC version is 5.1.1
Seata version is 1.4.2
这里是一个简单的Demo。谁能帮我看看为什么分布式事务是无效的吗？是否缺少了配置或者配置错误？

https://github.com/newchendb/shardingjdbc-seata-test

订单应用程序请求商品应用程序。当订单应用程序主动报告错误时，商品应用程序不会触发事务回滚或报告任何错误。

**Comment by pengten** [comment]
1、先检查异常是否被catch或者有无熔断降级
异常被catch后或熔断降级后，全局事务便不感知抛出的异常。建议catch异常后返回异常码给事务发起方（TM），然后事务发起方 (TM) 。通过API的方式回滚全局事务。
2、否则请自行debug以下方法：
ExecuteTemplate#execute(List<SQLRecognizer>, StatementProxy<S>, StatementCallback<T,S>, java.lang.Object...)如果没进入这个方法，说明数据源被没有代理。
如果没进入
if (CollectionUtils.isEmpty(sqlRecognizers)) {
 sqlRecognizers = SQLVisitorFactory.get(statementProxy.getTargetSQL(),dbType);
}没进去说明xid没有传递
