### ISSUE TITLE
数据正常回滚，但是undo_log表出现很多log_status=1的记录

### ISSUE THREAD

**Issue by mylixiangxiang** [seata/seata#4578]
我的问题是：
1、某个业务的回滚都会出现undo_log表log_status=1的数据，随着调用次数的增加，数据越来越多，这个数据是属于正常？
2、我是否可以定时清除log_status=1的记录？
谢谢

**Comment by a364176773** [comment]
多数据源?

**Comment by Lyrmal** [comment]
> 多数据源?

是的，使用了shardingsphere读写分离、多数据源

**Comment by mylixiangxiang** [comment]
> 多数据源?

是的，使用了shardingsphere读写分离、多数据源
