### ISSUE TITLE
rollback transaction should release the global lock before asynchronously deleting the branch transaction

### ISSUE THREAD

**Issue by a364176773** [seata/seata#4580]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
如果大量分支事务被异步删除情况下,branch被异步删除,解锁等于也异步了,回滚情况下,异步删除线程是跟提交都是在一个线程池中,一个队列中,当一个回滚的事务在队列中被排得相对靠后,那么解锁等于慢了,势必影响吞吐,特别是热点数据本身可以在业务线程中被解锁,却被放到了队列中,我个人觉得回滚情况下不应该异步删除branch,起码也是得先解锁再异步,提交倒是无所谓,因为锁事前就被全部解开了

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by slievrly** [comment]
#4591 

Currently only the `server.session.enable-branch-async-remove` is turned off, but further expect to unlock from asynchronous to synchronous processing.

**Comment by pengten** [comment]
please assign to me
