### ISSUE TITLE
关于insertExecutor中构建afterImage一种错误情况

### ISSUE THREAD

**Issue by jianglianggithub** [seata/seata#4581]
**遇到sql的模板** `insert into test(id, uname) values (unix_timestamp(now()), '1'),(uuid() , '2');`

根据 **MySQLInsertExecutor -> getPkValues -> getPkValuesByColumn**
以这个**sql**示例如果存在一个**insert sql**存在插入多条数据，但是又不是自动增长形的主键的时候
那么**getPkValuesByColumn**返回的`Map<String,List<Object>> pkValuesMap` 里面 List<Object> 中就是**SqlMethodExpr**类型的value
然后回到**buildTableRecords**构建出 **afterImage** 则为空，因为根本查不出来数据
由于**PreparedStatement**是根据传入的**dataType**来解析**value**的最后构建出来的sql则是
之前` SELECT * FROM test WHERE (id) in ( (?),(?) )`
之后 `SELECT * FROM test WHERE (id) in ( ('SQL_METHOD'),('SQL_METHOD') )`
请问一下这种情况是允许存在的吗

**Comment by jianglianggithub** [comment]
由于afterImage 为空后续如果发生错误也是无法回滚的测试了这种情况

**Comment by caohdgege** [comment]
只插入一条是有可能可以的，多条是一定不行的

**Comment by jianglianggithub** [comment]
> 
但是在执行过程中没有任何错误提示数据插入成功回滚失败这个我感觉不太正常吧

**Comment by jianglianggithub** [comment]
> 只插入一条是有可能可以的，多条是一定不行的

但是在执行过程中没有任何错误提示数据插入成功回滚失败这个我感觉不太正常吧

**Comment by jianglianggithub** [comment]
ok解决了，群里面说1.5版本会上限制
