### ISSUE TITLE
seata-server支持多注册中心

### ISSUE THREAD

**Issue by WangXiaoJin** [seata/seata#4584]
## Why you need it?
因历史原因我们现有系统同时包含Dubbo服务、SpringCloud服务，Dubbo注册中心使用了Zookeeper，SpringCloud注册中心使用了Consul，有些Dubbo服务会调用SpringCloud服务接口。
希望Dubbo服务、SpringCloud服务共用一套seata-server集群，此时需要seata-server集群同时使用Zookeeper和Consul作为注册中心。

## How it could be?
seata-server支持多注册中心后，我们现有系统接入Seata将变得方便，各服务使用原先各自的注册中心，无需再依赖其他注册中心的包。

**Comment by slievrly** [comment]
I think it's a good idea.

**Comment by liuqiufeng** [comment]
please assign it to me

**Comment by liuqiufeng** [comment]
目前有两种想法：
1.将io.seata.discovery.registry.RegistryFactory#getInstance改造为返回多个RegistryService，通过registry.type支持配置多个（比如逗号分隔）来实现。调用时循环多个RegistryService；
2.新增一种multiple RegistryType，扫描已配置的多个注册中心（比如同时配置了nacos、zookeeper等），多个注册中心同时执行subscribe等操作。
