### ISSUE TITLE
nacos-config-interactive.py 和nacos-config-interactive.sh 脚本文件名称有误

### ISSUE THREAD

**Issue by burncode** [seata/seata#4588]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata/script/config-center/nacos/ 目录里面 nacos-config-interactive.py 和nacos-config-interactive.sh 脚本文件名称 和文档有出入，不知道是不是单词漏拼了字母

nacos-confg-interactive.py    应该为 ----->     nacos-config-interactive.py
nacos-confg-interactive.sh     应该为 ----->     nacos-config-interactive.sh

**Comment by slievrly** [comment]
@burncode hope you can propose a PR to correct it.

**Comment by slievrly** [comment]
#4606
