### ISSUE TITLE
seata saga模式对mq的支持

### ISSUE THREAD

**Issue by menghuan123** [seata/seata#4592]
seta的saga模式目前有采用mq的方式实现吗?

**Comment by a364176773** [comment]
到底是对mq的支持，还是mq方式实现？

**Comment by menghuan123** [comment]
> 

mq方式实现saga,目前有实现嘛

**Comment by a364176773** [comment]
> > 
> 
> mq方式实现saga,目前有实现嘛

目前saga是基于状态机的，后续会基于注解+拦截器做另一个版本，基于mq这种我没了解过，但是这会不会太过依赖消息中间件，而不是自身框架了

**Comment by xingfudeshi** [comment]
Temporarily closed due to no reply for a long time, welcome to discuss at any time.
