### ISSUE TITLE
1.3 集成seata后服务不能正常停止

### ISSUE THREAD

**Issue by tianliu94321** [seata/seata#4594]
springboot集成seata后使用/actuator/shutdown不能正常停止 
异常信息：
10:03:56.893 [fileListener_1_1] ERROR io.seata.config.FileConfiguration:325 - fileListener execute error:null
10:03:56.943 [fileListener_2_1] ERROR io.seata.config.FileConfiguration:325 - fileListener execute error:null
10:03:56.943 [fileListener_3_1] ERROR io.seata.config.FileConfiguration:325 - fileListener execute error:null
...

环境：
jdk 1.8
springboot 2.3.12.RELEASE 
spring-cloud Hoxton.SR12 
spring-cloud-alibaba 2.2.7.RELEASE
spring-cloud-starter-alibaba-seata 2.2.7.RELEASE
nacos 2.0.3
seata 1.3.0

**Comment by a364176773** [comment]
这是其他线程，不会有影响，先确认你为什么有配置项是空的读不到吧

**Comment by tianliu94321** [comment]
我可能没说清楚，这个日志错误会一直刷， 这个程序会一直残留在那里 。

io.seata.config.FileConfiguration.FileListener#onChangeEvent

  @Override
        public void onChangeEvent(ConfigurationChangeEvent event) {
            while (true) {
                try {
                    String currentConfig =
                        ConfigurationFactory.getInstance().getLatestConfig(dataId, null, DEFAULT_CONFIG_TIMEOUT);
                    String oldConfig = listenedConfigMap.get(dataId);
                    if (ObjectUtils.notEqual(currentConfig, oldConfig)) {
                        listenedConfigMap.put(dataId, currentConfig);
                        event.setDataId(dataId).setNewValue(currentConfig).setOldValue(oldConfig);
                        listener.onChangeEvent(event);
                    }
                } catch (Exception exx) {
                    LOGGER.error("fileListener execute error:{}", exx.getMessage());
                }
                try {
                    Thread.sleep(LISTENER_CONFIG_INTERVAL);
                } catch (InterruptedException e) {
                    LOGGER.error("fileListener thread sleep error:{}", e.getMessage());
                }
            }
        }

**Comment by tianliu94321** [comment]
我可能没说清楚，这个日志错误会一直刷， 这个程序会一直残留在那里 。
