### ISSUE TITLE
ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL

### ISSUE THREAD

**Issue by susumumuqiqi** [seata/seata#4596]
Ⅰ. 请问是否支持MySQL的批量操作，如果支持需要怎么配置。
Mybatis 写法示例如下：

    <insert id="test">
        insert into test_log (c1,c2,c3 )
        select c1,c2,c3 from test where id=#{id} ;
        delete from test where id=#{id};
    </insert>

实际运行中报如下异常：
Cause: java.lang.UnsupportedOperationException: ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL

**Comment by a364176773** [comment]
ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL

**Comment by Joyonline** [comment]
请问使用seata GlobalTransactional注解，会出现这种问题，有解决方法吗？

**Comment by susumumuqiqi** [comment]
你试试在数据库的url配置里加上allowMultiQueries=true看看是否可以。我有点记不太清了。



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 28, 2023 13:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [seata/seata] ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL (Issue #4596)




 
请问使用seata GlobalTransactional注解，会出现这种问题，有解决方法吗？

**Comment by susumumuqiqi** [comment]
把mutil sql改了



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 28, 2023 13:48 PM
To: ***@***.***&gt;;
Subject: Re: [seata/seata] ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL (Issue #4596)


你试试在数据库的url配置里加上allowMultiQueries=true看看是否可以。我有点记不太清了。



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 28, 2023 13:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [seata/seata] ONLY SUPPORT SAME TYPE (UPDATE OR DELETE) MULTI SQL (Issue #4596)




 
请问使用seata GlobalTransactional注解，会出现这种问题，有解决方法吗？

**Comment by Joyonline** [comment]
多谢多谢。拆分一种类型的sql,是可以的   @susumumuqiqi
