### ISSUE TITLE
1.4.1 insert对象有Date类型时失败，1.4.2不会回滚

### ISSUE THREAD

**Issue by zhouxiaofu** [seata/seata#4597]
### 问题1
- 1.4.1 insert有数据有Date类型的属性时jackson会报错，原因是因为缺少LocalDateTime的处理模块，但是我的insert的对象中的属性是Date类型
- jackson有很多java8的数据类型不能处理，可以参考这个 (https://stackoverflow.com/questions/27952472/serialize-deserialize-java-8-java-time-with-jackson-json-mapper)[https://stackoverflow.com/questions/27952472/serialize-deserialize-java-8-java-time-with-jackson-json-mapper]

### 问题2
1.4.1可以回滚，切换到1.4.2后不能回滚

- JDK version : OpenJDK 1.8.0_0321
- Seata version:  1.4.2
- OS : win10
- Others: MySQL 8.0.28

两个问题的复现代码在**附件**中

[seata-demo.zip](https://github.com/seata/seata/files/8666498/seata-demo.zip)

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/overview/faq.html
1.4.2没有不回滚问题，自己多看下文档
