### ISSUE TITLE
TCC 模式, 如果 Server 端重启了,  那么此前未完成的事务是怎么恢复的呢?  可否告知下对应的源码在哪里

### ISSUE THREAD

**Issue by nimo10050** [seata/seata#4599]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

TCC 模式, 如果 Server 端重启了,  那么此前未完成的事务是怎么恢复的呢?  可否告知下对应的源码在哪里

在这篇 [分布式事务 Seata TCC 模式深度解析 | SOFAChannel#4 直播整理](https://developer.aliyun.com/article/699681#slide-13), 有提到蚂蚁金服内部是如何处理的,  我想知道 seata 里面是如何实现的.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/22631374/167773697-5f16ce21-033e-4286-af48-6ce0f307ab5a.png">

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5
- OS : macos
- Others:

**Comment by a364176773** [comment]
seata没有同库模式，依靠定时任务对超时事务进行驱动回滚

**Comment by a364176773** [comment]
server端重启不影响业务（高可用部署大于等于2节点），除非是非优雅下线
