### ISSUE TITLE
使用latset镜像无法注册到nacos

### ISSUE THREAD

**Issue by Q3B0** [seata/seata#4602]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

nacos版本2.0.3，使用docker-compose拉取lastest镜像后启动无法注册到nacos
使用1.4.2版本可以正常注册

`seata-server    | 10:21:53.261  INFO --- [                     main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 7091 (http)
seata-server    | 10:21:53.284  INFO --- [                     main] o.a.coyote.http11.Http11NioProtocol      : Initializing ProtocolHandler ["http-nio-7091"]
seata-server    | 10:21:53.288  INFO --- [                     main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
seata-server    | 10:21:53.289  INFO --- [                     main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.55]
seata-server    | 10:21:53.574  INFO --- [                     main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
seata-server    | 10:21:53.574  INFO --- [                     main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4654 ms
seata-server    | 10:21:55.891  INFO --- [                     main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
seata-server    | 10:21:56.649  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/'] with []
seata-server    | 10:21:56.650  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/**/*.css'] with []
seata-server    | 10:21:56.651  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/**/*.js'] with []
seata-server    | 10:21:56.663  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/**/*.html'] with []
seata-server    | 10:21:56.663  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/**/*.map'] with []
seata-server    | 10:21:56.669  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/**/*.svg'] with []
seata-server    | 10:21:56.670  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/**/*.png'] with []
seata-server    | 10:21:56.671  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/**/*.ico'] with []
seata-server    | 10:21:56.672  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/console-fe/public/**'] with []
seata-server    | 10:21:56.672  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure Ant [pattern='/api/v1/auth/login'] with []
seata-server    | 10:21:56.750  INFO --- [                     main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@5bda157e, org.springframework.security.web.context.SecurityContextPersistenceFilter@541afb85, org.springframework.security.web.header.HeaderWriterFilter@5efe47fd, org.springframework.security.web.authentication.logout.LogoutFilter@3dc68586, io.seata.console.filter.JwtAuthenticationTokenFilter@67e0fd6d, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@7db40fd5, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@44b940a2, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@21390938, org.springframework.security.web.session.SessionManagementFilter@7fe8c7db, org.springframework.security.web.access.ExceptionTranslationFilter@66d25ba9, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@6aa5974e]
seata-server    | 10:21:56.873  INFO --- [                     main] o.a.coyote.http11.Http11NioProtocol      : Starting ProtocolHandler ["http-nio-7091"]
seata-server    | 10:21:56.918  INFO --- [                     main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 7091 (http) with context path ''
seata-server    | 10:21:56.941  INFO --- [                     main] io.seata.server.ServerApplication        : Started ServerApplication in 10.721 seconds (JVM running for 12.844)
seata-server    | 10:21:57.856  INFO --- [                     main] i.s.core.rpc.netty.NettyServerBootstrap  : Server started, service listen port: 8091
seata-server    | 10:21:57.935  INFO --- [                     main] io.seata.server.ServerRunner             : seata server started in 989 millSeconds
`

registry.conf
`registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "IP:8848"
    namespace = "dev"
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
}

config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "nacos"

  nacos {
    serverAddr = "IP:8848"
    group = "DEFAULT_GROUP"
    namespace = "dev"
    username = "nacos"
    password = "nacos"
    dataId = "seata-server.properties"
  }
}
`
docker-compose.yml
`version: '3'

services:
seata-server:
    image: seataio/seata-server
    hostname: IP
    container_name: seata-server
    ports:
      - "8091:8091"
    environment:
      TZ: Asia/Shanghai
      SEATA_IP: IP
      SEATA_PORT: 8091
      SEATA_CONFIG_NAME: file:/root/seata-config/registry
    volumes:
      - /docker/seata/config:/root/seata-config
    privileged: true
    restart: always
`

nacos配置中心文件已创建

**Comment by a364176773** [comment]
用1.4.2

**Comment by Q3B0** [comment]
> 

1.4.2 设置SEATA_IP为外网ip后，nacos内的地址还是容器地址

**Comment by Been24** [comment]
****

> 用1.4.2

1.5.1也注册不了，我nacos版本2.1.0

**Comment by Been24** [comment]
> > 用1.4.2
> 
> 1.5.1也注册不了，我nacos版本2.1.0

ok,我切换挂载springboot配置文件可以了
