### ISSUE TITLE
https://github.com/seata/seata/pull/4408

### ISSUE THREAD

**Issue by Q3B0** [seata/seata#4604]
https://github.com/seata/seata/pull/4408

_Originally posted by @a364176773 in https://github.com/seata/seata/issues/4601#issuecomment-1123872146_

看了下1.4.2版本对应代码没有修改
是需要自己修改编译么？
是否有修改后的1.4.2 docker镜像？

**Comment by pengten** [comment]
拉源码把对应commit合并到1.4.2，然后编译。  自己找着pr改一次也行，没有单独的镜像

**Comment by a364176773** [comment]
都已经release的版本了，不可能会在上面改代码重新推的，建议后续迭代使用1.5.0的镜像，我们稍后会推出1.5.0的docker部署文档

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4408
