### ISSUE TITLE
事务提交后，数据回滚了

### ISSUE THREAD

**Issue by 18697970286** [seata/seata#4619]
使用版本1.4.2，有时候会出现以下问题：
调用了commit()，日志输出commit status: Begin，日志里没见有异常抛出，然后超时回滚了数据；
请问什么情况会出现commit后状态还是Begin？

**Comment by a364176773** [comment]
参与者没有决议权限，说明你用的是api方式，对api方式不熟悉的话，不要乱用，rm是没有决议权的

**Comment by 18697970286** [comment]
> 参与者没有决议权限，说明你用的是api方式，对api方式不熟悉的话，不要乱用，rm是没有决议权的

tm调用的commit()
![image](https://user-images.githubusercontent.com/64895204/170409803-cbb24797-fb4c-458d-a5ae-e8aed470a849.png)

**Comment by slievrly** [comment]
@18697970286 any further analysis?
