### ISSUE TITLE
事务提交返回TimeoutRollbacking未抛异常

### ISSUE THREAD

**Issue by luckyqiao** [seata/seata#4628]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
TM向TC发起事务提交时，TC返回了状态`TimeoutRollbacking`, 但没有抛出异常，导致TM认为事务提交成功，实际TC推动各个RM进行了回滚。

### Ⅱ. Describe what happened

None

### Ⅲ. Describe what you expected to happen
事务提交返回TimeoutRollbacking未抛异常

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

在事务中执行业务逻辑代码超出分布式事务的超时时长，就会发生

### Ⅴ. Anything else we need to know?
参考代码
- `io.seata.tm.api.TransactionalTemplate#execute`
- `io.seata.tm.api.DefaultGlobalTransaction#commit`

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.2
- OS :  CentOS
- Others:

**Comment by Bughue** [comment]
plz assign to me

**Comment by Bughue** [comment]
@luckyqiao  看看你说的跟这个是不是一个问题？https://github.com/seata/seata/issues/4372

**Comment by luckyqiao** [comment]
> @luckyqiao 看看你说的跟这个是不是一个问题？#4372

我发现的问题是在这里，提交事务时，事务并没有提交成功，但没有向业务代码抛出异常: 
https://github.com/seata/seata/blob/8f96afa3d4df5128ed80edae988e044c27e2f81a/tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java#L135

目前我遇到了两种情况：
- 如果在TM决议提交事务前，TC发现事务超时主动进行了回滚，TM在提交事务时，返回的事务状态为`Finished`, 但不会向业务代码抛出异常，导致业务代码认为事务提交成功。
- 如果在TM进行事务提交时，TC发现事务已经超时了，会返回`TimeoutRollbacking`和回滚所有分支事务，TM端也不会向业务代码抛出异常，导致业务代码认为提交成功

**Comment by Bughue** [comment]
> 

你碰到的应该和我的是一样的，所以总结一下，现在的问题是TM拿不到正确的结果对吗？而TC和RM都是正确的？

**Comment by luckyqiao** [comment]
> > 
> 
> 你碰到的应该和我的是一样的，所以总结一下，现在的问题是TM拿不到正确的结果对吗？而TC和RM都是正确的？

@Bughue 是的。事务本身回滚了，但TM认为事务提交了

**Comment by Bughue** [comment]
> > @luckyqiao 看看你说的跟这个是不是一个问题？#4372
> 
> @Bughue 我发现的问题是在这里，提交事务时，事务并没有提交成功，但没有向业务代码抛出异常:
> 
> https://github.com/seata/seata/blob/8f96afa3d4df5128ed80edae988e044c27e2f81a/tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java#L135
> 
> 目前我遇到了两种情况：
> 
> * 如果在TM决议提交事务前，TC发现事务超时主动进行了回滚，TM在提交事务时，返回的事务状态为`Finished`, 但不会向业务代码抛出异常，导致业务代码认为事务提交成功。
> * 如果在TM进行事务提交时，TC发现事务已经超时了，会返回`TimeoutRollbacking`和回滚所有分支事务，TM端也不会向业务代码抛出异常，导致业务代码认为提交成功

第一种情况，finish应该是因为TC早就回滚成功，而且自动任务甚至都把他给清干净了。按说TC不会提前这么多的，你们是真的遇到这种情况吗？是不是debug把他卡太久来验证的？
第二种情况，我提了个pr，应该可以修复这个问题。

**Comment by luckyqiao** [comment]
> 第一种情况，finish应该是因为TC早就回滚成功，而且自动任务甚至都把他给清干净了。按说TC不会提前这么多的，你们是真的遇到这种情况吗？是不是debug把他卡太久来验证的？ 第二种情况，我提了个pr，应该可以修复这个问题。

第一种情况是在压测时产生的，TC服务器由于性能不足，导致提交超时
