### ISSUE TITLE
exceptionHandleTemplate  didn't handle non-runtime exception

### ISSUE THREAD

**Issue by Bughue** [seata/seata#4630]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/3788653/169807844-ccccaa0b-a86b-474e-86f8-22b393ad0886.png">
在TM通信时返回异常，但TC没有打印异常
![image](![F814EE34-63FE-476A-852B-09AF92EFB24D](https://user-images.githubusercontent.com/3788653/170807919-b6a48551-65d7-453f-a2e0-cc98ca0c4306.png))

![2B31C05F-A77A-4011-9AB0-B203B60ED650](https://user-images.githubusercontent.com/3788653/170807942-b8a75682-a288-4abb-a4e7-0c3d3b831d5f.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by slievrly** [comment]
it will throw StoreException in  LogStoreDataBaseDAO#insertGlobalTransactionDO, and will be packaged as TransactionException in AbstractTCInboundHandler#handle.
