### ISSUE TITLE
logback-classic-1.2.0

### ISSUE THREAD

**Issue by Niuxiaobao** [seata/seata#4634]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Logback是一个 Java 应用程序的日志记录框架。
Logback存在远程代码执行漏洞，有编辑配置文件所需权限的攻击者可以制作恶意配置，允许执行从 LDAP 服务器加载的任意代码。

版本比对检测原理：检查当前系统中logback-classic版本是否在受影响版本内|版本比对检测结果：- logback-classic
当前安装版本：1.2.0
应用相关信息：
- 应用路径：/data/soft/seata/seata/seata-server-1.4.2/lib/logback-classic-1.2.0.jar
该主机存在此漏洞

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
将 Logback  升级到 1.2.9 及以上版本，下载地址：https://logback.qos.ch/download.html

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :  1.8
- Seata version:  1.4.2
- OS : liunx
- Others:

**Comment by a364176773** [comment]
这个漏洞对Seata应该无影响，如果你感兴趣的话可以提pr升级下这依赖，我们公司这边都已经升级1.2.9了，是平滑升级的

**Comment by Niuxiaobao** [comment]
> 这个漏洞对Seata应该无影响，如果你感兴趣的话可以提pr升级下这依赖，我们公司这边都已经升级1.2.9了，是平滑升级的

直接把logback-classic-1.2.0.jar替换成1.2.9版本就可以吗？ 会有别的问题吗

**Comment by a364176773** [comment]
> > 这个漏洞对Seata应该无影响，如果你感兴趣的话可以提pr升级下这依赖，我们公司这边都已经升级1.2.9了，是平滑升级的
> 
> 直接把logback-classic-1.2.0.jar替换成1.2.9版本就可以吗？ 会有别的问题吗

我测过，不会有什么问题

**Comment by a364176773** [comment]
<dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback-classic-version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>${logback-classic-version}</version>
            </dependency>
一起改成1.2.9就完事

**Comment by Smery-lxm** [comment]
please assign to me
