### ISSUE TITLE
compare row failed, rowKey {}, reason [newRow is null]

### ISSUE THREAD

**Issue by wgy1160754366** [seata/seata#4652]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
打debug调试发现前置镜像出现两个主键ID  后置镜像只有一个ID  导致主键被拼接成主键ID_主键ID  找不到后置镜像  所以一直回滚不了  控制台一直刷屏 compare row failed, rowKey {}, reason [newRow is null]

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

        this.enhanceModelMap(wfFormInfo, modelMap);
        String modelName = wfFormInfo.getFormKey();
        BaseSqlParser baseSqlParser = getSqlParser();
        String tableName = baseSqlParser.safeFormatTable(modelName);
        SqlTable table = SqlTable.of(tableName);
        Long pkValue = IdGenerator.nextId();
        // 填充主键
        modelMap.put(Cons.FieldName.id.name(), pkValue);
        // 字段映射
        InsertDSL<Map<String, Object>> insertDSL = SqlBuilder.insert(modelMap).into(table);
        for(Map.Entry<String, Object> entry : modelMap.entrySet()){
            if (com.diboot.workflow.form.config.Cons.SUB_FORM_MAP_KEY.equalsIgnoreCase(entry.getKey())) {
                continue;
            }
            String columnName = baseSqlParser.safeFormatColumn(entry.getKey());
            insertDSL.map(table.column(columnName)).toProperty(entry.getKey());
        }
        // 处理子表单数据
        Map<String, List<Map<String, Object>>> subFormMap = (Map<String, List<Map<String, Object>>>) modelMap.get(com.diboot.workflow.form.config.Cons.SUB_FORM_MAP_KEY);
        if (V.notEmpty(subFormMap)) {
            for(Map.Entry<String, List<Map<String, Object>>> entry : subFormMap.entrySet()){
                List<Map<String, Object>> subFormDataList = entry.getValue();
                if(V.notEmpty(subFormDataList)){
                    for(Map<String, Object> subformDataMap : subFormDataList){
                        // 填充关联字段id
                        subformDataMap.put(modelName+"_id", pkValue);
                        createSubFormData(entry.getKey(), subformDataMap);
                    }
                }
            }
        }
        // 构建insert sql
        InsertStatementProvider insertStatement = insertDSL.build().render(RenderingStrategies.MYBATIS3);
        // 执行insert
        int count = singleTableWriteMapper.insert(insertStatement);

    /**
     * 创建记录并返回主键ID（自增）
     * @param insertStatement
     * @return
     */
    @Options(useGeneratedKeys = true, keyProperty = "record.id")
    @InsertProvider(type= SqlProviderAdapter.class, method="insert")
    int insert(InsertStatementProvider insertStatement);

public interface InsertStatementProvider<T> {
    /**
     * Return the row associated with this insert statement.
     *
     * @return the row associated with this insert statement.
     * @deprecated in favor of {@link InsertStatementProvider#getRow()}
     */
    @Deprecated
    T getRecord();

    /**
     * Return the row associated with this insert statement.
     *
     * @return the row associated with this insert statement.
     */
    T getRow();

    /**
     * Return the formatted insert statement.
     *
     * @return the formatted insert statement.
     */
    String getInsertStatement();
}

debug看的insert语句：
insert into `df_drd00001` (`form_field_1`, `process_instance_id`, `create_by`, `id`) values (#{record.form_field_1}, #{record.process_instance_id}, #{record.create_by}, #{record.id})

       以上是构建insert语句代码片段
CREATE TABLE `df_drd00001`  (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'ID',
  `tenant_id` bigint NULL DEFAULT NULL COMMENT '租户ID',
  `process_instance_id` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '流程实例',
  `form_field_1` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '默认字段',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `create_by` bigint NULL DEFAULT 0 COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '默认表单' ROW_FORMAT = DYNAMIC;

以上是数据表  该表是由代码生成的数据表   配置flowable用做动态表单

### Ⅲ. Describe what you expected to happen
希望可以如期回滚

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. spring cloud alibaba 2021.1     seata1.5.1   flowable6.5
2. 尝试了几张类似动态生成的数据表都不可以回滚 不仅仅是df_drd00001

### Ⅴ. Anything else we need to know?
回滚失败是发生在我使用flowable工作流引擎审批任务，其他服务发生异常，工作流服务需要回滚审批任务操作，其他表都可以回滚，唯独生成的动态表单数据表插入的数据无法回滚 

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.1
- OS : 
- Others: windows10

**Comment by leonleonleonlu** [comment]
你可以尝试使用Mybatis BATCH 模式规避这个问题。

**Comment by a364176773** [comment]
sql不要带有''这种写法，导致去重失败，最终develop已经修了
