### ISSUE TITLE
AT模式下@GlobalTransactional注解的Service在第一次访问时，异常缓慢

### ISSUE THREAD

**Issue by wrathfuldawa** [seata/seata#4656]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
AT模式下@GlobalTransactional注解的Service在第一次访问时，异常缓慢
测试接口：
没有添加@GlobalTransactional时，首次访问时间大约在1s左右
添加@GlobalTransactional后，首次访问时间大约在3.s-4s左右

项目中实际的业务接口：
没有添加@GlobalTransactional时，首次访问时间大约在3s-4s左右
添加@GlobalTransactional后，首次访问时间大约在10s左右(已经超出)
### Ⅱ. Describe what happened
AT模式下@GlobalTransactional注解的Service在第一次访问时，异常缓慢
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
麻烦解答下，大约是什么原因导致的，或者是我哪里配置的有问题

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
客户端的seata配置：
#默认关闭seata,以防干扰单体服务,业务模块引用时修改为true
seata.enabled = false
#允许全局事务
seata.service.disable-global-transaction = false
#事务分组名称
seata.tx-service-group = csservice_tx_group
#事务分组与server集群映射关系
seata.service.vgroup-mapping.csservice_tx_group = seata-server
#注册类型
seata.registry.type = eureka
#注册中心地址
seata.registry.eureka.service-url = ${eureka.client.serviceUrl.defaultZone}
#注册名称
seata.registry.eureka.application = seata-server
seata.registry.eureka.weight = 1
#提交重试次数，默认1
seata.client.tm.commitRetryCount = 3
#回滚重试次数，默认1
seata.client.tm.rollbackRetryCount = 3
#lock冲突时回滚为false
seata.client.rm.lock.retry-policy-branch-rollback-on-conflict = true

seata-server的配置(启动了三个节点作为集群)：
#事务分组
service.vgroupMapping.csservice_tx_group = seata-server
service.enableDegrade = false
service.disableGlobalTransaction = false
#存储模式
store.mode = db
store.db.datasource = druid
store.db.dbType = mysql
store.db.driverClassName = com.mysql.jdbc.Driver
store.db.url = jdbc:mysql://10.19.1.206:3308/seata_server?useUnicode=true&rewriteBatchedStatements=true
store.db.user = root
store.db.password = Css@600536
store.db.minConn = 5
store.db.maxConn = 1000
store.db.globalTable = global_table
store.db.branchTable = branch_table
store.db.distributedLockTable = distributed_lock
store.db.queryLimit = 1000
store.db.lockTable = lock_table
store.db.maxWait = 30000

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.5.1
- OS :Linux
- Others:

**Comment by a364176773** [comment]
相关配置都是懒加载的，自己做下预热就完事了

**Comment by wrathfuldawa** [comment]
> 相关配置都是懒加载的，自己做下预热就完事了

不太懂预热，是指预热seata，还是预热微服务或者是接口，指的是所有加了全局事务的接口都要预热么，但是各个环境的接口的预热参数无法统一，无法形成统一的机制，麻烦指导下，

**Comment by pengten** [comment]
服务启动的时候，调接口跑一个事务链路

**Comment by wrathfuldawa** [comment]
已删除
