### ISSUE TITLE
seata v1.5.1 使用postgresql14,访问Console页面服务端报错

### ISSUE THREAD

**Issue by panhc1997** [seata/seata#4658]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata v1.5.1 使用postgresql14,访问Console页面服务端报错
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
13:28:59.795 ERROR --- [    http-nio-10005-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.seata.common.exception.StoreException: 错误: 字段 "global_table.gmt_create" 必须出现在 GROUP BY 子句中或者在聚合函数中使用
  位置：44] with root cause
==>
org.postgresql.util.PSQLException: 错误: 字段 "global_table.gmt_create" 必须出现在 GROUP BY 子句中或者在聚合函数中使用
  位置：44
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
        at io.seata.server.console.impl.db.GlobalSessionDBServiceImpl.query(GlobalSessionDBServiceImpl.java:113)
        at io.seata.server.console.controller.GlobalSessionController.query(GlobalSessionController.java:47)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : jdk1.8
- Seata version:  seata v1.5.1 
- OS : CentOS 7 
- Others: postgresql14

**Comment by YSF-A** [comment]
please assign it to me.

**Comment by azhsmesos** [comment]
> * [ ] 我已经搜索了这个存储库的[问题](https://github.com/seata/seata/issues)，并认为这不是重复的。
> 
> ### 一、问题描述
> seata v1.5.1 使用postgresql14,访问控制台页面服务端报错
> 
> ### Ⅱ．描述发生了什么
> 如果有异常，请附上异常跟踪：
> 
> ```
> 13:28:59.795 ERROR --- [    http-nio-10005-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.seata.common.exception.StoreException: 错误: 字段 "global_table.gmt_create" 必须出现在 GROUP BY 子句中或者在聚合函数中使用
>   位置：44] with root cause
> ==>
> org.postgresql.util.PSQLException: 错误: 字段 "global_table.gmt_create" 必须出现在 GROUP BY 子句中或者在聚合函数中使用
>   位置：44
>         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
>         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
>         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
>         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
>         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
>         at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
>         at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
>         at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
>         at io.seata.server.console.impl.db.GlobalSessionDBServiceImpl.query(GlobalSessionDBServiceImpl.java:113)
>         at io.seata.server.console.controller.GlobalSessionController.query(GlobalSessionController.java:47)
> ```
> 
> ### 三、描述你期望发生的事情
> ### 四、如何重现它（尽可能最小和精确）
> 1. xxx
> 2. xxx
> 3. xxx
> 
> ### Ⅴ. 还有什么我们需要知道的吗？
> ### Ⅵ. 环境：
> * JDK版本：jdk1.8
> * 席塔版本：席塔 v1.5.1
> * 操作系统：CentOS 7
> * 其他：postgresql14

请把您的代码总的sql部分贴出来，方便复现问题
