### ISSUE TITLE
how to use seata 1.5.1 in springcloud alibaba 2021.0.1?

### ISSUE THREAD

**Issue by 512744006** [seata/seata#4668]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by caozhiyuan** [comment]
https://budtech.yuque.com/docs/share/85bbde2d-44e3-4bda-a7f3-1ef0fe16ae79?#Ve6IL @512744006

**Comment by RoeGross** [comment]
> https://budtech.yuque.com/docs/share/85bbde2d-44e3-4bda-a7f3-1ef0fe16ae79?#Ve6IL @512744006

![图片](https://user-images.githubusercontent.com/42738826/178949437-87bce026-acc6-4484-bf9b-dd604a0cfd7b.png)
这选择nacos，不需要在下面填写补充nacos的信息吗？
