### ISSUE TITLE
Seata 0.9.0 TM Suspend When (concurrent requests) >= (datasource pool connection max-active)

### ISSUE THREAD

**Issue by a1104321118** [seata/seata#4691]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata version 0.9.0
druid version 1.2.8
mysql-connector-java version 8.0.25

The Service is

```java
@GlobalTransactional
public void service() {
      // local transaction
      transactionTemplete.execute(....);

     // callRpcService();
      
}
```

And The Test is 
```java
@Test
public void test_concurrent() {
      int druid_max_active = 100;  // in application.yml , there is an example 
      int concurrent = 100; 

      CountDownLatch countDownLatch = new CountDownLatch(1);

        for (int i = 0; i < concurrent ; i++) {
            new Thread(() -> {
           
                try {
                    countDownLatch.await();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                testService.service()
            }).start();
        }
        countDownLatch.countDown();
        TimeUnit.MINUTES.sleep(1);
      
}
```

if `druid_max_active` <= `concurrent`, the program looks like suspend, and local transaction is not commit;
if `druid_max_active` > `concurrent`, the program runs well;
if remove `@GlobalTransactional` ,even when `druid_max_active` <= `concurrent`, the program runs well;

### Ⅱ. Describe what happened

if `druid_max_active` <= `concurrent`, the program looks like suspend, and local transaction is not commit;
if `druid_max_active` > `concurrent`, the program runs well;
if remove `@GlobalTransactional` ,even when `druid_max_active` <= `concurrent`, the program runs well;

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  0.9.0
- OS : mac os
- Others:

**Comment by a364176773** [comment]
seata不会影响事务的一阶段是否提交的行为，并且建议你升级到最新版再做测试

**Comment by a1104321118** [comment]
您好  我已经收到你的邮件，谢谢！HR

**Comment by a1104321118** [comment]
> seata不会影响事务的一阶段是否提交的行为，并且建议你升级到最新版再做测试

那为什么 去掉 `@GlobalTransactional ` 注解之后，就不会有问题了呢？
因为公司目前使用的版本 是 0.9.0 ， 所以没有办法升级到最新版
