### ISSUE TITLE
Seata 不支持JDK17吗

### ISSUE THREAD

**Issue by adminSxs** [seata/seata#4703]
Java: 17
seata: 1.3
Springboot:  2.2.0.RELEASE

我用Java8启动项目没有任何问题，试用用JDK17就会报错,然后我在启动参数加入 `--add-opens java.base/java.lang=ALL-UNNAMED`,还是报错，移除seata依赖就能启动成功，加入就会报错

引入seata错误是:
```
Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @815b41f
```

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4434
