### ISSUE TITLE
seata1.4版本  fastjson   xstream有安全漏洞

### ISSUE THREAD

**Issue by zhaiyh131** [seata/seata#4725]
最近公司对安全漏洞看的很重  现在查出seata-server 1.4.1 版本有两个jar包出现安全漏洞： 要求 fastjson 版本大于1.2.80  xstream 版本要1.14+   这些参数是阿里云安全漏洞检测出来的，对我们公司有很大影响。能不能将seata-server 源码这两个jar报版本升级一下，然后发送一个jar包给我，非常感谢🙏
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/44602981/175351994-2e97913a-f21a-4327-999f-d4fc4087e8c1.png">

**Comment by zhaiyh131** [comment]
![Uploading image.png…]()

**Comment by GuoRanYiMao** [comment]
这件事解决了么 大佬
