### ISSUE TITLE
是否支持组合服务的分布式事务

### ISSUE THREAD

**Issue by clverhack** [seata/seata#4730]
大致如题，我方的微服务使用是这样，基础服务，如用户服务，订单服务，库存服务。都是有数据库本地事务的，也就是说能直接连接所属mysql数据库,
 在他们上游，有个组合服务，如APP 组合服务，这个服务没有直接的数据库连接。它只负责调用基础服务。
我希望在组合服务上代码放置 分布式事务的控制（既是：@globaltransaction）。
目前是组合服务上加上seata 1.5.1 jar 直接启动报错，另外请教官方是否支持这种使用方式。

**Comment by tanzzj** [comment]
当然是支持的，建议先看下官网教程

**Comment by clverhack** [comment]
那1.5.1 版本，目前启动直接报错呢， 说没有platformtransaction  
https://github.com/seata/seata/pull/4515 和这个问题一样，是不是下个版本会解决

**Comment by a364176773** [comment]
> 那1.5.1 版本，目前启动直接报错呢， 说没有platformtransaction #4515 和这个问题一样，是不是下个版本会解决

这个报错的服务可以引入1.4.2先，等1.5.2发布
