### ISSUE TITLE
seata 客户端后台日志打印已回滚，但是数据库里数据没有回滚

### ISSUE THREAD

**Issue by stonexthree** [seata/seata#4733]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### 具体情况
客户端后台日志打印已回滚，但是数据库里数据没有回滚。查看seata服务端后台日志，也有已回滚的信息。打断点调试发现，在执行数据库更新后异常抛出前，业务库下的undo_log没有数据。
### 异常代码
```
 @Override
    @GlobalTransactional
    public String reduceStock() {
        int currentStock = Integer.parseInt(stockMapper.getCurrentStock("01"));
        stockMapper.reduceStock("01",Integer.toString(currentStock-1));
        int i = 1/0;
        return "库存 -1";
    }
```
### 版本
|spring boot|2.6.3|
|--|--|
|spring cloud|2021.0.1|
|spring cloud alibaba|2021.0.1.0|
|seata 服务端|1.4.2|
|mysq|5.7|
|nacos|2.1.0|

_在百度和谷歌上都尝试搜索该问题，没有得到解决。_

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/overview/faq.html
