### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by novicate** [seata/seata#4741]
NullPointException:

class   io.seata.rm.datasource.util.JdbcUtils 

```
public static String getDbType(String jdbcUrl) {
        // parseFromJdbcUrl maybe return null
        return getDbTypeParser().parseFromJdbcUrl(jdbcUrl).toLowerCase();
}
```

**Comment by slievrly** [comment]
which database do you used ?

**Comment by novicate** [comment]
> which database do you used ?

高斯数据库 GaussDB

**Comment by a364176773** [comment]
你可以使用mysql的driver去连接试试吗？

**Comment by a364176773** [comment]
https://support.huaweicloud.com/gaussdb_faq/gaussdb_faq_0020.html
