### ISSUE TITLE
GlobalTransactionScanner在扫描ScopeBean进行Wrapper判断时报错

### ISSUE THREAD

**Issue by gaecfov** [seata/seata#4746]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

GlobalTransactionScanner执行wrapIfNecessary时，由于scopedTarget.mallOrderReader是Scope范围的，具体的代理对象是SimpleBeanTargetSource，所以在SimpleBeanTargetSource.getTarget()每次都会获取新的对象。在SpringBatch多个对象都是动态创建的，创建时是需要上下文信息来填充，而Seata进行getTarget()时没有Batch的上下文，导致出现异常。

### Ⅱ. Describe what happened

加入了seata时，服务启动初始化bean报错。

```
Just paste your stack trace here!
```
Error creating bean with name 'scopedTarget.mallOrderReader': Scope 'step' is
not active for the current thread; consider defining a scoped proxy for this
bean if you intend to refer to it from a singleton; nested exception is
java.lang.IllegalStateException: No context holder available for step scope
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean
(AbstractBeanFactory.java:372) ~
[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE] at
org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:202) ~
[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE] at
org.springframework.aop.target.SimpleBeanTargetSource.getTarget
(SimpleBeanTargetSource.java:35) ~
[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE] at
io.seata.spring.util.SpringProxyUtils.findTargetClass
(SpringProxyUtils.java:57) ~[seata-all-1.3.0.jar:1.3.0] at
io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary
(GlobalTransactionScanner.java:212) ~[seata-all-1.3.0.jar:1.3.0] ... 81
common frames omitted Caused by: java.lang.IllegalStateException: No context
holder available for step scope at
org.springframework.batch.core.scope.StepScope.getContext
(StepScope.java:167) ~[spring-batch-core-4.2.7.RELEASE.jar:4.2.7.RELEASE] at
org.springframework.batch.core.scope.StepScope.get(StepScope.java:99) ~
[spring-batch-core-4.2.7.RELEASE.jar:4.2.7.RELEASE] at
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean
(AbstractBeanFactory.java:360) ~
[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE] ... 85 common frames omitted

### Ⅲ. Describe what you expected to happen
当代理对象是SimpleBeanTargetSource类型时，直接使用getTargetClass获取实际的代理类即可。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 创建一个spring-batch示例项目
2. 引入seata配置
3. 创建一个ItemReader/ItemProcssor/ItemWriter
4. 启动项目

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4
- OS : macos 12.3
- Others:

**Comment by slievrly** [comment]
fixed in #2852

**Comment by gaecfov** [comment]
> fixed in #2852
Scaner检查器可以绕过特定场景这个问题，但是SpringProxyUtils.findTargetClass逻辑还是有问题的，如果SimpleBeanTargetSource代理的对象就是Scaner要检查的Bean，那么依然可能出现这个问题。

建议的findTargetClass这个方法可以兼容一下，如果代理对象是SimpleBeanTargetSource，class可以取SimpleBeanTargetSource.getTargetClass()

**Comment by a364176773** [comment]
> > fixed in #2852
> 
> Scaner检查器可以绕过特定场景这个问题，但是SpringProxyUtils.findTargetClass逻辑还是有问题的，如果SimpleBeanTargetSource代理的对象就是Scaner要检查的Bean，那么依然可能出现这个问题。
> 
> 建议的findTargetClass这个方法可以兼容一下，如果代理对象是SimpleBeanTargetSource，class可以取SimpleBeanTargetSource.getTargetClass()
> 
> 实际上AbstractBeanFactoryBasedTargetSource的子类对象都可能在getTarget()时实例化新的bean对象，所以应该都可以直接使用getTargetClass

你可以为此提个pr来兼容处理吗?

**Comment by gaecfov** [comment]
我翻了遍源码，最新的发现已经在#3709处理了，这个可以忽略了。

**Comment by a364176773** [comment]
是的，我印象中这个问题应该是被修了，所以一开始我想你帮忙验证下最新版版本
https://github.com/seata/seata/issues/3709
