### ISSUE TITLE
Seata中有基于1.5.1+shardingsphere的读写分离吗？

### ISSUE THREAD

**Issue by zgl1011** [seata/seata#4747]
项目中之前是使用seata1.4.1+sharding-transaction-base-seata-at 4.1.1能够实现事务回滚，但是升级到seata 1.5.1 读写分离事务不回滚了，请问是需要其他配置吗？

**Comment by a364176773** [comment]
应该跟版本无关，建议看官网不回滚的faq先自行排查下

**Comment by a364176773** [comment]
原来如此,我因为你是at模式,tcc的话可能是由于开启了本地事务导致的不兼容,tcc的防悬挂是分支注册前开启本地事务,然后进行防悬挂的一些动作,我估计是因为内部存在多数据源,tcc用的数据源非master,或者准确分片的datasource,导致无法正常使用,请问是否有什么报错信息?

**Comment by zgl1011** [comment]
> 原来如此,我因为你是at模式,tcc的话可能是由于开启了本地事务导致的不兼容,tcc的防悬挂是分支注册前开启本地事务,然后进行防悬挂的一些动作,我估计是因为内部存在多数据源,tcc用的数据源非master,或者准确分片的datasource,导致无法正常使用,请问是否有什么报错信息?

没有报错

**Comment by a364176773** [comment]
> > 原来如此,我因为你是at模式,tcc的话可能是由于开启了本地事务导致的不兼容,tcc的防悬挂是分支注册前开启本地事务,然后进行防悬挂的一些动作,我估计是因为内部存在多数据源,tcc用的数据源非master,或者准确分片的datasource,导致无法正常使用,请问是否有什么报错信息?
> 
> 没有报错

你是用tcc还是at?先检查分支事务有没有注册,日志都有的,从日志方面排查

**Comment by xingfudeshi** [comment]
Temporarily closed due to no reply for a long time, welcome to discuss at any time.
