### ISSUE TITLE
mysql使用datetime类型数据 jackson序列号异常

### ISSUE THREAD

**Issue by edifangyi** [seata/seata#4756]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

表中使用类型：datetime 字段，com.fasterxml.jackson.databind.exc.InvalidDefinitionException 异常

### Ⅱ. Describe what happened

![image](https://user-images.githubusercontent.com/12421552/177907364-aea58b35-e0c0-4543-8b27-00e12c6df9fb.png)

### Ⅲ. Describe what you expected to happen

使用：Seata 1.3.0 就没有该问题，但是为什么使用1.4.2  不支持序列化？是有什么原因吗？
查询后，有两种方案解决
1、数据库中不使用 datetime 数据类型（个人觉得做不到）
2、修改undo_log默认的序列化方式
undo_log 默认的序列化方式 jackson，在seata中使用jackson序列化方式会有问题，那么我们修改 kryo 序列化方式就可以解决这个问题。（感觉好麻烦啊···）

`org.springframework.jdbc.UncategorizedSQLException: 
### Cause: java.sql.SQLException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type java.lang.Object (by serializer of type com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["afterImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[14]->io.seata.rm.datasource.sql.struct.Field["value"])
; uncategorized SQLException; SQL state [null]; error code [0]; java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type java.lang.Object (by serializer of type com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["afterImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[14]->io.seata.rm.datasource.sql.struct.Field["value"]); nested exception is java.sql.SQLException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Type id handling not implemented for type java.lang.Object (by serializer of type com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer) (through reference chain: io.seata.rm.datasource.undo.BranchUndoLog["sqlUndoLogs"]->java.util.ArrayList[0]->io.seata.rm.datasource.undo.SQLUndoLog["afterImage"]->io.seata.rm.datasource.sql.struct.TableRecords["rows"]->java.util.ArrayList[0]->io.seata.rm.datasource.sql.struct.Row["fields"]->java.util.ArrayList[14]->io.seata.rm.datasource.sql.struct.Field["value"])
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy138.insert(Unknown Source)`

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.4.2
- OS :Windows 10
- Others: seata-service 1.4.2/1.5.1

**Comment by jsbxyyx** [comment]
可以参照seata-plugin里面的项目自己写插件

**Comment by edifangyi** [comment]
> 可以参照seata-plugin里面的项目自己写插件

我把 seata 升级到 1.5.1 没得用··· 数据库也用的 mysql driver8.0.12版本，麻了

**Comment by caohdgege** [comment]
same with #4757
