### ISSUE TITLE
升级到1.5.1版本后，还是会有jackson序列化问题

### ISSUE THREAD

**Issue by edifangyi** [seata/seata#4757]
1.4.2及以下版本回滚时抛出Cannot construct instance of `java.time.LocalDateTime` ？

A:升级1.5.0及以上版本

我是用的版本：

spring-boot.version 2.6.3
spring-cloud.version 2021.0.1
spring-cloud-alibaba.version 2021.0.1.0
seata-spring-boot-starter.version 1.5.1

mysql:8.0.12

![image](https://user-images.githubusercontent.com/12421552/177944114-41e19489-c516-4278-8aff-4d30131158e6.png)

异常：

![image](https://user-images.githubusercontent.com/12421552/177944390-f7b0e45d-6ff9-4ec9-ac12-f6aeea3870cb.png)

请问具体怎么操作可以解决这个问题

**Comment by edifangyi** [comment]
![image](https://user-images.githubusercontent.com/12421552/177949026-5d90a307-b31b-4ed2-967d-44eb6d2e0615.png)


服务端用的默认配置

**Comment by a364176773** [comment]
这个不是java.time.LocalDateTime的问题，数据库表去一下隐私信息，发一下建表sql看下，异常堆栈完整发成文字版再看下

**Comment by edifangyi** [comment]
> 这个不是java.time.LocalDateTime的问题，数据库表去一下隐私信息，发一下建表sql看下，异常堆栈完整发成文字版再看下

问题解决了，升级 seata，基础包里是1.5.1， 但是其他依赖这个基础包的微服务依赖的却是1.4.2

**Comment by edifangyi** [comment]
> 这个不是java.time.LocalDateTime的问题，数据库表去一下隐私信息，发一下建表sql看下，异常堆栈完整发成文字版再看下

![Uploading 1IWAU${Q~}{4)7OQ@`90SMT.png…]()

**Comment by a364176773** [comment]
> > 这个不是java.time.LocalDateTime的问题，数据库表去一下隐私信息，发一下建表sql看下，异常堆栈完整发成文字版再看下
> 
> 问题解决了，升级 seata，基础包里是1.5.1， 但是其他依赖这个基础包的微服务依赖的却是1.4.2

原来如此,那我关闭这个issue了
