### ISSUE TITLE
使用seata-all时怎么使用@Transactional来处理本地事务

### ISSUE THREAD

**Issue by happyycm** [seata/seata#4773]
JDK 1.8
SEATA: seata-all 1.5.1
shardingsphere-jdbc-core : 5.1.2

现在因为要集成shardingsphere，使用了seata-all来处理分布式事务
正常回滚没有问题，但是被调用方添加@Transactional注解后，被调用方的事务回滚失效。(查看server日志，被调用方未注册)
了解了QA中的22项，是基于springboot-starter的，如果使用seata-all在有shardingsphere的情况下应该怎么处理呢？
相关代码如下：
调用方
`
@GetMapping("order")
    public void order(@PathVariable boolean rollback) throws Exception {
        TransactionTypeHolder.set(TransactionType.BASE);
        Connection connection = null;
        try {
            connection = dataSource.getConnection();
            connection.setAutoCommit(false);

            //处理业务逻辑
            //...
            String xid = RootContext.getXID();

            //调用其它业务，主动传递xid
            productClient.do(xid);
        } catch (Exception e) {
            if (Objects.nonNull(connection) && !connection.isClosed()) {
                connection.rollback();
            }
        } finally {
            if (Objects.nonNull(connection) && !connection.isClosed()) {
                connection.close();
            }
            TransactionTypeHolder.clear();
        }
    }
`

被调用方
`
@Transactional(rollbackFor = Exception.class)
    @GetMapping("product/{xid}")
    public void do(@PathVariable String xid) {
        //接收并绑定xid
        RootContext.bind(xid);
        TransactionTypeHolder.set(TransactionType.BASE);
        try {
            //处理业务
            //...
        } finally {
            TransactionTypeHolder.clear();
        }
    }
`

望不吝赐教

**Comment by a364176773** [comment]
跟Transactional没什么关系，跟你有没有使用xid传递和数据源代理有关，建议根据sharding-sphere官方的demo走
