### ISSUE TITLE
Seata1.5.2 RootContext.getXID()拿不到值

### ISSUE THREAD

**Issue by pptech-dev** [seata/seata#4781]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
RootContext.getXID()拿不到值，RootContext.entities() 大小为空

### Ⅱ. Describe what happened
tcc模式，confirm阶段，如下图所示。但奇怪的是 businessActionContext是有值的

![image](https://user-images.githubusercontent.com/84951843/179169392-b051e83d-ee01-4ba9-91b0-ff12922cfe2c.png)

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS : macOS
- Others:

**Comment by pptech-dev** [comment]
但通过以下，是可以拿到值的
```
String txId = MDC.get(RootContext.MDC_KEY_XID);
String branchId = MDC.get(RootContext.MDC_KEY_BRANCH_ID);
// 以上两个值都可以拿得到
```

**Comment by a364176773** [comment]
二阶段在businessactioncontext是,rootcontext是一阶段用

**Comment by a364176773** [comment]
> 但通过以下，是可以拿到值的
> 
> ```
> String txId = MDC.get(RootContext.MDC_KEY_XID);
> String branchId = MDC.get(RootContext.MDC_KEY_BRANCH_ID);
> // 以上两个值都可以拿得到
> ```

这个mdc是链路追踪用的,完全不是一个用处的东西

**Comment by pptech-dev** [comment]
> > 但通过以下，是可以拿到值的
> > ```
> > String txId = MDC.get(RootContext.MDC_KEY_XID);
> > String branchId = MDC.get(RootContext.MDC_KEY_BRANCH_ID);
> > // 以上两个值都可以拿得到
> > ```
> 
> 这个mdc是链路追踪用的,完全不是一个用处的东西

如果我想在try阶段拿branchId，是不是只能使用 @a364176773 
```
String branchId = MDC.get(RootContext.MDC_KEY_BRANCH_ID);
```
