### ISSUE TITLE
seata注册nacos时的ip地址取的不对！

### ISSUE THREAD

**Issue by beelzebub2006** [seata/seata#4789]
本地ip地址如下：
br-61e4477f77a7: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.27.0.1  netmask 255.255.0.0  broadcast 172.27.255.255
        inet6 fe80::42:a6ff:fe01:f580  prefixlen 64  scopeid 0x20<link>
        ether 02:42:a6:01:f5:80  txqueuelen 0  (Ethernet)
        RX packets 95063900  bytes 473753553554 (441.2 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 96286004  bytes 473726658994 (441.1 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br-697faf123793: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.64.1  netmask 255.255.240.0  broadcast 192.168.79.255
        inet6 fe80::42:8bff:fec9:7b22  prefixlen 64  scopeid 0x20<link>
        ether 02:42:8b:c9:7b:22  txqueuelen 0  (Ethernet)
        RX packets 12196581  bytes 225248945270 (209.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10216647  bytes 757570693 (722.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br-f70824d87f6b: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.22.0.1  netmask 255.255.255.0  broadcast 172.22.0.255
        inet6 fe80::42:9cff:fe15:dd55  prefixlen 64  scopeid 0x20<link>
        ether 02:42:9c:15:dd:55  txqueuelen 0  (Ethernet)
        RX packets 39556252  bytes 20058886500 (18.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 34813505  bytes 11424197378 (10.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:c5ff:fea7:dabb  prefixlen 64  scopeid 0x20<link>
        ether 02:42:c5:a7:da:bb  txqueuelen 0  (Ethernet)
        RX packets 931152924  bytes 666439990351 (620.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1019545594  bytes 3302324075061 (3.0 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.25.217.72  netmask 255.255.240.0  broadcast 172.25.223.255
        inet6 fe80::216:3eff:fe29:6aab  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:29:6a:ab  txqueuelen 1000  (Ethernet)
        RX packets 3402689680  bytes 4042048817220 (3.6 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1103138080  bytes 811222294847 (755.5 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

但是seata注册到nacos里面读取的是192.168.64.1 这个ip地址。

把application.yml文件修改了也不行，修改如下：
spring:
  application:
    name: seata-server
  cloud:
    inetutils:
      ignored-interfaces: br-*
      preferred-networks: 172.25
    nacos:
      discovery:
        network-interface: eth0
        networkInterface: eth0
        ip: 172.25.217.72
        #port: 8091

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata

seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    nacos:
      # nacos ip地址
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username:
      password:
      ##if use MSE Nacos with auth, mutex with username/password attribute
      #access-key: ""
      #secret-key: ""
      # 读取nacos上的配置文件
      data-id: seatServer.properties
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    preferred-networks: 172.25.*
    nacos:
      application: seata-server
      # nacos ip地址
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      cluster: default

启动的时候加上-h 172.25.217.72也不行，这是为啥呢？

**Comment by a364176773** [comment]
升级1.5.2或者export SEATA_IP=xxxx
