### ISSUE TITLE
druid数据源问题

### ISSUE THREAD

**Issue by liruhui** [seata/seata#4808]
## 现象说明
```properties
  使用seata默认的AT模式，如果数据源使用springBoot默认的HikariDataSource  事务不回滚    使用DruidDatasource数据源事务会回滚
  并且配置DruidDataSource的方式不同 有的事务回滚 有的事务不回滚
```
## 这样设置会回滚
![QQ截图20220722164216](https://user-images.githubusercontent.com/24687986/180400562-adb56390-70b7-485e-8449-37388b547c01.png)

## 这样设置不会回滚
![QQ截图20220722164354](https://user-images.githubusercontent.com/24687986/180400816-41a96595-e99f-4912-87f4-856cb71e7731.png)

## 问题咨询
```properties
   1: 必须得使用DruidDataSource吗?  使用其他的数据源怎么样才能回滚 
   
   2: 为什么在配置文件中配置type 不会回滚
   
```

**Comment by a364176773** [comment]
HikariDataSource可以回滚没有问题，检查数据源代理
不回滚问题：https://seata.io/zh-cn/docs/overview/faq.html   q42
