### ISSUE TITLE
seata启动死锁

### ISSUE THREAD

**Issue by lrydl** [seata/seata#4809]
java version: 1.8
seata version: spring-cloud-starter-alibaba-seata 2.2.6.RELEASE
os : centos7

seata启动timeCheck线程和main线程死锁问题：

seata的GlobalTransactionScanner类的initClient方法最终会调用到AbstractNettyRemotingClient#init，如下：
![图片](https://user-images.githubusercontent.com/28042220/180408837-7c2bb525-91ac-42a2-b125-3d9da4a29cdd.png)
reconnect方法最终调用到NacosRegistryServiceImpl#lookup，如下:
![图片](https://user-images.githubusercontent.com/28042220/180409438-31b4ada3-4b4a-43a9-9c35-5b0046386881.png)

**综上所述：timecheck线程（延迟60s执行，间隔10s）会先请求seata LOCK_OBJ，再请求spring单例锁。**

seata的代理数据源增强aop代码如下：
![图片](https://user-images.githubusercontent.com/28042220/180410068-369b59c0-a88d-40e8-bb50-69337dbf5b04.png)
![图片](https://user-images.githubusercontent.com/28042220/180410174-c4598d81-6fb6-477d-be4e-8cebae19f2a3.png)
![图片](https://user-images.githubusercontent.com/28042220/180410363-12a91bba-775a-4f42-a356-bfd6852da0cc.png)
只要main线程代码走到了SeataAutoDataSourceProxyAdvice的invoke方法，那么此时已经持有了spring单例锁，当他new DataSourceProxy的时候又想去获取seata的LOCK_OBJ锁。

**综上所述：main线程持有了spring锁，想获取seata的LOCK_OBJ锁。**

综上两个综上所述：timecheck线程先获取seata的LOCK_OBJ锁，再获取spring锁，main线程先获取spring锁，再获取seata的LOCK_OBJ锁。故当应用启动慢时（60s还没启动成功，就有可能发生main线程和timecheck线程死锁的现象）。

通过如下修改，可以让我们本机回显这个bug：
![图片](https://user-images.githubusercontent.com/28042220/180411629-a6c9d559-c8ff-45a8-885f-513a9bd7c5ea.png)

官方能否尽快修复这个bug

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4107
