### ISSUE TITLE
seata1.4.2服务，不定时出现连接数据库异常问题，seata服务器跟报错数据库网络是通的，请问大佬是啥原因

### ISSUE THREAD

**Issue by liujunlin5168** [seata/seata#4811]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata1.4.2服务，不定时出现连接数据库异常问题，seata服务器跟报错数据库网络是通的，请问大佬是啥原因
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
![Tone](https://user-images.githubusercontent.com/20855640/180738936-3bb17971-0d58-46f7-854b-88f22a2e38b6.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.2
- OS :linux
- Others:

**Comment by a364176773** [comment]
driver和数据库版本可能有点影响关系，这个是标准的使用druid构建的datasource，连接串那块要加什么参数啥的自己都可以加哈

**Comment by slievrly** [comment]
@liujunlin5168 Pls provide more information. What are the database and DB-Connector-Driver versions?
