### ISSUE TITLE
seata1.4.2版本安全漏洞 fastjson xstream有安全漏洞 

### ISSUE THREAD

**Issue by GuoRanYiMao** [seata/seata#4814]
我们公司所有服务都在咱们阿里云上，阿里云漏洞扫描seata 引用fastjson 有安全漏洞 seata-server还用了xstream 也有问题
这个大伙都是怎么解决的啊
整体升1.5+能解决么 
还是在1.4.2基础上直接替换fastjson包，换包这条路走得通么

**Comment by a364176773** [comment]
可以直接替换相关jar，或者升级1.5.2
