### ISSUE TITLE
Tm端的发起事务可以支持不使用at模式，只在分支事务处理的时候进行at或者tcc模式的处理。

### ISSUE THREAD

**Issue by iron2022** [seata/seata#4824]
## Why you need it?
为了提升业务性能，避免不必要的程序处理，希望能支持 事务发起端不自动进行at代理的处理。

## How it could be?
举例：
3个应用，P-A,P-B,P-C，这3个应用都拥有TM，RM的角色，同时不同的接口提供的事务方式不同，同时支持AT和TCC的方式。
比如1个业务操作，整体流程是这样的，P-A 是事务发起方，在对应的Service 上面增加了@GlobalTransaction的注解 和 @Transaction 本地事务注解。
然后会调用P-B的at模式的接口，再调用 P-C 的tcc 模式的接口。

对于P-A的应用，本地增加了@Transaction的注解，在整个service的处理过程中，如果有报错，会通知TC端进行全局事务回滚。如果没有报错，会通知全局事务提交，但是在提交的时候，还会默认按照AT的模式生成镜像。对于生成的这个镜像，正常来说是没有什么用处的，是否可以考虑在TM端，不自动进行AT模式的处理。

**Comment by wangliang181230** [comment]
这个需求，存在一个临界时间问题。
TC端超时检测，与TM端一阶段提交一起发生。
如果TM端超时检测快一些，就会把P-B和P-C的分支先回滚掉了。
而P-A的本地事务因为你不希望创建分支，而被超时回滚忽略了。

**Comment by wangliang181230** [comment]
所以，并不建议省略这个AT分支的创建。

**Comment by wangliang181230** [comment]
如果还有什么建议，请再开启此issue，谢谢。
