### ISSUE TITLE
使用高版本JDK，SEATA会出现druid相关警告

### ISSUE THREAD

**Issue by esbug** [seata/seata#4837]
### 1、问题
我的项目使用JDK17，但是启动会有一个关于druid相关的异常，不知道会不会影响到seata AT模式的正常使用？
### 2、是否有解决方案
目前我使用的VM环境配置才能启动的
```
--add-opens java.base/java.lang=ALL-UNNAMED
```
想问一下是否有更好的解决方法

**Comment by a364176773** [comment]
什么异常？
