### ISSUE TITLE
用默认的HikariDataSource 注册不上

### ISSUE THREAD

**Issue by McGradyLinH** [seata/seata#4844]
用HikariDataSource 获取不到resourceIds

**Comment by a364176773** [comment]
springboot版本及seata版本是哪个

**Comment by McGradyLinH** [comment]
> springboot版本及seata版本是哪个

2.3.12   1.4.2

**Comment by a364176773** [comment]
> > springboot版本及seata版本是哪个
> 
> 2.3.12 1.4.2

要么切换手动代理试试，要么升级1.5.2试试，某些版本的hikari自动代理存在问题
