### ISSUE TITLE
task session manager chaos

### ISSUE THREAD

**Issue by Bughue** [seata/seata#4857]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
目前SessionHolder里面带有4个session manager（root/async_commit/retry_commit/retry_rollback），这4个manager在很多场景下都等价，所以root以外的manager大多被滥用，造成代码难读和维护困难，在进行新功能开发时也无法收敛到同一处，例如:
以下两个写法是等价的（都是移除全局事务）

```
SessionHolder.getRetryCommittingSessionManager().removeGlobalSession(committingSession);
SessionHolder.getRootSessionManager().removeGlobalSession(committingSession);
```

但以下两个写法是不一定等价的（在db/redis模式下用root是真正的新增，而用其他的则是更新，这和方法名称表达也不一致。）
```
SessionHolder.getRetryCommittingSessionManager().addGlobalSession(session);
SessionHolder.getRootSessionManager().addGlobalSession(session);
```

另一个问题是在globalsession里面addSessionLifecycleListener，可能会让globalsession持有多个manager，在某些操作（比如changestatus的时候，就会出现调用多次manager的情况，如果他们行为一致，那就是多余操作，如果他们行为不一致，那后果可能更严重）

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
建议分两步进行
第一步将 globalsession的增删查改操作都改回root manager（方便与之有关的功能编写）
第二步是以后真正把这个listener机制废除

**Comment by a364176773** [comment]
sessionMnager改造终态分4步
1.将分散的不同功能的sessionManager合并为rootsessionmanager简化学习和使用成本 
https://github.com/seata/seata/pull/4858
2.将listener与sessionmanager分离,各司其职,将原先由onxxxx的listener方法改为直接调用sessionmanager对应方法
https://github.com/seata/seata/pull/4881
3.将globalsession中的业务逻辑转移至sessionmanager中,globalsession为一个do角色
4.将sessionmanager中的sessionmanager做进一步的优化,filesessionmanager进行对不同status的globalsession分门别类处理,加快file的增删改查效率

**Comment by a364176773** [comment]
![lQDPJxbRVKJ3MnzNBCPNBASwSvLyDJLqpPgDWAiYXECJAA_1028_1059](https://user-images.githubusercontent.com/19943636/198300251-df45ee89-380f-4bab-9940-e814243c3150.jpg)
