### ISSUE TITLE
Trying to use two separate databases, can you provide a distributed transaction example of multiple libraries?

### ISSUE THREAD

**Issue by zhuyu19911016** [seata/seata#486]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by zhuyu19911016** [comment]
试了用2个单独数据库不行，能否提供个多个库的分布式事务的示例

**Comment by slievrly** [comment]
> 试了用2个单独数据库不行，能否提供个多个库的分布式事务的示例

https://github.com/fescar-group/fescar-samples

**Comment by slievrly** [comment]
You can configure the database connection string to be different

**Comment by zhuyu19911016** [comment]
谢谢你的回答，我有A、B 两个服务，请求先到A，A再调B，如果我在A源头服务中抛出 RuntimeException异常则会回滚，控制台输出 PhaseTwo_Rollbacked 测试成功 ，如果我在 B 服务中抛出异常，则分布式事务无法回滚，测试失败，此时A的控制台输出 AT Branch commit result: PhaseTwo_Committed

**Comment by zhuyu19911016** [comment]
Dude, can you answer the question above?

**Comment by slievrly** [comment]
@zhuyu19911016 use which example? can dingding ping me?

**Comment by zhuyu19911016** [comment]
According to the example configuration, but I use Spring Cloud, you Dingding number, I add you, thank yo

**Comment by slievrly** [comment]
dingTalk group：23171167
