### ISSUE TITLE
Mybatis-plus整合seata全局事务不生效  jdbcTemplate则生效

### ISSUE THREAD

**Issue by eureka1986** [seata/seata#4870]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
项目基于spring-cloud-alibaba搭建，通过引入spring-cloud-starter-alibaba-seata引入seata.发现通过mybatis-plus全局事务无法生效。
具体表现是global_table中有全局事务记录，branch_table表中没有分支事务的记录，当然业务系统DB中的undo_log也是没有回滚数据的。  但如果换成jdbcTemplate则一切正常，全局事务生效。

看官网文档对于ORM框架支持的描述，seata事务模式是针对jdbc标准接口操作的拦截和增强。
**Seata 虽然是保证数据一致性的组件，但对于 ORM 框架并没有特殊的要求，像主流的Mybatis，Mybatis-Plus，Spring Data JPA, Hibernate等都支持。这是因为ORM框架位于JDBC结构的上层，而 Seata 的 AT,XA 事务模式是对 JDBC 标准接口操作的拦截和增强。**

代码如下:
 @Override
    public String payAdd(Pay pay) {
        //通过mybatis-plus全局事务无法生效
        return payMapper.insert(pay)>0?"操作成功":"操作失败";

       //通过jdbcTemplate全局事务是生效的
//        String sql = "insert into pay(account,amount,create_time)values(?,?,?)";
//        Object[] params = {pay.getAccount(),pay.getAmount(),pay.getCreateTime()};
//        return jdbcTemplate.update(sql, params)>0?"操作成功":"操作失败";

    }

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
检查数据源代理，且代理的数据源有没有被mysql的sessionfactory使用

**Comment by eureka1986** [comment]
主键问题。mysql设置了主键AUTO_INCREMENT  mybatis-plus也设置了AUTO_INCREMENT。
