### ISSUE TITLE
A component required a bean of type 'io.seata.server.console.service.BranchSessionService' that could not be found.

### ISSUE THREAD

**Issue by xql80329** [seata/seata#4876]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/110291366/185594829-394afad7-d6cf-4d2d-a7be-a89c7cee177f.png)

A component required a bean of type 'io.seata.server.console.service.BranchSessionService' that could not be found.

### Ⅴ. Anything else we need to know?
Error reported by Nacos integration

### Ⅵ. Environment:

- JDK version : jdk1.8
- Seata version:  seata1.5.2
- OS :win10
- Others: nacos 2.1

**Comment by Wgx1220** [comment]
seata:
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: nacos
    # nacos:
    #   server-addr: 127.0.0.1:8848
    #   namespace: 01dd2ba7-be6f-4b2b-8bc3-91fc793aa07a
    #   group: SEATA_GROUP
    #   username: nacos
    #   password: nacos
    #   ##if use MSE Nacos with auth, mutex with username/password attribute
    #   #access-key: ""
    #   #secret-key: ""
    #   data-id: seataServer.properties
