### ISSUE TITLE
配置中的registry.conf文件是否可以写在配置中心

### ISSUE THREAD

**Issue by youngsapling** [seata/seata#4885]
## Why you need it?
registry.conf文件必须在项目中硬编码

## How it could be?
是否可以由配置中心拉取这个文件的内容

**Comment by a364176773** [comment]
https://github.com/seata/seata/tree/develop/script/config-center

**Comment by youngsapling** [comment]
> https://github.com/seata/seata/tree/develop/script/config-center

可是conf.type的这个配置，是在registry.conf文件中配置的，我的疑问是，这个registry.conf文件，是否可以走配置中心。
我看到源码中 ConfigurationFactory类是从本地读取File文件的方式获取到conf.type的

**Comment by a364176773** [comment]
不行，这个配置文件就是在本地告诉seata你的配置中心是什么，如果这个走配置中心seata怎么知道自己去读哪里的配置中心？
