### ISSUE TITLE
1.5.2版本注册不到nacos中是什么原因？

### ISSUE THREAD

**Issue by YuWanJun** [seata/seata#4886]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/25860944/186568608-d05967d7-e182-449f-9054-ede91b017874.png)
![image](https://user-images.githubusercontent.com/25860944/186568636-a8e71587-9518-49ea-81fb-9064d7a6aaf4.png)
![image](https://user-images.githubusercontent.com/25860944/186568672-506439b7-d6c3-4e62-b5e6-f55996c3eebe.png)
![image](https://user-images.githubusercontent.com/25860944/186568684-a15d50ac-662c-48b6-90d1-204be19044bb.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
建议重新看下官网的docker部署，1.5和以往部署方式已经不同了
