### ISSUE TITLE
help！！！ 1.5.2  TCC模式  try调用超时为什么会产生3个branch_id

### ISSUE THREAD

**Issue by zxd1996-stack** [seata/seata#4888]
![image](https://user-images.githubusercontent.com/66668085/186806267-df5b0fa8-4220-4f41-adb4-0698fab4e978.png)

**Comment by a364176773** [comment]
你rpc框架重试了

**Comment by a364176773** [comment]
最佳实践->tcc的注解写在provider的service上，并且在provider的controller等位置再调用service之前进行幂等处理避免进入seata-tcc注解切面进行多次分支事务注册

**Comment by zxd1996-stack** [comment]
好的，我试试

**Comment by zxd1996-stack** [comment]
这个幂等一般都是靠记录xid来实现的吧，但是这里的controller如何取到这个xid,而且1.5.2不是新增了tcc_fence_log表吗，里面已经记录了日志，那为什么io.seata.rm.tcc.TCCFenceHandler这个处理类里面没有做相应的处理，比如说tcc_fence_log表的(xid,action_name)做唯一索引，当rpc重试的时候插入一条记录抛出索引重复异常，说明该分支事务已经进入下一个步骤，也就不会执行和记录新的分支事务。难道说这样做会产生别的问题（可能我考虑的比较片面）

**Comment by zxd1996-stack** [comment]
> 这个幂等一般都是靠记录xid来实现的吧，但是这里的controller如何取到这个xid,而且1.5.2不是新增了tcc_fence_log表吗，里面已经记录了日志，那为什么io.seata.rm.tcc.TCCFenceHandler这个处理类里面没有做相应的处理，比如说tcc_fence_log表的(xid,action_name)做唯一索引，当rpc重试的时候插入一条记录抛出索引重复异常，说明该分支事务已经进入下一个步骤，也就不会执行和记录新的分支事务。难道说这样做会产生别的问题（可能我考虑的比较片面）
