### ISSUE TITLE
不支持连表更新？

### ISSUE THREAD

**Issue by MaiJiantian** [seata/seata#4890]
![image](https://user-images.githubusercontent.com/35630335/187334174-3cd35704-a932-403d-a6d7-75bb1e871fdc.png)
![企业微信截图_16618237468626](https://user-images.githubusercontent.com/35630335/187334228-5daae9ab-046d-4fb0-9c20-dc1f6847f777.png)

**Comment by MaiJiantian** [comment]
在

**Comment by a364176773** [comment]
1.3本身就不支持，只不过框架层没拦截，1.6会做相关支持
https://github.com/seata/seata/pull/4518
