### ISSUE TITLE
seata1.5.2版本Dockerfile不能使用

### ISSUE THREAD

**Issue by liuqiyang7** [seata/seata#4891]
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/63906369/187389256-aa6c8086-fa3c-4819-864c-7d0eba1ac2d8.png">
1.5.2版本执行faq中的打包命令之后没有bin目录，registry.conf等文件，且Dockerfile文件不能直接使用，希望能够更新一下最新版本的，谢谢！

**Comment by a364176773** [comment]
https://github.com/seata/seata/tree/develop/distribution
