### ISSUE TITLE
整合问题

### ISSUE THREAD

**Issue by liruhui** [seata/seata#4899]
## 1: 环境说明
```propreties
  springcloud+sharding-jdbc+seata   at模式
```
## 2: 项目结构
![QQ截图20220831223409](https://user-images.githubusercontent.com/24687986/187704972-fe61e58d-de17-4cd2-9a87-24ec9a98dd94.png)

## 3: 业务系统添加注解
![QQ截图20220831223920](https://user-images.githubusercontent.com/24687986/187706634-823fc320-3216-4bf4-b0aa-6dba6dfcfcd5.jpg)

## 4: 问题说明
```properties
 1：业务系统因为没有任何数据源 所以没有导入spring-tx包 默认没有@Transactional注解 
 2：业务系统我手动依赖上spring-tx包 就算添加了@Transactional注解  结果事务还是不回滚
```

## 5: 官方案例说明
![QQ截图20220831225004](https://user-images.githubusercontent.com/24687986/187708903-e898c4da-a387-4620-952e-6846028b42b9.jpg)

## 6: 诉求
```properties
   应该怎么解决？？ 怎么才能让事务生效 
```

**Comment by a364176773** [comment]
https://github.com/apache/shardingsphere-example/tree/dev/sharding-jdbc-example/transaction-example
