### ISSUE TITLE
Ask questions about server and Image and MT mode

### ISSUE THREAD

**Issue by xuyang0902** [seata/seata#49]
1, server abstraction into a service, but brought the consumption of rpc, why give up embedded in the application?
// 1、server抽象成服务，但是带来了rpc的消耗，为什么放弃 嵌入在应用呢？  
Can you tell the pros and cons of the selection?
//      能否告知选型的利弊？  
2, on the beforImage and afterImage, the framework in the implementation of the actual implementation of the update, select for update [previously according to the update conditions, the next time according to the primary key]. This should be strictly required in the sql generated for the business. Otherwise it is easy to bring the problem of deadlock. I hope that the later documents will be more abundant.
// 2、关于beforImage和afterImage，框架 在执行真正执行update时，先后都 select for update【前一次根据更新条件，后一次根据主键】。 这样在对业务生成的sql上面应该是需要有严格的要求的吧。否则很容易带来死锁的问题吧。希望后期文档能更丰富一点

// 
3, now open source is AT mode, MT mode is temporarily not supported, when will open source?
// 3、现在开源的是AT模式，MT模式暂时不支持，啥时候会开源呀？

// 

// ***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by xuyang0902** [comment]
期待你们的文档 来论证这块，，我再读读源码，，看看多个节点同时断电的情况 哈哈

**Comment by SageLam** [comment]
> 期待你们的文档 来论证这块，，我再读读源码，，看看多个节点同时断电的情况 哈哈

粗略看下源码，别说多节点，单节点断电都会有问题。目前分布式事务的实现是靠框架代码拆分成一个一个事务进行的。所谓的分布式事务回滚也是业务层面执行失败，然后后台根据前面记录的undo log进行数据库方面的回滚，回滚也是通过sql去执行insert或update或delete的操作修改数据进行还原。本质上网络异常或断电等问题都会导致数据最终不一致。

**Comment by xuyang0902** [comment]
> > 期待你们的文档 来论证这块，，我再读读源码，，看看多个节点同时断电的情况 哈哈
> 
> 粗略看下源码，别说多节点，单节点断电都会有问题。目前分布式事务的实现是靠框架代码拆分成一个一个事务进行的。所谓的分布式事务回滚也是业务层面执行失败，然后后台根据前面记录的undo log进行数据库方面的回滚，回滚也是通过sql去执行insert或update或delete的操作修改数据进行还原。本质上网络异常或断电等问题都会导致数据最终不一致。


>> 不知道我和你的理解是否有偏差， 我理解的branch任何节点断电，那对于business来说就是异常，tm会直接通知tc回滚global，tc会依次回滚global下注册上来的branch。 
你说的数据不一致的问题 希望你可以论证一下，我们可以一起探讨。

**Comment by xuyang0902** [comment]
> > > > 期待你们的文档 来论证这块，，我再读读源码，，看看多个节点同时断电的情况 哈哈
> > > 
> > > 
> > > 粗略看下源码，别说多节点，单节点断电都会有问题。目前分布式事务的实现是靠框架代码拆分成一个一个事务进行的。所谓的分布式事务回滚也是业务层面执行失败，然后后台根据前面记录的undo log进行数据库方面的回滚，回滚也是通过sql去执行insert或update或delete的操作修改数据进行还原。本质上网络异常或断电等问题都会导致数据最终不一致。
> > 
> > 
> > > > 不知道我和你的理解是否有偏差， 我理解的branch任何节点断电，那对于business来说就是异常，tm会直接通知tc回滚global，tc会依次回滚global下注册上来的branch。
> > > > 你说的数据不一致的问题 希望你可以论证一下，我们可以一起探讨。
> 
> tc依次回滚branch，回滚的逻辑是在branch上实现的，branch断电后branch使用的数据库数据尚未回退，此时数据是不一致的。目前还没深究源码。应该在branch重启后tm会通知branch根据数据库的undo log日志进行回滚，保证最终数据一致性吧。

就我读源码来看：
branch断电后，tc会把回滚的branch放到队列中，branch alive后就可以回滚到之前的数据快照了。且在这段时间内，如果有人想通过fescar修改这个branch涉及到的数据 是不被允许的（fescar有一个全局锁）。  关于锁和隔离性 这是一个很有趣的话题。
