### ISSUE TITLE
RollbackingRetryPeriod not work with Seata server 1.5.2 when config.type is file

### ISSUE THREAD

**Issue by meowWai** [seata/seata#4900]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

請教一下，Seata server 如何在config.type 為 file 的情況下設定RollbackingRetryPeriod，謝謝

### Ⅱ. Describe what happened

在application.yml中定義 seata.server.recovery.rollbacking-retry-period 沒有效果

### Ⅲ. Describe what you expected to happen

每60秒才重試，而不是一秒

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

![1061662013314_ pic](https://user-images.githubusercontent.com/91049935/187846615-300b9e84-d1c3-4325-96a6-395fb50c3a95.jpg)

![1071662013352_ pic](https://user-images.githubusercontent.com/91049935/187846629-e0306135-ba3d-4a5b-a985-372276f9db85.jpg)

### V. Environment:

- JDK version : 11
- Seata version:  1.5.2
- OS : Windows

**Comment by a364176773** [comment]
暂时使用远程配置中心来配置server.recovery.rollbackingRetryPeriod  
file下没有对应的properties导致读取不到，目前存在bug，包括commitretring等都是无法读取

**Comment by tuwenlin** [comment]
assign to me
