### ISSUE TITLE
1.4.2集成到springboot中，启动过程出现死锁

### ISSUE THREAD

**Issue by xiongyanglin** [seata/seata#4931]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在springboot整合seata1.4.2后启动偶然出现卡住的情况，
初始化数据源后，就卡住了，使用jstack发现了死锁。一批同时启动的情况出现的概率非常大

![image](https://user-images.githubusercontent.com/16217518/189887792-5258d8ac-8f03-4cd0-b540-6dfc34fb7aea.png)

### Ⅱ. Describe what happened
jstack 日志如下：
[jstack分析日志.txt](https://github.com/seata/seata/files/9556498/jstack.txt)

### Ⅲ. Describe what you expected to happen
急需解决此bug，环境上一键发包会部分服务卡住

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.4.2
- OS :centos
- Others: springboot 2.1.16.RELEASE nacos 1.3.2

**Comment by a364176773** [comment]
升级1.5.2即可解决
