### ISSUE TITLE
AT模式下，在特定情况下MySql批量更新操作无法创建undolog

### ISSUE THREAD

**Issue by walsece** [seata/seata#4933]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
针对mysql数据库执行批量更新操作（PreparedStatement.executeBatch()方法），在满足mysql的批量更新操作条件（mysql配置rewriteBatchedStatements=true且批量更新记录数目>3）时，无法创建undolog，
### Ⅱ. Describe what happened

经调试发现问题出在AbstractDMLBaseExecutor类中的以下方法中：
 protected T executeAutoCommitFalse(Object[] args) throws Exception {
        if (!JdbcConstants.MYSQL.equalsIgnoreCase(getDbType()) && isMultiPk()) {
            throw new NotSupportYetException("multi pk only support mysql!");
        }
        TableRecords beforeImage = beforeImage();
        T result = statementCallback.execute(statementProxy.getTargetStatement(), args);
        int updateCount = statementProxy.getUpdateCount();
        if (updateCount > 0) {
            TableRecords afterImage = afterImage(beforeImage);
            prepareUndoLog(beforeImage, afterImage);
        }
        return result;
    }

 int updateCount = statementProxy.getUpdateCount();
该行代码在mysql开启批量处理时始终返回-1（批量处理时没有对results进行赋值），因此无法创建undolog
在关闭批量处理(rewriteBatchedStatements=false)或者批量处理的数目<=3时正常

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1.mysql配置rewriteBatchedStatements=true
2.执行
jdbcTemplate.batchUpdate.batchUpdate("update XXX set field=? where id=?",args)
其中确保args的数量>3

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.5.2
- OS :
- Others:

**Comment by slievrly** [comment]
@walsece What is the mysql driver version? Do you have any further ideas for fixing this problem?

**Comment by slievrly** [comment]
#4838

**Comment by walsece** [comment]
> @walsece What is the mysql driver version? Do you have any further ideas for fixing this problem?

mysql-connector-java  version:8.0.17

**Comment by slievrly** [comment]
@walsece Pls help verify whether #4898 has fixed this problem.

**Comment by ovenfrank** [comment]
我也出现了这个问题，使用MyBatisPlus的saveBatch方法批量新增导致无法回滚，请问是怎么解决的

**Comment by a364176773** [comment]
> 我也出现了这个问题，使用MyBatisPlus的saveBatch方法批量新增导致无法回滚，请问是怎么解决的

https://github.com/seata/seata/issues/4833
