### ISSUE TITLE
seata-server.bat启动报错

### ISSUE THREAD

**Issue by chen-mingyang** [seata/seata#4939]
seata-server.bat启动报错Unrecognized VM option 'MatespaceSize=512m'

版本是照着参考下载的1.3.0，JDK8环境。

修改conf目录下的file.conf配置文件，完成
mysql5.7数据库新建库seata完成、在seata库里建表完成
registry.conf配置文件，修改成nacos。

然后一启动就是
![image](https://user-images.githubusercontent.com/68213575/190852030-41474d5e-2b62-45a8-a47d-8ae7ac31d1f7.png)

**Comment by a364176773** [comment]
请使用jdk8或jdk11

**Comment by chen-mingyang** [comment]
> 请使用jdk8或jdk11

使用的是JDK8，我看很过启动window的seata启动的就是JDK8，但这个错真的破天奇了，这个错百度几乎没有过

**Comment by a364176773** [comment]
你自己java -version看看什么版本

**Comment by chen-mingyang** [comment]
![image](https://user-images.githubusercontent.com/68213575/199999999-459e94b2-488b-4abd-ab1b-a8e8a5031644.png)
用的是java version "1.8.0_341"
