### ISSUE TITLE
TC端发生异常后，异常sqlexception没有包装回传给client端

### ISSUE THREAD

**Issue by zhandouji** [seata/seata#4941]
### Ⅰ. Issue Description
TC端发生异常后，异常sqlexception没有包装回传给client端

### Ⅱ. Describe what happened
TC端在写入【lock_table】表时，因为‘row_key’字段数据超长，造成【lock_table】表数据写入失败，但是该异常没有回传给client端。在client端的日志中，只提示
![image](https://user-images.githubusercontent.com/17878453/190987013-f76e87af-41ea-474b-8420-567896c37181.png)

### Ⅲ. Describe what you expected to happen
TC端应该将异常
![image](https://user-images.githubusercontent.com/17878453/190987228-987fb10c-cc60-40ae-ad46-db740d1b54e3.png)
包装后返回给client端，client打印出或者进行处理

### Ⅵ. Environment:

- JDK version : 8
- Seata version:  1.5.2
- OS : centos
- Others:sdf
应用版本：
- 
![image](https://user-images.githubusercontent.com/17878453/190987522-50793820-47bc-4d9f-b286-18c63d21c186.png)
- 
![image](https://user-images.githubusercontent.com/17878453/190987593-19cc4127-997f-4617-becc-6bd579cef7c4.png)

**Comment by pengten** [comment]
I think TC shoudn`t do it,  this error is not as expected.  why column is not long enough?

**Comment by Bughue** [comment]
plz assign to me

**Comment by Bughue** [comment]
@zhandouji 能否提供更完整的堆栈？我这边看这两个异常不一定是同一个的

**Comment by zhandouji** [comment]
@Bughue 
[TM端异常.txt](https://github.com/seata/seata/files/9613620/TM.txt)
这个是TM端异常。
[TC端异常.txt](https://github.com/seata/seata/files/9613752/TC.txt)
这个是TC端异常
