### ISSUE TITLE
how to get global status in springboot application

### ISSUE THREAD

**Issue by huangluoxiang** [seata/seata#4943]
### Ⅰ. Issue Description
cannot get global status in springboot application 

### Ⅱ. Describe what happened

i want to use global transaction status to decide whether send some message to another system in my springboot application, but when i used to method such as "transactionManager.getStatus(xid)" to obtain status of global transaction, the result is only '01' not matter which side is .
so , is there anybody help to find any alternatives ... thanks .

**Comment by a364176773** [comment]
Maybe you can use https://github.com/seata/seata/blob/develop/tm/src/main/java/io/seata/tm/api/transaction/TransactionHook.java
