### ISSUE TITLE
我在使用1.5.2的时候显示正确的事务回滚了。也显示成功了。但是数据库没有将之前的数据进行清除。这是怎么回事？

### ISSUE THREAD

**Issue by Red-collab** [seata/seata#4945]
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6fe35c01]
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6fe35c01]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6fe35c01]
2022-09-21 14:48:52.763  INFO 19132 --- [nio-9081-exec-3] i.seata.tm.api.DefaultGlobalTransaction  : Suspending current transaction, xid = 192.168.147.1:8091:901028382353817609
2022-09-21 14:48:52.765  INFO 19132 --- [nio-9081-exec-3] i.seata.tm.api.DefaultGlobalTransaction  : [192.168.147.1:8091:901028382353817609] rollback status: Rollbacked
2022-09-21 14:48:52.791 ERROR 19132 --- [nio-9081-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ArithmeticException: / by zero] with root cause

下面是seata：
14:48:51.915  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : timeout=60000,transactionName=add(java.lang.String),clientIp:192.168.147.1,vgroup:default_tx_group
14:48:51.915  INFO --- [verHandlerThread_1_18_500] i.s.s.coordinator.DefaultCoordinator     : Begin new global transaction applicationId: cnfe-auth,transactionServiceGroup: default_tx_group, transactionName: add(java.lang.String),timeout:60000,xid:192.168.147.1:8091:901028382353817609
14:48:52.752  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : xid=192.168.147.1:8091:901028382353817609,extraData=null,clientIp:192.168.147.1,vgroup:default_tx_group
14:48:52.752  INFO --- [verHandlerThread_1_19_500] io.seata.server.coordinator.DefaultCore  : Rollback global transaction successfully, xid = 192.168.147.1:8091:901028382353817609.

显示事务要回滚。可是数据库里面显示的却还有数据。

**Comment by Red-collab** [comment]
![1663743919700](https://user-images.githubusercontent.com/113892816/191437246-b9c8bb95-3f48-4843-a675-9fdca1993fb2.jpg)
![1663743966017](https://user-images.githubusercontent.com/113892816/191437268-180f4190-165e-494b-aa18-225b183be274.jpg)

**Comment by a364176773** [comment]
分支事务没有注册，检查xid传递，如果是at/xa模式检查数据源代理

**Comment by Red-collab** [comment]
> 分支事务没有注册，检查xid传递，如果是at/xa模式检查数据源代理

重写了dataSource（） 用mysql 就可以回滚了，但是用mariadb却一直在回滚重试
![1663750099183](https://user-images.githubusercontent.com/113892816/191459519-5d0ac965-67cc-488f-b5d2-18580b42f0cc.jpg)
![1663750091531](https://user-images.githubusercontent.com/113892816/191459617-e87b3350-8cf9-43a6-b71f-dd65d232bb46.jpg)
![1663750140338](https://user-images.githubusercontent.com/113892816/191459624-1c4e2cfc-f0ce-418e-aefd-9f2fcc04c086.jpg)
