### ISSUE TITLE
saga模式定义ServiceTask的Output表达式错误的话，会出现空指针异常

### ISSUE THREAD

**Issue by 1181954449** [seata/seata#4948]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
saga模式定义ServiceTask的Output表达式错误的话，会出现空指针异常

### Ⅱ. Describe what happened
output 表达式定义错误。会在记录数据库的时候未设置 GmtEnd 字段。在保存的时候会调用 
`stateInstance.getGmtEnd().getTime())`
出现空指针异常. 
![image](https://user-images.githubusercontent.com/28638437/191720461-6148e001-8c3f-4705-82fa-3e0daaf5785f.png)
应该在 ServiceTaskHandlerInterceptor 的 
![image](https://user-images.githubusercontent.com/28638437/191720948-56e84fd0-946c-4bc4-8d90-66ba0ee01d33.png)
设置 stateInstance.setGmtEnd(new Date()); 字段。

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 8
- Seata version:  1.4.2
- OS :
- Others:

**Comment by a364176773** [comment]
output 表达式定义错误
我的理解是不应该治本,而不是治标吗

**Comment by 1181954449** [comment]
是的。但是他选择记录了这个执行结果，那难道不需要解决空指针异常吗？

**Comment by a364176773** [comment]
> 是的。但是他选择记录了这个执行结果，那难道不需要解决空指针异常吗？

你可以提个pr来优化此问题吗？

**Comment by 1181954449** [comment]
好
