### ISSUE TITLE
当插入语句带有ID时候，ID被··包裹后，导致后置镜像有二个ID，造成无法回滚

### ISSUE THREAD

**Issue by z12131998** [seata/seata#4949]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

使用版本为1.5.1
Ⅰ. Issue Description
insert xxx (`ID`,`NAME`) values(1,'a');
导致出现`ID`和ID，从而让后置镜像有二哥ID，报错提示为 rowkey 1_1,newrow is null

 Ⅱ. Describe what happened

希望可以支持`ID`，在去重的时候注意一下

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:   1.5.1
- OS :
- Others:

**Comment by whxxxxx** [comment]
plz assign to me

**Comment by Moss-Lee** [comment]
只要解决镜像语句字段去重，更新复合主键字段导致回滚失败的问题就解决了，AT模式就支持更新复合主键字段了
