### ISSUE TITLE
ON DUPLICATE KEY UPDATE依旧会报错

### ISSUE THREAD

**Issue by z12131998** [seata/seata#4951]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
AT模式下报错
INSERT INTO test ( id, NAME, age )
VALUES( 1, '张三', 13 ) 
	ON DUPLICATE KEY UPDATE id = values(id),
	NAME = values(name),
	age = values(age)

### Ⅱ. Describe what happened
提示 update pk value is not supported 

### Ⅲ. Describe what you expected to happen
希望能正常加载到undolog日志和回滚

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.5.1
- OS :
- Others:

**Comment by a364176773** [comment]
不要加上 id = values(id),

**Comment by a364176773** [comment]
update里不允许放唯一索引和主键，不支持修改其值，如果想修改唯一索引而不是主键，可以用单纯的update去做
