### ISSUE TITLE
There InsertOnDuplicateUpdate  is an issue with bypassing modifying the primary key

### ISSUE THREAD

**Issue by a364176773** [seata/seata#4952]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
数据库开启不区分列大小写的情况下
数据库表的列名为 ID,sql中为id
duplicateKeyUpdateColumns会匹配不到数据库里的主键,导致认为业务sql并没有修改主键,导致后续的回滚存在失败的情况
![lQLPJxa2n-EiSsLNArLNBbKwcnRy0jE3hFQDLEdAh4CJAA_1458_690](https://user-images.githubusercontent.com/19943636/191978929-6966a718-54a5-468b-a7cb-a89d0fca5482.png)
![image](https://user-images.githubusercontent.com/19943636/191978982-0a518936-5c15-46df-b0c7-b2e0aad24c39.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by luky116** [comment]
seata-go: https://github.com/apache/incubator-seata-go/issues/701
