### ISSUE TITLE
create afterimages sql repeat pk

### ISSUE THREAD

**Issue by a364176773** [seata/seata#4955]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
构建后镜像sql生成没有进行去重等处理,在前镜像生成sql后,导致后镜像复用前镜像的sql,并往里面放主键的时候造成重复
![image](https://user-images.githubusercontent.com/19943636/192106826-5c1116a8-0404-46a7-889e-dcf9fbaad38c.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by renliangyu857** [comment]
please assign to me
