### ISSUE TITLE
When the unique index has a default null image sql error

### ISSUE THREAD

**Issue by a364176773** [seata/seata#4956]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
MySQLInsertOnDuplicateUpdateExecutor
![lQLPJxa35xe2rrbNAiDNBV2w-OVttIq3B18DLl9cKsA2AA_1373_544](https://user-images.githubusercontent.com/19943636/192132350-9baa5e1b-f22e-4a04-98f2-3c0db94f00b2.png)
`INSERT INTO p_p (ID, p_a_id, p_code, p_type, p_value_type, p_value, p_version, c_time) VALUES ('0000815e-1a83-4727-95cd-e2a173097780','dbbcdf52-5b1c-407a-a50a-3d2fc5cb788f','applyCreateTime','00','string','2022-09-05 15:21:26',0,now())  ON DUPLICATE KEY UPDATE id=values(id), p_a_id=values(p_a_id),p_code=values(p_code),p_type=values(p_type),p_value_type=values(p_value_type),p_value=values(p_value),p_version=p_version+1,c_time=values(c_time)`

其中id是pk,test_id是唯一索引默认值为null,且sql中不存在test_id
我这边测试了
1.优先匹配逻辑,如果有pk,且存在唯一索引,并且update的值是改动唯一索引的值
会按pk进行匹配,如果pk存在,那么update只会改动pk冲突的行,如果pk不存在才改动唯一索引的行
2.如果pk存在,唯一所以存在,且修改的唯一索引的值也存在,直接会报错
所以当插入字段存在pk不存在唯一索引时,直接按pk查即可
当插入pk及多个唯一索引时,应该进行or查询,会按照pk冲突就按pk命中那行进行修改,而不会管后面的唯一索引命中的行进行修改
当pk不存在,则按照多个唯一索引创建的顺序匹配,最终依旧只会改动一行数据
`INSERT INTO p_p (ID, p_a_id, p_code, p_type, p_value_type, p_value, p_version, c_time,test_id,test_id2) VALUES ('1236636','dbbcdf52-5b1c-407a-a50a-3d2fc5cb788f','applyCreateTime','00','string','2022-09-05 15:55:26',0,now(),'673','333')  ON DUPLICATE KEY UPDATE id=values(id), p_a_id=values(p_a_id),p_code=values(p_code),p_type=values(p_type),p_value_type=values(p_value_type),p_value=values(p_value),p_version=p_version+1,c_time=values(c_time)`
test_id2 先创建了唯一索引
test_id 是在test_id2之后创建
那么会优先匹配test_id2为333的行进行update,虽然影响行数为2,但是实际修改只有1
![image](https://user-images.githubusercontent.com/19943636/192133722-f0fe1333-4f84-455f-8d0b-d411444f1334.png)
![image](https://user-images.githubusercontent.com/19943636/192133730-424829ff-7c7c-4329-a2c7-b1b07b9dc9b7.png)
![image](https://user-images.githubusercontent.com/19943636/192133749-24420f6f-89b6-41e0-ace3-acf96bc5160c.png)
所以这块显示不是按时间排序的,不要被误导,实际创建test2是先创建的
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
1.唯一索引为null的不作为条件

**Comment by renliangyu857** [comment]
please assign it to me
