### ISSUE TITLE
seata 1.5.2 用 K8S部署的话，允许deployment设置2个副本数吗？

### ISSUE THREAD

**Issue by hillbun** [seata/seata#4959]
seata 1.5.2 用 K8S部署的话，允许deployment设置2个副本数吗？

我看到网上的文档都是1个，是架构不支持多个副本数吗

**Comment by hillbun** [comment]
yes, is it possible to scale deployment to 2 replicas to high-availability?

**Comment by a364176773** [comment]
Of course
