### ISSUE TITLE
不支持ARM64

### ISSUE THREAD

**Issue by 1774298958** [seata/seata#4960]
seataio/seata-server:latest版本docker镜像，不支持树莓派ARM64位
![image](https://user-images.githubusercontent.com/26165803/192429715-6033ea67-d6e8-4f2b-be3b-5ba4f09972e5.png)

**Comment by wangliang181230** [comment]
@1774298958 请重新尝试一下。

**Comment by 1774298958** [comment]
问题依然还在，我不知道exec /usr/local/openjdk-11/bin/java: exec format error这个错误来自哪里？本机也没有安装openjdk11，为何会报这个错误
![image](https://user-images.githubusercontent.com/26165803/192673616-50d5509a-63ec-485a-b732-f545305cbcc4.png)

**Comment by slievrly** [comment]
@1774298958 DIGEST:sha256:4b20aee1300fabf40a421bd73e2d0f8c2515a19f071f22ffa5547b92aaeafeca ?

**Comment by slievrly** [comment]
@wangliang181230 As I understand it, we will only release JDK8-based images, not JDK11-based images.

**Comment by wangliang181230** [comment]
@1774298958 确认是最新下载的镜像吗？

**Comment by a364176773** [comment]
docker rmi 删掉之前的latest的版本，重新pull
