### ISSUE TITLE
有考虑使用kryo5.X么 4.X最后更新时间是2018年 5.X目前已经更新到5.3.0了 更新的很活跃 功能也更好一些

### ISSUE THREAD

**Issue by JavaLionLi** [seata/seata#4961]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by JavaLionLi** [comment]
希望可以支持一下5.X

**Comment by slievrly** [comment]
@JavaLionLi  Are you willing to follow up on this issue ?

**Comment by JavaLionLi** [comment]
> @JavaLionLi Are you willing to follow up on this issue ?

https://github.com/apache/dubbo-spi-extensions/pull/141 已经给dubbo提了pr 由于不了解seata源码 暂时无法提供相关pr

**Comment by JavaLionLi** [comment]
> @JavaLionLi Are you willing to follow up on this issue ?

已经提交相关pr

**Comment by JavaLionLi** [comment]
> > @JavaLionLi Are you willing to follow up on this issue ?
> 
> 已经提交相关pr https://github.com/seata/seata/pull/4966
