### ISSUE TITLE
undo_log 表记录了两次主键

### ISSUE THREAD

**Issue by xiangch** [seata/seata#4965]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

AT模式下，该类型的SQL
```
INSERT INTO test (`id`, `NAME`, `age` ) VALUES( 1, '张三', 13 )
```
在回滚时会发生异常  `Has dirty records when undo`  `newRow is null`
### Ⅱ. Describe what happened

打断点调试后，发现字段记录了两次 id ，一次为 `id` 一次为\`id\` 

io.seata.rm.datasource.exec.BaseTransactionalExecutor#buildTableRecords(java.util.Map<java.lang.String,java.util.List<java.lang.Object>>)
```
  435 columns.addAll(recognizer.getInsertColumns()); // `id`, `NAME`, `age`
  436 columns.addAll(pkColumnNameList); // id
```
 \`id\`与 id 不能通过set去重，最终导致 columns=>[\`id\`,\`NAME\`, \`age\`,id]
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

getInsertColumns 时要去掉 \` \`

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS : 
- Others:

**Comment by a364176773** [comment]
是的，我们已经发现这个问题将在1.6修复

**Comment by slievrly** [comment]
@xiangch can you submit a pr to fix it?

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4949 我们将在此issue进行讨论
