### ISSUE TITLE
May rowkey be duplicated in different db?

### ISSUE THREAD

**Issue by zhuangqh** [seata/seata#4971]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

As I know, in AT mode. The global lock key is getRowKey(rowLock.getResourceId(), rowLock.getTableName(), rowLock.getPk()));

There are two totally different db, may their lockkey be the same? Because the resourceId may be the same?

在AT模式中，全局锁的key是resourceId+tablename+pk。有没可能两个完全不相关的db，他们的锁key是一样的，因为resourceid可能是一样，比如jdbc里的地址是虚地址？ 这会导致两个无关的应用抢同一个锁。
请问seata是如何考虑这个问题的，或者我理解有误。谢谢

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
jdbc:mysql://127.0.0.1:3306/seata-order^^^order^^^2188  
你觉得ip+dbname会出现相同mysqlip上有2个dbname一样几率大吗？
