### ISSUE TITLE
get table meta failed

### ISSUE THREAD

**Issue by mytxoo** [seata/seata#4972]
使用mycat 结合seata 无法插入数据。
错误如下: test1 是已经表
`### Cause: java.sql.SQLException: io.seata.common.exception.ShouldNeverHappenException: [xid:112.126.83.102:8091:9318962195157553]get table meta failed, please check whether the table `test1` exists.
; uncategorized SQLException; SQL state [null]; error code [0]; io.seata.common.exception.ShouldNeverHappenException: [xid:112.126.83.102:8091:9318962195157553]get table meta failed, please check whether the table `test1` exists.; nested exception is java.sql.SQLException: io.seata.common.exception.ShouldNeverHappenException: [xid:112.126.83.102:8091:9318962195157553]get table meta failed, please check whether the table `test1` exists. `
百思不得其解，求教
1，主键问题已经检查。正常，global_table表内数据可以插入，但是项目内undo_log表内无数据
2，@GlobalTransactional 取消这个，就正常了

**Comment by mytxoo** [comment]
主键问题已经检查。正常，global_table表内数据可以插入，但是项目内undo_log表内无数据

**Comment by a364176773** [comment]
请反馈至mycat社区或者使用shardingsphere,这个问题是mycat代理了背后的物理数据库,seata无法获取真正的物理数据库的相关表的元数据
