### ISSUE TITLE
复合主键undo_log 表镜像语句记录了两次主键

### ISSUE THREAD

**Issue by Moss-Lee** [seata/seata#4984]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
AT模式下，更新复合主键中的字段会导致undo_log镜像记录了两次主键
`update user set   id_card = 'xxx' , name = 'XXX', sex = 'xx' where  id = 'xxx';  复合主键（id_card,id）类似这样情况`

### Ⅱ. Describe what happened

    当出现异常会出现无限回滚，已下代码中io.seata.rm.datasource.exec.BaseTransactionalExecutor.containsPK参数的字段只存在复合主键的部分列时，导致判断为不存在主键，导致代码片段1添加了所有的复合主键后代码片段2中又添加了更新的列中存在复合主键字段，导致镜像列重复。

```
io.seata.rm.datasource.exec.UpdateExecutor
代码片段1：
if (!containsPK(updateColumns)) {
    selectSQLJoiner.add(getColumnNamesInSQL(tableMeta.getEscapePkNameList(getDbType())));
}
代码片段2：
for (String columnName : updateColumns) {
    selectSQLJoiner.add(columnName);
}
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 建立复合主键
2. 在更新语句中更新复合主键的字段

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS :  Linux
- Others:

**Comment by Moss-Lee** [comment]
不好意思，上面两个代码片段时此类中
`io.seata.rm.datasource.exec.UpdateExecutor`

**Comment by a364176773** [comment]
不要更新符合主键，在AT下这是不允许的操作

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4949 我们应该在这里统一进行讨论
