### ISSUE TITLE
JDK11直接启动 seata-server 报错

### ISSUE THREAD

**Issue by luojunjiess** [seata/seata#4994]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata 版本v1.5.2、v.1.5.1 都试过了，都是这个报错，没有进行任何的 seata-server.sh 修改；只有版本降到 1.4.2 才正常，求助

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/23051007/195816751-a3000de9-ec90-45c0-9bee-d05d60fb8945.png">

报错无法启动

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4874

**Comment by luojunjiess** [comment]
> #4874

好的，看起来pr还没合并是吗？

**Comment by luojunjiess** [comment]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/23051007/196099274-5b95d53a-7eed-4896-be82-1c0563c8b5b8.png">
我按照大佬这里的改动搬到本地，执行会报这个错
https://github.com/seata/seata/pull/4874/files/262c964474752c513e88507b0c6b61e211652964

**Comment by a364176773** [comment]
你启动的路径有问题，你cd bin 再启动
