### ISSUE TITLE
seata-server.sh LOADER_PATH optimize

### ISSUE THREAD

**Issue by a364176773** [seata/seata#5001]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
https://github.com/seata/seata/blob/develop/distribution/bin/seata-server.sh
![image](https://user-images.githubusercontent.com/19943636/196346917-2e80ba1c-c465-4aac-88f8-950440978b19.png)
目前loader.path路径默认为相对路径，导致在bin目录外使用seata-server.sh会失败
我们需要保证seata-server.sh不再bin目录也可以使用，顺便排查是否有类似如上问题的地方一并修复
Currently the loader.path path defaults to a relative path, which causes seata-server.sh to fail when used outside of the bin directory. We need to make sure seata-server.sh is not available outside of the bin directory, and check if there is anything like the above problem to fix as well
![image](https://user-images.githubusercontent.com/19943636/196347833-048fc9ae-3250-4e3e-91e8-abb6973566ba.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by lvekee** [comment]
please assign it to me
