### ISSUE TITLE
insert on duplicate语句不带列字段时出现空指针问题

### ISSUE THREAD

**Issue by renliangyu857** [seata/seata#5005]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

不带列字段时出现空指针，如insert into t values(1,1,1) on duplicate key update a = 2;

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
定位到时在通过插入的数据构造前置镜像时，recognizer.getInsertColumns返回了null，在遍历时出现空指针问题；此时应该根据values构造主键查询列，参考BaseInsertExecutor#parsePKValuesFromStatement

![image](https://user-images.githubusercontent.com/28523136/196583952-75042cbc-f27e-4ef6-80c6-d3d89d7f982b.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
insert into t_nounique values(3,3) on duplicate key update b = 5
这种sql需要根据matedata信息读到列的顺序去找到主键
