### ISSUE TITLE
将seata1.5.2封装成***starter.jar后，client启动提示no available service 'null' found, please make sure registry config correct

### ISSUE THREAD

**Issue by gostop0714** [seata/seata#5013]
首先，seata server端使用1.5.2版本，集成nacos作为注册、配置中心，docker方式启动成功

然后，client端集成Springboot2.2.5+SpringCloud Alibaba2.2.0+Nacos，直接集成seata-spring-boot-starter:1.5.2、spring-cloud-starter-alibaba-seata:2.2.0，启动并测试，能够支持分布式事务。

最后，我把seata这两个引用封装成一个stater启动包，client集成该starter包，其他配置没有变，启动后，控制台一直提示no available service 'null' found, please make sure registry config correct。

请问这个问题怎么解决？

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4312
https://seata.io/zh-cn/docs/user/txgroup/transaction-group.html

**Comment by gostop0714** [comment]
@a364176773 
client端直接引用seata1.5.2的jar包测试过，配置没问题。
现在的问题是，把seata1.5.2用到的jar包封装到另外一个starter包中，client端直接引用这个starter包，配置不做任何修改，启动就报错
再把引用的jar包还原回来，就能成功启动。。。
