### ISSUE TITLE
怎么通过seata-all的方式集成seata

### ISSUE THREAD

**Issue by heqianrui** [seata/seata#5019]
通过boot的方式已经集成成功，按照官网的说法通过添加注解@EnableAutoDataSourceProxy和手动注册GlobalTransactionScanner之后，事务并没有生效，也不报错，seata服务端没有任何信息打印，猜测可能是没有拦截，有没有具体的案例或者demo，谢谢

**Comment by a364176773** [comment]
https://github.com/seata/seata-samples
