### ISSUE TITLE
不生成xid

### ISSUE THREAD

**Issue by heqianrui** [seata/seata#5021]
我的项目是一个springmvc的项目，按照git上的案例进行了配置，包括file.conf和registry.conf，以及数据源代理和GlobalTransactionScanner，但是并不生成xid，事务不生效。
使用的是1.4.0版本
下图是seata服务端的打印
![image](https://user-images.githubusercontent.com/74887625/197914782-dddce6c0-ce6a-45aa-a8fd-06532a00df47.png)
不知道是哪里的问题，请帮忙解决一下，谢谢

**Comment by a364176773** [comment]
Did you annotate with @GlobalTransactional?

**Comment by heqianrui** [comment]
标注了，我使用的是file模式
file.conf的部分配置如下
![image](https://user-images.githubusercontent.com/74887625/197917610-bd7cc8ba-79cc-4aae-8c7f-cac57b78a626.png)
下图是代理和GlobalTransactional的配置
![image](https://user-images.githubusercontent.com/74887625/197917842-53dd0e11-8104-4b3d-b8f3-12b195402a71.png)
下图是代码片段
![image](https://user-images.githubusercontent.com/74887625/197917948-8c5b6e5b-7ba3-4e11-be6f-24fb8fd897db.png)
麻烦您再帮忙看下，谢谢

**Comment by a364176773** [comment]
Where is test1 being called?

**Comment by heqianrui** [comment]
是直接在上层controller调用的
![image](https://user-images.githubusercontent.com/74887625/197919266-3e78459e-f958-4527-983d-7d4687321c64.png)

**Comment by a364176773** [comment]
First confirm that the GlobalTransactionScanner bean is initialized, and second see if the GlobalTransactionalInterceptor cut is entered into the

**Comment by heqianrui** [comment]
第一点已经确认，GlobalTransactionScanner 是初始化完成的，在测试第二点的时候我发现GlobalTransactionalInterceptor 没有生效，也就是我在调用全局事务方法的时候GlobalTransactionalInterceptor没有起到作用，这个应该怎么解决呢？

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java
![image](https://user-images.githubusercontent.com/19943636/197922903-a8e88c40-0986-4379-8ca3-19c5849ce9a9.png)

**Comment by heqianrui** [comment]
我看了一下这个方法
![image](https://user-images.githubusercontent.com/74887625/197924360-69e86a22-37cb-4606-ab2c-0041128cea48.png)
我在这块是直接return出去的，说明他并没有找到任何我标注@GlobalTransactional的地方，我很奇怪，为什么会这样，我是分明标注了的，而且相关类是放在容器中的

**Comment by a364176773** [comment]
> 我看了一下这个方法 ![image](https://user-images.githubusercontent.com/74887625/197924360-69e86a22-37cb-4606-ab2c-0041128cea48.png) 我在这块是直接return出去的，说明他并没有找到任何我标注@GlobalTransactional的地方，我很奇怪，为什么会这样，我是分明标注了的，而且相关类是放在容器中的

It may have something to do with the order of the bean, try using version 1.5.2?
Version 1.5.2 can also be used in the following way
![image](https://user-images.githubusercontent.com/19943636/197924984-80d24d1c-3027-4f3b-bf97-d3c99e24bebc.png)

**Comment by heqianrui** [comment]
不好意思，上面那个问题是由于我的失误造成的，现在已经解决，但是GlobalTransactionalInterceptor 初始化之后，还是没有生效，
![image](https://user-images.githubusercontent.com/74887625/197926515-e5c69eb9-ff8e-4348-bbc9-e279dd3c791d.png)
他已经找到我需要事务的那个bean，但是GlobalTransactionalInterceptor 依然没有起作用

**Comment by a364176773** [comment]
Can you submit a demo?

**Comment by heqianrui** [comment]
您好，附件是我的demo，麻烦您再帮忙看下，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seata/seata] 不生成xid (Issue #5021)





 
Can you submit a demo?

**Comment by a364176773** [comment]
Can I put it in github?

**Comment by heqianrui** [comment]
可以

**Comment by heqianrui** [comment]
不好意思，请问一下，我是哪里的问题导致GlobalTransactionalInterceptor 不生效的，您有发现问题吗？

**Comment by a364176773** [comment]
> 不好意思，请问一下，我是哪里的问题导致GlobalTransactionalInterceptor 不生效的，您有发现问题吗？

Put your sample in github

**Comment by heqianrui** [comment]
请问一下，我应该提交到github哪里？是我自己的仓库吗

**Comment by heqianrui** [comment]
您好，这是demo的地址，https://github.com/heqianrui/seata.git，麻烦您再帮忙看下，谢谢

**Comment by slievrly** [comment]
@heqianrui Does spring.xml work?

**Comment by heqianrui** [comment]
是生效的，不好意思，因为是将原有工程中的配置直接复制出来的，所以web.xml忘记提交了，现在已经修改了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seata/seata] 不生成xid (Issue #5021)





 
@heqianrui Does spring.xml work?

**Comment by heqianrui** [comment]
不好意思，我这边发现个问题，等我再修改修改，您再帮忙看看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seata/seata] 不生成xid (Issue #5021)





 
@heqianrui Does spring.xml work?

**Comment by heqianrui** [comment]
spring的配置文件是工作的，这下我重新修改了一下，因为我这边确实会用到seata，但是现在集成不成功，麻烦您重新看看，谢谢您


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seata/seata"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seata/seata] 不生成xid (Issue #5021)





 
@heqianrui Does spring.xml work?

**Comment by a364176773** [comment]
你这上面各种NoClassDefFoundError，跑都跑不起来，建表sql之类的参数呢
![image](https://user-images.githubusercontent.com/19943636/198964379-6752ce84-d91c-4f10-9391-002b0641a336.png)
![image](https://user-images.githubusercontent.com/19943636/198964755-a636089e-bd9a-4361-b79b-6f707f8a3c03.png)

**Comment by a364176773** [comment]
我把你这些依赖加好了，测试是通过的，进了切面
![image](https://user-images.githubusercontent.com/19943636/198966182-cc22da8a-520e-4731-9b85-203bcb1b5e9f.png)
你会不会是认为system.out.println打印不到日志文件就以为没有吧？

**Comment by a364176773** [comment]
https://github.com/heqianrui/seata/pull/1

**Comment by heqianrui** [comment]
好的，谢谢您，我发现确实能生效，之前是因为我直接集成到公司的项目中去了，可能是公司的项目某个配置的地方使得失效了，我之后再自己研究一下，关于demo没有sql等，这个是我的失误，非常感谢您的帮助！

**Comment by a364176773** [comment]
> 好的，谢谢您，我发现确实能生效，之前是因为我直接集成到公司的项目中去了，可能是公司的项目某个配置的地方使得失效了，我之后再自己研究一下，关于demo没有sql等，这个是我的失误，非常感谢您的帮助！

好的，有问题再联系，最好能提供可复现问题的demo，这样有助于我们发现问题和帮助用户解决问题
