### ISSUE TITLE
很多properties通过@Component注入，是否可以通过@Bean注入方便扩展

### ISSUE THREAD

**Issue by crazy-sheep** [seata/seata#5041]
## Why you need it?
很多properties通过@Component注入，导致用户无法通过自定义条件注入bean，而且seata配置项很多，用户扩展起来极其繁琐，是否可以像naocs那样通过@Bean等其他条件注解注入bean，方便用户使用条件注解控制bean注入

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
Can you give me an example?

**Comment by crazy-sheep** [comment]
![image](https://user-images.githubusercontent.com/66940746/199263986-0b5e09c7-c969-41bc-8852-c430a00be656.png)
类似这样的properties类，不使用@Component方式注入properties类，通过配置类的方式，使用@Bean注解注入properties类，
![image](https://user-images.githubusercontent.com/66940746/199265248-194ed401-86f7-442a-84b3-b02660879222.png)

**Comment by a364176773** [comment]
@wangliang181230 @slievrly @xingfudeshi  
Let's talk about this view

**Comment by xingfudeshi** [comment]
I think these properties are used to serve the seata starter itself. If there is a need, it is recommended to submit a PR to make changes.

**Comment by xingfudeshi** [comment]
I think these properties are used to serve the seata starter itself. If there is a need, it is recommended to submit a PR to make changes.

**Comment by crazy-sheep** [comment]
这些properties确实都是seata必要的，但是如果可以使用条件控制，比如用户引入依赖但关闭全局事务的功能时，可以避免注入很多不需要的bean，同时用户可以使用这些条件去控制bean的注入，扩展自己bean替换原有功能的bean

**Comment by a364176773** [comment]
> 这些properties确实都是seata必要的，但是如果可以使用条件控制，比如用户引入依赖但关闭全局事务的功能时，可以避免注入很多不需要的bean，同时用户可以使用这些条件去控制bean的注入，扩展自己bean替换原有功能的bean

Doesn't seem to see much more merit than the ability to control the creation of beans
