### ISSUE TITLE
JDK 11 Server1.5.2 启动失败, Error: Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by zhoushuai1119** [seata/seata#5046]
Seata Version：1.5.2
JDK Version：11.0.17
OS：Centos7

通过seata-server.sh启动报错，错误信息如下：

![image](https://user-images.githubusercontent.com/29701159/199638180-af86485c-9b49-45d5-a051-e0f3624784f3.png)

我看了其他的issues，是openjdk11有这样的问题，但是Oracle_JDK 11 为什么也有这样的问题

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4874

**Comment by zhoushuai1119** [comment]
代码还没有合是吧，我想问一下大概什么时候会出下一个版本的？
