### ISSUE TITLE
seata 1.2版本，正常启动后，几个小时后进程自动关闭

### ISSUE THREAD

**Issue by GitHubcaowei** [seata/seata#5054]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata 1.2版本，正常启动后，几个小时后进程自动关闭

### Ⅱ. Describe what happened
seata 1.2版本，正常启动后，几个小时后进程自动关闭，日志无任何报错，如下：
 INFO [ShutdownHook]io.seata.core.rpc.netty.RpcServer.destroy:69 -destroyed rpcServer

  If there is an exception, please attach the exception trace:
  没有异常
```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
seata 1.2版本，正常启动后，进程一直正常运行，不关闭

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.2.0
- OS : Centos7
- Others:

**Comment by a364176773** [comment]
nohup./start.sh &
