### ISSUE TITLE
seata 1.4.2 版，docker集群报错问题解决

### ISSUE THREAD

**Issue by lbj812** [seata/seata#5058]
registry.conf 配置如下：
registry {
   type = "nacos"
  nacos {
    application = "seata-server"
    serverAddr = "192.168.0.xxx:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = ""
    password = ""
  }
}
config {
  type = "nacos"
  nacos {
    serverAddr = "192.168.0.xxx:8848"
    namespace = ""
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
    dataId = "seataServer.properties"
  }
}
nacos中的配置必须如下：
Data Id：seataServer.properties  值：数据库的连接文本信息
Data Id：store.mode  值：db
其中：
Data Id：store.mode 最为关键。
如果没有该项，seata的docker容器拉取不到 seataServer.properties 。
所以只能默认使用 file的配置，导致做业务的时候找不到 xid
报错如下：
io.seata.core.exception.GlobalTransactionException: Could not found global transaction xid = 192.168.0.82:8091:738914653720850446, may be has finished

**Comment by a364176773** [comment]
nacos什么版本，如果用的是mse nacos，可以咨询下对应开源的大致什么版本

**Comment by a364176773** [comment]
怀疑网络问题导致时不时拉取不到配置，在2.0.0nacos+1.4.2seata下测试n次未能复现，后续应该在拉取不到大的dataid配置时抛异常，而不是打印日志

**Comment by lbj812** [comment]
既然 config { type = "nacos" } ，那么就必须从nacos拉取成功，才可以正常启动seata服务进程。而不是在拉取失败的时候，启用默认的 type ="file ",如果这样，就失去了 config { type = "nacos" } 的意义。
如果拉取失败，不应该打个日志，而应该抛异常出来阻止进程启动。

**Comment by lbj812** [comment]
既然 config { type = "nacos" } ，那么就必须从nacos拉取成功，才可以正常启动seata服务进程。而不是在拉取失败的时候，启用默认的 type ="file ",如果这样，就失去了 config { type = "nacos" } 的意义。
如果拉取失败，不应该打个日志，而应该抛异常出来阻止进程启动。
