### ISSUE TITLE
seata 1.5.2回滚的时候afterImage的rows中会生成重复的id，导致回滚出现脏数据

### ISSUE THREAD

**Issue by showpro** [seata/seata#5059]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/36835026/200454250-6cf3e104-ee44-4424-93d8-7bcdede40bf4.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS :
- Others:

**Comment by showpro** [comment]
这样正常吗？请大佬指点一下

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4949

**Comment by showpro** [comment]
![image](https://user-images.githubusercontent.com/36835026/200454718-97f58646-77d7-4814-8f88-52cbef1bb25c.png)
上面这个是错误信息
