### ISSUE TITLE
seata 1.5.2回滚的时候afterImage中的rows会生成重复的id,回滚的时候报脏数据

### ISSUE THREAD

**Issue by showpro** [seata/seata#5060]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://user-images.githubusercontent.com/36835026/200455999-09d7f96c-c22c-4126-840a-f42e9758c957.png)
![image](https://user-images.githubusercontent.com/36835026/200456173-bf5c5447-4360-4f45-a2e9-9570a54504b5.png)

请大佬帮忙看下是啥原因造成的

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS :
- Others:

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4949 看这个issue，自行阅读

**Comment by showpro** [comment]
![image](https://user-images.githubusercontent.com/36835026/200456811-ec6cd124-81a4-4f7f-ac80-db1cd154026c.png)
这是debug的信息
