### ISSUE TITLE
关于@GlobalTransactional注解下sql存在 JSON_TABLE的COLUMNS字符报错的问题

### ISSUE THREAD

**Issue by XiwiNetwork** [seata/seata#5061]
关于**@GlobalTransactional注解**下 sql存在 JSON_TABLE的**COLUMNS字符报错**的问题
问题复现是任何SQL包含 JSON_TABLE函数的COLUMNS标识下 都会爆
去除 **@GlobalTransactional注解** 则可以执行成功

![报错SQL](https://user-images.githubusercontent.com/33108158/200470605-dd74680e-2fb9-4b9b-9d53-d4c2fa0d3b4d.png)

![日志报错](https://user-images.githubusercontent.com/33108158/200470353-07f05775-a8aa-4240-8a68-427f88d5e5f5.png)

**Comment by a364176773** [comment]
建议反馈至druid社区，异常是druid抛出的
