### ISSUE TITLE
seata全局锁使用的过程中（1.4.1版本），发现了死锁的问题

### ISSUE THREAD

**Issue by anwanju** [seata/seata#5063]
seata 在搭配mysql 的使用过程中，出现了死锁的问题。
使用示例：
初始化数据
row_key    branch_id
1                1
10              10
15              10
20              10
30               30

事务1 ：insert into lock_table（row_key,branch_id） values (9 ,25);
事务2： delete from lock_table where branch_id=10;  此处出现了阻塞
事务1： insert into lock_table（row_key,branch_id） values (10 ,25); 此处报出死锁。

在seata 删除全局锁的时候，能否强制指定使用索引？

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4750

**Comment by anwanju** [comment]
已收到邮件，请等待回复，谢谢
