### ISSUE TITLE
Configuration metrics is not valid

### ISSUE THREAD

**Issue by WVenus** [seata/seata#5066]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Configuration metrics is not valid

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/39941928/200758582-0b47549b-9484-456f-aaf8-d552a96a8492.png">

![image](https://user-images.githubusercontent.com/39941928/200758192-f77080f1-4d84-44a0-9719-6d64e145670a.png)

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 
- Seata version:   1.5.2
- OS : docker image seataio/seata-server:1.5.2
- Others:

**Comment by a364176773** [comment]
使用第三方配置中心就把它配到配置中心去 https://github.com/seata/seata/blob/develop/script/config-center/config.txt

**Comment by WVenus** [comment]
您好，我已经按照您的提示配置了metrics参数。重启后得到了解决。 十分感谢
<img width="901" alt="image" src="https://user-images.githubusercontent.com/39941928/200761620-8f1db86a-8019-410c-86c8-5f6a939a0865.png">
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/39941928/200761796-2a2f7989-bd17-416f-a1ba-4e6d90e1cddc.png">
