### ISSUE TITLE
如何关闭seata 的心跳日志信息

### ISSUE THREAD

**Issue by yjyq61** [seata/seata#5082]
![图片](https://user-images.githubusercontent.com/49428086/202368813-93861952-843b-42b9-99a3-7d6404462e63.png)

我在配置文件里把nacos的心跳日志登记设为warn 就不再打印了，但是不管怎么设置 seata 还是会一直打印心跳日志，请问seata的心跳日志如何关闭呀？

**Comment by a364176773** [comment]
日志配置成info级别
