### ISSUE TITLE
seata支持redis集群么

### ISSUE THREAD

**Issue by xujiliang** [seata/seata#5085]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
sentinel & 主备

**Comment by xujiliang** [comment]
啥时候能支持啊，我们现场生产环境现在是基于pg数据库的，经常性的报TransactionException[Could not found global transaction xid = 192.168.0.1:8081:1594602970694709515, may be has finished.] ，想切换成，然而redis又是集群模式

**Comment by a364176773** [comment]
这个问题跟redis没有任何关系，官网faq好好看
