### ISSUE TITLE
undo_log 没有删除 

### ISSUE THREAD

**Issue by lovlyhao** [seata/seata#5086]
请问  这是正常的嘛， undo_log表记录没有删除 rollback_info={},log_status =1 

![image](https://user-images.githubusercontent.com/30038949/202601985-604955c4-24fb-4e98-8ae7-c3d9deb6ea77.png)

![image](https://user-images.githubusercontent.com/30038949/202601929-811768fd-a01c-43d3-8e6a-04abeb7af134.png)

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/overview/faq.html
