### ISSUE TITLE
关于vgroup-mapping的问题

### ISSUE THREAD

**Issue by RedShameA** [seata/seata#5093]
经过自己测试的：vgroup-mapping 可以单配置在服务端、或者服务端客户端都配置，但不可以单配置在客户端
但当服务端客户端配置不一样的时候，会以哪个为准呢？为什么不只在服务端配置呢？
官网在 事务分组-事务分组与高可用 中这个图片，我理解的是以客户端配置来选择不同集群，但为什么不能只配置在客户端呢？

![image](https://seata.io/img/txgroup/txgroup-segregation-of-pre-and-product.png)

**Comment by a364176773** [comment]
1.seata-server不会读取事务分组
2.seata-client只会读取配置中心里的事务分组,如果你的config.type是nacos那就是读nacos,是file就读本地

**Comment by RedShameA** [comment]
> 
感谢回复！还有几个问题 希望您能解答一下！

1.seata-server不会读取事务分组，是不是指nacos里的那一个配置文件是同时被seata-server、seata-client来使用，但它们只会取自己用的到的配置项，比如事务分组配置其实只有seata-client会读取并用到？
2.当我在springboot客户端配置了config块为nacos、并且nacos里配置了事务分组，其中再配置的service.vgroup-mapping块是不是就无效了？（如下配置文件代码）  或者说配置了nacos之后，就只会在nacos里取事务分组，本地配置的就是没有用的？
3.客户端需要config、registry都配置吗？registry配置块是用来干啥的，是用来注册TM、RM的吗？
`
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  enable-auto-data-source-proxy: false
  service:
    vgroup-mapping:
      ruoyi-user-group: default
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      data-id: seata-server.properties
  registry:
      type: nacos
      nacos:
        application: seata-server
        server-addr: 127.0.0.1:8848
        namespace:
`

**Comment by RedShameA** [comment]
> 1.seata-server不会读取事务分组 2.seata-client只会读取配置中心里的事务分组,如果你的config.type是nacos那就是读nacos,是file就读本地


感谢回复！还有几个问题 希望您能解答一下！

1.seata-server不会读取事务分组，是不是指nacos里的那一个配置文件是同时被seata-server、seata-client来使用，但它们只会取自己用的到的配置项，比如事务分组配置其实只有seata-client会读取并用到？
2.当我在springboot客户端配置了config块为nacos、并且nacos里配置了事务分组，其中再配置的service.vgroup-mapping块是不是就无效了？（如下配置文件代码）  或者说配置了nacos之后，就只会在nacos里取事务分组，本地配置的就是没有用的？
3.客户端需要config、registry都配置吗？registry配置块是用来干啥的，是用来注册TM、RM的吗？
`
seata:

  enabled: true

  application-id: ${spring.application.name}

  tx-service-group: ${spring.application.name}-group

  enable-auto-data-source-proxy: false

  service:

    vgroup-mapping:

      ruoyi-user-group: default

  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      data-id: seata-server.properties
  registry:
      type: nacos
      nacos:
        application: seata-server
        server-addr: 127.0.0.1:8848
        namespace:
`

**Comment by a364176773** [comment]
1,2 配置中心是什么就去哪读.
3.config 配置中心相关配置,registry注册中心相关配置做client和tc的服务注册和发现

**Comment by RedShameA** [comment]
> 1,2 配置中心是什么就去哪读. 3.config 配置中心相关配置,registry注册中心相关配置做client和tc的服务注册和发现

谢谢！
