### ISSUE TITLE
你好，如何延长seata全局事物锁的信息

### ISSUE THREAD

**Issue by mdxlCJ** [seata/seata#5094]
搭建seata成功，测试了一下通过看seata后台可以看到事务信息和全局事物锁的整个链路信息，但是2分钟左右数据就自动消失了，数据库的数据自动清空，请问这个是怎么回事，这数据可以保留嘛

**Comment by a364176773** [comment]
就是要删除，目前不支持数据保留，后续将会把数据通过rocketmq和kafka方式发出去，业务方可自己消费持久化存储
