### ISSUE TITLE
Question regarding datasource

### ISSUE THREAD

**Issue by rpajaziti2** [seata/seata#5096]
Hello. So i have a few questions:
1. Is any other datasource supported other than druid, like hikaricp or others? As i have tested with hikari, dbcp and some others, but none worked other than druid. No errors was thrown, but it just didn't work as expected.
2. Is kafka supported yet with Seata?
3. Is Nacos mandatory? As i have been able to run it without nacos.
4. How to set the env variable SEATA_CONFIG_NAME to yml file, or is conf file only supported on docker.
Thanks

**Comment by xingfudeshi** [comment]
1.All DataSource should be supported.
2.They are two things.
3.Nope.We support many of configuration and discovery middleware
4.check this out:https://seata.io/zh-cn/docs/ops/deploy-by-helm.html
