### ISSUE TITLE
携程apollo配置中心版本1.5.1 eurake注册中心  seata该使用哪个版本

### ISSUE THREAD

**Issue by 412940226** [seata/seata#5105]
$ sh apollo-config.sh -h 192.168.40.1 -p 8070 -e DEV -a seata-server -c default -n application -d apollo -r apollo -t a3d4598a8312cc18ce7541d5050059902103fcc7
portalAddr is 192.168.40.1:8070
env is DEV
appId is seata-server
clusterName is default
namespaceName is application
dataChangeCreatedBy is apollo
releasedBy is apollo
token is a3d4598a8312cc18ce7541d5050059902103fcc7
set store.mode=db failure
set store.db.datasource=druid failure
set store.db.dbType=mysql failure
set store.db.driverClassName=com.mysql.cj.jdbc.Driver failure
set store.db.url=jdbc:mysql://localhost:3306/seata?useUnicode=true&rewriteBatchedStatements=true failure
set store.db.user=root failure
set store.db.password=root failure
set store.db.minConn=5 failure
set store.db.maxConn=30 failure
set store.db.globalTable=global_table failure
set store.db.branchTable=branch_table failure
set store.db.queryLimit=100 failure
set store.db.lockTable=lock_table failure
set store.db.maxWait=5000 failure
=========================================================================
 Complete initialization parameters,  total-count:14 ,  failure-count:14
=========================================================================
 init apollo config fail.

这个是使用seata1.4.1版本加载不了配置

**Comment by xingfudeshi** [comment]
Try version 1.5.2

**Comment by 412940226** [comment]
> Try version 1.5.2

这个版本可以用么

**Comment by 412940226** [comment]
这个版本可以用么

**Comment by xingfudeshi** [comment]
Not sure.Pls try it.If there is still a problem, we will fix it soon.

**Comment by xingfudeshi** [comment]
You'd better check whether apollo is configured correctly and started properly.

**Comment by 412940226** [comment]
apollo-config.sh 我通过命令上传配置命令没有错吧

**Comment by 412940226** [comment]
我确定apollo配置正常启动着

**Comment by xingfudeshi** [comment]
Comands are correct.

**Comment by 412940226** [comment]
apollo 携程配置中心这边是使用1.5.1版本

**Comment by xingfudeshi** [comment]
ok.I'll check it out.

**Comment by 412940226** [comment]
是不是需要升级版本，才可以使用seata1.5.2

**Comment by xingfudeshi** [comment]
> 是不是需要升级版本，才可以使用seata1.5.2

Not required.But you can just try it.

**Comment by xingfudeshi** [comment]
It seems the apollo 1.5.1 is too old.Please upgrade and try again

**Comment by 412940226** [comment]
先用apollo1.5.1 配seata1.5.2 搭建尝试一下

**Comment by xingfudeshi** [comment]
Temporarily close the issue, please feel free to feedback if you have any questions.
