### ISSUE TITLE
请求一个问题,我想把全局事务表信息的最终状态数据持久化到自己的库的话该怎么操作,求思路谢谢

### ISSUE THREAD

**Issue by Layfolk-zcy** [seata/seata#5113]

**Comment by a364176773** [comment]
改写源码，将branch和global的delete动作注解掉，lock必须被删除，否则会阻塞事务

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/3499 也可以参考这个pr

**Comment by Layfolk-zcy** [comment]
> 改写源码，将branch和global的delete动作注解掉，lock必须被删除，否则会阻塞事务
DataBaseTransactionStoreManager#writeSession()的方法中注释掉全局事务数据删除 和分支表数据删除后数据会入库,但是回滚时undolog日志在分支数据表数据存在的情况下undolog表数据不会清除。并且重新启动seata的时候会一直打印警告信息,这个引起的原因就是表数据存在的情况下引起的  还是不太懂(功底不行)求教谢谢！！！
