### ISSUE TITLE
在全局事务分支中，如何判断全局事务成功或失败？

### ISSUE THREAD

**Issue by lbj812** [seata/seata#5114]
在全局事务分支中，如何判断全局事务成功或失败？

**Comment by hh13516117509** [comment]
我认为 分支事务不关注全局事务是成功还是失败. 分支事务只执行自己的业务逻辑, 然后记录undolog 并 提交本地分支事务. 如果全局事务失败了. TC会通知RM 进行undolog数据回滚. 如果成功了 TC会通知RM直接删除undolog.

**Comment by a364176773** [comment]
TM侧决议提交至tc，tc返回committed就是成功
