### ISSUE TITLE
Saga 模式存在远程调用，被调用的服务集成了 seata 自动代理数据源，但是 TX_BRANCH_TYPE 不会透传导致创建一个无法结束的 AT 事务

### ISSUE THREAD

**Issue by fishisnow** [seata/seata#5116]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在使用 Seata Saga 模式时，状态机中某个一个子流程是调用（use spring cloud feign）一个远程的 RPC 接口，提供 RPC 接口的 spring-boot 服务集成了 seata (seata.enabled=true).
在事务执行到这个 rpc 接口内部时，由于 TX_BRANCH_TYPE 没有透传，会使用 AT 模式的代理数据源，并且在 seata-server 中注册了一个 AT 模式的分支事务，并且整个 Saga 全局事务结束后，这个 RPC 接口创建的 AT 分支事务并没有正常结束，导致 seata-server 中的全局锁没有释放，下一次请求过来的时候就会由于锁冲突问题导致失败。

### Ⅲ. Describe what you expected to happen
我的疑问是 RPC 调用为啥不将 TX_BRANCH_TYPE 随着 RootContext 透传下去，这样下游可以知道这是一个 Saga 模式的调用，这样就可以不创建 AT 的分支事务，从而避免这个问题。

### Ⅵ. Environment:
JDK version : 1.8
OS :
Others: 'io.seata', name: 'seata-all', version: "1.5.2

**Comment by a364176773** [comment]
saga不支持混用，涉及的服务不要代理数据源
