### ISSUE TITLE
optimize Throwable#getCause

### ISSUE THREAD

**Issue by a364176773** [seata/seata#5119]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
getCause带有同步锁,多次重复对同一个throwable进行getCause是没有必要的.
将Seata源码中多次重复getCause代码进行优化,降低为一次getCause

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by renliangyu857** [comment]
please assign it to me
