### ISSUE TITLE
官网文档上的这个registry.conf 文件 找不到

### ISSUE THREAD

**Issue by dayu521** [seata/seata#5125]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
[nacos注册中心的文档](https://seata.io/zh-cn/docs/user/registry/nacos.html),在`Server端配置注册中心`一节,找不到这个registry.conf,点进去是github page not find 页面

### Ⅱ. Describe what happened

  不知道 直接启动模式 如何吧server注册到nacos中.

**Comment by a364176773** [comment]
https://github.com/seata/seata/tree/develop/script/client
