### ISSUE TITLE
seata1.5.2版本AT模式下，根据年度配置的多数据源，xid传递但是事务不生效。

### ISSUE THREAD

**Issue by ybb007** [seata/seata#5132]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.5.2
- OS :
- Others:

**Comment by a364176773** [comment]
https://github.com/seata/seata-samples/blob/master/multiple-datasource/src/main/java/io/seata/samples/mutiple/datasource/config/DataSourceProxyConfig.java
参考这个sample

**Comment by ybb007** [comment]
多谢老哥，但是我看了一下，我们框架是根据切面获取的多数据源，然后我根据您发的这个例子改了一下，好像还是不生效，堆栈显示xid这些上下文都有，但是就是事务不生效。




| |
yanbinbin_921111
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年12月7日 14:16 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [seata/seata] seata1.5.2版本AT模式下，根据年度配置的多数据源，xid传递但是事务不生效。 (Issue #5132) |

https://github.com/seata/seata-samples/blob/master/multiple-datasource/src/main/java/io/seata/samples/mutiple/datasource/config/DataSourceProxyConfig.java
参考这个sample

**Comment by a364176773** [comment]
看不到你们的代码，所以不知道你们到底有没有正确使用，动态数据源切面读取具体数据源后，一定要去拿被代理的数据源，说明你们拿错了拿成没代理的数据源，所以不生效

**Comment by ybb007** [comment]
老哥，这个动态数据源切面读取具体数据源后，怎么去拿这个被代理的数据源？然后再手动代理？


| |
yanbinbin_921111
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年12月7日 16:06 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [seata/seata] seata1.5.2版本AT模式下，根据年度配置的多数据源，xid传递但是事务不生效。 (Issue #5132) |

看不到你们的代码，所以不知道你们到底有没有正确使用，动态数据源切面读取具体数据源后，一定要去拿被代理的数据源，说明你们拿错了拿成没代理的数据源，所以不生效

**Comment by a364176773** [comment]
你是不是需要读取到具体数据源？你具体数据源什么时候创建的？在创建的地方给他datasourceproxy包起来在用
