### ISSUE TITLE
如果想要实现方法或者类上动态添加全局事务注解的话需要从字节码层面做改动吗?  请教下思路谢谢

### ISSUE THREAD

**Issue by Layfolk-zcy** [seata/seata#5137]

**Comment by a364176773** [comment]
为何不用切面表达式的方式来配置？如果要动态是启动时还是运行中间时动态处理？如果是启动时用javassist或byte-buddy来处理，往方法上加事务注解。
不过方案太过复杂，建议自己用api形式创建事务最为简单，在自己的aop切面里做是否要开启全局事务的判断即可
