### ISSUE TITLE
@GlobalTransactional同用@Transactional，手动回滚异常

### ISSUE THREAD

**Issue by 5venw0ng** [seata/seata#5140]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在`@GlobalTransactional` `@Transactional` 这两个注解同时使用的时候，使用手动回滚会在抛出异常。
`GlobalTransactionContext.reload(RootContext.getXID()).rollback()`
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
Could not register branch into global session xid = xxx status = Rollbacking while expecting Begin]

```
org.springframework.transaction.TransactionSystemException: JDBC commit failed; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: 
Response[ TransactionException[Could not register branch into global session xid = xxx status = Rollbacking while expecting Begin] ]
```

### Ⅲ. Describe what you expected to happen
参考了https://seata.io/zh-cn/blog/seata-spring-boot-aop-aspectj.html 官方案例，和openFeign一起使用，但不论是在 被调用方 手动回滚，还是在发起方手动回滚，入口方法执行完，就会被 TransactionalTemplate中捕捉到。

但是尝试在发起方抛出异常，整个回滚流程是没问题的。去掉 @Transactional 也没问题

```java
Object rs;
try {
    // Do Your Business
    rs = business.execute();
} catch (Throwable ex) {
    // 3. The needed business exception to rollback.
    completeTransactionAfterThrowing(txInfo, tx, ex);   //手动回滚后，总是会回到这里
    throw ex;
}
```

### Ⅴ. Anything else we need to know?
可以确认的是，被调用的服务在全局事务中，XID也能获取到。也已经看过faq 6和 22，但是没有解决

### Ⅵ. Environment:

- JDK version :openjdk11
- Seata version:  1.5.2
- OS :manjaro
- Others:

**Comment by a364176773** [comment]
官网faq

**Comment by 5venw0ng** [comment]
> Collaborator

已经看过faq并且也排查过了

**Comment by 5venw0ng** [comment]
> 官网faq

faq已经看过很多遍了，列出的可能性也能排除 @a364176773 
![image](https://user-images.githubusercontent.com/10112418/206641270-cbf6f99e-9894-49b6-be1d-8a8e29091b24.png)

**Comment by a364176773** [comment]
completeTransactionAfterThrowing(txInfo, tx, ex);   //手动回滚后，总是会回到这里
有没有相关为什么会回到这？不是就抛异常抛出来了，如果实在看不明白faq的话，建议用api方式开启和提交/回滚事务，掌握权完全在你手里

**Comment by a364176773** [comment]
因为你的本地事务走去了commit去注册分支了，你排查问题去看下堆栈的流程先。至于你的本地事务为什么走去commit，那就是要你自己排查了

**Comment by 5venw0ng** [comment]
@a364176773 感谢回复。

我应该是犯了一个严重的错误，错误理解了seata全局事务，简单来说，AT模式下，它是本地的数据源代理（DataSourceProxy）做全局锁检查以及记录一些undo的操作，也就是只关心undo的内容，并不侵入本地事务。

我以为增加了`@GlobalTransactional`之后，它会接管本地事务，所以即使操作了`GlobalTransactionContext.reload(RootContext.getXID()).rollback()` 也只是最终告诉TC要进行全局回滚，但是本地事务如果不处理（回滚本地事务或者抛出异常），最后还是会commit

**Comment by hongmin118** [comment]
> 因为你的本地事务走去了commit去注册分支了，你排查问题去看下堆栈的流程先。至于你的本地事务为什么走去commit，那就是要你自己排查了

方法走完，就会自动commit了，只是我奇怪，注册分支事务为啥是在commit时去注册啊？不应该是方法一开始就注册么？
