### ISSUE TITLE
seata-server.bat无法启动

### ISSUE THREAD

**Issue by Lnsynd** [seata/seata#5143]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
点击seata-server.bat文件，没有反应，显示下图
![image](https://user-images.githubusercontent.com/37909383/206886638-ba75849e-9383-4e6a-97b9-e0fa1a6f64d8.png)

### Ⅱ. Describe what happened

点击seata-server.bat文件
```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :8
- Seata version:  1.4.2
- OS :Windows11
- Others:

**Comment by a364176773** [comment]
用命令行启动看具体错误

**Comment by Lnsynd** [comment]
这个？
![image](https://user-images.githubusercontent.com/37909383/206888484-b30c9906-fb11-46b1-9c9e-8a9160bd8006.png)

**Comment by Lnsynd** [comment]
不提示错误

**Comment by a364176773** [comment]
一般是java环境有问题，1.4.2用jdk8，建议直接用1.5.2
