### ISSUE TITLE
seata client 1.6.0rc  enable to using contextPath for nacos setting

### ISSUE THREAD

**Issue by nisamonica** [seata/seata#5144]
seata client 1.6.0rc  enable to using contextPath for nacos setting

**Comment by nisamonica** [comment]
nacos client login fail after set contextPath ,but server is ok
[com.alibaba.nacos.client.Worker] ERROR c.a.n.c.s.SecurityProxy - [login,149] - login failed: {"code":404,"message":"<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found

12:25:34.205 [com.alibaba.nacos.client.naming.security] ERROR c.a.n.c.s.SecurityProxy - [login,149] - login failed: {"code":404,"message":"<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
you can try use 1.6.0-SNAPSHOT
