### ISSUE TITLE
seata1.5.2多数据源自动代理导致服务端lock表主键冲突

### ISSUE THREAD

**Issue by crazy-sheep** [seata/seata#5147]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
多数据源示例demo multiple-datasorce去除手动数据源代理，引入seata-spring-boot-starter,调用接口操作数据库报错
![pom文件](https://user-images.githubusercontent.com/66940746/207009184-3f341494-1206-47ff-ad98-07fa74f5df0c.png)
![datasourceProxyConfig](https://user-images.githubusercontent.com/66940746/207009387-c8d3ac66-c737-4738-b822-147421542e29.png)

![客户端异常日志](https://user-images.githubusercontent.com/66940746/207009768-a082ccd6-320f-4f29-ae99-81e3c9f7b936.png)

![服务端日志](https://user-images.githubusercontent.com/66940746/207008574-c9f0025a-6d92-4b67-bac4-9279219ceec4.png)

原因:通过继承AbstractRoutingDataSource类，会把自定义dynamicDataSource类的defaultTargetDataSource也代理一次,服务端会收到重复的数据源代理
![服务端注册日志](https://user-images.githubusercontent.com/66940746/207012847-68c28d33-e5b6-4cb9-9f75-cbb87ede6253.png)

解决方式：代理数据源时跳过AbstractRoutingDataSource类型的数据源
![image](https://user-images.githubusercontent.com/66940746/207011924-1a71ffa7-94a1-44da-b0aa-c1eace52bd94.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
假设RoutingDataSource是一个主备datasource？请问如何区分？
或者读写分离的datasource，在与tcc混用下即便是从库也应该checklock

**Comment by a364176773** [comment]
seata本身要求类似mp提供的动态数据源这类功能包括sharding-jdbc这类都是要关闭自动代理
