### ISSUE TITLE
【Seata后台的事务信息列表】能否配置事务信息在列表中保留的时间呢

### ISSUE THREAD

**Issue by legendwu9527** [seata/seata#5149]
## Why you need it?
<img width="1451" alt="信息列表" src="https://user-images.githubusercontent.com/24804123/207235775-b01947f2-72c5-4c92-aeae-cf26a1d0f986.png">

当前情况：事务在回滚后，事务的信息在数据库中会被立即删除
预期：在一个时间周期内展示事务的详细信息，包括已经处理完成的事务
## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
storemode改为file以外的配置如db或redis，默认下可以保留globalsession 2分10秒
配置server.retryDeadThreshold到具体seata-server使用的配置中心中，值为延迟的时长，单位ms

**Comment by legendwu9527** [comment]
seata-server 的application.yml中加上了server.retryDeadThreshold=130000000 ，但是在后台事务信息的列表中只能查到status为Rollbacking的记录。查不到其他状态的事物。这个配置是否只是延迟事物回滚的功能呢？有没有能控制所有状态（成功、失败、回滚中等）事务信息的配置。
<img width="673" alt="image" src="https://user-images.githubusercontent.com/24804123/207569602-5d041cef-0d85-4f77-b593-9c1a29f1f744.png">
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/24804123/207569766-15a3cce6-7b2b-4918-aaf2-a72a7fd039c6.png">

**Comment by a364176773** [comment]
store.mode=file是不会延迟删除的，内存寸土寸金

**Comment by legendwu9527** [comment]
图二,store.mode配置的是db,nacos 和 config 配的是file

**Comment by legendwu9527** [comment]
测试确实是延迟删除了，但是貌似只是延迟回滚而已，状态一直是在Rollbacking，时间到了才删除。我的意思是能否事务还是正常处理，而不是一直在Rollbacking状态，到了配置的时间后才回滚完成。只是处理后的记录延迟删除。
