### ISSUE TITLE
Please help to confirm the problem, thank you very much

### ISSUE THREAD

**Issue by ingxiaowei** [seata/seata#5154]
![1671010374572_1F1DDDD6-DB15-4b95-8EC3-FC79475C9A85](https://user-images.githubusercontent.com/27408232/207561986-2064bbfb-38c8-4d87-9bd3-e21372768c06.png)
![1671010433147_E8F002D5-F098-4a7a-9FF2-4EEC09B525DE](https://user-images.githubusercontent.com/27408232/207562055-7b1c9c54-4426-4c28-a580-c9744e0431e0.png)
![1671010758754_E54DCCA6-EEEC-42d8-82D4-29F6F5A7A61B](https://user-images.githubusercontent.com/27408232/207562084-e09be6d0-3ce2-44e7-bf96-4938763d9296.png)
![1671010779598_33538416-AC8F-44b3-B629-B799B073B42C](https://user-images.githubusercontent.com/27408232/207562119-8494344d-504c-4cf1-aac9-9136b6d80dc8.png)

Configure load don't know what went wrong, now is availInetSocketAddressList is empty, is there can help solve, thank you very much

**Comment by a364176773** [comment]
What is your registration center? And what is the content of your profile?
