### ISSUE TITLE
seata 会在事务完成时会立马删除事务的信息，请教一下这样的设计的原因

### ISSUE THREAD

**Issue by legendwu9527** [seata/seata#5158]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
<img width="741" alt="image" src="https://user-images.githubusercontent.com/24804123/207820746-dc3bf73a-667f-47d3-891b-686ff3def602.png">

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
避免global table和branch table数据量过大，lock侧会阻塞at的事务，所以事务结束一定会删除lock。
本身是沿用了file的设计，因为file是存储至内存再刷到磁盘，内存是寸土寸金的，必须做到结束的事务进行删除，否者很有可能引起oom
