### ISSUE TITLE
是否有根据源码构建镜像/安装包的步骤的文档说明

### ISSUE THREAD

**Issue by legendwu9527** [seata/seata#5159]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/distribution/Dockerfile

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/207822209-bc305ff9-362b-4af2-af05-dd96510e8263.png)

**Comment by legendwu9527** [comment]
多谢指导
