### ISSUE TITLE
store.mode=db模式会有global_table数据量太大导致oom的问题吗？

### ISSUE THREAD

**Issue by legendwu9527** [seata/seata#5161]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
在以下issue里：
https://github.com/seata/seata/issues/5158
您提到的store.mode=db模式下,沿用了file模式的事务结束就删除事务的设计，因为存储至内存再刷到磁盘以避免oom.
使用db模式会全部存到内存吗，会不会也有global_table数据量太大导致oom的问题
## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
可能性非常低，global table和branch table太大导致查询效率低之类的
你可以参考 https://github.com/seata/seata/pull/3499 这个延迟删除的pr
