### ISSUE TITLE
请问branch_table中有一个resource_group_id，这个参数是在哪里配置的，有什么作用？

### ISSUE THREAD

**Issue by legendwu9527** [seata/seata#5169]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/24804123/208361728-351774e9-4e16-49c0-b7de-479366feb4a5.png">

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
@legendwu9527 Currently not useful, there will be the concept of data source group in the future, which can support dynamic switching of the database to other instance with the same table structure.
