### ISSUE TITLE
hsf-tcc可以支持几个子事务(即几个RM)

### ISSUE THREAD

**Issue by alant77** [seata/seata#5175]
我在测试3个RM的时候，第三个RM的prepare失败，只回滚后面两个，第一个不回滚。我参照的seata-samples中的hsf-tcc模块，进行的测试

**Comment by wangliang181230** [comment]
seata并未限制分支事务的数量。

**Comment by wangliang181230** [comment]
你是第三个分支没有生效？需要检查下XID有没有正常传递到第三个RM那。
