### ISSUE TITLE
Seata 中，部分bean为 `BeanPostProcessor`，在自动装配类中，创建这些bean的方法，必须添加上 `static` 关键字。

### ISSUE THREAD

**Issue by wangliang181230** [seata/seata#5176]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Seata 中，存在部分bean为 `BeanPostProcessor`，在自动装配类中，创建这些bean的方法，必须添加上 `static` 关键字。
否则，会导致部分 bean 扫描不到。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
无
```

### Ⅲ. Describe what you expected to happen

待测试......

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?

springboot 官方针对这块内容的说明章节
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-factorybeans-annotations

### Ⅵ. Environment:

- JDK version : *
- Seata version:  <= 1.6.0
- OS : *
- Others: 无

**Comment by whxxxxx** [comment]
plz assign to me
