### ISSUE TITLE
seata在insert时若数据表中存在sql关键词会报sql异常。``符号也不管用。

### ISSUE THREAD

**Issue by LuDragon** [seata/seata#5192]

**Comment by a364176773** [comment]
You can use version 1.6

**Comment by hwh32675834** [comment]
我们就是用的1.6.1也会出现此种情况

**Comment by linsmalldragon** [comment]
我也有这情况, 如果有一列叫 row,  seata没加`row`, 导致插入出错

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/5310  需要等待1.7或2.x发版

**Comment by yinrog** [comment]
完全不能用于生产，seata，严重bug都不出修复版本
