### ISSUE TITLE
1.3.0 为啥我用okhttp远程调用 服务，报错后，远程的服务没有回滚为啥

### ISSUE THREAD

**Issue by wwg2017** [seata/seata#5198]
1.3.0 为啥我用okhttp远程调用 服务，报错后，远程的服务没有回滚为啥，被调用的服务也没有xid
这个个时候 我再请求头上加了xid，可以回滚，，
但是有个问题，就是 A调用b服务，，b服务报错，都没有回滚，a报错都回滚
如果改用feign调用，A--》b，，b报错，b回滚，a不回滚

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/5199
