### ISSUE TITLE
我用okhttp远程调用 A---->B   然后B里我写了1/0  报错，，发现都没有回滚，，feign和restTemplate 可以回滚正常

### ISSUE THREAD

**Issue by wwg2017** [seata/seata#5199]
我用okhttp远程调用 A---->B   然后B里我写了1/0  报错，，发现都没有回滚，，feign和restTemplate 可以回滚正常

**Comment by a364176773** [comment]
restTemplate和feign 被sca做了代理,自动传递xid,okhttp自己写的工具类,需要自己传递xid

**Comment by ahaha-vip** [comment]
一开始我也很奇怪被调用的服务居然不需要 `@GlobalTransactional` 注解，原来在请求头里面把事务标识传过去了。

见 `SeataFeignClientAutoConfiguration` `SeataRestTemplateAutoConfiguration`

`
com.alibaba.cloud.seata.feign.SeataFeignClient#execute
`
`
com.alibaba.cloud.seata.rest.SeataRestTemplateInterceptor#intercept
`
