### ISSUE TITLE
Path traversal

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [seata/seata#520]
您好：
我是360代码卫士团队的工作人员，在我们的开源项目检测计划中发现fescar中存在路径遍历缺陷。
com.alibaba.fescar.server.store.FileTransactionStoreManager.java
![image](https://user-images.githubusercontent.com/39950310/53791049-6a586180-3f63-11e9-89b6-b2352dba64e8.png)
当fullFileName的值为一些特殊的字符（如“..”和“/”），可以摆脱受保护的限制，访问一些受保护的文件或目录。
com.alibaba.fescar.server.Server.java
![image](https://user-images.githubusercontent.com/39950310/53791536-a6d88d00-3f64-11e9-8931-d9ed3a14a7b8.png)
我们发现数据的污染源来自main方法的参数，main方法的参数来源于外部，且未做过滤,会导致路径遍历。
建议对可能造成威胁的输入参数进行过滤

**Comment by slievrly** [comment]
@360CodeSafe how can i contact you？

**Comment by 360CodeSafe** [comment]
> @ 360CodeSafe我怎么联系你？

codesafescan@360.net

**Comment by xingfudeshi** [comment]
Thank you for informing us of this problem.I'll fix it soon.
