### ISSUE TITLE
请教下如果通过源码进行编译构建可部署的tar.gz包

### ISSUE THREAD

**Issue by GitHub-JXJ** [seata/seata#5202]
目前发现部分版本有存在一些漏洞，希望通过源码进行修复，但是修复完之后不知如何进行打包构建成类似官方提供的tar.gz那种部署包，盼回复

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/overview/faq.html

**Comment by GitHub-JXJ** [comment]
thanks
