### ISSUE TITLE
模式设置为db，但是数据库表没记录，控制台有记录，怀疑是file有没有什么办法进行进一步排查

### ISSUE THREAD

**Issue by xiaoyuwang1987** [seata/seata#5205]
store.mode=db
store.lock.mode=db
store.session.mode=db

seata-server日志：10:18:29.139  INFO --- [verHandlerThread_1_23_500] i.seata.server.coordinator.AbstractCore  : Register branch successfully, xid = 192.168.9.110:9001:45378911314806322, branchId = 45378911314806326, res

有改过nacos连接seata数据库配置，如(账号不对的情况，或者删除全局表等)，seata-server启动后会报错，所以应该是连到数据库了

**Comment by a364176773** [comment]
server启动如果有datasource相关日志输出就是db模式，如果没有就是其他
事务结束后就会删除你在控制台看到，再去数据库看肯定已经删光了，tm侧globaltransational注解下的方法return前打个断点，去数据库看，或者方法内加sleep，或者制造事务回滚，回滚的事务在数据库会残留2分钟

**Comment by xiaoyuwang1987** [comment]
> server启动如果有datasource相关日志输出就是db模式，如果没有就是其他 事务结束后就会删除你在控制台看到，再去数据库看肯定已经删光了，tm侧globaltransational注解下的方法return前打个断点，去数据库看，或者方法内加sleep，或者制造事务回滚，回滚的事务在数据库会残留2分钟

我的是生产环境不好打断点，你说的启动有datasource相关信息在哪里

**Comment by xiaoyuwang1987** [comment]
启动完成没有看到datasource的日志

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/209753221-6db844c6-e9b5-4568-b99d-29926dc53ef0.png)
这不就是吗？less 看下日志搜下/datasource 随便都能看到，还有你觉得没有数据，你可以去看binlog里到底有没有数据落下来的记录

**Comment by xiaoyuwang1987** [comment]
> ![image](https://user-images.githubusercontent.com/19943636/209753221-6db844c6-e9b5-4568-b99d-29926dc53ef0.png) 这不就是吗？less 看下日志搜下/datasource 随便都能看到，还有你觉得没有数据，你可以去看binlog里到底有没有数据落下来的记录

![image](https://user-images.githubusercontent.com/24749103/209767929-76ea39c2-619c-4f4b-9438-fcd103074e6c.png)
我dump了binglog日志，没有看到insert关键字东西，不知道截图这个是不是有算插入
