### ISSUE TITLE
我想了解下lock_table  branch_table    undo_log   这三张表的插入顺序

### ISSUE THREAD

**Issue by wwg2017** [seata/seata#5207]
我想了解下lock_table  branch_table    undo_log   这三张表的插入顺序大概是什么

**Comment by a364176773** [comment]
at  lock 插入成功了->branch 插入->undolog插入
其余 branch直接插入

**Comment by wwg2017** [comment]
> at lock 插入成功了->branch 插入->undolog插入 其余 branch直接插入

at模式：假如请求走到数据库层面先执行业务sql，然后再上报给tc注册这个分支，tc服务端收到请求 lock 插入成功了->branch 插入，，然后再响应给rm，rm再插入undolog 么？
