### ISSUE TITLE
Explicit output of storage mode information in logs

### ISSUE THREAD

**Issue by a364176773** [seata/seata#5209]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
目前启动的时候没有明确输出seata-server使用的session和lock的type 如 db，redis，file
加上数据基本上是秒删，导致用户启动后并不是非常直观能知道自己配置的是否正确，需要在日志上增加标识信息

The current startup does not explicitly output the type of session and lock used by seata-server such as db, redis, file plus the data is basically deleted in seconds, resulting in the user not being able to intuitively know whether they are configured correctly after startup, and need to add identification information to the logs

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by selectbook** [comment]
please assign it to me

**Comment by a364176773** [comment]
> please assign it to me

Looking forward to your pr

**Comment by a364176773** [comment]
@selectbook Since it has been too long without your feedback, this task will be released to others
