### ISSUE TITLE
seata-server容器里面为什么装不了arthas？

### ISSUE THREAD

**Issue by xiaoyuwang1987** [seata/seata#5211]
想在seata-server 启动的容器里面装一个arthas，但是提示

/arthas # java -jar arthas-boot.jar
[INFO] JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/jre
[INFO] arthas-boot version: 3.6.7
[INFO] Can not find java process. Try to run `jps` command lists the instrumented Java HotSpot VMs on the target system.
Please select an available pid.
seata-server 不是java服务吗？

**Comment by a364176773** [comment]
jre是没有jps，jstack这些命令的，你用的是什么版本的seata镜像

**Comment by xiaoyuwang1987** [comment]
> jre是没有jps，jstack这些命令的，你用的是什么版本的seata镜像

1.5.2的

**Comment by a364176773** [comment]
1.5.2是jre，所以跑不了，你可以自行在里面装个jdk，也可以升级1.6
