### ISSUE TITLE
加了一串输出日志代码，持久化到镜像中，为什么启动没有生效？

### ISSUE THREAD

**Issue by xiaoyuwang1987** [seata/seata#5213]
![IP%5%Y4VLJGLL7K$93)(60K](https://user-images.githubusercontent.com/24749103/209789119-82d595a1-046d-4003-8356-405ebaf381d5.jpg)
![image](https://user-images.githubusercontent.com/24749103/209789329-c95cd253-eac2-4ce3-8bb7-04d0666d1073.png)

**Comment by a364176773** [comment]
详细说说怎么持久化到镜像中？

**Comment by xiaoyuwang1987** [comment]
> 详细说说怎么持久化到镜像中？

![image](https://user-images.githubusercontent.com/24749103/209791813-c6af853a-b047-4b29-a821-1c66a0cdd985.png)
![image](https://user-images.githubusercontent.com/24749103/209791912-966b2488-f5f2-4617-9b61-c54cfdc0db2e.png)

**Comment by a364176773** [comment]
建议你自己反编译看看到底有没有打包正确的代码进去

**Comment by xiaoyuwang1987** [comment]
> 建议你自己反编译看看到底有没有打包正确的代码进去

打包进去了 system.out.println就出的来

**Comment by a364176773** [comment]
> > 建议你自己反编译看看到底有没有打包正确的代码进去
> 
> 打包进去了 system.out.println就出的来

按你这么说tc其他日志也出不来才对，估计是第一次没打包好，第二次改成systemout打进去了，误以为前者不生效
