### ISSUE TITLE
at模式：假如请求走到数据库层面先执行业务sql，然后再上报给tc注册这个分支，tc服务端收到请求 lock 插入成功了->branch 插入，，然后再响应给rm，rm再插入undolog 么？

### ISSUE THREAD

**Issue by wwg2017** [seata/seata#5214]
at模式：假如请求走到数据库层面先执行业务sql，然后再上报给tc注册这个分支，tc服务端收到请求 lock 插入成功了->branch 插入，，然后再响应给rm，rm再插入undolog 么？

**Comment by a364176773** [comment]
是这样，但业务事务不会在branch插入前提交，一定是注册了分支才有可能提交分支事务

**Comment by wwg2017** [comment]
> 
您看下 我的订单表时间 总是小于分支表时间，说明分支表插入之前 订单表业务已经插入了
订单表时间
![image](https://user-images.githubusercontent.com/27998578/209801404-a8161d3a-cfd1-4c55-bf8f-b9b9859ff65e.png)
分支表时间
![image](https://user-images.githubusercontent.com/27998578/209801491-5525821c-021e-4366-a8ee-4a5dd3569dbb.png)

**Comment by a364176773** [comment]
> > 
> 
> 您看下 我的订单表时间 总是小于分支表时间，说明分支表插入之前 订单表业务已经插入了 订单表时间，您说的是二级段的全局提交，一定是在注册了分支事务之后才会吧 ![image](https://user-images.githubusercontent.com/27998578/209801404-a8161d3a-cfd1-4c55-bf8f-b9b9859ff65e.png) 分支表时间 ![image](https://user-images.githubusercontent.com/27998578/209801491-5525821c-021e-4366-a8ee-4a5dd3569dbb.png)

 确认下两者数据库的时区是否一致,然后分支事务的时间肯定是比tcbranch的时间要早的,因为是在本地事务commit前去注册的分支,你的sql,业务代码都执行完了,当然是比branch插入时间要早

**Comment by wwg2017** [comment]
> > > 
> > 
> > 
> > 您看下 我的订单表时间 总是小于分支表时间，说明分支表插入之前 订单表业务已经插入了 订单表时间，您说的是二级段的全局提交，一定是在注册了分支事务之后才会吧 ![image](https://user-images.githubusercontent.com/27998578/209801404-a8161d3a-cfd1-4c55-bf8f-b9b9859ff65e.png) 分支表时间 ![image](https://user-images.githubusercontent.com/27998578/209801491-5525821c-021e-4366-a8ee-4a5dd3569dbb.png)
> 
> 确认下两者数据库的时区是否一致,然后分支事务的时间肯定是比tcbranch的时间要早的,因为是在本地事务commit前去注册的分支,你的sql,业务代码都执行完了,当然是比branch插入时间要早

嗯嗯，我刚才看了源码然后调试，发现commit前，数据库订单表是没有数据的，确实是远程注册之后，分支注册表是有数据，但是分支全局表数据又要依赖于本地事务业务sql组成的主键key，，，，所以业务sql只是组装sql，并没有改变数据库物理磁盘，

**Comment by a364176773** [comment]
是的，seata不会改变业务sql的内容，所以sql发出是什么样，就是什么样

**Comment by wwg2017** [comment]
> 是的，seata不会改变业务sql的内容，所以sql发出是什么样，就是什么样

牛啊 你们这些阿里开源者简直就是天才啊赞赞赞

**Comment by a364176773** [comment]
> > 是的，seata不会改变业务sql的内容，所以sql发出是什么样，就是什么样
> 
> 牛啊 你们这些阿里开源者简直就是天才啊赞赞赞

哈哈过奖了，欢迎有机会也参与到社区的贡献中来
