### ISSUE TITLE
seata数据库没有数据，但是控制台有数据，确认是db模式？

### ISSUE THREAD

**Issue by xiaoyuwang1987** [seata/seata#5215]
用的是at模式，也有连上nacos，读取到对应的配置文件，数据库也是对的。
配置文件：
store.mode=db
store.lock.mode=db
store.session.mode=db

还有什么办法排查，主要是生产环境，seata-server日志也能正常输出xid那些。还有binlog日志没有插入的信息，undolog是正常的，云产品mysql没有看到seata服务连接池信息

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/5205
