### ISSUE TITLE
seata-server读取nacos地址，账号密码的代码在哪里

### ISSUE THREAD

**Issue by xiaoyuwang1987** [seata/seata#5217]
yml配置文件连上注册的nacos，这些代码在哪块我想调研一下

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
https://github.com/seata/seata/blob/develop/seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java

**Comment by xiaoyuwang1987** [comment]
> https://github.com/seata/seata/blob/develop/config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java

为什么用Logger.info打印不出来，是不是要在哪里开启，用system.out.println可以
