### ISSUE TITLE
关于Seata提供的Metrics的status

### ISSUE THREAD

**Issue by xyh081117** [seata/seata#5225]
目前使用的是1.5版本的Seata，配置了grafana和prometheus，请问Metrics里面的status有5个AfterCommitted、AfterRollbacked、committed、rollbacked、active，前四个的含义和区别是什么？

**Comment by a364176773** [comment]
字面含义，committed后，2分钟延迟删除下会再打一个aftercommitted，rollback同理，active纯字面含义
