### ISSUE TITLE
大佬们、seata客户端，事务里面 怎么获取branchId，

### ISSUE THREAD

**Issue by qq962155660** [seata/seata#5242]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

我客户端分支事务里面往mysql mq消息表插入了一条记录，二阶段分支事务commit的时候我会根据xid,branchId修改这条记录、然后有个任务轮询这张表，进行mq消息的发送;
所以我怎么在客户端获插入消息的时候，怎么获取当前的branchId呢？

**Comment by qq962155660** [comment]
> 你的消息需要有序吗?如果不需要为何不只标xid即可?然后注册个tm的hook,事务提交后触发发mq消息,或者注册个tcc分支,把tcc分支注册的时候提交mq消息,二阶段的时候再实际发出消息?

1.有序
2.只标记xid, xid是全局唯一的吗？
3.我用的at模式，不想写补偿代码；只有二阶段提交的时候才发消息

**Comment by a364176773** [comment]
> 

先尝试用tcc,二阶段会下发调你的tcccommit接口,是有branchid和xid的,你commit接口里的逻辑是自己写的,你一阶段可以写消息表,二阶段从消息表拿数据
