### ISSUE TITLE
Seata1.6.1，ext/apm-seata-skywalking-plugin模块在最后编译，导致首次编译打包时distribution目录下无ext子目录

### ISSUE THREAD

**Issue by HEIBAIJIE** [seata/seata#5245]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
由于distribution模块不依赖ext/apm-seata-skywalking-plugin模块，导致distribution先于ext/apm-seata-skywalking-plugin构建。
这导致release-seata.xml中
![image](https://user-images.githubusercontent.com/33556050/211740156-a86711d5-f5db-4a9d-a81b-7819f233a931.png)

的打包动作在首次构建时不会生效。
这将进一步导致Dockerfile中的这一行
ADD ext/ /seata-server/ext
在构建镜像时会报错。

这一bug在第二次构建时会消失，因为apm-seata-skywalking-plugin在上一次构建时已经打包完成了。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
![image](https://user-images.githubusercontent.com/33556050/211739352-e691f5b5-964c-4502-b7d5-b291b9fb29c0.png)
![image](https://user-images.githubusercontent.com/33556050/211739465-1c44092d-d4c3-4811-9930-3fff8798a7bd.png)
可以看到apm-seata-skywalking-plugin晚于distribution
![image](https://user-images.githubusercontent.com/33556050/211740057-cfd8b5aa-f33e-4ad1-abda-7fa0e34b46cb.png)

### Ⅲ. Describe what you expected to happen
预期是先构建apm-seata-skywalking-plugin再构建distribution

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1. 下载1.6.1源码包。
2. 运行 mvn -Prelease-seata -Dmaven.test.skip=true clean install -U
3. 观察distribution/target/seata-server-1.6.1/seata，其中没有ext子目录

### Ⅴ. Anything else we need to know?
建议distribution模块依赖apm-seata-skywalking-plugin模块

### Ⅵ. Environment:

- JDK version : 1.8.0_272
- Seata version:  1.6.1
- OS : Windows10
- Others: maven 3.6.3

**Comment by slievrly** [comment]
@HEIBAIJIE  Can you submit a pr to fix this issue  ?

**Comment by HEIBAIJIE** [comment]
@slievrly I will submit a pr tonight.

**Comment by slievrly** [comment]
> @slievrly I will submit a pr tonight.

thanks for your contribution.
