### ISSUE TITLE
seata 1.6.1 no available service found in cluster 'default', please make sure registry config correct and keep your seata server running 🆘🆘

### ISSUE THREAD

**Issue by lhh18** [seata/seata#5248]
# 这是server端启动日志
![image](https://user-images.githubusercontent.com/74589636/212011278-ecf8b5cf-0083-4254-9d30-3c6014f41601.png)
# 这是server端的配置文件application.yml
![image](https://user-images.githubusercontent.com/74589636/212014283-362c7259-8a54-492d-9505-d8f92c5ecf3d.png)
# 这是nacos配置中心的seata.properties
![image](https://user-images.githubusercontent.com/74589636/212013059-6ae858a7-bd01-4aa3-994c-7c2124a2c96c.png)
![image](https://user-images.githubusercontent.com/74589636/212012938-f8a13b4a-ed94-43f6-817c-487e269b85d4.png)
# server端已正常注册到nacos
![image](https://user-images.githubusercontent.com/74589636/212013418-a83618e5-695e-4ba5-9325-e7077f416b07.png)
![image](https://user-images.githubusercontent.com/74589636/212013495-863ecad6-f9c8-4c1d-8762-457d055e1bf4.png)
# client端的配置文件
![image](https://user-images.githubusercontent.com/74589636/212013674-2dd54e54-d4df-485f-8d73-11e1b54478da.png)
# client端的报错信息
![image](https://user-images.githubusercontent.com/74589636/212015407-136f98c4-8326-44b6-b8e2-b2e3e6688c2f.png)
# `seata-server版本为1.6.1 pom文件为seata-spring-boot-starter 1.6.1`
# `救命🆘🆘`

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/212017129-2cebe998-acad-4944-a292-71238c66cb9b.png)
检查group，namespace，client和server是否一致

**Comment by a364176773** [comment]
并且确定client用的是nacos做注册中心

**Comment by lhh18** [comment]
> 并且确定client用的是nacos做注册中心

client确定是注册到nacos中了，我再三检查group，确定均为DEFAULT_GROUP，namespace都是没有写的。对了好多遍，就是死活找不到哪里有问题😭😭 所有的配置都贴上了，能大致看出哪里不对么😭

**Comment by a364176773** [comment]
> > 并且确定client用的是nacos做注册中心
> 
> client确定是注册到nacos中了，我再三检查group，确定均为DEFAULT_GROUP，namespace都是没有写的。对了好多遍，就是死活找不到哪里有问题😭😭 所有的配置都贴上了，能大致看出哪里不对么😭

clustername读到了是default，是注册中心服务发现不了，https://github.com/seata/seata/blob/develop/discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java 自行debug这个类的lookup，也可以看下初始化的时候client的getNamingProperties 中的配置到底是什么

**Comment by lhh18** [comment]
> > > 并且确定client用的是nacos做注册中心
> > 
> > 
> > client确定是注册到nacos中了，我再三检查group，确定均为DEFAULT_GROUP，namespace都是没有写的。对了好多遍，就是死活找不到哪里有问题😭😭 所有的配置都贴上了，能大致看出哪里不对么😭
> 
> clustername读到了是default，是注册中心服务发现不了，https://github.com/seata/seata/blob/develop/discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java 自行debug这个类的lookup，也可以看下初始化的时候client的getNamingProperties 中的配置到底是什么

可以拜托帮我看下哪里可能有问题吗，我是在找不出（弱鸡😭）
![image](https://user-images.githubusercontent.com/74589636/212224633-b7e8b64f-4d46-4628-83d5-434dff1d5006.png)
![image](https://user-images.githubusercontent.com/74589636/212224692-522984da-1910-47eb-bc58-4bc49e0aeb0a.png)
![image](https://user-images.githubusercontent.com/74589636/212224716-c48dc737-332f-47ac-a07a-c816975436f5.png)

**Comment by a364176773** [comment]
自己curl nacos的openapi看看能不能查到，不能查到就是nacos有bug，自行组装对应参数，对应server端的参数，进行curl

**Comment by a364176773** [comment]
或者降级到1.4.2先测下是不是恢复正常

**Comment by a364176773** [comment]
看了下你这个servername写错了吧？为什么是system-server?

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/212296796-2b6c2b03-f22f-4aac-9a74-ae71b63aeddc.png)
这里填的是seata-server的application

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/script/client/spring/application.yml
这不写这吗，有些配置要仔细看，而不能瞎配

**Comment by cc4dogman** [comment]
nacos加一个配置
service.vgroupMapping.${client应用名}-seata-service-group=default

**Comment by lhh18** [comment]
> ![image](https://user-images.githubusercontent.com/19943636/212296796-2b6c2b03-f22f-4aac-9a74-ae71b63aeddc.png) 这里填的是seata-server的application

感谢旺仔，此处的application应为seata的application名称（默认为seata-server），不应为自己client的。已解决，非常感谢！

**Comment by lhh18** [comment]
> nacos加一个配置 service.vgroupMapping.${client应用名}-seata-service-group=default

感谢老哥，seata在新版本默认为default了，如果不需要配置别的事务组，这个service.vgroupMapping不需要额外写的。是我的seata的application配置错了。

**Comment by ETLGRN** [comment]
兄弟能详细的说下你是怎么解决的吗？我也碰到了一样的问题？现在看不出来是什么问题，非常感谢

**Comment by hebian1994** [comment]
找到抛出错误的地方，慢慢阅读下源码知道他在干什么就能解决了。
public List<InetSocketAddress> lookup(String key) throws Exception {
        String clusterName = getServiceGroup(key);
        if (null == clusterName) {
            return null;
        }
        if (!LISTENER_SERVICE_MAP.containsKey(clusterName)) {
            synchronized (LOCK_OBJ) {
                if (!LISTENER_SERVICE_MAP.containsKey(clusterName)) {
                    List<String> clusters = new ArrayList<>();
                    clusters.add(clusterName);
//去default分组里找叫做seata-server的服务，而seata-server就是seata服务端了，所以只要确保服务端注册到了DEFAULT-GROUP就行了
                    List<Instance> firstAllInstances = getNamingInstance().getAllInstances(getServiceName(), clusters);
                    if (null != firstAllInstances) {
                        List<InetSocketAddress> newAddressList = firstAllInstances.stream()
                                .filter(instance -> instance.isEnabled() && instance.isHealthy())
                                .map(instance -> new InetSocketAddress(instance.getIp(), instance.getPort()))
                                .collect(Collectors.toList());
                        CLUSTER_ADDRESS_MAP.put(clusterName, newAddressList);//放地址
                    }
                    subscribe(clusterName, event -> {
                        List<Instance> instances = ((NamingEvent)event).getInstances();
                        if (null == instances && null != CLUSTER_ADDRESS_MAP.get(clusterName)) {
                            CLUSTER_ADDRESS_MAP.remove(clusterName);
                        } else if (!CollectionUtils.isEmpty(instances)) {
                            List<InetSocketAddress> newAddressList = instances.stream()
                                    .filter(instance -> instance.isEnabled() && instance.isHealthy())
                                    .map(instance -> new InetSocketAddress(instance.getIp(), instance.getPort()))
                                    .collect(Collectors.toList());
                            CLUSTER_ADDRESS_MAP.put(clusterName, newAddressList);//放地址
                        }
                    });
                }
            }
        }
        return CLUSTER_ADDRESS_MAP.get(clusterName);
    }
所以先修改服务端配置文件，将分组改成DEFAULT-GROUP
registry {
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "127.0.0.1:8848"
    group = "DEFAULT_GROUP"
    namespace = ""
    cluster = "default"
    username = ""
    password = ""
  }

}

config {

  type = "nacos"

  nacos {
    serverAddr = "127.0.0.1:8848"
    namespace = ""
    group = "DEFAULT_GROUP"
    username = ""
    password = ""
  }

}

然后修改微服务的配置文件
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: SEATA_GROUP
      cluster: default
  config:
    type: nacos
    nacos:
      namespace: ""
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
