### ISSUE TITLE
建议：针对二阶段的重试能有配置进行处理？

### ISSUE THREAD

**Issue by AHangC** [seata/seata#5249]
起因是自己在测试TCC模式，模拟了在二阶段提交/回滚上如果因为一些原因导致一直失败，然后发现会不断的进行重试。跟进源码发现似乎并没有针对二阶段重试的限制，配置中似乎也没有发现。源码中针对二阶段的提交或回滚似乎也只会返回 成功或未成功重试 两种状态。
![image](https://user-images.githubusercontent.com/73221211/212022623-c03f3e12-bd73-452d-ab0d-28594f3f2840.png)

对于TCC模式感觉可以自己编码去处理，但是我看XA模式似乎也是这样。此外对于AbstractResourceManager的自实现似乎只有通过SPI实现，但是这种实现是根据branchType来初始化的，在进行处理时也是根据对应的branchType获取，但是似乎没有配置能去指定branchType来使用自己实现的ResourceManager，是否只有根据branchType覆盖原来的呢？
![image](https://user-images.githubusercontent.com/73221211/212023766-aa2bc390-dd87-409c-9d5c-8bad44642f0d.png)
![image](https://user-images.githubusercontent.com/73221211/212023930-8adca493-bfc7-4903-b238-69f9ebc61e35.png)

**Comment by a364176773** [comment]
目前就是无限重试，除非返回不可重试的状态，无限重试就是为了最终一致性，但是太过粗暴
后续会增加重试策略，可配置策略后按照策略重试，而不是1s一次

**Comment by a364176773** [comment]
二阶段应该是一个终态，也就是最终就应该是什么样子，而不应该有过多的扩展和配置影响实际数据的处理，应该是一个单一动作，不存在其他计算型开销，开销应该在一阶段处理完，二阶段将状态应用，比如扣款，扣款前可能有一定业务逻辑，扣款一阶段后，二阶段只需要扣款，那这种情况就是单一的动作，基本上不存在什么异常点，也即便有也应该是无限重试将其恢复，比如数据库挂了之类的

**Comment by AHangC** [comment]
> 二阶段应该是一个终态，也就是最终就应该是什么样子，而不应该有过多的扩展和配置影响实际数据的处理，应该是一个单一动作，不存在其他计算型开销，开销应该在一阶段处理完，二阶段将状态应用，比如扣款，扣款前可能有一定业务逻辑，扣款一阶段后，二阶段只需要扣款，那这种情况就是单一的动作，基本上不存在什么异常点，也即便有也应该是无限重试将其恢复，比如数据库挂了之类的

emmm...确实应该是这样，3Q
