### ISSUE TITLE
配置store.redis.database不生效

### ISSUE THREAD

**Issue by mumu-lab** [seata/seata#5254]
seata的store模式选用redis的时候，store.redis.database默认是0库，但是手动指定为别的库时不生效，仍然走的是0库

**Comment by mumu-lab** [comment]
![image](https://user-images.githubusercontent.com/46178311/212794458-066e20a7-77b1-4eac-9141-7346fb79e542.png)

**Comment by a364176773** [comment]
Is a configuration center other than file used?

**Comment by mumu-lab** [comment]
使用nacos作为配置中心，seata版本为1.5.2

**Comment by a364176773** [comment]
那就写到nacos上，而不是本地

**Comment by mumu-lab** [comment]
是写到nacos上的，如上面附图的配置，但是生效仍然是0库

**Comment by a364176773** [comment]
> 是写到nacos上的，如上面附图的配置，但是生效仍然是0库

那你可以试试写本地，把config.type=nacos改为file，看看本地是否生效，或者将nacos上redis的ip之类的改错，看看还是否能用

**Comment by a364176773** [comment]
`new JedisPool(poolConfig, host, port, 60000, password, CONFIGURATION.getInt(ConfigurationKeys.STORE_REDIS_DATABASE, DATABASE));`
源码就是这么简单一行代码构建的jedispool，你可以自己写个main方法测一下你的redis

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/server/src/main/java/io/seata/server/storage/redis/JedisPooledFactory.java

**Comment by mumu-lab** [comment]
非常感谢，已经解决了，换成本地文件正常，有可能是nacos上的配置是yaml格式的原因，这边再详细检查下

**Comment by a364176773** [comment]
> 非常感谢，已经解决了，换成本地文件正常，有可能是nacos上的配置是yaml格式的原因，这边再详细检查下

可以用properties的格式，这样不容易识别出错
