### ISSUE TITLE
seata 1.6.1采用nacos的方式注册，修改namespace之后还是public命名空间

### ISSUE THREAD

**Issue by KouShenhai** [seata/seata#5258]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata 1.6.1采用nacos的方式注册，修改namespace之后还是public命名空间

### Ⅱ. Describe what happened

修改配置文件 application.example.yml 采用nacos的方式注册，修改了nacos的namespace，改完之后，重启seata没有起作用，命名空间还是public
![image](https://user-images.githubusercontent.com/48756217/212894955-1d5c505b-9dc8-4c5e-8ab7-4e7f0469bcf7.png)
![image](https://user-images.githubusercontent.com/48756217/212895080-39d13c4d-ea6d-4719-92a8-d1197f894c25.png)

### Ⅲ. Describe what you expected to happen
修改namespace之后，可以将seata服务注册到指定的命名空间

### Ⅳ. Environment:

- JDK version : jdk8
- Seata version:  1.6.1
- OS :  CentOS 7
- Others: Nacos 2.2.0

**Comment by a364176773** [comment]
application.example.yml 是 example,使用 application.yml

**Comment by KouShenhai** [comment]
> 

非常感谢大佬，问题解决啦
