### ISSUE TITLE
seata 1.6.1 运行初始化nacos配置脚本报错

### ISSUE THREAD

**Issue by KouShenhai** [seata/seata#5259]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata 1.6.1 运行初始化nacos配置脚本报错

### Ⅱ. Describe what happened

执行命令
```shell
sh /seata/script/config-center/nacos/nacos-config.sh -h 127.0.0.1 -p 8848 -g SEATA_GROUP -t 命名空间id
```
初始化报错
![}K F6A74W ZUWJX0C26JM)X](https://user-images.githubusercontent.com/48756217/212927585-b1dc5516-3ebc-4fe7-aa12-ac02de820b6d.png)

### Ⅲ. Describe what you expected to happen
执行完脚本能够不报错，顺利完成nacos配置初始化

### Ⅳ. Environment:

- JDK version : jdk8
- Seata version:  seata1.6.1
- OS : CentOS 7
- Others: Nacos 2.2.0

**Comment by a364176773** [comment]
你可以自己手动复制黏贴,可以提pr修一下脚本,现在的脚本写入是单条写入,现在合并成一个大的dataid直接手动去nacos创建即可

**Comment by KouShenhai** [comment]
> 你可以自己手动复制黏贴，可以提pr修一下脚本，现在的脚本写入是单条写入，现在合并成一个大的dataid直接手动去nacos创建即可

出现这个问题的原因是，没有给默认值，导致无法插入nacos
![image](https://user-images.githubusercontent.com/48756217/213088215-f4a10177-1c36-4176-aec2-3df14f222377.png)
我增加默认值，然后插入成功
![image](https://user-images.githubusercontent.com/48756217/213088421-14446ead-792a-417b-a085-c77fe089708c.png)
![image](https://user-images.githubusercontent.com/48756217/213088872-7673906f-fcba-48c2-b45e-e06b2236be4a.png)

**Comment by a364176773** [comment]
https://github.com/seata/seata/tree/develop/script/config-center
看下readme里怎么说的，不是所有配置都要传到nacos的，也不是所有配置都有默认值的

**Comment by KouShenhai** [comment]
> https://github.com/seata/seata/tree/develop/script/config-center 看下readme里怎么说的，不是所有配置都要传到nacos的，也不是所有配置都有默认值的

这个我知道，我只是把问题分析一下
