### ISSUE TITLE
starting or entering transaction as spring，declaring transaction

### ISSUE THREAD

**Issue by leehom** [seata/seata#527]
tm starts a global transaction from a "business" method that marked "@GlobalTransactional", why not done it like spring，using aop，staring or entering transaction according the transaction context。

**Comment by slievrly** [comment]
@leehom aspect on @Transactional ?

**Comment by IS908** [comment]
@slievrly In my opinion, it is OK! I can rewrite Spring's DataSourceTransactionManager to integrate GlobalTransaction and Spring local transaction. In this way, fescar can support transaction propagation behavior as spring transaction except for propagation-nested!

**Comment by a364176773** [comment]
transaction propagation has been implemented
