### ISSUE TITLE
1.6.1 版本安装

### ISSUE THREAD

**Issue by zhouhui99** [seata/seata#5275]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1.6.1版本安装配置文件使用nacos注册中心，使用外网nacos,启动一直连接的是localhost:8848

### Ⅱ. Describe what happened

 ERROR --- [                          main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS SocketTimeoutException httpGet] currentServerAddr:http://localhost:8848， err : connect timed out
实际在conf/application.yml 中nacos 配置地址是外网nacos地址

**Comment by a364176773** [comment]
Can you add any more information?

**Comment by a364176773** [comment]
There is no such problem, please add detailed description and configuration information, privacy information can be hidden
