### ISSUE TITLE
1.6.1版本，事务无法回滚（求助贴🙇🏻‍♂️）

### ISSUE THREAD

**Issue by lhh18** [seata/seata#5276]
# 这是client端日志，显示回滚成功
![image](https://user-images.githubusercontent.com/74589636/215961346-c35d8a0c-3cfb-4c34-8068-ade9b05ceadb.png)
# 这是server端日志
![image](https://user-images.githubusercontent.com/74589636/215961781-d408decc-f6ba-487d-a2f3-124c10fcadd6.png)
![image](https://user-images.githubusercontent.com/74589636/215961528-e6e35d20-66f0-4021-bef4-09e0138c8ec2.png)

# 事务发起方（第一张截图）create方法正常回滚，但是远程调用无法回滚。菜鸡求助🆘🆘

**Comment by lhh18** [comment]
@a364176773 旺仔老哥，可以帮我看看哪里有问题么😭

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/overview/faq.html 看下第49条

**Comment by lhh18** [comment]
> https://seata.io/zh-cn/docs/overview/faq.html 看下第42条

老哥，我找到问题了。。。是我引入pom的问题。一开始我使用的是`seata-spring-boot-starter`，并没有使用`spring-cloud-starter-alibaba-seata`，然后我想起来之前一个帖子（截图如下），应该是这个XID的传递问题。后面我将pom修改后，事务可正常回滚。麻烦旺仔老哥了🙇🏻‍♂️
另外提一嘴，一开始“第49条”我费老劲儿也没找到，也没问你哪有49条（敢怒不敢言、瑟瑟发抖），哈哈哈哈。然后我检查了第42条中的异常捕获问题和数据源代理问题，头发都要褥掉了也没发现哪里错了，最后才想起来XID这个东西。
![image](https://user-images.githubusercontent.com/74589636/215976932-88993090-5b31-445c-9272-bf866252d246.png)

**Comment by a364176773** [comment]
是的，我一开始打错了发成了49，解决了就好

**Comment by lhh18** [comment]
> 是的，我一开始打错了发成了49，解决了就好

你帮忙解决issues，是不是每个月也都有指标的阿（doge）哈哈哈哈，都是看你在回答

**Comment by a364176773** [comment]
我不是阿里和蚂蚁的，没有任何指标，我是纯开源爱好者
