### ISSUE TITLE
客户端注册成功，但是resourceIds=null

### ISSUE THREAD

**Issue by zhudengsunjie** [seata/seata#5289]
![0df29551335dec50669b315e8efcba9](https://user-images.githubusercontent.com/106943409/216268993-996b751a-8958-4515-9a0f-6e17f1e30395.png)

**Comment by a364176773** [comment]
如果是纯tm应用是正常的，如果是使用at或xa模式的rm应用要检查数据源代理，如果是tcc等一样要检查tcc事务的注解是否生效

**Comment by zhudengsunjie** [comment]
我使用的是at模式，要怎么修改数据源的代理呀

**Comment by a364176773** [comment]
> 我使用的是at模式，要怎么修改数据源的代理呀

手动代理或自动代理
https://seata.io/zh-cn/docs/ops/deploy-guide-beginner.html
