### ISSUE TITLE
startup script should remove the xmn configuration

### ISSUE THREAD

**Issue by a364176773** [seata/seata#5290]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
默认垃圾收集器已经在1.6上改为g1了，g1不推荐设置xmn，其会根据实际的GC情况(主要是暂停时间)来动态的调整新生代的大小
此pr要提交给develop和2.x两个分支
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by mxsm** [comment]
Hi @a364176773  I want to try it. Can you assign it to me?

**Comment by a364176773** [comment]
> Hi @a364176773 I want to try it. Can you assign it to me?

Sure, looking forward to your pr
