### ISSUE TITLE
The datasource proxy's problem

### ISSUE THREAD

**Issue by ZenkieBear** [seata/seata#5291]
- [x]  I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Seata's datasource proxy's sql checker has a problem, it'll replace the character '`'.

### Ⅱ. Describe what happened
There's a field named 'all' in our table. But all is a sql keyword. We use MyBatisPlus, I used put a @TableFiled("`` `all` ``") annotation to avoid the sql syntax error, and it works.
Today, I imorted seata to our project. When I execute the sql include field 'all', a SQLSyntaxErrorException has been threw. It gave a message: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'all,xxx FROM t_access_record ' at line 1`. Seems, seata's datasource proxy replaced the characted '`'.
Normally, mybatis-plus don't replace the character. But it has dirty-reading problem. Seata resolve these distrubut-system's problem, but its datasource proxy is not ideal.

### Ⅲ. Describe what you expected to happen
I want to have an option to decide whether the data source agent should replace some characters.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Create an table, contains a field named 'all'
2. Include MyBatis-Plus, put an anotation '@TableField("`` `all` ``")' to the field
3. Enable GlobalTransaction, and use the field to execute **update** statement.

### Ⅴ. Anything else we need to know?
No.

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.6.1
- OS : Windows
- Others: IDEA 2021.1, SpringBoot 2.3.12.RELEASE

**Comment by a364176773** [comment]
Please provide the original field column names and sql and seata proxy generated sql and log details

**Comment by ZenkieBear** [comment]
> Please provide the original field column names and sql and seata proxy generated sql and log details

Stack information as above

**Comment by a364176773** [comment]
This is a strange problem, PlainExecutor does not modify any sql of the business, have you tried the case of uncommenting globaltransational?

**Comment by ZenkieBear** [comment]
> This is a strange problem, `PlainExecutor` does not modify any sql of the business, have you tried the case of uncommenting `globaltransational`?

I just removed `@GlobalTransactional` annotation, and the programe worked right. There's no any exception been threw.

**Comment by ZenkieBear** [comment]
> This is a strange problem, `PlainExecutor` does not modify any sql of the business, have you tried the case of uncommenting `globaltransational`?

Actually, disable `seata.enable-auto-data-source-proxy` option can also resolve this  exception. Well, does it means Seata's distributed transaction mechanism will fail？

**Comment by ZenkieBear** [comment]
@a364176773 
I've debug and looked the seata's source code up.
In `io.seata.rm.datasource.exec.UpdateExecutor` the method `buildBeforeImageSQL` had been called. At line 93, it means get the columns from `TableData`(get description from db). It is true that the colmun name has not been processed. Then the problem happends, `all` is a sql keyword.
![Get The Columns ](https://user-images.githubusercontent.com/62818957/216525001-0f977f6b-9f9c-4bf9-87a0-9e45f20a49f5.png)

This is the generated sql:
![Generate Result](https://user-images.githubusercontent.com/62818957/216523908-46d4bc7f-106e-4e80-a974-788dc14f87d2.png)
(Ignore the yellow texts. MyBatis-Plus dont add ``` `` ``` character, but it'll check the column by the alias. Seata check from the table fields from **db**)

I thought seata will call the `SelectForUpdateExecutor`'s execute method, but it didn't. That's why *select* statement wont make exceptions.

**Comment by a364176773** [comment]
> > This is a strange problem, `PlainExecutor` does not modify any sql of the business, have you tried the case of uncommenting `globaltransational`?
> 
> Actually, disable `seata.enable-auto-data-source-proxy` option can also resolve this exception. Well, does it means Seata's distributed transaction mechanism will fail？

Yes

**Comment by a364176773** [comment]
> @a364176773 I've debug and looked the seata's source code up. In `io.seata.rm.datasource.exec.UpdateExecutor` the method `buildBeforeImageSQL` had been called. At line 93, it means get the columns from `TableData`(get description from db). It is true that the colmun name has not been processed. Then the problem happends, `all` is a sql keyword. ![Get The Columns ](https://user-images.githubusercontent.com/62818957/216525001-0f977f6b-9f9c-4bf9-87a0-9e45f20a49f5.png)
> 
> This is the generated sql: ![Generate Result](https://user-images.githubusercontent.com/62818957/216523908-46d4bc7f-106e-4e80-a974-788dc14f87d2.png) (Ignore the yellow texts. MyBatis-Plus dont add `` `` `` character, but it'll check the column by the alias. Seata check from the table fields from **db**)
> 
> I thought seata will call the `SelectForUpdateExecutor`'s execute method, but it didn't. That's why _select_ statement wont make exceptions.

So your SQL is 'select for update'? Why don't I see 'SelectForUpdateExecutor' in your stack information?

**Comment by a364176773** [comment]
This is a bug, but the information you provided is not quite accurate

**Comment by a364176773** [comment]
![image](https://user-images.githubusercontent.com/19943636/216576540-6109683d-c4bd-478f-9993-47512b0fdd9d.png)
This code will handle keywords, can you debug this piece of code? `UpdateExecutor#getNeedUpdateColumns`

**Comment by slievrly** [comment]
@ZenkieBear please give me more information about druid dependency.

**Comment by ZenkieBear** [comment]
We're using druid-spring-boot-starter
1.2.11 version











ZENKIE

---Original---
From: ***@***.***&gt;
Date: Mon, Feb 6, 2023 20:08 PM
To: ***@***.***&gt;;
Cc: "Zenkie ***@***.******@***.***&gt;;
Subject: Re: [seata/seata] The datasource proxy's problem (Issue #5291)




 
@ZenkieBear please give me more information about druid dependency.

**Comment by a364176773** [comment]
The problem exists and I will fix it, but the problem with select sql I did not reproduce successfully

**Comment by ZenkieBear** [comment]
The select sql has no problem, it's just a guess. It could have worked right! :)









ZENKIE

---Original---
From: ***@***.***&gt;
Date: Mon, Feb 6, 2023 21:23 PM
To: ***@***.***&gt;;
Cc: "Zenkie ***@***.******@***.***&gt;;
Subject: Re: [seata/seata] The datasource proxy's problem (Issue #5291)




 
The problem exists and I will fix it, but the problem with select sql I did not reproduce successfully

**Comment by ZenkieBear** [comment]
Thank you！











ZENKIE

---Original---
From: ***@***.***&gt;
Date: Mon, Feb 6, 2023 21:23 PM
To: ***@***.***&gt;;
Cc: "Zenkie ***@***.******@***.***&gt;;
Subject: Re: [seata/seata] The datasource proxy's problem (Issue #5291)




 
The problem exists and I will fix it, but the problem with select sql I did not reproduce successfully
