### ISSUE TITLE
Refresh tableMeta when SQL throw a missing field exception

### ISSUE THREAD

**Issue by slievrly** [seata/seata#5292]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
Refresh tableMeta when SQL throw a missing field exception

When SQL reports a missing field, refresh TableMeta information immediately. When the table structure information is changed during running, such as adding column A, Seata will throw an Exception when executing SQL for a period of time, resulting in unavailable services for a period of time. This is because tableMeta cache information is cached in memory periodically. When this exception occurs, tabelMeta information should be refreshed immediately.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by robynron** [comment]
pls assign this to me😊

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4734
