### ISSUE TITLE
事务回滚重试超时后，DB会话存储的模式下会将全局事务删除掉，接下来还有修改事务状态的逻辑

### ISSUE THREAD

**Issue by ZhangShiYeChina** [seata/seata#5295]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

版本：1.6.1 
`DefaultCoordinator#handleRetryRollbacking`方法中，当遇到事务回滚重试 发生了超时，会包含以下逻辑：
1. DB模式下，会从global_table中删除此事务记录（`removeGlobalSession(...)`方法中会删除）
2. 将此事务状态变更为 `RollbackRetryTimeout`
疑问DB层面已删除，此处修改状态什么作用？

在 `DefaultCoordinator#handleRetryCommitting`也存在同样的情况。

### Ⅱ. Describe what happened
如下图所示
![image](https://user-images.githubusercontent.com/42596680/216557504-6764b6d4-70e5-4b28-8fb8-4ad2c63870f3.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

针对这个疑问跟社区的 [【a364176773】](https://github.com/a364176773) 进行探讨，初步结论是 可按照Seata后续的能力规划对此处进行修改：

*  如此上下文中重试回滚超时异常类的事务，不再由每秒执行一次的定时任务来自动删除
*  把这类异常事务记录保留下来，之后在控制台侧增加功能来管控这类异常事务。

那么当下对应的修改可为：

* 将上边的`removeGlobalSession`逻辑删除掉。

### Ⅵ. Environment:

- JDK version : 8
- Seata version:  1.6.1
- OS :
- Others:

**Comment by a364176773** [comment]
This should be a bug, this line of code should be removed
