### ISSUE TITLE
[Test] add  test for common module

### ISSUE THREAD

**Issue by slievrly** [seata/seata#5305]
## Why you need it?

Increase the unit test coverage target to 70% + 

https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/io/FileLoader.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/holder/ObjectHolder.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/loader/ExtensionDefinition.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/util/StringUtils.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/util/SizeUtil.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/util/ReflectionUtil.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/util/MapUtil.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/util/LowerCaseLinkHashMap.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/util/ConfigTools.java
https://app.codecov.io/gh/seata/seata/blob/2.x/common/src/main/java/io/seata/common/util/ArrayUtils.java

contributors claiming this task are requested to submit at least 3 test classes to a pr
请认领此任务的贡献者至少保证每个pr包含3个测试类达到要求。

contributors who plan to claim please comment the test class in issue
计划认领测试任务的贡献者请回复要测试的类。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by liuqiufeng** [comment]
io.seata.common.io.FileLoader
io.seata.common.holder.ObjectHolder
io.seata.common.util.StringUtils

**Comment by liuqiufeng** [comment]
io.seata.common.util.ArrayUtils
io.seata.common.util.ConfigTools
io.seata.common.util.MapUtil
