### ISSUE TITLE
jwt log error

### ISSUE THREAD

**Issue by jumtp** [seata/seata#5324]
### Ⅰ. Issue Description
When refreshing the page, a background log print jwt error occurs

### Ⅱ. Describe what happened

![20230209161906](https://user-images.githubusercontent.com/49558643/217756001-f7d46280-ab4e-43b0-b08c-707748d0d06a.png)

### Ⅲ. Describe what you expected to happen
no longer print jwt log errors
不再打印jwt日志错误

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1.Just [download](https://github.com/seata/seata/releases/download/v1.6.1/seata-server-1.6.1.zip) it and start it. Refresh the page on port 7091 and there will be some JWT errors
   只需要[下载](https://github.com/seata/seata/releases/download/v1.6.1/seata-server-1.6.1.zip)下来,然后启动.刷新7091端口的页面就会出些JWT错误

### Ⅵ. Environment:

- JDK version : 17
- Seata version:  1.6.1
- OS : win10
- Others: nothing

**Comment by liuqiufeng** [comment]
Please assign to me

**Comment by a364176773** [comment]
We tried to reproduce this problem, and accidentally found that there is indeed this problem, but the probability is very low and very difficult to reproduce, we will try to solve it by upgrading the sb version, if you know how to reproduce the problem please let us know

**Comment by jumtp** [comment]
> We tried to reproduce this problem, and accidentally found that there is indeed this problem, but the probability is very low and very difficult to reproduce, we will try to solve it by upgrading the sb version, if you know how to reproduce the problem please let us know

Do I need to be assigned for submitting a PR? I want to try it out.

**Comment by slievrly** [comment]
@jumtp Could you please help confirm that the code in PR solves this issue?

**Comment by jumtp** [comment]
> @jumtp Could you please help confirm that the code in PR solves this issue?

There is no need to do this. It is not SpringBoot fault, nor Security. Please leave it to me

没必要这样干..不是SpringBoot的错,也不是Security.请交给我来处理吧

**Comment by liuqiufeng** [comment]
> > @jumtp Could you please help confirm that the code in PR solves this issue?
> 
> There is no need to do this. It is not SpringBoot fault, nor Security. Please leave it to me
> 
> 没必要这样干..不是SpringBoot的错,也不是Security.请交给我来处理吧

可以的，你提个pr吧。
