### ISSUE TITLE
TCC commit和rollback方法去除FastJson依赖

### ISSUE THREAD

**Issue by GuoHaoZai** [seata/seata#5334]
## Why you need it?

TCC commit和rollback方法如果有BusinessActionContext类型的入参，要想使用BusinessActionContext中的actionContext变量，则必须使用FastJson的JsonObject。我们项目中并不想依赖FastJson。

## case

<img width="860" alt="image" src="https://user-images.githubusercontent.com/44019619/218248272-5ff168cb-91a1-4eb8-98a2-29e7999d3f3e.png">

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/5017
