### ISSUE TITLE
seata如何进行多环境配置，比如dev，test环境隔离

### ISSUE THREAD

**Issue by lints123** [seata/seata#5340]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by a364176773** [comment]
seata-server本身的配置来说 application.yml可以通过不同的spring.profiles.active来指定不同的yml去加载配置
服务发现注册上可以通过nacos进行通过namespace，group之类的配置划分
数据库上可以通过不同的数据库表名，库名去区分，但是要记住如果你是存算分离形式，且你的业务库在不同环境下用同一个，那么seata-server的lock表要用同一个，否则数据之间没有互斥会出现脏写（如果你不用at没这个问题），这里可以用同个库，同个lock表名，不同环境只需要改不同的global branch的表名分离即可

**Comment by lints123** [comment]
是否要启动多个seata进程呢？每一个进程对应每一个环境，还是说可以通过namespace，group来区分就可以？
