### ISSUE TITLE
配置context-path参数后，web页面无法访问接口

### ISSUE THREAD

**Issue by guanpeijia** [seata/seata#5346]
### Ⅰ. Issue Description

seata配置文件设置context-path参数后，web页面浏览路径增加context-path设置的参数，页面可以正常显示，但是页面查询接口404

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 修改seata/conf/application.yml文件，增加context-path配置
`server:
  port: 7091
  **servlet:
    context-path: /seata**

spring:
  application:
    name: seata-server`
2. 访问web页面

- JDK version :1.8
- Seata version:  1.6.1

**Comment by a364176773** [comment]
通过控制台查看请求的接口截图发出来看看，估计是因为加了context-path后接口的地址url不对了

**Comment by guanpeijia** [comment]
> 通过控制台查看请求的接口截图发出来看看，估计是因为加了context-path后接口的地址url不对了

前端请求的接口没有获取contextPath。截图如下
![image](https://user-images.githubusercontent.com/31607259/219293802-8aa21616-27c8-40c8-bd6a-4ea2600ef792.png)
![image](https://user-images.githubusercontent.com/31607259/219294076-d674b952-1b34-4a24-9295-d42f8e94cee5.png)

**Comment by guanpeijia** [comment]
> 通过控制台查看请求的接口截图发出来看看，估计是因为加了context-path后接口的地址url不对了

前端请求的接口，没有获取contextPath，截图如下
![image](https://user-images.githubusercontent.com/31607259/219294487-890f7bd1-083b-41fb-9246-c27d7f67a1f8.png)
![image](https://user-images.githubusercontent.com/31607259/219294671-b60818e3-3df6-40b2-ac3f-e60c98f80c72.png)

**Comment by liuqiufeng** [comment]
可以自行修改https://github.com/seata/seata/blob/2.x/console/src/main/resources/static/console-fe/src/utils/request.ts中的`baseURL: '/api/v1'`为`baseURL: '/seata/api/v1'`再重新对前端打包（console-fe目录下）

**Comment by guanpeijia** [comment]
> 可以自行修改https://github.com/seata/seata/blob/2.x/console/src/main/resources/static/console-fe/src/utils/request.ts 中的`baseURL: '/api/v1'`为`baseURL: '/seata/api/v1'`再重新对前端打包（console-fe目录下）

在未来的版本中会自动识别contextPath吗？
