### ISSUE TITLE
 seata 支持高斯数据库吗?

### ISSUE THREAD

**Issue by fengzikai111** [seata/seata#5348]
hi,
 seata 支持高斯数据库吗?

**Comment by HEIBAIJIE** [comment]
根据我的测试是支持高斯100的，开源版本不太清楚
客户端直接引用pom依赖就可以，服务端要在/lib目录下引入驱动

**Comment by a364176773** [comment]
高斯的driver在中央仓库有吗？如果没有的情况下，他对mysql/oracle是兼容的那就直接用mysql的driver即可
