### ISSUE TITLE
can not get cluster name in registry config 'service.vgroupMapping.default_tx_group'

### ISSUE THREAD

**Issue by S540J521** [seata/seata#5349]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
nacos：1.4.2
seata：1.6.1

### Ⅱ. Describe what happened
nacos中创建seataServer.properties里面有 service.vgroupMapping.default_tx_group=default
![image](https://user-images.githubusercontent.com/124575445/219325701-d3bee621-2bb2-4ed7-bdf6-65655e50fa71.png)
![image](https://user-images.githubusercontent.com/124575445/219327242-249d00d1-905d-4033-9f92-ecc2d4068db3.png)

seata-server/conf/application.yml配置如下
![image](https://user-images.githubusercontent.com/124575445/219325989-2640275a-b6c5-4899-a826-66a7dd930aac.png)

每个微服务yml配置文件如下
![image](https://user-images.githubusercontent.com/124575445/219326330-a3c53c2e-483b-4520-a4c5-91592ae47140.png)

项目启动就报错了
![image](https://user-images.githubusercontent.com/124575445/219326885-9bd21253-79d1-4db3-a695-b9b5d072af27.png)

**Comment by a364176773** [comment]
service.vgroupMapping.default_tx_group 要配置在client，而不是server，其次读取yml是seata-spring-boot-starter才有的功能，seata-all读取不了application.yml

**Comment by S540J521** [comment]
client是指project吧，我在每个微服务里都加了呀
![image](https://user-images.githubusercontent.com/124575445/219528139-6e0cf5aa-396a-4de8-a451-85d7982f9c50.png)
server是指注册到nacos中的吧，seataServe.properties中也加了，即便不加也是默认就有的
![image](https://user-images.githubusercontent.com/124575445/219528470-322dc32d-35b9-4f62-9a62-1b9fe7004cbb.png)
两外，每个服务我都有引入seata-spring-boot-starter

**Comment by a364176773** [comment]
那你client使用的配置中心是什么？

**Comment by S540J521** [comment]
> 那你client使用的配置中心是什么？
nacos，已经解决了，在client的yml中配置seata.nacos.config.data-id=seataServer.properties就可以了
