### ISSUE TITLE
MySQLUndoUpdateExecutor only needs to  rollback changed field

### ISSUE THREAD

**Issue by beston123** [seata/seata#5353]
## Why you need it?
MySQLUndoUpdateExecutor only needs to  rollback changed field, this prevents the data fields from being overwritten.

## How it could be?
MySQLUndoUpdateExecutor compares the beforeImage and afterImage to get the difference fields, then generate the unlog sql.

**Comment by a364176773** [comment]
That's the way it is now.

**Comment by beston123** [comment]
我之前19年提的一个issue，当时考虑到更新列是function（如自动更新列时间戳）的情况，不能从update sql推理到更新前的数据字段，需要保留atferImage 通过对比来获取实际更新的数据字段。
刚看了源码，onlyCareUpdateColumns配置默认开启，即beforeImage只保存sql中SET的列。
考虑到上面说的问题， 如果onlyCareUpdateColumns关闭的情况下，还是需要比较前后快照比较好，而不是全部字段更新
#1864

**Comment by a364176773** [comment]
onlyCareUpdateColumns 关闭下代表你要求真正意义的强一致，比如一个人只改了姓名为张三变成李四，另一个地方绕过全局锁把张三的出生年月日改了，你觉得算不算脏写呢？是不是需要全部比对呢？

**Comment by beston123** [comment]
> onlyCareUpdateColumns

这个例子不恰当，不需要全局锁控制的业务更新，两个字段应该是不相关的，可以独自更新，比如以身份证id为主键的数据，姓名和当前工作两个字段没有直接关联，改名和换工作不冲突。
onlyCareUpdateColumns = false 如果表示同一pk的数据变更必须经过seata的全局锁，那没问题；
如果不是，onlyCareUpdateColumns 配置关闭时，需要考虑怎么构造unlog防止数据覆盖了

**Comment by a364176773** [comment]
> > onlyCareUpdateColumns
> 
> 这个例子不恰当，不需要全局锁控制的业务更新，两个字段应该是不相关的，可以独自更新，比如以身份证id为主键的数据，姓名和当前工作两个字段没有直接关联，改名和换工作不冲突。 onlyCareUpdateColumns = false 如果表示同一pk的数据变更必须经过seata的全局锁，那没问题； 如果不是，onlyCareUpdateColumns 配置关闭时，需要考虑怎么构造unlog防止数据覆盖了

那你有没有想过mysql为什么只做行锁而不做字段锁吗?其次onlyCareUpdateColumns = false就是表示同一pk的数据变更必须经过seata的全局锁,因为不只是关心被修改的字段
