### ISSUE TITLE
seata1.4.2配置enabled:false启动报错

### ISSUE THREAD

**Issue by zhangbohua** [seata/seata#5369]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
![image](https://user-images.githubusercontent.com/37918621/220239471-a9942dcc-c001-414a-9df3-00020f19a8a9.png)

```
seata1.4.2版本配置seata.enabled:false导致启动报错；
```

### Ⅲ. Describe what you expected to happen
启动报错，找不到其他配置类：```Parameter 0 of method seataAutoDataSourceProxyCreator in io.seata.spring.boot.autoconfigure.SeataDataSourceAutoConfiguration required a bean of type 'io.seata.spring.boot.autoconfigure.properties.SeataProperties' that could not be found```；

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. SeataDataSourceAutoConfiguration自动配置类上```@ConditionalOnExpression("${seata.enable:true} && ${seata.enableAutoDataSourceProxy:true} && ${seata.enable-auto-data-source-proxy:true}")```表达式改为```@ConditionalOnExpression("${seata.enabled:true} && ${seata.enableAutoDataSourceProxy:true} && ${seata.enable-auto-data-source-proxy:true}")```

### Ⅴ. Anything else we need to know?
No

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.4.2
- OS : Windows10
- Others:

**Comment by wangliang181230** [comment]
很久以前就修复了：https://github.com/seata/seata/pull/3588
