### ISSUE TITLE
seata server1.4.0不能按照db模式启动

### ISSUE THREAD

**Issue by 852675742** [seata/seata#5394]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

seata server1.4.0不能按照db模式启动，启动日志也没有初始化数据源的日志

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :  1.8
- Seata version:  1.4.0
- OS : Windows
- Others:

**Comment by slievrly** [comment]
need to provide more information such as error stacks or logs.
