### ISSUE TITLE
store.mode=db不生效，依然使用file存储事务信息

### ISSUE THREAD

**Issue by wenbin-usr** [seata/seata#5398]
seata1.6.0，conf/application.yml中配置了store.mode=db，发现事务信息还是存储到文件中
![QQ截图20230301005934](https://user-images.githubusercontent.com/83151102/221924202-7163470b-aa59-4c9c-a2a1-8294aa730744.png)
nacos配置中心也加了store.mode=db配置，也不生效
![QQ截图20230301010209](https://user-images.githubusercontent.com/83151102/221924649-b2ee00b9-2f7d-4f4f-9936-d9f1e488cdc8.png)

**Comment by slievrly** [comment]
the above information does not prove that you use nacos.

**Comment by wenbin-usr** [comment]
使用nacos作为注册中心，seata-server已经注册到nacos上了，事务失败能够回滚，debug发现使用file存储事务信息。除了配置store.mode=db之外，还需要添加其他配置吗？

**Comment by chinaboy007** [comment]
我也遇到这个问题了

**Comment by xiaoyuwang1987** [comment]
我之前也碰到一次，后面重启就好了 你是不是用docker部署的，感觉是docker环境问题造成的

**Comment by timshinlee** [comment]
是不是config是配置在nacos的呢，会从nacos读取配置，不从本地配置文件读取了
