### ISSUE TITLE
AT模式部分节点二阶段异步提交不执行

### ISSUE THREAD

**Issue by javahaohao** [seata/seata#5417]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata-server有五个节点，执行一段时间之后，部分节点二阶段异步提交停止执行
通过搜索“Committing global”相关日志，无搜索结果，判定该节点异步提交停止执行
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
请教下是什么原因会导致类似问题的发生？

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :1.8
- Seata version:  1.3.0
- OS :
- Others:

**Comment by slievrly** [comment]
Asynchronous tasks can only be executed by one node at the same time, and the execution node is determined by distributed lock.

**Comment by javahaohao** [comment]
> 

Our seata-server version number is 1.3.0, which does not use distributed locks @slievrly

**Comment by javahaohao** [comment]
I understand that in AT mode, asynchronous commit in two phases, multiple node services will cause data competition problems, and in a scenario with a large amount of concurrency, will cause nodes to interrupt each other's asynchronous commit global transactions, resulting in performance loss in two phases
