### ISSUE TITLE
1.6.1版，global_table表status=9的记录，发生系统不自动删除的问题

### ISSUE THREAD

**Issue by lbj812** [seata/seata#5418]
![image](https://user-images.githubusercontent.com/30791781/223593871-7cbaae60-9716-45c5-814a-efaa1217ef13.png)

**Comment by slievrly** [comment]
The globalSession deletion failed due to the database deadlock exception triggered when the lock was released.

**Comment by lbj812** [comment]
原因我已经知道了，我想知道如何解决这个问题

**Comment by slievrly** [comment]
Wait for the next version to fix it.

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/233572737-07942c6f-558c-4930-a16c-39a7b9e37091.png)
