### ISSUE TITLE
multi-table joins for update

### ISSUE THREAD

**Issue by gumandy** [seata/seata#542]
## Why you need it?
too many scenarios requiring multi-table joins

**Comment by slievrly** [comment]
Currently does not support more complex sql

**Comment by phongnho1991** [comment]
Tot

**Comment by maverickswin** [comment]
Hi @slievrly 

I am facing the same issue.
If I removed the **"for update"** statement, seata will use PlainExecutor instead of SelectForUpdateExecutor.
Whether we can use the PlainExecutor as well for **select ... from ... join .... for update** statement?
Does it have any protential issue?

**Comment by slievrly** [comment]
> Hi @slievrly
> 
> I am facing the same issue.
> If I removed the **"for update"** statement, seata will use PlainExecutor instead of SelectForUpdateExecutor.
> Whether we can use the PlainExecutor as well for **select ... from ... join .... for update** statement?
> Does it have any protential issue?

select ... from ... join .... for update ,currently not support
