### ISSUE TITLE
seata启动不了

### ISSUE THREAD

**Issue by Lnsynd** [seata/seata#5425]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
启动不报错，没反应
我是windows11 系统
![image](https://user-images.githubusercontent.com/37909383/224328063-2e800001-2a4f-4021-870f-fecc3954add2.png)
![image](https://user-images.githubusercontent.com/37909383/224328570-a75ebcb7-3d9b-46ee-a0a3-1628c7f8c4cb.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 8
- Seata version:  1.4.2
- OS :Windwos11
- Others:

**Comment by Lnsynd** [comment]
![image](https://user-images.githubusercontent.com/37909383/224470256-1fbe4d19-c218-4125-b36f-60e0b2571aee.png)
这是启动了seata-server.sh的报错信息
seata-server.bat打不开

**Comment by a364176773** [comment]
尝试调整xmx xms
