### ISSUE TITLE
saga模式需要业务方自己处理 幂等、空回滚、资源悬挂问题吗？

### ISSUE THREAD

**Issue by liyy653787585** [seata/seata#5433]
你好，在saga模式的官方文档中，为saga服务的设计提供了最佳实践，如下图：
![最佳实践](https://user-images.githubusercontent.com/36065022/224598071-13d4924a-1c5d-4266-8e36-487e20225a7e.jpg)

那是不是意味着saga模式本身是没有处理 幂等、空回滚、资源悬挂这些问题？而是需要业务方自己来处理？

**Comment by wt-better** [comment]
目前是的。

**Comment by liyy653787585** [comment]
> 目前是需要业务方自己处理 幂等、空回滚、资源悬挂的。

好的，谢谢
