### ISSUE TITLE
What does fescar mean?

### ISSUE THREAD

**Issue by wwftw** [seata/seata#544]
This is a general question out of curiosity

**Comment by skyesx** [comment]
Fescar: Fast & Easy Commit And Rollback

**Comment by wwftw** [comment]
It's FECAR

**Comment by RunningSanil** [comment]
I guess it's Fast & Easy Support Commit And Rollback

**Comment by slievrly** [comment]
> I guess it's Fast & Easy Support Commit And Rollback

yes

**Comment by wwftw** [comment]
Now it got renamed to SEATA, and I believe it stands for "Simple Extensible Autonomous Transaction Architecture
", which is a bit vague I think, why would a solution/framework be named "architecture". In addition, I think using acronyms to name things isn't ideal, you open yourself to various wild guesses from people.

**Comment by drinkjava2** [comment]
when google seata, got SOUTHEAST ATHLETIC TRAINERS' ASSOCIATION, suggest change back to fescar.

**Comment by leizhiyuan** [comment]
because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
