### ISSUE TITLE
v1.6.1分布式事务xid无法通过feign传递

### ISSUE THREAD

**Issue by Mycheers** [seata/seata#5446]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description、
集成了spring-cloud-starter-alibaba-seata  2022.0.0.0-RC1 包
启动成功，注册成功
发起调用服务有xid生成，调用feign直接进入到feign默认  Client 无法进入SeataFeignClient.execute
导致xid无法传递到下一个服务中  如果单独配置feign拦截器执行把xid塞进请求头可以正常执行回滚

切换seataV1.5.2版本后不需要任何额外配置可以实现事务回滚

### Ⅵ. Environment:

seataV1.6.1
springCloud Hoxton.SR9
nacos 1.2.1
springboot 2.3.4.RELEASE
pgsql 14
jdk 1.8

**Comment by slievrly** [comment]
please use https://github.com/alibaba/spring-cloud-alibaba/releases/tag/2.2.10-RC1

**Comment by vanniuner** [comment]
com.alibaba.cloud:spring-cloud-starter-alibaba-seata:jar:2021.0.5.0:compile
也不支持使用openFegion进行服务间的 xid 传递。还是需要升级到2022.x?

**Comment by a364176773** [comment]
该问题请反馈至spring-cloud-alibaba社区

**Comment by vanniuner** [comment]
算了，自己弄了filter实现就行了，不知道怎那么复杂干啥。。。
