### ISSUE TITLE
java.io.IOException: The remote host forcibly closed an existing connection

### ISSUE THREAD

**Issue by 15168326318** [seata/seata#545]
我启动服务，tc,rm都经常报这个错是什么原因啊？
java.io.IOException: 远程主机强迫关闭了一个现有的连接。

**Comment by 15168326318** [comment]
对不起，我看不太懂英文呀，别强制翻译了吧。

**Comment by Jnoson** [comment]
also ,i find,the connetion of application  have been worked out, throw Timeout waiting for idle object

**Comment by shengqiang025210** [comment]
"com.alibaba.fescar.core.rpc.netty.AbstractRpcRemoting.exceptionCaught:408 -0318
java.io.IOException:The remote host forcibly closed an existing connection"
Has the problem been solved？

**Comment by 15168326318** [comment]
@shengqiang025210  no

**Comment by slievrly** [comment]
@15168326318 Is the latest version？

**Comment by 15168326318** [comment]
@slievrly  我是develop版本自己编译的。
现在回滚一次正常，第二次就报错：can not register RM,err:Timeout waiting for idle object

**Comment by Insightskr** [comment]
me too，I run a fescar-server in Cloud Server，when i run two application，the exception will happen
`2019-04-06 17:07:41.863  INFO 3040 --- [imeoutChecker_1] c.a.f.c.rpc.netty.NettyPoolableFactory   : NettyPool create channel to {"address":"104.248.187.92:8091","message":{"applicationId":"account-gts-fescar-example","byteBuffer":{"char":"\u0000","direct":false,"double":0.0,"float":0.0,"int":0,"long":0,"readOnly":false,"short":0},"transactionServiceGroup":"my_test_tx_group","typeCode":103,"version":"0.4.1"},"transactionRole":"RMROLE"}
2019-04-06 17:07:42.210 ERROR 3040 --- [lector_RMROLE_1] c.a.fescar.core.rpc.netty.RmRpcClient    : 0318`

**Comment by slievrly** [comment]
@Insightskr both two application configured as `"applicationId":"account-gts-fescar-example"`?
