### ISSUE TITLE
get table meta failed, please check whether the table xxx exists

### ISSUE THREAD

**Issue by chenglutao** [seata/seata#5451]
spring-cloud-alibaba.version:2.2.10-RC1
spring-cloud.version:Hoxton.SR12
spring-boot.version:2.3.12.RELEASE
dynamic.datasource.version:3.6.1
mybatis-plus.version:3.5.3
dubbo.version:3.1.7
seata.version:1.6.1
db:postgresql
jdk:1.8

使用注解@GlobalTransactional 就会抛异常，无法插入数据
若使用@Transactional 则不会抛异常，正常插入数据
对于使用mybatis-plus 动态数据源，=配置GlobalTransactionScanner 后还是会抛下述异常
@Bean
public GlobalTransactionScanner globalTransactionScanner() {
        logger.info("配置seata........");
        return new GlobalTransactionScanner("系统配置值", "系统配置值");
}

yml config:
![image](https://user-images.githubusercontent.com/51188496/225660509-97ddc88e-b6ab-4d29-8f8a-d55e75dc65cd.png)
![image](https://user-images.githubusercontent.com/51188496/225660788-6ebe97e7-b847-4a8b-babd-568381de001e.png)

error log:
![image](https://user-images.githubusercontent.com/51188496/225658919-acc0ff76-cadf-4ff8-988d-e72e73e75e8a.png)
![image](https://user-images.githubusercontent.com/51188496/225661716-3318ce5b-63a9-43fe-9954-acdbce7c73f8.png)
![image](https://user-images.githubusercontent.com/51188496/225661867-72696912-129b-4843-af40-696fd9119358.png)
![image](https://user-images.githubusercontent.com/51188496/225667770-f6bac288-1a45-4fab-97f5-d88d47cb6718.png)
![image](https://user-images.githubusercontent.com/51188496/225667880-946ebb50-494d-4e3a-8b4c-4a36a03a3d18.png)

**Comment by slievrly** [comment]
Try using the following versions of org.postgresql: postgresql dependencie.
```
          <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>
```

**Comment by chenglutao** [comment]
> 尝试使用以下版本的 org.postgresql：postgresql dependencie。
> 
> ```
>           <dependency>
>                 <groupId>org.postgresql</groupId>
>                 <artifactId>postgresql</artifactId>
>                 <version>${postgresql.version}</version>
>             </dependency>
> ```
这是我引入的依赖，还是会报错
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.6.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba</groupId>
                    <artifactId>druid</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runntime</scope>
        </dependency>

**Comment by slievrly** [comment]
@chenglutao 42.3.3

**Comment by slievrly** [comment]
try execute `select current_schema()`

**Comment by wt-better** [comment]
> > 尝试执行`select current_schema()`
> 
> 使用42.3.3依旧报错 select current_schema()为public

what is the version of druid jar

**Comment by chenglutao** [comment]
> > > 尝试执行`select current_schema()`
> > 
> > 
> > 使用42.3.3依旧报错 select current_schema()为public
> 
> what is the version of druid jar

<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.10</version>
        </dependency>

**Comment by slievrly** [comment]
@chenglutao https://stackoverflow.com/questions/26274312/getschema-in-postgresql-jdbc-driver-throws-java-lang-abstractmethoderror-or-java

**Comment by wt-better** [comment]
> @chenglutao https://stackoverflow.com/questions/26274312/getschema-in-postgresql-jdbc-driver-throws-java-lang-abstractmethoderror-or-java

This version druid  `DruidPooledConnection` dont support`getSchema` . Cause io.seata.rm.datasource.sql.struct.TableMetaCache#getTableMeta  fail.

Can upgrade druid version to support getSchema

**Comment by chenglutao** [comment]
> 

您的建议是有效的

```
<dependency>
	<groupId>com.alibaba</groupId>
	<artifactId>druid-spring-boot-starter</artifactId>
	<version>1.2.16</version>
</dependency>
```

但又有新的异常，从issues上找到了相同的问题  ：
1.6.1，pgsql自增主键、当insert语句不包含主键列时，报[ShouldNeverHappenException: pkIndex is not found] 
https://github.com/seata/seata/issues/5264

**Comment by craftsman4j** [comment]
我的是因为参与全局事务的表没有主键，建立主键后解决

**Comment by chenglutao** [comment]
> 我的是因为参与全局事务的表没有主键，建立主键后解决

新版本已解决该问题
