### ISSUE TITLE
MybatisPlus+dynamic-datasource只做了一次查询直接就将此次事务给回滚了（偶发性事件）过了两天又出现一次

### ISSUE THREAD

**Issue by lxgwzx** [seata/seata#5458]
![image](https://user-images.githubusercontent.com/102020403/226517763-36ad6729-a1c3-4512-9bd3-a928f72bfa4f.png)
![image](https://user-images.githubusercontent.com/102020403/226517955-137efc64-a5e2-4071-bed1-07c6b9a8b072.png)

**Comment by slievrly** [comment]
Are there any error outputs?

**Comment by lxgwzx** [comment]
No error output 您好 ，我将日志重新截取了一下，您可以看看
![image](https://user-images.githubusercontent.com/102020403/227091764-bbd4ae29-ba3f-4756-965f-f833648b516a.png)
![image](https://user-images.githubusercontent.com/102020403/227092599-3be7ea98-f18a-494c-b19e-70e694234a0f.png)

**Comment by lxgwzx** [comment]
现在这个问题每次都会出现

**Comment by a364176773** [comment]
> 现在这个问题每次都会出现

你发的截图压根不是一个xid, 而且rollback完全没看到timeout相关的日志,按你的截图只能是你的tm自己发起的事务回滚,自行debug看下.如果能找到这个事务在60s内出现了timeout,大概是server所使用的数据库时钟与server机器的时钟时区不一致,导致提前回滚了事务.

**Comment by lxgwzx** [comment]
好的，谢谢，已经解决，同事编写代码时传递的参数为空，导致rocketmq进程退出，最初时没有想到，看了rocketmq日志才发现
