### ISSUE TITLE
Seata support other primary key

### ISSUE THREAD

**Issue by 3EDCKenneth** [seata/seata#546]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
整合tk.mybatis, 当id主键为null，自增时， 插入数据， 抛出java.io.NotSerializableException：com.alibaba.fescar.rm.datasource.struct.Null,
查看数据库发现该条数据已经插入，异常没有回滚数据， 

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : centos 7.2
- Others: fescar 0.2.1+springboot2.0.3 tk.mybatis2.1.5

**Comment by xingfudeshi** [comment]
Could you provide a example which can reproduce this problem?

**Comment by 3EDCKenneth** [comment]
@xingfudeshi 内网环境， id为varchar类型，通过@GeneratedValue(UUID)  ， 表结构允许id为null，通过fescar 插入的数据，在发生异常回滚后我，数据未回滚

**Comment by xingfudeshi** [comment]
@3EDCKenneth Thanks for the feedback.Fecar supports Auto-increment primary key only so far.

**Comment by 3EDCKenneth** [comment]
@xingfudeshi 那个版本才能支持其他类型主键，

**Comment by jsbxyyx** [comment]
@3EDCKenneth can you provide table struct？

**Comment by slievrly** [comment]
already support.
