### ISSUE TITLE
咨询事务分组问题?

### ISSUE THREAD

**Issue by ttxs0109** [seata/seata#5469]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata: 1.6.1
使用nacos作为配置和注册中心
客户端启动一直报错： can not get cluster name in registry config 'service.vgroupMapping.default-tx-group', please make sure registry config correct. TM和RM注册不上.
![image](https://user-images.githubusercontent.com/12425007/228107952-22d1a088-0d2c-4e53-bf02-883f2b885c4a.png)

然后nacos单独配置一条: Data ID: service.vgroupMapping.default-tx-group default 就成功了
![image](https://user-images.githubusercontent.com/12425007/228108016-31c9eee4-0672-4056-b1ca-f9fa99559a87.png)
![image](https://user-images.githubusercontent.com/12425007/228108092-0ced0634-492f-4173-a4b7-95d43f0ac71e.png)

是我使用seata不对，还是需要单独配置事务分组？

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- Seata version:  1.6.1
- OS :
- Others:

**Comment by slievrly** [comment]
https://seata.io/zh-cn/docs/user/txgroup/transaction-group.html
