### ISSUE TITLE
seata 1.5.2 全局事务。无法回滚

### ISSUE THREAD

**Issue by xt19960729** [seata/seata#5470]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:
 clould 版本： 2021.0.4 
- JDK version :1.8
- Seata version:  1.5.2
- OS :
- Others:

A服务不管是单表操作，还是跨服务事务。使用GlobalTransactional 都不会进行回滚。
![0KNBSM{J_2$FL 9TOR)E5DW](https://user-images.githubusercontent.com/51768240/228153214-612dd725-1d15-49ba-8e63-3556a88daa0d.png)
以下是A服务配置：

![U 41AYLDIS1Q)LPO3HJ{NAT](https://user-images.githubusercontent.com/51768240/228153412-6f862bf7-4f23-4dc1-83a1-e57863090753.png)

**Comment by xt19960729** [comment]
当然。我使用 Transactional 注解。他是可以得。  但是GlobalTransactional不行。。然后。我在使用GlobalTransactional 得时候。A（GlobalTransactional ）调用B（Transactional ）。。A执行成功了。没有发生回滚操作。B服务成功回滚了。

以下B服务代码。配置跟A一样。
![GX{H_S$PGL_2)S}T1% J )2](https://user-images.githubusercontent.com/51768240/228154169-2ee60397-0c09-4350-917a-a5d3a009a608.png)

**Comment by xt19960729** [comment]
我看到我得seata 控制台。
![C5Z_J ~RBPQGPS56VPB_{E6](https://user-images.githubusercontent.com/51768240/228154428-8ed03e27-5062-4008-b87a-ac068d6d31c5.png)
他一直显示这个。。想问一下问题出在哪里。

**Comment by slievrly** [comment]
How to verify that a transaction is not rollback, is it through business data? The console will delay deleting the data of rollbacked transactions.

**Comment by xt19960729** [comment]
> 

我看到了。操作台显示 成功操作。。然后查看数据库。发现并没有回滚。 不管延迟多久。我等很久。他也还在。
