### ISSUE TITLE
Static resource 401

### ISSUE THREAD

**Issue by cetuer** [seata/seata#5473]
### Ⅰ. Issue Description
Static resource error. code 401

### Ⅱ. Describe what happened
I deploy seata-server in docker. 
After the deployment is complete, an error message is displayed during login, The stack information is as follows:
```
15:17:00.302 ERROR --- [     http-nio-7091-exec-7] i.s.c.s.JwtAuthenticationEntryPoint      : Responding with unauthorized error. Message - Full authentication is required to access this resource
```
Back to the page console found static resource error 401. A quick look at what looks like a static resource error in the header tag. Hopefully it can be fixed, although it won't affect function. （强迫症患者）
screenshot:
![image](https://user-images.githubusercontent.com/45710021/228591615-219dc791-aa63-40a9-8383-2492a9410925.png)
![image](https://user-images.githubusercontent.com/45710021/228591777-2c6427ed-0f6c-4173-8509-388d81290ce7.png)

### Ⅲ. Describe what you expected to happen
No error message is reported in the log. The front end did not report error 401.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. The seata login page is displayed
2. Enter the user name and password and click the login button
3. View logs

### Ⅵ. Environment:

- JDK version : 1.8.0_342
- Seata version:  1.6.1
- OS : CentOS Linux release 7.9.2009 (Core)
- Others:

**Comment by osheeps** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/5347
