### ISSUE TITLE
saga sql script not found

### ISSUE THREAD

**Issue by chenhong231** [seata/seata#5475]
### Ⅰ. Issue Description

在saga模式页面（https://seata.io/zh-cn/docs/user/saga.html）。
step 3 启动 Saga Demo这个章节，提到：Demo中的数据库使用的是H2内存数据库, 生产上建议使用与业务相同的库, 目前支持Oracle, Mysql, DB2. 建表语句。点击后面给出的连接，出现404错误（ https://github.com/seata/seata/tree/develop/saga/seata-saga-engine-store/src/main/resources/sql）。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen

应该能访问到对应的SQL脚本

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by chenhong231** [comment]
麻烦提供能访问的sql脚本对应的地址

**Comment by slievrly** [comment]
@chenhong231 https://github.com/seata/seata/tree/2.x/script/client/saga/db
