### ISSUE TITLE
Business table and undo log table must be in the same database? Can I divide two data inventories?

### ISSUE THREAD

**Issue by 15168326318** [seata/seata#548]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
i guess you can't put business table and undo_log table in different database instance.in order to guarantee the branch transaction can be rollback properly.the undo_log must be created within the branch transaction.
