### ISSUE TITLE
GlobalTransactionScanner#wrapIfNecessary在springboot3下无法代理导致启动失败

### ISSUE THREAD

**Issue by ForJ-W** [seata/seata#5480]
### 环境：
**JDK：17
springboot：3.0.5
springcloud: 2022.0.2
springcloud-alibaba:2022.0.0.0-RC1

seata-all：1.6.1**

### 问题描述：
启动微服务客户端报错（集成了）

`java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.reflect.InvocationHandler java.lang.reflect.Proxy.h accessible: module java.base does not "opens java.lang.reflect" to unnamed module`

在getBean初始化调用applyBeanPostProcessorsAfterInitialization时
如果当前类为代理类（已被AnnotationAwareAspectJAutoProxyCreator#applyBeanPostProcessorsAfterInitialization增强过）
调用GlobalTransactionScanner#applyBeanPostProcessorsAfterInitialization再次代理时
通过SpringProxyUtils.findInterfaces获取接口信息（内部getAdvisedSupport会反射protected java.lang.reflect.InvocationHandler java.lang.reflect.Proxy.h）
调用h.setAccessible(true);
即出现jdk模块化后无法直接反射内部模块错误

### 期望解惑
目前我手动注入了GlobalTransactionScanner并设置了Order为最高优先级，让GlobalTransactionScanner在AnnotationAwareAspectJAutoProxyCreator执行后就不不会出现该问题；

1. 希望能告知此问题产生的原因；如果不是bug：我该怎么解决这个问题
2. 我这个解决方案有效吗，会影响事务内部代理的机制不

谢谢各位~

**Comment by ForJ-W** [comment]
“集成了“，那里我想说的是nacos、sentinel、dynamic-datasource、mybatis-plus来着

**Comment by ForJ-W** [comment]
1.7.0-native-rc2版本修复了SpringProxyUtils#getAdvisedSupport

**Comment by knightdreams6** [comment]
> 1.7.0-native-rc2版本修复了SpringProxyUtils#getAdvisedSupport

问一下怎么解决的，我也碰到了这个问题

**Comment by zhouxiaofu** [comment]
我也遇到这个问题了，终于解决了，谢谢楼主老哥。
```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.seata</groupId>
                <artifactId>seata-spring-boot-starter</artifactId>
                <version>1.7.0-native-rc2</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
