### ISSUE TITLE
当更新多个表时，多个表存在相同的onUpdateColumns时，会出现 column '***' in field list is ambigous 异常

### ISSUE THREAD

**Issue by liuxiaofeng2** [seata/seata#5488]
https://github.com/seata/seata/blob/faea6fb881774364c6281322fbbbd13a526c3c11/rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java#L144

**Comment by liuxiaofeng2** [comment]
`
// 需要给onUpdateColumns添加别名
List<String> onUpdateColumns = tableMeta.getOnUpdateColumnsOnlyName().stream().foreach(item -> getColumnNamesWithTablePrefix(table,tableAlias,item)).collect(Collections.toList());
onUpdateColumns.removeAll(unescapeUpdateColumns);
needUpdateColumns.addAll(onUpdateColumns.parallelStream()
    .map(onUpdateColumn -> ColumnUtils.addEscape(onUpdateColumn, getDbType()))
    .collect(Collectors.toList()));
`

**Comment by a364176773** [comment]
请发下你的sql示例

**Comment by liuxiaofeng2** [comment]
公司代码不方便展示；
示例：
存在user表(id,name,update_time)，user_company表(id,user_id,company_id,staff_no,update_time)
update_time 为onUpdateColumn字段
sql示例:

**Comment by liuxiaofeng2** [comment]
![image](https://user-images.githubusercontent.com/50196212/230286857-165dc747-f7dd-499d-bb70-142c0a0772bc.png)

**Comment by a364176773** [comment]
升级最新版检查下是否修复

**Comment by liuxiaofeng2** [comment]
> 升级最新版检查下是否修复

用的1.6.1的版本未修复

**Comment by a364176773** [comment]
> 

client.undo.onlyCareUpdateColumns是否设置为true，看你未更新的列也在后镜像中被查询，说明client.undo.onlyCareUpdateColumns是false，导致全量查询了其他列，而你的sql应该是从a库连接，查询b库，导致未指定库名的异常吧？

**Comment by a364176773** [comment]
update一次更新多个表目前应该是没有做支持的

**Comment by funky-eyes** [comment]
针对这个问题，社区讨论结论如下:
1. 需要再sql上增加表名区分
2. 增加产品限制，识别相关不支持的语法抛异常提示
The conclusions from the community discussions regarding this issue are as follows:
1. It is necessary to add table name distinction in SQL.
2. Add product restrictions to identify relevant unsupported syntax and throw exceptions with error messages indicating the unsupported syntax.

**Comment by liuxiaofeng2** [comment]
> 针对这个问题，社区讨论结论如下:
> 
> 1. 需要再sql上增加表名区分
> 2. 增加产品限制，识别相关不支持的语法抛异常提示
>    The conclusions from the community discussions regarding this issue are as follows:
> 3. It is necessary to add table name distinction in SQL.
> 4. Add product restrictions to identify relevant unsupported syntax and throw exceptions with error messages indicating the unsupported syntax.

好的，什么版本可以支持？大概什么时候完成？

**Comment by funky-eyes** [comment]
> > 针对这个问题，社区讨论结论如下:
> > 
> > 1. 需要再sql上增加表名区分
> > 2. 增加产品限制，识别相关不支持的语法抛异常提示
> >    The conclusions from the community discussions regarding this issue are as follows:
> > 3. It is necessary to add table name distinction in SQL.
> > 4. Add product restrictions to identify relevant unsupported syntax and throw exceptions with error messages indicating the unsupported syntax.
> 
> 好的，什么版本可以支持？大概什么时候完成？

Not yet finalized, progress will be updated in subsequent issues

**Comment by ptyin** [comment]
assign to me plz
