### ISSUE TITLE
no available service found in cluster 'default', please make sure registry config correct and keep your seata server running

### ISSUE THREAD

**Issue by xiaohaoni** [seata/seata#5495]
spring:
   application:
     name: bgb-core
   cloud:
      alibaba:
        seata:
           tx-service-group: my_test_tx_group
---
seata:
  enabled: true
  application-id: applicationName
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
      only-care-update-columns: true
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: localhost:8091
    enable-degrade: false
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: file
  registry:
    type: nacos
    nacos:
      server-addr: nacos://${nacos.host}:8848
      group: SEATA_GROUP
      application: seata-server
问题：
服务端已经跑起来了，但是一直报这个错误，请问是为什么

**Comment by slievrly** [comment]
https://seata.io/zh-cn/docs/user/registry/nacos.html

**Comment by xiaohaoni** [comment]
config:
      type: file
这个配置可以不加吗，配置我全部加到了application.yml里
