### ISSUE TITLE
使用feature_support_sqlserver分支，出现ClassCastException

### ISSUE THREAD

**Issue by fatapan** [seata/seata#5497]
使用Seata并使用SqlServer下，测试全局事务提交/回滚，通过一个center-service，调storage-service和account-service
![image](https://user-images.githubusercontent.com/77669844/230575183-e68a01b2-758c-4949-bdf0-784a130423e1.png)

![image](https://user-images.githubusercontent.com/77669844/230574431-127d21fd-5dec-4278-b15a-87f59e591f32.png)

![image](https://user-images.githubusercontent.com/77669844/230574115-92f77ac6-c2c1-45ee-a6fa-dc5ba2e616e8.png)

出现转化异常

- JDK version(e.g. `java -version`): 8
- Seata client/server version:  1.6.1
- Database version: mssql-jdbc 12.2.0.jre8

**Comment by a364176773** [comment]
这个应该是druid的问题,你尝试切换几个druid版本试试,如果还不行建议反馈至druid社区

**Comment by wt-better** [comment]
druid 解析 insert statement 的时候，会进行强制转型，SQLServer Oracle等DBType都是如此。
![image](https://user-images.githubusercontent.com/26296600/230721187-201d6da5-2038-4340-a671-819467b5345c.png)

druid里面可能其他地方也依赖了这块，是否在seata里面兼容下，根据DB类型new出不同类型的VisitorAdapter。

**Comment by a364176773** [comment]
> druid 解析 insert statement 的时候，会进行强制转型，SQLServer Oracle等DBType都是如此。 ![image](https://user-images.githubusercontent.com/26296600/230721187-201d6da5-2038-4340-a671-819467b5345c.png)
> 
> druid里面可能其他地方也依赖了这块，是否在seata里面兼容下，根据DB类型new出不同类型的VisitorAdapter。

druid在1.1.x版本上没有提供SQLASTVisitorAdapter的sqlserver实现,在sqlserver pr实现的时候没有用到这块所以没问题,随着后续seata的不断迭代,导致引发了这个潜在问题,得看下1.2.x的druid是否提供了对应sqlserver的实现

**Comment by a364176773** [comment]
https://github.com/GoodBoyCoder/seata/pull/3

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/3887  已修复,可以看下

**Comment by fatapan** [comment]
感谢你们的回复与帮助！

**Comment by a364176773** [comment]
不客气，我们计划在2.x的版本上合并这个pr，在这段时间内有任何问题欢迎反馈

**Comment by fatapan** [comment]
顺便问一下，你们计划在什么时候推出2.x的版本
