### ISSUE TITLE
examples improvement

### ISSUE THREAD

**Issue by oceanos** [seata/seata#55]
The examples module should be changed to a multi-module project to facilitate developers to contribute different cases.

**Comment by sharajava** [comment]
Good suggestion! 👍 Can you please contact 雪滴 in Dingtalk to get involved in example improvement?

**Comment by lovepoem** [comment]
The initial sql in this page https://github.com/alibaba/fescar/wiki/Quick-Start
should also be added to the source code

**Comment by leizhiyuan** [comment]
It seems have been done

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
