### ISSUE TITLE
Timeout Check

### ISSUE THREAD

**Issue by donnie0915** [seata/seata#550]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
   出现time out 时，出现无限的，如图
<img width="1109" alt="default" src="https://user-images.githubusercontent.com/5294336/53943862-05367480-40f9-11e9-8f13-5d05ec5805f3.png">

<img width="928" alt="default" src="https://user-images.githubusercontent.com/5294336/53943927-2e570500-40f9-11e9-9772-69094d12ead0.png">
数据就没有回滚
<img width="315" alt="default" src="https://user-images.githubusercontent.com/5294336/53944053-84c44380-40f9-11e9-9e86-72302bc0b006.png">
<img width="270" alt="default" src="https://user-images.githubusercontent.com/5294336/53944100-a291a880-40f9-11e9-9915-341d99a36eb6.png">

### Ⅱ. Describe what happened
只是dubeg doGlobalBegin 很快就time out ，后面就无法回滚，就是想问一下万一线上出现延迟出现time out,该如何避免数据无法回滚？
<img width="584" alt="default" src="https://user-images.githubusercontent.com/5294336/53944534-8c381c80-40fa-11e9-88f9-9c5e5a3c7ca0.png">

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
