### ISSUE TITLE
在升级到 seata-1.6.1 的时候发现 对字段名是关键字的情况不再兼容

### ISSUE THREAD

**Issue by graviation** [seata/seata#5500]
原来表中使用到了MySQL的关键字作为字段名，之前通过加 ` 号进行解决。

io.seata.rm.datasource.exec.UpdateExecutor#buildBeforeImageSQL

**Comment by a364176773** [comment]
异常堆栈

**Comment by graviation** [comment]
项目已经改了字段名。
就是源码中的这个方法：io.seata.rm.datasource.exec.UpdateExecutor#buildAfterImageSQL 中的 recognizer.getUpdateColumnsIsSimplified() 删除掉了字段的 ` 符号导致 SELECT FOR UPDATE 语句执行不成功。

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/5310
