### ISSUE TITLE
k8s部署1.2.0版本server怎么自定义JVM参数

### ISSUE THREAD

**Issue by JiangGuangxing** [seata/seata#5508]
k8s部署1.2.0版本server怎么自定义JVM参数
请问1.2.0版本docker镜像支持自定义JVM参数吗

**Comment by a364176773** [comment]
不支持，自行修改启动脚本重新打镜像

**Comment by JiangGuangxing** [comment]
> 不支持，自行修改启动脚本重新打镜
感谢回复，请问1.2.0版本的官方Dockerfile在哪里能查看呢，参考一下

**Comment by JiangGuangxing** [comment]
> 不支持，自行修改启动脚本重新打镜像

 感谢回复，请问1.2.0版本的官方Dockerfile在哪里能查看呢，参考一下
