### ISSUE TITLE
The distribute lock table is not config, please create the target table and config it

### ISSUE THREAD

**Issue by zhanjinhao** [seata/seata#5511]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I run seata-server on linux, it start successfully, but an error is reported in log.

>> The distribute lock table is not config, please create the target table and config it

![image](https://user-images.githubusercontent.com/39193291/231808440-9f33161a-288a-416f-bfe7-ee0961a8077c.png)

I have checked the db and the distribute lock table existes.

![image](https://user-images.githubusercontent.com/39193291/231810815-34998530-e9bc-4525-982c-ad98a29560b4.png)

my seata-server is register to nacos and the seataServer.properties is:

![image](https://user-images.githubusercontent.com/39193291/231809405-d9dfe3fd-aff1-4053-ba13-7bc65688c639.png)

I just learn to use seata and do not what the error means, can somebody give me advice?

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8_221
- Seata client/server version:  1.6.1
- Database version: mysql8
- OS(e.g. `uname -a`): centos8
- Others:

**Comment by a364176773** [comment]
Yes, if you want it to work, you must configure the table name

**Comment by canxiusi** [comment]
如果是 properties配置文件, 我觉得使用 驼峰可以解决问题, 我已经验证过 store.db.distributedLockTable=distributed_lock
