### ISSUE TITLE
Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by sixlei** [seata/seata#5512]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
全局事务提交时报错Deadlock found when trying to get lock; try restarting transaction，导致提交失败，全局事务未结束但是tm端已经运行结束，全局事务只能等timoutrollback。结合业务的现象是先操作成功了，过一分钟（全局事务超时时间）后，又回滚掉了

### Ⅱ. Describe what happened
seata-server报错
`io.seata.common.exception.StoreException: Deadlock found when trying to get lock; try restarting transaction
	at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.unLock(LockStoreDataBaseDAO.java:302) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.storage.db.lock.DataBaseLocker.releaseLock(DataBaseLocker.java:103) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.storage.db.lock.DataBaseLockManager.releaseGlobalSessionLock(DataBaseLockManager.java:79) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.session.GlobalSession.clean(GlobalSession.java:230) [seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.session.GlobalSession.closeAndClean(GlobalSession.java:243) [seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.coordinator.DefaultCore.lambda$commit$0(DefaultCore.java:154) [seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:194) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:331) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.coordinator.DefaultCore.commit(DefaultCore.java:152) [seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.doGlobalCommit(DefaultCoordinator.java:170) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:95) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.server.AbstractTCInboundHandler$2.execute(AbstractTCInboundHandler.java:90) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:124) ~[seata-core-1.4.3-fingard.jar:na]
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:90) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.core.protocol.transaction.GlobalCommitRequest.handle(GlobalCommitRequest.java:34) ~[seata-core-1.4.3-fingard.jar:na]
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:473) ~[seata-server-1.4.3-fingard.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:124) ~[seata-core-1.4.3-fingard.jar:na]
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:77) ~[seata-core-1.4.3-fingard.jar:na]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:279) ~[seata-core-1.4.3-fingard.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255) ~[druid-1.1.23.jar:1.1.23]
	at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.unLock(LockStoreDataBaseDAO.java:300) ~[seata-server-1.4.3-fingard.jar:na]
	... 22 common frames omitted`

目前发现了两种死锁：
一种是分支注册和锁删除之间的锁：
`*** (1) TRANSACTION:
TRANSACTION 7740634, ACTIVE 0 sec fetching rows
mysql tables in use 1, locked 1
LOCK WAIT 4 lock struct(s), heap size 1136, 52 row lock(s), undo log entries 7
MySQL thread id 970422, OS thread handle 139979643524864, query id 140047606718 10.10.57.14 root updating
delete from lock_table where xid = '10.10.57.14:8091:2234134150353738077' and branch_id in (2234134150353738095,2234134150353738111)
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 2690 page no 9 n bits 112 index PRIMARY of table `atsdb`.`lock_table` trx id 7740634 lock_mode X waiting
Record lock, heap no 41 PHYSICAL RECORD: n_fields 11; compact format; info bits 0
 0: len 30; hex 6a6462633a6d7973716c3a2f2f31302e31302e35372e31353a333330362f; asc jdbc:mysql://10.10.57.15:3306/; (total 88 bytes);
 1: len 6; hex 000000761cd8; asc    v  ;;
 2: len 7; hex 82000007d80110; asc        ;;
 3: len 30; hex 31302e31302e35372e31343a383039313a32323334313334313530333533; asc 10.10.57.14:8091:2234134150353; (total 36 bytes);
 4: len 8; hex 9f013d2c3c675964; asc   =,<gYd;;
 5: len 8; hex 9f013d2c3c675984; asc   =,<gY ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f31302e31302e35372e31353a333330362f; asc jdbc:mysql://10.10.57.15:3306/; (total 35 bytes);
 7: len 15; hex 4143545f48495f50524f43494e5354; asc ACT_HI_PROCINST;;
 8: len 30; hex 306464646537643232663439343938333933356231303564323131653566; asc 0ddde7d22f494983935b105d211e5f; (total 32 bytes);
 9: len 5; hex 99af1aa536; asc     6;;
 10: len 5; hex 99af1aa536; asc     6;;

*** (2) TRANSACTION:
TRANSACTION 7740632, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
3 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 5
MySQL thread id 970425, OS thread handle 139974227228416, query id 140047606724 10.10.57.14 root update
insert into lock_table(xid, transaction_id, branch_id, resource_id, table_name, pk, row_key, gmt_create, gmt_modified) values ('10.10.57.14:8091:2234134150353738084', 2234134150353738084, 2234134150353738116, 'jdbc:mysql://10.10.57.15:3306/atsdb', 'ACT_HI_ACTINST', '83999f65d3b34425a96fb194d8e52a3e', 'jdbc:mysql://10.10.57.15:3306/atsdb^^^ACT_HI_ACTINST^^^83999f65d3b34425a96fb194d8e52a3e', now(), now())
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 2690 page no 9 n bits 112 index PRIMARY of table `atsdb`.`lock_table` trx id 7740632 lock_mode X locks rec but not gap
Record lock, heap no 41 PHYSICAL RECORD: n_fields 11; compact format; info bits 0
 0: len 30; hex 6a6462633a6d7973716c3a2f2f31302e31302e35372e31353a333330362f; asc jdbc:mysql://10.10.57.15:3306/; (total 88 bytes);
 1: len 6; hex 000000761cd8; asc    v  ;;
 2: len 7; hex 82000007d80110; asc        ;;
 3: len 30; hex 31302e31302e35372e31343a383039313a32323334313334313530333533; asc 10.10.57.14:8091:2234134150353; (total 36 bytes);
 4: len 8; hex 9f013d2c3c675964; asc   =,<gYd;;
 5: len 8; hex 9f013d2c3c675984; asc   =,<gY ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f31302e31302e35372e31353a333330362f; asc jdbc:mysql://10.10.57.15:3306/; (total 35 bytes);
 7: len 15; hex 4143545f48495f50524f43494e5354; asc ACT_HI_PROCINST;;
 8: len 30; hex 306464646537643232663439343938333933356231303564323131653566; asc 0ddde7d22f494983935b105d211e5f; (total 32 bytes);
 9: len 5; hex 99af1aa536; asc     6;;
 10: len 5; hex 99af1aa536; asc     6;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 2690 page no 7 n bits 112 index PRIMARY of table `atsdb`.`lock_table` trx id 7740632 lock_mode X locks gap before rec insert intention waiting
Record lock, heap no 28 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f31302e31302e35372e31353a333330362f; asc jdbc:mysql://10.10.57.15:3306/; (total 87 bytes);
 1: len 6; hex 000000761c7c; asc    v |;;
 2: len 7; hex 010000064b0a51; asc     K Q;;
 3: len 30; hex 31302e31302e35372e31343a383039313a32323334313334313530333533; asc 10.10.57.14:8091:2234134150353; (total 36 bytes);
 4: len 8; hex 9f013d2c3c675903; asc   =,<gY ;;
 5: len 8; hex 9f013d2c3c675966; asc   =,<gYf;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f31302e31302e35372e31353a333330362f; asc jdbc:mysql://10.10.57.15:3306/; (total 35 bytes);
 7: len 14; hex 4143545f48495f414354494e5354; asc ACT_HI_ACTINST;;
 8: len 30; hex 393939646138363034633861346137346262356661643635363930373437; asc 999da8604c8a4a74bb5fad65690747; (total 32 bytes);
 9: len 5; hex 99af1aa535; asc     5;;
 10: len 5; hex 99af1aa535; asc     5;;

*** WE ROLL BACK TRANSACTION (2)`
可以看到是delete from lock_table和insert into lock_table之间的死锁。
两个sql分别是：
delete from lock_table where xid = '10.10.57.14:8091:2234134150353738077' and branch_id in (2234134150353738095,2234134150353738111)；
insert into lock_table(xid, transaction_id, branch_id, resource_id, table_name, pk, row_key, gmt_create, gmt_modified) values ('10.10.57.14:8091:2234134150353738084', 2234134150353738084, 2234134150353738116, 'jdbc:mysql://10.10.57.15:3306/atsdb', 'ACT_HI_ACTINST', '83999f65d3b34425a96fb194d8e52a3e', 'jdbc:mysql://10.10.57.15:3306/atsdb^^^ACT_HI_ACTINST^^^83999f65d3b34425a96fb194d8e52a3e', now(), now());

另外一种是两个全局提交之间的死锁：
` (1) TRANSACTION:
TRANSACTION 22608608, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 5 lock struct(s), heap size 1136, 4 row lock(s), undo log entries 1
MySQL thread id 207969, OS thread handle 140178113099520, query id 849506804 172.18.229.176 jats001 updating
delete from lock_table where xid = '172.18.229.176:8091:6782791748958879406' and branch_id in (6782791748958879413,6782791748958879425)
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 117 page no 6 n bits 104 index PRIMARY of table `atsdb`.`lock_table` trx id 22608608 lock_mode X locks rec but not gap waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 11; compact format; info bits 0
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 100 bytes);
 1: len 6; hex 00000158fad6; asc    X  ;;
 2: len 7; hex 820000046c0bf8; asc     l  ;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feae; asc  !Q( $  ;;
 5: len 8; hex de215128ae24fec1; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 24; hex 4143545f4558545f48495f425553494e4553535f494e464f; asc ACT_EXT_HI_BUSINESS_INFO;;
 8: len 30; hex 336363333935336364393137663638323462303936626264313461343163; asc 3cc3953cd917f6824b096bbd14a41c; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

*** (2) TRANSACTION:
TRANSACTION 22608601, ACTIVE 0 sec fetching rows, thread declared inside InnoDB 4267
mysql tables in use 1, locked 1
21 lock struct(s), heap size 3520, 110 row lock(s), undo log entries 106
MySQL thread id 208011, OS thread handle 140177967838976, query id 849506401 172.18.229.176 jats001 updating
delete from lock_table where xid = '172.18.229.176:8091:6782791748958879404' and branch_id in (6782791748958879411,6782791748958879423)
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 117 page no 6 n bits 112 index PRIMARY of table `atsdb`.`lock_table` trx id 22608601 lock_mode X locks rec but not gap
Record lock, heap no 2 PHYSICAL RECORD: n_fields 11; compact format; info bits 0
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 100 bytes);
 1: len 6; hex 00000158fad6; asc    X  ;;
 2: len 7; hex 820000046c0bf8; asc     l  ;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feae; asc  !Q( $  ;;
 5: len 8; hex de215128ae24fec1; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 24; hex 4143545f4558545f48495f425553494e4553535f494e464f; asc ACT_EXT_HI_BUSINESS_INFO;;
 8: len 30; hex 336363333935336364393137663638323462303936626264313461343163; asc 3cc3953cd917f6824b096bbd14a41c; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

Record lock, heap no 6 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 100 bytes);
 1: len 6; hex 00000158fad9; asc    X  ;;
 2: len 7; hex 020000046f1c87; asc     o  ;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feac; asc  !Q( $  ;;
 5: len 8; hex de215128ae24febf; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 24; hex 4143545f4558545f48495f425553494e4553535f494e464f; asc ACT_EXT_HI_BUSINESS_INFO;;
 8: len 30; hex 653364613339663062613932343934323235643162646436633130383531; asc e3da39f0ba92494225d1bdd6c10851; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

Record lock, heap no 8 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 100 bytes);
 1: len 6; hex 00000158fad9; asc    X  ;;
 2: len 7; hex 020000046f1d75; asc     o u;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feac; asc  !Q( $  ;;
 5: len 8; hex de215128ae24febf; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 24; hex 4143545f4558545f52555f425553494e4553535f494e464f; asc ACT_EXT_RU_BUSINESS_INFO;;
 8: len 30; hex 393332393263613861303130313931376139636564313237396663643537; asc 93292ca8a0101917a9ced1279fcd57; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

Record lock, heap no 13 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 100 bytes);
 1: len 6; hex 00000158fad9; asc    X  ;;
 2: len 7; hex 020000046f1e63; asc     o c;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feac; asc  !Q( $  ;;
 5: len 8; hex de215128ae24febf; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 24; hex 4143545f4558545f52555f425553494e4553535f494e464f; asc ACT_EXT_RU_BUSINESS_INFO;;
 8: len 30; hex 653364613339663062613932343934323235643162646436633130383531; asc e3da39f0ba92494225d1bdd6c10851; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

Record lock, heap no 17 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 90 bytes);
 1: len 6; hex 00000158fad9; asc    X  ;;
 2: len 7; hex 020000046f1f51; asc     o Q;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feac; asc  !Q( $  ;;
 5: len 8; hex de215128ae24febf; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 14; hex 4143545f48495f414354494e5354; asc ACT_HI_ACTINST;;
 8: len 30; hex 353833646339333231643930346665303939393439643964663365616234; asc 583dc9321d904fe099949d9df3eab4; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

Record lock, heap no 19 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 90 bytes);
 1: len 6; hex 00000158fad9; asc    X  ;;
 2: len 7; hex 020000046f202b; asc     o +;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feac; asc  !Q( $  ;;
 5: len 8; hex de215128ae24febf; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 14; hex 4143545f48495f414354494e5354; asc ACT_HI_ACTINST;;
 8: len 30; hex 386564646432383739646534346138666261666362643031663061363933; asc 8eddd2879de44a8fbafcbd01f0a693; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

Record lock, heap no 25 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 90 bytes);
 1: len 6; hex 00000158fad9; asc    X  ;;
 2: len 7; hex 020000046f2105; asc     o! ;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feac; asc  !Q( $  ;;
 5: len 8; hex de215128ae24febf; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 14; hex 4143545f48495f434f4d4d454e54; asc ACT_HI_COMMENT;;
 8: len 30; hex 306634376539376465386666343064346164313065373631616531386239; asc 0f47e97de8ff40d4ad10e761ae18b9; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

Record lock, heap no 28 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 90 bytes);
 1: len 6; hex 00000158fad9; asc    X  ;;
 2: len 7; hex 020000046f21df; asc     o! ;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feac; asc  !Q( $  ;;
 5: len 8; hex de215128ae24febf; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 14; hex 4143545f48495f434f4d4d454e54; asc ACT_HI_COMMENT;;
 8: len 30; hex 353436353433653437383261343932636134356336633836383937383036; asc 546543e4782a492ca45c6c86897806; (total 32 bytes);
 9: len 5; hex 99afd6a2e6; asc      ;;
 10: len 5; hex 99afd6a2e6; asc      ;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 117 page no 14 n bits 128 index PRIMARY of table `atsdb`.`lock_table` trx id 22608601 lock_mode X locks rec but not gap waiting
Record lock, heap no 27 PHYSICAL RECORD: n_fields 11; compact format; info bits 32
 0: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 89 bytes);
 1: len 6; hex 00000158fae0; asc    X  ;;
 2: len 7; hex 02000001650253; asc     e S;;
 3: len 30; hex 3137322e31382e3232392e3137363a383039313a36373832373931373438; asc 172.18.229.176:8091:6782791748; (total 39 bytes);
 4: len 8; hex de215128ae24feae; asc  !Q( $  ;;
 5: len 8; hex de215128ae24feb5; asc  !Q( $  ;;
 6: len 30; hex 6a6462633a6d7973716c3a2f2f3137322e31382e3232392e3137353a3333; asc jdbc:mysql://172.18.229.175:33; (total 38 bytes);
 7: len 13; hex 545f53455f5041594d454e5453; asc T_SE_PAYMENTS;;
 8: len 30; hex 306364636332636439626630346331343866376565396263316362316362; asc 0cdcc2cd9bf04c148f7ee9bc1cb1cb; (total 32 bytes);
 9: len 5; hex 99afd6a2e5; asc      ;;
 10: len 5; hex 99afd6a2e5; asc      ;;

*** WE ROLL BACK TRANSACTION (1) `
可以看到是两个delte from lock_table之间的死锁。
sql分别是：
delete from lock_table where xid = '172.18.229.176:8091:6782791748958879406' and branch_id in (6782791748958879413,6782791748958879425)
delete from lock_table where xid = '172.18.229.176:8091:6782791748958879404' and branch_id in (6782791748958879411,6782791748958879423)

看到其他人也有类似的问题，回复是#4750的pr修复了这个问题，现在不理解这两种死锁原因是什么。特别是第二种，为什么两个delete之间会触发死锁呢。然后4570的pr把(xid,branchid)的联合索引换成了xid的索引为什么能解决呢

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:   1.4.2
- Database version: MySQL 8.0.16 RR隔离级别
- OS(e.g. `uname -a`):centos7
- Others:

**Comment by a364176773** [comment]
https://github.com/seata/seata/issues/4382
