### ISSUE TITLE
seata使用redis注册中心，pod杀掉了ip变更，但是client连的还是旧的。客户端重启后才能正常访问

### ISSUE THREAD

**Issue by Splinglove** [seata/seata#5516]
jdk：1.8
使用的是seata1.4.2

**Comment by a364176773** [comment]
升级1.5.2及以上版本，非优雅下线server导致了ip残留

**Comment by Splinglove** [comment]
是服务器非优雅下线，然后导致客户端ip残留吗？我这边是否是升级client的版本即可？按现象来看，seata-server也需要同步升级么？
