### ISSUE TITLE
使用k8s方式部署高可用，控制面板数据不一致问题

### ISSUE THREAD

**Issue by SophonSecurityEngineer** [seata/seata#5517]
使用k8s方式部署高可用，控制面板数据不一致问题
如下图，应用启动时，连接了两个节点
![image](https://user-images.githubusercontent.com/122199877/232290012-16449845-d9b3-4218-9fd8-52a8fee6320b.png)
![image](https://user-images.githubusercontent.com/122199877/232289866-4dd41a9a-1493-489c-9951-20809a44bfb6.png)
断点调试 
![image](https://user-images.githubusercontent.com/122199877/232290046-dcd08fca-d9cb-4901-858c-038445150f8d.png)
断点后，查看控制台的数据信息，发现只有一个节点的数据
![image](https://user-images.githubusercontent.com/122199877/232290082-4187fa01-da82-4667-bb34-c74c41fd4357.png)

请问是否我的部署方式有问题，还是说seata不支持控制台数据同步?

**Comment by a364176773** [comment]
估计用的是file，压根没用存算分离的db模式或redis，如果你觉得你配了，那肯定是配错了。
