### ISSUE TITLE
docker image supports JVM parameter injection

### ISSUE THREAD

**Issue by slievrly** [seata/seata#5521]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

docker image supports JVM parameter injection

1. Keep the default JVM parameters consistent with the script https://github.com/seata/seata/blob/2.x/distribution/bin/seata-server.sh.
2. Support environment variable injection of JVM parameters such as Xmx, Xms, etc.

docker hub: https://hub.docker.com/repository/docker/seataio/seata-server/general

jib plugin: https://github.com/seata/seata/blob/9b35ba9f6b866f9aaa1ff6e655f6b0e576faca4a/server/pom.xml#L287

---

1. 保持默认JVM参数与脚本https://github.com/seata/seata/blob/2.x/distribution/bin/seata-server.sh一致。

2. 支持JVM参数如Xmx、Xms等的环境变量注入。

docker hub: https://hub.docker.com/repository/docker/seataio/seata-server/general

jib plugin: https://github.com/seata/seata/blob/9b35ba9f6b866f9aaa1ff6e655f6b0e576faca4a/server/pom.xml#L287

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by xingfudeshi** [comment]
I will do this.
