### ISSUE TITLE
Support for more operational commands in seata-server.sh

### ISSUE THREAD

**Issue by slievrly** [seata/seata#5522]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

Support for more operational commands in seata-server.sh
1. start
2. stop
3. restart

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by doubleDimple** [comment]
please assign me

**Comment by xingfudeshi** [comment]
> please assign me

Thank you!Looking forward to your PR.
