### ISSUE TITLE
springboot整合Seata报错 io.seata.common.exception.ShouldNeverHappenException: auto increment column not exist

### ISSUE THREAD

**Issue by songyang89** [seata/seata#5526]
io.seata.common.exception.ShouldNeverHappenException: auto increment column not exist

**Comment by doubleDimple** [comment]
please add an auto-increment primary key to your table and try again

**Comment by songyang89** [comment]
但是我们的数据库表的主键都是UUID,这样怎么解决
But our database tables all have UUID primary keys, so what's the solution
我是在数据库中使用触发器为主键设置UUID的
I set the UUID in the database using the trigger as the primary key

**Comment by a364176773** [comment]
版本号,表结构,异常完整堆栈发出来

**Comment by slievrly** [comment]
@songyang89 Currently, trigger-generated primary keys are not supported. We suggest specifying a determined value directly in the program.
