### ISSUE TITLE
反馈一个1.5.2的bug：file-appender.xml修改不生效

### ISSUE THREAD

**Issue by 412165137lzh** [seata/seata#5530]
#5493  这个bug之前提到过，开发者觉得没问题居然直接关闭issue了，也不经过测试就下结论，很无语，这里再补充一下，避免大家踩坑

问题描述：
1.5.2的seata-server端配置有问题，根目录下的conf\logback\file-appender.xml文件修改不生效，原因是seata-server服务启动的时候，并不会加载这个配置文件，经过分析，是conf/logback-spring.xml里面的配置有问题，如下
原配置：<include resource="logback/file-appender.xml"/>
修改成<include file=“”>的形式就正常了

**Comment by 412165137lzh** [comment]
部分信息被吞了，补充
原配置是：include resource="logback/file-appender.xml"
修改后配置是include file=""

**Comment by a364176773** [comment]
这个问题存在,是因为读取了jar里的logback文件夹的xml导致的,解决方案需要打包出来的logback.xml中的resource路径改为bashdir的路径指向外部,否则直接用相对路径走的是jar包内

**Comment by 412165137lzh** [comment]
> 

好的~ 
我之前的修改方案如下，可供参考
《include file="${basedir}/conf/logback/file-appender.xml"》

**Comment by a364176773** [comment]
> > 
> 
> 好的~ 我之前的修改方案如下，可供参考 《include file="${basedir}/conf/logback/file-appender.xml"》

直接这么写在idea开发的时候引不到，所以要区分开到底是打包下允许的，还是idea里开发运行的，你可以一起看下#5531 pr的改动
