### ISSUE TITLE
io.seata 1.7.0-native-rc2 no available service found in cluster 'default', please make sure registry config correct and keep your seata server running [BUG]

### ISSUE THREAD

**Issue by caomeinaitang** [seata/seata#5533]
你好我在使用 seata 1.7.0-native-rc2
出现了no available service found in cluster 'default', please make sure registry config correct and keep your seata server running问题
查看日志--- 
[main] com.alibaba.nacos.client.naming          : init new ips(0) service: DEFAULT_GROUP@@seata-server@@default -> []
[ main] com.alibaba.nacos.client.naming          : current ips:(0) service: DEFAULT_GROUP@@seata-server@@default -> []
![image](https://user-images.githubusercontent.com/116071038/234236121-eb7f3aa1-1d5f-421f-bb0c-c477b3d552f1.png)

**Comment by caomeinaitang** [comment]
### is:open label:"type: bug"

**Comment by slievrly** [comment]
@caomeinaitang Please search the issue first. There are similar problems.

**Comment by a364176773** [comment]
你发的截图没任何意义，都跟到这了，自行对比下跟server的nacos配置内容是否一致，到底有没有返回集群列表

**Comment by slievrly** [comment]
> SEATA_GROUP

I didn't quite understand the meaning that needs to be expressed. I suggest breaking it down into 1, 2, 3, 4 points to clarify the expression.

**Comment by a364176773** [comment]
那你seata-server的nacos配置项又是怎么写的？信息不提供完整无从排查
