### ISSUE TITLE
seata连接nacos集群，心跳400刷日志

### ISSUE THREAD

**Issue by white1208** [seata/seata#5534]
seata连接nacos集群（3台）后，
注册到了A，后续nacos心跳（/nacos/v1/ns/instance/beat）请求发送到
B或C报400，后台一直刷日志，请求到注册A返回200

心跳报错日志
![image](https://user-images.githubusercontent.com/15647160/233988754-bf679dc9-d19f-4ceb-b320-62e3c55003a6.png)

心跳请求到注册nacos服务端
![image](https://user-images.githubusercontent.com/15647160/233988952-63a32880-07a8-4b1a-ba80-1d7240014669.png)

心跳请求到非注册nacos服务端
![image](https://user-images.githubusercontent.com/15647160/233989063-0bcbff5a-a010-4a39-a580-fde45034f417.png)

**Comment by slievrly** [comment]
@white1208 Provide more information such as nacos client and server versions.

**Comment by white1208** [comment]
server  nacos version 2.2.2
client   seata  version 1.6.1

![image](https://user-images.githubusercontent.com/15647160/234205711-735bd528-48ce-406e-ad86-66a3775369b8.png)
![image](https://user-images.githubusercontent.com/15647160/234205870-34119340-b42b-43c6-a339-2540174965bc.png)

**Comment by a364176773** [comment]
建议提交到nacos社区辅助排查下是否存在高低版本兼容性问题

**Comment by white1208** [comment]
> 建议提交到nacos社区辅助排查下是否存在高低版本兼容性问题

您那边会复现么，我想确认一下是不是我配置的问题

**Comment by a364176773** [comment]
seata基于1.4.2测试没有这个问题，本人测试过2.0.x没有这个问题

**Comment by white1208** [comment]
> seata基于1.4.2测试没有这个问题，本人测试过2.0.x没有这个问题

2.0.X测试的也是连接nacos集群场景么，nacos单机情况，我这也没问题，
如果您那边也是nacos集群场景没问题，那就是我这边问题

**Comment by a364176773** [comment]
即便是集群有问题也跟seata无关，seata用的是标准的nacos api实现的，你应该反馈到nacos社区

**Comment by shfpflyawei** [comment]
@white1208 
我这边也遇到了类似问题，我使用的是nacos集群2.2.2然后seata版本是1.3.0
我的问题是微服务启动的时候，seata客户端连接nacos集群会遇到400问题，这是偶发性的，重启微服务POD 就正常，
而且只有在启动的时候会偶尔出现
![09812fc7dca8f17bf3686a7653af96e1](https://user-images.githubusercontent.com/34828547/236413114-546750f6-4920-424c-9e95-714ddd328dcb.png)
