### ISSUE TITLE
xa not support dbType: sqlserver

### ISSUE THREAD

**Issue by wangenji2015** [seata/seata#5542]
请问sqlserver目前是不支持吗，调了两天白费了，就没有适配SqlServer的模式是吗

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/3203  拉这个pr的代码下来本地打包后引入，测试没问题后帮忙留言一下，社区后面会合并，需要大家的测试

**Comment by wangenji2015** [comment]
好

**Comment by wangenji2015** [comment]
> #3203 拉这个pr的代码下来本地打包后引入，测试没问题后帮忙留言一下，社区后面会合并，需要大家的测试

请问我这个报错，是maven版本问题吗，protoc did not exit cleanly. Review output for more information.
![image](https://user-images.githubusercontent.com/20235911/234807367-bec28191-ad54-4a41-a8a8-8f8b0caf99ed.png)

**Comment by wangenji2015** [comment]
![image](https://user-images.githubusercontent.com/20235911/234813564-76837499-7f8c-495d-9163-707e39c56eb3.png)

**Comment by a364176773** [comment]
打包命令是什么?你的idea有问题吧,输出的都是乱码,设置下编码

**Comment by slievrly** [comment]
https://github.com/seata/seata/blob/1c8e4bfb55d629f4efd2880d16ad10ee88837d13/integration/grpc/pom.xml#L79
change to com.google.protobuf:protoc:3.5.0:exe:${os.detected.classifier}

**Comment by wangenji2015** [comment]
> https://github.com/seata/seata/blob/1c8e4bfb55d629f4efd2880d16ad10ee88837d13/integration/grpc/pom.xml#L79
> 
> 
> change to com.google.protobuf:protoc:3.5.0:exe:${os.detected.classifier}

感谢，我直接把test里面的protobuf删了，打包可以了

**Comment by wangenji2015** [comment]
> 打包命令是什么?你的idea有问题吧,输出的都是乱码,设置下编码

删了test里面的protobuf文件可以打包了，我就用idea的install命令，skip.test=true，另外server还是用1.6.1吗还是也需要打包部署呢

**Comment by a364176773** [comment]
应该是1.7.0-SNAPSHOT

**Comment by a364176773** [comment]
目前有没有什么问题?

**Comment by wangenji2015** [comment]
> 目前有没有什么问题?

还在调试，什么时候发正式版啊

**Comment by a364176773** [comment]
> > 目前有没有什么问题?
> 
> 还在调试，什么时候发正式版啊

测试的咋样了，等2.0会集成进去
