### ISSUE TITLE
seata1.7何时发版

### ISSUE THREAD

**Issue by lbj812** [seata/seata#5543]
目前已知的重大bug已经在develop分支修改了，何时发版呢？
很着急

**Comment by yili001** [comment]
啥重大bug？

**Comment by xbox1994** [comment]
bug太tm多了，https://github.com/seata/seata/pull/5310
这个绝对是重大bug

**Comment by yinrog** [comment]
绝对是重大bug,升级1.6的话，需要把有关键字字段的表相关的业务全部去掉全局事务，而且官方发现了也不着急出修复版本，意思是等到新版本再修复，到时候新版本又有新bug，来来回回，完全不能用于生产环境；
