### ISSUE TITLE
Enhancement nacos-config

### ISSUE THREAD

**Issue by TianMing2018** [seata/seata#5547]
## Why you need it?

1. optimize pull interval
when we register `seata` to `nacos`, it will pull  config from `nacos` every 200ms, it's so terrible. Normally , we will not change this config so frequently.  why don't try to listening config changed event  or add one property to controll poll interval?
2. chage log level of 'com.alibaba.nacos.client.config.impl.ClientWorker` to `error `
   > due to line 1, it will increase log size so fast , this config info is not so important for seata,too
3. upgrade `nacos-client` to 2.x and adapt the new authentication

## How it could be?

q1 and q2 should not be designed so carefully, cause it's not so adjective for un real-time

**Comment by a364176773** [comment]
Question 1 is not related to seata, it is a bug in a certain version of nacos. Please refer to the nacos community for consultation
Question 2: Please provide the official new authentication parameters of NACOS for us to adapt
