### ISSUE TITLE
delete fence log failed

### ISSUE THREAD

**Issue by slievrly** [seata/seata#5554]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

work in AT mode

![image](https://user-images.githubusercontent.com/8758457/236593675-e4aa8c15-295d-4cf2-b38f-d7317acf55a0.png)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by dmego** [comment]
plz assgin to me
