### ISSUE TITLE
TC 在删除分支事务时，同步和异步的问题

### ISSUE THREAD

**Issue by laywin** [seata/seata#5564]
retrying = true 的时候应该才是异步的情况，目测应该去掉取反，确认下哈.

![image](https://user-images.githubusercontent.com/22276474/236667727-29eda797-7b80-4bdc-b94b-1394c532b7cf.png)

![image](https://user-images.githubusercontent.com/22276474/236667769-6937726a-cd1f-44d6-a45c-4a203c993b76.png)

**Comment by a364176773** [comment]
已经处于异步线程中，删除branchsession就本身在异步，不需要额外开线程资源去处理造成无意义开销

**Comment by laywin** [comment]
感谢，明白了，这命名太疑惑！
