### ISSUE TITLE
有没有打算，注册中心和配置中心，支持k8s？

### ISSUE THREAD

**Issue by thousmile** [seata/seata#5569]
有没有打算，注册中心和配置中心，支持k8s？

Is there any plan, registration center and configuration center, to support k8s?

**Comment by a364176773** [comment]
配置中心自己用type=file，然后configmap环境变量注入即可。
raft模式下可以直接用k8s的clusterip连接，也不需要额外注册中心，无状态部署方式需要对接apiserver在计划中
