### ISSUE TITLE
RM_CHANNELS get npe

### ISSUE THREAD

**Issue by a364176773** [seata/seata#5575]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
rm注册时resourceid未指定,tc二阶段下发shi时由于rm resourceid为null,通过ConcurrentHashMap get(null) 会发生空指针异常,jdk8及以上版本是不允许key为null
![image](https://github.com/seata/seata/assets/19943636/a330e8fd-fce2-4ccd-a0f9-27fba743d193)

<img width="1618" alt="ca245f3b131a31a6b4b7eb1e1c5f13ff" src="https://github.com/seata/seata/assets/19943636/c97ca0d9-c724-4426-b271-85eb48a6a8e6">
<img width="1724" alt="00c481467493cb34f3793cf407f5c676" src="https://github.com/seata/seata/assets/19943636/a48dd2d0-a948-4dfd-93af-40bf7efa01d1">

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by dmego** [comment]
plz assgin to me
