### ISSUE TITLE
Seata的注册中心、配置中心，可以与微服务业务使用不同的吗?

### ISSUE THREAD

**Issue by Melod-YI** [seata/seata#5581]
RT，团队目前使用的注册配置中心选型不在Seata支持范围。可以通过另外部署一个nacos集群专门用于seata吗？

**Comment by a364176773** [comment]
可以,你也可以用spi扩展你们使用的注册配置中心

**Comment by Melod-YI** [comment]
> 可以,你也可以用spi扩展你们使用的注册配置中心

也就是我的业务微服务是不需要注册到seata配置的注册中心的，可以这么理解么？
通过spi拓展，是指去实现seata的拓展点接口吗

**Comment by a364176773** [comment]
你的业务应用所用的配置注册中心跟seata用的不是一回事，使用方都不是同一个。
是
