### ISSUE TITLE
全局事务未提交，本地其他事务修改相同数据，脏写提交后导致全局事务回滚失败的情况如何处理

### ISSUE THREAD

**Issue by yili001** [seata/seata#5586]
根据官方文档上提供的信息，对这种情况，本地其他事务修改相同数据时需要使用@GlobalLock注解来避免。但是假如开发人员忘记了加上此注解，导致此种异常发生，这种情况下如何在seata中安全地释放全局锁，清除对应的undo_log,branch-table, distributed_locak,global-table,lock_table表中的数据呢？
文档里给的这个链接感觉很模糊 [脏数据回滚失败如何处理?](https://seata.io/zh-cn/docs/overview/faq.html#5)， 
希望各位可以提供一个详细一点的解决思路

**Comment by yili001** [comment]
如果seata-server是以db作为存储方式，seata server连的数据库里的表数据不需要手动清理吗

**Comment by a364176773** [comment]
undolog删除后自动会删除对应的branch，global ，lock信息
