### ISSUE TITLE
session 采用file存储时的一点疑惑

### ISSUE THREAD

**Issue by FRookie** [seata/seata#5592]
https://github.com/seata/seata/blob/d1e6e6bcc99c594542fbbe5a207cad006b8f84ca/server/src/main/java/io/seata/server/storage/file/store/FileTransactionStoreManager.java#L183

此处出现缓存次数不是 65535 * 8的整数倍时，但时间间隔很久的情况该怎么处理呢？用 条件或（“｜｜”）处理会不会好点？

**Comment by a364176773** [comment]
不明白你想干嘛，可以描述清楚点吗

**Comment by FRookie** [comment]
> 不明白你想干嘛，可以描述清楚点吗

这里是 判断session刷新到本地文件的逻辑：
            if (!writeDataFile(new TransactionWriteStore(session, logOperation).encode())) {
                return false;
            }
            lastModifiedTime = System.currentTimeMillis();
            curFileTrxNum = FILE_TRX_NUM.incrementAndGet();
            if (curFileTrxNum % PER_FILE_BLOCK_SIZE == 0
                && (System.currentTimeMillis() - trxStartTimeMills) > MAX_TRX_TIMEOUT_MILLS) {
                return saveHistory();
            }
我想问的是，如果在很长一段时间内 curFileTrxNum 不能达到PER_FILE_BLOCK_SIZE的整数倍时，session就无法存到到本地文件中了。 是否可以改成 curFileTrxNum % PER_FILE_BLOCK_SIZE == 0 || (System.currentTimeMillis() - trxStartTimeMills) > MAX_TRX_TIMEOUT_MILLS来判断？

**Comment by a364176773** [comment]
这里只是saveHistory 做文件的rolling吧？

**Comment by slievrly** [comment]
Data file rolling requires a block size that is a multiple of the block size and reaches a certain time. The block size is set to prevent periodic rolling of low-frequency transactions, while the time-based rolling is to prevent frequent rolling of high-frequency transactions. Rolling a data file is a time-consuming I/O operation.
