### ISSUE TITLE
Repeatedly executed hook in TransactionalTemplate

### ISSUE THREAD

**Issue by Bughue** [seata/seata#5595]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
在 https://github.com/seata/seata/pull/5594 里修复了日志重复打印的问题，但hook重复执行依然存在。以begin为例子，每次切面进来时会先执行hook再执行tx.begin()。
![image](https://github.com/seata/seata/assets/3788653/400c3b96-3c1b-474b-8f07-01f80aafd116)
在tx.begin()里面会有 判断role != GlobalTransactionRole.Launcher并直接返回，但before和after的hook依然执行了，这个不太符合事务传播的逻辑，因为根本就没有新开启事务
![image](https://github.com/seata/seata/assets/3788653/042c2cb7-9941-4b34-a183-358972bd1ede)

同理，在commit和rollback都有这种问题。大家可以讨论一下是不是要改成只执行一次。
另外我有考虑过，如果把一些关键参数给到hook，用户就能自行决定，不过这样做有点重，可能没有必要。
如果确认需要改成执行一次的话，我可以fix掉

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
"Begin/Commit/Rollback" are hooks designed for Global Transaction Manager, and they should only be executed once.
