### ISSUE TITLE
请问 1.7.0 什么时候能发呢

### ISSUE THREAD

**Issue by JavaLionLi** [seata/seata#5597]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by xbox1994** [comment]
同问+100000000000000000000000000000000000000000000000

**Comment by xbox1994** [comment]
这个seata的bug实在是数不胜数，只能期待最新版本
