### ISSUE TITLE
how to trace the transaction link according to the XID

### ISSUE THREAD

**Issue by vonfun** [seata/seata#5599]
## Why you need it?
I want to implement the distributed transaction tracing according to the XID, but  seata-plugin could not finish it.

## How it could be?
Intercept distributed transaction requests with xid and span xid into the seata-plugin

## Other related information
End-to-end distributed transaction tracing

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/user/apm/skywalking.html  Did you actually encounter any problems based on this document?

**Comment by fengzhenhai168** [comment]
> https://seata.io/zh-cn/docs/user/apm/skywalking.html Did you actually encounter any problems based on this document?
yes，i want use xid as a conditional trace distributed transaction in skywalking

**Comment by a364176773** [comment]
i got ,we will review this pr you submit
