### ISSUE TITLE
fescar-server must run startup script with port

### ISSUE THREAD

**Issue by yiailake** [seata/seata#56]
why not read config from application.conf or have default port 8091? I run startup script without port, because the xid is consists of ipAddress + ":" + port + ":" + tranId and generate value become 192.168.2.170:0:200918724, so the second parameter is 0, means port is 0. the RM connect fescar-server is failure.

**Comment by sharajava** [comment]
it seems to be a bug. can you please try a fix out? thanks 👍

**Comment by leizhiyuan** [comment]
the issue has been fixed, I will close the issue, if you have other questions, please reopen it or create a new one
