### ISSUE TITLE
1.6.1版本 RM回滚TM没有回滚，undo_log中无数据

### ISSUE THREAD

**Issue by loveTtt** [seata/seata#5603]
### 开发环境
> jdk 8、eureka、mysql5.7

### 场景描述
> 事务调用方使用for update查询数据，修改数据后使用jpa的saveAndFlush进行修改，后调用接收方的新增方法对产量进行更新，RM中同意也是使用jpa的saveAndFlush，中途抛出 by zero异常后发现RM的数据回滚成功，调用方修改的数据回滚失败，undo_log中无数据

**Comment by a364176773** [comment]
检查数据源代理和xid传递

**Comment by loveTtt** [comment]
> 检查数据源代理和xid传送

![image](https://github.com/seata/seata/assets/44689736/fc8223a5-1a1c-4fc6-bef5-c788e57664ae)
数据源代理使用的Hikari，xid在TM和RM中都是同一个

**Comment by loveTtt** [comment]
如果把TM中的一些校验删除之后，发现可以正常回滚
