### ISSUE TITLE
Ipv6环境下，io.seata.common.util.NetUtil的toInetSocketAddress方法没办法正确解析ipv6格式的地址

### ISSUE THREAD

**Issue by xiaoqiang-github-123** [seata/seata#5607]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
当seataf服务部署在ipv6环境时，注册到注册中心上的seata服务地址是ipv6形式的，当服务导入seata依赖时，发现如图的这个工具类里对ip地址的解析有问题，会出现截取的host和port不正确

![image](https://github.com/seata/seata/assets/134508814/45ab6d9f-017a-4788-b920-f755bdcee326)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
 i.s.c.r.netty.NettyClientChannelManager  : 0101 can not connect to 2202:0:0:0:0:0:0:133:9908 cause:can not register RM,err:For input string: "0:0:0:0:0:0:133:9908"
io.seata.common.exception.FrameworkException: can not register RM,err:For input string: "0:0:0:0:0:0:133:9908"
....
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8.0_191-b12
- Seata client/server version:  latest
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
@xiaoqiang-github-123 can you submit a PR to fix it？
