### ISSUE TITLE
针对原生sql语句，存在即更新的情况，异常回滚，Seata将更新数据删除

### ISSUE THREAD

**Issue by yjq0529** [seata/seata#5619]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by a364176773** [comment]
把你的sql和seata版本都写清楚

**Comment by yjq0529** [comment]
pgsql：
insert into org(org_id, org_no, org_name)
values (3, '003', '根据org_id不存在即插入')
on conflict(org_id) do update set org_name='根据org_id不存在即更新';

seata版本
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-seata</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
            <version>2.2.0.RELEASE</version>
        </dependency>

**Comment by a364176773** [comment]
你没有列清楚这个seata版本,请写清

**Comment by a364176773** [comment]
insert on update这种sql在1.3以后应该是直接拦截掉非mysql,mariadb的,这个sql目前pg和oracle数据库上at不支持

**Comment by yjq0529** [comment]
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
    <version>2.2.0.RELEASE</version>
    <exclusions>
        <exclusion>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>io.seata</groupId>
    <artifactId>seata-spring-boot-starter</artifactId>
    <version>1.4.2</version>
</dependency>
<dependency>
    <groupId>io.seata</groupId>
    <artifactId>seata-all</artifactId>
    <version>1.4.2</version>
</dependency>

**Comment by yjq0529** [comment]
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
    <version>2.2.0.RELEASE</version>
    <exclusions>
        <exclusion>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.seata</groupId>
            <artifactId>seata-all</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>io.seata</groupId>
    <artifactId>seata-spring-boot-starter</artifactId>
    <version>1.4.2</version>
</dependency>
<dependency>
    <groupId>io.seata</groupId>
    <artifactId>seata-all</artifactId>
    <version>1.4.2</version>
</dependency>

**Comment by yjq0529** [comment]
目前是在AT模式，pgsql出现的问题

**Comment by a364176773** [comment]
> 目前是在AT模式，pgsql出现的问题

可以明确告诉你的是这个sql是不支持的,具体参考官网列举的sql支持范围

**Comment by a364176773** [comment]
![image](https://github.com/seata/seata/assets/19943636/d93d0362-838d-4327-b34d-3f2ec2a26273)
1.4.2发布后才做的处理,也就是1.5以上会拦截下来

**Comment by yjq0529** [comment]
好的

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/user/sqlreference/sql-restrictions.html  AT模式上我们将持续支持更多语句,但并没有那么快,敬请谅解

**Comment by yjq0529** [comment]
好的
