### ISSUE TITLE
1.6.1版本 seata docker指定外部配置文件不生效

### ISSUE THREAD

**Issue by yili001** [seata/seata#5620]
docker run -p 7091:7091 -p 8091:8091 -e SEATA_CONFIG_NAME=file:/root/seata-config/registry -v ./registry.conf:/root/seata-config/registry.conf seataio/seata-server: 1.6.1

registry.conf同级目录下执行docker run，进入到容器内，registry.conf也的确映射进去了

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/ops/deploy-by-docker.html
