### ISSUE TITLE
seata AT模式分库分表事务会报错

### ISSUE THREAD

**Issue by hugohong999** [seata/seata#5635]
1、mysql 分表因子不是主键id，插入数据时本地事务执行成功，拿到id=22;
2、之后发现会遍历所有的分表，查询id=22的数据，因为是分表，所有的表主键都是从0开始递增，所有可能会遇到多个表中都含有id=22的数据；比如100张分表，查到5个表中都含有id=22的数据，此时会报错，会多次重试；
3、最后发起事务的服务发现调用超时回滚；

**Comment by a364176773** [comment]
将代理放到实际的物理datasource中而不是逻辑datasource

**Comment by hugohong999** [comment]
> a364176773
spring:
  datasource:
    dynamic:
      primary: sharding
  shardingsphere:
    datasource:
      names: temp
      temp:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://****:3306/temp?useUnicode=true&characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&useSSL=false&serverTimezone=UTC
        username: root
        password: *****
      tables:
        t_xxx_record:
          actual-data-nodes: tempTables.t_xxx_record_$->{0..99}
          table-strategy:
            standard:
              sharding-column: uid
              precise-algorithm-class-name: com.xxx.shardingjdbc.MyTableXXX

我这里没有分库，只是分表了

**Comment by a364176773** [comment]
反馈给对应的分库分表中间件社区
