### ISSUE TITLE
default.grouplist is required

### ISSUE THREAD

**Issue by slievrly** [seata/seata#5649]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://github.com/seata/seata/assets/8758457/57e17ddc-bc7b-49c1-9594-5a009c6ad700)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```
seata.enabled=true
seata.application-id=applicationName
seata.tx-service-group=default_tx_group
seata.enable-auto-data-source-proxy=true
seata.data-source-proxy-mode=AT
seata.use-jdk-proxy=false

seata.service.vgroup-mapping.default_tx_group=default
seata.service.default.grouplist=127.0.0.1:8091

1.7.0-SNAPSHOT
![image](https://github.com/seata/seata/assets/8758457/754dc843-8591-42c8-8e0e-71bf44e54089)

1.6.1
![image](https://github.com/seata/seata/assets/8758457/3d790317-192b-4914-8660-1c22b423ab9a)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by a364176773** [comment]
![image](https://github.com/seata/seata/assets/19943636/9937489d-f8f5-4542-b869-fe56411b1c70)
![f1def2caf4c70d2892bbf052e51deb37](https://github.com/seata/seata/assets/19943636/5d3ccb47-eec1-490f-93a1-bbc7b99bf230)
I can't reproduce the problem

**Comment by slievrly** [comment]
https://github.com/seata/seata/blob/8e030e679b2f154ac6515af8a5b44a96bbb1c9ac/script/client/conf/file.conf#L57

https://github.com/seata/seata/blob/8e030e679b2f154ac6515af8a5b44a96bbb1c9ac/script/client/spring/application.properties#L61

https://github.com/seata/seata/blob/8e030e679b2f154ac6515af8a5b44a96bbb1c9ac/seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/main/java/io/seata/spring/boot/autoconfigure/properties/client/ServiceProperties.java#L97
