### ISSUE TITLE
Is there a way to support PHP?

### ISSUE THREAD

**Issue by hegoku** [seata/seata#565]
I'm a PHPer, and I read the theory about fescar and find it is nice. So is there a way to use it in PHP or other program language? Thanks!

**Comment by lovepoem** [comment]
https://github.com/alibaba/fescar/issues/348

The discussion is here

**Comment by yuguangmao** [comment]
怎么支持的？

**Comment by yuguangmao** [comment]
How to solve this question？（怎么支持的？）
