### ISSUE TITLE
K8s部署seata1.6.1日志时间错误问题

### ISSUE THREAD

**Issue by yili001** [seata/seata#5650]
K8s部署时，已同步主机时区，进入容器内发现时间也正常，但查看seata启动打印出的日志发现日志时间依然少了8个小时

**Comment by a364176773** [comment]
增加一个环境变量JAVA_OPT=-Duser.timezone=Asia/Shanghai

**Comment by yili001** [comment]
> 增加一个环境变量JAVA_OPT=-Duser.timezone=Asia/Shanghai

增加JAVA_OPTS没用，应该增加 环境变量 JAVA_TOOL_OPTIONS="-Duser.timezone=Asia/Shanghai"，生效的标志是启动时日志第一行会打印出此环境变量
