### ISSUE TITLE
docke 拉取seata latest版本，但是client 跟seata-server版本不一致，数据库表lock_table出现死锁

### ISSUE THREAD

**Issue by VOCTERMA** [seata/seata#5652]
![772ac06de9ae8b3da9b8c7b2411dc8e9](https://github.com/seata/seata/assets/47771073/5fcb180b-76fd-4437-a05f-4c25e8f2bc20)

**Comment by a364176773** [comment]
根据最新的lock_table设置你的表结构和索引

**Comment by VOCTERMA** [comment]
这是因为版本不一致导致的吗？
![image](https://github.com/seata/seata/assets/47771073/84655f24-88b0-4b8a-a1f5-0836fd8a16c3)

**Comment by VOCTERMA** [comment]
谢谢你的解答

**Comment by VOCTERMA** [comment]
根据seata-server:latest docker中查看版本号，确实存在server与client版本不一致的问题
![image](https://github.com/seata/seata/assets/47771073/9c98ae2a-7dbe-4cdd-9d1e-886510e3e8ed)
