### ISSUE TITLE
metrics-api支持type、unit

### ISSUE THREAD

**Issue by stone-98** [seata/seata#5674]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

我注意到seata自定义了相关的metrics-api，发现里面没有关于metrics type、unit的相关定义，是有什么具体原因嘛？
根据我的理解如何seata中的metrics-api如果定义了type、unit，那么通过PrometheusExporter输出到Prometheus也能够有type以及unit属性，目前我看PrometheusExporter导出的指标type是未知的，没有unit的。如下图所示：
![image](https://github.com/seata/seata/assets/35629966/9e5877b1-94ca-4ac8-aaa3-4db4e76fe0d0)

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

metrics-api新增关于type、unit的定义

**Comment by robynron** [comment]
对于`unit`，seata现在版本依赖的`prometheus_client`版本比较低，在此低版本中未引入`unit`定义。后续如果升级了`prometheus_client`至较高版本，这部分缺失的`unit`定义需要补充上。

对于`type`，首先是要明确这个是prometheus定义的`metrics`类型。由于`seata-metrics`是无依赖于`prometheus`的独立的定义，其中`seata-metrics-api`有着自定义的指标定义方式、计算逻辑。对于兼容`prometheus`生态，`seata-metrics`模块只保证从采集结果上兼容`promethues`的接口，与`prometheus`的指标类型（如`Counter`、`Histogram`等）完全解耦，因此这里的`type`也无需与`prometheus`的指标类型关联。
