### ISSUE TITLE
globalSession.closeAndClean()方法有bug

### ISSUE THREAD

**Issue by 412165137lzh** [seata/seata#5681]
（1）源码：seata-server端（注意，我们采用db模式保存事务数据）
DefaultCore.commit(String xid)方法中有如下代码：
```
// Highlight: Firstly, close the session, then no more branch can be registered.
globalSession.closeAndClean();
```
closeAndClean这个方法实际上是将globalSession对象的active变量改为false，注释说修改之后，可以保证其他分支无法再注册到当前全局事务中！

（2）问题：
研究发现，这个方法根本无法实现“保证其他分支无法再注册到当前全局事务”这个功能
原因是虽然actvice变量被volatile修饰，但是在RM注册，调用AbstractCore.branchRegister方法时，该方法会重新new一个新的globalsession，那么此时再校验active就没有任何意义了，这里应该是设计缺陷，是否忘记对globalSession做缓存了？

如有不对请指出，谢谢

**Comment by a364176773** [comment]
缓存了也没用,因为client的负载均衡默认是RandomLoadBalance或XID,如果是xid那么缓存了有一点意义,如果配置成了RandomLoadBalance begin和commit以及中间的registry都不是一个tc,缓存了也没意义还有一致性问题,xid的话如果该begin的tc重启或者销毁重建了,就会降级为随机,依旧是存在上面说的问题,缓存这个事情社区讨论过,如果是xid负载均衡,下游及tm节点找不到这个xid对应的tc时抛异常来解决缓存不一致的问题的话可用性受到损害,不抛异常降级位随机的话缓存一致性不好做.
你说的问题1和2在file和raft模式是不会出现的,只有存算分离架构如db,redis才会遇到,本身概率也非常低,所以社区采用了保守的方式,在commit和rollback后2分10秒才会去删除这个commit,而删除动作就是retry二阶段的动作,就会将你说的如果在close后还有分支注册上来的情况进行兜底,正确的执行二阶段动作

**Comment by 412165137lzh** [comment]
了解，感谢。


本来想了另一个方案，但是应该不行：
DefaultCore.commit方法中，修改一下逻辑，一开始只查询global_table数据，不查branch，然后再修改全局状态为commiting/AsyncCommitting，接着才查询branchList数据，这样可以解决二阶段提交时中途注册的问题，但是又引发另一个问题，就是比如XA模式是先注册分支，再执行sql的，所以在TC通知RM进行branchCommit的时候，XA事务可能还处于start阶段，XA重试失败超时一定时间，会强制改为PhaseTwo_Committed

**Comment by 412165137lzh** [comment]
> 缓存了也没用,因为client的负载均衡默认是RandomLoadBalance或XID,如果是xid那么缓存了有一点意义,如果配置成了RandomLoadBalance begin和commit以及中间的registry都不是一个tc,缓存了也没意义还有一致性问题,xid的话如果该begin的tc重启或者销毁重建了,就会降级为随机,依旧是存在上面说的问题,缓存这个事情社区讨论过,如果是xid负载均衡,下游及tm节点找不到这个xid对应的tc时抛异常来解决缓存不一致的问题的话可用性受到损害,不抛异常降级位随机的话缓存一致性不好做. 你说的问题1和2在file和raft模式是不会出现的,只有存算分离架构如db,redis才会遇到,本身概率也非常低,所以社区采用了保守的方式,在commit和rollback后2分10秒才会去删除这个commit,而删除动作就是retry二阶段的动作,就会将你说的如果在close后还有分支注册上来的情况进行兜底,正确的执行二阶段动作


了解，感谢。

本来想了另一个方案，但是应该不行：
DefaultCore.commit方法中，修改一下逻辑，一开始只查询global_table数据，不查branch，然后再修改全局状态为commiting/AsyncCommitting，接着才查询branchList数据，这样可以解决二阶段提交时中途注册的问题，但是又引发另一个问题，就是比如XA模式是先注册分支，再执行sql的，所以在TC通知RM进行branchCommit的时候，XA事务可能还处于start阶段，XA重试失败超时一定时间，会强制改为PhaseTwo_Committed

**Comment by 412165137lzh** [comment]
close
