### ISSUE TITLE
你们这个Seata的bug实在是太多了，我们这又短期内没办法去掉，我能否用你们最新分支2.x的代码自己打包服务端和客户端？

### ISSUE THREAD

**Issue by xbox1994** [seata/seata#5687]
1. 有什么风险么？
2. 需要改数据库么？
3. 具体操作是？

**Comment by a364176773** [comment]
什么bug，是否其他版本没有这个bug？不升级是否可回退？

**Comment by xbox1994** [comment]
> 什么bug，是否其他版本没有这个bug？不升级是否可回退？

我们目前生产环境用的1.4.1，存在非常多的seata异常，跟踪源码还有问你之后发现很多是seata的bug，比如不加@Transactional会脏写的bug，还有我没排查出来的疑似全局锁没控制住导致脏写的bug。
所以我想你们高版本应该bug会少点，结果我用1.6.1的时候有这个https://github.com/seata/seata/issues/5676  跟 这个https://github.com/seata/seata/pull/5307 bug
特别是这个5307的pull这么明显的bug会导致我不可能将seata用到生产环境，所以我现在到底是应该
1. 在1.6.1的基础上将这个pull给手动加到1.6.1源码自己打包，然后再碰到问题之后再手动加源码打包
2. 还是应该用你们最新分支的2.x的代码直接打包？我实在是太怕我升级到2.x之后又碰到2.x版本里新写的bug

我实在不想再自己排查源码再跟提一些重复的问题了，太费时间和感情了，我不期待seata最新版本把bug解决完，我只想要一个生产环境比较稳定的版本。

**Comment by xbox1994** [comment]
@a364176773

**Comment by a364176773** [comment]
你说的第一个不是bug，第二个用1.4.2或1.5.2

**Comment by xbox1994** [comment]
> 你说的第一个不是bug，第二个用1.4.2或1.5.2

不敢用低版本，低版本碰到bug之后又要我用高版本？高版本碰到bug退到低版本？死循环啊

**Comment by xbox1994** [comment]
我准备在1.6.1的基础上将这个pull给手动加到1.6.1源码自己打包，然后再碰到问题之后再手动加源码打包。
看起来应该比较稳，可以避免低版本的bug，也避免了最新版本可能新引入的bug，还能解决我碰到的https://github.com/seata/seata/pull/5307 bug

**Comment by xbox1994** [comment]
> 我准备在1.6.1的基础上将这个pull给手动加到1.6.1源码自己打包，然后再碰到问题之后再手动加源码打包。 看起来应该比较稳，可以避免低版本的bug，也避免了最新版本可能新引入的bug，还能解决我碰到的#5307 bug

已验证，无效，准备使用1.5.2
