### ISSUE TITLE
seata注册到nacos端口问题

### ISSUE THREAD

**Issue by dpc-graduate** [seata/seata#5698]
seata注册到nacos的端口 是server.port 加1000，这样的话与spring-boot-starter-actuator 集成时，actuator 的服务端会读取nacos中注册的ip+端口，seata报错
因为actuator 暴露出的地址是 ip+7091，但是actuator 读取的是注册到nacos中的ip+端口（8091），导致在actuator 控制台看seata状态是离线。seata控制台报错：Decode frame error, cause: Adjusted frame length exceeds 8388608: 539976035 - discarded

**Comment by slievrly** [comment]
seata console port: 7091
seata service to client port: 8091

"Decode frame error, cause: Adjusted frame length exceeds 8388608: 539976035 - discarded" cause is that the non-Seata-client connects to port 8091 of the seata-server.

**Comment by dpc-graduate** [comment]
这样的话是代表seata在注册到nacos的情况下无法集成spring-boot-starter-actuato吗，

**Comment by slievrly** [comment]
@dpc-graduate Is it the actuator's adaptation to seata-server?  
ref   https://github.com/seata/seata/pull/4737/files

**Comment by dpc-graduate** [comment]
谢谢！
