### ISSUE TITLE
Is dubbo necessary component?

### ISSUE THREAD

**Issue by leenux** [seata/seata#57]
Is importing dubbo must?
If I don't want to use dubbo,what will I do?
Are there plans to support grpc or Kafka in the future?

**Comment by sharajava** [comment]
No. Dubbo is not required. You can find how to propagate XID in your RPC framework in com.alibaba.fescar.dubbo.TransactionPropagationFilter.

Actually, using RootContext API can adapt to any RPC framework. But, application should be Java based by now.

gRPC or Kafka support is not taken into plan yet. You're strongly welcomed to share your requirements in detail. Let's see if we can get a way.
