### ISSUE TITLE
K8s 部署 seata1.6.0 报错  io.seata.server.console.service.BranchSessionService 

### ISSUE THREAD

**Issue by kee-kuang** [seata/seata#5702]
以下是我的yml 文件，能看出是哪里出了问题吗：
![image](https://github.com/seata/seata/assets/73287461/fc2b2b9c-105d-4c15-9803-8587880c3456)
![image](https://github.com/seata/seata/assets/73287461/ea591b56-69b8-46ad-9a3a-e23aa97a59f9)
![image](https://github.com/seata/seata/assets/73287461/7648627c-172f-4ec6-ae77-33c83badfee6)

**Comment by a364176773** [comment]
nacos中的store.mode配置了吗

**Comment by kee-kuang** [comment]
在nacos上已经配置了

**Comment by a364176773** [comment]
这个很明显是没有读到store.mode导致无法加载到对应的bean,检查你的nacos配置项是否能被seata-server读取到

**Comment by a364176773** [comment]
建议你直接换1.7的镜像,是哪种配置注册中心,storemode是什么都会直接打印日志
