### ISSUE TITLE
docker 运行 seata-1.7.0版本 连接nacos被拒

### ISSUE THREAD

**Issue by ArexdOr** [seata/seata#5703]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

#### 我的 `seata` 本地配置文件如下：
<img width="1431" alt="image" src="https://github.com/seata/seata/assets/81457763/8523607c-a0ce-4e93-a151-2b799041d309">

#### 我的 `nacos` 配置文件如下：
<img width="1605" alt="image" src="https://github.com/seata/seata/assets/81457763/430806dc-3e7b-48c0-911f-a851e4e8fc21">

#### `nacos` 版本是 `2.2.1`。docker指令：
<img width="1880" alt="image" src="https://github.com/seata/seata/assets/81457763/baa706b8-6789-4a0d-b50f-bd7ef58d393d">

#### log报错：
<img width="1901" alt="image" src="https://github.com/seata/seata/assets/81457763/c6810a95-9d8e-4365-810f-a5ee42a1f8a8">

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  `1.7.0`
- Nacos server version: `2.2.1`
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
@ArexdOr What is the nacos-server version?

**Comment by ArexdOr** [comment]
2.2.1。我记得我在描述中写过版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月6日(周四) 中午11:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [seata/seata] docker 运行 seata-1.7.0版本 连接nacos被拒 (Issue #5703)




 
@ArexdOr What is the nacos-server version?

**Comment by slievrly** [comment]
It is confirmed that NacosRegistryServiceImpl only adds a commit in 1.7.0 compared to 1.6.1 and does not involve service registration.

![image](https://github.com/seata/seata/assets/8758457/33cd20f4-0670-4f09-ba6a-6211bd50308e)

**Comment by ArexdOr** [comment]
> It is confirmed that NacosRegistryServiceImpl only adds a commit in 1.7.0 compared to 1.6.1 and does not involve service registration.
> 
> ![image](https://user-images.githubusercontent.com/8758457/251330886-33cd20f4-0670-4f09-ba6a-6211bd50308e.png)

好吧，我明天再测试一次

**Comment by slievrly** [comment]
@ArexdOr Any feedback?

**Comment by ArexdOr** [comment]
> @ArexdOr Any feedback?
我今天试了一次1.7的版本，还是出现连接问题。日志如下图：
<img width="1505" alt="image" src="https://github.com/seata/seata/assets/81457763/eb4bbe91-1167-4c88-a05b-9388f1e49b5c">
ui界面：
<img width="1913" alt="image" src="https://github.com/seata/seata/assets/81457763/0feeb42b-a6c5-4efb-b1e0-3d435ea735b3">
docker暴露容器ip：
<img width="1448" alt="image" src="https://github.com/seata/seata/assets/81457763/1a062589-f8b0-4b0f-81ab-4bc2964973c0">

**Comment by ArexdOr** [comment]
> > @ArexdOr Any feedback?
> > 我今天试了一次1.7的版本，还是出现连接问题。日志如下图：
> 
> <img alt="image" width="1505" src="https://user-images.githubusercontent.com/81457763/251631979-eb4bbe91-1167-4c88-a05b-9388f1e49b5c.png"> ui界面： <img alt="image" width="1913" src="https://user-images.githubusercontent.com/81457763/251632049-0feeb42b-a6c5-4efb-b1e0-3d435ea735b3.png"> docker暴露容器ip： <img alt="image" width="1448" src="https://user-images.githubusercontent.com/81457763/251632120-1a062589-f8b0-4b0f-81ab-4bc2964973c0.png">

我什么都没有改动，只是在docker运行1.6.1版本seata。两个版本使用的配置文件都是一样的，1.6.1版本一切正常。ui界面也没有报错。
<img width="1415" alt="image" src="https://github.com/seata/seata/assets/81457763/1687d8a2-e34d-4f74-a6f4-33e98149c021">

**Comment by slievrly** [comment]
2.2.1 image not found.
![image](https://github.com/seata/seata/assets/8758457/1944bff1-cacd-4535-ab95-3773b0e2f2c3)

**Comment by slievrly** [comment]
It's been reproduced. Thank you very much.

**Comment by slievrly** [comment]
@ArexdOr The new image has been updated with the original docker tag to solve this issue, you can pull down the new image to try to see if the issue is solved, note that the original image needs to be deleted or force update.

---

新的image使用原来的docker tag已经更新解决这个问题，你可以拉取下新的镜像尝试下看是否解决了问题，注意需要删除原镜像或force update.

**Comment by slievrly** [comment]
Due to the long time no reply temporarily closed, if necessary, please re-reopen.
