### ISSUE TITLE
1.7.0 版本  orcal 数据 beforImage 方法 标识符无效

### ISSUE THREAD

**Issue by wawua** [seata/seata#5719]
执行insert语句时  beforImage 方法生成的 sql 加了双引号 会导致 sql 执行标识符无效

![image](https://github.com/seata/seata/assets/49055426/49d19902-4de5-40d9-8491-28e892e2c66e)

报错

![image](https://github.com/seata/seata/assets/49055426/f9989749-f6e2-4767-a26f-bd67d29b7c6b)

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 
- Seata client/server version:  client 1.7.0 1.7.0-native-rc2  server 1.7.0
- Database version: orcal   11.2.0.1.0

**Comment by a364176773** [comment]
insert sql不会有beforeimage
update在oracle中的before image中只有关键字或在数据库中的列名就是小写的才会加上""，你能发一下你的表结构和原sql吗？

**Comment by a364176773** [comment]
![image](https://github.com/seata/seata/assets/19943636/e280dbfc-55d5-481f-b9d3-ce9c66f93c51)
![image](https://github.com/seata/seata/assets/19943636/a6123b4e-cac2-4b17-ba5a-2e394ea0ece8)
![image](https://github.com/seata/seata/assets/19943636/85ae9fb9-e737-4599-b7d1-bc62d835093f)

**Comment by a364176773** [comment]
如果你的列名本身是大写，你可以看下OracleTableMetaCache#resultSetMetaToSchema 118行里你的columnname到底是大写还是小写，是否与库中表column不同

**Comment by slievrly** [comment]
@wawua Pls provides table structure and SQL statements.

**Comment by wawua** [comment]
> resultSetMetaToSchema



> insert sql不会有beforeimage update在oracle中的before image中只有关键字或在数据库中的列名就是小写的才会加上""，你能发一下你的表结构和原sql吗？

这是我的表结构，orcal 中字段都是大写的

CREATE TABLE "KFXT_PDKF_TEST"."PATIENT" (
  "ID" NUMBER(11,0) NOT NULL,
  "CODE" NVARCHAR2(64),
  "NAME" NVARCHAR2(32),
  "ID_CARD_TYPE" NUMBER(11,0),
  "ID_CARD" NVARCHAR2(32),
  "BIRTHDAY" DATE,
  "SEX" NUMBER(11,0),
  "TEL" NVARCHAR2(32),
  "NATION" NVARCHAR2(64),
  "ADDRESS" NVARCHAR2(255),
  "MARRIAGE" NUMBER(11,0),
  "OCCUPATION" NVARCHAR2(255),
  "CREATE_TIME" DATE,
  "UPDATE_TIME" DATE,
  "IS_DELETE" NUMBER(4,0) DEFAULT 0    NOT NULL,
  "AGE" NUMBER
);
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."ID" IS '患者主表';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."CODE" IS '患者编码';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."NAME" IS '姓名';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."ID_CARD_TYPE" IS '证件号类型';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."ID_CARD" IS '证件号';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."BIRTHDAY" IS '出生日期';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."SEX" IS '性别 1.男 2.女 参考EnumEmployeeSex';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."TEL" IS '联系方式';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."NATION" IS '民族';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."ADDRESS" IS '联系地址';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."MARRIAGE" IS '婚姻状况 参考EnumPersonalMarriage';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."OCCUPATION" IS '职业';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."UPDATE_TIME" IS '更新日期';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."IS_DELETE" IS '是否删除 1.是';
COMMENT ON COLUMN "KFXT_PDKF_TEST"."PATIENT"."AGE" IS '年龄';

ALTER TABLE "KFXT_PDKF_TEST"."PATIENT" ADD CONSTRAINT "SYS_C00105612" PRIMARY KEY ("ID");

这是执行的SQL

### SQL: UPDATE patient  SET code=?, name=?,  id_card=?, birthday=?, age=?, sex=?, tel=?,   marriage=?,  create_time=?, update_time=?  WHERE id=?  AND is_delete=0

**Comment by wawua** [comment]
> resultSetMetaToSchema
数据库中取出来是大写的字段
![image](https://github.com/seata/seata/assets/49055426/3456549f-d7d0-4c64-855b-3fcd6c694a67)
col.getColumnName(）取出来的是小写
![image](https://github.com/seata/seata/assets/49055426/8790bcab-9317-42c6-80b4-e29be03a6d49)

**Comment by a364176773** [comment]
![image](https://github.com/seata/seata/assets/19943636/d529c637-4854-4709-a7f4-2a41840ee4a8)
你看下这里是从rsColumns读到的是大写还是小写

**Comment by a364176773** [comment]
把下面map里的columnmeta打开给我看下具体的内容，主要是casesensitive是不是false，如果是false理论上是不会加转义符的
OracleEscapeHandler你能debug这个类的checkIfNeedEscape中的534行吗，也就是
 return columnMeta.isCaseSensitive();  这一行的结果是什么

**Comment by slievrly** [comment]
![image](https://github.com/seata/seata/assets/8758457/ca35b23f-d68e-46c8-86db-1fb5b242c3b1)

**Comment by slievrly** [comment]
oracle 12c

**Comment by wawua** [comment]
> casesensitive

我的columnmeta 对象里面没有 casesensitive属性

![image](https://github.com/seata/seata/assets/49055426/c7156a59-b754-4d05-96b2-7d51b05c539d)

![image](https://github.com/seata/seata/assets/49055426/3b2d69d9-adb0-4bbc-92af-6c17b5ba0cae)

**Comment by a364176773** [comment]
你版本不对，你要用1.7.0，不是rc2那个

**Comment by wawua** [comment]
更换1.7.0后不会有这问题了， 感谢 @slievrly @a364176773
