### ISSUE TITLE
seata 1.5.2服务端nacos报错: use https

### ISSUE THREAD

**Issue by xbox1994** [seata/seata#5724]
服务端的节点已经在nacos上注册成功了，这个服务端的日志报错可以忽略吗？我们的nacos只有http的链接。

02:29:29.609 ERROR --- [cos.client.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":400,"message":"Use HTTPS\n","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Content-Length":"10","Content-Type":"text/plain; charset=utf-8","Date":"Thu, 13 Jul 2023 02:29:29 GMT","X-Content-Type-Options":"nosniff"},"originalResponseHeader":{"Content-Length":["10"],"Content-Type":["text/plain; charset=utf-8"],"Date":["Thu, 13 Jul 2023 02:29:29 GMT"],"X-Content-Type-Options":["nosniff"]},"charset":"UTF-8"}}

**Comment by a364176773** [comment]
请咨询nacos社区
