### ISSUE TITLE
出现分布式事务失效问题，分布式事务部分失效问题

### ISSUE THREAD

**Issue by tyza66** [seata/seata#5725]
- [X] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

- 在项目中出现了分布式事务失效的问题（分布式事务调用放在了controller层）
- 在重新编写的项目（删掉原来写的模块，新建了一个模块，并且将分布式事务改到了service层）中

### Ⅱ. Describe what happened
- 在项目中出现了分布式事务失效的问题
- 在其他测试项目中一切正常，说明环境一切正常：https://github.com/tyza66/SeataReview-Dubbo
- 在这个项目版本中就是不行，分布式事务注解没有生效，甚至在AT模式下不创建undo_log表也没报错https://github.com/tyza66/GoldenShovelShop/tree/5e02dd351b096ac5a58978bc8d957e4a94c23f25/GoldenShovelShop-SC
- 猜测是MyBatisPlus、Knife4j等等其他依赖的问题，删除依赖后仍然这样
- 出现在分布式事务方法*调用的地方*使用RootContext.getXID()直接就是null的情况
- 重新建立模块后重新搭建之后RootContext.getXID()有值了，但是之发生了部分事务回滚，修改的信息恢复了，插入的信息没有删除

### Ⅲ. Describe what you expected to happen
- 正常情况下事务失败应该进行完整的回滚

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:  1.3.0
- Database version: 8+
- OS(e.g. `uname -a`): windows-11

**Comment by slievrly** [comment]
Whether there is minimal reproducible code for uncoupled project code ？

**Comment by tyza66** [comment]
There is no minimum repeatability code in the part I wrote myself, I simply referenced the Mapper generated with the assistance of MyBatis Plus for use. I have been using MyBatis Plus to directly implement the operations of the Dao layer, perhaps due to its lack of understanding of its source code, and I am not sure if there is minimal repeatability code in it.

**Comment by a364176773** [comment]
检查数据源代理，以及你的orm到底有没有使用你代理的数据源
