### ISSUE TITLE
SpringBoot版本2.7，Seata版本1.7.0，AT事务回滚失败问题

### ISSUE THREAD

**Issue by ChienSun666** [seata/seata#5734]
### Ⅰ. Issue Description
SpringBoot版本2.7，Seata版本1.7.0，AT事务回滚失败问题。
因为驱动返回的字段是大写，seata缓存中的字段是小写，回滚的时候，主键判断没有忽略大小写，回滚时无法匹配到pk，导致delete语句不完整。

错误sql：delete from table where 

### Ⅱ. Describe what happened
A -> B服务，B服务insert一条数据成功，然后A服务报异常，B服务回滚的时候回滚失败。

### Ⅲ. Describe what you expected to happen
<img width="1479" alt="1" src="https://github.com/seata/seata/assets/136292070/a8ac6d8e-1c7b-4505-b149-42bf799982c6">
<img width="1650" alt="2" src="https://github.com/seata/seata/assets/136292070/f9746bc3-6089-4f54-bc0e-6a3df9f88ec1">
<img width="1605" alt="3" src="https://github.com/seata/seata/assets/136292070/8ffe6cc1-eb94-4338-8dc8-1d0c202b9b17">
<img width="1678" alt="4" src="https://github.com/seata/seata/assets/136292070/2ffbf8d4-b954-4500-be18-a277d914e783">
<img width="1508" alt="5" src="https://github.com/seata/seata/assets/136292070/fb081997-3c0f-4bea-b01f-1671a0e2fe15">
<img width="1148" alt="6" src="https://github.com/seata/seata/assets/136292070/96e6cdf8-9526-4950-8a2f-f60661c6e445">

### Ⅵ. Environment:

- JDK version 1.8
- Seata client/server version:   1.7.0
- Database version: mysql8

**Comment by capthua** [comment]
plz assign to me，3q
