### ISSUE TITLE
On the issue of fescar server crash transaction recovery

### ISSUE THREAD

**Issue by XCXCXCXCX** [seata/seata#574]
I have read the official documents and recommended blogs of fescar, and I have read some of the source code of fescar myself. I have some questions to discuss:

1. The current version does not yet support the fescar server cluster? The data synchronization between cluster nodes is not found in the source code. If this is the case, the global transaction file for the crashed node may not be restored normally, and a new global transaction is also enabled.

2. fescar's global transaction will be stored in memory + asynchronous write file, but the global lock is only stored in memory, restarted in the server node, if there is a new global transaction open during the crash transaction recovery, will there be data inconsistency?

**Comment by slievrly** [comment]
1. currently it's a single server node， file mode can set rws
2. when restarted server node，global lock also recovery based on unfinished transaction operation

**Comment by XCXCXCXCX** [comment]
Thanks for the reply, looking forward to the development of the cluster model

**Comment by leizhiyuan** [comment]
wait for this pr https://github.com/seata/seata/pull/942
