### ISSUE TITLE
Seata-discovery-nacos是否有必要将依赖的nacos-sdk升级至2.x

### ISSUE THREAD

**Issue by Bo-Qiu** [seata/seata#5741]
## Why you need it?
 当前seata依赖的nacos-client版本是<nacos-client.version>1.4.2</nacos-client.version>，版本较低，注册发现使用的是http、订阅使用的udp，是否有必要升级至2.x版本，以支持grpc的方式实现注册发现和订阅。

## How it could be?
调整seata-discovery-nacos模块，使用nacos-2.x版本

**Comment by slievrly** [comment]
Currently, nacos-client 1.x is compatible with nacos-server 2.x. The maven scope for service discovery is declared as provided, which is actually the version of nacos-client on the business side. For seata-server, 1.4.2 is used, and the scale of service registration is relatively small, so I think the status quo can be maintained.

---

目前nacos-client 1.x是兼容nacos-server 2.x的。对于服务发现的maven scope声明为provided，实际为业务侧的nacos-client版本。对于seata-server使用的是1.4.2，对于服务注册的量级比较小，我认为可保持现状。
