### ISSUE TITLE
SpringBoot 2.4 + SpringDataJpa + PostgreSQL 12.x + Identity主键的问题

### ISSUE THREAD

**Issue by wnwnfgx** [seata/seata#5746]
在Entity中的自增主键定义为
    
@Id
@GeneratedValue(strategy= GenerationType.IDENTITY)
private Long id;

Jpa会自动创建表的序列和主键Id列（类型为 serial8 ）。SpringDataJpa在insert数据时不会写入id列的值，导致Seata AT模式在insert数据时报错 ：io.seata.common.exception.ShouldNeverHappenException: pkIndex is not found

**Comment by wnwnfgx** [comment]
![image](https://github.com/seata/seata/assets/7233809/938e362e-7401-4ecd-b41f-7b71c8030b3f)
确定是有的

**Comment by wnwnfgx** [comment]
如果Entity中的id列定义成这样就没有问题，但太多地方要修改了，是否seata不支持postgresql的serial自增主键呢？

**Comment by wnwnfgx** [comment]
升级到1.7.0就可以了

**Comment by a364176773** [comment]
当时支持多主键上有个bug，导致不读自增主键，你尝试升级1.7看看
