### ISSUE TITLE
为什么k8s启动的时候总是报端口被占用

### ISSUE THREAD

**Issue by chenshao98** [seata/seata#5754]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seata-server
  namespace: basic
  labels:
    k8s-app: seata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: seata-server
  template:
    metadata:
      labels:
        k8s-app: seata-server
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: seata-server
          image: docker.io/seataio/seata-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SEATA_CONFIG_NAME
              value: file:/root/seata-config/registry
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: seata-config
              mountPath: /root/seata-config
      volumes:
        - name: seata-config
          configMap:
            name: seata-server-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-server-config
  namespace: basic
data:
  registry.conf: |
    registry {
        type = "nacos"
        nacos {
          application = "seata-server"
          serverAddr = 
          namespace = 
          username = "nacos"
          password = 

        }
    }
    config {
      type = "nacos"
      nacos {
          serverAddr = 
          namespace = 
          username = "nacos"
          password = 
          dataId =  
          group = "DEFAULT_GROUP"
      }
    }
这个是我的启动文件

**Comment by a364176773** [comment]
自行检查是否有定义了spring的server.port导致于netty端口冲突，之前有个用户就是全局配置了个env

**Comment by chenshao98** [comment]
我没有配env，啥也没指定都起不来

**Comment by a364176773** [comment]
那你指定一个env SEATA_PORT=8092  试试

**Comment by chenshao98** [comment]
指定端口可以启动，如果不指定端口就会报错端口被占用，这个是不是bug呢

**Comment by chenshao98** [comment]
![image](https://github.com/seata/seata/assets/139935802/5600fd60-ee6c-4a58-9ab4-15b609af09b9)

![image](https://github.com/seata/seata/assets/139935802/01460777-7e0e-4ad1-97bb-f87ddaba7b1a)

**Comment by a364176773** [comment]
> 指定端口可以启动，如果不指定端口就会报错端口被占用，这个是不是bug呢

不是bug,你自己启动后进容器查看env,和启动参数的区别,没有这种问题,肯定是哪里指定了冲突的端口导致的

**Comment by tanyaofei** [comment]
k8s默认会创建 `Deployment` 和 `Service` 定义的端口号作为环境变量，格式是 `<deployment 名>_PORT` 和 `<Service 名>_PORT` ，刚好 `Service` 叫 `seata-server`, 所以就叫 `SEATA_SERVER_SERVICE_PORT`，刚好被 `seata` 用了，于是冲突
