### ISSUE TITLE
seata1.7在获取表索引基数时，由于我们表数据量太大，超过了int最大值

### ISSUE THREAD

**Issue by runtimeEX** [seata/seata#5761]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
io.seata.sqlparser.struct.IndexMeta中的private int cardinality;需要修改为long类型

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
fixed #5762
