### ISSUE TITLE
seata1.7.0。mysql8

### ISSUE THREAD

**Issue by yangrenjie1995** [seata/seata#5763]
请教大佬，我在标记全局事务的方法里调的feign接口。这个接口里的方法如果标记@Transactional。全局事务回退成功，分支事务回退不生效。感觉没注册上分支。
不标记@Transactional。他会生效，日志也显示注册上。并且回退成功。FAQ22。这个feign接口标记Transactional算内层还是外层呢。没看明白
![image](https://github.com/seata/seata/assets/33629033/370486d8-b4bd-4c26-9a9d-7baa9a0c98a9)

![image](https://github.com/seata/seata/assets/33629033/5484533a-5c56-48e6-b780-00aa1951bbae)

**Comment by a364176773** [comment]
检查分支的xid传递和数据源代理
