### ISSUE TITLE
I am going to conduct local testing. Is there any official website recommended?

### ISSUE THREAD

**Issue by ordinaryShen** [seata/seata#577]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
run sample testing？https://github.com/fescar-group/fescar-samples

**Comment by ordinaryShen** [comment]
I am going to deploy the fescar-server to the Linux server for testing. I don't know if fescar-server has high requirements for cpu and memory. Is there a recommended host configuration?

**Comment by ordinaryShen** [comment]
Beside, Could I deploy fescar-server based on the docker container

**Comment by slievrly** [comment]
> Beside, Could I deploy fescar-server based on the docker container

https://github.com/fescar-group/fescar-docker

**Comment by slievrly** [comment]
> I am going to deploy the fescar-server to the Linux server for testing. I don't know if fescar-server has high requirements for cpu and memory. Is there a recommended host configuration?

>2G mem?
