### ISSUE TITLE
Seeking help about seata error "service.vgroupMapping.default_tx_group"

### ISSUE THREAD

**Issue by Demonor1995** [seata/seata#5774]
Windows
jdk1.8.0
nacos 2.1.2
seata-server-1.7.0

    These days I want to use seata in my project, but occured an error which could not solve it even though I try to find the solution on www.baidu.com, so I want to seek help here, could you please help me?
my config are as follows:
**1. seata\script\config-center\config.txt**, all config in this file has been uploaded to nacos, I just modify store.mode=db and db config, and service.default.grouplist=192.168.1.105:8091
**2. seata\conf\application.yml**

> seata:
        config:
        type: nacos
        nacos:
        server-addr: 192.168.1.105:8848
        namespace:
             group: SEATA_GROUP
        username: nacos
        password: nacos
        context-path:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.105:8848
      group: SEATA_GROUP
      namespace:
      cluster: default
      username:
      password:
      context-path:

**3. my project application.properties**
>seata.data-source-proxy-mode=AT
seata.tx-service-group=default_tx_group
seata.registry.type=nacos
seata.registry.nacos.server-addr=192.168.1.105:8848
seata.registry.nacos.group=SEATA_GROUP
seata.registry.nacos.cluster=default
seata.config.type=nacos
seata.config.nacos.server-addr=192.168.1.105:8848
seata.config.nacos.group=SEATA_GROUP
seata.config.nacos.username=nacos
seata.config.nacos.password=nacos

When I start my project, occured error:
main] .s.s.a.d.SeataAutoDataSourceProxyCreator: Auto proxy of [druid]
main] com.alibaba.druid.pool.DruidDataSource: {dataSource-1} inited
main] i.s.c.r.netty.NettyClientChannelManager: can not get cluster name in registry config 'service.vgroupMapping.default_tx_group', please make sure registry config correct

Could you please give me some suggestions?

**Comment by slievrly** [comment]
In nacos `service. vgroupMapping. default_tx_group` configuration value is what?

**Comment by Demonor1995** [comment]
> In nacos `service. vgroupMapping. default_tx_group` configuration value is what?

service.vgroupMapping.default_tx_group=default

> In nacos `service. vgroupMapping. default_tx_group` configuration value is what?

oh , I make a mistake when I upload seata/srcipt/config-center/config.txt, what my command is :
[root@localhost nacos]# sh nacos-config.sh -h 192.168.37.129 -p 8848 -g SEATA_GROUP -u nacos -w nacos
set nacosAddr=192.168.37.129:8848
set group=SEATA_GROUP
Set transport.type=TCP successfully 
Set transport.server=NIO successfully 

nacos host should be 192.168.1.105, although it will sync config from db which uploaded by 192.168.37.129
Anyway,thanks !

**Comment by a364176773** [comment]
service.vgroupMapping.default_tx_group=default放到nacos上
