### ISSUE TITLE
TM 的状态是回滚了，两哥服务之间的xid也是一样，为什么事务还没有生效

### ISSUE THREAD

**Issue by tanxinwu** [seata/seata#5793]
TM [192.168.1.110:8091:2020103100] rollback status: Rollbacked
RM  c.a.c.seata.web.SeataHandlerInterceptor  : xid in change during RPC from 192.168.1.110:8091:2020103097 to null

**Comment by a364176773** [comment]
https://seata.io/zh-cn/docs/overview/faq.html
