### ISSUE TITLE
nacos服务识别错误seata-server的IP地址

### ISSUE THREAD

**Issue by TerMinalTEL** [seata/seata#5796]
用docker部署seata-server，seata-server成功启动，但是nacos服务列表的IP地址是容器的ip地址而不是虚拟机的IP地址，然后client就没法启动，但是在Windows中启动seate就没有这个问题，IP地址没有任何问题

**Comment by slievrly** [comment]
add env  SEATA_IP=虚拟机的IP

**Comment by TerMinalTEL** [comment]
> add env SEATA_IP=虚拟机的IP

试过了，host和bridge模式也试过了，还是不行

**Comment by slievrly** [comment]
Please take a screenshot.

**Comment by TerMinalTEL** [comment]
> > add env SEATA_IP=虚拟机的IP
> 
> 试过了，host和bridge模式也试过了，还是不行

从头开始弄一遍再用host模式又好了
