### ISSUE TITLE
1.7.0这个配置属性 写不写有什么区别server.enableParallelRequestHandle

### ISSUE THREAD

**Issue by xiaoyuwang1987** [seata/seata#5798]
如果配置文件没写这个属性server.enableParallelRequestHandle，客户端并发上去会不会在报rpc time out

**Comment by slievrly** [comment]
the default value is true. The batch messages merged on the client side can be processed in parallel on the server side, depending on the processing capability of the server side.

**Comment by a364176773** [comment]
1.6.x中存在一个bug会在合并请求时数组越界导致rpctimeout，1.7上修复了这个问题
