### ISSUE TITLE
咨询：seata1.7.0支持国产数据库人大金仓吗？

### ISSUE THREAD

**Issue by yangrenjie1995** [seata/seata#5799]
看文档上写。AT模式支持的数据库有：MySQL、Oracle、PostgreSQL、 TiDB、MariaDB。如果想支持该如何适配。

**Comment by slievrly** [comment]
currently not support . For the adaptation, see the rm-datasource module.

**Comment by vincent50411** [comment]
请问，是server端不支持 还是client sdk不支持呢？

**Comment by liuqiufeng** [comment]
> 请问，是server端不支持 还是client sdk不支持呢？

都不支持
