### ISSUE TITLE
Link failure in the Alibaba Open Source Distributed Transaction Solution FESCAR document

### ISSUE THREAD

**Issue by acodeman** [seata/seata#58]
In the first chapter, the text "Pattern: Database per service" is invalid.
// 第一章节中 文字“Pattern: Database per service” 关联的链接失效
![image](https://user-images.githubusercontent.com/7656171/51023388-c507b980-15c1-11e9-85c0-ccf130b4b4e9.png)

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by Lykosteng** [comment]
thanks acodeman

**Comment by xingfudeshi** [comment]
Thanks for reporting.That link has been fixed.
