### ISSUE TITLE
关于undo_log中rollback_info19位id精度丢失问题

### ISSUE THREAD

**Issue by xuxuhui** [seata/seata#5806]
Ⅰ. Issue Description
seata版本1.4.2
数据库mysql
业务中的id是19位的保存到undo_log中的rollback_info中id精度丢失

Ⅱ. Describe what happened
业务中的ID是1694991816469950466 保存到undo_log中的rollback_info中后为1694991816469950500
<img width="792" alt="image" src="https://github.com/seata/seata/assets/10111609/54812acb-3e35-4c91-a09c-21bd9074ddc0">

**Comment by a364176773** [comment]
升级到最新版
