### ISSUE TITLE
tcc模式,事务成功后,到控制台查看,一直是committing状态,等一段时间才会正常

### ISSUE THREAD

**Issue by dayu521** [seata/seata#5837]
参考官网博客的[教程](https://seata.io/zh-cn/blog/integrate-seata-tcc-mode-with-spring-cloud),事务执行状态是成功的

![Screenshot_20230908_202555](https://github.com/seata/seata/assets/38237890/7471f0ed-78d1-4551-9a20-809928029b2a)

控制台是这个状态,
![Screenshot_20230908_202456](https://github.com/seata/seata/assets/38237890/d1950803-2525-4d9b-b7e7-cf2f893e9288)

大概130s左右,seata-server重试提交成功,seata控制台就没有正在提交状态了
![Screenshot_20230908_202904](https://github.com/seata/seata/assets/38237890/feadbe6e-38bc-48d7-87a1-38fc1ca766a7)

我的问题是,事务在第一次日志Committing global transaction is successfully done完成后,为什么seata控制台一直是committing状态,

这个问题困扰好几天,不知道这个是不是正常的

**Comment by slievrly** [comment]
This is normal, the global transaction is delayed after 2min10s.

**Comment by dayu521** [comment]
明白了谢谢
