### ISSUE TITLE
Seata 2.0.0 什么时候release?有计划吗？

### ISSUE THREAD

**Issue by zhiwei55** [seata/seata#5838]
如题，需要使用 #3887 的MSSQL AT Mode,当前是merge到 2.0.0版本的，请问有release计划了吗？
https://github.com/seata/seata/pull/3887

**Comment by slievrly** [comment]
Can try ` 2.0.0 -SNAPSHOT `  first , https://oss.sonatype.org/#welcome

**Comment by leizhiyuan** [comment]
2.0.0 has been released 

release note https://github.com/seata/seata/releases/tag/v2.0.0
mvn jar https://mvnrepository.com/artifact/io.seata/seata-all/2.0.0
