### ISSUE TITLE
seata的at模式支持物理外键吗

### ISSUE THREAD

**Issue by xnb970919** [seata/seata#5844]
用seata 的at模式回滚带物理外键的表时，一直回滚失败，有什么好的处理办法吗

**Comment by a364176773** [comment]
不支持外键，规范上也不允许使用外键

**Comment by bright-mph** [comment]
> 用seata 的at模式回滚带物理外键的表时，一直回滚失败，有什么好的处理办法吗

可以描述下报错场景吗？我有两张表用是物理外键关联起来的，先插入主表，再插入子表，最后抛出异常，数据成功回滚，并没有复现您说的现象。
