### ISSUE TITLE
v2.x 里的 seata-all，是不是把 spring 相关的包去掉？或者作用域改为可选？更好！

### ISSUE THREAD

**Issue by noear** [seata/seata#5852]
这样显得太“面向 spring 编程”了。。。seata 应当面向全球的不同应用开发框架：）

**Comment by slievrly** [comment]
Spring is the most widely used programming framework for Java developers. To avoid developer dependency on multiple modules, support for Spring core is included by default in Seata-all. In addition, Seata-Spring-Boot-Starter includes separate support for SpringBoot.

**Comment by noear** [comment]
@slievrly 我印象里国外好多框架，都是独立的模块  + 适配的模块。。。如果与 spring 的框架绑得太多，java 的世界都被你缩小了。。。非 spring 的框架怎么办？

**Comment by noear** [comment]
@slievrly 做为一个项级项目。要是面向 spring 编程，格局小了。
