### ISSUE TITLE
1.7.1版本，store.mode 为 redis时，Console 进入 GlobalLockInfo页面报错。

### ISSUE THREAD

**Issue by woodmanwumeng** [seata/seata#5859]
1.7.1版本，使用k8s部署。当store.mode配置为redis，进入console。点击”GlobalLockInfo“查询页面，弹出错误信息：
”only three parameters of tableName,pk,resourceId or Xid are supported“
此时没有输入参数。

**Comment by wt-better** [comment]
`store.mode` current only support limited parameters query, but click 'GlobalLockInfo' query contains some not support params cause this ex.

this can optimization
