### ISSUE TITLE
seata1.5.2和jdk17搭配使用会有seata中GlobalTransactionScanner无法实例化问题

### ISSUE THREAD

**Issue by liuzhongyang881022** [seata/seata#5861]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by a364176773** [comment]
升级到最新版看下，如果还有问题请提供堆栈信息

**Comment by slievrly** [comment]
Seata 1.7.0 support JDK17
ref https://github.com/seata/seata/pull/5201
