### ISSUE TITLE
fescar+springboot+jpa don't auto create table

### ISSUE THREAD

**Issue by wangpeng9910** [seata/seata#587]
fescar+springboot+jpa don't auto create table,
DataSource configuration:
  @Bean
    public DataSource getDataSource() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setUrl(env.getProperty("spring.datasource.url"));
        dataSource.setUsername(env.getProperty("spring.datasource.username"));
        dataSource.setPassword(env.getProperty("spring.datasource.password"));
        dataSource.setDriverClassName(env.getProperty("spring.datasource.driver-class-name"));

        DataSourceProxy proxy = new DataSourceProxy(dataSource);

        return proxy;
    }
don't auto create table 
but The following configuration:
@Bean
    public DataSource getDataSource() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setUrl(env.getProperty("spring.datasource.url"));
        dataSource.setUsername(env.getProperty("spring.datasource.username"));
        dataSource.setPassword(env.getProperty("spring.datasource.password"));
        dataSource.setDriverClassName(env.getProperty("spring.datasource.driver-class-name"));

        return dataSource ;
    }
can do auto create table

How should I solve this problem?
Thank you

**Comment by slievrly** [comment]
@wangpeng9910 run our sample？

**Comment by wangpeng9910** [comment]
@slievrly yes i run your sample ,i modify springboot application.yml:
jpa: 
        hibernate:
            ddl-auto: update
        show-sql: true
i hope jpa  automatically create tables，but failure

**Comment by wangpeng9910** [comment]
@slievrly console already output hibernate sql ,but database not have tables

**Comment by slievrly** [comment]
I will check

**Comment by huhuajie** [comment]
org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(String) 这个方法里面执行  jdbcStatement.execute( command )建表。   但是 com.alibaba.fescar.rm.datasource.StatementProxy.execute(String) 没有实现,所以无法建表

**Comment by wangpeng9910** [comment]
@huhuajie 谢谢你的解释，看来要我自己修改完善或者等feacar后面的版本能修正

**Comment by slievrly** [comment]
mark as bug

**Comment by yuchonghua** [comment]
我也很期待使用fescar，
期待问题得到解决

**Comment by xingfudeshi** [comment]
i have made one PR to fix this bug.but i still suggest to create tables by executing the SQL scripts as the undo_log can't be created automatically by JPA.

**Comment by wangpeng9910** [comment]
@xingfudeshi ok
