### ISSUE TITLE
Spring boot instance

### ISSUE THREAD

**Issue by 544845389** [seata/seata#59]
Can provide a spring boot example呗
// 能提供一个 spring boot 的例子呗

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by sharajava** [comment]
working on it.

**Comment by leizhiyuan** [comment]
please see https://github.com/seata/seata-samples/tree/master/springboot

I will close the issue, if you have other questions, please reopen it or create a new one
