### ISSUE TITLE
SAGA state machine definition lacks syntax and semantic parsing

### ISSUE THREAD

**Issue by ptyin** [seata/seata#5904]
## Why you need it?
> Is your feature request related to a problem? Please describe in details

1. JSON syntax is not strictly defined currently, which leads to unclarified usage. 
2. No semantic verification is performed in parsing phase. Some errors that can be checked during parsing are not throwed until the state machine is run.

## How it could be?
> A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

1. Strict JSON shcema definitions. 
    Beyond that, JSON schema offers syntax highlight, code completion, and other functionalities achieved by popular editors like vscode .
2. Semantic verification.

## Other related information
> Add any other context or screenshots about the feature request here.

I can implement.

**Comment by wt-better** [comment]
Yes, it`s good idea.
