### ISSUE TITLE
Move module of integration to sub-directory.

### ISSUE THREAD

**Issue by ujjboy** [seata/seata#591]
There are some modules like `dubbo`, `dubbo-alibaba`, but Seata will integrate with more and more 3rd-party project in the future.  

I think it's best to move this type of modules to a subdirectory.

change 

```
 |--config
 |--dubbo-alibaba
 |--dubbo
 |--rm-datasource
 |-- ...
```
from 

```
+
|--config
|--integration
    |--dubbo
    |--dubbo-alibaba
    |--spring
    |--spring-boot
|-- ...
```

**Comment by zhangthen** [comment]
|--dubbo
 |--dubbo-alibaba

Above two shoud move  to  sub-directory, they are tools for context transmission, and we will have many tools like them.
