### ISSUE TITLE
how many tps can fecar support well?

### ISSUE THREAD

**Issue by wisdomhealth** [seata/seata#592]
how many tps can fecar support well?
In a global transaction session, there are usually multiple branch transactions, and the TPS in each specification refers to the number of global transaction sessions per second plus the peak number of branch transactions. Using a large amount of past statistics as a reference, this average is 5 to 10 times the number of global transaction sessions per second. Customers can evaluate the peak value of TPS according to their business characteristics to select the appropriate specifications. The extreme scenario is batch processing, where a global transaction session can contain hundreds of thousands of branch transactions.

**Comment by xingfudeshi** [comment]
4c8g 1w+.It also depends on the business scenarios.

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!
