### ISSUE TITLE
为什么现在存储redis模式没有支持集群模式，是基于什么的考虑？

### ISSUE THREAD

**Issue by PeppaO** [seata/seata#5920]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
Is there a real need for redis cluster?

**Comment by PeppaO** [comment]
生产环境目前redis是集群模式

**Comment by PeppaO** [comment]
想问一下，如果用集群模式，目前会存在什么问题和风险呀

**Comment by funky-eyes** [comment]
1.pippline，lua这类都不支持，再事务需要强一致的场景下，redis-cluster带来的丢失风险更大
2.吞吐量上redis已经完全超过了日常seata-server能承载的吞吐量，没有必要对接redis-cluster
