### ISSUE TITLE
我在使用seata+camunda时，遇到一个回滚数据缺失的问题

### ISSUE THREAD

**Issue by georliu** [seata/seata#5921]
我有一个业务系统与流程引擎系统，在业务系统里使用了@GlobalTransactional注解了业务方法A，流程引擎里完成流程实例方法B用的是springboot的事务处理@Transactional，然后方法A调完方法B之后，由于A的后续处理发生了异常，导致事务回滚，seata回滚日志里显示camunda回滚了act_ru_task,act_ru_execution等表内容，但是没回滚act_ru_variable表。 
我尝试过在流程引擎系统里面集成业务系统方法A，使用本地事务@Transactional注解，抛异常后是能正常回滚，看起来问题就在于使用seata+camunda引起的该异常。
请问我应该如何排查这个问题呢？

**Comment by slievrly** [comment]
Provide a minimum reproducible demo code.

**Comment by georliu** [comment]
> Provide a minimum reproducible demo code.
想要复现整个场景需要先创建流程引擎的流程配置，然后提交单据才能走到流程审批操作，我先提供执行审批的代码片段看您是否有思路。
方法A代码如下：
    @ApiOperation(value = "流程表单批准接口", httpMethod = "POST", response = RetResult.class)
    @PostMapping(value = "/approval")
    @SystemLog(eventName = "流程表单批准接口")
    @GlobalTransactional(rollbackFor = Exception.class)
    public RetResult<String> approval(@RequestBody RetRequest<SscAgreeDTO> request) {
        return workflowService.approval(request);
    }

    @Override
    public RetResult<String> approval(RetRequest<SscAgreeDTO> request) {
        log.info("Seata全局事务id=================>{}", RootContext.getXID());
        String content = StringUtils.isNotBlank(request.getData().getContent()) ? request.getData().getContent() : "";

        RetRequest<WfApprovalDto> wfReq = new RetRequest();
        WfApprovalDto approvalDto = new WfApprovalDto();
        approvalDto.setTaskId(request.getData().getTaskId());
        approvalDto.setAudit("pass");
        approvalDto.setContent(content);
        approvalDto.setUsers(new ArrayList<>(Collections.singletonList(request.getOperator())));
        wfReq.setData(approvalDto);
        wfReq.setOperator(request.getOperator());
        log.info("请求approval:{}", JSON.toJSONString(wfReq));
        //审批结果
        String result = workflowClient.approval(wfReq).getData();
        //模拟抛出业务异常
        throw new BizException("asd");
    }


方法B代码如下：

    @ApiOperation(value = "流程审批", notes = "流程审批", httpMethod = "POST", response = RetResult.class)
    @SystemLog(eventName = "流程审批")
    @PostMapping("/approval")
    public RetResult<String> approval(@Validated @RequestBody RetRequest<WfApprovalDto> request) {
        return RetResponse.makeOKRsp(workflowService.approval(request));
    }


    @Override
    @Transactional(rollbackFor = Exception.class)
    public String approval(RetRequest<WfApprovalDto> request) {
        log.info("Seata全局事务id=================>{}", RootContext.getXID());
        LocalDateTime now = LocalDateTime.now();
        String result = ContractStatus.APPROVING.getCode();
        Map<String, Object> variablesComplete = new HashMap<>();
        WfApprovalDto wfApprovalDto = request.getData();
        variablesComplete.put("users", wfApprovalDto.getUsers());
        String taskId = wfApprovalDto.getTaskId();
        String userId = request.getOperator();
        String audit = wfApprovalDto.getAudit();
        //判断是否流程运维操作
        Task task;
        if (ObjectUtil.isNotEmpty(wfApprovalDto.getOperateFlag()) && wfApprovalDto.getOperateFlag().equals(CommonConstants.ACTIVE_ON)) {
            task = taskService.createTaskQuery().taskId(wfApprovalDto.getTaskId()).singleResult();
        } else {
            task = getTask(wfApprovalDto.getTaskId(), userId);
        }
        ProcessInstance processInstance = runtimeService.createProcessInstanceQuery().processInstanceId(task.getProcessInstanceId()).singleResult();
        verifySuspended(processInstance);
        QueryWrapper<WfNode> queryWrapper = new QueryWrapper<>();
        queryWrapper.eq("process_id", task.getProcessInstanceId()).eq("node_key", task.getTaskDefinitionKey());
        WfNode wfNode = wfNodeService.getOne(queryWrapper);
        String operation = "";
        //流程变量提前取出来，防止流程结束获取失败
        Map<String, Object> varMap = historyService.createHistoricVariableInstanceQuery()
                .processInstanceId(task.getProcessInstanceId())
                .list()
                .stream()
                .filter(t -> ObjectUtil.isAllNotEmpty(t.getName(), t.getValue()))
                .collect(Collectors.toMap(
                        HistoricVariableInstance::getName,
                        HistoricVariableInstance::getValue,
                        (existingValue, newValue) -> newValue // 解决重复键的策略，选择最后一个值
                ));
        //回写状态
        if (!varMap.isEmpty() && ObjectUtil.isNotEmpty(varMap.get(CommonConstants.REQUEST_JSON))) {
            JSONObject requestJson = JSON.parseObject(varMap.get(CommonConstants.REQUEST_JSON).toString());
            callbackStatus(task, processInstance.getBusinessKey(), wfApprovalDto.getAudit(), requestJson, varMap);
        }
        //进行审批
        if (ConstantEnum.PASS.getCode().equals(audit)) {
            taskService.createComment(taskId, task.getProcessInstanceId(), wfApprovalDto.getContent());
            taskService.complete(taskId, variablesComplete);
            operation = ConstantEnum.PROCESSOR_OPERATION_TYPE_PASS.getCode();

            String actAssignee = wfNode.getActAssignee();
            if (StringUtils.isNotEmpty(actAssignee)) {
                wfNode.setActAssignee(actAssignee + "," + userId);
            } else {
                wfNode.setActAssignee(userId);
            }
        } else if (ConstantEnum.REJECT.getCode().equals(audit)) {
            runtimeService.deleteProcessInstance(task.getProcessInstanceId(),
                    CommonConstants.ACTIVE_ON.equals(wfApprovalDto.getCancelFlag()) ? ConstantEnum.CANCEL.getCode() : wfApprovalDto.getAudit());
            operation = CommonConstants.ACTIVE_ON.equals(wfApprovalDto.getCancelFlag()) ?
                    ConstantEnum.PROCESSOR_OPERATION_TYPE_CANCEL.getCode() : ConstantEnum.PROCESSOR_OPERATION_TYPE_REJECT.getCode();
            workflowMapper.updateProcessState(task.getProcessInstanceId(), WorkflowConstants.PROCESS_STATE_REJECT);
        }

        return result;
    }

**Comment by georliu** [comment]
异常后回滚的seata日志记录如下
14:24:16.531  INFO --- [nPool.commonPool-worker-1] i.seata.server.coordinator.AbstractCore  : Register branch successfully, xid = 10.20.12.53:8005:18458157566277141, branchId = 18458157566277169, resourceId = jdbc:mysql://10.20.12.53:3306/sys_base_db ,lockKeys = lc_message:161308218771001344
14:24:16.780  INFO --- [     batchLoggerPrint_1_1] i.s.c.r.p.server.BatchLogHandler         : SeataMergeMessage xid=10.20.12.53:8005:18458157566277141,branchType=AT,resourceId=jdbc:mysql://10.20.12.53:3306/sys_workflow_db,lockKey=act_hi_taskinst:a29a1ad7-6735-11ee-a7a2-f24bd6ffd0b4;act_hi_op_log:a3480e1a-6735-11ee-a7a2-f24bd6ffd0b4;act_ru_task_meter_log:a29a1ad9-6735-11ee-a7a2-f24bd6ffd0b4;act_hi_identitylink:a29a1ad8-6735-11ee-a7a2-f24bd6ffd0b4;act_ru_variable:a299f3c4-6735-11ee-a7a2-f24bd6ffd0b4;act_hi_procinst:a2973500-6735-11ee-a7a2-f24bd6ffd0b4;act_ru_task:a29a1ad7-6735-11ee-a7a2-f24bd6ffd0b4;wf_hi_activity:2068
,clientIp:10.20.12.54,vgroup:bps-workflow

**Comment by funky-eyes** [comment]
Looking at your logs to there is one branch, but code wise it is multiple, please check that the data source agent is working properly when the camunda related code is running, and that the xid is being passed to the thread that the camunda code is in
看你的日志至有一个分支，但是代码上是多个，请检查数据源代理在camunda相关代码运行时是否正常，xid是否传递到camunda代码所处线程中
