### ISSUE TITLE
How does "seat.client.undo.logTable" work in client application

### ISSUE THREAD

**Issue by miracleQin** [seata/seata#5929]
https://github.com/seata/seata/blob/2cc875bc7fd1a0902f842e8bf839cb5c95a96db7/seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/client/UndoProperties.java#L35C5-L35C5

**Comment by leizhiyuan** [comment]
in SeataClientEnvironmentPostProcessor   add this to PROPERTY_BEAN_MAP

then 

io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider#getDefaultValueFromPropertyObject(java.lang.String)

process the value

**Comment by miracleQin** [comment]
i try to set this config on application.yml , but it did not work in my springboot application. the field "io.seata.rm.datasource.undo.AbstractUndoLogManager.UNDO_LOG_TABLE_NAME" still be "undo_log".

**Comment by funky-eyes** [comment]
> i try to set this config on application.yml , but it did not work in my springboot application. the field "io.seata.rm.datasource.undo.AbstractUndoLogManager.UNDO_LOG_TABLE_NAME" still be "undo_log".

What configuration center are you using?
