### ISSUE TITLE
AT模式的行锁是否可以考虑新增乐观锁的配置？dtx是支持乐观锁的

### ISSUE THREAD

**Issue by garrett-cn** [seata/seata#5937]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
In principle, optimistic locking should not be supported. AT mode needs to ensure strong consistency of data, so there is no planned support for the time being.
