### ISSUE TITLE
TCC 开启 useTCCFence，dubbo 远程调用的接口仍然有两次 commit 记录

### ISSUE THREAD

**Issue by kunghim** [seata/seata#5940]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
账户服务和库存服务使用 TCC 模式，测试时打印调用 commit 记录，发现seata 调用了两次。
而本地调用的 service 使用 TCC 模式就不会

### Ⅱ. Describe what happened
seataDemo 服务
![image](https://github.com/seata/seata/assets/104054614/37a3efdf-e2a0-4d1c-ad6e-e18abdf46256)
![image](https://github.com/seata/seata/assets/104054614/0f90fddc-b47a-48f4-ad36-29f3b507cfed)
![image](https://github.com/seata/seata/assets/104054614/6331f7a5-1ab3-4ab1-ac76-2bde98ac8485)
本地 service 只有一次 commit 记录
![image](https://github.com/seata/seata/assets/104054614/9bc2b2c2-f04e-434d-b678-c9de1717358c)
库存服务（TCC 业务代码）
![image](https://github.com/seata/seata/assets/104054614/2694f99f-b8bf-4634-a7d7-12684417c9db)
![image](https://github.com/seata/seata/assets/104054614/c016a69c-4545-4d9a-9ffd-7692ed99e345)
有两次 commit 记录
![image](https://github.com/seata/seata/assets/104054614/32c65bf5-c7d9-47cc-9259-7bede7f8327c)
账户服务（TCC 业务代码）
![image](https://github.com/seata/seata/assets/104054614/8eb2b02f-35df-4faa-9fc4-6f287ea1c3ea)
![image](https://github.com/seata/seata/assets/104054614/ac229cf5-e239-41ee-93c3-54cde4da4612)
有两次 commit 记录
![image](https://github.com/seata/seata/assets/104054614/fa936346-bd90-4516-baac-9934d2a69311)
  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): java JDK1.8
- Seata client/server version:  seata1.7.1
- Database version: mysql 
- OS(e.g. `uname -a`): macOS
- Others:

**Comment by kunghim** [comment]
<img width="845" alt="image" src="https://github.com/seata/seata/assets/104054614/e48184ee-24e5-41c8-9760-933632d99ba1">
tcc_fence_log表也有两条记录

**Comment by leizhiyuan** [comment]
If convenient, please provide the complete test demo.

**Comment by funky-eyes** [comment]
The idempotency in the tcc anti-suspension is to safeguard two-stage idempotency, not one-stage idempotency

**Comment by Bughue** [comment]
一阶段的时候已经产生了两个分支了，由于branchid是TC分配的，所以只要rm的方法体能进入就会产生，你应该要在rm的一阶段之前自己做幂等了
