### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0

### ISSUE THREAD

**Issue by slievrly** [seata/seata#5948]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
![image](https://github.com/seata/seata/assets/8758457/06664464-fd66-420a-93a9-0efb2b6d6326)

https://github.com/seata/seata/actions/runs/6604746563/job/17939197694

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by wangliang181230** [comment]
This error prompt does not affect the unit-test, so it was not removed before.
