### ISSUE TITLE
Adding test cases for RaftClusterMetadataMsg

### ISSUE THREAD

**Issue by funky-eyes** [seata/seata#5961]
## Why you need it?
增加该msg及相关的RaftClusterMetadata测试用例，序列化，反序列化，模拟同步时的过程
Add this msg and the associated RaftClusterMetadata test case, serialize it, deserialize it, and simulate the process during synchronization

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
referable： https://github.com/seata/seata/blob/2.x/server/src/test/java/io/seata/server/raft/RaftSyncMessageTest.java

**Comment by ggbocoder** [comment]
assign to me please.
