### ISSUE TITLE
Adding test cases for RaftMsgExecute

### ISSUE THREAD

**Issue by funky-eyes** [seata/seata#5963]
## Why you need it?
将io.seata.server.cluster.raft.execute包下的global，branch，lock三个部分添加相关测试用例，可每个部分提交一个pr
Add relevant test cases to the global, branch, and lock sections under the io.seata.server.cluster.raft.execute package, and submit one pr for each section.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by ptyin** [comment]
It's interesting, let me try 🙋‍♂️

**Comment by funky-eyes** [comment]
> It's interesting, let me try 🙋‍♂️

Good job, looking forward to your pr

**Comment by ptyin** [comment]
@funky-eyes Ready to review ;)
