### ISSUE TITLE
seata正常使用没有问题，控制台偶尔会打印no available service found in cluster 'seata-server'，please make sure registry config correct and keep your seata server running

### ISSUE THREAD

**Issue by ryk72835** [seata/seata#5974]
## 使用的配置
apollo + consul
大部分情况下，seata能正常使用，但是控制台日志偶尔会打印
···
no available service found in cluster 'seata-server'，please make sure registry config correct and keep your seata server running
···
consul上的服务也是存活状态

**Comment by funky-eyes** [comment]
Please check that the cluster in the seata-server consul configuration is seata-server

**Comment by ryk72835** [comment]
> Please check that the cluster in the seata-server consul configuration is seata-server
我可能没表达清楚我的意思，我的意思是，大部分情况下seata是能够正常注册并使用的，出现的问题也能正常回滚，这样的日志只是偶尔打印，我想找到出现这种偶尔打印情况的原因
![QQ截图20231030181042](https://github.com/seata/seata/assets/48279964/fc16c73b-1bf5-4bfc-888a-62ffc348ffdd)

**Comment by funky-eyes** [comment]
That could be because of seata-server and consul network issues, or it's offline causing the client side to not get it, are you a test environment? How many seata-server nodes?

**Comment by ryk72835** [comment]
> That could be because of seata-server and consul network issues, or it's offline causing the client side to not get it, are you a test environment? How many seata-server nodes?

目前是使用的单节点的seata，使用的是db模式，consul是三台集群部署，当前该consul上注册的consul存在多台应用使用，是一个开发自测的环境。

**Comment by ryk72835** [comment]
> That could be because of seata-server and consul network issues, or it's offline causing the client side to not get it, are you a test environment? How many seata-server nodes?

经过我的debug我发现此处是由于如果不处于File模式时，就会打印这个错误，不过我不太清楚触发的原因
![ZXLBGJX@OXG2P(8)CS43M$F](https://github.com/seata/seata/assets/48279964/134a1ca4-35e6-4f2d-951f-3be5a421e673)
我使用的seata为1.6.1版本，依赖也是1.6.1版本
当前打印位置位于NettyClientChannelManage的188行

**Comment by funky-eyes** [comment]
I see, may be because there is only one tc, network or restart tc led to the appearance of the prompt, if the deployment of multiple tc nodes should not be easy to appear

**Comment by webfast-lab** [comment]
> I see, may be because there is only one tc, network or restart tc led to the appearance of the prompt, if the deployment of multiple tc nodes should not be easy to appear

好的，让我试试，尝试部署多个节点
