### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by beifeng-785** [seata/seata#5975]
![image](https://github.com/seata/seata/assets/74748004/c48fe2f1-bc06-4a56-aaac-b7928243239f)

v1.7.0 报错lock_table的PRIMARY重复，但是去掉这个lock_table表的主键以后，不再报错
1.7.0的源码启动，报错：java: 程序包io.seata.serializer.protobuf.generated不存在，
![image](https://github.com/seata/seata/assets/74748004/c3f8a22d-e201-4219-825b-34f738fd25f9)

**Comment by beifeng-785** [comment]
1

**Comment by leizhiyuan** [comment]
```
mvn  clean install -Dmaven.test.skip=true -Prelease-seata

```

compile first

**Comment by beifeng-785** [comment]
8.0.32

**Comment by beifeng-785** [comment]
mysql-8.0.32

**Comment by funky-eyes** [comment]
Please post the tc side exception stack here
