### ISSUE TITLE
After a branch in transaction A is submitted, it is modified by a branch of global transaction B. The other branches in A are abnormal. How does A roll back the data?

### ISSUE THREAD

**Issue by airufei** [seata/seata#62]
If a branch in global transaction A is committed and is modified by a branch of global transaction B, the other branches in A are abnormal, how does A roll back the data?
// 如果全局事物A中的一个分支提交之后 被全局事物B的一个分支修改数据，A中的其他分支异常，A要怎么回滚数据？

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by sharajava** [comment]
There are global locks managed in TC server side. Such case you mentioned never happen.

**Comment by airufei** [comment]
> There are global locks managed in TC server side. Such case you mentioned never happen.

OK，thanks
