### ISSUE TITLE
From the current lockManager, the server is only allowed to deploy one?

### ISSUE THREAD

**Issue by xuyang0902** [seata/seata#63]
I see that the global lock is synchronized. In the case of cluster deployment, something goes wrong. .
// 我看全局锁是用了synchronized呀。集群部署情况下会出错吧。。

--------------------------------------------------
Simply look at the code of the client begin to tune to the remote and only support a single server
// 简单看了下客户端begin的代码 调到远程也是只支持单个server

 private String loadBalance() {
        String[] addresses = serviceManager.lookup(transactionServiceGroup);
        if (addresses == null || addresses.length == 0) {
            throw new FrameworkException(NoAvailableService);
        }
        // Just single server node
        return addresses[0];
    }

How to deal with the bottleneck of a single-node server? Transaction registration, coordination.
// 单节点的server的瓶颈如何处理？ 事务注册，协调。

Single point of risk?
// 单点风险？

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by sharajava** [comment]
HA Cluster will be released later on 0.5.x. 💯

**Comment by xuyang0902** [comment]
how can I be a contibutor？

**Comment by warrior2005** [comment]
Is HA Cluster available in 0.5.0 version? I see that the "loadBalance()" function has been changed.
`protected String loadBalance(String transactionServiceGroup) {
        InetSocketAddress address = null;
        try {
            List<InetSocketAddress> inetSocketAddressList = RegistryFactory.getInstance().lookup(
                transactionServiceGroup);
            address = LoadBalanceFactory.getInstance().select(inetSocketAddressList);
        } catch (Exception ignore) {
            LOGGER.error(ignore.getMessage());
        }
        if (address == null) {
            throw new FrameworkException(NoAvailableService);
        }
        return NetUtil.toStringAddress(address);
    }`
Is there any concurrency problem with the 0.5.0 version?

**Comment by leizhiyuan** [comment]
wait for this pr https://github.com/seata/seata/pull/942
