### ISSUE TITLE
Does seata support mysql sharding scenarios？

### ISSUE THREAD

**Issue by wjyheropk** [seata/seata#635]
如题，fescar是否支持，或者计划支持分库分表场景？

**Comment by zhangthen** [comment]
> 如题，fescar是否支持，或者计划支持分库分表场景？

fescar是否支持分库分别场景，这个不取决fescar，取决分库分表组件是否能把底层的 物理DataSource换成 fescar的 DataSourceProxy。

**Comment by wjyheropk** [comment]
个人愚见，对于我们使用者来说，不是把DataSource换一下就能直接用的，我理解这个问题可以有两个解决方向：
1、fescar适配分库分表框架（可以选择一种最常用的分库分表框架做一个解决方案）
2、分库分表框架适配fescar

想了解一下fescar有没有这方面的规划？

**Comment by zongtanghu** [comment]
1、fescar适配分库分表框架（可以选择一种最常用的分库分表框架做一个解决方案）
补充：比如以当前比较常用的分库分表组件，ShardingSphere或者Mycat，fescar是否有做这方面集成的计划？



huzongtang@cmss.chinamobile.com
 
发件人： Wang Jiayin
发送时间： 2019-03-20 20:35
收件人： alibaba/fescar
抄送： Subscribed
主题： Re: [alibaba/fescar] Does fescar support mysql sharding scenarios？ (#635)
个人愚见，对于我们使用者来说，不是把DataSource换一下就能直接用的，我理解这个问题可以有两个解决方向：
1、fescar适配分库分表框架（可以选择一种最常用的分库分表框架做一个解决方案）
2、分库分表框架适配fescar
想了解一下fescar有没有这方面的规划？

**Comment by xingfudeshi** [comment]
DB sharding should be considered in the side of your application,not in Fescar's side.
