### ISSUE TITLE
dubbo+zk  will be   can not connect to fescar-server 

### ISSUE THREAD

**Issue by click-one** [seata/seata#636]
23:20:12.722 [DubboServerHandler-192.168.199.245:20881-thread-33] ERROR com.alibaba.fescar.core.rpc.netty.RmRpcClient - 0304
com.alibaba.fescar.common.exception.FrameworkException: can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:244)
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:63)
	at com.alibaba.fescar.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:41)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:354)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:322)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.getRemoteServerChannel(RmRpcClient.java:243)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:227)
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.sendMsgWithResponse(RmRpcClient.java:248)
	at com.alibaba.fescar.rm.datasource.DataSourceManager.branchRegister(DataSourceManager.java:70)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.register(ConnectionProxy.java:202)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:175)
	at com.alibaba.fescar.rm.datasource.ConnectionProxy.setAutoCommit(ConnectionProxy.java:221)
	at com.alibaba.fescar.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:104)
	at com.alibaba.fescar.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:55)
	at com.alibaba.fescar.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:72)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:100)
	at com.alibaba.fescar.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:46)
	at com.alibaba.fescar.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:867)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:917)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:927)
	at com.alibaba.fescar.samples.dubbo.service.impl.AccountServiceImpl.debit(AccountServiceImpl.java:54)
	at org.apache.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:86)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.alibaba.fescar.dubbo.TransactionPropagationFilter.invoke(TransactionPropagationFilter.java:60)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:63)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:88)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:79)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:78)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:138)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:39)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:103)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.fescar.common.exception.FrameworkException: connect failed, can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.getNewChannel(AbstractRpcRemotingClient.java:239)
	... 55 common frames omitted

**Comment by click-one** [comment]
https://github.com/alibaba/fescar/issues/69 我看了这个里面的问题 启动fascar-server没有指定端口号，我启动服务的时候加了 8091端口号，如下图所示控制台输出信息
![image](https://user-images.githubusercontent.com/12377170/54697831-3a1ae080-4b69-11e9-81a8-8dec63074585.png)

**Comment by slievrly** [comment]
Please paste registry.conf, file.conf and GlobalTransactionScanner

**Comment by click-one** [comment]
> Please paste registry.conf, file.conf and GlobalTransactionScanner


**registry.conf**
```  confregistry {
  # file 、nacos 、eureka、redis、zk
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://localhost:1001/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  apollo {
    app.id = "fescar-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

```

**file.conf**
``` conf
transport {
  # tcp udt unix-domain-socket
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #enable heartbeat
  heartbeat = true
  #thread factory for netty
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    # netty boss thread size,will not be used for UDT
    boss-thread-size = 1
    #auto default pin or 8
    worker-thread-size = 8
  }
}
service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "localRgroup"
  #only support single node
  localRgroup.grouplist = "127.0.0.1:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disable = false
}

client {
  async.commit.buffer.limit = 10000
  lock {
    retry.internal = 10
    retry.times = 30
  }
}

```
**GlobalTransactionScanner.java**
``` java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package com.alibaba.fescar.spring.annotation;

import com.alibaba.fescar.common.exception.NotSupportYetException;
import com.alibaba.fescar.config.ConfigurationFactory;
import com.alibaba.fescar.rm.RMClientAT;
import com.alibaba.fescar.tm.TMClient;
import com.alibaba.fescar.tm.api.DefaultFailureHandlerImpl;
import com.alibaba.fescar.tm.api.FailureHandler;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Set;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.aop.Advisor;
import org.springframework.aop.TargetSource;
import org.springframework.aop.framework.AdvisedSupport;
import org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator;
import org.springframework.aop.support.AopUtils;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.InitializingBean;

public class GlobalTransactionScanner extends AbstractAutoProxyCreator implements InitializingBean {
    private static final Logger LOGGER = LoggerFactory.getLogger(GlobalTransactionScanner.class);
    private static final int AT_MODE = 1;
    private static final int MT_MODE = 2;
    private static final int ORDER_NUM = 1024;
    private static final int DEFAULT_MODE = 1;
    private static final Set<String> PROXYED_SET = new HashSet();
    private static final FailureHandler DEFAULT_FAIL_HANDLER = new DefaultFailureHandlerImpl();
    private GlobalTransactionalInterceptor interceptor;
    private final String applicationId;
    private final String txServiceGroup;
    private final int mode;
    private final boolean disableGlobalTransaction;
    private final FailureHandler failureHandlerHook;

    public GlobalTransactionScanner(String txServiceGroup) {
        this(txServiceGroup, txServiceGroup, 1);
    }

    public GlobalTransactionScanner(String txServiceGroup, int mode) {
        this(txServiceGroup, txServiceGroup, mode);
    }

    public GlobalTransactionScanner(String applicationId, String txServiceGroup) {
        this(applicationId, txServiceGroup, 1);
    }

    public GlobalTransactionScanner(String applicationId, String txServiceGroup, int mode) {
        this(applicationId, txServiceGroup, mode, DEFAULT_FAIL_HANDLER);
    }

    public GlobalTransactionScanner(String applicationId, String txServiceGroup, FailureHandler failureHandlerHook) {
        this(applicationId, txServiceGroup, 1, failureHandlerHook);
    }

    public GlobalTransactionScanner(String applicationId, String txServiceGroup, int mode, FailureHandler failureHandlerHook) {
        this.disableGlobalTransaction = ConfigurationFactory.getInstance().getBoolean("service.disableGlobalTransaction", false);
        this.setOrder(1024);
        this.setProxyTargetClass(true);
        this.applicationId = applicationId;
        this.txServiceGroup = txServiceGroup;
        this.mode = mode;
        this.failureHandlerHook = failureHandlerHook;
    }

    private void initClient() {
        if (LOGGER.isInfoEnabled()) {
            LOGGER.info("Initializing Global Transaction Clients ... ");
        }

        if (!StringUtils.isEmpty(this.applicationId) && !StringUtils.isEmpty(this.txServiceGroup)) {
            TMClient.init(this.applicationId, this.txServiceGroup);
            if (LOGGER.isInfoEnabled()) {
                LOGGER.info("Transaction Manager Client is initialized. applicationId[" + this.applicationId + "] txServiceGroup[" + this.txServiceGroup + "]");
            }

            if ((1 & this.mode) > 0) {
                RMClientAT.init(this.applicationId, this.txServiceGroup);
                if (LOGGER.isInfoEnabled()) {
                    LOGGER.info("Resource Manager for AT Client is initialized. applicationId[" + this.applicationId + "] txServiceGroup[" + this.txServiceGroup + "]");
                }
            }

            if ((2 & this.mode) > 0) {
                throw new NotSupportYetException();
            } else {
                if (LOGGER.isInfoEnabled()) {
                    LOGGER.info("Global Transaction Clients are initialized. ");
                }

            }
        } else {
            throw new IllegalArgumentException("applicationId: " + this.applicationId + ", txServiceGroup: " + this.txServiceGroup);
        }
    }

    protected Object wrapIfNecessary(Object bean, String beanName, Object cacheKey) {
        if (this.disableGlobalTransaction) {
            return bean;
        } else {
            try {
                Set var4 = PROXYED_SET;
                synchronized(PROXYED_SET) {
                    if (PROXYED_SET.contains(beanName)) {
                        return bean;
                    } else {
                        Class<?> serviceInterface = this.findTargetClass(bean);
                        Method[] methods = serviceInterface.getMethods();
                        LinkedList<MethodDesc> methodDescList = new LinkedList();
                        Method[] arr$ = methods;
                        int len$ = methods.length;

                        for(int i$ = 0; i$ < len$; ++i$) {
                            Method method = arr$[i$];
                            GlobalTransactional anno = (GlobalTransactional)method.getAnnotation(GlobalTransactional.class);
                            if (anno != null) {
                                methodDescList.add(this.makeMethodDesc(anno, method));
                            }
                        }

                        if (methodDescList.isEmpty()) {
                            return bean;
                        } else {
                            if (this.interceptor == null) {
                                this.interceptor = new GlobalTransactionalInterceptor(this.failureHandlerHook);
                            }

                            if (!AopUtils.isAopProxy(bean)) {
                                bean = super.wrapIfNecessary(bean, beanName, cacheKey);
                            } else {
                                AdvisedSupport advised = this.getAdvisedSupport(bean);
                                Advisor[] advisor = this.buildAdvisors(beanName, this.getAdvicesAndAdvisorsForBean((Class)null, (String)null, (TargetSource)null));
                                Advisor[] arr$ = advisor;
                                int len$ = advisor.length;

                                for(int i$ = 0; i$ < len$; ++i$) {
                                    Advisor avr = arr$[i$];
                                    advised.addAdvisor(0, avr);
                                }
                            }

                            PROXYED_SET.add(beanName);
                            return bean;
                        }
                    }
                }
            } catch (Exception var16) {
                throw new RuntimeException(var16);
            }
        }
    }

    private MethodDesc makeMethodDesc(GlobalTransactional anno, Method method) {
        return new MethodDesc(anno, method);
    }

    private Class<?> findTargetClass(Object proxy) throws Exception {
        if (AopUtils.isAopProxy(proxy)) {
            AdvisedSupport advised = this.getAdvisedSupport(proxy);
            Object target = advised.getTargetSource().getTarget();
            return this.findTargetClass(target);
        } else {
            return proxy.getClass();
        }
    }

    private AdvisedSupport getAdvisedSupport(Object proxy) throws Exception {
        Field h;
        if (AopUtils.isJdkDynamicProxy(proxy)) {
            h = proxy.getClass().getSuperclass().getDeclaredField("h");
        } else {
            h = proxy.getClass().getDeclaredField("CGLIB$CALLBACK_0");
        }

        h.setAccessible(true);
        Object dynamicAdvisedInterceptor = h.get(proxy);
        Field advised = dynamicAdvisedInterceptor.getClass().getDeclaredField("advised");
        advised.setAccessible(true);
        return (AdvisedSupport)advised.get(dynamicAdvisedInterceptor);
    }

    protected Object[] getAdvicesAndAdvisorsForBean(Class beanClass, String beanName, TargetSource customTargetSource) throws BeansException {
        return new Object[]{this.interceptor};
    }

    public void afterPropertiesSet() {
        if (this.disableGlobalTransaction) {
            if (LOGGER.isInfoEnabled()) {
                LOGGER.info("Global transaction is disabled.");
            }

        } else {
            this.initClient();
        }
    }
}

```

**Comment by Scorpio-ljc** [comment]
> > Please paste registry.conf, file.conf and GlobalTransactionScanner
> 
> **registry.conf**
> 
> ```
>   # file 、nacos 、eureka、redis、zk
>   type = "file"
> 
>   nacos {
>     serverAddr = "localhost"
>     namespace = "public"
>     cluster = "default"
>   }
>   eureka {
>     serviceUrl = "http://localhost:1001/eureka"
>     application = "default"
>     weight = "1"
>   }
>   redis {
>     serverAddr = "localhost:6379"
>     db = "0"
>   }
>   zk {
>     cluster = "default"
>     serverAddr = "127.0.0.1:2181"
>     session.timeout = 6000
>     connect.timeout = 2000
>   }
>   file {
>     name = "file.conf"
>   }
> }
> 
> config {
>   # file、nacos 、apollo、zk
>   type = "file"
> 
>   nacos {
>     serverAddr = "localhost"
>     namespace = "public"
>     cluster = "default"
>   }
>   apollo {
>     app.id = "fescar-server"
>     apollo.meta = "http://192.168.1.204:8801"
>   }
>   zk {
>     serverAddr = "127.0.0.1:2181"
>     session.timeout = 6000
>     connect.timeout = 2000
>   }
>   file {
>     name = "file.conf"
>   }
> }
> ```
> **file.conf**
> 
> ```
> transport {
>   # tcp udt unix-domain-socket
>   type = "TCP"
>   #NIO NATIVE
>   server = "NIO"
>   #enable heartbeat
>   heartbeat = true
>   #thread factory for netty
>   thread-factory {
>     boss-thread-prefix = "NettyBoss"
>     worker-thread-prefix = "NettyServerNIOWorker"
>     server-executor-thread-prefix = "NettyServerBizHandler"
>     share-boss-worker = false
>     client-selector-thread-prefix = "NettyClientSelector"
>     client-selector-thread-size = 1
>     client-worker-thread-prefix = "NettyClientWorkerThread"
>     # netty boss thread size,will not be used for UDT
>     boss-thread-size = 1
>     #auto default pin or 8
>     worker-thread-size = 8
>   }
> }
> service {
>   #vgroup->rgroup
>   vgroup_mapping.my_test_tx_group = "localRgroup"
>   #only support single node
>   localRgroup.grouplist = "127.0.0.1:8091"
>   #degrade current not support
>   enableDegrade = false
>   #disable
>   disable = false
> }
> 
> client {
>   async.commit.buffer.limit = 10000
>   lock {
>     retry.internal = 10
>     retry.times = 30
>   }
> }
> ```
> **GlobalTransactionScanner.java**
> 
> ```java
> //
> // Source code recreated from a .class file by IntelliJ IDEA
> // (powered by Fernflower decompiler)
> //
> 
> package com.alibaba.fescar.spring.annotation;
> 
> import com.alibaba.fescar.common.exception.NotSupportYetException;
> import com.alibaba.fescar.config.ConfigurationFactory;
> import com.alibaba.fescar.rm.RMClientAT;
> import com.alibaba.fescar.tm.TMClient;
> import com.alibaba.fescar.tm.api.DefaultFailureHandlerImpl;
> import com.alibaba.fescar.tm.api.FailureHandler;
> import java.lang.reflect.Field;
> import java.lang.reflect.Method;
> import java.util.HashSet;
> import java.util.LinkedList;
> import java.util.Set;
> import org.apache.commons.lang.StringUtils;
> import org.slf4j.Logger;
> import org.slf4j.LoggerFactory;
> import org.springframework.aop.Advisor;
> import org.springframework.aop.TargetSource;
> import org.springframework.aop.framework.AdvisedSupport;
> import org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator;
> import org.springframework.aop.support.AopUtils;
> import org.springframework.beans.BeansException;
> import org.springframework.beans.factory.InitializingBean;
> 
> public class GlobalTransactionScanner extends AbstractAutoProxyCreator implements InitializingBean {
>     private static final Logger LOGGER = LoggerFactory.getLogger(GlobalTransactionScanner.class);
>     private static final int AT_MODE = 1;
>     private static final int MT_MODE = 2;
>     private static final int ORDER_NUM = 1024;
>     private static final int DEFAULT_MODE = 1;
>     private static final Set<String> PROXYED_SET = new HashSet();
>     private static final FailureHandler DEFAULT_FAIL_HANDLER = new DefaultFailureHandlerImpl();
>     private GlobalTransactionalInterceptor interceptor;
>     private final String applicationId;
>     private final String txServiceGroup;
>     private final int mode;
>     private final boolean disableGlobalTransaction;
>     private final FailureHandler failureHandlerHook;
> 
>     public GlobalTransactionScanner(String txServiceGroup) {
>         this(txServiceGroup, txServiceGroup, 1);
>     }
> 
>     public GlobalTransactionScanner(String txServiceGroup, int mode) {
>         this(txServiceGroup, txServiceGroup, mode);
>     }
> 
>     public GlobalTransactionScanner(String applicationId, String txServiceGroup) {
>         this(applicationId, txServiceGroup, 1);
>     }
> 
>     public GlobalTransactionScanner(String applicationId, String txServiceGroup, int mode) {
>         this(applicationId, txServiceGroup, mode, DEFAULT_FAIL_HANDLER);
>     }
> 
>     public GlobalTransactionScanner(String applicationId, String txServiceGroup, FailureHandler failureHandlerHook) {
>         this(applicationId, txServiceGroup, 1, failureHandlerHook);
>     }
> 
>     public GlobalTransactionScanner(String applicationId, String txServiceGroup, int mode, FailureHandler failureHandlerHook) {
>         this.disableGlobalTransaction = ConfigurationFactory.getInstance().getBoolean("service.disableGlobalTransaction", false);
>         this.setOrder(1024);
>         this.setProxyTargetClass(true);
>         this.applicationId = applicationId;
>         this.txServiceGroup = txServiceGroup;
>         this.mode = mode;
>         this.failureHandlerHook = failureHandlerHook;
>     }
> 
>     private void initClient() {
>         if (LOGGER.isInfoEnabled()) {
>             LOGGER.info("Initializing Global Transaction Clients ... ");
>         }
> 
>         if (!StringUtils.isEmpty(this.applicationId) && !StringUtils.isEmpty(this.txServiceGroup)) {
>             TMClient.init(this.applicationId, this.txServiceGroup);
>             if (LOGGER.isInfoEnabled()) {
>                 LOGGER.info("Transaction Manager Client is initialized. applicationId[" + this.applicationId + "] txServiceGroup[" + this.txServiceGroup + "]");
>             }
> 
>             if ((1 & this.mode) > 0) {
>                 RMClientAT.init(this.applicationId, this.txServiceGroup);
>                 if (LOGGER.isInfoEnabled()) {
>                     LOGGER.info("Resource Manager for AT Client is initialized. applicationId[" + this.applicationId + "] txServiceGroup[" + this.txServiceGroup + "]");
>                 }
>             }
> 
>             if ((2 & this.mode) > 0) {
>                 throw new NotSupportYetException();
>             } else {
>                 if (LOGGER.isInfoEnabled()) {
>                     LOGGER.info("Global Transaction Clients are initialized. ");
>                 }
> 
>             }
>         } else {
>             throw new IllegalArgumentException("applicationId: " + this.applicationId + ", txServiceGroup: " + this.txServiceGroup);
>         }
>     }
> 
>     protected Object wrapIfNecessary(Object bean, String beanName, Object cacheKey) {
>         if (this.disableGlobalTransaction) {
>             return bean;
>         } else {
>             try {
>                 Set var4 = PROXYED_SET;
>                 synchronized(PROXYED_SET) {
>                     if (PROXYED_SET.contains(beanName)) {
>                         return bean;
>                     } else {
>                         Class<?> serviceInterface = this.findTargetClass(bean);
>                         Method[] methods = serviceInterface.getMethods();
>                         LinkedList<MethodDesc> methodDescList = new LinkedList();
>                         Method[] arr$ = methods;
>                         int len$ = methods.length;
> 
>                         for(int i$ = 0; i$ < len$; ++i$) {
>                             Method method = arr$[i$];
>                             GlobalTransactional anno = (GlobalTransactional)method.getAnnotation(GlobalTransactional.class);
>                             if (anno != null) {
>                                 methodDescList.add(this.makeMethodDesc(anno, method));
>                             }
>                         }
> 
>                         if (methodDescList.isEmpty()) {
>                             return bean;
>                         } else {
>                             if (this.interceptor == null) {
>                                 this.interceptor = new GlobalTransactionalInterceptor(this.failureHandlerHook);
>                             }
> 
>                             if (!AopUtils.isAopProxy(bean)) {
>                                 bean = super.wrapIfNecessary(bean, beanName, cacheKey);
>                             } else {
>                                 AdvisedSupport advised = this.getAdvisedSupport(bean);
>                                 Advisor[] advisor = this.buildAdvisors(beanName, this.getAdvicesAndAdvisorsForBean((Class)null, (String)null, (TargetSource)null));
>                                 Advisor[] arr$ = advisor;
>                                 int len$ = advisor.length;
> 
>                                 for(int i$ = 0; i$ < len$; ++i$) {
>                                     Advisor avr = arr$[i$];
>                                     advised.addAdvisor(0, avr);
>                                 }
>                             }
> 
>                             PROXYED_SET.add(beanName);
>                             return bean;
>                         }
>                     }
>                 }
>             } catch (Exception var16) {
>                 throw new RuntimeException(var16);
>             }
>         }
>     }
> 
>     private MethodDesc makeMethodDesc(GlobalTransactional anno, Method method) {
>         return new MethodDesc(anno, method);
>     }
> 
>     private Class<?> findTargetClass(Object proxy) throws Exception {
>         if (AopUtils.isAopProxy(proxy)) {
>             AdvisedSupport advised = this.getAdvisedSupport(proxy);
>             Object target = advised.getTargetSource().getTarget();
>             return this.findTargetClass(target);
>         } else {
>             return proxy.getClass();
>         }
>     }
> 
>     private AdvisedSupport getAdvisedSupport(Object proxy) throws Exception {
>         Field h;
>         if (AopUtils.isJdkDynamicProxy(proxy)) {
>             h = proxy.getClass().getSuperclass().getDeclaredField("h");
>         } else {
>             h = proxy.getClass().getDeclaredField("CGLIB$CALLBACK_0");
>         }
> 
>         h.setAccessible(true);
>         Object dynamicAdvisedInterceptor = h.get(proxy);
>         Field advised = dynamicAdvisedInterceptor.getClass().getDeclaredField("advised");
>         advised.setAccessible(true);
>         return (AdvisedSupport)advised.get(dynamicAdvisedInterceptor);
>     }
> 
>     protected Object[] getAdvicesAndAdvisorsForBean(Class beanClass, String beanName, TargetSource customTargetSource) throws BeansException {
>         return new Object[]{this.interceptor};
>     }
> 
>     public void afterPropertiesSet() {
>         if (this.disableGlobalTransaction) {
>             if (LOGGER.isInfoEnabled()) {
>                 LOGGER.info("Global transaction is disabled.");
>             }
> 
>         } else {
>             this.initClient();
>         }
>     }
> }
> ```
The `GlobalTransactionScanner`  is your project config,It's not the one you sent，Like this

>   @Bean
    public GlobalTransactionScanner globalTransactionScanner(){
        return new GlobalTransactionScanner("account-gts-fescar-example", "my_test_tx_group");
    }

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
