### ISSUE TITLE
Can @GlobalTransaction be nested ?

### ISSUE THREAD

**Issue by tinycedar** [seata/seata#64]
Can we invoke a @GlobalTransaction annotated method from current @GlobalTransaction ?

**Comment by sharajava** [comment]
Yes. PROPAGATION should be REQUIRED by default.

**Comment by zhfeng** [comment]
@sharajava I think it is not the nest transaction. We can consider the following scenario:

```
GlobalTransaction tx1 = tm.begin();
tx1.branchRegister(branch1);

GlobalTransaction tx2 = tm.begin(); // tx2 will be the nest transaction
tx2.branchRegister(branch2); 

tx2.rollback(); // we just rollback the nest transaction.
tx1.commit(); // we can commit the parent transaction as well and it should be OK
```
So if the PROPAGATION_REQUIRED is added, I think tx1 and tx2 will be in the same global transaction.

**Comment by nikorliu** [comment]
> @sharajava I think it is not the nest transaction. We can consider the following scenario:
> 
> ```
> GlobalTransaction tx1 = tm.begin();
> tx1.branchRegister(branch1);
> 
> GlobalTransaction tx2 = tm.begin(); // tx2 will be the nest transaction
> tx2.branchRegister(branch2); 
> 
> tx2.rollback(); // we just rollback the nest transaction.
> tx1.commit(); // we can commit the parent transaction as well and it should be OK
> ```
> 
> So if the PROPAGATION_REQUIRED is added, I think tx1 and tx2 will be in the same global transaction.

这样不行，我在所有的方法都加上GlobalTransaction是不行
