### ISSUE TITLE
Can ordinary local transactions and global transactions be mixed?

### ISSUE THREAD

**Issue by zwjtech** [seata/seata#663]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
例如，有些事务只需要本地控制就行，不需要全局控制。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by skyesx** [comment]
* if  (talbes(or more specified--filed) in a transaction is a never participate in GlobalTransaction) 
    * treat it like normal local transaction.
* else 
    * if (your transaction only need to execute in local db)
         * use @GlobalLock to improve performance
    * else 
         * use @GlobalTransaction to execute full global transaction process
