### ISSUE TITLE
samples-dubbo-business-call  startup failed

### ISSUE THREAD

**Issue by myishuohuo** [seata/seata#674]
fescar-server-0.4.0.tar.gz
nacos-server-1.0.0-RC2.tar.gz
This is the version I used
![image](https://user-images.githubusercontent.com/31065623/55138731-1fe79080-516f-11e9-9996-f7b26612b312.png)

![image](https://user-images.githubusercontent.com/31065623/55138600-d0a16000-516e-11e9-927b-9177d33a1c84.png)

**Comment by myishuohuo** [comment]
When I run the  samples-dubbo-business-call service.My nacos service naming.log show
com.alibaba.nacos.api.exception.NacosException: instance already exist: 
192.168.43.244:unknown:DEFAULT_1.0_true_false_DEFAULT.
Why the port is unknown

**Comment by slievrly** [comment]
@myishuohuo Check if 2 services have been started.

**Comment by xingfudeshi** [comment]
please try the Fescar 0.4.1

**Comment by leizhiyuan** [comment]
you can try the new demo， If have other question, please reopen it.
