### ISSUE TITLE
What is the difference between MT mode and TCC?

### ISSUE THREAD

**Issue by MikeLC7** [seata/seata#676]
MT模式的实现逻辑是否就是TCC模式；两者都是通过业务Coding实现回滚和提交；

**Comment by slievrly** [comment]
MT==TCC

**Comment by pengle425** [comment]
TCC is a pattern, and MT is one of the implementations

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!
