### ISSUE TITLE
About shutdown gracefully

### ISSUE THREAD

**Issue by CoffeeLatte007** [seata/seata#679]
1.在这个 https://github.com/alibaba/fescar/pull/671 PR中，我已经优化了一版shutdown gracefully，但是正确的做法应该是把RpcServer中destory方法注册为我们的钩子，否则timerExecutor不能进行优雅的关闭。

2.接口RegistryService没有close()方法，我们的资源就会得不到及时的关闭

**Comment by github-ygy** [comment]
it ‘s ok， when u finished，ping or @ me

**Comment by slievrly** [comment]
@CoffeeLatte007 good job。
