### ISSUE TITLE
Is there a performance test?

### ISSUE THREAD

**Issue by jacky1193610322** [seata/seata#68]
Look at the official documentation that is high performance, so here is the approximate reference data? Or approximate performance data used inside Ali.
// 看官方文档说是高性能，那么这里有大概的参考数据吗？或者在阿里内部使用的大概性能数据。

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by sharajava** [comment]
Planning on performance test. It's hard to design a fairly enough case for transaction. 

Do you have any good idea on performance test? It will be great if you can join us.

**Comment by jacky1193610322** [comment]
I'm not having a good idea now, but I am willing to do something.

**Comment by devpage** [comment]
@jacky1193610322 赞
