### ISSUE TITLE
Can fescar0.4.0 be configured and registered with nacos0.9.0

### ISSUE THREAD

**Issue by sundong1982** [seata/seata#699]
nacos地址为192.168.1.102:8848

registry.conf

registry {
  type = "nacos"
  nacos {    
    serverAddr = "192.168.1.102"
    namespace = "public"
    cluster = "default"
  }
}
config {
  type = "nacos"
  nacos {
    serverAddr = "192.168.1.102"
    namespace = "public"
    cluster = "default"
  }
}

导入到nacos的配置与file.conf完全一样。改成type=file 没有问题 切换到nacos报错

2019-03-30 17:27:54.401 ERROR 18660 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.TmRpcClient    : no available server to connect.
2019-03-30 17:27:54.561 ERROR 18660 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.RmRpcClient    : no available server to connect.

**Comment by xingfudeshi** [comment]
Did you initialize the configuration for Nacos?if not,please follow instructions here https://github.com/fescar-group/fescar-workshop
In addition, please update fescar to the latest version 0.4.1.

**Comment by slievrly** [comment]
@sundong1982 please check nacos config key: service.vgroup_mapping.XXXXX, XXXXX will be as GlobalTransactionScanner the second param.

**Comment by sundong1982** [comment]
@xingfudeshi 升级到0.4.1报错变为 ERROR[timeoutChecker_1]c.a.fescar.core.rpc.netty.AbstractRpcRemotingClient.reconnect:337 -no available server to connect.

**Comment by sundong1982** [comment]
@slievrly 是启动的时候报错，还没有开始调用api，我试着加上注解@GlobalTransactional(timeoutMills = 300000, name = "my_test_tx_group") 依旧报错。

**Comment by sundong1982** [comment]
当我从type = "nacos"切换到type = "file" 运行正常
file配置为

transport {
  type = "TCP"
  server = "NIO"
  heartbeat = true
  thread-factory {
    boss-thread-prefix = "NettyBoss"
    worker-thread-prefix = "NettyServerNIOWorker"
    server-executor-thread-prefix = "NettyServerBizHandler"
    share-boss-worker = false
    client-selector-thread-prefix = "NettyClientSelector"
    client-selector-thread-size = 1
    client-worker-thread-prefix = "NettyClientWorkerThread"
    boss-thread-size = 1
    worker-thread-size = 8
  }
}
service {
  vgroup_mapping.my_test_tx_group = "serverRgroup"
  serverRgroup.grouplist = "192.168.1.102:8091"
  enableDegrade = false
  disable = false
  disableGlobalTransaction = false
}

client {
  async.commit.buffer.limit = 10000
  lock {
    retry.internal = 10
    retry.times = 30
  }
}

nacos配置为：
transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.thread-factory.boss-thread-prefix=NettyBoss
transport.thread-factory.worker-thread-prefix=NettyServerNIOWorker
transport.thread-factory.server-executor-thread-prefix=NettyServerBizHandler
transport.thread-factory.share-boss-worker=false
transport.thread-factory.client-selector-thread-prefix=NettyClientSelector
transport.thread-factory.client-selector-thread-size=1
transport.thread-factory.client-worker-thread-prefix=NettyClientWorkerThread
transport.thread-factory.boss-thread-size=1
transport.thread-factory.worker-thread-size=8
service.vgroup_mapping.my_test_tx_group=serverRgroup
service.serverRgroup.grouplist=192.168.1.102:8091
service.enableDegrade=false
service.disable=false
service.disableGlobalTransaction=false
client.async.commit.buffer.limit=10000
client.lock.retry.internal=10
client.lock.retry.times=30

**Comment by xingfudeshi** [comment]
@sundong1982 please paste the configuration of registry.conf and file.conf.both the fescar server side and sample side.

**Comment by sundong1982** [comment]
@xingfudeshi 代码在 https://github.com/sundong1982/spali.demo  registry.conf 和 file.conf在项目里  我用的jdk11     fescar-server端的配置文件在该项目里https://github.com/sundong1982/spali.demo/blob/master/fescar-server.zip

运行user-web即可

**Comment by xingfudeshi** [comment]
@sundong1982 ok.i will check.

**Comment by vergilyn** [comment]
相似问题，看了下0.4.1的源代码（并未理解）
`com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl#lookup`中`  List<Instance> firstAllInstances = getNamingInstance().getAllInstances(PRO_SERVER_ADDR_KEY, clusters);`，在调用nacos-api是，并未转换成serviceName，恒等于`serverAddr`。

另外就是clusters使用的是`service.vgroup_mapping.xx_tx_group=default`中的default，不理解为什么这么设计。

**Comment by sundong1982** [comment]
漏掉了
        <dependency>
            <groupId>com.alibaba.fescar</groupId>
            <artifactId>fescar-discovery</artifactId>
            <version>0.4.2</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fescar</groupId>
            <artifactId>fescar-config</artifactId>
            <version>0.4.2</version>
        </dependency>
加上后问题解决
