### ISSUE TITLE
Each microservice corresponds to one transaction group, or one microservice corresponds to one transaction group.

### ISSUE THREAD

**Issue by sundong1982** [seata/seata#700]
哪种更适合。

**Comment by xingfudeshi** [comment]
Sorry.i didn't catch your meaning.could describe your question in detail,please.

**Comment by slievrly** [comment]
@sundong1982 if each microservice's fescar trxServiceGroup is different, Only the beginning of the transaction trxServiceGroup function。

**Comment by sundong1982** [comment]
@slievrly 没有完全懂的的意思呢

**Comment by sundong1982** [comment]
@slievrly 我这样理解对不对，两种都可以，只是名称不同？

**Comment by slievrly** [comment]
> @slievrly 我这样理解对不对，两种都可以，只是每个微服务对应1个事务组，这种方式的名称不同？ 在实际项目中，你推荐用哪种方式呢？

两种都可以，但是如果一个服务链路上有2个不同的service group，这时只会按照事务发起方配置的service group算，即使走到了provider 也是连接第一个service group对应的server。如果可以确定服务节点只提供provider服务可以配置和consumer一样，不必再重新分配。如果服务节点也会独立发起事务那么可以配置一个新的service group。service group是用户实例名称会映射到后端集群名。

**Comment by sundong1982** [comment]
@slievrly 非常感谢您耐心的解答。
