### ISSUE TITLE
About Example

### ISSUE THREAD

**Issue by shang6107** [seata/seata#71]
There is an **com.alibaba.fescar.common.exception.FrameworkException : can not register RM,err:can not connect to fescar-server.** that displayed from console when BussinessServiceImpl.class running. However, fescar-server had already started and run.

**Comment by zhuzhuhong** [comment]
Whether to support remote fescar-server;If supported, how to configure?

**Comment by shang6107** [comment]
> Whether to support remote fescar-server;If supported, how to configure?

I think that configurate remote fescar-server just like locally, Specify your **application.conf#service#localRgroup.grouplist** in application.conf

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.

use the latest demo
