### ISSUE TITLE
run springcloud integrate fescar demo,xid is null

### ISSUE THREAD

**Issue by xieyeming** [seata/seata#710]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/fescar-example

I import  storage,account,business,order microservice into idea, then I add fescar-spring to pom.xml of storage,account,business,order microservice to solve dependency issue,then run the demo, xid is null
- fescar-server0.4.0
-mysql5.6

**Comment by JJS857012499** [comment]
me too, it see client don't begin a global transaction!

**Comment by leizhiyuan** [comment]
please use the master branch to test , It has been fixed 

If you have other questions, please reopen it.
