### ISSUE TITLE
Mistake Data From Example

### ISSUE THREAD

**Issue by shang6107** [seata/seata#72]
I made a break point at **com.alibaba.fescar.tm.dubbo.impl.AccountServiceImpl#debit**,  Found mistake data in order_tbl After resume that break point.

**Comment by shang6107** [comment]
one more order data

**Comment by shang6107** [comment]
> I have a similar problem.The "money" is -601 in account_tbl,and it's no use to restart BussinessService.

It's possible on money is -601, because example program without account money check code.

**Comment by shang6107** [comment]
I am not noticed on undo_log. Maybe abnormal

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
