### ISSUE TITLE
fescar-server-0.4.1 ERROR[main]com.alibaba.fescar.config.ConfigFuture.get:100 -config operation timeout,cost:5003 ms,op:GET,dataId:service.session.reload.read_size

### ISSUE THREAD

**Issue by MrLiuFang** [seata/seata#731]
从releases下载0.4.1，解压后未做任何改动，启动服务
./fescar-server.sh 8091 /development/opt/fescar-server/bin

报：ERROR[main]com.alibaba.fescar.config.ConfigFuture.get:100 -config operation timeout,cost:5003 ms,op:GET,dataId:service.session.reload.read_size

请问要如何解决

**Comment by xingfudeshi** [comment]
mark,i will check.

**Comment by slievrly** [comment]
@MrLiuFang If you do not read the default value, this configuration item will be added in the next release.
