### ISSUE TITLE
[optimize] seata have many chinese  comments

### ISSUE THREAD

**Issue by CoffeeLatte007** [seata/seata#732]
I've provided seta with a shell script to check for Chinese files that appear in.java files。
Many of these documents are annotated in Chinese and need to be translated into English by authors and community members
```
#! /bin/sh ~
if [ $# -ne 1 ]
	then echo "usage check_CN.sh <dir>"
	exit
fi
{
	function check(){
		for file in `ls $1`
		do
			if [ -d $1"/"$file ]
			then
				check $1"/"$file
			else
				local path=$1"/"$file
				local name=$file
				if [ "${name##*.}" != "java" ]
					then continue
				fi
				if [[ `cat $path | sed 's/[a-zA-Z0-9[:punct:]ø]//g' | grep -v '^[[:space:]]*$'` ]]
					then echo ""
						echo $path
				fi
				cat -n $path | sed 's/[a-zA-Z0-9[:punct:]ø]//g' | grep -v '^[[:space:]]*$'
			fi
		done
	}
}
check $1
```
use it :
```
sh check_CN.sh /Users/lizhao/Documents/seata
```

**Comment by KAMIJYOUDOUMA** [comment]
Anybody do this?I'd like to do it.

**Comment by CoffeeLatte007** [comment]
> Anybody do this?I'd like to do it.

now just update a little of chinese comments, i am looking forward to your help. Thank you

**Comment by Danaykap** [comment]
Hello!! Me and my partner kaitithoma want to contribute!! What can we do?

**Comment by CoffeeLatte007** [comment]
> Hello!! Me and my partner kaitithoma want to contribute!! What can we do?
you can remove this Chinese comments in code

**Comment by CoffeeLatte007** [comment]
> Hello!! Me and my partner kaitithoma want to contribute!! What can we do?

Thank you, you can remove these Chinese comments in code
