### ISSUE TITLE
In AT mode, how does seta handle transactions when rpc calls time out and TC control is lost?

### ISSUE THREAD

**Issue by rtj599** [seata/seata#736]
比如应用A和B，rpc用dubbo，A本地事务提交后调用B的接口，然而dubbo返回调用超时，此时TC和B的通讯中断。A并不知道B事务是否提交。此时若B的本地事务提交了，seata如何处理这种情况？

**Comment by slievrly** [comment]
A->B rpctimeout, will throw an exception rollback

**Comment by rtj599** [comment]
> 
> 
> A->B rpctimeout, will throw an exception rollback

Then B will rollback,too because of connection lost with TC?

**Comment by slievrly** [comment]
> Then

because of microservice call timeout or @GlobalTransactional timeout

**Comment by rtj599** [comment]
THX

**Comment by rtj599** [comment]
> 
> 
> > Then
> 
> because of microservice call timeout or @GlobalTransactional timeout

THX

**Comment by maverickswin** [comment]
Hi,

I have a similar question:

I run the seata_sample and let it time out. Then there is an item on lock_table:
{table_name: t_storage, Pk: 1}

And there is an undo_log item with status 0, which is not rollback yet:
{
  "branchId": 2015348659,
  "sqlUndoLogs": [
    {
      "afterImage": {
        "rows": [
          {
            "fields": [
              {
                "keyType": "PrimaryKey",
                "name": "id",
                "type": 4,
                "value": 1
              },
              {
                "keyType": "NULL",
                "name": "count",
                "type": 4,
                "value": 992
              }
            ]
          }
        ],
        "tableName": "t_storage"
      },
      "beforeImage": {
        "rows": [
          {
            "fields": [
              {
                "keyType": "PrimaryKey",
                "name": "id",
                "type": 4,
                "value": 1
              },
              {
                "keyType": "NULL",
                "name": "count",
                "type": 4,
                "value": 993
              }
            ]
          }
        ],
        "tableName": "t_storage"
      },
      "sqlType": "UPDATE",
      "tableName": "t_storage"
    }
  ],
  "xid": "192.168.56.1:8091:2015348652"
}

How can I rollback this and release the lock?
