### ISSUE TITLE
The UUID might be duplicated

### ISSUE THREAD

**Issue by CoffeeLatte007** [seata/seata#738]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
The UUID might be duplicated.The logical implementation of UUIDGenerator is incorrect

**Comment by slievrly** [comment]
i will fix later

**Comment by xingfudeshi** [comment]
Is this problem optimized？

**Comment by leizhiyuan** [comment]
it seems fixed in d1d14b33c1846fa5c675e189ee2a06288ace11ec

I will close it , If you have other questions, you can reopen it.
