### ISSUE TITLE
what is the relationship between Alibaba GST and Fescar? thanks.

### ISSUE THREAD

**Issue by Kiddinglife** [seata/seata#74]

**Comment by shang6107** [comment]
[https://github.com/alibaba/fescar/wiki/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4%E5%BC%80%E6%BA%90%E5%88%86%E5%B8%83%E5%BC%8F%E4%BA%8B%E5%8A%A1%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88-FESCAR](url) 2.Fescar 的发展历程

**Comment by shang6107** [comment]
[https://github.com/alibaba/fescar/wiki/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4%E5%BC%80%E6%BA%90%E5%88%86%E5%B8%83%E5%BC%8F%E4%BA%8B%E5%8A%A1%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88-FESCAR](url)

**Comment by leizhiyuan** [comment]
as @shang6107   said, you can check it.

because of no update for a long time, I will close the issue, if you have other questions, please reopen it or create a new one
