### ISSUE TITLE
0.4.1 Possible bugs with global update operations

### ISSUE THREAD

**Issue by lynk-coder** [seata/seata#740]
Today I came across A situation, when A requested B, B only handled the update operation, after A threw an exception, B's update operation was not withdrawn.This only happens the first time the project is launched, and it won't happen again.

**Comment by xingfudeshi** [comment]
Please provide a demo that can reproduces this bug.thanks.

**Comment by lynk-coder** [comment]
I'm sorry, but this did happen before, causing the first global transaction after the project was started to fail.(using nacos 1.0.0-rc3 Server, SpringCloud RestTmplate)
Now use back eureka, and somehow that won't happen again.
I need to look again.
Thanks a million.

**Comment by xingfudeshi** [comment]
Does this happen every time when project is started?

**Comment by lynk-coder** [comment]
Yes, that was the case, but the insertion was normal.Only the first update operation causes the update not to be rolled back.
Additional topics: can "undo" tables be managed in other databases?Because by default our database users are not allowed to delete.



kunloz520@163.com
 
发件人： xingfudeshi
发送时间： 2019-04-08 18:30
收件人： seata/seata
抄送： lynk; Mention
主题： Re: [seata/seata] 0.4.1 关于全局更新操作可能存在的bug（0.4.1） (#740)
Does this happen every time when project is started?

**Comment by xingfudeshi** [comment]
@lynk-coder you have to keep the undo_log table with the same database.and for the situation your described,i will check and fix it soon.thanks for reporting.

**Comment by xingfudeshi** [comment]
only occurs with nacos？

**Comment by lynk-coder** [comment]
What happens is that when nacos is used, the RestTemplate is used for data passing.
(using nacos 1.0.0-rc3 Server, SpringCloud RestTmplate)


Here are some of the interceptors

public class FescarHandlerInterceptor extends HandlerInterceptorAdapter {

    private static final LogUtil log = LogUtil
            .init(FescarHandlerInterceptor.class);

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response,
                             Object handler) throws Exception {

        if(!DBConfig.disableGlobalTransaction) {
            String xid = RootContext.getXID();
            String rpcXid = request.getHeader(RootContext.KEY_XID);
            log.debug("xid in RootContext {} xid in RpcContext {}", xid, rpcXid);


            if (xid == null && rpcXid != null) {
                RootContext.bind(rpcXid);
                log.debug("bind {} to RootContext", rpcXid);
            }
        }
        return true;
    }

    @Override
    public void afterCompletion(HttpServletRequest request, HttpServletResponse response,
                                Object handler, Exception e) throws Exception {

        if(!DBConfig.disableGlobalTransaction) {
            String rpcXid = request.getHeader(RootContext.KEY_XID);

            if (StringUtils.isEmpty(rpcXid)) {
                return;
            }

            String unbindXid = RootContext.unbind();
            log.debug("unbind {} from RootContext", unbindXid);
            if (!rpcXid.equalsIgnoreCase(unbindXid)) {
                log.warn("xid in change during RPC from {} to {}", rpcXid, unbindXid);
                if (unbindXid != null) {
                    RootContext.bind(unbindXid);
                    log.warn("bind {} back to RootContext", unbindXid);
                }
            }
        }
    }

}

**Comment by xingfudeshi** [comment]
Actually, neither nacos nor eureka is involved in any global transactions. Are you sure you can only have this problem with nacos? thanks.

**Comment by xingfudeshi** [comment]
can you paste some logs ?

**Comment by lynk-coder** [comment]
There are so many changes now, there is no way to reproduce the problem in the afternoon, logs certainly not.
I have read the source code and understand that the project has nothing to do with nacos. I just want to explain the environment in which this happens to me, but such problems do occur.
I am wondering whether the Fescar initialization time is greater than the resttemplate end time when the project is just started and called for the first time, and it will be "unbing xid", resulting in the problem that the first update is not rolled back.

**Comment by lynk-coder** [comment]
But I'm still confused.Why not roll back only the first update?
This problem was tested many times, but after I switched to eureka, it didn't recur.

**Comment by xingfudeshi** [comment]
but insert operation is ok?

**Comment by lynk-coder** [comment]
yes！

**Comment by xingfudeshi** [comment]
I tried what you said, but I didn't find any problem. I'll keep my eye on it.it will be great if you can provide a demo to reproduce this problem.

**Comment by slievrly** [comment]
thanks @lynk-coder @xingfudeshi report the problem

**Comment by lynk-coder** [comment]
Wait a minute, I'll try it. How do I do it again

**Comment by lynk-coder** [comment]
I found another problem that if my service A - > B (RestTemplate), if A service restart, B service does not restart, at the moment of startup is completed (probably Fescar RPC not connected) direct access to the services A, will lead to service A countless times repeat request service B, and the agent's data source appears to be invalid, unable to request to the data from A database, will enter the jam.

![QQ截图20190410112631](https://user-images.githubusercontent.com/23651124/55849554-9e86f980-5b83-11e9-9e24-e1f173264a9a.png)

**Comment by zhenjing** [comment]
> I found another problem that if my service A - > B (RestTemplate), if A service restart, B service does not restart, at the moment of startup is completed (probably Fescar RPC not connected) direct access to the services A, will lead to service A countless times repeat request service B, and the agent's data source appears to be invalid, unable to request to the data from A database, will enter the jam.

can you provide a demo?
