### ISSUE TITLE
Research on the Design of AT and MT Mode Principles

### ISSUE THREAD

**Issue by upcwangying** [seata/seata#762]
Why the AT mode is based on a relational database that supports local ACID transactions, 
and the MT mode does not rely on transaction support for the underlying data resources. 
For example, the MT mode two-phase rollback operates on multiple tables, 
which is still dependent on local transactions. Does anyone explain in detail?
![QQ截图20190411094353](https://user-images.githubusercontent.com/19725091/55924934-5bd62780-5c3e-11e9-8ea7-907aba0b48f4.png)

**Comment by CoffeeLatte007** [comment]
If certain resources do not have ACID transactions, you can use MT, otherwise use AT. The AT does not need to define rollback logic.
In a GlobalTranscation, you can mix MT and AT。
