### ISSUE TITLE
record did not rollback automatically

### ISSUE THREAD

**Issue by xieyeming** [seata/seata#763]
every micro service has own database,a->b->c,in service b,between invoked service c and excuted local transaction,i closed service c and  run the code to the end,then i restarted service c,the data of c in its own database did not rollback

**Comment by CoffeeLatte007** [comment]
Can u give me more information?
Even if you shut down the service, as long as you reopen, TC will try again.

**Comment by xieyeming** [comment]
I test  based on fescar-spring 0.4.1 and seata-server0.4.1. I set each service has its own databse and modify the code. In order service, i add the breakpoint  below  the 
 function "invokerAccountService" and throw the exception brefore excute local transaction. After  funtion of invokerAccountService has excuted, data has updated in database of  storage service. Then I close the storage service and go on the code to the end in order service, order service throw the exception,then I reopen the storage service,the data in storage service did not rollback.
the code in order service is:
@RequestMapping(value = "/order", method = RequestMethod.POST, produces = "application/json")
    public String order(String userId, String commodityCode, int orderCount) {
        LOGGER.info("Order Service Begin ... xid: " + RootContext.getXID());

        int orderMoney = calculate(commodityCode, orderCount);

        invokerAccountService(orderMoney);

        int a=1;
        int b=1;
        if(a == b){
            throw new RuntimeException("this is a mock Exception");
        }
        final Order order = new Order();
        order.userId = userId;
        order.commodityCode = commodityCode;
        order.count = orderCount;
        order.money = orderMoney;

        KeyHolder keyHolder = new GeneratedKeyHolder();

        int result = jdbcTemplate.update(new PreparedStatementCreator() {

            @Override
            public PreparedStatement createPreparedStatement(Connection con)
                    throws SQLException {
                PreparedStatement pst = con.prepareStatement(
                        "insert into order_tbl (user_id, commodity_code, count, money) values (?, ?, ?, ?)",
                        PreparedStatement.RETURN_GENERATED_KEYS);
                pst.setObject(1, order.userId);
                pst.setObject(2, order.commodityCode);
                pst.setObject(3, order.count);
                pst.setObject(4, order.money);
                return pst;
            }
        }, keyHolder);

        order.id = keyHolder.getKey().longValue();

//        if (random.nextBoolean()) {
//            throw new RuntimeException("this is a mock Exception");
//        }

        LOGGER.info("Order Service End ... Created " + order);

        if (result == 1) {
            return SUCCESS;
        }
        return FAIL;
    }

**Comment by CoffeeLatte007** [comment]
Where is @GlobalTransactional , the method which is used @GlobalTransactional should throw Exception

**Comment by slievrly** [comment]
#770

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
