### ISSUE TITLE
There are Chinese descriptions in seata

### ISSUE THREAD

**Issue by rtj599** [seata/seata#764]
the followings are the list of classes which contain Chinese words:
com.alibaba.fescar.common.exception.FrameworkErrorCode
com.alibaba.fescar.core.rpc.netty.AbstractRpcRemoting(line 343)
com.alibaba.fescar.rm.datasource.sql.SQLType(line 95,line103,line 204)
com.alibaba.fescar.common.loader.EnhancedServiceLoader

**Comment by CoffeeLatte007** [comment]
https://github.com/seata/seata/issues/732 There is a shell script in this issue，It can scan all the Chinese documents.If you are interested, please support some pull requests for us.

**Comment by rtj599** [comment]
ok,I'll try it.
