### ISSUE TITLE
How to view deadlocks and kill？

### ISSUE THREAD

**Issue by vergilyn** [seata/seata#766]
最近在学习时，发现会出现LockConflictException。（具体复现流程暂时还不是很清晰）
产生原因是fescar-server中并未并未释放pks对应的锁。
然而fescar的锁是基于concurrent实现，那么如何知道持锁情况和释放死锁？

(sorry, my english is poor )
Recently while studying, a LockConflictException was found.(the specific reproduction process is not clear yet)
The reason is that the lock corresponding to PKS is not released in fescar-server.
However, fescar's lock is based on the concurrent implementation, so how do you know about lock holding and release deadlocks?

**Comment by CoffeeLatte007** [comment]
The key for the globalLock is the primary key for each row in the database.There is currently no monitoring to monitor globalLocks.If u want, u can see the DefaultLockManagerImpl.java. break a point to LOCK_MAP

**Comment by vergilyn** [comment]
> The key for the globalLock is the primary key for each row in the database.There is currently no monitoring to monitor globalLocks.If u want, u can see the DefaultLockManagerImpl.java. break a point to LOCK_MAP

thx，Hopefully in the future a design like redisson's will avoid deadlocks

**Comment by CoffeeLatte007** [comment]
> > The key for the globalLock is the primary key for each row in the database.There is currently no monitoring to monitor globalLocks.If u want, u can see the DefaultLockManagerImpl.java. break a point to LOCK_MAP
> 
> thx，Hopefully in the future a design like redisson's will avoid deadlocks

Seata already avoid deadlock. lock mode is fast fail and try many times
