### ISSUE TITLE
different with Atomikos?

### ISSUE THREAD

**Issue by liurenjin** [seata/seata#77]
1 Spring Boot supports distributed JTA transactions   by using either an Atomikos or Bitronix ,what's the differences with fescar 
2 RocketMQ  used as  transaction messages in fescar  is about to release as v1.5.x , and  do we have the deadline, few months? 
ref links:
1 https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-jta.html
2 https://stackoverflow.com/questions/31634475/does-apache-tomcat-6-support-jta
3 https://stackoverflow.com/questions/2552612/how-to-use-jta-support-in-tomcat-6-for-hibernate

**Comment by sharajava** [comment]
1. JTA is XA in Java. Fescar was born when XA was a heavy solution. Fescar designed a transaction protocol which was different from XA. Fescar does NOT require the underlying databases to support  XA. In the feature, Fescar will also provide a XA solution. Atomikos and Bitronix are great projects for us to learn. BTW, if you have interest in JTA implementation without Application Server, it'll be great if you can join us.

2. GA release is planned to be published in 3 month. Feature of supporting RocketMQ will be released later.

**Comment by zhfeng** [comment]
It could be also considered to use the [Narayana ](http://narayana.io) as the JTA Transaction Manager.

**Comment by jyizheng** [comment]
I am interested in JTA implementation without Application Server.
