### ISSUE TITLE
Use TCC under Spring Boot Dubbo

### ISSUE THREAD

**Issue by ShootMooN** [seata/seata#773]
尝试在Spring Boot Dubbo下使用TCC，但服务提供方收到的BusinessActionContext为null。
将Spring Boot换成Spring，改用xml配置就没有问题。
调试后发现Spring里获得的dubbo service是经过cglib字节码增强的，但Spring Boot下通过@Reference注解得到的就不是。尝试在Spring Boot下改用xml配置的方式获得dubbo service，但并没有用。求问大神有什么解决方法。

**Comment by ShootMooN** [comment]
#857

**Comment by leizhiyuan** [comment]
has been fixed in https://github.com/seata/seata/pull/866 

I will close the issue, if you have other questions, please reopen it or create a new one
