### ISSUE TITLE
Configure branchReport retry times

### ISSUE THREAD

**Issue by leizhiyuan** [seata/seata#782]
## Why you need it?

Configure branchReport retry times

![image](https://user-images.githubusercontent.com/2684384/56077728-4b76a600-5e12-11e9-8c78-62b95b31c1af.png)

## How it could be?

maybe 

```
    <bean id="orderDataSourceProxy" class="com.alibaba.fescar.rm.datasource.DataSourceProxy">
        <constructor-arg ref="orderDataSource"/>
    </bean>
```
we can set a key like 'branch.report.times', then we can get the times for ConnectionProxy

from 

```
  /**
     * Instantiates a new Connection proxy.
     *
     * @param dataSourceProxy  the data source proxy
     * @param targetConnection the target connection
     */
    public ConnectionProxy(DataSourceProxy dataSourceProxy, Connection targetConnection) {
        super(dataSourceProxy, targetConnection);
        dataSourceProxy.getparameter("branch.report.times");
    }
```

**Comment by CoffeeLatte007** [comment]
In the future, we will continue to provide this custom configuration.
If you are interested, you can also submit one pull request.

**Comment by leizhiyuan** [comment]
ok, I will pr later
