### ISSUE TITLE
globalSession getSortedBranches do not work

### ISSUE THREAD

**Issue by leizhiyuan** [seata/seata#787]
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

maybe we forget to sort it? if you can confirm this, I will fix it.

### Ⅱ. Describe what happened

getSortedBranches forget to invoke `Collections.sort` because I can see  `getReverseSortedBranches` is ok

### Ⅲ. Describe what you expected to happen

you can see the test case

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

```
  @Test
    public void testSort(){
        GlobalSession globalSession = new GlobalSession("demo-app", "my_test_tx_group", "test", 6000);

        BranchSession branchSession2 = new BranchSession();
        branchSession2.setBranchId(2);
        globalSession.add(branchSession2);

        BranchSession branchSession1 = new BranchSession();
        branchSession1.setBranchId(1);
        globalSession.add(branchSession1);

        BranchSession branchSession3 = new BranchSession();
        branchSession3.setBranchId(3);
        globalSession.add(branchSession3);

        ArrayList<BranchSession> result = globalSession.getSortedBranches();
        Assert.assertEquals(1,result.get(0).getBranchId());

    }
```

### Ⅴ. Anything else we need to know?

version 0.4.2

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by CoffeeLatte007** [comment]
yes ,it should be sorted. Thank you!

**Comment by leizhiyuan** [comment]
ok, I will pr for it
