### ISSUE TITLE
Change the startup parameters of seata-server to support database-storage

### ISSUE THREAD

**Issue by zhangthen** [seata/seata#789]
## Why you need it?

The startup parameters of seata-server is "${port}  ${file-path} ${ip}",  which is  prepared for file-storage.
Now we need to add  database-storage, and need a parameter to specify whether the storage is  file or a database

## How it could be?

I will change the startup parameters of seata-server to "${port}  ${store-mode} ${ip}", and add the file-config or database-config into the file.conf.

**Comment by leizhiyuan** [comment]
thanks,it has done.
