### ISSUE TITLE
NullPointerException occured when using @GlobalTransactional and SQL with 'union all'

### ISSUE THREAD

**Issue by lmcboy** [seata/seata#794]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Service interface use @GlobalTransactional，and there are three sqls in it. First two of them has succeed. But when run the third sql，it throw a NullPointerException.

### Cause: java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null

### Ⅲ. Describe what you expected to happen
run succeed.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

Debug sure that is relative with SQLUnionQuery class.
Bug will happend when i use like:
select * from table1 union all select * from table2
when i change the sql to
select t.* from (select * from table1 union all select * from table2) t

### Ⅴ. Anything else we need to know?
none

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows
- Others: Spring cloud 1.5.3 + Mybatis

**Comment by liujianhuiouc** [comment]
please paste the full stack trace

**Comment by xingfudeshi** [comment]
thanks for reporting.it's a bug.i will fix it
