### ISSUE TITLE
Change groupId,artifactId, and package in 0.5.0

### ISSUE THREAD

**Issue by zhangthen** [seata/seata#806]
## Why you need it?

Rename Fescar to Seata

## How it could be?

Change groupId from  com.alibaba.fescar to io.seata

Change artifactId from  fescar-* to seata-*

Change package from  com.alibaba.fescar.* to io.seata.*

**Comment by rtj599** [comment]
why to change package name from 'com.alibaba' to 'io', and what's the meaning of 'io'?

**Comment by zhangthen** [comment]
> why to change package name from 'com.alibaba' to 'io', and what's the meaning of 'io'?

https://github.com/seata/seata/issues/670
