### ISSUE TITLE
[Question] what is the purpose of updateChannelsResource in ChanenlManager

### ISSUE THREAD

**Issue by liujianhuiouc** [seata/seata#810]
- [ ] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
the method `updateChannelsResource` want to add a RpcContext whose resource id is different from the one in RM_CHANNELS
```
 private static void updateChannelsResource(String resourceId, String clientIp, String applicationId) {
        ConcurrentMap<Integer, RpcContext> sourcePortMap = RM_CHANNELS.get(resourceId).get(applicationId).get(clientIp);
        for (ConcurrentMap.Entry<String, ConcurrentMap<String, ConcurrentMap<String, ConcurrentMap<Integer,
            RpcContext>>>> rmChannelEntry : RM_CHANNELS.entrySet()) {
            if (rmChannelEntry.getKey().equals(resourceId)) { continue; }
            ConcurrentMap<String, ConcurrentMap<String, ConcurrentMap<Integer,
                RpcContext>>> applicationIdMap = rmChannelEntry.getValue();
            if (!applicationIdMap.containsKey(applicationId)) { continue; }
            ConcurrentMap<String, ConcurrentMap<Integer,
                RpcContext>> clientIpMap = applicationIdMap.get(applicationId);
            if (!clientIpMap.containsKey(clientIp)) { continue; }
            ConcurrentMap<Integer, RpcContext> portMap = clientIpMap.get(clientIp);
            for (ConcurrentMap.Entry<Integer, RpcContext> portMapEntry : portMap.entrySet()) {
                Integer port = portMapEntry.getKey();
                if (!sourcePortMap.containsKey(port)) {
                    RpcContext rpcContext = portMapEntry.getValue();
                    sourcePortMap.put(port, rpcContext);
                    rpcContext.holdInResourceManagerChannels(resourceId, port);
                }
            }
        }
    }
```
what the purpose of the line `sourcePortMap.put(port, rpcContext);`,the resource id of that rpcContext is differenct from the resouce id relate to sourcePortMap. and i guess that method is wrong and is unnecessary
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by CoffeeLatte007** [comment]
maybe one machine has many clients, need record other client port.
if one of client channel close,we can use other channel

**Comment by liujianhuiouc** [comment]
> maybe one machine has many clients, need record other client port.
> if one of client channel close,we can use other channel

i guess the origin ideas of the method as you said, actually RpcContext add a differenct resource id's rpc context in it.
`if (rmChannelEntry.getKey().equals(resourceId)) { continue; }` the line said the resouce id in param in method is not same to the ` RpcContext rpcContext = portMapEntry.getValue();`, i think it's a bug, furthermore, the method `registerRMChannel` has already done what you said
