### ISSUE TITLE
In ExecuteTemplate.java line ,new a SQLException but not throw it, is it a matter?

### ISSUE THREAD

**Issue by zhjuntao** [seata/seata#816]
### Ⅰ. Issue Description
In ExecuteTemplate.java line 109 ,new a SQLException but not throw it, is it a matter?

     try {
                rs = executor.execute(args);

        } catch (Throwable ex) {
            if (ex instanceof SQLException) {
                throw (SQLException)ex;
            } else {
                // Turn everything into SQLException
                new SQLException(ex);
            }
        }

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by github-ygy** [comment]
it is a bug.
