### ISSUE TITLE
How to control transaction propagation  in the service invocation pipeline

### ISSUE THREAD

**Issue by hylitjob** [seata/seata#82]
How to control transaction propagation  in the service invocation pipeline, for case in DDD model, I don't want sub procedure to rollback when encounter exception

**Comment by sharajava** [comment]
Basically, you can use API:

`
// before sub procedure call
String xid = RootContext.unbind();

// Do you sub procedure call

RootContext.bind(xid);
`

No sure if I got your point. There should be a better way of controlling propagation. It's great if you can share your suggestions.
