### ISSUE TITLE
Use Protobuf  as the codec of RPC 

### ISSUE THREAD

**Issue by leizhiyuan** [seata/seata#823]
## Why you need it?

protocol buffers are Google's language-neutral, platform-neutral, extensible mechanism for serializing structured data. 

you can assign to me

## How it could be?

I will design and pr this feature

```
 * 0     1     2     3     4           6           8          10           12          14         16
 * +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
 * |   0xdada  |   flag    | typecode/ |                 requestid                     |           |
 * |           |           | bodylength|                                               |           |
 * +-----------+-----------+-----------+-----------+-----------+-----------+-----------+           +
 * |                                    ... ...                                                    |
 * +                                                                                               +
 * |                                     body                                                      |
 * +                                                                                               +
 * |                                    ... ...                                                    |
 * +-----------------------------------------------------------------------------------------------+
 *
```

now, the RPC protocol like this, there has some extra preserved codec for Hessian, we will use this for PB, because hessian is only for Java. Protostuff is not a good way for the future

but notice body length occupies 2 bytes, about 32767 bytes,32k, we can think it is enough for now.

if so

## Encode:

 in the part of body , I will write body=serializeType(1byte)+classNameLength(2bytes)+className(clazzNameLength bytes)+encode(requestObject)

## Decode:

if not SeataCodec, I will read ClassName,load ,then parseFrom data

## For Request Object

I think we should write some protobuf file to define these class which implements MessageCodec.

When serialize switch is ok,  we will translate these classes to corresponding protobuf class， then write to server or back。

## Time Point

I prefer to translate class in MessageCodecHandler ，the changes are small，if it is ok later， we can remove MessageCodec and use these protobuf class to write our code。

Phase 1
![Phase 1](https://user-images.githubusercontent.com/2684384/56369279-a271e600-622b-11e9-95ed-c79a324dc521.png)

Phase 2
![Phase 2](https://user-images.githubusercontent.com/2684384/56369299-ae5da800-622b-11e9-9d39-efd3399f159a.png)

## Other related information

nope

**Comment by github-ygy** [comment]
Looking forward to your pull request ！

**Comment by leizhiyuan** [comment]
please review for the design ，If ok， I will pr for phase 1

**Comment by github-ygy** [comment]
> please review for the design ，If ok， I will pr for phase 1

it is ok to me，can u ding talk ping us and join our small group？

**Comment by leizhiyuan** [comment]
> > please review for the design ，If ok， I will pr for phase 1
> 
> it is ok to me，could u please ding talk ping us and join our small group？

what is your dingtalk id?

**Comment by CoffeeLatte007** [comment]
Does the design remove  MergedWarpMessage encode?

**Comment by leizhiyuan** [comment]
> Does the design remove MergedWarpMessage encode?

It seems MergedWarpMessage for batch process。Let me see how to process this class which contains many other message。

**Comment by CoffeeLatte007** [comment]
> > Does the design remove MergedWarpMessage encode?
> 
> It seems MergedWarpMessage for batch process。Let me see how to process this class which contains many other message。
> I will update later

ok

**Comment by github-ygy** [comment]
> > > please review for the design ，If ok， I will pr for phase 1
> > 
> > 
> > it is ok to me，could u please ding talk ping us and join our small group？
> 
> what is your dingtalk id?

gr3n4d4

**Comment by leizhiyuan** [comment]
> > > > please review for the design ，If ok， I will pr for phase 1
> > > 
> > > 
> > > it is ok to me，could u please ding talk ping us and join our small group？
> > 
> > 
> > what is your dingtalk id?
> 
> gr3n4d4

ping you，please check your 'add friend request '

**Comment by slievrly** [comment]
@leizhiyuan good job.

**Comment by leizhiyuan** [comment]
use any may can process MergedWarpMessage  https://developers.google.com/protocol-buffers/docs/proto3#any 

I will test it

**Comment by leizhiyuan** [comment]
io.seata.core.protocol.protobuf.MergeMessageTest
io.seata.core.rpc.netty.MessageCodecHandlerTest

please review these cases for merged model and basic usage for pb，if ok ， I will continue

@slievrly @CoffeeLatte007 @github-ygy

**Comment by CoffeeLatte007** [comment]
> io.seata.core.protocol.protobuf.MergeMessageTest
> io.seata.core.rpc.netty.MessageCodecHandlerTest
> 
> please review these cases for merged model and basic usage for pb，if ok ， I will continue
> 
> @slievrly @CoffeeLatte007 @github-ygy
I forgot to mention that we need a compression to improve transport‘s performance

**Comment by leizhiyuan** [comment]
maybe the compression feature should after https://github.com/seata/seata/issues/893
