### ISSUE TITLE
seat0.4.2 spring cloud mybatis can not return AUTO_INCREMENT ID

### ISSUE THREAD

**Issue by vikenlove** [seata/seata#854]
i have two service A & B  in my consumer controller .
`
	@PostMapping("/saveAndUpdate")
	@GlobalTransactional(timeoutMills = 300000, name = "spring-cloud-demo-tx")
	public String saveAndUpdate(){
		
		// 调用A 服务  简单save
		ResponseData<Integer> result = demoFeignClient.insertService("test234",111);
		
		if(result.getStatus()==400) {
			System.out.println(result+"+++++++++++++++++++++++++++++++++++++++");
			throw new RuntimeException("this is error1");
		}
		//B 服务，内部先insert 后update ，通过@Transactional 管理 service 内部 事务
		ResponseData<Object> result2 = demoFeignClient2.saveAndUpdate();
		
		if(result2.getStatus()==400) {
			System.out.println(result+"++++");
			throw new RuntimeException("errors mulitpart");
		}
		return "SUCCESS";
	}
	`
there is  a location transactional in B service .
`	/**
	 *  开启本地事务
	 */
	@Transactional
	public void saveAndUpdate() {
		//先保持 后修改
		UserModel record = new UserModel();
		record.setName("年龄修改");
		record.setAge(12);
		userModelMapper.insertSelective(record);
		
		**Integer id = record.getId();**
	
		System.out.println(id+"------------------------------------");
		
		//修改操作
		UserModel record2 = new UserModel();
		record2.setName("tis is test");
		record2.setAge(24);
		record2.setId(id);
		userModelMapper.updateByPrimaryKey(record2);
		//userModelMapper.updateByPrimaryKeySelective(record2);
	}
	`
the mybatis SQL is 
  <insert id="insert" parameterType="com.emerging.service.persistence.model.UserModel">
 
    <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
      SELECT LAST_INSERT_ID()
    </selectKey>
    insert into t_user (name, age, type, 
      create_date)
    values (#{name,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER}, #{type,jdbcType=VARCHAR}, 
      #{createDate,jdbcType=TIMESTAMP})
  </insert>

the issue is  :
  if you insert into DB ,you reuturn ID should 10 .but it is not return 10 .

**Comment by slievrly** [comment]
@slievrly mark

**Comment by xingfudeshi** [comment]
duplicate with #934
