### ISSUE TITLE
0.4.2 use my definition exception,transaction rollbacked,but undo_log has not been deleted

### ISSUE THREAD

**Issue by JohnAddison** [seata/seata#862]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
fescar version: 0.4.2
If i use my own definition exception extends RuntimeException; transaction rollbacked,but undo_log has not been deleted。 
And RuntimeException happening, fescar worked normally.
### Ⅱ. Describe what happened
![image](https://user-images.githubusercontent.com/25993672/56467485-08d84d80-6452-11e9-8c14-a8bc3da233c3.png)
![image](https://user-images.githubusercontent.com/25993672/56467487-1392e280-6452-11e9-882d-c7ae16b8a3b4.png)

### Ⅲ. Describe what you expected to happen
if transaction rollbacked, undo_log should be deleted.

### Ⅵ. Environment:

- JDK version :1.8
- OS :10.14.4 (18E226)
- Others:

**Comment by xingfudeshi** [comment]
this bug has been fixed.pls upgrade the version of seata to 0.5.0.
