### ISSUE TITLE
0.5.0 restart after content in the service method is modified, resulting in blocking of requesting service

### ISSUE THREAD

**Issue by lynk-coder** [seata/seata#863]
I found a particularly strange problem.
A - > B requests
A changes the content of the method in A service and restarts it
B don't restart
This causes the A-> B request to block timeout (the error reported is at the DruidDataSource getConnection)
But when B also restarts, normal communication can resume.

This has been the case in all previous versions, but the pattern has never been found.
Now the pattern of this problem has been discovered by me.And submit an associated error log.

[error-log.04-21.log](https://github.com/seata/seata/files/3101141/error-log.04-21.log)

Development framework：
Springboot 2.x
Springcloud Finchley.SR2
Nacos discover 1.0.0
Mybatis 3.4.4

**Comment by lynk-coder** [comment]
Without modifying the code in the service method, it is not a problem to restart either service.
But even if a method adds a carriage return, both services need to be restarted to execute.

**Comment by slievrly** [comment]
mark

**Comment by lynk-coder** [comment]
Use RestTemplate

**Comment by lynk-coder** [comment]
A service and B service error logs are the same

**Comment by slievrly** [comment]
@lynk-coder if use spring cloud alibaba seata-sample，can reproduced？

**Comment by lynk-coder** [comment]
I haven't used demo to run it yet, but I believe I have seen the project and the structure is relatively simple. There should be no problem. I will try it when I am free.




On 04/22/2019 14:47, jimin wrote:

@lynk-coder if use spring cloud alibaba seata-sample，can reproduced？

**Comment by lynk-coder** [comment]
I've identified the problem.
It's not seata's problem, but my IDEA project
The structure of module A and module B is exactly the same.As A result, I changed the service of A, but somehow the service of B was also overwritten in memory.It then leads to an infinite request for itself.
Thank you very much!
