### ISSUE TITLE
how to use seata 0.5.0?

### ISSUE THREAD

**Issue by mostcool** [seata/seata#864]
how to use seata 0.5.0?

seata-server.bat  running error :

2019-04-21 19:37:34.367 INFO [main]io.seata.common.loader.EnhancedServiceLoader.loadFile:193 -load ConfigurationProvider[Nacos] extension by class[io.seata.config.nacos.NacosConfigurationProvider]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.seata.core.rpc.netty.RpcServer.<init>(RpcServer.java:87)
        at io.seata.server.Server.main(Server.java:54)
Caused by: java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236)
        at io.seata.core.rpc.netty.TransportProtocolType.valueOf(TransportProtocolType.java:25)
        at io.seata.core.rpc.netty.NettyBaseConfig.<clinit>(NettyBaseConfig.java:114)
        ... 2 more

**Comment by zhangthen** [comment]
pom 里面手动加一下  seata-config-nacos的包依赖

**Comment by warrior2005** [comment]
> Manually add seata-config-naco dependency to the pom.xml

Same problem here.
@zhangthen What did you mean by add a dependency? There is no pom.xml in the **release** package.

**Comment by publisherfk** [comment]
Same problem here too!

**Comment by zhangthen** [comment]
What is the value of "transport.type" ?

Must be one of  TransportProtocolType.

**Comment by misvcom** [comment]
Same problem here ，but there is no pom.xml in the release package.

**Comment by xingfudeshi** [comment]
@misvcom @publisherfk @mostcool @warrior2005 please make sure you have initialized the configs in nacos.please use
`sh nacos-config.sh localhost `
to initialize the configs in Nacos.
If you are using Seata for the first time, it is recommended that you use the file-based registry and configuration center directly.

**Comment by mostcool** [comment]
> @misvcom @publisherfk @mostcool @warrior2005 please make sure you have initialized the configs in nacos.please use
> `sh nacos-config.sh localhost `
> to initialize the configs in Nacos.
> For quick start of seata, it is recommended that you use the file-based registry and configuration center directly.

Why not provide .bat file?

**Comment by warrior2005** [comment]
> @misvcom @publisherfk @mostcool @warrior2005 please make sure you have initialized the configs in nacos.please use
> `sh nacos-config.sh localhost `
> to initialize the configs in Nacos.
> For quick start of seata, it is recommended that you use the file-based registry and configuration center directly.

However, it was not mentioned in the "Quick Start" page.

**Comment by xingfudeshi** [comment]
sorry for lack of documentation.if you use file based registry and configuration,everything should be fine.

**Comment by xingfudeshi** [comment]
> > Manually add seata-config-naco dependency to the pom.xml
> 
> Same problem here.
> @zhangthen What did you mean by add a dependency? There is no pom.xml in the **release** package.

@zhangthen means if you use nacos as your configuration center，then you have to add seata-config-nacos in your application's pom.xml (if you manage your dependency by maven).not add any thing in the seata server side.

**Comment by warrior2005** [comment]
> sorry for lack of documentation.if you use file based registry and configuration,everything should be fine.

Run up on ["seata-samples"](https://github.com/seata/seata-samples) project, thx.

**Comment by yangchenquan** [comment]
1.which project to add dependency  seata-config-naco  (seata-server-0.5.0 or my project  )? i added both but  it not worked.
2.besides i use sh nacos-config.sh localhost to initialized the configs , allows show  "**Failed to connect to localhost port 8848: Connection refused**"  .  should i start some seata-serve first?  
3.Hope to be answered   thanks!

**Comment by mark988** [comment]
https://user-images.githubusercontent.com/22902512/56825915-3f1c2f80-688d-11e9-9620-a80b9e6a62ec.png

**Comment by mark988** [comment]
![1](https://user-images.githubusercontent.com/22902512/56829147-8c9c9a80-6895-11e9-8ac7-6b021a512a36.png)

windows 下执行报错：

**Comment by xingfudeshi** [comment]
@mark988 you have to import the configurations to Nacos before you start seata server.pls refer to https://github.com/seata/seata-workshop

**Comment by yangchenquan** [comment]
------------------ 原始邮件 ------------------
发件人: "mark988"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 凌晨2:24
收件人: "seata/seata"<seata@noreply.github.com>;
抄送: "杨宸权"<524350237@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [seata/seata] how to use seata 0.5.0? (#864)




https://user-images.githubusercontent.com/22902512/56825915-3f1c2f80-688d-11e9-9620-a80b9e6a62ec.png
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.







Thank you very much. I've solved this problem. Instead of using nacos, I changed the type in the registy.conf type="nacos" to type="file". it's worked!

**Comment by lilongthinker** [comment]
i have the same problem, until i change the server from 0.5.0.zip to an application based on the newest code of branch 0.5.0.

i don't know why

all my seata store type is file.(client&server)



~~~
➜  seata git:(95deba8) git status
HEAD detached at 0.5.0
nothing to commit, working tree clean
~~~

**Comment by sanwancoder** [comment]
> ![1](https://user-images.githubusercontent.com/22902512/56829147-8c9c9a80-6895-11e9-8ac7-6b021a512a36.png)
> 
> windows 下执行报错：

和你报一样的错误 windows下 下载 https://github.com/seata/seata/releases/tag/0.5.0 这个server

**Comment by xingfudeshi** [comment]
@sanwancoder please set the value of registry.type and config,type to file.

**Comment by xingfudeshi** [comment]
![image](https://user-images.githubusercontent.com/24457941/57211204-02c99b80-7012-11e9-94d7-b26088a1238a.png)
![image](https://user-images.githubusercontent.com/24457941/57211211-0c530380-7012-11e9-871e-65f0742bfefc.png)

**Comment by sanwancoder** [comment]
> @sanwancoder please set the value of registry.type and config,type to file.

首先谢谢你的回复，一定得在idea下执行吗？

谢谢 我直接下载包的  解压后设置了 依然会报错 

windows下cmd下执行 bat文件
![cmd](https://user-images.githubusercontent.com/10041958/57212107-3528c800-7015-11e9-9c75-ffc82c38bb15.PNG)


![捕获](https://user-images.githubusercontent.com/10041958/57212023-f85cd100-7014-11e9-92c7-1cac0aebfc5a.PNG)

**Comment by sanwancoder** [comment]
> Same problem here ，but there is no pom.xml in the release package.

在下载的release版本中，增加pom.xml可以解决问题吗？

**Comment by sanwancoder** [comment]
使用如下文件registry.conf 即可




registry {
  # file 、nacos 、eureka、redis、zk、consul
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  eureka {
    serviceUrl = "http://localhost:1001/eureka"
    application = "default"
    weight = "1"
  }
  redis {
    serverAddr = "localhost:6379"
    db = "0"
  }
  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
  }
  file {
    name = "file.conf"
  }
}

config {
  # file、nacos 、apollo、zk
  type = "file"

  nacos {
    serverAddr = "localhost"
    namespace = "public"
    cluster = "default"
  }
  apollo {
    app.id = "seata-server"
    apollo.meta = "http://192.168.1.204:8801"
  }
  zk {
    serverAddr = "127.0.0.1:2181"
    session.timeout = 6000
    connect.timeout = 2000
  }
  file {
    name = "file.conf"
  }
}

**Comment by sanwancoder** [comment]
> @sanwancoder please set the value of registry.type and config,type to file.

thank u

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!
