### ISSUE TITLE
New RPC protocol propose.

### ISSUE THREAD

**Issue by ujjboy** [seata/seata#893]
## Why you need it?

graph from #823
```
 * 0     1     2     3     4           6           8          10           12          14         16
 * +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
 * |   0xdada  |   flag    | typecode/ |                 requestid                     |           |
 * |           |           | bodylength|                                               |           |
 * +-----------+-----------+-----------+-----------+-----------+-----------+-----------+           +
 * |                                    ... ...                                                    |
 * +                                                                                               +
 * |                                     body                                                      |
 * +                                                                                               +
 * |                                    ... ...                                                    |
 * +-----------------------------------------------------------------------------------------------+
 *
```
I reviewed the rpc protocol in the current project. There are three places I think need improvement. 
- HEAD part missing
- body length is `short`, and the RequestId `int` is enough.
- missing serialization type.

 I noticed that @leizhiyuan  was writing a compatibility plan that solved the serialization type problem. But if we transparently pass some baggage in RPC (such as Tracer contexts), the current protocol is powerless, especially the head part. so I suggested redesigning a protocol before we release v1.0.

## How it could be?

- Redesigning a new rpc protocol.
- Use the new magic code (not `0xdadb`) to distinguish the different version.
- Add HEAD part.

 **If everyone thinks this is OK, I will carry out this part of the design.**

**Comment by CoffeeLatte007** [comment]
1.short is not enough , because lock key will be large.
2.we need compress to improve transport performance.
3.Can you introduce   the more function of HEAD part?
4.Now there are two people doing this, I suggest you to discuss with @leizhiyuan

**Comment by slievrly** [comment]
@ujjboy Suggest read MessageCodecHandler，`body length` not use ,currently just as typecode.

**Comment by ujjboy** [comment]
@slievrly  OK. I read it first.

**Comment by ujjboy** [comment]
@slievrly @zhangthen @leizhiyuan @CoffeeLatte007   Here is new rpc protocol design, please review it.

```
0     1     2     3     4     5     6           8          10           12          14         16
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|   magic   |Proto|     Full length       |    Head   | Msg |Seria|Compr|     RequestId         |
|   code    |colVer|    （head+body)      |   Length  |Type |lizer|ess  |                       |
+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
|    type   |                                                                                   |
|    code   |                       Head Map [Optional]                                         |
+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
|                                                                                               |
|                                         body                                                  |
|                                                                                               |
|                                        ... ...                                                |
+-----------------------------------------------------------------------------------------------+
```

| Len | Param             | Desc                                               | Desc in chinese                                        |
| --- | ----------------- | -------------------------------------------------- | ------------------------------------------------------ |
| 2B  | Magic Code        | 0xdada                                             | 魔术位                                                 |
| 1B  | ProtocolVersion   | 1                                                  | 协议版本：用于非兼容性升级                             |
| 4B  | FullLength        | not include front 3 bytes, include self 4 bytes    | 总长度 ：用于拆包，不包括前3位，包括自己4位            |
| 2B  | HeadLength        | not include front 7 bytes, include self 4 bytes    | 头部长度：不包括前面7位，包括自己4位                   |
| 1B  | Message type      | request(oneway/twoway)/response/heartbeat/callback | 消息类型：请求（单向/双向）/响应/心跳/回调/go away等   |
| 1B  | Serialization     | custom, hessian, pb                                | 序列化类型：内置/hessian/protobuf等                    |
| 1B  | CompressType      | None/gzip/snappy...                                | 压缩算法：无/gzip/snappy                               |
| 4B  | MessageId         | Integer                                            | 消息 Id                                                |
| 2B  | TypeCode             | code in AbstractMessage                     | 消息类型: AbstractMessage 里的类型                     |
| ?B | HeadMap[Optional] | if head length > 12                                | 消息Map（可选的，如果头部长度大于12，代表存在HeadMap） |
|     |    | ATTR_KEY(？B)  key:string:length(2B)+data <br>       ATTR_TYPE(1B) 1:int; 2:string; 3:byte; 4:short<br>       ATTR_VAL(?B)  int:(4B); string:length(2B)+data; byte:(1B); short:(2B)<br>     } |    Key: 字符串<br> Value 类型<br>Value 值<br>|
| ?b  | Body              | (FullLength-HeadLength)                            | 请求体:长度为总长度-头长度                             |


There is one more question:
- Is the `head map` need to restrict users to only use `Map<String, String>`? this determines the serialization of the head map.

**Comment by CoffeeLatte007** [comment]
> @slievrly @zhangthen @leizhiyuan @CoffeeLatte007 Here is new rpc protocol design, please review it.
> 
> ```
> 0     1     2     3     4     5     6           8          10           12          14         16
> +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
> |   magic   |Proto|     Full length       |    Head   | Msg |Seria|Compr|     RequestId         |
> |   code    |colVer|    （head+body)      |   Length  |Type |lizer|ess  |                       |
> +-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
> |    type   |                                                                                   |
> |    code   |                       Head Map [Optional]                                         |
> +-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
> |                                                                                               |
> |                                         body                                                  |
> |                                                                                               |
> |                                        ... ...                                                |
> +-----------------------------------------------------------------------------------------------+
> ```
> 
> Len	Param	Desc	Desc in chinese
> 2B	Magic Code	0xdada	魔术位
> 1B	ProtocolVersion	1	协议版本：用于非兼容性升级
> 4B	FullLength	not include front 3 bytes, include self 4 bytes	总长度 ：用于拆包，不包括前3位，包括自己4位
> 2B	HeadLength	not include front 7 bytes, include self 4 bytes	头部长度：不包括前面7位，包括自己4位
> 1B	Message type	request(oneway/twoway)/response/heartbeat/callback	消息类型：请求（单向/双向）/响应/心跳/回调/go away等
> 1B	Serialization	custom, hessian, pb	序列化类型：内置/hessian/protobuf等
> 1B	CompressType	None/gzip/snappy...	压缩算法：无/gzip/snappy
> 4B	MessageId	Integer	消息 Id
> 2B	TypeCode	code in AbstractMessage	消息类型: AbstractMessage 里的类型
> ?B	HeadMap[Optional]	if head length > 12	消息Map（可选的，如果头部长度大于12，代表存在HeadMap）
> ATTR_KEY(？B) key:string:length(2B)+data 
> ATTR_TYPE(1B) 1:int; 2:string; 3:byte; 4:short
> ATTR_VAL(?B) int:(4B); string:length(2B)+data; byte:(1B); short:(2B)
> }	Key: 字符串
> Value 类型
> Value 值
> ?b	Body	(FullLength-HeadLength)	请求体:长度为总长度-头长度
> There is one more question:
> 
> * Is the `head map` need to restrict users to only use `Map<String, String>`? this determines the serialization of the head map.

Whether attachment can be supported as Dubbo?

**Comment by zhangthen** [comment]
>  Head Map [Optional]

Is the  tracing id put in the ’header map‘  ？

**Comment by ujjboy** [comment]
@CoffeeLatte007    Yes, we can transmit attachments in head map.  

But this protocol is different with`Dubbo` protocol.   `dubbo` protocol has no head part and transmits attachments through the body part.

**Comment by ujjboy** [comment]
> > Head Map [Optional]
> 
> Is the tracing id put in the ’header map‘ ？

@zhangthen Yes.  any attachments with a total size < 64K.

**Comment by zhangthen** [comment]
> type   |                                                                                   |
> |    code

The ’type code ‘ only be used by seata-diyx codec, and the protobuf codec don't use it, so is it necessary to put 'type code' in header?

**Comment by ujjboy** [comment]
@zhangthen now `protobuf` also need to send the class name for deserializing.  

seata-diy: `BranchCommitRequest -> **type code(4)** -> BranchCommitRequest`

pb: `BranchCommitRequest --convert--> BranchCommitRequestProto -> **classname(io.seata.codec.protobuf.generated.BranchTypeProto)** -> BranchCommitRequestProto --convert-->BranchCommitRequest`

maybe in protobuf, we can also use type code, too.

pb: `BranchCommitRequest --convert--> BranchCommitRequestProto -> **type code(4)** -> 
 -> BranchCommitRequestProto --convert-->BranchCommitRequest`

**Comment by zhangthen** [comment]
> @zhangthen now `protobuf` also need to send the class name for deserializing.
> 
> seata-diy: `BranchCommitRequest -> **type code(4)** -> BranchCommitRequest`
> 
> pb: `BranchCommitRequest --convert--> BranchCommitRequestProto -> **classname(io.seata.codec.protobuf.generated.BranchTypeProto)** -> BranchCommitRequestProto --convert-->BranchCommitRequest`
> 
> maybe in protobuf, we can also use type code, too.
> 
> pb: `BranchCommitRequest --convert--> BranchCommitRequestProto -> **type code(4)** -> -> BranchCommitRequestProto --convert-->BranchCommitRequest`

Whether the 'type code' of seata-diy codec and the 'class name' of protobuf codec can be considered as business data both?  
Maybe they can be placed in the body, which be managed by the codecs themselves.

**Comment by slievrly** [comment]
It is recommended to set the messageId to 8B.

**Comment by slievrly** [comment]
ProtocolVersion+Message type=1B, Serialization+ CompressType=1B, MessageId->UnsignedInterger
