### ISSUE TITLE
Can you integrate conf files into spring boot?

### ISSUE THREAD

**Issue by Python-IBM** [seata/seata#897]
## Why you need it?

If I want to use Seata in my project, I need to copy file. conf and registry. conf into the project. I can't configure the group name, host IP and port flexibly.

## How it could be?

I hope the project does not depend on file. It can configure the Seata service's group name, host id, and port through spring boot.

**Comment by xingfudeshi** [comment]
do you mean something like seata-spring-boot-starter?

**Comment by Python-IBM** [comment]
> do you mean something like seata-spring-boot-starter?

Yes, that's exactly what it means.
such as yml:
seata:
     server:
        group: demo-tx-group
        addr: localhost:8091
        nacos-addr: localhost:8092

**Comment by xingfudeshi** [comment]
After all main features were developed,we will do that.
