### ISSUE TITLE
Can @Transactional non-global transactions be supported?

### ISSUE THREAD

**Issue by Python-IBM** [seata/seata#898]
## Why you need it?
Sometimes a service call has only one transaction, not a global transaction. I just want to use spring's annotation @Transactional, but Seata does not support it.

## How it could be?
I want to use Spring's annotation @Transactional when I'm not using @Global Transactional.

**Comment by slievrly** [comment]
if use  @transactional，what is the problem reported?

**Comment by slievrly** [comment]
@Python-IBM

**Comment by Python-IBM** [comment]
> @transactional

I use @transactional with no transaction rollback

**Comment by Python-IBM** [comment]
> if use @transactional，what is the problem reported?

Transactions do not roll back

**Comment by slievrly** [comment]
@Python-IBM just only use `@Transactional`,it not work?

**Comment by huinew** [comment]
> > if use @transactional，what is the problem reported?
> 
> Transactions do not roll back
 may be you should paste your error info here.
if you are using @transctional only, then you're only using the spring transcatioin and dataSource manager,maybe you should check your dataSourceConfig and dataSourceProxy, don't proxy by seata-rm-dataSource

**Comment by Python-IBM** [comment]
> may be you should paste your error info here.
> if you are using @transctional only, then you're only using the spring transcatioin and dataSource manager,maybe you should check your dataSourceConfig and dataSourceProxy, and get rid of seata-rm-dataproxy

But I want to use @Global Transactional for global transactions as well as @transctional for individual transactions. What should I do?

**Comment by huinew** [comment]
> But I want to use @global Transactional for global transactions as well as @transctional for individual transactions. What should I do?

just use one of them, there is no need to use both. Otherwise there is 2 transactional manager and it goes false.

**Comment by Python-IBM** [comment]
> > But I want to use @global Transactional for global transactions as well as @transctional for individual transactions. What should I do?
> 
> just use one of them, there is no need to use both. Otherwise there is 2 transactional manager and it goes false.

OK, I understand. Thank you. So I can use @Global Transactional instead of Spring's @Transactional only for single transactions, right?

**Comment by zhenjing** [comment]
if use @globalTransactional and Spring's @transactional (with @GlobalLock) for single transactions in the same project, Can I use them together?

If @globalTransactional call Spring's @transactional method what happen?
