### ISSUE TITLE
What scene is LockManager used in?

### ISSUE THREAD

**Issue by chenld** [seata/seata#90]
在数据库本地隔离级别 读已提交 或以上的前提下，Fescar 设计了由事务协调器维护的 全局写排他锁，来保证事务间的 写隔离，将全局事务默认定义在 读未提交 的隔离级别上。
  ------这句话怎么理解分布式事务隔离呀？采用主键排它锁，还是不明白这个场景?

**Comment by sharajava** [comment]
Datas in Fescar always have two locks: a local one and a global one.
Before a Fescar global transaction commit a update on data, it much has got both two locks.
Local lock is managed by local transaction. The local lock is released when branch transaction is committed. However, the global lock will just be held until global transaction is done to protect the data updated in the global transaction.

Hope this can help you: https://www.jianshu.com/p/4cb127b737cf

**Comment by chenld** [comment]
@sharajava  thanks!

**Comment by leizhiyuan** [comment]
It seems ok for you, I will close the issue, if you have other questions, please reopen it or create a new one, thanks
