### ISSUE TITLE
Provide an all-in-one package for easier usage.

### ISSUE THREAD

**Issue by ujjboy** [seata/seata#914]
## Why you need it?
Now, we need to add multiple dependencies for use seata. Such as:

```
seata-common
seata-core
seata-config-all
seata-tcc
seata-rm
...
```
We can provide an all-in-one package that is easier for developers to use.

## How it could be?
- add `all` module
- use maven-shade-plugin for package

**Comment by slievrly** [comment]
it will be provided `all` and `bom` packages.
