### ISSUE TITLE
Why is this project named seata?

### ISSUE THREAD

**Issue by sanwancoder** [seata/seata#919]
I am curious about the name of this project.

Looking forward to reply

**Comment by ujjboy** [comment]
@sanwancoder You can get it in [README.md](https://github.com/seata/seata/blob/develop/README.md)

**Comment by xingfudeshi** [comment]
Seata: Simple Extensible Autonomous Transaction Architecture

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!
