### ISSUE TITLE
Unable to register to the custom namespace by nacos

### ISSUE THREAD

**Issue by wowtrxqn** [seata/seata#926]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Unable to register to the custom namespace by nacos，all registered are “Public” default namespace

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen
want to assign to my custom namespace

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : windows 10
- Others: nacos-server:1.0.0  seata-server:0.5.0

**Comment by slievrly** [comment]
it will be fix on 0.6.0

**Comment by wowtrxqn** [comment]
> it will be fix on 0.6.0

thks，got it

**Comment by xingfudeshi** [comment]
mark

**Comment by slievrly** [comment]
fixed on 0.9.0
