### ISSUE TITLE
Tidy the maven dependency 

### ISSUE THREAD

**Issue by lovepoem** [seata/seata#933]
## Why you need it?

Now the jar dependency have some confusion.

## How it could be?
 
Tidy the maven dependency ：

1、Unify the version of `netty`  
2、Remove guava ，use [caffine](https://github.com/ben-manes/caffeine) to instead of guava cache
3、Remove other useless jars
4、Upgrade junit4 to [junit5](https://junit.org/junit5/docs/current/user-guide)
5、Remove testng

**Comment by slievrly** [comment]
add 
1. Unify  spring framework, httpClient
2. nacos->1.0

**Comment by lovepoem** [comment]
close via https://github.com/seata/seata/pull/981
