### ISSUE TITLE
about mybatis auto_increment Id can't return right value BUG

### ISSUE THREAD

**Issue by vikenlove** [seata/seata#934]
`	UserModel record = new UserModel();
		record.setName(name);
		record.setAge(age);
		int count =  userModelMapper.insertSelective(record);
		System.out.println("我這次下這個ID----"+record.getId()+"--------------");`

mybatis run insert SQL after run SELECT LAST_INSERT_ID(), but  
`  sqlRecognizer = SQLVisitorFactory.get(
                statementProxy.getTargetSQL(),
                statementProxy.getConnectionProxy().getDbType());`
ast instanceof SQLSelectStatement is SELECT , it is not for upldate 
![图片](https://user-images.githubusercontent.com/2834207/56862815-7f8cc200-69e1-11e9-8c2f-b178c5f8a10f.png)

 。then  the sqlRecognizer is null ,so it will be run 
`  executor = new PlainExecutor<T, S>(statementProxy, statementCallback);`
so the SELECT LAST_INSERT_ID() SQL return value is undolog ID.
![图片](https://user-images.githubusercontent.com/2834207/56862761-08efc480-69e1-11e9-9395-9bf6eb7fe3f0.png)

**Comment by xingfudeshi** [comment]
it will be great if you can submit a PR to fix it.thanks.

**Comment by vikenlove** [comment]
@xingfudeshi i will try to fixed it ,but i don't konow how to fixed it  and i think i will create SelectExcutor to solve it 。

**Comment by vikenlove** [comment]
@xingfudeshi the bug come from mybatis generator  and SQL XML mapping is 
`<insert id="insertSelective" parameterType="com.emerging.service.persistence.model.UserModel">
    
    <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
      SELECT LAST_INSERT_ID()
    </selectKey>
    insert into t_user
    <trim prefix="(" suffix=")" suffixOverrides=",">
      <if test="name != null">
        name,
      </if>
      <if test="age != null">
        age,
      </if>
      <if test="type != null">
        type,
      </if>
      <if test="createDate != null">
        create_date,
      </if>
    </trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
      <if test="name != null">
        #{name,jdbcType=VARCHAR},
      </if>
      <if test="age != null">
        #{age,jdbcType=INTEGER},
      </if>
      <if test="type != null">
        #{type,jdbcType=VARCHAR},
      </if>
      <if test="createDate != null">
        #{createDate,jdbcType=TIMESTAMP},
      </if>
    </trim>
  </insert>`

**Comment by xingfudeshi** [comment]
add the following code to the insert tag.and remove selectKey tag.then try it.
useGeneratedKeys="true" keyProperty="id"

**Comment by vikenlove** [comment]
@xingfudeshi  i was removed selectKey ,and add useGeneratedKeys="true" keyProperty="id" after the problem was soluted。but  selectkey code  is generate by mybatis generator plugin。 so  I think  seata should be match  SQL XML by mybatis generator plugin。Should i add a MySQLSelectRecognizer to solve it ?

**Comment by xingfudeshi** [comment]
Yes.you can just do it,then see how it would be.in addition,i think "SELECT LAST_INSERT_ID() AS value" is not the best way to get the key id.because it may returns the key id from another table in high concurrent scenario.and the Selectkey tag was designed for non-autoincrement primary key database,like  Oracle.

**Comment by vikenlove** [comment]
@xingfudeshi  thanks  so much

**Comment by Empty66** [comment]
mybatis和tkmybatis这个bug可以有配置方案，已验证
See [/issues/1257]
