### ISSUE TITLE
SEATA supports Saga mode distributed transactions

### ISSUE THREAD

**Issue by long187** [seata/seata#937]
Saga mode uses the compensation mechanism to achieve the final consistency of distributed transactions. It has the advantages of no lock, asynchronous execution, high performance, and easy implementation of business services. It is widely used in financial institutions such as banks. Currently, we have a implementation based on Saga theory in Ant Financial, and there are business scenarios used internally. We hope to contribute to the SEATA community.

Our implementation is composed of two parts: client and server.  The client has two forms of expression. One is to orchestrate business processes with state machines. Each node on the state machine is executing business logic (or service), each node can define its compensation node，control execution and transaction rollback by state machine; Another form is Java annotation, which uses annotations to define a method for its compensation. The framework rolls back the transaction according to the compensation definition when an exception occurs. The server will continuously asks the client whether there is a business process that has not been successfully executed or has not been rolled back successfully, and continuously sends a retry or rollback command. In extreme cases, if process cannot retry or roll back successfully, we can manually handle it by alarm notification.

**Comment by zhangthen** [comment]
Look forward to Saga.

**Comment by hehedahehe** [comment]
is there a opening source plan for saga mode? cause i do not find "saga" in the source code...

**Comment by long187** [comment]
version 1.0.0
