### ISSUE TITLE
why failed branchSession has no influence on the globalSession?

### ISSUE THREAD

**Issue by nexxxxxxx** [seata/seata#948]
![](https://ae01.alicdn.com/kf/HTB1JdqUTCzqK1RjSZFLq6An2XXa8.jpg)

just like the picture, even thought there exists some failed branchSessions, but the whole globalSession will not roll back 
I mean transaction has to be atomic, which means the whole process has to roll back when error occurs in one of the steps

so these codes confused me

**Comment by xingfudeshi** [comment]
In a global transaction, if the branch transaction executes successfully, it can commit directly; if it fails, it can rollback directly. Finally, the compensation is made according to the execution result to achieve the final consistency.

**Comment by nexxxxxxx** [comment]
> In a global transaction, if the branch transaction executes successfully, it can commit directly; if it fails, it can rollback directly. Finally, the compensation is made according to the execution result to achieve the final consistency.

appreciate your reply, but I still confused about this case
as you said, if the branch transaction executes successfully, it can commit directly; if it fails, it can rollback directly. 
if branch failed, then the whole global transaction must fail, which required by so-called "atomic"
but in seata, although a branch failed, the global transaction can still commit.

I can't understand why seata can endure failed branch

**Comment by xingfudeshi** [comment]
In the execution of branch transaction, seata will parse the SQL statement and execute before image and after image on the data involved. If the global transaction ultimately needs rollback, it will compensate according to the snapshot information to achieve the final consistency.

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!
