### ISSUE TITLE
After the transaction is committed, during the rollback process, the data is changed by other write operations, and all the intermediate changes are lost.

### ISSUE THREAD

**Issue by SpringRen** [seata/seata#95]
For example, in the example:
// 比如示例中：
` @override
@GlobalTransactional(timeoutMills = 300000, name = "dubbo-demo-tx")
public void purchase(String userId, String commodityCode, int orderCount) throws Exception {
storageService.deduct(commodityCode, orderCount);
orderService.create(userId, commodityCode, orderCount);

} `
orderService.create(userId, commodityCode, orderCount);, add a breakpoint here.
// orderService.create(userId, commodityCode, orderCount);，此处加入断点。
After storageService.deduct successfully performs deduction of inventory, manually modify the inventory in the database.
// storageService.deduct成功执行扣减库存后，手动修改数据库中库存。
Then a rollback occurs in the orderService.create execution.
// 然后orderService.create执行中产生了回滚。
Data that causes manual modifications or intermediate process modifications will be lost.
// 会导致手动修改或者中间过程修改的数据会丢失。
What do you think about this?
// 对于这一点，大家怎么看？

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by winflex** [comment]
试了一下，你说的这种情况是会出现的，看代码上好像没有给数据上锁的操作，不知道是不是还没做？

**Comment by skyesx** [comment]
the problem exists, maybe it's just the design for efficiency，add GlobalTransaction sign can avoid this
//存在这个问题，或许因为效率而设计如此，可以加上全局事务标志来避免这种情况出现

in my opinion, when global transaction rollback, should check and alert in the record modified status
//但个人觉得但回滚事务时，应该用更新后的镜像检测一遍，如果不一致应该报错会更好

**Comment by SpringRen** [comment]
所以更新操作的回滚过程，是使用操作前备份的数据直接覆盖的，中间其他操作产生的数据都会被覆盖掉。对于这个问题，如果想要生产使用，需要从哪些方面去避免呢？

**Comment by leizhiyuan** [comment]
please use the latest version . If you have other questions, please reopen it.
