### ISSUE TITLE
What is the main difference between Seata and DTX versions?

### ISSUE THREAD

**Issue by githubyangxd** [seata/seata#950]
Seata版本开源的免费  DTX产品是收费的，想了解下主要的区别是什么，开源版本是否可以实现分布式事务，谢谢

**Comment by xingfudeshi** [comment]
Seata itself is a distributed transaction middleware. It is used to deal with distributed transactions.

**Comment by githubyangxd** [comment]
> 
> 
> Seata itself is a distributed transaction middleware. It is used to deal with distributed transactions.

you said i know, i want to know the differents!!

**Comment by zhangthen** [comment]
@githubyangxd  Seata is an open source version of DTX, and their main functions are almost the same.

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!
