### ISSUE TITLE
Currently,the seata does not support data batch processing

### ISSUE THREAD

**Issue by romeoblog** [seata/seata#962]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

Currently,the seata does not support data batch processing.We hope to support this feature.The current seata version is 0.50

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
![image](https://user-images.githubusercontent.com/18193426/56967417-b9052f00-6b93-11e9-84da-5eececb25bed.png)

**Comment by romeoblog** [comment]
There is also a case where batch execution is unsuccessful when the dataSource is the Sease proxy and the business layer is not  @GlobalTransactional annotation.

**Comment by StrangeYear** [comment]
I also have this problem.Hope to be fix

**Comment by iapplejohn** [comment]
> There is also a case where batch execution is unsuccessful when the dataSource is the Sease proxy and the business layer is not @GlobalTransactional annotation.

I have created a pull request: https://github.com/seata/seata/pull/1265

**Comment by romeoblog** [comment]
> > There is also a case where batch execution is unsuccessful when the dataSource is the Sease proxy and the business layer is not @GlobalTransactional annotation.
> 
> I have created a pull request: #1265

Thank you very much
