### ISSUE TITLE
use support?

### ISSUE THREAD

**Issue by jimmycheng888** [seata/seata#963]
**## How it could be?**
 Is your feature request related to a problem? Please describe in details
1.Can support the database PostgreSQL?
2. Does the current version support TCC?
3. seata and tcc-transaction, LCN, ByteTCC, Himly, EasyTransaction performance Which is better?
4.Whether to support docker environment deployment
5.Can it be used for large-scale applications?
6.Can it be integrated with third-party database sharding tools such as myCat, shardingsphere.

**Comment by xingfudeshi** [comment]
1.we have plan to support postgreSQL.
2.already supported
3.i can't say our seata is better.it depends on the actual business scenarios.
4.yes
5.yes.seata was designed for large-scale application.But the cluster-related functionality is still in development.
6.In theory, it should be possible, but practice is needed. In fact, distributed transaction is irrelevant to sharding.

**Comment by xingfudeshi** [comment]
I will close this issue,if you have further question about this issue,please comment here.thank you!
