### ISSUE TITLE
SQLInListExpr cannot be cast to SQLBinaryOpExpr

### ISSUE THREAD

**Issue by pgm-rookie** [seata/seata#971]
mybatis mysql中update时，使用了mybatis的foreach语句拼接sql中的in语句，会报错com.alibaba.druid.sql.ast.expr.SQLInListExpr cannot be cast to com.alibaba.druid.sql.ast.expr.SQLBinaryOpExpr。
查看seata-rm-datasource-0.5.1中的源码，发现了强转代码：visitor.visit((SQLBinaryOpExpr)where);
这里应该是个bug

**Comment by hongweiyi** [comment]
same issue #867 
fixed in #965

**Comment by xuanbingcheng** [comment]
you can add a condition after where "1=1 and id in ()"
