### ISSUE TITLE
buffer size is hard-code as 1K, which cannot support bulk update cases

### ISSUE THREAD

**Issue by bbcpan** [seata/seata#976]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
buffer size is hard-code as 1K, which cannot support bulk update cases

### Ⅱ. Describe what happened
when use update statements for bulk records in on local transaction 

  If there is an exception, please attach the exception trace:
![image](https://user-images.githubusercontent.com/22337047/57206421-2849ab80-6ff8-11e9-921f-f75348a8bc33.png)

Just paste your stack trace here!
```
![image](https://user-images.githubusercontent.com/22337047/57206428-313a7d00-6ff8-11e9-80f3-dafeba691035.png)



### Ⅲ. Describe what you expected to happen


### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?


### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by xingfudeshi** [comment]
Could you.submit a PR to improve this?thanks.
