### ISSUE TITLE
Enable checkstyle plugin run in travis CI

### ISSUE THREAD

**Issue by lovepoem** [seata/seata#985]
## Why you need it?
Enable checkstyle plugin run in travis CI 

## How it could be?
1、Open the check switch : change `script` in `seata/.travis.yml` , add `-Dcheckstyle.skip=false` at  the end of the script
2、Modify the code style error following the rule of  [p3c](https://github.com/alibaba/p3c), that will be a hard work

## Other related information
none

**Comment by leizhiyuan** [comment]
https://github.com/seata/seata/pull/802

**Comment by lovepoem** [comment]
What I mean is to unify the code style.
But now I find that the config of `maven-checkstyle-plugin` is :
```
<consoleOutput>true</consoleOutput>
<failsOnError>false</failsOnError>
<failOnViolation>false</failOnViolation>
```
So when the code style occur error , it will only print error result on the console , but can't break the CI.

**Comment by leizhiyuan** [comment]
yes, we need to open this feature, and modify the code style.
