### ISSUE TITLE
Does it supports distributed transactions with DRDS

### ISSUE THREAD

**Issue by liaow** [seata/seata#990]
## Why you need it?
Hi, our team is using the DRDS(Distributed Relational Database Service of Aliyun) database in microservices architecture.I want to find out if it supports distributed transactions with DRDS?

## How it could be?
because some tables are designed into many sub-tables, which require cross-database transaction support when doing distributed transactions.

1.  sample table structure of `t_order`
```sql
CREATE TABLE `t_order ` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `merchant_id` varchar(10) NOT NULL,
  `customer_id` varchar(10) NOT NULL,
 ....
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8  dbpartition by hash(`customer_id`);
```
2.  another sample table partition structure of `t_order_merchant`, which is very similar to `t_order` with a different dbpartition key.
```sql
CREATE TABLE `t_order_merchant ` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `merchant_id` varchar(10) NOT NULL,
  `customer_id` varchar(10) NOT NULL,
 ....
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8  dbpartition by hash(`merchant_id`);
```

**Comment by junlei-lv** [comment]
does it  Support DRDS?

**Comment by liaow** [comment]
> does it Support DRDS?

doesn't yet support. GTS supported
